### ISSUE TITLE
doesn't recognize the clip-vision pytorch_model.bin from my installation 

### ISSUE THREAD

**Issue by tekakutli** [Acly/krita-ai-diffusion#1]
downloaded it again from here just in case, still nothing

https://huggingface.co/h94/IP-Adapter/blob/main/models/image_encoder/pytorch_model.bin

using linux, default port
message:
```
Error: Could not find CLIPVision model SD1.5/pytorch_model.bin. Make sure to download the model and place it in the [ComfyUI]/models/clip_vision folder.
```

**Comment by tekakutli** [comment]
solved it, had to put it inside a directory named SD1.5
so the correct location is
./ComfyUI/models/clip_vision/SD1.5/

**Comment by Acly** [comment]
Yes unfortunately the original model name is very generic, so I kept the subfolder (I think ComfyUI Manager also puts it there).

The error message has the folder stuck to the filename, which is not ideal, I can probably fix that.

**Comment by MackNcD** [comment]
> Yes unfortunately the original model name is very generic, so I kept the subfolder (I think ComfyUI Manager also puts it there).
> 
> The error message has the folder stuck to the filename, which is not ideal, I can probably fix that.

I'm having the same issue, the new versions of comfy run the .safetensors version -- we're in the future now and we can not have to take any risks leaving backdoors open! Upgrade it so that everyone can use .safetensors for clipvision please! :)

**Comment by Acly** [comment]
Why comment on months old issue then? safetensors version has been supported since a few versions back, see #54
