### ISSUE TITLE
Bug: layers in a group cannot be selected as controlnet input

### ISSUE THREAD

**Issue by gergelyszaz** [Acly/krita-ai-diffusion#10]
Only top level layers can be selected for controlnet use.
The list is not automatically updated when new layers are added or removed.

**Comment by Acly** [comment]
First issue is easy to fix.

Updating the list automatically is tricky, unfortunately Krita doesn't expose a layer created/deleted event to Python. Currently the list is  updated when some obvious actions are triggered (create layer, remove layer, duplicate) but there are other ways to create layers that won't get picked up.
