### ISSUE TITLE
IPAdapter issue when using inpaint at 100% strength

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#100]
When using a selection tool to inpaint a part of an image with a strength setting at 100%, I got the following error with SDXL :  

```
  File "F:\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 390, in apply_ipadapter
    self.ipadapter = IPAdapter(
  File "F:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 178, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
        size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 768]).
```

With SD 1.5 models, same traceback but the dimension is different : 

```
size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
```

If I set the strength to anything lower than 100%, it's working, albeit without IPAdapter.

I'm using a local installation of ComfyUI, updated to the latest version at the moment of this post (2023-11-22), same for IPAdapter plus custom node.

**Comment by Acly** [comment]
This error message is listed as [common issue](https://github.com/cubiq/ComfyUI_IPAdapter_plus#troubleshooting) in the ip-adapter repo when the clip-vision and ip-adapter models don't match.
See [comfyui requirements](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md) for the exact model expected by the plugin. It also has hints how to check logs for which file is used.

**Comment by Danamir** [comment]
Good call ! It was a problem of clip-vision model. I was using `models/clip_vision/clip-vision-sd1.5.safetensors` for my own SD1.5 and SDXL IPAdapter workflows. But the plugin was using  `models/clip_vision/SD1.5/model.safetensors` which seems to have been previously downloaded by ComfyUI and had the wrong size (1.6GB).

I created a symbolic link of to the correct clip-vision model, and everything works fine now.

Thanks, keep up the good work !
