### ISSUE TITLE
Generated imaged 'burned' when using the selection tool with seamless.

### ISSUE THREAD

**Issue by LilSodium** [Acly/krita-ai-diffusion#1002]
Hello, for some reason whenever I use the selection tool with seamless on, the result just looks like a cursed mess.
![image](https://github.com/user-attachments/assets/6a2657b2-3122-4d4e-a77d-7b560fa2b538). 

However when seamless is off it, it looks mostly normal:
![image](https://github.com/user-attachments/assets/902484e1-ee1f-416f-9b8d-e4ca811550b9)

Any ideas why this is?

Thanks.

**Comment by Acly** [comment]
If you're using a custom checkpoint, it may not be compatible with the inpaint model. Typical SDXL checkpoints are all compatible, but eg. Pony derivatives are too different.
