### ISSUE TITLE
Error Upgrade 1.21.0 Failed

### ISSUE THREAD

**Issue by SyamsQ** [Acly/krita-ai-diffusion#1004]
Can all upgrade files be downloaded and installed manually? I have tried several times, the latest upgrade always fails.

Your guidance please.

![image](https://github.com/user-attachments/assets/f368b087-8e65-47a0-9117-a9a920cb4abf)
![image](https://github.com/user-attachments/assets/741568d0-9eb4-492b-bac7-32266228c457)

**Comment by cguijarro2** [comment]
I had this same problem when trying to install version 1.21.0 from the previous version 1.18.0. I solved the problem by installing successive versions from 1.18 to 1.20, version 1.21.0 was installed as an update without any error message.

**Comment by Acly** [comment]
It may have just been a sporadic internet connection issue.

Technically all files required for installation can be downloaded separately via browser, and then installed locally. You need to know how to setup the python environment, download wheel files and use pip to install them.
