### ISSUE TITLE
Add ComfyUI-IF_AI_tools for krita ai diffusion?

### ISSUE THREAD

**Issue by syl1130** [Acly/krita-ai-diffusion#1007]
Hello Acly @Acly ,

Can you add ComfyUI-IF_AI_tools for krita ai diffusion? 

Users can use IF Chat Prompt to enrich and optimize professional and detailed prompt words through short descriptive words, for generating high-quality visual scenes. This greatly simplifies the process for users to write their own descriptive words. Do you have this idea? Thank you for your support.

ComfyUI-IF_AI_tools is a set of custom nodes for ComfyUI that allows you to generate prompts using a local Large Language Model (LLM) via Ollama. This tool enables you to enhance your image generation workflow by leveraging the power of language models. [https://github.com/if-ai/ComfyUI-IF_AI_tools](url)

**Comment by Marksusu** [comment]
这个也可以跟翻译功能结合起来。
有翻译、有风格选择器、有 Ollama……
这个插件会更强大！
