### ISSUE TITLE
Style embeddings question

### ISSUE THREAD

**Issue by lucafoscili** [Acly/krita-ai-diffusion#1010]
Hi, first of all thanks for this awesome tool, it's incredible!
I write here because I found out an odd behavior that I can't explain - maybe I'm missing something, I searched more info about this topic but I didn't find a clear answer.

I'm using a preset that includes an [embedding](https://civitai.com/models/596442/vampire-and-gothic-outfit):
![Screenshot 2024-07-30 091823](https://github.com/user-attachments/assets/c9550fd6-afbb-4c0b-9192-380a06fc60d7)

It seems that with an empty prompt, this embedding is ignored:
![Screenshot 2024-07-30 091721](https://github.com/user-attachments/assets/66063dc6-cf41-4e60-8cb7-22f7bfbd4138)

If I add the trigger word, even without the "embedding:" prefix, it works as intended:
![Screenshot 2024-07-30 091752](https://github.com/user-attachments/assets/a73821f8-8a0b-4312-a3dc-071443b2c3b0)

Is this the intended behavior?
If it is, what's the correct way to attach an embedding in a use-case like this that won't need me to type the trigger word in each prompt (maybe something like "embedding:trigger, trigger" in the positive style prompt)?

Thanks in advance and keep up the amazing work! :)

**Comment by Acly** [comment]
Empty prompt will really pass no prompt to the model at all (no style prompt either). So you don't need a trigger word, just don't leave it empty.

Reason is that empty prompt is quite useful to expand/fill/remove things in the image. But for a typical style prompt "photo", if that was added, you'd get images of photo cameras. Usually not what you want.

**Comment by lucafoscili** [comment]
Oh I see, that makes sense.
Prompting for `triggerw0rd` while also having `embedding:triggerw0rd` in the style is equivalent to `(embedding:triggerw0rd:1.2)` then?

**Comment by Acly** [comment]
I don't think embeddings have tigger words. You write `embedding:name_of_the_embedding_file` and it will add the embedding. Anything you do after isn't related. You can just put `.` into the prompt to make sure the style is used.

**Comment by lucafoscili** [comment]
Got it! Thank you very much for the explanation - closing the issue! :)
