### ISSUE TITLE
Version 1.21 argos-translate error

### ISSUE THREAD

**Issue by syl1130** [Acly/krita-ai-diffusion#1015]
```
!!! Exception during processing!!! Not found: "C:\Users\梁\.local\share\argos-translate\packages\translate-zh_en-1_9\sentencepiece.model": No such file or directory Error #2 

OSError: Not found: "C:\Users\梁\.local\share\argos-translate\packages\translate-zh_en-1_9\sentencepiece.model": No such file or directory Error #2
```
@Acly  The above is the log error of prompt word translation. The translation package files were downloaded normally. I have checked that there is a sentencepiece.model file in the ”C:\Users\梁\.local\share\argos-translate\packages\translate-zh_en-1_9\“ directory.
I guess the error is caused by the Users name is in Chinese name. Please help me check this, thanks

**Comment by Acly** [comment]
I tried with packages located in a path with chinese characters, and it works for me. So that doesn't seem to be the problem? But I also don't have any other idea.

**Comment by syl1130** [comment]
okay, thanks

**Comment by qingzhenbiaojie** [comment]
@syl1130 请问你解决了吗？我也出现同样的错误
