### ISSUE TITLE
Error during server startup - clean install of 1.21.0

### ISSUE THREAD

**Issue by beep-beep-morales** [Acly/krita-ai-diffusion#1017]
Clean install of Windows 11.
Clean install of Krita 5.2.3.
Clean install of krita-ai-diffusion 1.21.0.
Clean install of the packages selected by default in the krita-ai-diffusion docker.

Trying to start the sever results in the following error:

Error during server startup: OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Beep\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\torch\lib\c10.dll" or one of its dependencies. [1]

The file 'c10.dll' is actually in that directory.

Help?

**Comment by Acly** [comment]
Try installing the latest VC redistributable: https://aka.ms/vs/17/release/vc_redist.x64.exe (link is from [microsoft.com](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version))

**Comment by beep-beep-morales** [comment]
That fixed the problem, thank you.
