### ISSUE TITLE
Error: ControlNet model not found for mode ControlMode scribble

### ISSUE THREAD

**Issue by Yinluok99** [Acly/krita-ai-diffusion#1018]
![image](https://github.com/user-attachments/assets/01446dee-a71f-4620-8359-2b99bd0335f7)
I put the model in controlnet file but it still not work...
[diffusion_pytorch_model.safetensors](https://huggingface.co/lllyasviel/sd-controlnet-scribble/blob/main/diffusion_pytorch_model.safetensors)

**Comment by syl1130** [comment]
you can rename the file to control_lora_rank128_v11p_sd15_scribble_fp16.safetensors

the download link is [https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_lora_rank128_v11p_sd15_scribble_fp16.safetensors](url)

**Comment by Yinluok99** [comment]
> you can rename the file to control_lora_rank128_v11p_sd15_scribble_fp16.safetensors
> 
> the download link is https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_lora_rank128_v11p_sd15_scribble_fp16.safetensors
> 
> and 1.21 new version support the [Xinsir Union ControlNet](https://huggingface.co/xinsir/controlnet-union-sdxl-1.0) model for SDXL. It combines many control modes (scribbles, lines, depth, normals, pose, segmentation...) into one model. https://huggingface.co/xinsir/controlnet-union-sdxl-1.0/blob/main/diffusion_pytorch_model_promax.safetensors download and rename to xinsir-controlnet-union-sdxl-1.0-promax.safetensors
> 
> https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup this is more

It does work, thank you!!
