### ISSUE TITLE
"server running - connection error: connection established, but the server is missing one or more stable diffusion checkpoints."

### ISSUE THREAD

**Issue by odarcan** [Acly/krita-ai-diffusion#102]
"server running - connection error: connection established, but the server is missing one or more stable diffusion checkpoints."

I dont know what that means, Im following instructions

**Comment by Acly** [comment]
![ckpt](https://github.com/Acly/krita-ai-diffusion/assets/6485914/ae4bad9a-e514-47ef-9844-05c1986d5ce6)

It's talking about this. You have to install at least one.

**Comment by odarcan** [comment]
thanks it installed 

now when generating something simple it says out of memory
device mem 5.79 gb
used 2.89 gb
requested 600 something mb.

what to do ? there is more memory than needed.

**Comment by odarcan** [comment]
okay! nevermind the image was very large, it sort of works on smaller images. 
Thanks!
