### ISSUE TITLE
Blank generation when using any ControlNet with inpainting

### ISSUE THREAD

**Issue by sfisher** [Acly/krita-ai-diffusion#1020]
- Without adding a ControlNet layer, inpainting works.
- In Live Mode in-painting works.
- When doing in-painting, especially with less than 100% generation ("refinement") strength, it creates black or white blobs and doesn't create the in-painted content.
- When I use in-painting with 100% strength it does create something but it is very pale and seems to only create something in the center of the in-painted area and not the full space.

## Steps to reproduce:

1. Select an area on an image with a selection tool.
2. Move the slider "strength" to less than 100% (try 75% or something).
3. Click + and add a ControlNet layer such as "depth"
4. Click the "Refine" button and you get to see a white or black blob instead of in-painted content.

There are no errors in the ComfyUI output, but it appears that the plugin is not correctly sending the part of the image to be modified, but instead just sends a white or black square (though it seems to send the correct piece of the image to the main image path but not ControlNet).  I'm not sure if it's sometimes the other way around, also, and the main image path receives a black or white square and controlnet gets the good image (?)

## This is what it does when it doesn't in-paint correctly, along with the workflows

It creates a white blob instead of inpainting

![inpainting_w_controlnet01](https://github.com/user-attachments/assets/36cd9f6b-b4e5-4131-9eb5-0c8eb310455b)

ComfyUI does not correctly receive the part of the image for controlnet, but receives white or black square instead, though it seems to be receiving the image for the main path.  I added preview nodes to see what was being passed in.

![inpainting_w_controlnet_workflow01](https://github.com/user-attachments/assets/95b58e4b-2cc5-4dff-ae34-4efdef2b6912)

Output is an ugly blob of white (or black)

![inpainting_w_controlnet_workflow02](https://github.com/user-attachments/assets/ee398907-1bc7-4855-8dbb-911a424d7675)

This is the workflow that the plugin creates and it doesn't work or pass in the correct image (?)

I've verified that I think this is the problem since if I copy and paste the correct base64 encoded image from section with a good image into the white square, then it produces better output.

[man_kite_controlnet_depth.json](https://github.com/user-attachments/files/16462903/man_kite_controlnet_depth.json)

## It works as long as no ControlNet is attached

![inpainting](https://github.com/user-attachments/assets/d4fdc4f9-46a4-40b4-bb91-1de1a1b3ae37)

![normal_inpainting_workflow01](https://github.com/user-attachments/assets/27978261-429f-4a1a-b139-14452e690754)

![normal_inpainting_workflow02](https://github.com/user-attachments/assets/3ca3b412-85ca-4fc3-b306-d1fee67e996f)

[man_kite_no_controlnet.json](https://github.com/user-attachments/files/16462991/man_kite_no_controlnet.json)

## It also seems to work in Live Mode

It passes in two images and one mask correctly in live mode.

![inpainting_w_controlnet_live](https://github.com/user-attachments/assets/2fe5328c-dd6f-4003-9ee5-7e751f0895e9)

![inpainting_w_controlnet_live_workflow01](https://github.com/user-attachments/assets/cff51c47-2134-4b6d-a062-3b4da3376380)

[man_kite_controlnet_depth_live.json](https://github.com/user-attachments/files/16463088/man_kite_controlnet_depth_live.json)

## Things I've tried in order to fix

- Updating the plugin to the latest version
- Already running the latest version of Krita
- Restarting ComfyUI
- Rebooting computer
- Tried many different checkpoints (no difference)
- Looked for errors in the logs, but there are no errors that I can see but it just doesn't seem to work
- I've used depth controlnets on my install of ComfyUI in other workflows and they work fine
- I completely uninstalled krita in Windows and found all the krita folders I could and deleted them and then reinstalled the latest of everything.  This seemed to update some of the menus and things in the plugin and be the latest version but the inpainting problems while using a controlnet still exist outside of Live Mode which works correctly.

**Comment by Acly** [comment]
The reason for the behavior is that you are using your input image also as depth control image. Typically you want to use an actual depth map as control layer. You can generate one from the current image with the sparkly button in the control layer UI.

Generally control images are separate from the actual image, which is why they are automatically hidden before sending to ComfyUI. This allows you to layer them on top (nice for adjusting pose for example) without having them be part of diffusion.

**Comment by sfisher** [comment]
Ok. I gave it a try explicitly generating the control layer first and it worked.  Thanks you.  Feel free to close this issue since I obviously didn't understand how it worked.

It's a little confusing since in automatic1111, it automatically creates a default control mask without having to do anything extra. You can explicitly create one and modify it by hand, but it creates a pretty reasonable default one that will help you do things like maintain depth or outlines so more in-painting doesn't go too far off.

Thanks again for the help and creating such a good interface for something so complicated.  It's definitely much, much better than the things offered by both ComfyUI and automatic.

Closing this since it's not an issue, just a confusion.  I probably should've figured it out but was expecting something different.

**Comment by Acly** [comment]
Since it's much more likely to have hand drawn sketch/line-art/pose-vector etc. here I think it makes sense that processing the current image isn't the default. The confusing part is probably the magic hiding of control layers, it's nice if you're modifying it or just generated it and forget to hide, but makes it hard to figure out what's going wrong when used with the wrong layer.

I don't have a good solution though that doesnt need more UI.
