### ISSUE TITLE
flux.1 models

### ISSUE THREAD

**Issue by redclif43** [Acly/krita-ai-diffusion#1023]
Can you add this model for generative fill? 
https://github.com/black-forest-labs/flux

**Comment by GKartist75** [comment]
That would be awesome.
Played with flux in comfyui and it works great!

**Comment by agoulddesign** [comment]
Yes please!

**Comment by NoMansPC** [comment]
Waiting for this as well. While the model will be very slow on my 4060ti 16gb, from what I've seen, it almost always gives me something I can use.

**Comment by GKartist75** [comment]
> Waiting for this as well. While the model will be very slow on my 4060ti 16gb, from what I've seen, it almost always gives me something I can use.

Im using rtx 3080 10GB and have i9 12th with  32GB ram.
Flux schnell  apprx 26 till- 35 seconds to generate after model loaded. Lowmem combination.

**Comment by LeF0URBE** [comment]
yes a FLUX WF plz :D !

**Comment by GKartist75** [comment]
great news,

a FLUX1 Schnell and DEV (fp8!) as checkpoint with included VAE and simple loader is available and now easy to use in simple flows and is really fast!

see [Flux Examples | ComfyUI_examples (comfyanonymous.github.io)](https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version)

Model links: see: [Comfy-Org (Comfy Org) (huggingface.co)](https://huggingface.co/Comfy-Org)

[Comfy-Org/flux1-schnell at main (huggingface.co)](https://huggingface.co/Comfy-Org/flux1-schnell/tree/main)

[Comfy-Org/flux1-dev at main (huggingface.co)](https://huggingface.co/Comfy-Org/flux1-dev/tree/main)

works perfect on my rtx 3080 10GB!
(schnell 40 sec 1024x1024)

**Comment by Acly** [comment]
The hype is real when 40sec for a fp8 distilled low-step model is considered "perfect" :D

I added support for the checkpoint versions ([flux1-dev-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors), [flux1-schnell-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors)).
* Make sure to update ComfyUI + comfyui-tooling-nodes.
* Select flux checkpoint and set sampler to temporary "Flux - Euler simple".

![Screenshot 2024-08-05 015707](https://github.com/user-attachments/assets/7c03a5b5-ae4b-4b85-9fb3-75cc096d7802)

**Comment by GKartist75** [comment]
> The hype is real when 40sec for a fp8 distilled low-step model is considered "perfect" :D
> 
> I added support for the checkpoint versions ([flux1-dev-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors), [flux1-schnell-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors)).
> 
> * Make sure to update ComfyUI + comfyui-tooling-nodes.
> * Select flux checkpoint and set sampler to temporary "Flux - Euler simple".
> 
> ![Screenshot 2024-08-05 015707](https://private-user-images.githubusercontent.com/6485914/354937971-7c03a5b5-ae4b-4b85-9fb3-75cc096d7802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDQ4ODMsIm5iZiI6MTcyMjg0NDU4MywicGF0aCI6Ii82NDg1OTE0LzM1NDkzNzk3MS03YzAzYTViNS1hZTRiLTRiODUtOWZiMy03NWNjMDk2ZDc4MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMDc1NjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE4NDhmZmZjNWJhMjdmNmY0NDkwNWNhN2UxMzQ5OGFhMzI1MWVmMmZiNTY4NzU2MTEzZjhiN2E3NWIyZjg0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6MP0of4py5GoQEmYwUTNQuyjYajbx71pcKL2EiV6Kqk)

@Acly thx! impressive you have implemented it so quick. BTW with the last comfyui update the loading and rendering went from 40sec to 26sec ;-)

**Comment by redclif43** [comment]
> The hype is real when 40sec for a fp8 distilled low-step model is considered "perfect" :D
> 
> I added support for the checkpoint versions ([flux1-dev-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors), [flux1-schnell-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors)).
> 
> * Make sure to update ComfyUI + comfyui-tooling-nodes.
> * Select flux checkpoint and set sampler to temporary "Flux - Euler simple".
> 
> ![Screenshot 2024-08-05 015707](https://private-user-images.githubusercontent.com/6485914/354937971-7c03a5b5-ae4b-4b85-9fb3-75cc096d7802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTI5MjIsIm5iZiI6MTcyMjg1MjYyMiwicGF0aCI6Ii82NDg1OTE0LzM1NDkzNzk3MS03YzAzYTViNS1hZTRiLTRiODUtOWZiMy03NWNjMDk2ZDc4MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTAxMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk4N2ExNTRlMzJhODY0YjA0MzM1MjEwODI0ZWY2ZThkMzAwMGZjOWVkZmU2Mjg5YTMyZWE0NWQzY2UxZmJjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.adNkH9aVZfWAbiihowtsFnQKjSJHA3N91LjAnDe-jOY)

how to implement flux support into the latest version of the plugin ?

**Comment by Acly** [comment]
You can use [krita_ai_diffusion-1.22.0-pre1.zip](https://github.com/Acly/krita-ai-diffusion/releases/download/v0.1.0/krita_ai_diffusion-1.22.0-pre1.zip)

It also has a built-in default style for Flux [schnell]

Run local: make sure your ComfyUI is setup to run [this](https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version)

Cloud: use the "Online Service" connection to run Flux-schnell on 48GB card, ~5 sec for batch of 2x 1024 images if its warmed up (longer if it needs to load the model)

Keep in mind this is a pre-release, lots of things are changing still and most of this is somewhat temporary.

Don't expect too much from Fill/Expand, Flux does not have an inpaint model, it mostly generates unrelated stuff if you use 100% strength (especially Schnell variant). Using lower strength with selection works fine.

**Comment by waynemadsen** [comment]
This is so exciting. You are amazing to get this up and running so quickly. Do you have a timeframe for when 1.22.0 will be full release?

**Comment by jxded** [comment]
Nice, i tried with https://huggingface.co/Kijai/flux-fp8 which are fp8 models with a lower size, which I assumed would work better on my 12gb card, but it returns "Unable to determine checkpoint type" would it be a lot of work to get it working? :)

**Comment by Acly** [comment]
Please use the ones from https://huggingface.co/Comfy-Org - they are also fp8. They're only bigger size because they include the vae + text encoder, which you'd need separately for the Kijai version.

I might implement support for having diffusion, vae, text as 3 separate models, but it's a bit more work and also boud to be more confusing for users.

**Comment by redclif43** [comment]
Too bad the model doesn't support inpaint :(

**Comment by NoMansPC** [comment]
> Please use the ones from https://huggingface.co/Comfy-Org - they are also fp8. They're only bigger size because they include the vae + text encoder, which you'd need separately for the Kijai version.
> 
> I might implement support for having diffusion, vae, text as 3 (or 4) separate models, but it's a bit more work and also boud to be more confusing for users.
> 
> NB: even in fp8 12GB is not enough, you can run it but it will be slow

Do we know what the RAM requirement for this model is? Because it completely fills up my 16 GB RAM (I also have 16 GB VRAM) and it doesn't even begin to generate an image. It froze up my PC and I needed to do a hard reset.

**Comment by Sil3ntKn1ght** [comment]
> Waiting for this as well. While the model will be very slow on my 4060ti 16gb, from what I've seen, it almost always gives me something I can use.

there is a fp8 model now for low ram etc faster than lightning models and better that fp32 sdxl

**Comment by nourghafarji** [comment]
> The hype is real when 40sec for a fp8 distilled low-step model is considered "perfect" :D
> 
> I added support for the checkpoint versions ([flux1-dev-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors), [flux1-schnell-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors)).
> 
> * Make sure to update ComfyUI + comfyui-tooling-nodes.
> * Select flux checkpoint and set sampler to temporary "Flux - Euler simple".
> 
> ![Screenshot 2024-08-05 015707](https://private-user-images.githubusercontent.com/6485914/354937971-7c03a5b5-ae4b-4b85-9fb3-75cc096d7802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA4MTIsIm5iZiI6MTcyMjkzMDUxMiwicGF0aCI6Ii82NDg1OTE0LzM1NDkzNzk3MS03YzAzYTViNS1hZTRiLTRiODUtOWZiMy03NWNjMDk2ZDc4MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMDc0ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjhjYmM5MGY5MWVmZWQ5ZGQwMTJjN2I2YTA4YmE5N2NjNGIzMzE0MmQzMDE4OTQ4MDZkNTU5OWIxZTlmNzk4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.djMHYpJuK4Kp0rNfiEbtheTgebZy2VwwDuCbOBGIJFA)

Hi Thanks! how can i get the "Flux - Euler simple" i am new to this

**Comment by Acly** [comment]
> Do we know what the RAM requirement for this model is?

roughly 12 GB for fp8,  24 GB for fp16
that's for the diffusion model, you tend to need a bit extra for the image and system stuff

Comfy loads fp16 by default, even if the file is stored in fp8. It uses fp8 only if there is not enough VRAM, but not entirely sure how that's determined. Maybe it can be influenced with command line arguments. There is also on option to set it explicitly in the workflow, but it requires changing a few things.

**Comment by parella007** [comment]
Working ok in mac (M1 Ultra 128Gb)

Around 95 seconds for 1,024x1,024, schnell-fp8

**Comment by yen-shi-lun** [comment]
![螢幕擷取畫面 2024-08-07 070318](https://github.com/user-attachments/assets/16980c19-0008-4ff4-a95f-caf0941f63e2)

Thank you very much for the updated version, I really appreciate it

**Comment by NoMansPC** [comment]
> Please use the ones from https://huggingface.co/Comfy-Org - they are also fp8. They're only bigger size because they include the vae + text encoder, which you'd need separately for the Kijai version.
> 
> I might implement support for having diffusion, vae, text as 3 (or 4) separate models, but it's a bit more work and also boud to be more confusing for users.
> 
> NB: even in fp8 12GB is not enough, you can run it but it will be slow

Just reporting on my experience, I managed to get it to work on 16GB VRAM and 16GB RAM using the following model: https://civitai.com/models/623224?modelVersionId=696732

It's still slow and lags my entire PC, but it doesn't outright freeze it.

**Comment by Beeda2004** [comment]
hello i am sorry but i am little new in this, but i instaled "krita_ai_diffusion-1.22.0-pre1.zip" run update after launch but and when i jump into checkpoint i did not see any flux ones which i downloaded, so i am just asking which step i missed probably thank you

**Comment by waynemadsen** [comment]
and the controlnet and loras will soon pour in:
https://huggingface.co/XLabs-AI/flux-controlnet-canny

**Comment by redclif43** [comment]
> and the controlnet and loras will soon pour in: https://huggingface.co/XLabs-AI/flux-controlnet-canny

wow

**Comment by yangmc0709** [comment]
> > The hype is real when 40sec for a fp8 distilled low-step model is considered "perfect" :D
> > I added support for the checkpoint versions ([flux1-dev-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors), [flux1-schnell-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors)).
> > 
> > * Make sure to update ComfyUI + comfyui-tooling-nodes.
> > * Select flux checkpoint and set sampler to temporary "Flux - Euler simple".
> > 
> > ![Screenshot 2024-08-05 015707](https://private-user-images.githubusercontent.com/6485914/354937971-7c03a5b5-ae4b-4b85-9fb3-75cc096d7802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA4MTIsIm5iZiI6MTcyMjkzMDUxMiwicGF0aCI6Ii82NDg1OTE0LzM1NDkzNzk3MS03YzAzYTViNS1hZTRiLTRiODUtOWZiMy03NWNjMDk2ZDc4MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMDc0ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjhjYmM5MGY5MWVmZWQ5ZGQwMTJjN2I2YTA4YmE5N2NjNGIzMzE0MmQzMDE4OTQ4MDZkNTU5OWIxZTlmNzk4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.djMHYpJuK4Kp0rNfiEbtheTgebZy2VwwDuCbOBGIJFA)
> 
> Hi Thanks! how can i get the "Flux - Euler simple" i am new to this

I try tools/scripts to overwrite script, but overwrite fail!
finally, I remove krita/ai_diffusion folder(that include model files, before remove should backup),
reimport [krita_ai_diffusion-1.22.0-pre1.zip](https://github.com/Acly/krita-ai-diffusion/releases/download/v0.1.0/krita_ai_diffusion-1.22.0-pre1.zip), solve problem!

**Comment by sraney** [comment]
on a custom server, where do I drop the flux models?

**Comment by rktvr** [comment]
tested with 1.22.0-pre1. it works really well. might even be faster than default comfy hah

**Comment by rktvr** [comment]
only issue i have had so far is going from flux to 1.5/SDXL. vram/ram doesn't get unloaded before changing the model so it just crashes every single time (3090 24gb vram+ 32gb ram).

is there a way to have krita/comfy unload the flux model fully before attempting to load another?

**Comment by noyart** [comment]
> on a custom server, where do I drop the flux models?

I was wondering the same thing, but I think Krita Ai uses the two checkpoints that was posted above. 17Gb each, and should be in checkpoint folder.

**Comment by waynemadsen** [comment]
new post by Illyasviel
NF4 model version of flux

https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

**Comment by rktvr** [comment]
> new post by Illyasviel NF4 model version of flux
> 
> [lllyasviel/stable-diffusion-webui-forge#981](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981)

comfyanon mentioned on reddit that he didn't use/add nf4 due to loss of quality but after playing with forge and nf4 it seems still pretty good. though i'm not getting any of the faster speeds.

**Comment by NoMansPC** [comment]
> > new post by Illyasviel NF4 model version of flux
> > [lllyasviel/stable-diffusion-webui-forge#981](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981)
> 
> comfyanon mentioned on reddit that he didn't use/add nf4 due to loss of quality but after playing with forge and nf4 it seems still pretty good. though i'm not getting any of the faster speeds.

After my limited testing, the results look very close to the fp16 dev model. It loads fully in my 16gb VRAM card, so just for that, it's my preferred model. I downloaded Forge for it and because I needed tile upscale again.

**Comment by GKartist75** [comment]
lllyasviel flux1-dev-bnb-nf4 v2! is now available:

https://civitai.com/models/645429
https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4

**Comment by christianv78** [comment]
Any chance of getting support for the dev version of Flux?  Or is it already possible?  (I couldn't get it to show up in the model list.)

**Comment by DVDMAN77** [comment]
> i have a rtx 3080 10gb, and 1024x1024, within 26 seconds, including loading model, and 20 steps

Hi @GKartist75 could you please describe in some steps how you do parameter this new model (just downloaded it from your CivitAI link) in the KritaAI setup, in order for it to work properly?
THANK You!

**Comment by DVDMAN77** [comment]
Hi @Acly Do you intend to also support both FP16 models of Flux1?
Thank you for your work in Krita AI, really appreciated! :-)

**Comment by redclif43** [comment]
> You can use [krita_ai_diffusion-1.22.0-pre1.zip](https://github.com/Acly/krita-ai-diffusion/releases/download/v0.1.0/krita_ai_diffusion-1.22.0-pre1.zip)
> 
> It also has a built-in default style for Flux [schnell]
> 
> Run local: make sure your ComfyUI is setup to run [this](https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version)
> 
> Cloud: use the "Online Service" connection to run Flux-schnell on 48GB GPU, ~5 sec for batch of 2x 1024 images if its warmed up (longer if it needs to load the model)
> 
> Keep in mind this is a pre-release, lots of things are changing still and most of this is somewhat temporary.
> 
> Don't expect too much from Fill/Expand, Flux does not have an inpaint model, it mostly generates unrelated stuff if you use 100% strength (especially Schnell variant). Using lower strength with selection works fine.

https://www.youtube.com/watch?v=xeIcjTiu3OI&pp=ygUPZmx1eCBpbnBhaW50aW5n
flux already support inpainting

**Comment by Acly** [comment]
no, not really. you can already do what this video does in the plugin, but it only works ok for some simple scenarios.

**Comment by DVDMAN77** [comment]
> > The hype is real when 40sec for a fp8 distilled low-step model is considered "perfect" :D
> > I added support for the checkpoint versions ([flux1-dev-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors), [flux1-schnell-fp8.safetensors](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors)).
> > 
> > * Make sure to update ComfyUI + comfyui-tooling-nodes.
> > * Select flux checkpoint and set sampler to temporary "Flux - Euler simple".
> > 
> > ![Screenshot 2024-08-05 015707](https://private-user-images.githubusercontent.com/6485914/354937971-7c03a5b5-ae4b-4b85-9fb3-75cc096d7802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDQ4ODMsIm5iZiI6MTcyMjg0NDU4MywicGF0aCI6Ii82NDg1OTE0LzM1NDkzNzk3MS03YzAzYTViNS1hZTRiLTRiODUtOWZiMy03NWNjMDk2ZDc4MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMDc1NjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE4NDhmZmZjNWJhMjdmNmY0NDkwNWNhN2UxMzQ5OGFhMzI1MWVmMmZiNTY4NzU2MTEzZjhiN2E3NWIyZjg0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6MP0of4py5GoQEmYwUTNQuyjYajbx71pcKL2EiV6Kqk)
> 
> @Acly thx! impressive you have implemented it so quick. BTW with the last comfyui update the loading and rendering went from 40sec to 26sec ;-)

Now went to 23,75sec with Flux1 [Schnell] with the latest ComfyUI config and 12GB VRAM, for a 1024*1024 image. 
Flux1 takes more than 4minutes to produce images in 1024px.
Quality is a bit different depending on both models and requests, but Schnell is clearly schnell and beautiful already!!
