### ISSUE TITLE
(URLError(gaierror(11004, 'getaddrinfo failed')),)

### ISSUE THREAD

**Issue by syl1130** [Acly/krita-ai-diffusion#1027]
(URLError(gaierror(11004, 'getaddrinfo failed')),)

sometime show this, since update to 1.21.0 version, how to do?

**Comment by Acly** [comment]
That's usually just internet connection issue. Difficult to say without more context...

**Comment by syl1130** [comment]
> That's usually just internet connection issue. Difficult to say without more context...

I have identified the issue. When I use VPN tools, the system proxy is modified, which caused this error.

**Comment by sgkongAi** [comment]
I have this problem. Version 1.70 can still be used, but for versions above 1.20, as soon as I click connect, the background interface keeps refreshing and prompting (URLError(gaierror(11004, 'getaddrinfo failed')),). How can I solve this problem
![why](https://github.com/user-attachments/assets/b3af757b-dc9c-44bb-9ca0-8930f8324625)

**Comment by syl1130** [comment]
> I also had this issue and modified the proxy VPN, but it cannot be fixed
> 
> > I have this problem. Version 1.70 can still be used, but for versions above 1.20, as soon as I click connect, the background interface keeps refreshing and prompting (URLError(gaierror(11004, 'getaddrinfo failed')),). How can I solve this problem ![why](https://private-user-images.githubusercontent.com/127425531/365336406-b3af757b-dc9c-44bb-9ca0-8930f8324625.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDI5MzgsIm5iZiI6MTcyOTAwMjYzOCwicGF0aCI6Ii8xMjc0MjU1MzEvMzY1MzM2NDA2LWIzYWY3NTdiLWRjOWMtNDRiYi05Y2EwLTg5MzBmODMyNDYyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNDMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDUwYTFmZTIwYTRmY2Q3NTg4ZjFlMDY4MWIyYTU1ODZjMzY2NzRjM2UzZGFlYjc0MGQwZTgzMjY2MTNlN2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9FFOG4_8w_7NbHkVvr4YzvChzJGTsuYP5JvAD8lmiMk)

update 1.25 new version. https://github.com/Acly/krita-ai-diffusion/releases/download/v1.25.0/krita_ai_diffusion-1.25.0.zip

**Comment by tangA008** [comment]
I also encountered this problem and have updated to krita_ai_diffusion-1.28.1
![QQ图片20241123190317](https://github.com/user-attachments/assets/fc9d8931-0861-4c9d-94f4-a35115dd3fe6)
![QQ图片20241123190257](https://github.com/user-attachments/assets/b420bb3a-cfcd-43be-a2b7-b4de9fdb33ec)
