### ISSUE TITLE
"This is a 1.5 checkpoint, but the SD 1.5 workload has not been installed

### ISSUE THREAD

**Issue by NoMansPC** [Acly/krita-ai-diffusion#103]
I'm using a previously installed ComfyUI. I fixed all the red issues. The plugin works and generates images, but it always shows that message when I select a 1.5 model. How to fix this?

**Comment by Acly** [comment]
You probably saw [ComfyUI required models](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md). The error message specifically means that one of the models in the SD 1.5 section is missing. The client.log file will give you more detailed information which one (see Troubleshooting section at the bottom of the page)

**Comment by NoMansPC** [comment]
> You probably saw [ComfyUI required models](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md). The error message specifically means that one of the models in the SD 1.5 section is missing. The client.log file will give you more detailed information which one (see Troubleshooting section at the bottom of the page)

Going through everything that wasn't installed fixed it, thanks.

**Comment by yaqing10** [comment]
This is a SD 1.5 checkpoint, but the SD 1.5 workload has not been  这个怎么解决，请教大神！

**Comment by yaqing10** [comment]
This is a SD 1.5 checkpoint, but the SD 1.5 workload has not been 这个怎么解决，请教大神！

![微信图片_20231216180448](https://github.com/Acly/krita-ai-diffusion/assets/153982771/5c412d40-a71a-415c-bbd9-677084829585)

**Comment by Kmeyel** [comment]
I also encountered it.

**Comment by wowop2000** [comment]
1.  open "configure image diffusion",select "connection" item.
2.  select "local server managed by krita plugin" from "server management"
3.  locate your comfyui direcory in "server path"
4.   expand  "workloads" lebal ,checked "stable diffusion 1.5" ,uncheck other items.
5.  click "install"  button
krita will install all the necessary model automaticly. 
6.when install finished ,change back "connetct to extranal Server(local or remote)" option in "server configuration"
if you want to know which model has been installed,you can click "view log files" option below the "install" button.
good luck!
