### ISSUE TITLE
Request: Add Model Name to History

### ISSUE THREAD

**Issue by jaredwastaken** [Acly/krita-ai-diffusion#1040]
Please add the ability to see which model generated the image in the history panel.
Currently it shows the prompt and strength - But I tend to queue a lot of different models and strengths.

**Comment by waynemadsen** [comment]
This would be a great feature to have. I also tend to try out a long list of different programmed styles (using different models) with the same prompt and then leave to let them run. By the time I come back, I am only guessing which styles connect to which images.

**Comment by Acly** [comment]
This was done in v1.24.0
