### ISSUE TITLE
pose

### ISSUE THREAD

**Issue by plasx520** [Acly/krita-ai-diffusion#1042]
`*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************`
![有道截屏翻译结果_1723045240348](https://github.com/user-attachments/assets/05323400-953c-443f-b893-b11a7d9ac8a9)

**Comment by Acly** [comment]
Looks like `onnxruntime-gpu` is installed in your python environment, but the required CUDA libraries are not. Either do
```
pip uninstall onnxruntime-gpu
```
or try to install the requirements.

**Comment by plasx520** [comment]
OK Solved

**Comment by plasx520** [comment]
Would the big shot consider transplanting it to Photoshop? That might also be great.
