### ISSUE TITLE
 This is a Flux checkpoint, but the Flux workload has not been installed?

### ISSUE THREAD

**Issue by kwang0429** [Acly/krita-ai-diffusion#1047]
![WeChat Screenshot_20240808201054](https://github.com/user-attachments/assets/4ce3f876-2576-4850-8e8b-28e8520b756b)
it seems like I can not get the flux model to work, it's saying  This is a Flux checkpoint, but the Flux workload has not been installed., can you please help ? 

Thanks

**Comment by kwang0429** [comment]
also would like to know if I am missing any, what's the fastest way to get all models in place. Thanks

**Comment by kwang0429** [comment]
<img width="637" alt="Screenshot 2024-08-08 195620" src="https://github.com/user-attachments/assets/357f619d-9eac-4a40-a9fb-d25898b8d501">
![WeChat Screenshot_20240808195544](https://github.com/user-attachments/assets/17baeea3-eb1f-4bb7-94a9-55e8dd85b59f)

**Comment by kwang0429** [comment]
![WeChat Screenshot_20240808195544](https://github.com/user-attachments/assets/494aafe7-339e-4e17-9b80-281143cb28b8)

**Comment by Acly** [comment]
Strange, there is currently nothing required for "Flux workload" apart from having a checkpoint.

Can you try to restart, and post [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) if it still complains about workload.

**Comment by Sil3ntKn1ght** [comment]
how did you get it to see the model v1.22 its not seeing it for me same with sdxl v3

**Comment by oleshanepro** [comment]
I don't see Flux checkpoints either

**Comment by kwang0429** [comment]
make sure you get the right one, there are few with the same naming. 

Put the following ones in your checkpoint folder, if you have downloaded the same file from huggingface, it might be different in size, make sure to download those 2 and put them in your checkpoints.

https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors
https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors

**Comment by waynemadsen** [comment]
is the comfyui and all necessary addons up to date for whatever server being used?

**Comment by Jarco** [comment]
I had the same issue, and it was solved by restarting Krita.

**Comment by SenshiV22** [comment]
> I had the same issue, and it was solved by restarting Krita.

Confirmed. Sometimes is just the all-time simplistic thing...

Thanks!

**Comment by SimonHeggie** [comment]
Confirming for 1.36.1.

My work around; grab the suggested files as recommend in the latest release description.

Then: create a copy of the flux workflow, and it should just be pointed automatically at the checkpoint if it acted like mine. Otherwise, I think you can manually select the file from here.

My guess... is something is not connected by default with the flux workflow settings. At least from my setup.

-S
