### ISSUE TITLE
ComfyUI IPAdapter plus has been installed, but it shows as not installed

### ISSUE THREAD

**Issue by salier** [Acly/krita-ai-diffusion#1048]
I used the official ComfyUI portable standalone build for Windows, installed ComfyUI IPAdapter plus using ComfyUI Manager, and its sample runs normally. I also downloaded the model files required in the documentation. However, there was an issue where ComfyUI IPAdapter plus was not installed when connecting the plugin to ComfyUI. My console does not have any related errors. I would like to know where the problem lies and how I can solve it.
![image](https://github.com/user-attachments/assets/a85c6de8-eb86-4d93-9362-d3152743b1ca)
![image](https://github.com/user-attachments/assets/bbf1f549-1525-4489-afc0-512e5082a2f9)
![image](https://github.com/user-attachments/assets/0533be1d-4241-42fb-85eb-afe04acfd1c8)

**Comment by Acly** [comment]
Maybe it's a problem with the translation pack? Did you try to disable it?

**Comment by salier** [comment]
It may not be that problem. I reinstalled this comfyUI. When I installed IPAdapter plus, I did not install the localized language pack.

**Comment by Acly** [comment]
It's just a simple check if `IPAdapter` and `IPAdapterModelLoader` appear in http://127.0.0.1:8188/object_info
If you can use those nodes in comfyui that should be the case.

**Comment by Acly** [comment]
Can you find them in http://127.0.0.1:8188/object_info output (Ctrl+F to search)? Or send me the output as file.

Do you have comfyui-inpaint-nodes installed? Asking because I didn't see it in your log screenshot. Maybe the error message is wrong and something else is missing...

**Comment by salier** [comment]
I tried to search, but there were a huge number of results
![image](https://github.com/user-attachments/assets/3cd2ce2a-5289-4925-8de5-6fdc0cf95799)
![image](https://github.com/user-attachments/assets/5a8aa451-4256-4f59-8e8d-e6e2069632fe)
![image](https://github.com/user-attachments/assets/3b6635d6-059b-4366-9401-3852fc21c87e)
![image](https://github.com/user-attachments/assets/7d402618-20d6-4306-8828-229f80a062e2)
I have already installed it using the manager
![image](https://github.com/user-attachments/assets/63ade207-fdff-46f3-9715-a21c55bc799b)

**Comment by syl1130** [comment]
Try update comfyui-inpaint-nodes

**Comment by Acly** [comment]
The output looks good. 

I forgot to check this, but it looks like you are running a really old version of the plugin. That is likely the problem.

Please use the latest version from here: https://github.com/Acly/krita-ai-diffusion/releases
If the update doesn't work, try clean install: https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-uninstall-the-plugin

**Comment by salier** [comment]
He looks normal now, sorry. I uninstalled krita and reinstalled it directly before, but did not delete the cache in appdata, which resulted in the old plugin still being used after reinstallation.![image](https://github.com/user-attachments/assets/3c773599-a5be-462b-baac-c2757475690c)
