### ISSUE TITLE
no puedo instalar el modulo de IA en Mac

### ISSUE THREAD

**Issue by DanielMDamilano** [Acly/krita-ai-diffusion#1049]
EL archivo no me aparece en formato zip , y cuando lo convierto a zip me da error al instalarlo

**Comment by parella007** [comment]
https://github.com/Acly/krita-ai-diffusion/releases/download/v1.22.0/krita_ai_diffusion-1.22.0.zip

Eso es un .zip, no le hagas nada! no dejes que el navegador te lo descomprima, solo: desde krita, desde herramientas, scripts, importar python plugin desde archivo y escojes el .zip, ya esta!

(thats a zip, dont do anything to it!, dont let the browser to unpack it, just, in krita: tools, scripts, import python plugin from file, choose the .zip, voila!)
