### ISSUE TITLE
[Question] Multi-GPU Configuration Guidance on Krita 5.2.1

### ISSUE THREAD

**Issue by red-rackham** [Acly/krita-ai-diffusion#105]
Hello,

I've been using the krita-ai-diffusion plugin on Krita 5.2.1 with Ubuntu 20.04.6 LTS and am really impressed with its capabilities. I'm looking to further enhance its performance by leveraging a multi-GPU setup.

I've already looked through the README, settings.py, and the cloud-gpu.md documentation but couldn't find specific information on configuring and using multiple GPUs.

Could you provide any guidance or instructions for setting up and using multiple GPUs with this plugin? Any advice or tips would be greatly appreciated.

Thank you for your amazing work on this plugin!

**Comment by Acly** [comment]
Hi,

if you mean multiple GPUs work together to generate one image faster: I don't think this exists for image diffusion. At least I've never seen it, and the algorithm seems inherently ill-suited.

Using multiple GPUs to generate separate images concurrently is feasible, but not implemented. You can run two ComfyUI server instances on your machine and each uses one of the GPUs, but you'd still need a way to aggregate them. It boils down to the same as #53
