### ISSUE TITLE
Prompt Translation there is no other language selection

### ISSUE THREAD

**Issue by yaolllppp** [Acly/krita-ai-diffusion#1052]
![Snipaste_2024-08-10_11-17-37](https://github.com/user-attachments/assets/5a80de94-2a1a-46b3-891f-7bfc9b44d1e7)
I am using the latest version 1.22.0, but the prompt word translation function is not available and there is no other language selection

**Comment by syl1130** [comment]
open VPN tool first than open krita ai, you will see all languages

**Comment by wz488241** [comment]
> open VPN tool first than open krita ai, you will see all languages首先打开VPN工具而不是打开krita ai，你会看到所有语言

我打开了vpn，仍然还是没有其他语言选择，请问这个怎么处理

**Comment by xtywwl** [comment]
我也遇到了相同的问题

**Comment by Acly** [comment]
Internet connection is required to retrieve available languages and download language packs.

Please check [log files](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) for errors.

Try http://127.0.0.1:8188/api/etn/languages (while Krita/ComfyUI is running).

**Comment by wz488241** [comment]
It is a pleasure to hear from you!
I tried connecting to the VPN and then opening the krita plugin settings page, but still didn't succeed in updating to the language pack.
I don't know much about computer programming and don't quite understand how to do what you said, [Try http://127.0.0.1:8188/api/etn/languages (while Krita/ComfyUI is running)].
When I click on the language pack setting button, the following prompt appears in the background





&nbsp;


赤奣
***@***.***



&nbsp;

**Comment by lazycat64** [comment]
remove "comfyui-tooling-nodes",use Manager reinstall it.

**Comment by xtywwl** [comment]
> 删除“comfyui-tooling-nodes”，使用管理器重新安装。

我试试

**Comment by xtywwl** [comment]
> 删除“comfyui-tooling-nodes”，使用管理器重新安装。

这个试过了好像不行

**Comment by balroge** [comment]
1.开vpn到这里下载语言包，重命名为：translate-zh_en.argosmodel    https://www.argosopentech.com/argospm/index/
2.下载这个index.json
[index.json](https://github.com/user-attachments/files/16703652/index.json)
3.秋叶整合包文件放置路径：index.json放在：ComfyUI-aki-v1.3\.cache\argos-translate
![1](https://github.com/user-attachments/assets/5908dcdd-28b2-47eb-9104-a40d9d13bddc)
语言包放在：ComfyUI-aki-v1.3\.cache\argos-translate\downloads
![2](https://github.com/user-attachments/assets/699aee88-9266-41b5-8005-ef4451d0d8af)
4.成功的话会在下面位置解压语言包：
C:\Users\***\.local\share\argos-translate\packages\translate-zh_en-1_9
非整合包可以尝试把两个文件放在：C:\Users\***\.cache

**Comment by Rain-LA** [comment]
> 1.开vpn到这里下载语言包，重命名为：translate-zh_en.argosmodel https://www.argosopentech.com/argospm/index/ 2.下载这个index.json [index.json 索引.json](https://github.com/user-attachments/files/16703652/index.json) 3.秋叶整合包文件放置路径：index.json放在：ComfyUI-aki-v1.3.cache\argos-translate ![1](https://private-user-images.githubusercontent.com/167946381/360259057-5908dcdd-28b2-47eb-9104-a40d9d13bddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mzc5MzAsIm5iZiI6MTcyNTUzNzYzMCwicGF0aCI6Ii8xNjc5NDYzODEvMzYwMjU5MDU3LTU5MDhkY2RkLTI4YjItNDdlYi05MTA0LWE0MGQ5ZDEzYmRkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxMjAwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzExYWFhNmM1YTUzZTY5NGNmMzczZDM0NGYxYTExNDBmNDNjM2FmMWVhYjZiMThmMDAzYzE0NjczOTRkY2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PKdIrWr87hCzCe8mqJXxGHP1eSn2d7svP6MybGBGqWk) 语言包放在：ComfyUI-aki-v1.3.cache\argos-translate\downloads ![2](https://private-user-images.githubusercontent.com/167946381/360262764-699aee88-9266-41b5-8005-ef4451d0d8af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mzc5MzAsIm5iZiI6MTcyNTUzNzYzMCwicGF0aCI6Ii8xNjc5NDYzODEvMzYwMjYyNzY0LTY5OWFlZTg4LTkyNjYtNDFiNS04MDA1LWVmNDQ1MWQwZDhhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxMjAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjVmZjU2NmNhZDAwMjg3YzVhNTliOGIzYjA0YzY2OTkyZTI0NWQ2MmJlZTk5MThjODZiYWNmNTIwZDZmZTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1MHv1wGm9YY2ouz_QdP3L81e6_saBL_91kqmRSVRxCM) 4.成功的话会在下面位置解压语言包： C:\Users***.local\share\argos-translate\packages\translate-zh_en-1_9 非整合包可以尝试把两个文件放在：C:\Users***.cache 。缓存

It works!Solved a problem that had been plaguing me for a long time. Thank you very much
