### ISSUE TITLE
fresh install, it wont see the flux model

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#1053]
have re installed restarted and no luck it wont see the flux model, or sdxl 3 models there just not seen other sdxl3 models say the bellow, workflow missing, how does one add it.

![Screenshot 2024-08-10 135541](https://github.com/user-attachments/assets/943c505b-ca99-4727-8c85-36a7d108cb9f)
![Screenshot 2024-08-10 135642](https://github.com/user-attachments/assets/e6f709b5-eee6-4760-b12d-28aea9f4545b)
![Screenshot 2024-08-10 155545](https://github.com/user-attachments/assets/4c045f10-6841-4197-903a-bf3e372bae0d)

**Comment by esmail-mkh** [comment]
Update the comfyui!

**Comment by Sil3ntKn1ght** [comment]
> Update the comfyui!

its freshly installed from Aclys installer, its not a separate comfy

**Comment by Sil3ntKn1ght** [comment]
i downloaded black forest labs versions kijai version and one by dice, 
dice's is the only one seen and others are invisible in kritas model selection and don't show at all.

3 models in my flux dir one in defult dir as original post image. 

the working one below is dices version, has in-pained spot just showing that one is working.
very odd issue.
![Screenshot 2024-08-10 165110](https://github.com/user-attachments/assets/1c5aab2b-ae54-4d47-b11f-1db21e60d1aa)
![Screenshot 2024-08-10 163735](https://github.com/user-attachments/assets/12e13e72-dcd8-4796-9bef-6285ff7b9b31)
![Screenshot 2024-08-10 163939](https://github.com/user-attachments/assets/3fdd8ffc-cbe2-493a-bbc2-682bdbb2f9e9)
![10-2_001](https://github.com/user-attachments/assets/bbd9a472-722d-4def-878a-6c193108bacb)

**Comment by Acly** [comment]
From release page:

> Please use one of the following checkpoints:
> [Flux.1 [dev]](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors) to ComfyUI/models/checkpoints
> [Flux.1 [schnell]](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors) to ComfyUI/models/checkpoints

Other files only contain the diffusion model and do not work (including blackforest version). They are not the same.

**Comment by Sil3ntKn1ght** [comment]
> From release page:
> 
> > Please use one of the following checkpoints:
> > [Flux.1 [dev]](https://huggingface.co/Comfy-Org/flux1-dev/blob/main/flux1-dev-fp8.safetensors) to ComfyUI/models/checkpoints
> > [Flux.1 [schnell]](https://huggingface.co/Comfy-Org/flux1-schnell/blob/main/flux1-schnell-fp8.safetensors) to ComfyUI/models/checkpoints
> 
> Other files only contain the diffusion model and are not supported (including blackforest version). They are not the same.

and the sd3 missing workflow where do i get and put that.
![Screenshot 2024-08-10 155545](https://github.com/user-attachments/assets/86a9ab94-0185-4a67-bb38-552f6c8bc74f)
