### ISSUE TITLE
Add Remove Content with Flux

### ISSUE THREAD

**Issue by esmail-mkh** [Acly/krita-ai-diffusion#1054]
Hi dear Acly, please add Remove Content with Flux in next updates, thanks

**Comment by Acly** [comment]
Is this about Remove Content showing an error on cloud? Or about the model not working particularly well for Remove Content (or any other 100% fill mode)?

**Comment by esmail-mkh** [comment]
Not in the cloud, I used it locally with the Flux model, but it didn't Remove anything and just added weird stuff to my selection part.

**Comment by Acly** [comment]
Okay yes, that's just not something Flux can do at the moment. Have to wait until someone trains an inpaint model which is good at these kind of tasks.

**Comment by esmail-mkh** [comment]
> Okay yes, that's just not something Flux can do at the moment. Have to wait until someone trains an inpaint model which is good at these kind of tasks.

Oh ok thanks❤️
