### ISSUE TITLE
Flux generations dark and/or blurry

### ISSUE THREAD

**Issue by XetalSL** [Acly/krita-ai-diffusion#1056]
With default settings flux seams to be a bit screwed:

![image](https://github.com/user-attachments/assets/d39c19a2-2651-4ed6-a174-cbb25c557877)

![image](https://github.com/user-attachments/assets/71ffe1cf-8bac-4fc4-be66-da45811ec094)
![image](https://github.com/user-attachments/assets/5ce8dfa4-d1c0-4f35-a7c8-a0fbbcb8b67d)
![image](https://github.com/user-attachments/assets/11a58e36-10b8-4aa4-bef1-806e4d1c7874)

**Comment by rktvr** [comment]
those aren't the default values for flux (at least not for me): 
![image](https://github.com/user-attachments/assets/02d6db71-15b6-4950-ac60-b642ec4c72fc)
your steps are too high

**Comment by XetalSL** [comment]
those are not right - re-select the preset and itll change to 20. 4 also doesnt work and it generates the same images you see

**Comment by rktvr** [comment]
nope. i'm using steps 4 to great effect with the schnell model. not sure why yours doesn't work.

**Comment by XetalSL** [comment]
did a settings reset - works correctly now - dunno what was messed up.
