### ISSUE TITLE
pose不能正常使用

### ISSUE THREAD

**Issue by aiphoto-ithub** [Acly/krita-ai-diffusion#1059]
pose不能使用，
这个问题折磨了我12个小时了，一直解决不了。
希望在这里得到帮助

![微信截图_20240811002311](https://github.com/user-attachments/assets/a9004cab-cd12-4c10-91f4-ce44bf9429aa)
![微信截图_20240811002553](https://github.com/user-attachments/assets/64468213-df04-4d52-bc45-f55115de997d)
![微信截图_20240811002624](https://github.com/user-attachments/assets/1f0941ca-8a56-45ff-ab38-e6a9117bad1e)

**Comment by aiphoto-ithub** [comment]
pose无法使用

**Comment by guijiaosir** [comment]
报错已经很详细介绍了

**Comment by aiphoto-ithub** [comment]
> 报错已经很详细介绍了

看不懂这个报错

**Comment by Acly** [comment]
There is an issue with the .onnx file mentioned in the error message. 
It might be incomplete or corrupt. If it exists, try deleting it (it will automatically re-download).

**Comment by wuliang19869312** [comment]
> 错误消息中提到的 .onnx 文件存在问题。 它可能不完整或已损坏。如果存在，请尝试删除它（它会自动重新下载）。

Where do I remove the SD1.5 pose model, which link is the corresponding download, please help~ I am connecting to the model originally installed in comfyui, not in krita's sever!
![Uploading 屏幕截图 2024-10-27 191517.png…]()

**Comment by wuliang19869312** [comment]
> There is an issue with the .onnx file mentioned in the error message. It might be incomplete or corrupt. If it exists, try deleting it (it will automatically re-download).
![屏幕截图 2024-10-27 191517](https://github.com/user-attachments/assets/08df50c6-4495-49ba-b410-3869dc3b0e6c)

Where do I remove the SD1.5 pose model, which link is the corresponding download, please help~ I am connecting to the model originally installed in comfyui, not in krita's sever!
