### ISSUE TITLE
Sdxl3 missing workload

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#1061]
sd3 missing workflow where do i get and put that please.
![Screenshot 2024-08-10 155545](https://github.com/user-attachments/assets/51ad8a9b-e335-41d2-9d07-e5160750388e)
![Screenshot 2024-08-11 130820](https://github.com/user-attachments/assets/9e252e7c-df8b-4c40-aa01-acf967ca10a2)

**Comment by Acly** [comment]
* [clip_g.safetensors](https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/text_encoders/clip_g.safetensors) to ComfyUI/models/clip
* [clip_l.safetensors](https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/text_encoders/clip_l.safetensors) to ComfyUI/models/clip

**Comment by Sil3ntKn1ght** [comment]
> * [clip_g.safetensors](https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/text_encoders/clip_g.safetensors) to `ComfyUI/models/clip`
> 
>     * [clip_l.safetensors](https://huggingface.co/stabilityai/stable-diffusion-3-medium/blob/main/text_encoders/clip_l.safetensors) to `ComfyUI/models/clip`

![Screenshot 2024-08-12 133314](https://github.com/user-attachments/assets/8d0d2f8a-dfcb-4507-bb0a-b8dca306d7bc)

no luck signed up etc did the ask for permission but no access seems limited probably server issues any other locations

**Comment by Sil3ntKn1ght** [comment]
I'm at a loss still has workload missing 

![Screenshot 2024-08-13 140447](https://github.com/user-attachments/assets/274fe57d-9a00-40f4-95e9-4db0fb53f472)

**Comment by Sil3ntKn1ght** [comment]
got access today downloading to clip file will test later

**Comment by Sil3ntKn1ght** [comment]
placed in clip folder still get the error on all sd3 models 

![Screenshot 2024-08-13 144807](https://github.com/user-attachments/assets/45ab9395-a7bc-48f7-ab8b-4dd67e24649a)
@
![Screenshot 2024-08-13 140447](https://github.com/user-attachments/assets/bcd63686-db96-4b4f-bc8b-bfc7bf555bd5)

**Comment by Acly** [comment]
Check client.log, it should say something like this:
```
2024-08-13 09:23:42,271 INFO Found CLIP model clip_g for SD 3: clip_g.safetensors
2024-08-13 09:23:42,271 INFO Found CLIP model clip_l for SD 3: clip_l.safetensors
...
2024-08-13 09:23:46,241 INFO SD 3: supported
```

**Comment by Sil3ntKn1ght** [comment]
> Check client.log, it should say something like this:
> 
> ```
> 2024-08-13 09:23:42,271 INFO Found CLIP model clip_g for SD 3: clip_g.safetensors
> 2024-08-13 09:23:42,271 INFO Found CLIP model clip_l for SD 3: clip_l.safetensors
> ...
> 2024-08-13 09:23:46,241 INFO SD 3: supported
> ```

awesome restart pc and now it seeing the clip L and G

thanks you very much for the clip data links
![Screenshot 2024-08-13 160504](https://github.com/user-attachments/assets/fc8cb197-8549-4361-a5e4-b8cfbd5843b9)
