### ISSUE TITLE
Flux rendering Stuck (maybe no running)

### ISSUE THREAD

**Issue by Skylerky** [Acly/krita-ai-diffusion#1065]
I try to Flux modal but it Stuck in 1% (but SDXL modal is normal rendering)
![image](https://github.com/user-attachments/assets/5dd7fa85-b2e8-4840-b874-7a60e0e2b034)
and The chart does not change, it may not be running at all
![image](https://github.com/user-attachments/assets/c5c627e4-c992-40c2-8504-f2f1226427ae)
cannot see what happen
![image](https://github.com/user-attachments/assets/222903f7-562a-4fd0-a7e9-dd1836f3e644)
 
GPU rtx3060 12GB
RAM 16GB
SSD

**Comment by Sil3ntKn1ght** [comment]
reduce canvas to 480x800 takes 3min on my 8 gig. 
but the new flux for 8g dropped, hopefully acly adds support soon as its very fast from 1min on 4090 videos to 14sec so for us its imagine 30sec to 1min with this. 
https://openart.ai/workflows/cgtips/comfyui---flux-nf4-model---lighter-and-faster/xgXUBq2E14uoHdyx2LTe

**Comment by Acly** [comment]
The client was disconnected, so probably the server crashed. Probably out of RAM
