### ISSUE TITLE
8GB Flux coming?

### ISSUE THREAD

**Issue by nigelp** [Acly/krita-ai-diffusion#1067]
Is there any chance of Flux model support in Krita Ai for 8GB RTX 4060 VRAM?

**Comment by Serasul1984** [comment]
maybe in 6 months but i doubt it

**Comment by Sil3ntKn1ght** [comment]
> maybe in 6 months but i doubt it
it happen, just need acly to add the support

https://openart.ai/workflows/cgtips/comfyui---flux-nf4-model---lighter-and-faster/xgXUBq2E14uoHdyx2LTe
https://www.youtube.com/watch?v=L5BjuPgF1Ds

**Comment by Acly** [comment]
NF4 still uses ~10.5GB on my system. I am not sure it will fit entirely into 8GB. (It will probably work, but very slow)

**Comment by syl1130** [comment]
![image](https://github.com/user-attachments/assets/5a54b811-646e-4b69-bf60-8b5b8c26c0b7)
I found that my laptop 3070 graphics card 8GB can also calculate, and it takes about 70 seconds to capture a 1024 resolution image

**Comment by nigelp** [comment]
Oh interesting. But this is using Krita AI or standalone?

**Comment by Sil3ntKn1ght** [comment]
> ![image](https://private-user-images.githubusercontent.com/61195061/357380518-04b672d3-e547-48a5-9161-aaa500a5ef44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTIwMjEsIm5iZiI6MTcyMzU5MTcyMSwicGF0aCI6Ii82MTE5NTA2MS8zNTczODA1MTgtMDRiNjcyZDMtZTU0Ny00OGE1LTkxNjEtYWFhNTAwYTVlZjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDIzMjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YTJhNzE1YjkxNzUxMjc4ZjcyMTNjMDMyNTY4NmQxNmY0NGRiMzYwNmVhMWE3ODRiZTBhY2E4NTEwYzQ0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KvknTVbIKarqA9fy8UDh9ac195s-9awON1wxXFhkO6g) I found that my laptop 3070 graphics card 8GB can also calculate, and it takes about 70 seconds to capture a 1024 resolution image

70sec is quick, normal flux is 5 to 10 minutes

**Comment by GKartist75** [comment]
lllyasviel flux1-dev-bnb-nf4 v2! is now available:

https://civitai.com/models/645429
https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4

**Comment by Sil3ntKn1ght** [comment]
> NF4 still uses ~10.5GB on my system. I am not sure it will fit entirely into 8GB. (It will probably work, but very slow)

i get 5min on schnell at 1024x1024 while watching YouTube on my rtx3060, any decrease in wait time would be a win even if its 2min ...

**Comment by Acly** [comment]
See https://github.com/Acly/krita-ai-diffusion/discussions/1176 for current state on low-VRAM models.
