### ISSUE TITLE
Doesn't recognize particular models

### ISSUE THREAD

**Issue by alperktt** [Acly/krita-ai-diffusion#1068]
![image](https://github.com/user-attachments/assets/81f80651-66ed-4bc0-9294-496df20ef368)

![image](https://github.com/user-attachments/assets/9f91b51c-9f67-47e4-9621-54fbc2aaa502)

It doesn't recognize realvisxlV40_v30inpaintBakedvae, but it does recognize pony_inpaint. I was experimenting, and when I turned off the seamless mode, I could use my inpaint model, and it got faster. Normally, I think it uses the foocus_inpaint method.

**Comment by Acly** [comment]
Inpaint models are not supported. And yes it will create one on the fly using fooocus method where needed. Doesn't work for pony models unfortunately.

I don't know what pony_inpaint is, but it is not an inpaint model.

**Comment by alperktt** [comment]
> Inpaint models are not supported. And yes it will create one on the fly using fooocus method where needed. Doesn't work for pony models unfortunately.
> 
> I don't know what pony_inpaint is, but it is not an inpaint model.

Hmm when i choosed pony_inpaint.safetensors model inpainting got faster compare to foocus method and quality was good- seamless disabled- 

Well, the inpaint models will be supported in the future?

Thanks

**Comment by Acly** [comment]
> Well, the inpaint models will be supported in the future?

not planned, inpaint merges just waste a lot of space compared to other methods
