### ISSUE TITLE
THE NEW SD3 AND flux1 ,I can use ,but sd1.5 and SDXL cannot use,

### ISSUE THREAD

**Issue by chentaopisces** [Acly/krita-ai-diffusion#1070]
THE NEW SD3 AND flux1 ,I can use ,but sd1.5 and SDXL cannot use,
![屏幕截图 2024-08-13 010638](https://github.com/user-attachments/assets/91a6155a-83dc-4403-a911-5f20ba8f03d4)
why 
![屏幕截图 2024-08-13 010753](https://github.com/user-attachments/assets/e0fcb195-aea1-46db-b13b-324695068077)

**Comment by negalioja** [comment]
For me was problem with missing loras (info from client.log):

"No model matches search paths: hyper-sdxl-8steps-cfg-lora"

"No model matches search paths: hyper-sd15-8steps-cfg-lora"


I just downloaded and put in loras folder:
https://huggingface.co/ByteDance/Hyper-SD/blob/main/Hyper-SDXL-8steps-CFG-lora.safetensors
https://huggingface.co/ByteDance/Hyper-SD/blob/main/Hyper-SD15-8steps-CFG-lora.safetensors

**Comment by chentaopisces** [comment]
thank you ,i got it,

**Comment by catto123455** [comment]
This is a large SDXL model, but the SDXL has reached its workload and has not yet been installed.
this is mine

**Comment by MrUSBEN** [comment]
> For me was problem with missing loras (info from client.log):
> 
> "No model matches search paths: hyper-sdxl-8steps-cfg-lora"
> 
> "No model matches search paths: hyper-sd15-8steps-cfg-lora"
> 
> I just downloaded and put in loras folder: https://huggingface.co/ByteDance/Hyper-SD/blob/main/Hyper-SDXL-8steps-CFG-lora.safetensors https://huggingface.co/ByteDance/Hyper-SD/blob/main/Hyper-SD15-8steps-CFG-lora.safetensors

This worked for me for the latest update, thankyou :D
