### ISSUE TITLE
where to download scibble contronet ? 

### ISSUE THREAD

**Issue by kwang0429** [Acly/krita-ai-diffusion#1071]
I can't seem to find the right model for this or other plugins, can someone please shine the light on this ? Thanks

![WeChat Screenshot_20240812103851](https://github.com/user-attachments/assets/46aaddba-7945-44b3-9982-80de071578e8)

**Comment by GKartist75** [comment]
u can use the internal download manager of the plugin

![Schermafbeelding 2024-08-13 103642](https://github.com/user-attachments/assets/d276b927-8af7-473a-81e3-cb786875aa0e)

or use the script: https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup

and if you want to use your own comfyui, just adjust the settings to custom server, and move the downloaded controlnets to the new location or use path references.
