### ISSUE TITLE
[BUG] Problem whith CotrolNet XL hand refiner

### ISSUE THREAD

**Issue by monkeybas9** [Acly/krita-ai-diffusion#1074]
Hey everyone,

Does anyone know how I can solve this problem using ControlNet?

![Captura de pantalla 2024-08-12 142951](https://github.com/user-attachments/assets/dacf3605-9c88-4214-9dfe-a83fad7d2d92)

**Comment by guijiaosir** [comment]
Just download the corresponding model.
