### ISSUE TITLE
updated control presets not showing in ver. 1.22

### ISSUE THREAD

**Issue by waynemadsen** [Acly/krita-ai-diffusion#1082]
Previous versions have had no problems showing the custom presets in the drop down menu for sampler settings. Version 1.22, I can edit the file, but they don't show up. I have tried restarting krita and comfy, but they don't appear. Did the file get moved because this install was a update to version 1.22 instead of a fresh install?

**Comment by Acly** [comment]
Not sure, there were no changes in that regard.

The presets located in `krita/ai_diffusion/presets` aren't touched during updates. Only the built-in ones in `krita/pykrita/ai_diffusion/presets` are replaced.

**Comment by waynemadsen** [comment]
yeah, i still can't use any of my custom sampler settings. I'm not sure if it is only me, or if someone else can verify this bug.

**Comment by Acly** [comment]
It works for me. Check client.log for something like this:
```
2024-08-15 19:47:47,647 INFO Loaded 2 sampler presets from C:\Users\Acly\AppData\Roaming\krita\ai_diffusion\presets\samplers.json
```
