### ISSUE TITLE
Where do I put Flux models?

### ISSUE THREAD

**Issue by xtywwl** [Acly/krita-ai-diffusion#1086]
My Flux model is not appearing in Krita's models folder.

**Comment by piotrkucharski** [comment]
@xtywwl 

![image](https://github.com/user-attachments/assets/0c8b1bf7-e596-4954-8b7b-132b12c7cd41)

**Comment by Acly** [comment]
It's checkpoints only

**Comment by mvstrawn** [comment]
> It's checkpoints only

In my explanation above,
`flux1-dev-fp8.safetensors`
`flux1-schnell-fp8.safetensors`
`flux1-schnell.sft`
are usable models in ComfyUI. I'm not sure I understand the difference between these three and the other three that appear in the list, but if this is intended behavior that's fine, I'm not asking for an explanation, just wanted to bring it to your attention.

**Comment by xtywwl** [comment]
> @xtywwl
> 
> ![图像](https://private-user-images.githubusercontent.com/5716174/358857763-0c8b1bf7-e596-4954-8b7b-132b12c7cd41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzY5NTAsIm5iZiI6MTcyNDAzNjY1MCwicGF0aCI6Ii81NzE2MTc0LzM1ODg1Nzc2My0wYzhiMWJmNy1lNTk2LTQ5NTQtOGI3Yi0xMzJiMTJjN2NkNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDMwNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI2M2M1ZjIwZTRjODkwZDBiMmNiMTNjYzU5MmIwZjk3MDVkMjQ5ODc4Y2UzNjY5NmFiMjc4ODgwM2U2YzBiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1uhQA8Ipy_pKiB4IKpZX_CCdwHUx5SXJnyXbzmJ2rAs)

就是在放在这个目录下但是，krita无法显示，很多人都有这个问题

**Comment by Peter5Chiou** [comment]
don't forget to update "ComfyUI Nodes for External Tooling" and "ComfyUI Inpaint Nodes" in comfyui Custom Nodes Manager

**Comment by FHeifer** [comment]
> > @xtywwl
> > ![图像](https://private-user-images.githubusercontent.com/5716174/358857763-0c8b1bf7-e596-4954-8b7b-132b12c7cd41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzY5NTAsIm5iZiI6MTcyNDAzNjY1MCwicGF0aCI6Ii81NzE2MTc0LzM1ODg1Nzc2My0wYzhiMWJmNy1lNTk2LTQ5NTQtOGI3Yi0xMzJiMTJjN2NkNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDMwNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI2M2M1ZjIwZTRjODkwZDBiMmNiMTNjYzU5MmIwZjk3MDVkMjQ5ODc4Y2UzNjY5NmFiMjc4ODgwM2U2YzBiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1uhQA8Ipy_pKiB4IKpZX_CCdwHUx5SXJnyXbzmJ2rAs)
> 
> 就是在放在这个目录下但是，krita无法显示，很多人都有这个问题

你必须从 hugginface 中的 comfyui-org 下载模型。我也遇到了同样的问题 // You Have to download the models from comfyui-org in hugginface. I Had the same problem:    https://huggingface.co/Comfy-Org/flux1-schnell/tree/main https://huggingface.co/Comfy-Org/flux1-dev/tree/main

**Comment by Acly** [comment]
See https://github.com/Acly/krita-ai-diffusion/discussions/1176 for wider support of various Flux models.
