### ISSUE TITLE
Remember text translation toggle state

### ISSUE THREAD

**Issue by picolet21** [Acly/krita-ai-diffusion#1087]
Normally I prefer to use English prompts without text translation, but occasionally I also use text translation.

However, currently when I create a new document, text translation is enabled.

If I enter an English prompt when text translation is enabled, the text content changes internally and I do not get the correct image.

Please make it so that it remembers the toggle status of text translation, as I keep forgetting to toggle it.

**Comment by Acly** [comment]
It is currently tracked and saved per document. I think that makes sense (you might use non-english prompt in one document but not another).

When creating a new document it's currently always enabled. I can change it to use the last-used setting. That would work for you?

**Comment by picolet21** [comment]
> When creating a new document it's currently always enabled. I can change it to use the last-used setting. That would work for you?

So please.

While creating images, I often create a temporary new document to work on. At that time I forget to toggle the text translation operation.

Please take care of this issue.

**Comment by Acly** [comment]
Should work in [v1.23.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.23.0)
