### ISSUE TITLE
Exception: Error during installation: ERROR: Could not find a version that satisfies the requirement torch 

### ISSUE THREAD

**Issue by flohh80** [Acly/krita-ai-diffusion#109]
Server configuration:
Exception: Error during installation: ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

2023-11-23 21:34:23,914 ERROR Installation failed

**Comment by Acly** [comment]
What's your OS & Python version?

**Comment by Acly** [comment]
I don't think pytorch is available yet for Python 3.12
See https://pytorch.org/get-started/locally/#linux-python
Try with 3.11

**Comment by SimonHeggie** [comment]
Thanks Acly, I'll give it a try. 

Is there something inside the add-on; like some meta date, readme or config that I can use to retrieve the recommended python version automatically? I extended my install script to include this as well as ai select. Only thing currently not working is that when ever a new version of python would be needed, I'd have to manually fix the installation script.

-S

**Comment by Acly** [comment]
Keep in mind PyTorch is one of many dependencies, all of which may require a certain range of Python version, which they usually don't declare, and could change daily, often by accident, without notice. So it might be practical to just hardcode it to 3.11 for now (I'm still using 3.10 for tests and installer)...
