### ISSUE TITLE
Mac ver. Error: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by PATMCG02** [Acly/krita-ai-diffusion#1092]
<img width="969" alt="Screenshot 2024-08-19 at 11 03 23 AM" src="https://github.com/user-attachments/assets/39fa2f78-50e5-41bc-9654-5e0da7b0b05b">
can not connect. can someone help

**Comment by Acly** [comment]
Please provide full error from client.log (click "View log files")
