### ISSUE TITLE
Thumb rule for step modifaction from fp32 to fp16?

### ISSUE THREAD

**Issue by Codeschreibaer** [Acly/krita-ai-diffusion#1093]
Hello!
The concern tells it all. I had to fore-fp16 (inestad normal)32 and now have much white or black pictures, since my old step settings for the models are too few. Do you have any thumb rule für adapting step amount? It seems due to some culminative effects on steps before just doubling the number is not enough. Thanks!

**Comment by Acly** [comment]
For diffusion fp16 is normal. RTX 30xx and 40xx use bf16. Nobody uses fp32 if they can help it.

I don't think there is a rule for step count, it probably just makes the symptom less likely if its more converged.

Maybe the issue is VAE? I'm not sure if this works, but worth a try:
```
--force-fp16 --fp32-vae
--fp16-unet --fp32-vae
```

**Comment by Codeschreibaer** [comment]
Thanks. I'll keep that in mind.
