### ISSUE TITLE
error while attempting to bind on address ('127.0.0.1', 8188): address already in use

### ISSUE THREAD

**Issue by PATMCG02** [Acly/krita-ai-diffusion#1096]
<img width="778" alt="Screenshot 2024-08-20 at 3 19 43 PM" src="https://github.com/user-attachments/assets/e199dab2-e8a5-491d-b8c2-cb82e8615217">
[client.log](https://github.com/user-attachments/files/16670590/client.log)
[server.log](https://github.com/user-attachments/files/16670593/server.log)

anyone can help??

**Comment by ichswarox** [comment]
reboot to see if system release 8188 port.

**Comment by guijiaosir** [comment]
https://www.youtube.com/playlist?list=PLbHwyRozz8GRL7pyOBHu44u8c9Cm94WLx
go to learn....

**Comment by FeepingCreature** [comment]
You can't have multiple comfyui running at the same time on the same port.
