### ISSUE TITLE
Pony Model Support

### ISSUE THREAD

**Issue by ichswarox** [Acly/krita-ai-diffusion#1097]
I check the doc but none of pony model was listed, if it's support in Krita Ai?

**Comment by Acly** [comment]
It works. 

Only caveat: if you do Fill/Expand you may want to choose "Custom" and disable "Seamless".

**Comment by tommywright** [comment]
I'm on latest and it just generates garbled images.. like a mosaic of colors. I'm using the same settings I use in ComfyUI (works fine there). What am I doing wrong?
