### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by GiChiken** [Acly/krita-ai-diffusion#11]
![image](https://github.com/Acly/krita-ai-diffusion/assets/96877334/6274659f-b11b-4908-b1b5-53fe05efbee1)

**Comment by GiChiken** [comment]
Manually installing PyQt seems to have fixed the problem

**Comment by Acly** [comment]
Thanks for reporting. The code is broken, but it only runs if there is some connection issue. 

> Manually installing PyQt seems to have fixed the problem

Was probably coincidence, Krita brings its own isolated Python with PyQt.
