### ISSUE TITLE
QA: How do we save the session?

### ISSUE THREAD

**Issue by gerroon** [Acly/krita-ai-diffusion#110]
Hi

Is there a way to save all the generated images with the krita file? I have been generating some images, not sure if I wil loose themif I restart Krita.

thanks

**Comment by Acly** [comment]
Generated images and all other per-document state is currently lost if you close the document. If you want to keep some generations you have to apply them so they are stored inside a layer.

Persisting the last x results and also the current prompt/strength/etc to .kra file would be neat.

**Comment by gerroon** [comment]
Is there a place where the images are saved temporarily? ComfyUI normally saves those images in `output` but I do not see them there.

**Comment by Acly** [comment]
No images are written to disk. That's quite intentional, it's overhead, and images accumulate quickly - unlike when you use Comfy directly it's not obvious that it happens and has to be cleaned up manually.
See also #181 #177

**Comment by Acly** [comment]
Done in [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0)
