### ISSUE TITLE
Server Configuration Issues

### ISSUE THREAD

**Issue by what-even-is-coding** [Acly/krita-ai-diffusion#1101]
I just discovered Krita & the AI Generation plugin- however, when I go to import the plugin and select "Local Managed Server" it gives me two dropdown options. 

* Run on CPU  
* Use Metal Performance Shader

the server path that pops up automatically is 
/User/(myname)/Library/Application Support/krita/ai_diffusion/server 

it gave me this error code:
- Error: [Errno 30] Read-Only file system.

So I changed the server path to the downloads folder & it gave me this code
- error code: Error During Installation. ERROR: Could Not Find A Version That Satisfies the Requirement Torch== 2.3.1 (from versions: 1.7.1, 1.8.0, ect.) ERROR: No matching distribution found for torch== 2.3.1

I am not good at the backend of computers, does anyone know where my issue lays? I do not have the ComfyUI software installed, I dont know if there is something I need to do with that, or some kind of Local Server I need to enquire?

**Comment by Acly** [comment]
You probably want "Metal Performance Shader"

> Could Not Find A Version That Satisfies the Requirement Torch== 2.3.1

This probably means the Python installed on your system is too old or new. You can check client.log ("View log files") for which version it is using.

**Comment by what-even-is-coding** [comment]
So I downloaded Python through my Terminal window and the lastest version it will let me download is 3.9. I tried reinstalling the software and it still gave me the error code- which appears to be requiring version 2.3.1 and that is so outdated that I cant seem to find a place to install it.

**Comment by Acly** [comment]
Python 3.9 is fine. I think newer macOS versions will let you use Python 3.10 or 3.11.

Don't confuse it with the version for Torch (2.3.1).

You have to make sure that the Krita plugin is using the Python you installed. Delete any previous server installation to restart the process. Please check client.log for the Python that is actually used.

I don't know if the Python you install via terminal is available system-wide by default, no idea how that works on mac.
