### ISSUE TITLE
[feature request] better inpaint content / mask control

### ISSUE THREAD

**Issue by StableLlama** [Acly/krita-ai-diffusion#1124]
There's a feature that I liked very well with A1111 but am missing now with Krita AI (which is a much better tool for inpainting over all):
The possibility to easily and exactly define what content / context is passed to the AI for inpainting.

At A1111 I can select whether the whole image or only the masked area (+ padding) it transferred to the AI. AFAIK only the later is possible with Krita AI. But sometimes it's important to give the AI the full context. Especially when I don't want to change the prompt to reflect only the little part that I have selected.

Also, AFAIK, Krita AI is only passing the mask + padding. That's nice. But sometimes I want the full image that's in the rectangle that bounds my selection.

=> According to my understanding I want two more modes and a top level (i.e. without the config menu) switch that allows me to choose which one I want right now:

1.  Krita AI default as it is
2. Bounding box around my selection
3. The full image

Of course the AI is still only allowed to inpaint inside of my selection.

And then there's an additional point:
The padding is currently in percentage of the selection, as far as I understood. So it's changing with my change of selection. Which is bad as it's creating unpredictable results. 
=> I'd like to be able to set it in pixels (or at least in percent of the image)
Best would be to have that on the top level as well (as does A1111) and not hidden in a config menu

**Comment by Drakosha405** [comment]
https://github.com/Acly/krita-ai-diffusion/wiki/Inpainting#context-area

**Comment by StableLlama** [comment]
That sounds like the solution - except that there's a but so that I can't use it with less than 100%.

I'm opening a report for that one, so this request can be closed.
