### ISSUE TITLE
External Server Setup

### ISSUE THREAD

**Issue by ludos1978** [Acly/krita-ai-diffusion#113]
Hi, 

i've been trying to setup my external server (because on osx the python version is difficult to get right and setup the way krita-ai needs it). However the names provided with the readme eigher seem to be outdated or not accurate enough to setup my system. I was only able to get the basic version running with trial and error or looking into the logfiles. I suggest adding the links for the required and suggested models to the User interface to make this simpler.

thank you for you work!

**Comment by Acly** [comment]
I've heard this before, but what exactly is supposed be outdated or not accurate? The links and paths look fine to me.

**Comment by Danamir** [comment]
The [Requirements for ComfyUI](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md) documentation is missing quite a few models, especially for the control layers.

But you can find all the required models URLs in the [resources.py](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py) file.

**Comment by ludos1978** [comment]
Yes, that's what I meant, sorry to be not that explicit. 

What might be added to the docs as well is the path for the installation "Unpack the archive into your pykrita folder":
OSX: "~/Library/Application Support/krita/pykrita/"

An alternative approach that would help me (and other developers that have brew python installed) would be to only download the models and rename them as needed into a folder, and not to manage/alter the comfyui installation.

**Comment by Acly** [comment]
I only listed the required models to get it running, the rest is optional and it sort of picks up most files if you downloaded them from a popular location.

> OSX: "~/Library/Application Support/krita/pykrita/"

Thanks I will add it to the Readme

> only download the models and rename them as needed into a folder

Actually this script exists in the repo, running
```
python scripts/docker.py
```
will do just that. I use it to set up docker build and test installation (it doesn't actually build the docker, just prepares all models). I could also ship it in the package with a different name, though I'm not sure how people will discover it unless they specifically look for something like that...

**Comment by Acly** [comment]
Related: the readme currently says for Linux "Python + venv must be installed".
Presumably this also applies to macOS, but I'm not sure what to write there, or how Python is typically/best installed.

**Comment by Acly** [comment]
Script is now part of the package in [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0) with updated documentation.
