### ISSUE TITLE
Filtering LoRAs by folder changes all active LoRAs

### ISSUE THREAD

**Issue by mvstrawn** [Acly/krita-ai-diffusion#1138]
What it says on the tin. If you have your LoRAs sorted into folders, and you filter them by folder, every active LoRA gets overwritten by the first LoRA in whatever folder you filtered by and reset to 100% strength.

**Comment by OMGrant** [comment]
Second this. Ran into this one immediately yesterday, permanently ruining one of my profiles.
I store each lora in it's own folder so I can include links to the lora's source like Civit.ai or Huggingface so I have an easier time reading up on their weights and triggers.

**Comment by Acly** [comment]
Maybe filter should only apply to newly added items?

Previous behavior (allow Lora that are technically filtered out and not part of the list) is tricky, it's not how the UI framework does it. Only worked because a lot of things were done manually, but that had other issues and I'd rather not go back.

Main idea was to filter LoRA by eg. SD15, SDXL... if you have only small amount (or 1) Lora in a folder, why bother with the filter? It's less clicks to just choose it directly?

**Comment by OMGrant** [comment]
I also have each lora separated by type, like concept, or style. And at this point I've collected hundreds of loras. Filtering by one of these folders helps in selecting what I'm looking for quicker. That aside, I don't think selecting a filter should automatically clear out all the previously applied loras with the first entry in the filter group. That's a rather destructive behavior. I think the filter should apply to the selection list only, whether its a new item or old.

**Comment by Acly** [comment]
I was looking for an alternative without destructive behavior, under the constraint that the UI element does not allow having an item selected that does not exist in its list of items.

**Comment by FeepingCreature** [comment]
It's just `LoraList._item_list`, right? That should be able to be filtered, because it's always required to be in sync with `_items` anyways, and `_items` is what's used to save via `value()`, right?

**Comment by Acly** [comment]
All Lora items have a ComboBox which now use the same `FileFilter(root.files.loras)` as item source (via `setModel`).

This ensures they're updated automatically when Lora are discovered, removed, uploaded, etc. via various means, and you can also simply set a filter on the model and everything works.

But if the current item of any ComboBox isn't in the list anymore, it will automatically select a default item. That's just baked in behavior of Qt, at least I don't know a way to change it (except implement all this stuff manually).

**Comment by Acly** [comment]
I think it's solved. (Hoping it didn't break something else)

**Comment by Acly** [comment]
Fixed in [1.24.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.24.0)
