### ISSUE TITLE
[QOL Requests] Few UX adjustments to make plugin even more user-friendly

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#114]
A list of adjustments which will make life with plugin easier:
- Exclude 'Strength' and '%' from string. There's no real need of those to be in type area
- Allow generation of not-only-one depth map per Krita session. Currently if you'll try to gen few depth maps for different layers, it won't allow you to do it
- Tap on header above the generated stack of images/areas to get that prompt, or, button to do so. Its really annoying to copy prompt from the layer name
- Global interference settings + toggle for presets to override global settings
- Button to clear all/current generated images/areas from the buffer
- Memorize last-used control map when you add a new control layer, instead having 'image' 
- Prevent cursor reset if you type new prompt during generation process, keep prompt window independent
- Auto-select last generated preview since it creates new layer and it is visible anyway, will eliminate double-clicking over and over again

Overall, the plugin is the greatest thing I ever used, please keep it up, it's amazing!

**Comment by Acly** [comment]
> Allow generation of not-only-one depth map per Krita session

Please elaborate? You should be able to generate as many depth maps as you like...

> Its really annoying to copy prompt from the layer name

I'm with you, which is why tap on header copies it to the clipboard. Yes that's totally indiscoverable :) I implemented it long ago, don't quite remember why I chose that over puting it directly into the prompt (maybe because it allows adding it to existing prompt rather then replacing it)


The last two I consider bugs, need to invest some time to deal with that properly.

**Comment by Acly** [comment]
> Exclude 'Strength' and '%' from string. There's no real need of those to be in type area

 I had it outside before, but didn't like it visually. Still easy to edit with slider, mouse wheel, double click IMO

> Memorize last-used control map when you add a new control layer, instead having 'image'

Done

> * Prevent cursor reset if you type new prompt during generation process, keep prompt window independent
> * Auto-select last generated preview since it creates new layer and it is visible anyway, will eliminate double-clicking over and over again

Those should be fixed ([1.9.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.9.0))

**Comment by FugueSegue** [comment]
> * Button to clear all/current generated images/areas from the buffer


I just started using this plugin and this is one of the first things I'm trying to figure out. Is there a solution to this?

**Comment by Acly** [comment]
Closing this, there is a separate issue #342 for delete results from history (not implemented yet)
