### ISSUE TITLE
AMD 6650M issue

### ISSUE THREAD

**Issue by tomperys** [Acly/krita-ai-diffusion#1140]
Is there any chance to get the plugin working with the 8G graphics in my HOP Omen 16 (AMD Radeon RX 6650M)? 

Because I tried to follow this guide (https://github.com/vladmandic/automatic/wiki/ZLUDA) and installed everything (used the Optimised_ROCmLibs_gfx1032.7z file) pick directly the C:\SDnext\ which should not be under admin priviledges (I dont have any sedond drive yet) and after I run the `webui.bat --use-zluda --debug --autolaunch` I ended up in this error in attached file
[logfile.txt.txt](https://github.com/user-attachments/files/16839884/logfile.txt.txt)

Iam not sure why it doesnt want to work :(

**Comment by tomperys** [comment]
Thanks I tried it but unfortunately cen not get it to work either it end up with "The procedure entry point hipDeviceSetLimit could not be found in the dynamic link library C:\Zluda\ComfyUI-Zluda\zluda\nvcuda.dll" so far no luct to find any solution for this :-(

**Comment by DGdev91** [comment]
The official version of ComfyUI already supports AMD gpus, but not trough Zluda.
you have two choices:

- DirectML on windows, wich is way slower, but still officially supported
- ROCm on Linux, a bit harder to install but much faster

They both need a manual installation and the official ComfyUI guithub doesn't explain it very well, but i'm sure there are some guides around.
