### ISSUE TITLE
[BUG] Lora on Flux doesn't work, 1:1 tests with Comfy included

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#1143]
I did a side-by-side comparison between how does LORA applied directly in Comfy vs Krita:
![image](https://github.com/user-attachments/assets/648a831f-9d02-471c-8028-f557bfca6740)

1 - I can't truly reproduce the same image with the same inputs, if even seed, resolution and prompt are identical, it's quite a challenge to find the same Guidance scale in Comfy to mimic what I see in Krita
2 - Applying lora doesn't do anything in Krita. Same lora in Comfy adds drastic changes to the image
3 - On top of the issue, Krita plugin takes more VRAM than Comfy with the same checkpoint
15228mb on Comfy, 19442mb on Krita
![image](https://github.com/user-attachments/assets/090a7208-18d2-4e11-9119-6f6131432d88)

Prompt:
Fauvism art style, a stylized illustration of a white cat with glass of red wine. Dark blue background.

Seed:  262
Resolution: 1024x1024
let me know if you need a lora file to test (or you can practically pick any lora from CivitAI for test)

**Comment by Acly** [comment]
If you use the same workflow as the plugin in Comfy, images, RAM, etc are exactly the same.
If you use a different workflow... they will be different.

That being said, you can dump the workflow to the log folder (Interface settings > Dump Workflow) to compare. It's the most direct way to figure out what might be going wrong.

Technically adding Lora just adds the Lora loader. It works fine for me.

The guidance is always default (3.5) at the moment. I linked it to the slider to make it configurable in https://github.com/Acly/krita-ai-diffusion/commit/13e613ff6a52142f7e74c139600d4710ba65ea13 (unreleased)
