### ISSUE TITLE
Error in Stable Diffusion ussing Krita

### ISSUE THREAD

**Issue by SomeshBhatti** [Acly/krita-ai-diffusion#1145]
Hi, i am getting this error using stable diffusion AI image generation in krita
can somebody help me on this one?
![2024-09-04_10-51](https://github.com/user-attachments/assets/566b9431-a3a4-4876-adee-c321f6c992e5)
[server.log](https://github.com/user-attachments/files/16861172/server.log)

**Comment by guijiaosir** [comment]
It is recommended to deploy comfyUI locally! You can use the comfyUI integration package.

**Comment by Acly** [comment]
This should no longer be a problem in latest version. See #965 for history
