### ISSUE TITLE
Server execution error

### ISSUE THREAD

**Issue by jovGith** [Acly/krita-ai-diffusion#1149]
i downloaded Krita because some images im trying to use have sections cut off, so the only feature im trying to get working is the expand feature which im assuming is similar to Gen fill on PS. 

(also if there's a mode to delete a background that would also be extremely helpful to me)

my issue is whenever i make a selection to the image and hit expand, it will take INSANELY long to get up to around the 80% mark (10-20 mins) and it wont even generate what i selected. instead i get this error

### Server execution error: Could not allocate tensor with 26214400 bytes. There is not enough GPU video memory available!

i have it set up with the local managed server and have a AMD 6600xt gpu. 

im confused because in some of the videos I've seen, they have way worse gpus than mine but are able to generate complete images from scratch, meanwhile im not even able to generate a characters elbow that got cut off. 

So far ive tried
-using XL and 1.5 and i get the same error with both
-have lowered the GPU preset from high to low neither work
-have lowered the sampler steps in the quality preset
-and i've already encountered the numpy error because im on an AMD gpu and downgraded that using command prompt.

This is my first time ever using any AI image app so im assuming i did something wrong while installing but i have no idea how to fix whatever is wrong.

**Comment by jovGith** [comment]
did more searching and am now doomed because i did nothing wrong besides own an AMD card apparently lmao. if there is a solution outside of switching to linux/getting a new computer that would be nice, but if not ill have to just keep this app in mind if i ever do upgrade.

**Comment by Acly** [comment]
The biggest influence on performance/memory is resolution.

But yea, AMD on Windows is not in a great state and that won't change overnight. Cloud compute might be an alternative (not free but maybe cheaper than upgrading).
