### ISSUE TITLE
FLUX Support 

### ISSUE THREAD

**Issue by metamountain** [Acly/krita-ai-diffusion#1152]
Would be cool if Flux support could be implemented !  Inpainting is quite easy with FLUX!

**Comment by waynemadsen** [comment]
Flux is implemented as of version 1.22

**Comment by NoMansPC** [comment]
Inpainting works with Flux? On Forge, it always gives me nonsensical images.

**Comment by Acly** [comment]
> Inpainting works with Flux?

No, not really. People have different understanding of what "inpainting" means.

**Comment by waynemadsen** [comment]
Could you help me to understand why Flux behaves differently than SD on inpainting? I've noticed that img2img behaves wildly different when using flux in comfy as it does in SD. I have to use much higher incoming latent noise values on Flux to make it do the same thing in SDXL. In Krita with my Schnell model, I seem to be able to locally do something akin to inpainting with selection, but the refine levels are VERY different often needing to run a 97% refine to get a suitable change.
Maybe I don't understand clearly what 'inpainting' means.

It seems that people have offered solutions to doing inpainting in flux:
https://github.com/black-forest-labs/flux/issues/26
https://huggingface.co/spaces/SkalskiP/FLUX.1-inpaint
https://github.com/huggingface/diffusers/pull/9135

**Comment by Acly** [comment]
[v1.25.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.25.0) has inpainting (this means 100% strength)

Img2img (lower strength) works similar to SDXL for me, ie. range 40% - 90% result in gradually more impactful changes. With some jumps here and there.
