### ISSUE TITLE
FLUX -KRITA -COMFYUI - webui question

### ISSUE THREAD

**Issue by guijiaosir** [Acly/krita-ai-diffusion#1153]
closed

**Comment by guijiaosir** [comment]
![df42cf71-7e56-4323-acc2-2ded0673de0e](https://github.com/user-attachments/assets/31e69949-85f3-4b0b-b7fa-4c2658d90fdb)
This is what I made with krita AI SD1.5+FLUX
But using the FLUX model directly in krita feels problematic. Don't know why.

Best quality,masterpiece,8K,ultra high res,single background,realistic,photography,studio shooting,clarity,high detail,high quality,detailed clothes,detailed body,detailed face,intricate detail,detailed eyes,soft lighting,Photography, studio photography,photo realism,realistic,photorealistic,extremely_detailed_eyes_and_face,guijiaoxiansheng,1girl, scene, black stockings, focused feet, indoor feet,

![image](https://github.com/user-attachments/assets/cd84897d-2864-4e95-a443-7ea4539e0d36)
![image](https://github.com/user-attachments/assets/cbcdb2ad-c54b-4142-8f94-60e301aa1e2b)

**Comment by FeepingCreature** [comment]
Did you use the exact same seed and workflow? Generations are randomized.
