### ISSUE TITLE
 The server is missing the IP-Adapter model reference whern use flux model

### ISSUE THREAD

**Issue by arduino2018** [Acly/krita-ai-diffusion#1154]
The server is missing the IP-Adapter model reference whern use flux model
![ip-adapter-missing](https://github.com/user-attachments/assets/1fbf908a-1a14-4b90-849d-3c8a799d018b)
I have download https://huggingface.co/XLabs-AI/flux-ip-adapter model and put to models\ipadapter , but the question remains.
Which flux ip-adapter should to add?

**Comment by guijiaosir** [comment]
Not supported yet

**Comment by Acly** [comment]
Tracking in https://github.com/Acly/krita-ai-diffusion/discussions/1176

So far IP-Adapter model is not working great and XLabs implementation doesn't integrate with the rest of the pipeline.

**Comment by GumDeveloper** [comment]
any ETA ?
