### ISSUE TITLE
Server Execution error :- Numpy is not available

### ISSUE THREAD

**Issue by codeloveranish** [Acly/krita-ai-diffusion#1157]
when i use ai feature of kirta so its showing me this error Server Execution error :- Numpy is not available
i check all the server python file that have numpy file but it's also showing me this error
please help me this is very important issue for me........
![Screenshot 2024-09-07 101922](https://github.com/user-attachments/assets/f84aa652-ed37-4307-a9d6-e0ecd692dd49)

**Comment by Acly** [comment]
#1130 #1135

**Comment by Acly** [comment]
Latest versions should install older Numpy to avoid this.
