### ISSUE TITLE
Module not loading

### ISSUE THREAD

**Issue by Guzzlerone** [Acly/krita-ai-diffusion#1164]
![Cattura](https://github.com/user-attachments/assets/2138cd65-9c5c-4f71-849b-b3c8882bfbff)

Similary to the example error, the plugin is grayed out in the plugin manager, but even after following the steps to fix the problem nothing changed (I installed the relese package as sugested). The error is kinda different from the one showed in the example too. I tried to install older versions but nothing changed. The logs are empty.

I apologise if i this is some easyly fixable issue or if i miss interpreted the gudelines, but i'm not very handy with these topics

**Comment by Acly** [comment]
Looks like an old Krita version? Minimum 5.2 is required.
