### ISSUE TITLE
Flux inpainting

### ISSUE THREAD

**Issue by metamountain** [Acly/krita-ai-diffusion#1165]
Doesnt really work in Krita , If you have time , check my comfy workflow.

![image](https://github.com/user-attachments/assets/9f78b09f-aa74-4a4a-a333-d59ccbace333)

Model sampling values  are the most important part. The upper value is similar as denoising rate...
I put in a differential diffusion node , its supposed to take care of the mask gradient ....
I have not yet myself understtood how this beast work ;(

![ComfyUI_temp_asvgg_00007_](https://github.com/user-attachments/assets/56a1d540-b5c7-43a4-b72a-33eb25e13a9c)
![ComfyUI_temp_asvgg_00006_](https://github.com/user-attachments/assets/9087e0bd-7509-48e3-a42d-15c3973972d2)
![ComfyUI_temp_asvgg_00005_](https://github.com/user-attachments/assets/2989d167-8d47-407f-a63d-9c1566b787c4)
![ComfyUI_temp_asvgg_00004_](https://github.com/user-attachments/assets/fe5463b5-cde4-4a60-a489-be9949e4b9c8)
![ComfyUI_temp_asvgg_00009_(1)](https://github.com/user-attachments/assets/1eccd8e8-80b9-4783-a740-a560107fa80d)

[Flux Inpaint(1).json](https://github.com/user-attachments/files/16936417/Flux.Inpaint.1.json)
![ComfyUI_temp_icrqz_00001_](https://github.com/user-attachments/assets/63df8801-e661-4c38-bae9-278d473528c8)

**Comment by Acly** [comment]
Initial inpaint support is in [v1.25.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.25.0)
