### ISSUE TITLE
Max seed value is 2147483647.

### ISSUE THREAD

**Issue by OMGrant** [Acly/krita-ai-diffusion#1171]
In researching this issue, I found that 2147483647 is the max value variables declared as integers can have. Unfortunately this often conflicts with the ability to enter seed values from external sources that are above this value, e.g. matching the configuration of published outputs from sites like Civit.ai, who's seed values can exceed this.

**Comment by Acly** [comment]
See #597 - I don't really see the point in copying seeds from civitai, you need exact matching systems for seed values to have meaning. Rather it's there to experiment and observe changes without randomness by switching between fixed/not-fixed.

**Comment by OMGrant** [comment]
@Acly Understood. To elaborate though, the use case is really simple. CivitAI provides the checkpoints, LoRAs, and exact weights of each per image generated on the site, along wit the prompts needed to create them. It's easy to match the configuration locally and generate an image _near_ identical if the seed happens to be within the 2147483647 window. 

I often use CivitAI as a visual catalog of working prompts to use as a starting point. If I'm looking for a generation that captures the look/context I'm trying to generate, starting from the same seed makes a big difference.  

Thanks.
