### ISSUE TITLE
error in the finish of image generation

### ISSUE THREAD

**Issue by 1MB4R0SS4** [Acly/krita-ai-diffusion#1182]
STEPS TO REPRODUCE
generate an image with krita

OBSERVED RESULT
even tho it finishes in the terminal, in krita it couses error
![Képernyőkép 2024-09-14 124001](https://github.com/user-attachments/assets/08d2fd32-a1f4-4f42-8960-83c24e1abf88)

EXPECTED RESULT
it generates the image

SOFTWARE/OS VERSIONS
Windows: 11 Pro, 23H2

ADDITIONAL INFORMATION

IndexError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Sat Sep 14 12:30:14 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\baros\AppData\Roaming\krita\pykrita\ai_diffusion\model.py in update_preview(self=<ai_diffusion.model.Model object>)
  444     def update_preview(self):
  445         if selection := self.jobs.selection:
  446             self.show_preview(selection.job, selection.image)
  447         else:
  448             self.hide_preview()
self = <ai_diffusion.model.Model object>
self.show_preview = <bound method Model.show_preview of <ai_diffusion.model.Model object>>
selection = Item(job='52675a1a-f576-4466-8e6c-97508e80b7a7', image=0)
selection.job = '52675a1a-f576-4466-8e6c-97508e80b7a7'
selection.image = 0

 C:\Users\baros\AppData\Roaming\krita\pykrita\ai_diffusion\model.py in show_preview(self=<ai_diffusion.model.Model object>, job_id='52675a1a-f576-4466-8e6c-97508e80b7a7', index=0, name_prefix='Preview')
  460         else:
  461             self._layer = self.layers.create(
  462                 name, job.results[index], job.params.bounds, make_active=False
  463             )
  464             self._layer.is_locked = True
name = '[Preview] taylor swift on stage at a concert taking a selfie, colors: blue, orange, ...'
job = <ai_diffusion.jobs.Job object>
job.results = <ai_diffusion.image.ImageCollection object>
index = 0
job.params = JobParams(bounds=Bounds(x=0, y=0, width=1024, he...has_mask=False, frame=(0, 0, 0), animation_id='')
job.params.bounds = Bounds(x=0, y=0, width=1024, height=1024)
make_active undefined

 C:\Users\baros\AppData\Roaming\krita\pykrita\ai_diffusion\image.py in __getitem__(self=<ai_diffusion.image.ImageCollection object>, i=0)
  663 
  664     def __getitem__(self, i: int):
  665         return self._items[i]
  666 
  667     def __iter__(self):
self = <ai_diffusion.image.ImageCollection object>
self._items = []
i = 0
IndexError: list index out of range
    __cause__ = None
    __class__ = <class 'IndexError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of IndexError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of IndexError object>
    __doc__ = 'Sequence index out of range.'
    __eq__ = <method-wrapper '__eq__' of IndexError object>
    __format__ = <built-in method __format__ of IndexError object>
    __ge__ = <method-wrapper '__ge__' of IndexError object>
    __getattribute__ = <method-wrapper '__getattribute__' of IndexError object>
    __gt__ = <method-wrapper '__gt__' of IndexError object>
    __hash__ = <method-wrapper '__hash__' of IndexError object>
    __init__ = <method-wrapper '__init__' of IndexError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of IndexError object>
    __lt__ = <method-wrapper '__lt__' of IndexError object>
    __ne__ = <method-wrapper '__ne__' of IndexError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of IndexError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of IndexError object>
    __repr__ = <method-wrapper '__repr__' of IndexError object>
    __setattr__ = <method-wrapper '__setattr__' of IndexError object>
    __setstate__ = <built-in method __setstate__ of IndexError object>
    __sizeof__ = <built-in method __sizeof__ of IndexError object>
    __str__ = <method-wrapper '__str__' of IndexError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('list index out of range',)
    with_traceback = <built-in method with_traceback of IndexError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\baros\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 446, in update_preview
    self.show_preview(selection.job, selection.image)
  File "C:\Users\baros\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 462, in show_preview
    name, job.results[index], job.params.bounds, make_active=False
  File "C:\Users\baros\AppData\Roaming\krita\pykrita\ai_diffusion\image.py", line 665, in __getitem__
    return self._items[i]
IndexError: list index out of range

**Comment by Acly** [comment]
This happens only if execution is cached? Ie. trying to generate again with same parameters and same seed.

It kinda looks like that from the console log, the last prompt didn't produce an image because nothing changed.

I wasn't able to reproduce it though, even with fixed seed / cached prompt. Which version of the plugin are you using?

**Comment by 1MB4R0SS4** [comment]
Version 1.24.0

with previous versions, I had similar problems. I would try to generate an image, and although the terminal showed it was done, nothing appeared in krita. I had to attempt generating the image several times to make it work, but there were no error messages about it. now, sometimes an error message appears, and I’m unable to regenerate any images later on, so I have to reload krita to make it work again.

**Comment by Acly** [comment]
The "no image" case is handled now and there's some more error reporting for spurious connection issues.
