### ISSUE TITLE
'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by CannibalKush** [Acly/krita-ai-diffusion#1184]
Firstly, thanks for adding Flux support. The instructions outlined in [this guide](https://github.com/Acly/krita-ai-diffusion/discussions/1176) work great!

However, when I try a specific popular flux checkpoint found on Civitai, I get the error `'NoneType' object has no attribute 'tokenize'`.

In my client.log, it shows:

```
2024-09-15 00:17:06,624 ERROR Job Job[local=373959a4-4f30-4099-a27d-492d62524497, remote=9567c79b-0807-4a95-a6e1-db31eeef12ea] failed: 'NoneType' object has no attribute 'tokenize'
['  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 323, in execute\n    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n', '  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 198, in get_output_data\n    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n', '  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 169, in _map_node_over_list\n    process_inputs(input_dict, i)\n', '  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 158, in process_inputs\n    results.append(getattr(obj, func)(**inputs))\n', '  File "H:\\Krita\\server\\ComfyUI\\nodes.py", line 64, in encode\n    tokens = clip.tokenize(text)\n']
```

Seems we're having trouble finding the correct clip or something. The model uses `t5xxl_fp8_e4m3fn.safetensors` I believe, and the file is present in my clip folder as outlined in above guide.

Am I missing something simple?

**Comment by Acly** [comment]
Which folder did you put it in? If it needs T5 as external file it should go into `diffusion_models`.

**Comment by sunnysnake** [comment]
> Firstly, thanks for adding Flux support. The instructions outlined in [this guide](https://github.com/Acly/krita-ai-diffusion/discussions/1176) work great!
> 
> However, when I try a specific popular flux checkpoint found on Civitai, I get the error `'NoneType' object has no attribute 'tokenize'`.
> 
> In my client.log, it shows:
> 
> ```
> 2024-09-15 00:17:06,624 ERROR Job Job[local=373959a4-4f30-4099-a27d-492d62524497, remote=9567c79b-0807-4a95-a6e1-db31eeef12ea] failed: 'NoneType' object has no attribute 'tokenize'
> ['  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 323, in execute\n    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n', '  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 198, in get_output_data\n    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n', '  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 169, in _map_node_over_list\n    process_inputs(input_dict, i)\n', '  File "H:\\Krita\\server\\ComfyUI\\execution.py", line 158, in process_inputs\n    results.append(getattr(obj, func)(**inputs))\n', '  File "H:\\Krita\\server\\ComfyUI\\nodes.py", line 64, in encode\n    tokens = clip.tokenize(text)\n']
> ```
> 
> Seems we're having trouble finding the correct clip or something. The model uses `t5xxl_fp8_e4m3fn.safetensors` I believe, and the file is present in my clip folder as outlined in above guide.
> 
> Am I missing something simple?

same to you, I tried using ae.safetensors or placing T5 in the diffusion_models folder, but still got the same error.

**Comment by Acly** [comment]
I meant whatever "checkpoint" you downloaded might have to go into diffusion_models. Can't really say without seeing the model.

T5 should always be in clip.

**Comment by maplecasino** [comment]
Is this issue related to https://github.com/comfyanonymous/ComfyUI/issues/4624#issuecomment-2311971542 ?

> These smaller models ( ~ 11 GB ), don't have CLIP/text encoder weights. The larger ones ( ~ 22 GB ) also don't have CLIP/text encoder weights ( but they are in FP16 format, instead of FP8 ).
> 
> For them, you use the UNET loader.
> 
> https://comfyanonymous.github.io/ComfyUI_examples/flux/
> 
> ![unet](https://private-user-images.githubusercontent.com/72734038/361731201-28f99366-322b-46cb-a6b0-28ea3ae1c1a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5Mzg0NjksIm5iZiI6MTcyNjkzODE2OSwicGF0aCI6Ii83MjczNDAzOC8zNjE3MzEyMDEtMjhmOTkzNjYtMzIyYi00NmNiLWE2YjAtMjhlYTNhZTFjMWEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE3MDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYmVkZmJlMGJiYjhlNTA5ZmE3NzA1MGFmNWVkOWVkN2U4ZjY0YjYyY2VlOGY2ZTEwOGY1ZTE3M2E5MzY2MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SPOnAtoxM4CEwXI6QBFj-pBcsTNk0TEIrhNiwevmIy4)
> 
> Only the ones with 15 GB ~ 17 GB are checkpoint versions and include CLIP/text encoder weights ( they are all in FP8 ).

**Comment by mysticfall** [comment]
I have a similar problem with this particular model (the main download, i.e. 11.08Gb f16 version):

https://civitai.com/models/161068/stoiqo-newreality-flux-sd-xl-lightning

The model has the `.safetensors` extension. If I put it under `diffusion_models`, it doesn't appear in Krita. And, if I move it to the `checkpoints` directory, it is listed but fails with the same error as shown above.

I have no problem with the 20.34Gb fp8 version, which seems to include the text encoder and clip. And I have `t5xxl_fp8_e4m3fn.safetensors` and `clip_l.safetensors` in my `models/clip` folder.

Am I missing something?

**Comment by Acly** [comment]
It should work. Make sure you have latest versions. Verify it's listed in http://127.0.0.1:8188/api/etn/model_info/diffusion_models

**Comment by mysticfall** [comment]
> It should work. Make sure you have latest versions. Verify it's listed in http://127.0.0.1:8188/api/etn/model_info/diffusion_models

I think I already have everything up-to-date. The endpoint in question shows a suspicious error, however:

```json
{
  "FLUX1/stoiqoNewrealityFLUXSD_f1DAlphaTwo.safetensors": {
    "base_model": "unknown", 
    "error": "Failed to detect base model: argument of type 'NoneType' is not iterable"
}}
```

If there's anything I can help debug the issue please let me know.

**Comment by mysticfall** [comment]
> Looks like that model uses some prefix that is usually used by checkpoints (Flux base model does not do this).
> 
> It should be detected if you update comfyui-tooling-nodes: [Acly/comfyui-tooling-nodes@20c8039](https://github.com/Acly/comfyui-tooling-nodes/commit/20c8039a98e69b93ba7e58ac2e2cef846f2072c2)

I just tested the patch and it fixed my problem, indeed. The model now works flawlessly on Krita.

Thanks much for the help!

**Comment by oleshanepro** [comment]
> Looks like that model uses some prefix that is usually used by checkpoints (Flux base model does not do this).
> 
> It should be detected if you update comfyui-tooling-nodes: [Acly/comfyui-tooling-nodes@20c8039](https://github.com/Acly/comfyui-tooling-nodes/commit/20c8039a98e69b93ba7e58ac2e2cef846f2072c2)

Could you please tell me what I'm doing wrong? I updated comfyui-tooling-nodes, added fluxTextencoderT5XxlFp8_v10 to the diffusion_models folder, but it still says 'NoneType' object has no attribute 'tokenize'. I use the https://civitai.com/models/141592/pixelwave  model 
![image](https://github.com/user-attachments/assets/c24a33b6-347a-4766-b790-98c777e41164)

**Comment by oleshanepro** [comment]
> > Looks like that model uses some prefix that is usually used by checkpoints (Flux base model does not do this).
> > It should be detected if you update comfyui-tooling-nodes: [Acly/comfyui-tooling-nodes@20c8039](https://github.com/Acly/comfyui-tooling-nodes/commit/20c8039a98e69b93ba7e58ac2e2cef846f2072c2)
> 
> Could you please tell me what I'm doing wrong? I updated comfyui-tooling-nodes, added fluxTextencoderT5XxlFp8_v10 to the diffusion_models folder, but it still says 'NoneType' object has no attribute 'tokenize'. I use the https://civitai.com/models/141592/pixelwave model ![image](https://private-user-images.githubusercontent.com/135276140/380436003-c24a33b6-347a-4766-b790-98c777e41164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NjAyNDQsIm5iZiI6MTcyOTk1OTk0NCwicGF0aCI6Ii8xMzUyNzYxNDAvMzgwNDM2MDAzLWMyNGEzM2I2LTM0N2EtNDc2Ni1iNzkwLTk4Yzc3N2U0MTE2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNjI1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTY1NWEyZTJhNzM0NzQxZDBiYWE0MGM4NGQyYTIwNWM2YTIxZTYwNzg3MTEyZGM2NWY5YmFkZWFiMzY4ZWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iX79OgLEA6VwH0yxmbPSGF8yIAd0C8E3ADnH6Lthaac)

so I added the checkpoint to Diffusion_models and it works fine, thanks for your great work!
