### ISSUE TITLE
installing IP-Adapter Face (XL) give ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by marcoA152** [Acly/krita-ai-diffusion#1186]
hello to all, 
after a fresh install of 1.24.0 plugin, I have this error while installing IP-Adapter Face (XL)
I'm running Python 3.11.9 (from automatic local install) on windows
same error with 1.5 controlnet workload (only for face ipadapter)

here an extract from the log:
Traceback (most recent call last):
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 297, in download
    await self._install_requirements(resource.requirements, network, cb)
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 237, in _install_requirements
    await self._install_insightface(network, cb)
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 229, in _install_insightface
    await _execute_process("FaceID", self._pip_install(whl_file), self.path, cb)
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 557, in _execute_process
    raise Exception(_("Error during installation") + f": {errlog}")
Exception: Error during installation: ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

![Screenshot 2024-09-15 214612](https://github.com/user-attachments/assets/53803a10-761a-4fd8-a757-f1f138eea203)

thanks for your (great) work!

**Comment by marcoA152** [comment]
here last dump of the log (with onnx versions):


2024-09-16 11:50:12,987 INFO Executing C:\ComfyUI_windows_portable\krita1\python\python.exe -su -m pip install onnxruntime
2024-09-16 11:50:14,167 INFO Requirement already satisfied: onnxruntime in c:\comfyui_windows_portable\krita1\python\lib\site-packages (1.19.2)
2024-09-16 11:50:14,167 INFO Requirement already satisfied: coloredlogs in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from onnxruntime) (15.0.1)
2024-09-16 11:50:14,167 INFO Requirement already satisfied: flatbuffers in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from onnxruntime) (24.3.25)
2024-09-16 11:50:14,167 INFO Requirement already satisfied: numpy>=1.21.6 in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from onnxruntime) (1.26.3)
2024-09-16 11:50:14,168 INFO Requirement already satisfied: packaging in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from onnxruntime) (24.1)
2024-09-16 11:50:14,168 INFO Requirement already satisfied: protobuf in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from onnxruntime) (4.25.4)
2024-09-16 11:50:14,168 INFO Requirement already satisfied: sympy in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from onnxruntime) (1.12)
2024-09-16 11:50:14,168 INFO Requirement already satisfied: humanfriendly>=9.1 in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from coloredlogs->onnxruntime) (10.0)
2024-09-16 11:50:14,168 INFO Requirement already satisfied: mpmath>=0.19 in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from sympy->onnxruntime) (1.3.0)
2024-09-16 11:50:14,168 INFO Requirement already satisfied: pyreadline3 in c:\comfyui_windows_portable\krita1\python\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime) (3.5.2)
2024-09-16 11:50:14,794 INFO Using C:\ComfyUI_windows_portable\krita1\.cache\insightface-0.7.3-cp310-cp310-win_amd64.whl
2024-09-16 11:50:14,795 INFO Executing C:\ComfyUI_windows_portable\krita1\python\python.exe -su -m pip install C:\ComfyUI_windows_portable\krita1\.cache\insightface-0.7.3-cp310-cp310-win_amd64.whl
2024-09-16 11:50:16,453 ERROR Error during installation: ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
Traceback (most recent call last):
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 297, in download
    await self._install_requirements(resource.requirements, network, cb)
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 237, in _install_requirements
    await self._install_insightface(network, cb)
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 229, in _install_insightface
    await _execute_process("FaceID", self._pip_install(whl_file), self.path, cb)
  File "C:\Users\Pc\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 557, in _execute_process
    raise Exception(_("Error during installation") + f": {errlog}")
Exception: Error during installation: ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

**Comment by Acly** [comment]
https://github.com/Acly/krita-ai-diffusion/commit/e6301fb1754f3bfb43afaf5412f8ab2efa807c03 should fix it, the important part is to change the URL to the Python3.11 version

**Comment by marcoA152** [comment]
thanks, server.py updated and plugin reinstalled, now model download works but got this new error generating with ipadapter face controlnet:

2024-09-16 12:23:06,581 ERROR Job Job[local=052d5d44-4da0-4518-bfd6-2b6fc025f87f, remote=7ed915ef-50b2-4c93-bd33-dfd2411c8b45] failed: DLL load failed while importing onnx_cpp2py_export: Routine di inizializzazione della libreria di collegamento dinamico (DLL) non riuscita.
['  File "C:\\ComfyUI_windows_portable\\krita1\\ComfyUI\\execution.py", line 323, in execute\n    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\ComfyUI_windows_portable\\krita1\\ComfyUI\\execution.py", line 198, in get_output_data\n    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\ComfyUI_windows_portable\\krita1\\ComfyUI\\execution.py", line 169, in _map_node_over_list\n    process_inputs(input_dict, i)\n', '  File "C:\\ComfyUI_windows_portable\\krita1\\ComfyUI\\execution.py", line 158, in process_inputs\n    results.append(getattr(obj, func)(**inputs))\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\ComfyUI_windows_portable\\krita1\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus\\IPAdapterPlus.py", line 674, in load_insightface\n    return (insightface_loader(provider, model_name=model_name),)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\ComfyUI_windows_portable\\krita1\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus\\utils.py", line 161, in insightface_loader\n    raise Exception(e)\n']

**Comment by KrissOk1** [comment]
Hiya, just created an account to share my solve in Krita (local managed server). I know pretty much nothing about coding, but solution I found :)
Seems the latest Krita Ai python scripts directs to download the latest release, which installs Python 3.11.9 (right now, 16th of sept. 2024). Conflict ensues because Krita is set to install the 310 version of the IP-Adapter rather than the 311.
Ok, so then point Krita to install the 311 version.

What to do:
Unzip the downloaded script file (the one intended to be run from 'tools' in Krita. At the time of writing it is 'krita_ai_diffusion-1.24.0.zip'. One file ("ai-diffusion.desktop") and one folder will be extracted. In the folder 'ai_diffusion', open the file 'settings.py' in a text editor. Find the line "_install_insightface". A couple of lines down it says   "whl_file = self._cache_dir / "insightface-0.7.3-cp310-cp310-win_amd64.whl", Change the 310 to 311.
Beneath that is the URL it gets the file from. I changed to the location I've currently got for the file, so that line is:
whl_url = "https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl"

Save the file.

Now make a zip file with the folder "ai-diffusion" and the file "ai_diffusion.desktop", you can name it whatever. Start, or restart, Krita, go to tools > scripts > import python plugin from file and choose the zip you just made, click 'ok' when asked to overwrite (or whatever the prompts was).
Then open the AI-image docker > configuration > Connection and check the IP-Adapters > press install. Presto!

Trying to write so fellow n00bs can follow.

**Comment by marcoA152** [comment]
> Hiya, just created an account to share my solve in Krita (local managed server). I know pretty much nothing about coding, but solution I found :) Seems the latest Krita Ai python script directs to download the latest release of Python, which installs Python 3.11.9 (right now, 16th of sept. 2024). Conflict ensues because Krita is then set to install the 310 version of the IP-Adapter rather than the 311.
> 
> Ok, probleme, so, then point Krita to install the compatible 311 version of the IP-adapter, m'kay?
> 
> What to do: Unzip the downloaded script file (the one intended to be run from 'tools' in Krita. At the time of writing it is 'krita_ai_diffusion-1.24.0.zip'. One file ("ai-diffusion.desktop") and one folder will be extracted. In the folder 'ai_diffusion', open the file 'server.py' in a text editor. Find the line "_install_insightface". A couple of lines down it says "whl_file = self._cache_dir / "insightface-0.7.3-cp310-cp310-win_amd64.whl", Change the 310 to 311. Beneath that is the URL it gets the file from. I changed to the URL I've currently got for the file, so that line is: whl_url = "https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl"
> 
> Save the file.
> 
> Now make a zip file with the folder "ai-diffusion" and the file "ai_diffusion.desktop", you can name it whatever. Start, or restart, Krita, go to tools > scripts > 'import python plugin from file', and choose the zip you just made. Click 'ok' when asked to overwrite (or whatever the prompts was). Restart Krita. Open new file. Then open the AI-image docker > configuration > 'Connection' and check the 'IP-Adapters' > press install. Presto!
> 
> Trying to write so fellow n00bs like myself can follow.
> 
> (btw, I tried several other tips, of which I could get none working with local server in Krita)


:/  these lines are on the server.py file (on settings.py there are other things) and are already correctly linked to 311 version by Acly
thanks anyway for your suggestion! maybe something in .cache folder? i have found a insightface-0.7.3-cp310-cp310-win_amd64.whl in it

![image](https://github.com/user-attachments/assets/32ca68ac-45aa-4bb4-a112-73f0383abcc9)

**Comment by KrissOk1** [comment]
> > Hiya, just created an account to share my solve in Krita (local managed server). I know pretty much nothing about coding, but solution I found :) Seems the latest Krita Ai python script directs to download the latest release of Python, which installs Python 3.11.9 (right now, 16th of sept. 2024). Conflict ensues because Krita is then set to install the 310 version of the IP-Adapter rather than the 311.
> > Ok, probleme, so, then point Krita to install the compatible 311 version of the IP-adapter, m'kay?
> > What to do: Unzip the downloaded script file (the one intended to be run from 'tools' in Krita. At the time of writing it is 'krita_ai_diffusion-1.24.0.zip'. One file ("ai-diffusion.desktop") and one folder will be extracted. In the folder 'ai_diffusion', open the file 'server.py' in a text editor. Find the line "_install_insightface". A couple of lines down it says "whl_file = self._cache_dir / "insightface-0.7.3-cp310-cp310-win_amd64.whl", Change the 310 to 311. Beneath that is the URL it gets the file from. I changed to the URL I've currently got for the file, so that line is: whl_url = "https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl"
> > Save the file.
> > Now make a zip file with the folder "ai-diffusion" and the file "ai_diffusion.desktop", you can name it whatever. Start, or restart, Krita, go to tools > scripts > 'import python plugin from file', and choose the zip you just made. Click 'ok' when asked to overwrite (or whatever the prompts was). Restart Krita. Open new file. Then open the AI-image docker > configuration > 'Connection' and check the 'IP-Adapters' > press install. Presto!
> > Trying to write so fellow n00bs like myself can follow.
> > (btw, I tried several other tips, of which I could get none working with local server in Krita)
> 
> :/ these lines are on the server.py file (on settings.py there are other things) and are already correctly linked to 311 version by Acly thanks anyway for your suggestion! maybe something in .cache folder? i have found a insightface-0.7.3-cp310-cp310-win_amd64.whl in it
> 
> ![image](https://private-user-images.githubusercontent.com/65495051/368015758-32ca68ac-45aa-4bb4-a112-73f0383abcc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTEyMTksIm5iZiI6MTcyNjU1MDkxOSwicGF0aCI6Ii82NTQ5NTA1MS8zNjgwMTU3NTgtMzJjYTY4YWMtNDVhYS00YmI0LWExMTItNzNmMDM4M2FiY2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA1MjgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZmU2N2NlNThjMzhjZmVjMTk1ODBjY2IyMGQ4YjE0MGQzM2I3ZjIyMWU2MTU5MzkwMzQzYmUxYTg4ZGFlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1843CHTn7NAfqk_ERg8jUUunyJR7IupJVcZbJthWfZI)

Hm? I edited the mistake, should say "server.py". I did as describedm and that resolved the "can't install on this platform" issue, since installed python is 3.11, and the script in Krita points to install insightface compatible with 3.10. Easy enough to have it download insightface 3.11 instead, compatibil,ity issue resolved :)

**Comment by marcoA152** [comment]
> thanks, server.py updated and plugin reinstalled, now model download works but got this new error generating with ipadapter face controlnet:
> 
> 2024-09-16 12:23:06,581 ERROR Job Job[local=052d5d44-4da0-4518-bfd6-2b6fc025f87f, remote=7ed915ef-50b2-4c93-bd33-dfd2411c8b45] failed: DLL load failed while importing onnx_cpp2py_export: Routine di inizializzazione della libreria di collegamento dinamico (DLL) non riuscita. [' File "C:\ComfyUI_windows_portable\krita1\ComfyUI\execution.py", line 323, in execute\n output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', ' File "C:\ComfyUI_windows_portable\krita1\ComfyUI\execution.py", line 198, in get_output_data\n return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', ' File "C:\ComfyUI_windows_portable\krita1\ComfyUI\execution.py", line 169, in _map_node_over_list\n process_inputs(input_dict, i)\n', ' File "C:\ComfyUI_windows_portable\krita1\ComfyUI\execution.py", line 158, in process_inputs\n results.append(getattr(obj, func)(**inputs))\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', ' File "C:\ComfyUI_windows_portable\krita1\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 674, in load_insightface\n return (insightface_loader(provider, model_name=model_name),)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', ' File "C:\ComfyUI_windows_portable\krita1\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 161, in insightface_loader\n raise Exception(e)\n']
> 
> translated from ita is something like: Dynamic link library (DLL) initialization routine failed.

solved with 
https://github.com/Acly/krita-ai-diffusion/issues/1033

**Comment by nkBrew** [comment]
I faced the same issue. 

I changed the `server.py` file with the one Acly linked to on the main branch, but that wasn't enough as then I was getting an error for `server is missing one or more ip-adapter model`. Fixed that by doing #1033 like @marcoA152 suggested.

Maybe I'm wrong about closing issues, but I don't think this issue should be closed. Most people aren't going to go to these lengths.

**Comment by KrissOk1** [comment]
> https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl

I dunno if it matters, but in the acly post the download source for the insightface is the same, merely changing the file name.
In the solution that worked for me I changed the entire URL to: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl

**Comment by Acly** [comment]
Should boil down to the same thing, they're just different sources for the unofficial pre-built windows packages of insightface.

I also pinned the onnx version for now to avoid #1033, was optimistically hoping they'd fix this sooner...
