### ISSUE TITLE
Is there any suggestion to adjust CFG value for 1.5 or xl checkpoint? It can only run under 3, otherwise the picture will be a mess.

### ISSUE THREAD

**Issue by Tonny-gitgub** [Acly/krita-ai-diffusion#1192]
Is there any files miss？I can only set cfg value under 3,no mate it is 1.5 or xl checkpoint. Is it a right value?

**Comment by Acly** [comment]
Values up to 7-9 should work, but it depends on the checkpoint. Distilled checkpoints (Lighting, Hyper, etc.) only support lower values.
