### ISSUE TITLE
About SDXL - SEGMENT

### ISSUE THREAD

**Issue by guijiaosir** [Acly/krita-ai-diffusion#1198]
I would like to ask what model file **CONtolnet-【SDXL SEGMENT】** uses.
Thank you. I looked for the official document, but did not find a specific model introduction.

![image](https://github.com/user-attachments/assets/1a19ba7c-4296-4db9-bac1-c8daccf0943a)

I would like to ask what model file is used for this model.  in SDXL - CN

**Comment by Acly** [comment]
Usually this: https://huggingface.co/xinsir/controlnet-union-sdxl-1.0
