### ISSUE TITLE
Intel Arc supporting

### ISSUE THREAD

**Issue by roflosaur** [Acly/krita-ai-diffusion#120]
Is Intel Arc (XPU) supported?

**Comment by Acly** [comment]
Not out of the box. If you can get ComfyUI with Arc running, you can use the Krita plugin with that too. As far as I know it's possible.

**Comment by glaubitz** [comment]
> Not out of the box. If you can get ComfyUI with Arc running, you can use the Krita plugin with that too. As far as I know it's possible.

Could you elaborate on that a little more? ComfyUI indeed has added support for Intel ARC graphics.

If I understand this correctly, Krita AI Diffusion builds on top of ComfyUI, so when the latter is configured to work on Intel ARC, it should just work with Krita AI Diffusion, correct?

**Comment by Acly** [comment]
Yes. You might run into parts or features that won't work, depending on how good the support is. But basic generation should be no problem.
