### ISSUE TITLE
Problem installing server and components for AI on my iMac

### ISSUE THREAD

**Issue by CuevArt** [Acly/krita-ai-diffusion#1201]
Hello I´m CuevArt, I´m having problems during installation of server and components for the AI complement on Krita software. Also I can not see my NVIDIA graffics on the configuration box. I only have the Run on CPU or Use MPS (Metal Performance Shader) options.

My specifications are:

iMac 27" 2012 late 
running OSX 10.15.7. 
3.4 GHZ intel core i7 4 cores 
32 GB 1600 MHZ DDR3 of RAM
NVIDIA GeForce GTX, 680 MX  2GB  for graffics 

Krita version: 5.2.3
Krita AI diffusion 1.24.0

I loaded a screen capture of the error and graffics issues
I hope you can help me on this issue

![Error Krita](https://github.com/user-attachments/assets/a446b88c-3e28-4a58-a476-b8477827f5fa)

![Can´t see my NVIDIA Graffics](https://github.com/user-attachments/assets/f3e384d8-7c9a-4579-9096-77c551223ebd)

**Comment by Acly** [comment]
Apple does not support NVIDIA CUDA, it cannot be used.

(Also not sure exactly, but you probably need a more recent system, macOS version 14+ with a newer Python installed)
