### ISSUE TITLE
Outpaint

### ISSUE THREAD

**Issue by mp3pintyo** [Acly/krita-ai-diffusion#121]
Unfortunately, in version 1.8, I simply cannot figure out how to make the outpaint option work. The picture that enlarges the original picture is always horribly bad. As if it has nothing to do with the original image.
I installed everything possible for the plugin.
![outpaint_bug_1](https://github.com/Acly/krita-ai-diffusion/assets/5299995/71986eb9-6ada-4465-a579-7fcc3123a8f0)
![outpaint_bug_2](https://github.com/Acly/krita-ai-diffusion/assets/5299995/214f360d-0668-41b5-a475-ba5f17c1ef8a)

**Comment by Acly** [comment]
I see what you mean, it looks like there is something broken when upscaling.

![outpainte](https://github.com/Acly/krita-ai-diffusion/assets/6485914/869080b3-eb5b-4c00-8ae0-00136759283c)

Here I first tried on large resolution (1024) and it produced garbage.
Then with smaller resolution (around 512) and it works as expected.
I will take a look...

**Comment by mp3pintyo** [comment]
It doesn't work with the 1.5 models, but the SDXL one seems perfectly fine. But I'm still testing it

**Comment by Acly** [comment]
It's because SDXL runs at a higher resolution by default, so it doesn't need upscaling.

I think I found the problem.

**Comment by mp3pintyo** [comment]
Yes, I know, I generate 1024x1024 directly with the SDXL model.
This is often what generation does. I am not claiming the type of appointment.
![outpaint_bug_3](https://github.com/Acly/krita-ai-diffusion/assets/5299995/eebf410a-dc1f-458e-a412-0de3281ec286)

**Comment by Acly** [comment]
SD XL is generally bad at inpaint/outpaint, there is still no good model or control-net for that.

I pushed a fix for the issue. Probably will make a 1.8.1 at some point, but if you want to test it early you can get the source from git.

**Comment by Danamir** [comment]
> SD XL is generally bad at inpaint/outpaint, there is still no good model or control-net for that.

FYI the SDXL inpaint model from Stable Diffusion (available here : https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1/tree/main/unet ) works pretty well for a 0.1 version. Even if it may need a second pass with a recent model to get a good style on the inpainted region.

Note : you have to load it with the UNETLoader node to get it working in ComfyUI.

**Comment by Acly** [comment]
Yea it's not terrible, but not very flexible. I concluded that it's another 5 GB download for something that doesn't work as well as SD1.5, which makes it not really worth including.

But I also thought at the time an inpaint ControlNet for SDXL was surely just around the corner...

**Comment by Acly** [comment]
Fixed in [1.8.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.8.1)
