### ISSUE TITLE
Can't use pose because ControlNet model is not instailled

### ISSUE THREAD

**Issue by shikochi** [Acly/krita-ai-diffusion#1210]
HI! 
I can't use pose because the ControlNet model is not installed. 
I tried following [this tutorial](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#-download-script) to install ControlNet, 
but I don't actually know how to install it. My English isn't very good, so I may not fully understand the tutorial. 
There is no "ai_diffusion" folder in my Krita folder.
I also can't run this line of code successfully :
python download_models.py /path/to/your/comfyui.

Is this code supposed to be executed in the ComfyUI folder or in the Krita folder? I’ve tried running it in both, but I keep getting this error message:
![螢幕擷取畫面 2024-09-23 173007](https://github.com/user-attachments/assets/b86cec97-3acd-4243-adc0-ff29fbefc360)

I would like to ask if there are any other ways to resolve the "pose ControlNet model" issue?
I'm sorry for the trouble, and I really appreciate your help.

**Comment by guijiaosir** [comment]
https://github.com/Acly/krita-ai-diffusion/discussions/1208
You can download this tool and click on one-click download to complete the error repair.
The software must be placed in the comfyUI directory.

**Comment by Acly** [comment]
> Is this code supposed to be executed in the ComfyUI folder or in the Krita folder? 

A copy of this file should already be located in the [plugin install directory](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#where-are-plugin-and-user-files-located). Best invoke it directly from there. Replace `/path/to/your/comfyui` with the actual path (`D:\AI\ComfyUI_windows_portable` in your case).

Add eg. `--sdxl --controlnet` to download SDXL ControlNet models (including pose)

**Comment by shikochi** [comment]
> #1208 You can download this tool and click on one-click download to complete the error repair. The software must be placed in the comfyUI directory.

Thank you so much for your help! I later followed this method (https://www.bilibili.com/read/cv28325204/?jump_opus=1) and solved the issue. 
Your method seems more convenient, so I’ll try using it next time. Thank you again!

**Comment by shikochi** [comment]
> > Is this code supposed to be executed in the ComfyUI folder or in the Krita folder?
> 
> A copy of this file should already be located in the [plugin install directory](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#where-are-plugin-and-user-files-located). Best invoke it directly from there. Replace `/path/to/your/comfyui` with the actual path (`D:\AI\ComfyUI_windows_portable` in your case).
> 
> Add eg. `--sdxl --controlnet` to download SDXL ControlNet models (including pose)

Thank you for your quick response! 
I found a way to solve the problem, and I'll try your method next time! 
One question: is installing SDXL necessary? 
Thanks!

**Comment by ve3** [comment]
The document on page ( https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup ) maybe confuse if someone who isn't good at English like I am.

To make it easier and more clear, install this file **download_models.py** on **C:\Users\\%username%\AppData\Roaming\krita\pykrita**.  
Then call it with command (and maybe with path to ComfyUI as example above).  
Example for my case:
```
python download_models.py "C:\stable-diffusion\ComfyUI" --all
```

The folder "C:\stable-diffusion\ComfyUI" must contain **models, comfy, comfy_execution, main.py** folders and files in it.
