### ISSUE TITLE
Autocomplete LoRA filename with parenthesis

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#1213]
When auto-completing a LoRA name including parenthesis in the prompt, those are escaped and thus the file cannot be found.

A quick fix could be to add in `autocomplete.PromptAutoComplete` the property :  

```Python
    @property
    def is_lora_mode(self):
        prefix = self._current_text()
        name = prefix.removeprefix("<lora:")
        return len(prefix) > len(name)
```

An alter first line of the `_insert_completion()` method : 

```Python
    if not self.is_lora_mode:
        completion = completion.replace("(", "\\(").replace(")", "\\)")
```

**Comment by Acly** [comment]
Fixed in [1.26.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.26.0)
