### ISSUE TITLE
[Feature] AuraSR upscaler

### ISSUE THREAD

**Issue by DeXtmL** [Acly/krita-ai-diffusion#1214]
The old SR models are really outdated; the AuraSR is marginally better in quality, and perhaps speed as well.

**Comment by Acly** [comment]
Which old SR models? You can use HAT by default, which is still SotA (there is HMA which is new and no pretrained models released yet).

AuraSR didn't seem convincing initially, and no comparisons provided. But if [Spandrel implements support for it](https://www.github.com/chaiNNer-org/spandrel/issues/298) you will be able to use it here too.
