### ISSUE TITLE
Checkpoints showing as wrong versions

### ISSUE THREAD

**Issue by rktvr** [Acly/krita-ai-diffusion#1216]
not sure if it's because of a too up to date  custom portable comfyui version but i have some XL models that are all showing up as 1.5 in Krita, even though they show as sdxl here: http://127.0.0.1:8188/etn/model_info 
![image](https://github.com/user-attachments/assets/7d99b927-08f7-4888-bdfd-f136d2318c03)
![image](https://github.com/user-attachments/assets/4853fb46-d5da-4399-9482-ab739c1b905f)
note how comfyui reports them both as sdxl but only one shows up correctly in krita.

this causes issues with controlnets as krita is trying to load the 1.5 versions which give a mismatch:
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (462x2048 and 768x320)

i haven't updated comfyui in a while, so i can't say if it's a recent update

**Comment by rktvr** [comment]
uninstalled and reinstalled the plugin, and it's still wrong: 
![image](https://github.com/user-attachments/assets/5217bb46-d56c-4fb7-a453-fc6421ef2d48)

**Comment by rktvr** [comment]
installed the plugin managed version of comfyui and everything now shows up as it should. means a comfyui update on the custom/portable version broke it

**Comment by waynemadsen** [comment]
Every time I open krita, my Flux GGUF profile defaults to the first alphabetical SDXL model and I have to change it. I wonder if this is related?

**Comment by KusaPinPon** [comment]
Same problem here, it shows almost all models as 1.5 for some reason. I guess it takes the list of models from the comfy ui, maybe I use outdated comfy ui or something. But the plugin doesn't complain about unsupported comfy ui version or something. So, the last version doesn't work for me it seems ... 

But as a workaround, just settings "sd_version": "sdxl" in style files seems to help...
They are in AppData/Roaming/krita/ai_diffusion/styles
