### ISSUE TITLE
Black image after macOS 15 update

### ISSUE THREAD

**Issue by bohmm** [Acly/krita-ai-diffusion#1219]
Image generation does not work after updating macOS to Sequoia (v.15).

Previously I created a new file and had the image generated using keywords. Everything worked great. After updating macOS, it now only generates a black image for me.

I tried reinstalling Krita and Plugin but it didn't help.

**Comment by parella007** [comment]
I had that problem and i solved it with this instructions:
https://github.com/Acly/krita-ai-diffusion/issues/783#issuecomment-2305834278

**Comment by gums007** [comment]
I got the same issues. Anyone can help?

**Comment by bohmm** [comment]
This solved my problem:

https://github.com/Acly/krita-ai-diffusion/issues/783#issuecomment-2305834278

**Comment by Acly** [comment]
I believe this should be active for macOS 15 by default now in latest versions of plugin / ComfyUI.
