### ISSUE TITLE
AI Image Generation did't show in plugin manager.

### ISSUE THREAD

**Issue by shikochi** [Acly/krita-ai-diffusion#1222]
After importing the Python plugin from the ZIP file (latest version 1.25), I can't find the option to enable AI Image Generation in plugin manager.
I re-imported it, and it still shows that the plugin is installed (I also tried version 1.23).

Could you please let me know if there are any solutions to this issue?

![image](https://github.com/user-attachments/assets/8b49433b-3ac5-48ab-a359-02b161b89066)

krita version: 5.2.5

**Comment by shikochi** [comment]
The issue has been identified as a problem with the latest version of Krita (5.2.5).... 
I installed an older version (5.2.3), and it worked successfully.

**Comment by Acly** [comment]
It works fine for me with Krita 5.2.5 too

**Comment by ichswarox** [comment]
Delete the old plugin (ai_diffusion) in folder C:\Users\#YOUR USER NAME#\AppData\Roaming\krita then redo  Python plugin from the ZIP again might help
