### ISSUE TITLE
feature: new image same sets in inpaint and tools

### ISSUE THREAD

**Issue by kalle07** [Acly/krita-ai-diffusion#1225]
Whenever I open a new image, the inpaint sets are always reset to the default value.
so i should be the same

also all tools set to default
so if i had "freehand selection" its reset to"brush"

**Comment by Acly** [comment]
what do you mean with "inpaint sets"?

> so if i had "freehand selection" its reset to"brush"

That's Krita behavior, nothing to do with this plugin. I'm not sure if you can configure it somewhere.

**Comment by kalle07** [comment]
i see where i can contact krita except of discord (i dont use it) ?


with inpaint sets i mean the prompt and all ...
if i load 10 images or one after another it would be nice, to have every time the same prompt, and neg-prompt ...

**Comment by Acly** [comment]
> if i load 10 images or one after another it would be nice, to have every time the same prompt, and neg-prompt ...

In general, different images usually need different prompts. So I don't think that should be the default. Other settings are already remembered from the last document, but prompts are deliberately excluded.

>  its only possible to inpaint with 8bit colors? in fooocus i never had such problems ...

Yes. You sure Fooocus doesn't just convert your image to 8bit too?

**Comment by kalle07** [comment]
May I ask if these settings are applied to every image even if I don't see them in the prompt as above and why i dont see it should be a template thats loaded everyx time !?

![grafik](https://github.com/user-attachments/assets/da0b318d-aba6-4ec1-b0ea-d32fb941d459)



maybe foocus convert it but krita give an error so i must convert it in an extra step


which adress can i contact krita except of discord (i dont use it) ?

**Comment by kalle07** [comment]
?

**Comment by Acly** [comment]
Style prompts are always applied. If you don't want them, leave them empty.

They are intended to reduce clutter in the docker where you enter important parts of the prompt. Showing them there would defeat the purpose.

**Comment by kalle07** [comment]
NOT absolutely not!
FOOOCUS, img2img inpaint like webui, a1111 (all free python based software on github) work with it, that allways  the whole prompt is visible for every new picture !!!

you are just as resistant to advice as KRITA itsself  : D

if i want to change the prompt quickly i have to click 4 times to get to the option and if i want to change it again after 5 edited pictures ... click 4 times again!

it's not confusing and let's be honest only 10% use it at all !!!

**Comment by Acly** [comment]
I don't understand your problem. If you don't like the style prompt, you don't have to use it. Just use the main prompt, everything visible, no clicks.

**Comment by kalle07** [comment]
and btw ...

when I load a PNG with internal information of the prompt, as it is created in a1111 and webui and fooocus...
this is immediately displayed in your prompt window ... on the other hand, this is very confusing and unfamiliar if I want to change a small part of my image, i must delete it every time ...

**Comment by kalle07** [comment]
work with it and than you see that iam right

programmers often dont do that   ;)

**Comment by Acly** [comment]
It was requested by people working with it in #880

**Comment by kalle07** [comment]
i see ....  can i disable it in options ?
