### ISSUE TITLE
Cannot execute because node ControlNetInpaintingAliMamaApply

### ISSUE THREAD

**Issue by Lastofthefirst** [Acly/krita-ai-diffusion#1226]
Hello, thanks for the update. I am trying to test out inpainting using the inpainting model and the recent update. I downloaded the model, renamed it and placed it in the controlnet folder. When I tried to inpaint i got the following error:

```
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node ControlNetInpaintingAliMamaApply does not exist.', 'details': "Node ID '#13'", 'extra_info': {}}

```

I looked and cant find the appropriate node. The controlnets github repo has a similar issue: https://github.com/alimama-creative/FLUX-Controlnet-Inpainting/issues/13

**Comment by Acly** [comment]
Then your ComfyUI is too old.

**Comment by shanghaiyangming** [comment]
我用的是最新的comfyUI
