### ISSUE TITLE
Profile at the top of the Style Presets dropdown doesn't save checkpoint changes and defaults to first alphabetical entry in the Model Checkpoint dropdown on every Krita relaunch

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#1227]
I don't have the OP's issue with wrong checkpoint types, but I do have this one mentioned in that same issue, and I'm not sure if it's related to OP's issue either.

https://github.com/Acly/krita-ai-diffusion/issues/1216#issuecomment-2374097293 
> Every time I open krita, my Flux GGUF profile defaults to the first alphabetical SDXL model and I have to change it. I wonder if this is related?

Whichever style preset ends up at the top of the dropdown's list ends up having this issue. Other profiles below that one at the top don't seem to be affected. 

The top style preset doesn't save checkpoint selections, so if the top one is a Flux style preset, it might default to an SD 1.5 or an SDXL checkpoint instead of Flux and needs to be manually changed on every Krita relaunch.

Seems to be related to the style preset's name, but not the profile .json's actual filename, though if its filename causes it to be the top listing, that could also cause it. Thought it could be related to some specific filename, specifically filenames with "default" on them, but that didn't seem to be the case.

One temp workaround is making a new profile just named 00 so it shows up at the top, but of course that's not really optimal.

Also using a fully updated custom Comfy UI install, not sure if it's also related.

**Comment by waynemadsen** [comment]
For me, this only seems to occur on my own flux-schnell workspace (which is the first style in my list). This doesn't happen to the built-in flux-schnell; I have the default model installed and it uses that. For my own flux style, I'm trying to use a GGUF model and the style will not remember it but defaults to the SDXL model.

**Comment by freecoderwaifu** [comment]
From a quick test looks like it's fixed, thank you!
