### ISSUE TITLE
feature: every new generation visible

### ISSUE THREAD

**Issue by kalle07** [Acly/krita-ai-diffusion#1232]
so if i generate an inpaint the first is showing in the image 
but if i press again generate it is not , only the small preview on right side and i must choose to see it in the full image

and all new previews ordered one under the other but the window is big so it can be shown like a table

**Comment by Acly** [comment]
Images are generated in the background. They are not automatically shown on the canvas as that would interrupt drawing, editing, previewing (or whatever you are doing).

> and all new previews ordered one under the other but the window is big so it can be shown like a table

Only if you change parameters. Images with the same inputs are shown in a table / grid.

**Comment by kalle07** [comment]
no i meant

i generate on inpaint image, the first and it is shown in the small table and instaantly in my RAW image
if i want an another inpaint, and press oncea again, its is only shown in the table not in the RAW image, i must choose it by hand...
