### ISSUE TITLE
SD1.5 models generating at fixed res then upscaling

### ISSUE THREAD

**Issue by SytanSD** [Acly/krita-ai-diffusion#1242]
I have been using this plugin for a while, and I was trying to figure out why I get much better results when doing a native res generation in Comfy, only to find out when I dumped the workflow for KAD that it locks the res to some weird/arbitrary res around 512x. I assume thats because its a 1.5 profile? But this is really quite annoying, because the model I use is 880x trained, so when I try to generate 880x images, I get 512X images poorly upscaled to 880 instead of improved details and coherence. Was wondering if anybody knows how I can fix this/turn it off, because I would like to actually generate at the resolutions I specify

**Comment by Acly** [comment]
Yes SD doesn't work beyond the resolution it was trained on, so 2 pass workflow is used (aka hi-res fix). The default range for SD1.5 is 512-768, you can change it in: Style > Checkpoint configuration (advanced)
