### ISSUE TITLE
Krita AI ComfyUI server custom port

### ISSUE THREAD

**Issue by jalfort** [Acly/krita-ai-diffusion#1244]
Hi, would it be possible to have option to launch Kritas ComfyUi server on a custom port. I've let Krita handle the comfyui server and then I'm symlinking my models, but I'd like to run it on something other than port 8188.

There might already be a way to do it but I haven't figured it out.

**Comment by Acly** [comment]
You can edit the settings file to pass additional arguments, see https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui

Passing eg. `--port 1234` should work.
