### ISSUE TITLE
Loading model time when switching from SDXL to Flux

### ISSUE THREAD

**Issue by ichswarox** [Acly/krita-ai-diffusion#1246]
Generating image using SDXL then switch to Flux to inpaint, and it costs many time when loading checkpoints, do we have solutions like cache model in memory to short the loading time?

**Comment by freecoderwaifu** [comment]
It's a ComfyUI issue. This helps for regular safetensors but not for GGUFs. 

https://github.com/nonnonstop/comfyui-faster-loading

www.github.com/comfyanonymous/ComfyUI/issues/1992#issuecomment-2384723731

**Comment by Acly** [comment]
I don't think there's an easy way to cache more than the last-used model in RAM/VRAM.

Also you'd need a LOT of RAM/VRAM to cache Flux+SDXL, 48 GB was not enough with text encoders + VAE.

**Comment by ichswarox** [comment]
Thanks for the explanation!

**Comment by ichswarox** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/1992#issuecomment-1817821952

I'm going to try this method later.
