### ISSUE TITLE
Upscale process updating size even when the upscale is cancelled. Just a doubt.

### ISSUE THREAD

**Issue by GastonSan79** [Acly/krita-ai-diffusion#125]
First at all, I love the plugin and congratulations on this work! This is not much an "issue" than a doubt if I'm missing something.

Every time I want to do an upscale, the interface shows the new dimensions that the image will have. That's fine, but if for some reason I have to cancel the operation - modify steps, cfg, model - when I want to do the upscale again, the screen shows as if the upscale had been applied and the values it shows are those of the scaled image plus the new value to apply (for example, to my 512x768 image I want to apply an upscale x2, the plugin shows me that the result will be 1024x1536. I start the upscale, but I cancel it for whatever reason. But now the plugin tells me that the result of doing the upscale will be 2048x3072).
 
If this is how is intended to work, I humbly apologize, just seemed odd to me.

**Comment by ZaneH** [comment]
I've ran into this too, I think what's happening is the upscale has two steps: 1. Resize the canvas 2. Add the upscaled image.

So if you want to undo the upscale, you have to press undo 2x to get back to the original image dimensions. If the "resulting dimension" doesn't go back to what it was originally after doing that, it sounds like a bug. Switching the mode from Upscale to Generate mode and then switching it back would probably update it.

**Comment by GastonSan79** [comment]
Well, it never actually occurred to me to, besides cancelling the upscale, to press the "undo" button in Krita. This, plus switching from Upscale to Generation and back solved the situation and clarify my doubts. Thanks ZaneH for the hint that made me do the connection. I'm closing this.

**Comment by Acly** [comment]
It's still a bit odd, and technically it's possible to delay the canvas resize until the image is completed. It just might be that you're in the middle of doing something and then generation finishes and sudden resize is disruptive. At least that was my thinking, but I didn't consider cancel.
