### ISSUE TITLE
Request to add UNET model loader

### ISSUE THREAD

**Issue by wz488241** [Acly/krita-ai-diffusion#1251]
![11](https://github.com/user-attachments/assets/f57c9733-490a-4822-ab9c-8e2d72da1cf4)
1.25 The plugin could not load the FLUX recognition model.
If you put the model in the UNET model folder, the plug-in can recognize the loaded model, but there will be an error generating the image.
![43857ea72799fc49ccc08fd89fb2b5e](https://github.com/user-attachments/assets/8047fa71-e0ef-4ce5-b486-fbb552fb493d)

**Comment by Acly** [comment]
It should already work. Sounds like there is a VAE mix-up maybe?

Try setting it manually
![image](https://github.com/user-attachments/assets/13d3aec2-fc3a-43bf-ae29-df4489a8d2d4)

**Comment by Acly** [comment]
It will be difficult to get "real-time" speed with FLUX, it's a very heavy model. Maybe Hyper can be supported in the future, but it will still be much slower than SD.

**Comment by wz488241** [comment]
> It will be difficult to get "real-time" speed with FLUX, it's a very heavy model. Maybe Hyper can be supported in the future, but it will still be much slower than SD.使用 FLUX 很难获得“实时”速度，它是一个非常重的模型。也许以后可以支持Hyper，但还是会比SD慢很多。

I see. Thank you.
