### ISSUE TITLE
Alimama Flux inpainting model has been updated to Beta

### ISSUE THREAD

**Issue by buzzz3d** [Acly/krita-ai-diffusion#1253]
https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Beta
How do we replace the existing Alpha version with the new one?

**Comment by Acly** [comment]
Just replace the file.

You can call it `FLUX.1-dev-Controlnet-Inpainting-Beta.safetensors` if you want, but delete (or move) the previous file to make sure it uses the new one.

**Comment by buzzz3d** [comment]
Excellent thanks!

Op wo 9 okt 2024 20:47 schreef Acly ***@***.***>:

**Comment by buzzz3d** [comment]
Although my results are not as good as this [workflow](https://huggingface.co/alimama-creative/FLUX.1-dev-Controlnet-Inpainting-Alpha/resolve/main/images/alimama-creative-flux-inapint-cn-beta.json) in Comfyui.
Is that to be expected or am I doing something wrong here (Strength 100, seamless and focus checked)
