### ISSUE TITLE
[feature request] Settable denoise for automatic upscale

### ISSUE THREAD

**Issue by SHoogstad** [Acly/krita-ai-diffusion#1258]
I noticed when generating a image with high resolution it performs a second pass with a upscaled image which is good, but I noticed it deviated way to much from the base image this is because the second pass is performing at 1,0 denoise where I use 0.4-0.7 on my own second pass workflow so my question is it possible to set the denoise by the user.

Contact:
Discord: hoogstaddie
Email: shoogstad@icloud.com

**Comment by Acly** [comment]
Denoise for second pass is 0.4

I don't see a good reason to make it configurable so far. It's not like the "base" image is a user input in this case, it's just an intermediate part of the process.

**Comment by SHoogstad** [comment]
this may be an edge case but I tend to see with generating for example big muscles, that the deviation is wat to much in krita then base comfy with 0.4 denoise

**Comment by Acly** [comment]
how would you even see that? the base image is never shown

**Comment by SHoogstad** [comment]
recreated the image with same seed without the upscale in my own workflow

**Comment by Acly** [comment]
There's a "Dump Workflow" switch in Interface settings where you can run the exact plugin workflow. Makes it easier to investigate what the difference is.

**Comment by SHoogstad** [comment]
looks like this is not an issue that I get frequent but it will still be nice if it was settable

**Comment by Acly** [comment]
Realistically it needs to do a lot better than "would be nice" to be worth implementing though :)
Ie. a strong case where users can derive when to set it, what the values mean and how they may improve the image.
I don't really see it.
