### ISSUE TITLE
type: "invalid promot', "message: "cannot execute because nodetontrolNetlnpaintingAliMamaApply does not exist,', 'details': "Nade lp '*16""extra info': () (Error transferring http://127.0.0.1:8188/prompt -server repliediad Reduest)

### ISSUE THREAD

**Issue by 775229123** [Acly/krita-ai-diffusion#1262]
type: "invalid promot', "message: "cannot execute because nodetontrolNetlnpaintingAliMamaApply does not exist,', 'details': "Nade lp '*16""extra info': () (Error transferring http://127.0.0.1:8188/prompt -server repliediad Reduest)

**Comment by Acly** [comment]
likely just need to update comfyui
