### ISSUE TITLE
Upscale issue #1-#2: target size indicator is not updated properly

### ISSUE THREAD

**Issue by valery016** [Acly/krita-ai-diffusion#1264]
With this, I begin a series of postings related to Upscale issues, finally got around to reporting them. 

Upscale issue #1: target size indicator displays premature value

Starting an upscale immediately updates the target size indicator: after just having clicked on Upscale 2x with a file of size 1024x1024, the indicator already shows target size 4096x4096, while the operation is still in progress (and for large files, it can take a while). It should be updated only after finishing the upscale. 

Upscale issue #2 (quite an old one, still unfixed) : target size indicator is not reset upon Ctrl-Z

Undoing upscale (Ctrl-Z) does not reset the target size indicator. The picture below shows the Upscale panel after undoing upscale from 2048x2048 back to 1024x1024, but the target size still indicates 4096x4096. In fact, it stays this way during all the subsequent upscales and Ctrl-Zs.

![upscale screenshot 1 (issues #1-#2)](https://github.com/user-attachments/assets/9e00923a-e65f-4ec1-ada8-710ac7305a21)

**Comment by Acly** [comment]
Changed in [v1.28.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.28.0) to only show target resolution on hover.

Wasn't realistic to keep it updated, there are dozens of things one can do which change canvas size.
