### ISSUE TITLE
Upscale issue #4: Nearest Neighbor and Lanczos upscale methods missing

### ISSUE THREAD

**Issue by valery016** [Acly/krita-ai-diffusion#1268]
Nearest Neighbor and Lanczos are included as a standard in just about every AI upscaling framework at the top of the AI upscaler model list, but for some reason, in Krita AI they are not. These methods, while much simpler, remain efficient for a wide variety of use cases and most of all, important for comparison purposes. (Also, ‘None’ would be useful to include, for the case when only the Refine option is utilized with the Scale 1,00x.)

Yes, it’s possible to perform NN and Lanczos upscaling manually in Krita (outside the Upscale panel that is), but again, for reasons of comparison with other upscaling tools and platforms, ComfyUI-built-in versions of these methods have to be available as well.

**Comment by Acly** [comment]
I'm not convinced, as you say regular (non-AI) scaling is already in a different place. This may not be the case for other frameworks, so other frameworks do it differently.
