### ISSUE TITLE
[BUG] Auto-complete fails with lora bracket

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#1273]
When you use a LORA file that has a name containing bracket, the file name will change.

Example: cat(anime style).safetensor

Auto-complete will put the following in the prompt:
<lora:cat\\(anime style\\)>

Notice the brackets become \\( causing the plug in to fail to locate the file.

**Comment by Acly** [comment]
Fixed in [1.26.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.26.0)
