### ISSUE TITLE
Styles show up twice, some don't show up at all

### ISSUE THREAD

**Issue by feureau** [Acly/krita-ai-diffusion#1274]
Just upgraded to ai_diffusion-1.25.0 by fresh install, and the styles shows up twice in the dropdown. On top of that apparently the flux styles don't show up in the main sidebar dropdown for styles either. Any ideas on what's going on here? Thanks in advance

![image](https://github.com/user-attachments/assets/ad3a729a-d5a6-41e4-b400-4fad8e7be10f)

**Comment by syl1130** [comment]
You did not manually delete the old version files, you can refer to the installation instructions   https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-update-to-a-new-version-of-the-plugin

**Comment by Acly** [comment]
Check out #496, #689 - this looks similar
