### ISSUE TITLE
Send krita-generated images to PS plugin

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#1275]
When comfyui generates images on the web page, adding a sending node can send the generated image to PS. Can this node be added to krita?
![image](https://github.com/user-attachments/assets/f9625db6-d683-429f-9a20-5a4dce3d30fb)

**Comment by Acly** [comment]
Check out custom workflows in [1.26.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.26.0)

It has something similar (and more powerful customization). But it works the other way round: you have to run the workflow from Krita. Running from web UI will not work.
