### ISSUE TITLE
when i ues  depth  there was somthing wrong！

### ISSUE THREAD

**Issue by xtywwl** [Acly/krita-ai-diffusion#1278]
model_path is G:\BaiduNetdiskDownload\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\ckpts\depth-anything/Depth-Anything-V2-Base\depth_anything_v2_vitb.pth                                                                                                   
using MLP layer as FFN                                                                                                            
!!! Exception during processing !!! No operator found for `memory_efficient_attention_forward` with inputs:                       
     query       : shape=(1, 1370, 12, 64) (torch.float32)                                                                        
     key         : shape=(1, 1370, 12, 64) (torch.float32)                                                                        
     value       : shape=(1, 1370, 12, 64) (torch.float32)                                                                        
     attn_bias   : <class 'NoneType'>                                                                                             
     p           : 0.0                                                                                                            
`decoderF` is not supported because:                                                                                              
    xFormers wasn't build with CUDA support                                                                                       
    attn_bias type is <class 'NoneType'>                                                                                          
    operator wasn't built - see `python -m xformers.info` for more info                                                           
`flshattF@0.0.0` is not supported because:                                                                                        
    xFormers wasn't build with CUDA support                                                                                       
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})                                                              
    operator wasn't built - see `python -m xformers.info` for more info                                                           
`cutlassF` is not supported because:                                                                                              
    xFormers wasn't build with CUDA support                                                                                       
    operator wasn't built - see `python -m xformers.info` for more info                                                           
`smallkF` is not supported because:                                                                                               
    max(query.shape[-1] != value.shape[-1]) > 32                                                                                  
    xFormers wasn't build with CUDA support                                                                                       
    operator wasn't built - see `python -m xformers.info` for more info                                                           
    unsupported embed per head: 64                                                                                                
Traceback (most recent call last):                                                                                                
  File "G:\BaiduNetdiskDownload\ComfyUI-aki-v1.3\execution.py", line 323, in execute                                              
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                                                                                               
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                               
  File "G:\BaiduNetdiskDownload\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data                                      
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                                                                              
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                              
  File "G:\BaiduNetdiskDownload\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list                                  
    process_inputs(input_dict, i)                                                                                                 
  File "G:\BaiduNetdiskDownload\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs                                       
    results.append(getattr(obj, func)(**inputs))                                                                                  
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Acly** [comment]
Looks like some issue with the python environment / xformers installation. I don't think it's related to the plugin...
