### ISSUE TITLE
live drawing report this error. I don't know the reason, but it was reinstalled and updated, but it still hasn't solved the problem. Please help

### ISSUE THREAD

**Issue by hawk0123** [Acly/krita-ai-diffusion#128]
got prompt
ERROR:root:Failed to validate prompt for output 12:
ERROR:root:* ModelSamplingDiscrete 3:
ERROR:root:  - Value not in list: sampling: 'lcm' not in ['eps', 'v_prediction']
ERROR:root:* KSampler 9:
ERROR:root:  - Value not in list: sampler_name: 'lcm' not in ['euler', 'euler_ancestral', 'heun', 'dpm_2', 'dpm_2_ancestral', 'lms', 'dpm_fast', 'dpm_adaptive', 'dpmpp_2s_ancestral', 'dpmpp_sde', 'dpmpp_sde_gpu', 'dpmpp_2m', 'dpmpp_2m_sde', 'dpmpp_2m_sde_gpu', 'dpmpp_3m_sde', 'dpmpp_3m_sde_gpu', 'ddpm', 'ddim', 'uni_pc', 'uni_pc_bh2']
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

Above is the information of comfyui, and below is the information of krita

Error: ('type': ' prompt
validation
extra info".lliError trans
.1:8188/prompt - server replied: Bad
Request) [url=http://127.0.0.1:8188/prompt, code=302

**Comment by Acly** [comment]
This looks like ComfyUI version is too old. Did you install it via the plugin or separately?
