### ISSUE TITLE
I'm getting an error when I'm using Flux.

### ISSUE THREAD

**Issue by heng0ai** [Acly/krita-ai-diffusion#1283]
Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
!!! Exception during processing !!! Error while deserializing header: InvalidHeader
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 932, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path1, clip_path2], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 405, in load_clip
    clip_data.append(comfy.utils.load_torch_file(p, safe_load=True))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeader

Prompt executed in 45.36 seconds

**Comment by Acly** [comment]
Probably something wrong with the model file you're trying to load, try to re-download

**Comment by heng0ai** [comment]
> Probably something wrong with the model file you're trying to load, try to re-download可能是您尝试加载的模型文件有问题，请尝试重新下载

This is a strange bug. When I place "flux1-dev-fp8.safetensors" in the "ComfyUI\models\checkpoints" path, it runs normally. However, when I also place "flux1-dev-fp8.safetensors" in the "ComfyUI\models\unet" path (to use it in the Unet loader within ComfyUI), the bug occurs. Currently, I can only move the model from the "unet" path when using Krita, and then move it back to "unet" when using ComfyUI, but I don't think this is normal. I'm not sure if there's a solution.

**Comment by Acly** [comment]
Is your file a checkpoint? Then it should be in checkpoint folder (and use CheckpointLoader node in Comfy!)
Is your file a unet/diffusion model? Then it should be in unet folder (and use Unet loader in Comfy)

It can't be both and you shouldn't have to move it. It might be possible Comfy also supports loading checkpoints with the Unet-loader node, that would explain your observation.

**Comment by heng0ai** [comment]
> Is your file a checkpoint? Then it should be in checkpoint folder (and use CheckpointLoader node in Comfy!)您的文件是检查点吗？那么它应该位于 checkpoint 文件夹中（并使用 Comfy 中的 CheckpointLoader 节点！） Is your file a unet/diffusion model? Then it should be in unet folder (and use Unet loader in Comfy)您的文件是unet/扩散模型吗？那么它应该在unet文件夹中（并在Comfy中使用Unet加载器）
> 
> It can't be both and you shouldn't have to move it. It might be possible Comfy also supports loading checkpoints with the Unet-loader node, that would explain your observation.不可能两者兼而有之，您不必移动它。 Comfy 可能还支持使用 Unet-loader 节点加载检查点，这可以解释您的观察结果。

Thank you for your help. I directly deleted the files in the unet and then used the checkpoint loader in comfyui. As long as I stop using the unet loader, there won't be any issues! (Although I'm still not clear why it caused such a bug.)
