### ISSUE TITLE
ComfyUI-Login Compability / Token Validation

### ISSUE THREAD

**Issue by CloudWalker-II** [Acly/krita-ai-diffusion#1284]
Hello, thank you so much for your work on this plugin, the new node graph update looks super exiting. I was wondering if I could get some assistance using this plugin together with [ComfyUI-Login](https://github.com/liusida/ComfyUI-Login)

When I have the ComfyUI-Login node installed I get this error in the Krita plugin in when trying to connect to my local install:
`Error: Authentication required. (Host requires authentication)`

That's all good and should just mean that Login works as intended but I would like to give the Krita plugin access.
I have my API key / token, but I'm unsure where or how to implement it with the Krita plugin as per the instructions on his GitHub Page: [ComfyUI-Login using-rest-api-calls](https://github.com/liusida/ComfyUI-Login?tab=readme-ov-file#using-rest-api-calls)

I understand that this might not be a issue for a lot of users but any help or pointing in directions would still be greatly appreciated.

Edit, Solved: https://github.com/Acly/krita-ai-diffusion/issues/1284#issuecomment-2483769011

**Comment by Acly** [comment]
Related: #1234

In this case it might be simpler though, you can pass a bearer token for all requests here:
https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/comfy_client.py#L181-L185

Add an extra argument `bearer="...your token here..."`, similar to how it looks in the cloud client:
https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/cloud_client.py#L59-L63

**Comment by liusida** [comment]
@CloudWalker-II 

This is the first time I am installing Krita, sorry for the late reply.

I think you'll need to add another bearer to another function in the file `comfy_client.py`.
Around line 113, you'll do:
```
        # Try to establish websockets connection
        wsurl = websocket_url(client.url)
        headers = {
            "Authorization": f"Bearer $2b..."
        }        
        try:
            async with websockets_client.connect(f"{wsurl}/ws?clientId={client._id}", extra_headers=headers):
                pass
        except Exception as e:
            msg = _("Could not establish websocket connection at") + f" {wsurl}: {str(e)}"
            raise Exception(msg)
```
This is for setting the bearer for the `ws` connection.

And now I get this instead of Auth Error:
![image](https://github.com/user-attachments/assets/0fcbcffd-7979-4518-83bb-01b5ef42d701)

I think after my installation of those custom nodes finishes, it'll work.

**Comment by liusida** [comment]
My bad, another line of change, around L246, in `_listen()`, need another `extra_headers`:

```
        async for websocket in websockets_client.connect(
            f"{url}/ws?clientId={self._id}", max_size=2**30, read_limit=2**30, ping_timeout=60, extra_headers={"Authorization": f"Bearer {token}"}
        ):
```

**Comment by ipaqmaster** [comment]
Things have changed since then. It uses `websockets.connect` now which needs keyword argument `additional_headers` instead.

This diff of comfy_client.py for 1.36.1 gets me connected:

```diff
113,114d112
<         headers = { "Authorization": f"Bearer $2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
< 
116c114
<             async with websockets.connect(f"{wsurl}/ws?clientId={client._id}", additional_headers=headers):
---
>             async with websockets.connect(f"{wsurl}/ws?clientId={client._id}"):
198c196
<         return await self._requests.get(f"{self.url}/{op}", timeout=timeout, bearer="$2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
---
>         return await self._requests.get(f"{self.url}/{op}", timeout=timeout)
201c199
<         return await self._requests.post(f"{self.url}/{op}", data, bearer="$2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
---
>         return await self._requests.post(f"{self.url}/{op}", data)
254c252
<             f"{url}/ws?clientId={self._id}", max_size=2**30, ping_timeout=60, extra_headers={"Authorization": f"Bearer $2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
---
>             f"{url}/ws?clientId={self._id}", max_size=2**30, ping_timeout=60
```

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
could you elaborate a little on those changes @ipaqmaster 
Is there any additional effort on this working on other versions or are we stuck with 1.36.1?

**Comment by ipaqmaster** [comment]
There's nothing stopping us from adapting the above change to a newer version.

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
> There's nothing stopping us from adapting the above change to a newer version.

That would be nice if so @ipaqmaster I tried applying your diff to 13.6.1 but I'm having issues. Would you be able to make a fork?

**Comment by ipaqmaster** [comment]
Things have shuffled around in the file but applying each patch line still worked just fine by hand.


Untested patch for `ai_diffusion/comfy_client.py` in the current latest version v1.38.0

```diff
100a101
>         headers = { "Authorization": f"Bearer $2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
108c109
<             async with websockets.connect(f"{wsurl}/ws?clientId={client._id}"):
---
>             async with websockets.connect(f"{wsurl}/ws?clientId={client._id}", additional_headers=headers):
113a115
> 
190c192,193
<         return await self._requests.get(f"{self.url}/{op}", timeout=timeout)
---
>         return await self._requests.get(f"{self.url}/{op}", timeout=timeout,
>                                         bearer="$2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
193c196
<         return await self._requests.post(f"{self.url}/{op}", data)
---
>         return await self._requests.post(f"{self.url}/{op}", data, bearer="$2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
244c247
<             f"{url}/ws?clientId={self._id}", max_size=2**30, ping_timeout=60
---
>             f"{url}/ws?clientId={self._id}", max_size=2**30, ping_timeout=60, extra_headers={"Authorization": f"Bearer $2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
```
