### ISSUE TITLE
[Feature Request] Text output node for workflows

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#1285]
That workflow feature is so powerful!! I started working on it, but I directly noticed that I need feedback after execution.

For example, I want to see what is the width and height provided to the workflow when I make a selection. I can't troubleshoot that without output.

Also, when I want to troubleshoot the workflow, I have to disconnect krita inputs before I could troubleshoot problems.

If at least there was text output, I could see those numbers. I would also use it to give me back lora trigger words.

I suggest making the parameter node an input/output node.

**Comment by Marksusu** [comment]
这个必须有！👍
markdown、 fountain 都要有

**Comment by Acly** [comment]
Done. Including markdown and html support, for no obvious reason. No clue what "fountain" is though :D

**Comment by Marksusu** [comment]
> No clue what "fountain" is though :D

@Acly 大佬你好！
fountain 跟 Markdown 类似，是写剧本的通用格式。
如果可以导入剧本，或者在 Krita 里借助 AI 修改剧本，就可以与故事板、关键帧……这些功能连接。
在 ComfyUI 里，已经可以生成文字、图片和声音，还有人制作了“为关键帧填补中间帧”的工作流…… 这些拼在一起，就可以制作有配音的故事板和动画片段了。
有 fountain 就能对剧本进行深入操作，而剧本简单来说就是影片的拍摄计划（目前 blender 里就有支持 fountain 的插件）。这应该对叙事类的创作很有帮助。

**Comment by guzuligo** [comment]
> Done. Including markdown and html support, for no obvious reason. No clue what "fountain" is though :D

Great! Now I can see the trigger words of those cryptic Loras without leaving Krita 😁
An option to clear the output would be nice, though 👍
