### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by guijiaosir** [Acly/krita-ai-diffusion#1292]
closed

**Comment by guzuligo** [comment]
![image](https://github.com/user-attachments/assets/364dee7c-9a44-4e6d-a5ee-22b2c385c89e)

**Comment by guijiaosir** [comment]
> ![image](https://private-user-images.githubusercontent.com/4189008/378137521-364dee7c-9a44-4e6d-a5ee-22b2c385c89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Mjc1MDAsIm5iZiI6MTcyOTQyNzIwMCwicGF0aCI6Ii80MTg5MDA4LzM3ODEzNzUyMS0zNjRkZWU3Yy05YTQ0LTRlNmQtYTVlZS0yMmIyYzM4NWM4OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTIyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVlMjc3NGVjOGI1NTVkYmVjYjg3MjIxYWU4MTkyZDAyYjdjMjAwYWY2ZTg1MDgxMjRjOGNhZmU2YjhiODVlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v38MvstKlsxk07BAHGn2gfo3cov7lCMdW_IlfX2X6tE)

I didn't lock him.

**Comment by guijiaosir** [comment]
> ![image](https://private-user-images.githubusercontent.com/4189008/378137521-364dee7c-9a44-4e6d-a5ee-22b2c385c89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Mjc1MDAsIm5iZiI6MTcyOTQyNzIwMCwicGF0aCI6Ii80MTg5MDA4LzM3ODEzNzUyMS0zNjRkZWU3Yy05YTQ0LTRlNmQtYTVlZS0yMmIyYzM4NWM4OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTIyNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVlMjc3NGVjOGI1NTVkYmVjYjg3MjIxYWU4MTkyZDAyYjdjMjAwYWY2ZTg1MDgxMjRjOGNhZmU2YjhiODVlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v38MvstKlsxk07BAHGn2gfo3cov7lCMdW_IlfX2X6tE)

To verify my options, I can tell you that I have not turned on this button. And for the comfyUI workflow, I set the random seed.

**Comment by Acly** [comment]
What is the bug?

**Comment by guijiaosir** [comment]
> What is the bug?

I don't know, but now the pictures I generate are always consistent pictures, and I don't set the lock seed number. When I changed to version 1.23, this problem was solved

**Comment by guijiaosir** [comment]
> , and I don't set the lock seed number. When I changed to version 1.23, this problem was solved

![image](https://github.com/user-attachments/assets/fb68d799-2bf5-432c-84b7-a52873d1906e)
![image](https://github.com/user-attachments/assets/288d4717-6aff-4538-9364-ac92ccabf0d7)
![image](https://github.com/user-attachments/assets/aa28b2a8-b207-447f-80f5-78064d40ea0d)
![image](https://github.com/user-attachments/assets/0cd43cd8-d73e-44ce-8d4c-2490753d4f23)
I didn't lock the seed value
The weird thing is, no matter what I do, lock the seed, or change the seed, the characters are consistent. Don't know if it's good or bad.

When I fix the number of seeds and then modify the seeds manually, the resulting graph is still consistent.
![image](https://github.com/user-attachments/assets/7ad776df-4289-45fd-b44f-f864423ce15f)

![image](https://github.com/user-attachments/assets/a914666c-2d39-4073-92ac-f84dcc4c2f19)
![image](https://github.com/user-attachments/assets/ac9f5e1a-faf3-433e-8c5f-8b577e895833)
![image](https://github.com/user-attachments/assets/71d60e79-29ef-4808-9643-854b5c69a05d)
![image](https://github.com/user-attachments/assets/732ba233-63a3-4d54-99e8-070240282ddc)
![image](https://github.com/user-attachments/assets/5f301db8-4ba9-4a80-925b-ff389fd5d79e)
When I change the seed number of comfyUI to random, or increase it, it has no effect. Then I seem to be able to directly appear consistent characters. . .

![image](https://github.com/user-attachments/assets/9c258285-dad5-450d-9ba6-3258d5bb8baa)
It's always the same face.
![image](https://github.com/user-attachments/assets/7c6257cf-b1b8-455e-b5cf-9f693912a3b8)
![image](https://github.com/user-attachments/assets/166b4bd7-a90a-451b-8bf6-158164c0a732)
![image](https://github.com/user-attachments/assets/813e9500-0266-4cfa-a920-4d0e49631cd4)
![image](https://github.com/user-attachments/assets/d7132d72-2771-409f-bade-a282dd2bc69e)

**Comment by guijiaosir** [comment]
When I restored to 1.23, the characters were inconsistent. Of course, this is okay, I may be the first lucky person in the world, I did not lock the seed
![image](https://github.com/user-attachments/assets/076586ab-9a7b-4ca9-a43d-183285e9b881)


When I changed to the FLUX large model, everything was OK. But when I changed to the SD1.5... he had perfect consistency.

![image](https://github.com/user-attachments/assets/123ac84e-889f-484c-a803-5fe18cd9a031)
![image](https://github.com/user-attachments/assets/ae9b7cc9-6e81-4466-a031-127d8e0ced37)
![image](https://github.com/user-attachments/assets/6b0e39ca-0857-44dd-8b3c-677d446abb4b)
![image](https://github.com/user-attachments/assets/88d7e5fa-1b20-45c4-87be-30beb7dba71b)

**Comment by guijiaosir** [comment]
![image](https://github.com/user-attachments/assets/663839ca-1ce6-4069-9126-4497d61dee4d)
![image](https://github.com/user-attachments/assets/5c9eb64d-231c-4070-9dc6-591d21b468a5)
![image](https://github.com/user-attachments/assets/792b7d50-5d69-4273-9fec-78e33268db5c)
![image](https://github.com/user-attachments/assets/38a821f0-82b3-48c3-b522-ff01caed548b)

**Comment by guijiaosir** [comment]
When I reverted the plugin to 1.23, it still had perfect consistency. . . Yesterday it was working fine as I recall. I changed the big model. . . but still consistent. . .
![image](https://github.com/user-attachments/assets/1a78cbbc-7390-4e0d-8742-b9449df0694a)

**Comment by guijiaosir** [comment]
![image](https://github.com/user-attachments/assets/512b770a-be54-47a5-9651-be45a657d280)
I found the reason now, maybe I used the built-in version? Then I deleted the built-in version and used krita - comfyUI local connection?
![image](https://github.com/user-attachments/assets/bec7d38f-379f-4be1-b2d5-ad2994facc45)
![image](https://github.com/user-attachments/assets/f26cbaea-4b0c-4645-aa92-4cd8a996d195)
![image](https://github.com/user-attachments/assets/7f59364a-86c0-4c82-b837-8e5a3b74eb12)
![image](https://github.com/user-attachments/assets/35752870-ed36-46b0-a518-072cf452b621)

**Comment by guijiaosir** [comment]
I have tested various models, plugin versions.
My version got fixed when I deleted the Roaming-krita directory.
I kept the buggy version, as I felt it had commercial value.

**Comment by guijiaosir** [comment]
I reinstalled krita... but the problem still exists... maybe it's a problem with my comfyUI... I'm still looking for this bug...

**Comment by guijiaosir** [comment]
![image](https://github.com/user-attachments/assets/b66c2d00-5b54-497f-9440-4b775c8c3494)

COMFYui works normally,

**Comment by guijiaosir** [comment]
![image](https://github.com/user-attachments/assets/1cc16d18-a6de-408b-b13f-af6779620b6f)
When running in krita, a character will always appear.
I would like to ask where is the cache directory file of krita?

1：C:\Program Files\Krita (x64) 
2：C:\Users\Administrato\AppData\Roaming

**Comment by guijiaosir** [comment]
I tested it in the workflow, and the workflow is normal. Stable diffusion is also normal. I uninstalled krita, then deleted some files, reinstalled krita, and the problem still exists. I am now sure that the problem comes from krita. But I don't know which files need to be deleted.
![image](https://github.com/user-attachments/assets/f7d77190-4d10-4dff-8d2f-4ba0b60658e4)

**The problem still exists. Since I upgraded to 1.26, I use 1.23 version again. Every time I generate a character, it is consistent. I don't know where the problem is.**

**Comment by guzuligo** [comment]
I doubt the problem is a bug. It might be more of a workflow change. Probably this would help you troubleshoot further.
See the workflow in comfyUI and compare it to the workflow of the previous version.
![image](https://github.com/user-attachments/assets/fb5da0a2-83e8-443e-94a5-e40108214fdf)

**Comment by guijiaosir** [comment]
> I doubt the problem is a bug. It might be more of a workflow change. Probably this would help you troubleshoot further. See the workflow in comfyUI and compare it to the workflow of the previous version. ![image](https://private-user-images.githubusercontent.com/4189008/378267084-fb5da0a2-83e8-443e-94a5-e40108214fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTQ0NjYsIm5iZiI6MTcyOTUxNDE2NiwicGF0aCI6Ii80MTg5MDA4LzM3ODI2NzA4NC1mYjVkYTBhMi04M2U4LTQ0M2UtOTRhNS1lNDAxMDgyMTRmZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMTIzNjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFkNGYyZmQwMzAxYjE4OThlNmIzNmYyMjQ4ZTAzNDQ3MzNmZTg2NmVhM2M1ZTRiNDg3MDU4MWY2MDIzM2Y0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0UXSpYSdE8WTjiOpDU72aqiI071sBr3wA7vCZ0zELrc)

I have reverted the plugin to 1.23 and reinstalled krita, but the problem still exists. I also tried using the old comfyUI software. The problem still exists and I am still looking for a solution.

**Comment by guijiaosir** [comment]
![image](https://github.com/user-attachments/assets/59b97ee9-ba67-4917-a70b-d86ecc46acb7)
I tried turning ON ,OFF, all the settings but the problem still persists, I'm not sure where the problem is but when I use comfyUI there is no problem.

**Comment by guijiaosir** [comment]
![image](https://github.com/user-attachments/assets/a6ee3182-5a85-412e-a29d-ec2f4530676c)
![image](https://github.com/user-attachments/assets/a9598bf0-6550-49b2-b501-2b869d35b679)

These problems are caused by me after updating 1.26. I don't know which files I should delete,
