### ISSUE TITLE
Autocomplete space bug

### ISSUE THREAD

**Issue by picolet21** [Acly/krita-ai-diffusion#1294]
I found a bug in autocomplete.
When I add a space to the end of a word and select autocomplete,
one character remains at the beginning.

![comp1](https://github.com/user-attachments/assets/5690aa03-c403-4c4a-8101-2a5b2a4a8aee)
![comp2](https://github.com/user-attachments/assets/ea15c917-1709-404e-908c-dea4d89b5b83)

I was hoping to complete the phrase with "from_",
but it seems spaces are outside the scope of autocomplete.

For example, to correct "looking at viewer", I select "viewer",
press the delete key, and select "looking at object" in autocomplete,
but it becomes "llooking at object".

![comp3](https://github.com/user-attachments/assets/72ea76d1-9765-4e8b-ac79-78e91517542d)
![comp4](https://github.com/user-attachments/assets/7ab61c20-4147-4f9a-91cb-70b0ed906902)
![comp5](https://github.com/user-attachments/assets/f89d0e1e-5060-4675-af6c-96afec101654)

I can't stop typing spaces all the time,
so I'd like this bug to be fixed if possible.

**Comment by Acly** [comment]
Fixed in [v1.28.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.28.0)
