### ISSUE TITLE
update to 1.26，can't find krita output node in comfyUI

### ISSUE THREAD

**Issue by Rhymo** [Acly/krita-ai-diffusion#1296]
![QQ截图20241020203116](https://github.com/user-attachments/assets/c034c379-f58c-4006-a55d-dd9f7943cb0b)

**Comment by ZorisBube** [comment]
Did you update "comfyui tooling nodes" ?

**Comment by Rhymo** [comment]
> Did you update "comfyui tooling nodes" ?

just solved，thanks
