### ISSUE TITLE
get Error when update 1.26 Flux inpaint 

### ISSUE THREAD

**Issue by cppong1117** [Acly/krita-ai-diffusion#1298]
get Error when update 1.26 Flux inpaint 
![image](https://github.com/user-attachments/assets/e7d08a96-5330-40d0-9a93-3fe7f22e156e)
i try 2 computer  same problem .
one of old verson is working but  1.26  i make a circle selection if not work 
but i did not select anything a can generator the image  , so what can i do 
did some one have same problem  ???

**Comment by Acly** [comment]
You need to update ComfyUI.
