### ISSUE TITLE
Can the Mac OS system not be practical? The plug-in is displayed in gray, and there is no corresponding option in dockers

### ISSUE THREAD

**Issue by seeklake** [Acly/krita-ai-diffusion#13]
Can the Mac OS system not be practical? The plug-in is displayed in gray, and there is no corresponding option in dockers

**Comment by seeklake** [comment]
thank's ,
when you hover over it.There are the following tips, but I won't solve this problem
Module not loaded:
Traceback (most recent call last):
File "/Users/wi/Library/Application Support/krita/pykrita/ai_diffusion/_init_py", line 13, 
infrom .server import Server, ServerState, InstallationProgress
File "/Users/wi/Library/Application Support/krita/pykrita/al_diffusion/server.py", line 22, in
_process_flags = subprocess.CREATE_NO WINDOW if
_is windows else 0
AttributeError: module 'subprocess' has no attribute
'CREATE_NO_WINDOW!
Could not import ai_diffusion

**Comment by seeklake** [comment]
> It could work, I don't think there is a big blocker. But there are probably some small things that need to be fixed, and I'm not familiar with MacOS and don't have access to a machine.
> 
> If the plugin is grayed out there was some error loading it, I think it shows more info in a tooltip when you hover over it.
> 
> 它可以工作，我不认为有一个大的障碍。但可能有一些小东西需要修复，我不熟悉MacOS，也无法访问机器。
> 
> 如果这个插件是灰色的，那是因为加载的时候出现了一些错误，我想当你把鼠标悬停在它上面的时候，它会在一个工具提示中显示更多的信息。

thank's ,
when you hover over it.There are the following tips, but I won't solve this problem
Module not loaded:
Traceback (most recent call last):
File "/Users/wi/Library/Application Support/krita/pykrita/ai_diffusion/_init_py", line 13,
infrom .server import Server, ServerState, InstallationProgress
File "/Users/wi/Library/Application Support/krita/pykrita/al_diffusion/server.py", line 22, in
_process_flags = subprocess.CREATE_NO WINDOW if
_is windows else 0
AttributeError: module 'subprocess' has no attribute
'CREATE_NO_WINDOW!
Could not import ai_diffusion

**Comment by Acly** [comment]
I fixed this particular issue. But there are probably more.

**Comment by seeklake** [comment]
> I fixed this particular issue. But there are probably more 
[https://i.postimg.cc/SKkFWcTV/2023-10-09-10-27-09.png](url)
Thank you very much, but a new problem has arisen

**Comment by seeklake** [comment]
Error: Error during installation: ERROR: Could n not find a version that satisfies the requirement torch (from versions: none) ERROR: No matching distribution found for torch

**Comment by seeklake** [comment]
Thank you very much, by manually entering the URL has been successfully downloaded, can start and run smoothly, but the MAC OS graphics card only 4G can not run, the CPU is also very slow

**Comment by seeklake** [comment]
> I fixed this particular issue. But there are probably more.

Thank you very much, by manually entering the URL has been successfully downloaded, can start and run smoothly, but the MAC OS graphics card only 4G can not run, the CPU is also very slow

**Comment by Acly** [comment]
Good to know. Yes you need a fairly powerful PC to get good speed. Only other option at the moment is to run it on cloud GPU (but it's not free).

**Comment by Acly** [comment]
Good to know. Yes you need a fairly powerful PC to get good speed. Only other option at the moment is to run it on cloud GPU (but it's not free).
