### ISSUE TITLE
Clicking on the Use Prompt switch in Upscale causes the main extension's docked panel to keep stretching and can't be normally resized back

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#1302]
Video example.

https://github.com/user-attachments/assets/e52bdb1e-9a3b-4191-bcc0-708154bb14cc

Only happens when there's a prompt in the main panel, doesn't happen with a blank prompt. Just enabling it once already stretches it a tiny bit, constantly enabling and disabling keeps stretching it, until it can potentially fill the entire workspace. Then it can't be normally resized back.

Temp fix is to make a new document without any prompt, then go to Upscale on that new document, and then you can resize it back to normal. 

Using Krita 5.2.6 and the latest version of the plugin.

**Comment by Acly** [comment]
Fixed in  [v1.27.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.27.0)

I feel like this happens in some other places that I haven't been able to pin down...
