### ISSUE TITLE
Feature Request: Paint Tool for Mask like all doo

### ISSUE THREAD

**Issue by kalle07** [Acly/krita-ai-diffusion#1303]
OK for the moment i found no other Option

Only Selction Tools are possible to select a part of an Image for Inpaint ...

All other 10 Ai Inpaint softwares in the world works with a drawing/painting Mask with resizable brush ...
like this

![grafik](https://github.com/user-attachments/assets/44a71e32-9364-4b4b-a4f2-eca05e2c28fe)

do you have that option?

**Comment by Acly** [comment]
Sure you can use brush or other tools to edit selection/masks in Krita: https://docs.krita.org/en/user_manual/selections.html#display-modes
