### ISSUE TITLE
The "unblur Controlnet" is not working

### ISSUE THREAD

**Issue by cornum501109** [Acly/krita-ai-diffusion#1304]
![Snipaste_2024-10-22_18-00-03](https://github.com/user-attachments/assets/6c4538cb-7ea8-40aa-9907-129364efcf90)

Hi there, I'm having trouble using the Flux unblur Controlnet Model in ComfyUI. I've downloaded it from https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Upscaler and placed it in the ComfyUI\models\controlnet folder, but ComfyUI doesn't seem to recognize it. Could you please tell me the correct location and file name for this model?

**Comment by Acly** [comment]
Location is correct. Filename should be `FLUX.1-dev-Controlnet-Upscaler.safetensors`. Check client.log for more info.

**Comment by morningddy** [comment]
这个命名方式在哪里可以看到     别的模型应该改成什么名字

**Comment by Acly** [comment]
> Where can I see what other models should be renamed in this naming method?

#1176
