### ISSUE TITLE
Problem with The IP-Adapter Face (SD1.5)

### ISSUE THREAD

**Issue by Lanserotti** [Acly/krita-ai-diffusion#1307]
The IP-Adapter Face (SD1.5) is not working. I installed Krita along with the AI plugin, and in the additional content installation window, I selected literally everything. Everything installed successfully, but the IP-Adapter Face (SD1.5) option does not start. A month ago, everything worked. Today, I uninstalled Krita and then reinstalled it. The IP-Adapter Face (SD1.5) is not responding.

Thank you in advance for your help.

**Comment by Lanserotti** [comment]
![obraz_2024-10-22_190942828](https://github.com/user-attachments/assets/2d30fb99-f054-4f37-8d55-a140cceba58f)

**Comment by Lanserotti** [comment]
![Zrzut ekranu 2024-10-22 190835](https://github.com/user-attachments/assets/565b1d23-aaa0-446b-b4d7-b02c2c71cb05)

**Comment by Lanserotti** [comment]
It’s working now. Thank you for the quick intervention.

**Comment by Acly** [comment]
I didn't do anything, looks like maybe github.com wasn't reachable for a while.
