### ISSUE TITLE
pose 生成的不是矢量图层，只是颜料图层

### ISSUE THREAD

**Issue by alexjamwei** [Acly/krita-ai-diffusion#1308]
pose 生成的不是矢量图层，只是颜料图层，故无法调整姿态
请问如何解决？

**Comment by alexjamwei** [comment]
参阅过很多网上关于POSE的使用过程，都是直接能生成矢量图层，也在AI diffusion的设置里翻查，没有关于POSE或control net的设置

**Comment by guijiaosir** [comment]
矢量是矢量，矢量要自己转。。。。

**Comment by Acly** [comment]
Fixed in  [v1.27.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.27.0)
