### ISSUE TITLE
Control net--pose not creating a vector layer

### ISSUE THREAD

**Issue by alexjamwei** [Acly/krita-ai-diffusion#1312]
I tried Control net-- pose but it is not creating a vector layer, just a paint layer instead, so I can't adjust the pose.
How can I fix this?
BTW,I go over the AI diffusion's settings, there are nothing about control net outputs.

**Comment by Acly** [comment]
It's a bug and will be fixed next release (
 https://github.com/Acly/krita-ai-diffusion/commit/022bc243cdb047020cc05f564bfd49af5ef270b9)

**Comment by Acly** [comment]
Should work again in [v1.27.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.27.0)
