### ISSUE TITLE
OSError WinError126

### ISSUE THREAD

**Issue by MON232323** [Acly/krita-ai-diffusion#1317]
Hi, I just installed version 1.25 of the plugin with all its elements. They all appear in green as installed, but when I try to start the server I get the following error message in red and it does not let me start it:
Error: Error during server initialization: OSError:[WinError 126] Cannot find the specified module. Erro loading “C:\Usersmon23\AppData\Roaming\krita\ai_diffusion\server\Python\Lib\site-packages\torch\lib\lib\c10.dll” or one of its dependencies. [1]
Do you know how I can fix it?

My computer has Windows 11 OS, Nvidia 3060 12 GB and 16 GB RAM.

Thank you very much

**Comment by Acly** [comment]
See #1243
