### ISSUE TITLE
Outpainting options (fill, expand...) does not use the defined LoRA

### ISSUE THREAD

**Issue by jfuentesa** [Acly/krita-ai-diffusion#1318]
If you generate something using the outpainting options (fill, expand...) the defined LoRAs are not used.

Is there any option to activate this feature?

Style file:
```
{
    "name": "Illustration",
    "version": 1,
    "sd_version": "auto",
    "sd_checkpoint": "SDXL_Generic\\epicjourneyXL_v1PromptMeIDeliver.safetensors",
    "loras": [
        {
            "name": "SDXL_Styles\\LaxpeintXL-2.0.safetensors",
            "strength": 1.5
        }
    ],
    "style_prompt": "",
    "negative_prompt": "ugly, cropped, deformed, mutated deformed, mutated hands, mutation, worst quality, low res, bad face, bad anatomy, bad proportions, jpeg artifacts, text, error, signature, watermark, username, malformed limbs, missing limbs, missing arms, missing legs, bad-artist, bad-hands-5, futa, extra limbs, extra arms, extra legs, extra feet, extra tail, deformed tail, extra fingers, deformed fingers, deformed item, others hands, floating hands, poorly drawn hands, poorly drawn face, disfigured, gross proportions",
    "vae": "Checkpoint Default",
    "clip_skip": 2,
    "v_prediction_zsnr": false,
    "self_attention_guidance": false,
    "preferred_resolution": 0,
    "sampler": "DPM++ 2M SDE Karras",
    "sampler_steps": 25,
    "cfg_scale": 4.5,
    "live_sampler": "Realtime - Hyper",
    "live_sampler_steps": 8,
    "live_cfg_scale": 3.5
}
```

**Comment by Acly** [comment]
They're used. They might have less impact, though I just did a quick test and it was very noticeable.

Which base model are you using (SD1.5, SDXL, Flux...?)

**Comment by jfuentesa** [comment]
> Which base model are you using (SD1.5, SDXL, Flux...?)

Hello @Acly, I'm using this settings:
Checkpoint: epicjourneyXL_v1PromptMeIDeliver.safetensors
LoRA: LaxpeintXL-2.0

I've just updated my first message.

It works well when I use "Generation" mode, but the LoRA is not taken into account in "Fill" mode.

**Comment by Acly** [comment]
What makes you say it doesn't work? Did you check the same seed, with and without Lora?

**Comment by jfuentesa** [comment]
Yes @Acly, the LoRA only works in Generate mode.

Tested with:

Prompt: "girl on vacation, village, mediterranean sea, midday sun, illustration
<lora:SDXL_Styles/EldritchCharcoalXL1.1>"
Checkpoint: "sdXL_v10VAEFix.safetensors"

Watch the results on the attached image:

![image](https://github.com/user-attachments/assets/b6ac817a-9364-47ad-bbba-da300126b2f5)

**Comment by Acly** [comment]
I meant did you try Fill with Lora vs. Fill without Lora, using the same settings (and the same seed!).

In this case Fill attempts to make a image that _fits in with the surroundings_ and the Lora is presumably trying to make it charcoal, but it may just be that fill is "stronger". So I think the way you're using it is a bit contradictory, you might have better results by using a lower strength (~70%), or first make the area B/W first by adjusting saturation.

**Comment by jfuentesa** [comment]
Ah, now I understand, so the strength of the 'surroundings' has more weight than the strength of the LoRA used... I’ll adjust it with the Fill strength, thank you very much.

**Comment by jfuentesa** [comment]
The strength should be taken into account when using outpainting options together with a LoRA, as the weight of the surroundings could 'override' the weight of the LoRA.
