### ISSUE TITLE
wiki ComfyUI-Setup needs to be updated

### ISSUE THREAD

**Issue by tampadesignr** [Acly/krita-ai-diffusion#1322]
https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup
does not have all necessary info, names, things needed
i had a ton of issues following that for local(manual install}
when i did the auto one and copied all things it installed into comfy into my local version, i then got it working
and there were clearly things missing from the list

example

you have in wiki

[Clip-Vision](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors?download=true) to models/clip_vision/SD1.5
and in 

resources.py
you have

 Path(
                "models/clip_vision/clip-vision_vit-h.safetensors"

not the same paths

also could you make it so it needs one simple location to find stuff
like d:\allmymodelsfrom5differentguis\models
i have invokeai,autoo1111,comfy,forge all sharing same location
or the ability to give location for each folder so my name structuce doesnt need to match yourname structure since i just point it at each needed location for what it needs
so
you want 
loras
mine is
lorasss

**Comment by Acly** [comment]
I do not think it's outdated. Note that it lists required models only, there are more models that are optional.

> you have in wiki

> [Clip-Vision](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors?download=true) to models/clip_vision/SD1.5
> and in
> resources.py
> you have
> Path(
> "models/clip_vision/clip-vision_vit-h.safetensors"

they should both work.

> also could you make it so it needs one simple location to find stuff

you can do that: https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#how-do-i-share-models-between-another-ui-and-comfyui

it is comfyui that needs to find the models, not the plugin itself.

**Comment by tampadesignr** [comment]
> they should both work.


following your links it didnt work
using your installer and moving everything over did
