### ISSUE TITLE
I'm trying to install a local sever, and I always get a download error.

### ISSUE THREAD

**Issue by wuliang19869312** [Acly/krita-ai-diffusion#1323]
![wrong](https://github.com/user-attachments/assets/c959c453-9f17-43e8-9c32-2e8ac354369e)

**Comment by tampadesignr** [comment]
you could try and download manually and put it where the programs expects it to be
might help
https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup

**Comment by Acly** [comment]
I can't really help with connection issues.
