### ISSUE TITLE
Is there any plugin for krita that can replace this functionality?

### ISSUE THREAD

**Issue by guijiaosir** [Acly/krita-ai-diffusion#1325]
![image](https://github.com/user-attachments/assets/0b877ad4-7cbb-4883-b12b-07ad5f4d14db)
I want to extract the transparent layer of the image directly through layerdiffusion

I don't know how to connect the artboard to the workflow, and then connect it to krita. I can paint in krita and directly output transparent layers.

**Comment by Acly** [comment]
Don't really understand what this is about.

There are already open issues/PR for layer diffusion / transparency.
