### ISSUE TITLE
Why is the pose not installed in controlnet for SD1.5? I have the SD1.5 model with openpose in the model, is the name still DWPOSE, not openpose? But the SDXL pose works, only SD1.5 says it's not installed.

### ISSUE THREAD

**Issue by wuliang19869312** [Acly/krita-ai-diffusion#1326]
![屏幕截图 2024-10-27 191517](https://github.com/user-attachments/assets/e17f5b8b-82c4-41dc-bb68-3b618166aaea)

Why is the pose not installed in controlnet for SD1.5? I have the SD1.5 model with openpose in the model, is the name still DWPOSE, not openpose? But the SDXL pose works, only SD1.5 says it's not installed.

**Comment by Acly** [comment]
SD1.5 OpenPose: https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_lora_rank128_v11p_sd15_openpose_fp16.safetensors (folder: ComfyUI/models/controlnet)
