### ISSUE TITLE
Genration steps showing up in selection area

### ISSUE THREAD

**Issue by sraney** [Acly/krita-ai-diffusion#1330]
Not sure how to even describe this but after using the auto-update today, suddenly I am seeing each step exported as an image in the selection sidebar.  I do run an external server.  

<img width="508" alt="generation-steps-inside-bar" src="https://github.com/user-attachments/assets/43b6e56b-ef3f-4cf6-bd1f-b794ec69bb7b">

**Comment by realjoschek** [comment]
+1

**Comment by Acly** [comment]
Hm it's because you're using ComfyUI with `--preview-method` I guess? I'm not sure yet why this pops up now, I thought that was always an issue...

**Comment by guzuligo** [comment]
> Hm it's because you're using ComfyUI with `--preview-method` I guess? I'm not sure yet why this pops up now, I thought that was always an issue...

That makes it more of a feature than an issue then 😂
It might be a good idea to add a switch to turn it off, though.

**Comment by Acly** [comment]
Eh, it's definitely not a feature.

I know why it changed: the plugin now also accepts JPEG (not just PNG) images, because technically custom workflows can send JPEG if they want.

So previously the intermediate results were filtered out because they were JPEG. I may just revert to that.

**Comment by youo0o0** [comment]
From the Comfort Manager, @Light-light-lee easily closes it ![image](https://private-user-images.githubusercontent.com/4189008/380763960-708becf0-39da-4891-81a4-56b1d6ac6f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjc3MTEsIm5iZiI6MTczMDEyNzQxMSwicGF0aCI6Ii80MTg5MDA4LzM4MDc2Mzk2MC03MDhiZWNmMC0zOWRhLTQ4OTEtODFhNC01NmIxZDZhYzZmMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTQ1NjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRlODM2MzY0YTk5ZjIwMTU0MzRjYjFjZjEyMmM1OWEzZjZlOTVkYWI3N2JiZGJmMjA5MmRkZTNjMWI2NWYxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.znG_6h2FzReBVNsngQDXJusZ60neJFrthAIGO5t7U6s)
This works, it solves my problem.

**Comment by Acly** [comment]
Fixed in [v1.27.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.27.1)

**Comment by sraney** [comment]
Fixed! thank you @Acly
