### ISSUE TITLE
BUG in version 1.27

### ISSUE THREAD

**Issue by shumoLR** [Acly/krita-ai-diffusion#1336]
In version 1.27, using the comfyui node, the resulting image is the image of the sampler, that is, all the steps, such as the 20 steps I used, resulting in 20 images.
![427008b9546551bad7671c0b14a530e](https://github.com/user-attachments/assets/0136d85e-24fb-4ccc-b2a2-82490f2ce827)

**Comment by youo0o0** [comment]
I have encountered this problem as well.

**Comment by Acly** [comment]
#1330
