### ISSUE TITLE
dosnet work offline 

### ISSUE THREAD

**Issue by hamid1372** [Acly/krita-ai-diffusion#1339]
When I open the app without connecting to the internet, if the checkbox for the plugin update is enabled, the plugin won't work. It stays on 'Connecting' and doesn't bring up the generating box, unless I disable 'Check for updates on startup.' It would be great if it could bypass this problem without needing to uncheck that option. Thanks to @2ndworstplayer in the Discord server for the help with this!"

**Comment by Acly** [comment]
I wasn't really able to reproduce, it immediately detected the network was down and failed the check and went on to the generation UI. But maybe you ran into some long timeout for some reason?

In any case it doesn't show the update UI now while it's checking, so it should work better ([1.27.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.27.1)).

**Comment by hamid1372** [comment]
yeah thank you,looks like fully fixed for me on the new upgrade!
