### ISSUE TITLE
Custom Paths possible ?

### ISSUE THREAD

**Issue by EKKIV0K** [Acly/krita-ai-diffusion#134]
Hey mates ! first of all well done for this incredible plugin but....
i checked the code, and i didn't found any custom paths....
you know, i don't want to have multiple duplicated models, cause i have already sdxl and bunch of models already downloaded, can you please make an update for that ?!

thanks for this incredible work !

**Comment by Acly** [comment]
You can find a file `extra_model_paths.yaml.example` in the ComfyUI folder where you installed the server.
Rename this file to `extra_model_paths.yaml` and edit it to include additional paths where you store models.

**Comment by EKKIV0K** [comment]
Yeah I found the right file lol sorry I just searched in the wrong folder -_- I was too tired I guess, thanks for your answer :)

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
