### ISSUE TITLE
Apply button when Regional prompting is available has undesirable behavior

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#1344]
When I hit apply while using Regional prompting, it apply each layer separately and creates folders. This is only desirable when I want to edit individual layers.

But I find myself more often using regional prompting only to specify what object I want in that location using a single color. When folders get created, I end up having many folders, which disturbs my flow.

I suggest to make such behavior optional. I usually prefer the basic apply of the preview layer being applied.

Edit: This is more relevant to "Generate" more than "Live".

**Comment by Acly** [comment]
You can try the options in #806

Closing this since the other issue is still open and I think it's the same request.
