### ISSUE TITLE
Inpainting - Multiple results

### ISSUE THREAD

**Issue by ZorisBube** [Acly/krita-ai-diffusion#1345]
Interestingly, since the last versions, when I use inpaint, it gives multiple results. Usually five results, sometimes 3-4 or six. I have this problem with SD 1.5 models and Flux, but I don't have a similar problem with SDXL models. I am sharing a photo below as an example. I have also given explanations on the photo. Batch number is 1, of course.  There are no issues with normal generations.

Honestly, I couldn't find out what is the reason for this.

![example2](https://github.com/user-attachments/assets/67e92bde-c8a5-4bd8-bda1-4ff112c6a99e)

**Comment by WatermelonMango451** [comment]
![obraz](https://github.com/user-attachments/assets/989df5c5-9d9a-4188-97b7-bdeeededa030)
You have to change it from Automatic to custom and set the first parameter to 1.

**Comment by ZorisBube** [comment]
Yes, that's the reason. Thank you @WatermelonMango451  I forgot I've chnaged it a couple of days ago. 
Best regards
