### ISSUE TITLE
error loading SD3.5 medium

### ISSUE THREAD

**Issue by marcoA152** [Acly/krita-ai-diffusion#1348]
got this error loading stableDiffusion35_medium.safetensors
using Local Managed Server for Krita

probably is related that ComfyUI version is not the latest(?)
https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.2.5
and
https://www.reddit.com/r/StableDiffusion/comments/1gevd96/comment/ludkop2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Thanks for your work!!!

# ComfyUI Error Report
## Error Details
- **Node Type:** CheckpointLoaderSimple
- **Exception Type:** RuntimeError
- **Exception Message:** Error(s) in loading state_dict for OpenAISignatureMMDITWrapper:
	size mismatch for joint_blocks.0.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.0.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.1.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.1.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.2.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.2.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.3.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.3.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.4.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.4.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.5.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.5.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.6.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.6.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.7.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.7.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.8.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.8.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.9.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.9.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.10.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.10.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.11.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.11.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
	size mismatch for joint_blocks.12.x_block.adaLN_modulation.1.weight: copying a param with shape torch.Size([13824, 1536]) from checkpoint, the shape in current model is torch.Size([9216, 1536]).
	size mismatch for joint_blocks.12.x_block.adaLN_modulation.1.bias: copying a param with shape torch.Size([13824]) from checkpoint, the shape in current model is torch.Size([9216]).
## Stack Trace
```
  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\nodes.py", line 540, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\comfy\sd.py", line 560, in load_checkpoint_guess_config
    out = load_state_dict_guess_config(sd, output_vae, output_clip, output_clipvision, embedding_directory, output_model, model_options, te_model_options=te_model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\comfy\sd.py", line 601, in load_state_dict_guess_config
    model.load_model_weights(sd, diffusion_model_prefix)

  File "C:\ComfyUI_windows_portable\krita2\ComfyUI\comfy\model_base.py", line 223, in load_model_weights
    m, u = self.diffusion_model.load_state_dict(to_load, strict=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\krita2\python\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by arcusmaximus** [comment]
Relatedly, the addon references a version of the "ComfyUI-GGUF" custom node that doesn't support SD3.5 yet - the error message is clearer in this case, saying that the "sd3" identifier is not recognized. (The latest version does support this)

**Comment by DrSiemer** [comment]
Update Comfy, that fixed it for me. I used the ComfyUI Manager and first executed "Update ComfyUI" and then "Update All".

**Comment by Acly** [comment]
[v1.28.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.28.0) managed install uses latest ComfyUI/GGUF so SD3.5 medium should work there too now
