### ISSUE TITLE
Running the local server as a network server? 

### ISSUE THREAD

**Issue by gerroon** [Acly/krita-ai-diffusion#135]
HI

Is it possible to run the locally downloaded server as a network server like the ComfyUI server? So that the user can download all the necessary stuff (given the addon installs well working versions of everything) and put it on a different PC and access it as a remote standalone server in the addon pref?

thanks

**Comment by ZaneH** [comment]
If I understand correctly, yes, check this out: https://github.com/Acly/krita-ai-diffusion/issues/91#issuecomment-1820922515

**Comment by gerroon** [comment]
I am asking about taking the ComfyUI install that the extension creates and putting on another PC, so that I can run the vanilla version of the extensions's installation because it seems to work without torubles (vs trying tointegrate the my custom ComfyUI installation as a remote) I looked at the folder and it looks slightly different so I am not sure how I could run it as a server on another PC.

**Comment by Acly** [comment]
The installation should be relocatable (on Windows), so I don't see a problem with copying it to a different PC and running from there. Copy the folder where you installed (it should have a Python and ComfyUI folder inside), then start via
```
python\python.exe ComfyUI\main.py --listen
```

**Comment by gerroon** [comment]
Thanks, it works that way. It looked like some modules were not avail on the other PC. So I had to install them, other than that it works as advertised.
