### ISSUE TITLE
Download of models keeps stopping

### ISSUE THREAD

**Issue by JackGreenEarth** [Acly/krita-ai-diffusion#1352]
When setting up a local server, the download keeps stopping after downloading for about 30s, the MB/s freezes, and the only way to resume the download for another 30s is to restart the app, which tales a while and requires constant interaction. I've only noticed this in the new 1.27.1 update. When I initially set the plugin up, in one of the versions before automatic updates, it just downloaded continuously and worked. My network isn't getting interrupted, other apps are downloading things and using the network just fine. Maybe you can provide a link to the files I need to download so I can put them in the correct folder with a different download manager which doesn't have issues?

OS: Manjaro GNOME
GPU: NVIDIA 1660 ti 6GB
Connection: wifi

**Comment by Acly** [comment]
It might also be a temporary issue with the server it's downloading from. I haven't seen any issue (also there have been no changes in that area).

Required downloads are described here: https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup
For the full list including optional models you'll have to use the script, or check the source: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py#L314
