### ISSUE TITLE
实时功能：多个comfyui网页如何更方便对应krita ai？以及在网页关闭后如何恢复关联？

### ISSUE THREAD

**Issue by hhhaa123** [Acly/krita-ai-diffusion#1354]
![1730565711959](https://github.com/user-attachments/assets/e0c6520c-f020-47fd-beb8-ea8df2ded9cf)
我觉得如果能与指定comfyui网页对应起来的话，实时功能会更方便点。
![image](https://github.com/user-attachments/assets/e9136e89-f776-4561-9862-5296199f1c5c)
我觉得如果能与指定comfyui网页对应起来的话，实时功能会更方便点。

**Comment by Marksusu** [comment]
这个实在太让人暈菜了，莫名焦虑、需要安慰……

**Comment by Acly** [comment]
???
