### ISSUE TITLE
Can't use SDXL when open Krita today..........

### ISSUE THREAD

**Issue by K-O-N-B** [Acly/krita-ai-diffusion#1355]
SDXL has been work well last week. 

But today......
![image](https://github.com/user-attachments/assets/c3b23bab-d4c0-47e5-8671-2eb97918d3b1)

after I update last version, still same.

all the files in the correct folder
![image](https://github.com/user-attachments/assets/11969377-4e0c-48d2-815e-c1ed534b5fd3)

**Comment by K-O-N-B** [comment]
![image](https://github.com/user-attachments/assets/32d73d62-a404-44c1-8152-ad2ac6f3634c)

**Comment by K-O-N-B** [comment]
I've check the log file:
![image](https://github.com/user-attachments/assets/f77be91a-5fe4-4dad-879b-a03e7be5d21d)

and this is the file:
![image](https://github.com/user-attachments/assets/d90069d6-2535-4467-846e-09f7b4fc7389)

**Comment by elyetis** [comment]
Similar problem here. 
I updated my custom nodes a like a couple days ago and a saw that the Load Fooocus Inpaint node wasn't working anymore, I had to rename inpaint_v26.fooocus.patch into inpaint_v26.fooocus.pth so the node would find it ( still the same path ). I can only guess krita-ai-diffusion problem comes from whatever whatever change they did which prevent that node from finding a .patch extension ?

**Comment by kevinwbryant** [comment]
![image](https://github.com/user-attachments/assets/6efb92d3-b325-4218-8504-718de046664b)
I also encountered this problem today. Remember to downgrade this node. Upgrading to the latest version will cause the problem of being unable to use sdxl. @K-O-N-B

**Comment by Acly** [comment]
https://github.com/Acly/comfyui-inpaint-nodes/issues/93

not sure what the remaining issue is though, does the problem occur with using `extra_model_paths.yaml` or without?

**Comment by lunatico67** [comment]
> [Acly/comfyui-inpaint-nodes#93](https://github.com/Acly/comfyui-inpaint-nodes/issues/93)
> 
> not sure what the remaining issue is though, does the problem occur with using `extra_model_paths.yaml` or without?

In comfyui is it possible to revert to previous versions of your custom node ComfyUI inpaint nodes?

**Comment by K-O-N-B** [comment]
> inpaint_v26.fooocus.patch

I've downgrade this node, but still can't use SDXL  :((((((

**Comment by dmac-afk** [comment]
> [Acly/comfyui-inpaint-nodes#93](https://github.com/Acly/comfyui-inpaint-nodes/issues/93)
> 
> not sure what the remaining issue is though, does the problem occur with using `extra_model_paths.yaml` or without?

Occurs without using the yaml file. 
My model directory is just default comfy structure

**Comment by Acly** [comment]
> Occurs without using the yaml file. My model directory is just default comfy structure

Using [146a2f1](https://github.com/Acly/comfyui-inpaint-nodes/commit/146a2f17b1f91eb155011ab36aa349c696b6e38b)? And the behavior is that content of `ComfyUI/models/inpaint` shows up, but not files with `.patch` extension?

Any other custom nodes that might interfere because they also use the inpaint folder?

I'm a bit puzzled, after the fix it works for me in all constellations, with .patch file showing up too.

**Comment by mwo72** [comment]
I had the same problem, but after disabling this node 'https://github.com/yolain/ComfyUI-Easy-Use' it works again

**Comment by Acly** [comment]
> I had the same problem, but after disabling this node 'https://github.com/yolain/ComfyUI-Easy-Use' it works again.

That helped, it was the kind of mistake that is quite obvious but you don't see when staring at it...

Latest version ([422eccd](https://github.com/Acly/comfyui-inpaint-nodes/commit/422eccd86685e084b551fb7e14bc025d77a64cc2)) should work also with Easy-Use

**Comment by mendo878** [comment]
@Acly  bro, then what is the solution? it does not recognize me.

**Comment by gambikules** [comment]
Any fix ?
