### ISSUE TITLE
Flux 1 dev with Cloud server

### ISSUE THREAD

**Issue by krishnaik3** [Acly/krita-ai-diffusion#1357]
is it possible to configure the interstice.cloud server instance to use the Flux 1 dev model? Would like to use inpainting with the cloud server

**Comment by megagrump** [comment]
Licensing issues; can't use it in a commercial setting. 

(It's possibly a bullshit license that can be ignored for several reasons, but no one knows for sure yet)

**Comment by Acly** [comment]
Yes it's tricky. Would need some more throughput and comitment to Flux to have chance of working out licensing.

Not quite clear yet if it doesn't make more sense to invest into a more flexible and permissive model.
