### ISSUE TITLE
Improve in painting features.. add parameters like inpaint mode

### ISSUE THREAD

**Issue by RanjithGadde447** [Acly/krita-ai-diffusion#1361]
Please improve inpainting features.. 
Please add parameters like inpaint mode .. 
Currently I can't create different colour dress inpaint 

Please add parameters like used in fooocus. 3 modes 
Default Inpaint outpaint , (initial latent enable, denoise strength 100)
improve details ( initial latent enable, inpaint denoise strength 50)
Modify content ( initial latent disable, denoise strength 100
These parameters help create better results)

Inpaint pannel
Drop down menu for 3 options 
Initial latent check box
Denoise strength slider

**Comment by Acly** [comment]
https://github.com/Acly/krita-ai-diffusion/wiki/Inpainting

There are a lot of options.
