### ISSUE TITLE
can't find IPadapter model?

### ISSUE THREAD

**Issue by K-O-N-B** [Acly/krita-ai-diffusion#137]
![屏幕截图 2023-11-27 135226](https://github.com/Acly/krita-ai-diffusion/assets/152141077/584249ac-f2d6-46fc-91aa-12d9883a53d6)

I am sure I place the files in the right folder, and all the files download from ComfyUI manager or hugface.

![image](https://github.com/Acly/krita-ai-diffusion/assets/152141077/7c81e38e-ca0a-4b7d-bece-8754a2b69e14)

**Comment by K-O-N-B** [comment]
PS, 

this problems shows when I selected "connect to external server".

I try "local server" today, it is work well.

so I copy the local server ipadater files to external server folder. but still not working.

**Comment by Acly** [comment]
Files look fine, can you check client.log file for a line that includes "Available IP-Adapter models"? It should list the models Comfy finds. Does the Comfy web UI list the models in the IPAdapterApply node?

**Comment by K-O-N-B** [comment]
![屏幕截图 2023-11-28 172106](https://github.com/Acly/krita-ai-diffusion/assets/152141077/b62e6c08-7caa-48f9-8ed0-6d08418957cc)
![屏幕截图 2023-11-28 172345](https://github.com/Acly/krita-ai-diffusion/assets/152141077/38f7bcd5-403a-4042-a5cd-10de572473d9)

comfyUI can load the model.

**Comment by Acly** [comment]
But both the log and UI confirm that it only finds 2 files, and they are not the right ones. Your windows explorer screenshot showed more files, but Comfy doesn't find them. Are you sure they're in the right place?

**Comment by K-O-N-B** [comment]
I guest the ComfyUI can't read bin files? but those 2 safetensors files shows in comfyUI.

and here is the full path, any problems?

![屏幕截图 2023-11-28 173857](https://github.com/Acly/krita-ai-diffusion/assets/152141077/712cf51d-9592-4074-96f7-ca771c8ee7fb)

**Comment by K-O-N-B** [comment]
I search all my drivers. 2 folders have those files, and all files are same Coz I've copy them before.
all the files download from comfyUI manager. (and I installed local server today, so  I copy those model files in ".server" place it  into the folder below) 

H:\ComfyUI-qiuye\ComfyUI\custom_nodes\IPAdapter-ComfyUI\models
H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models

and then, comfyui "load IPAdapter Model" still only read 2 bin files as my screenshot above.

Krita still show the warning message.

any chanse mixed up?

**Comment by Acly** [comment]
Maybe try removing the first folder (`IPAdapter-ComfyUI` is old implementation, maybe it interferes). Just a guess, I don't have a better idea.

**Comment by K-O-N-B** [comment]
i have delete \IPAdapter-ComfyU....

still not working, sad.
