### ISSUE TITLE
Model script does not work.

### ISSUE THREAD

**Issue by bbecausereasonss** [Acly/krita-ai-diffusion#1371]
First its not located in the folder you mentioned after install, so I had to download and place it there seperately...

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\krita\ai_diffusion\download_models.py", line 25, in <module>
    from ai_diffusion import resources
ImportError: cannot import name 'resources' from 'ai_diffusion' (unknown location)

**Comment by Acly** [comment]
You're in the wrong folder, it's in `C:\Users\...\Roaming\krita\pykrita\ai_diffusion` (note the `pykrita`)

**Comment by bbecausereasonss** [comment]
Okay, now gives me No models selected for download.

**Comment by Acly** [comment]
Use `python download_models.py --help` for options on what to download.

It used to download everything by default, but by now thats 100GB+ I think. Usually you want a subset. Though if you really want everything append `--all`.

Example for when you want SDXL and already have a checkpoint:
```
python download_models.py --sdxl --controlnet
```

**Comment by veeroo18** [comment]
> Use `python download_models.py --help` for options on what to download.
> 
> It used to download everything by default, but by now thats 100GB+ I think. Usually you want a subset. Though if you really want everything append `--all`.
> 
> Example for when you want SDXL and already have a checkpoint:
> 
> ```
> python download_models.py --sdxl --controlnet
> ```

This worked for me, but needs a detailed step by step guide to utilize comfyui models checkpoints without double downloading files
