### ISSUE TITLE
Feature: easy one click transparent mask for inpaint

### ISSUE THREAD

**Issue by kalle07** [Acly/krita-ai-diffusion#1375]
HELP Workflow mask for inpaint #1347 

i want a mask not a selection !

iam prof in Adobe photoshop but here i dont get it even with the help of
https://docs.krita.org/en/user_manual/selections.html#display-modes

it is TOTALY complicated !!!
every inpaint option in any known program like forge, a1111, swarmui, invoke, fooocus is one click!

i think you can talk with krita to get a simple solution  ;)

**Comment by Acly** [comment]
You need to use this https://docs.krita.org/en/user_manual/selections.html#global-selection-mask-painting-a-selection
Select the mask layer and use a brush to paint the mask. Very simple.

It's really not hard, I will not add something that already exists.

**Comment by kalle07** [comment]
if it works fine but i dont get it - iam a ADOBE professional !

so first
![grafik](https://github.com/user-attachments/assets/818b54c8-022a-4d31-bda4-843846fc72ca)


than ???
![grafik](https://github.com/user-attachments/assets/c77c1163-16d3-41b3-9f17-682abe853bdb)

???
what add masklayer  ???
add tarnsparent ??
add local selection ?? 

i tryed all but none work ...

**Comment by kalle07** [comment]
help?
