### ISSUE TITLE
ERROR:root:Failed to validate prompt for output 12:  ERROR:root:* IPAdapterApply 9:

### ISSUE THREAD

**Issue by iconnoci** [Acly/krita-ai-diffusion#138]
ERROR:root:Failed to validate prompt for output 12:
ERROR:root:* IPAdapterApply 9:
ERROR:root:  - Required input is missing: start_at
ERROR:root:  - Required input is missing: end_at
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

![QQ截图20231127140548](https://github.com/Acly/krita-ai-diffusion/assets/22522962/88ecae6c-3a8b-4899-ba26-1b00cd46cf61)

[krita-ai-diffusion] 1.8.1
krita 5.2.1
comfy ui  SHA-1: 39e75862b248a20e8233ccee743ba5b2e977cdcf
ComfyUI_IPAdapter_plus SHA-1: a1ddc8b729d360f86cc44fc98ec0b10c94f1747b

**Comment by Danamir** [comment]
It seems the latest `IPAdapterApply` node takes two new arguments in parameter. I didn't have those, so I updated my installation and two new lines appeared : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/2bf87904-84bf-46dd-bb98-0875a3037811)
