### ISSUE TITLE
Graph: ComfyUI Resets Negative "Min" Values to 0 When Loading Saved JSON Workflows saved via the Krita Plugin

### ISSUE THREAD

**Issue by patrickchamp** [Acly/krita-ai-diffusion#1381]
**Description**:
After saving a custom workflow using the Krita AI Diffusion plugin, negative "Min" values in Parameter nodes are reset to zero upon loading the JSON file in ComfyUI. Additionally, the Min value cannot be adjusted back to a negative number within ComfyUI, requiring manual JSON editing after saving the api workflow. This issue complicates small edits to saved workflows and impedes sharing workflows, as any loaded JSON reverts negative values to zero, potentially without other users noticing.

**Expected Behavior**:
- The JSON workflow should retain Parameter node "Min" values upon reloading in ComfyUI.
- Users should be able to adjust Min values to negative values, directly within ComfyUI without manual JSON modification.

**Observed Behavior**:
- Negative "Min" values are reset to zero when loading the saved JSON in ComfyUI.
- The Min value in Parameter nodes cannot be changed back to a negative value within ComfyUI after loading.
- Editing workflows with negative Min values requires manual adjustment in the JSON file.

**Steps to Reproduce**:
1. Save a custom workflow using the Krita AI Diffusion plugin that has negative "Min" values in Parameter nodes.
2. Load the saved JSON workflow in ComfyUI.
3. Observe that all negative Min values in Parameter nodes are reset to zero.
4. Attempt to set Min values back to negative within ComfyUI; note that it’s not possible.

**Additional Information**:
- **Workaround**: Currently, the only workaround is to manually edit the JSON file to reintroduce negative Min values after saving, or to always work from the original non-api workflow versions and only share non-api workflows with other users.
- **Potential Scope**: This issue may extend beyond negative Min values, potentially affecting all Min values upon reloading (not tested).
- **Note**: There is no "Open Saved Workflows Folder" option in the plugin, so i realized i may not be doing it the right way. Let me know.

**Comment by Acly** [comment]
I think I fixed this today in https://github.com/Acly/comfyui-tooling-nodes/commit/517790d1d6c044f2aab1bc1a9c570caf1138dc6b - if you're using a custom install you can try updating comfyui-tooling-nodes
