### ISSUE TITLE
please help please I'm begging you

### ISSUE THREAD

**Issue by brodieleee21312** [Acly/krita-ai-diffusion#1385]
please help how to fix socket not connected and download all the required models in one script without waiting days or hours for the fils to download with huggingface

**Comment by brodieleee21312** [comment]
and it won't work it says download_models.py: error: the following arguments are required: destination

**Comment by Sorry-Im-Stupid** [comment]
You don't need ALL of them unless you plan on generating comparison charts. In usual applications you can only use one checkpoint and a handful of Loras at a time.

**Comment by brodieleee21312** [comment]
im talking about the required models for krita ai image generation

**Comment by brodieleee21312** [comment]
clip vision and stuff
