### ISSUE TITLE
HOW TO CHOOSE THE FLUX MODEL IN KRITA WHEN  I NEED USE THE "LIVE"???

### ISSUE THREAD

**Issue by therover-01** [Acly/krita-ai-diffusion#1387]
i am using the flux 1.dev fp8 to work in LIVE,but its always slowly and no effect! which model should i use like the sd1.5 with lcm?

**Comment by Acly** [comment]
You can try https://huggingface.co/ByteDance/Hyper-SD/blob/main/Hyper-FLUX.1-dev-8steps-lora.safetensors
but I'm not sure how good it is, there is nothing built-in yet.

**Comment by hjmeneses** [comment]
where we can put that model tp try?

**Comment by Acly** [comment]
It's a Lora, you can use it like any other Lora. They have some instructions on what weight to use etc.
