### ISSUE TITLE
Feature Request: Make seed accessible from dock

### ISSUE THREAD

**Issue by SteffenDuenner** [Acly/krita-ai-diffusion#139]
Right now the seed is only available from the plugin configuration. Would be nice to have it in the dock to quickly change / set it to fixed.

**Comment by ImpulseMirror** [comment]
Would also be nice if I could configure the Lora from the dock as well. Maybe both being optional for those that like a clean UI instead.

**Comment by Acly** [comment]
Seed options are now part of the queue button popup in [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0)
