### ISSUE TITLE
Server execution error: Missing required parameter '1. Prompt' for custom workflow

### ISSUE THREAD

**Issue by nabileisa** [Acly/krita-ai-diffusion#1393]
Hi i got this error in krita when attempting to use the sorting feature in 1.28.0
`Server execution error: Missing required parameter '1. Prompt' for custom workflow`
this happened with the example workflow and any other workflow i tried to create that used the sorting feature
see attached workflow.
[krita workflow_api.json](https://github.com/user-attachments/files/17733379/krita.workflow_api.json)

Another issue that is unrelated
I get this error if I switch workflows in graph mode if I'm using  `Krita Style` node and try to run in directly without change
`Error: Style auto not found`  ,  or `Error: Style regular not found` depending on which default i have in the node.
And I would have to chose another style for the error to go away and the workflow to work again.

I should note that I'm using custom installation and the latest `comfyui` and `comfyui-tooling-nodes`
thanks for your awesome work on this plugin.

**Comment by Acly** [comment]
Fixed in [v1.28.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.28.1)
