### ISSUE TITLE
download_models.py with Flux not working correctly

### ISSUE THREAD

**Issue by ChristianMayer** [Acly/krita-ai-diffusion#1398]
I get
```
$ python download_models.py -v -d --flux  ~/path/to/ComfyUI/
Generative AI for Krita - Model download - v1.28.0

No models selected for download.
```
Although `$ python download_models.py -v -d --sdxl  ~/path/to/ComfyUI/` would work as expected.

**Comment by Acly** [comment]
`--flux --checkpoints` will list Flux dev/schnell checkpoints.
`--flux` would just be the prerequisites, but there currently aren't any.

So it's working as expected for now, there just isn't much there yet for flux.

**Comment by ChristianMayer** [comment]
I don't understand that answer. The Flux model itself is already available on my system, but that shouldn't matter.

What I'm missing is that it doesn't tell me that it wants to download the controlnets https://github.com/Acly/krita-ai-diffusion/blob/00536f49a80b6508974291aa966d4699b94fdf71/ai_diffusion/resources.py#L660-L696

**Comment by Acly** [comment]
Oh, forgot I added those.
`--flux --controlnet` lists them.
