### ISSUE TITLE
GGUF model support

### ISSUE THREAD

**Issue by ricperry** [Acly/krita-ai-diffusion#1411]
With the official FLUX and SD3.5 models being too large to work on many GPUs, and the prevalence of quantized models in .gguf format, it would be nice to support .gguf model files. This makes it necessary to specify the CLIP_L and T5XXL model paths, (specifying VAE path is already supported). Request official support for this method of running Flux and advanced SD3x models.

**Comment by Acly** [comment]
Flux: already supported #1176 
SD3.5: doesn't work yet, but issue exists #1405
