### ISSUE TITLE
Error:无法找到 LoRA"hyper'，它被采样器预设"Realtime-Hyper’使用

### ISSUE THREAD

**Issue by Coffeeja** [Acly/krita-ai-diffusion#1425]
![1732114438604](https://github.com/user-attachments/assets/0aafa2a1-014c-46a8-8f30-77e40846618c)
使用提示词的“生成”功能，可以正常生画，使用实时绘画出现报错，该如何解决

**Comment by Acly** [comment]
You can't use Realtime/Hyper sampler with SD3, the model doesn't exist so far.
If you want to use Live, select the same Sampler for Quality and Performance.
It will not be fast.

![image](https://github.com/user-attachments/assets/519c1a35-a804-4e87-b0bd-d9aaeb8e959c)
