### ISSUE TITLE
It can be generated normally without a selection, but not in selection or lasso mode, reporting an error.

### ISSUE THREAD

**Issue by cdmusic2019** [Acly/krita-ai-diffusion#143]
It can be generated normally without a selection, but not in selection or lasso mode, reporting an error.

The following errors are reported
got prompt
ERROR:root:Failed to validate prompt for output 32:
ERROR:root:* IPAdapterApply 12:
ERROR:root:  - Required input is missing: start_at
ERROR:root:  - Required input is missing: end_at
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
![01](https://github.com/Acly/krita-ai-diffusion/assets/126891037/57ab2dee-b9e6-4cde-bbb8-4583ce2c3419)
![02](https://github.com/Acly/krita-ai-diffusion/assets/126891037/e6009a9e-a213-4cf7-9543-6d40e874f460)
![03](https://github.com/Acly/krita-ai-diffusion/assets/126891037/a599067c-c6c5-46bf-ae57-1bb0502c0891)

**Comment by Danamir** [comment]
Cf. #138

It will be fixed with the next PR.

**Comment by cdmusic2019** [comment]
I've managed to fix it, thanks for your help!
