### ISSUE TITLE
Support for FLUX.1 Tools

### ISSUE THREAD

**Issue by WatermelonMango451** [Acly/krita-ai-diffusion#1430]
Today, Black Forest Labs have announced FLUX.1 Tools:

- FLUX.1 Fill: State-of-the-art inpainting and outpainting models, enabling editing and expansion of real and generated images given a text description and a binary mask.
- FLUX.1 Depth: Models trained to enable structural guidance based on a depth map extracted from an input image and a text prompt.
- FLUX.1 Canny: Models trained to enable structural guidance based on canny edges extracted from an input image and a text prompt.
- FLUX.1 Redux: An adapter that allows mixing and recreating input images and text prompts.

https://blackforestlabs.ai/flux-1-tools/

**Comment by agoulddesign** [comment]
Looks like depth and canny can be easily implemented with loras but inpaint and redux need to be quantized.

**Comment by GumDeveloper** [comment]
> Looks like depth and canny can be easily implemented with loras but inpaint needs to be quantized.
> 

may i ask for the background info of why  it needs to be quantized ?

**Comment by agoulddesign** [comment]
> may i ask for the background info of why  it needs to be quantized ?
> are there limits to sizes krita ai can handle ?

The unquantized version requires a lot of VRAM. I can barely run them on 16GB, and 24GB+ is needed to run optimally.

Also, I'm almost certain that even the loras don't work well (or at all) with quantized models. I haven't been able to get them to work with .safetensor files, and friends are reporting that they don't work well with GGUF quantized models. Could be wrong.

**Comment by GumDeveloper** [comment]
OK, thx, i wasnt even aware that my 16GB wouldnt be or might not be enough... from that point, yeah, if its true... *sigh* thanks for responding !

**Comment by Acly** [comment]
#### Redux
Implemented this as a "Reference" image layer, some observations:
* Strength can be adjusted, but not at a fine granular level (it basically has like 3 settings, weak/medium/strong)
* Time range can also be adjusted, but limited usefulness. Almost everything happens in the first 10% of sampling.
* Also works with Schnell 

#### Depth & Canny
The Loras work well for me, also with quantized (GGUF) base models. There are some restrictions though:
* Adjustable strength, although there is not much trade-off and 1.0 is the best setting
* Time range could technically work, but is complex, not composable, and not really worth it
* **Can't be mixed!** Unlike ControlNet, only 1 model at a time.

I dunno. The exsiting CN for Flux are not very good, but these Lora are somewhat restrictive. Not going to keep both though.

#### Inpainting (Fill)
Quants (GGUF) are available, works as advertised. As with other inpaint model, you have to load a copletely new model into memory when you inpaint, and it can't easily be used with finetunes.

Not really sold yet, but I might just make the Alimama CN optional, that way if people don't have it they can use the fill model and it will work for inpainting.

**Comment by GumDeveloper** [comment]
> Not really sold yet, but I might just make the Alimama CN optional, that way if people don't have it they can use the fill model and it will work for inpainting.

That would be nice.

**Comment by Danamir** [comment]
I made a quick patch to test the Flux Fill model, and I must say I find it much more reliable than the Alimama CN method.

It is no fine tune model, but it can imitate the source style pretty well. Once the base work is done for the outpainting/inpainting, you can always switch back to any model to do the refining.

**Comment by Acly** [comment]
[1.29.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.29.0) has full support for Redux, the Depth/Canny Lora.

You can also use Fill, but it's not really integrated, have to use it as separate model.

My experience hasn't been great tbh, like everything Flux it's excrutiatingly slow and the results often not better than what I could get with SDXL in 1/6th of the time. Probably there's exceptions, but meh. Sloooooow.

@Danamir  If you see something wrong with the workflow let me know, I admit I didn't experiment that much. I override guidance to 30, that seemed important.

**Comment by Danamir** [comment]
> @Danamir If you see something wrong with the workflow let me know, I admit I didn't experiment that much. I override guidance to 30, that seemed important.
> PS: If you have Alimama inpaint CN, you need to remove it to use Fill.

Thanks for the update !

I removed my flux inpaint CN and tested the worklow. It seems to work as intended. I can confirm that the 30 guidance is really helping. 

As expected it's slow, but for me the results are impressively good.
