### ISSUE TITLE
Krita Server running - Connection error 

### ISSUE THREAD

**Issue by 3H4D0W** [Acly/krita-ai-diffusion#1431]
I am getting this error after the plugin update. I couldn't figure out what the problem was. I tried several ways as far as I researched on the internet but it didn't work. Please help

![Screenshot 2024-11-21 191429](https://github.com/user-attachments/assets/3b4dad77-5146-4488-8356-6cb2f30338fb)

**Comment by JapanTalker** [comment]
I'm getting the same thing after updating to the newest version. I tried searching on the Internet for resolutions and stumbled upon a video directing me to here.

**Comment by JapanTalker** [comment]
I ended up uninstalling Krita & reinstalling it to resolve the issue.

**Comment by Acly** [comment]
If you can provide client.log, there might be a hint about what went wrong.

Realistically though, reinstall is the easiest way to fix. You can backup your models to avoid re-downloading them.

**Comment by 3H4D0W** [comment]
I uninstall and reinstall krita that fix my problem
