### ISSUE TITLE
[Error] Server execution error: mat1 and mat2 shapes cannot be multiplied (154x2048 and 768x320)

### ISSUE THREAD

**Issue by kojr9x** [Acly/krita-ai-diffusion#1432]
**model =** Pony Realism V2.1

**action =** ControlNet and/or Inpainting → [ error occurs ] 

> Server execution error: mat1 and mat2 shapes cannot be multiplied (154x2048 and 768x320)

**Comment by Acly** [comment]
Try the "Generate (Custom)" mode for inpainting and untick "Seamless".

There is actually no inpaint model or ControlNet models either for Pony (as far as I know), the SDXL ones aren't really compatible.
