### ISSUE TITLE
"ERROR: Could not install packages due to an OSError: [WinError 225] " - when trying to install any python package in Krita AI

### ISSUE THREAD

**Issue by DrawPurple** [Acly/krita-ai-diffusion#1433]
I always had problems installing Stable diffusion on my computer. That's why I constantly use cloud services. But now i need first. 
last time ｗhen I installed Stable Diffusion separately, there was a problem with Pytorch which I still haven't solved. Maybe this is related? Please help me!

**Comment by Acly** [comment]
WinError 225: "Operation did not complete successfully because the file contains a virus or potentially unwanted software"

That could be a hint.

**Comment by DrawPurple** [comment]
But, its no virus . I added that to the exclusion list in my antivirus? but still did not work.

**Comment by DrawPurple** [comment]
Problem solved

**Comment by VectorGudi** [comment]
how did you fix it?

**Comment by VectorGudi** [comment]
I already fixed the problem

**Comment by 666xSatanx666** [comment]
How did you guys fix the problem? im still getting the error
