### ISSUE TITLE
ERROR During Installing

### ISSUE THREAD

**Issue by dj0012** [Acly/krita-ai-diffusion#1434]
![Screenshot 2024-11-23 at 8 40 02 PM](https://github.com/user-attachments/assets/9527c907-4b5b-4b55-b45b-4c469dbdffdd)

**Comment by Acly** [comment]
This is related to incompatible Python (or macOS) version. I don't know enough about it to suggest a fix, but there are other issues like about this problem (eg #528 #1101).
