### ISSUE TITLE
Receiving this error when trying to use Live generation mode with my XL models

### ISSUE THREAD

**Issue by SilverSix311** [Acly/krita-ai-diffusion#1436]
`Server execution error: ModelSamplingDiscreteDistilled.__init__() got an unexpected keyword argument 'zsnr'`

**Comment by LoganX83** [comment]
I run into the same problem, but not with every Model. 
Like when using Juggernaut_X or something like that, it works fine. But as soon as I add a Lora, it won't work.

**Comment by Acly** [comment]
I think this is related to LCM, which is outdated / no longer supported version of low-step sampling.

As mentioned in above comment, please switch Sampler to Hyper.
