### ISSUE TITLE
Trying to run on Google Colabs

### ISSUE THREAD

**Issue by thatcomicsguy** [Acly/krita-ai-diffusion#144]
I've been trying to run this on my Colabs account, but have been running into some trouble...

Message from Krita setup when trying to connect...

**The following ComfyUI custom nodes are missing:
IP-Adapter https://github.com/cubiq/ComfyUI_IPAdapter_plus
Ultimate SD Upscale https://github.com/Acly/krita-ai-diffusion/releases/download/v0.1.0/ComfyUI_UltimateSDUpscale_6ea48202a76ccf5904ddfa85f826efa80dd50520.zip
External Tooling Nodes https://github.com/Acly/comfyui-tooling-nodes**

I've managed to include most of the dependencies, but the ones listed above I can't seem to figure out.

I suspect it's quite simple, but I think I need help. This is the notebook I've been trying to get running:

https://colab.research.google.com/github/comfyanonymous/ComfyUI/blob/master/notebooks/comfyui_colab.ipynb

**Comment by Acly** [comment]
Following [requirements for comy](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md) you can install the custom nodes via git
```
%cd custom_nodes
!git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git
!pip install -r comfyui_controlnet_aux/requirements.txt
!git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus.git
!git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git
%cd ComfyUI_UltimateSDUpscale
!git submodule update --init
%cd ..
!git clone https://github.com/Acly/comfyui-tooling-nodes.git
%cd ..
```
untested, but should be something like this. Then you download the models with `wget` to the correct places, lots of examples already in the collab.
