### ISSUE TITLE
why do I need SD1.5?

### ISSUE THREAD

**Issue by olliacc** [Acly/krita-ai-diffusion#1444]
```
Error: Missing CLIP Vision model: sd1.5/pytorch_model.bin, sd1.5/model.safetensors, clip-vision_vit-h.safetensors, clip-vit-h-14-laion2b-s32b-b79k
Checking for files with a (partial) match:
```
why do I need SD1.5 to use to use krita-ai-diffusion? can't I just any other model like Sana?

Do I really need all of this 
<img width="653" alt="image" src="https://github.com/user-attachments/assets/0df05e86-b79e-4c4c-9785-338cb2678866">
to use a non-stable diffusion model?

**Comment by Acly** [comment]
You need what's listed here in "Shared": https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup
You do not need SD1.5 stuff if you don't use SD1.5. Clip vision is related to Clip, used by many models.

Some models are used in various places at various times by the plugin, easier to check them at startup.

**Comment by olliacc** [comment]
> You need what's listed here in "Shared": https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup You do not need SD1.5 stuff if you don't use SD1.5. Clip vision is related to Clip, used by many models.
> 
> Some models are used in various places at various times by the plugin, easier to check them at startup.

so is it only SDXL and SD1.5 allowed?
what if I only wanted flux?
