### ISSUE TITLE
Failed to update plugin to 1.29.0

### ISSUE THREAD

**Issue by piotr-kucharski** [Acly/krita-ai-diffusion#1448]
![image](https://github.com/user-attachments/assets/38e25149-a154-4c3e-8bac-38dba5dfc3fd)

But I updated manually...

**Comment by Acly** [comment]
There was a wrong version of the file still cached by some web servers, but it should fix itself in a few minutes.

I just checked and it's working again for me.

**Comment by ETCore7** [comment]
Thank you for the plugin and dedication, Acly.
