### ISSUE TITLE
Turn off input image resizing in Flux fill

### ISSUE THREAD

**Issue by esmail-mkh** [Acly/krita-ai-diffusion#1449]
It seems that when we do a Fill with Flux fill, the input image is resized to 512x512 or 1024x1024, is it possible to turn off the resize to fill the input image, and fill with original size?

**Comment by Acly** [comment]
Depends, it shouldn't resize if it's not necessary. What is the size of the input image?

If the image is > 2k resolution the fill won't work properly at the moment. In that case you can disable resize in Style > Advanced Checkpoint settings > Preferred resolution. Just set it to something big.

**Comment by esmail-mkh** [comment]
> Depends, it shouldn't resize if it's not necessary. What is the size of the input image?
> 
> If the image is > 2k resolution the fill won't work properly at the moment. In that case you can disable resize in Style > Advanced Checkpoint settings > Preferred resolution. Just set it to something big.

Ok thanks you, I will try.
