### ISSUE TITLE
Server running - Connection error: Connection established, but the server is missing one or more custom node

### ISSUE THREAD

**Issue by Guiihenx** [Acly/krita-ai-diffusion#1452]
Hello, I am installing Krita + Krita AI for the first time on MacMini M4 and having this error: **Server running - Connection error: Connection established, but the server is missing one or more custom node****

The error I can see from client.log is this: 2024-12-01 23:50:55,631 ERROR Missing required node ETN_LoadImageBase64 from package External Tooling Nodes (https://github.com/Acly/comfyui-tooling-nodes) ... but you can see the full error in the client.log file attached.

[client.log](https://github.com/user-attachments/files/17970464/client.log)

[server.log](https://github.com/user-attachments/files/17970465/server.log)

Any ideas on how to fix this pls? Some very basic stuff I already tried were: Restart Mac, Reinstalling Krita, Deleting and Reinstalling Krita AI Plugin... no success so far. Any help is very appreciated, thanks!

**Comment by Acly** [comment]
Reason is that the install uses Python 3.9 on your system, which is a bit old and causes an error at the moment.
There is a newer version of comfyui-tooling-nodes though which should be compatible again.

You can wait for next update, or try to patch it manually:
* download https://github.com/Acly/comfyui-tooling-nodes/archive/refs/heads/main.zip
* extract contents of the folder inside the zip into `your-server-install-path/ComfyUI/custom_nodes/comfyui-tooling-nodes` (such that it overwrites the existing files there)

**Comment by Guiihenx** [comment]
It worked! Thank you very much!

**Comment by Aaarmaan** [comment]
> Reason is that the install uses Python 3.9 on your system, which is a bit old and causes an error at the moment. There is a newer version of comfyui-tooling-nodes though which should be compatible again.
> 
> You can wait for next update, or try to patch it manually:
> 
> * download https://github.com/Acly/comfyui-tooling-nodes/archive/refs/heads/main.zip
> * extract contents of the folder inside the zip into `your-server-install-path/ComfyUI/custom_nodes/comfyui-tooling-nodes` (such that it overwrites the existing files there)

Thanks it works for me too.
