### ISSUE TITLE
Server Execution Error: noise_mask

### ISSUE THREAD

**Issue by 3H4D0W** [Acly/krita-ai-diffusion#1456]
Everything was fine but suddenly I get this error. Some resources says that I have to update Comfy but sadly I don't know how to do it. Please help.

![Screenshot 2024-12-03 184749](https://github.com/user-attachments/assets/3d7affd6-b4b2-4ec6-b572-f9dbe3d0d5cf)

**Comment by Acly** [comment]
It looks more like ComfyUI is up-to-date, but comfyui-inpaint-nodes are not.

Is this managed server?

Either way you will have to manually update from https://github.com/Acly/comfyui-inpaint-nodes in some way, if you want to avoid a reinstall or waiting for next plugin update.

**Comment by 3H4D0W** [comment]
Thank you so much I did what you said, and this solved my problem. Thanks!
