### ISSUE TITLE
Request: Add option to open local server to network

### ISSUE THREAD

**Issue by austeregrim** [Acly/krita-ai-diffusion#1459]
Request: Add option to open local server to network when starting the server.

A checkbox that when enabled, adds the argument `--listen` to the server execution, to open the service to all networks on the server.
Could be implemented with a NIC/IP selection, to select which IP to listen on, adding `--listen 192.168.1.30` (respectively) for the network selected.

This removes my requirement to edit the settings.json to add the listen argument, and provides others the option to open their kritaAI/ComfyUI server to other network users.

**Comment by Acly** [comment]
very old issue that is still open: #129
