### ISSUE TITLE
Request: inpaint option

### ISSUE THREAD

**Issue by celll1** [Acly/krita-ai-diffusion#147]
Thanks for the good work!

I am trying to generate and modify an image using this plugin.
When I select a range and generate it, it regenerates it within the size of the selection.
Often when a model is trained at a relatively large resolution, this method does not adequately depict the object.
For example, When trying to modify a part of the person, such as a hand, a person's face forcibly dipicted in this small area.
Can you add an option to regenerate at the original resolution and show only the masked areas from the whole?
(Corresponding to inpaint area: "Whole picture" or "Only masked" in AUTOMATIC1111/stable-diffusion-webui)

Best regards.

**Comment by Acly** [comment]
Hi, if you can share more info about what parameters you tried  and the use case it will be easier to think about a good solution.
Note that inpaint already considers an area around the mask as context, and you can configure it in settings Interface > Selection Padding. For 100% inpaint usually initial generation happens at whole picture level (or something very close) already. 

See also discussion in #38 - some kind of explicit control could be added.

**Comment by Acly** [comment]
Closing this, and will post updates to #38
