### ISSUE TITLE
[Feature request] Save all outputs to a folder on pc/server where the comfy instance is running on 

### ISSUE THREAD

**Issue by SHoogstad** [Acly/krita-ai-diffusion#1486]
i had multiple times where krita crashed(not an issue by this plugin) and didn't auto save correctly, so the output was gone along the prompt. So i think i would be nice and a good addition to this plugin, as you could also track output of your work

**Comment by Acly** [comment]
I would be more worried about losing my work than the AI outputs.... I'm not sure Krita crashing & Autosave not working are good reasons to implement this. Not exactly a typical situation (I hope).

I'm generally against saving all images also as files. They are already saved in the document, and it means they need manual clean up (#357, #946).

**Comment by SHoogstad** [comment]
i think its is a good option that could be off by default as this can prevent someone loosing his progress if krita crashes and autosave did not save
