### ISSUE TITLE
The "Refine" mode's "Focus" option behavior feels counterintuitive and inverse of what one would expect.

### ISSUE THREAD

**Issue by FreeeFry** [Acly/krita-ai-diffusion#1487]
The behavior and UI description of the "Focus" setting is unclear and counterintuitive when using the "Refine" mode tbh.
Currently, the description of the "Focus" option states (when you hover your mouse over it):
"Use the text prompt to describe the selected region rather than the context area / Use only one regional prompt."

This suggests that when "Focus" is unchecked, the prompt is supposed to describe the surrounding area rather than the selected region, this behavior is unintuitive as one would naturally expect the prompt to apply directly to the selected area, not the surrounding content.

If enabling "Focus" means that the prompt is applied to the selected area (as in a typical inpainting scenario), then it should:
1. Be automatically enabled if the user selects an area of an image as it aligns with user expectations when selecting a region.
2. Be clarified in the UI to avoid confusion about what the setting does.

In case it actually works differently than what the description clearly states, additional clarification is needed about what "Focus" actually affects.

Expected behavior:
- When an area is selected, the default behavior should apply the prompt to the selected region. I should not need to enable a separate "Focus" option to achieve this, especially since it hides under the "custom" sub-option.
- The "Focus" option should automatically activate when a region is selected to ensure behavior aligns with user expectations.

Using latest version of both Krita and the plugin on Windows 11.

**Comment by Acly** [comment]
> This suggests that when "Focus" is unchecked, the prompt is supposed to describe the surrounding area rather than the selected region

Yes. More precicely it should describe the entire context area, which includes the selection.

"Focus" enabled applies the text only to the selection. You seem to have understood it correctly, so I guess the description is clear?

The confusion seems to be about two things:
* Your expectation that this is always what you would want. I don't think this applies to common scenarios like "Remove Content" or "Expand". Focus enabled is also a bit slower and doesn't make much sense or work well if the selection is small.
* How "Custom" works: this is a _separate operation_. Its configuration only applies when you use it. The other modes (Fill, Expand, Remove/Add Content...) are not affected, and they will use Focus where it makes sense, eg. add content always does.

**Comment by FreeeFry** [comment]
The confusion was more relating what is meant by "context area", I assumed this was the selected area more or less but I think I understand it better now after having re-read the wiki article a few times.

Great plugin! ⭐
