### ISSUE TITLE
[Feature request] More controls from the main Docker GUI

### ISSUE THREAD

**Issue by broli** [Acly/krita-ai-diffusion#149]
* Add negative prompt for Live mode
* Allow for embeddings to be loaded/used (if this is already working then i must be doing something wrong)
* Add the option to use the "restore face" thingy

**Comment by Muskelmagier** [comment]
negative prompt in live mode is already possible. since version 1.8 

look under option->Interface->Negative prompt

**Comment by broli** [comment]
> negative prompt in live mode is already possible. since version 1.8
> 
> look under option->Interface->Negative prompt

Yeap. thanks! I havent updated by the time I asked for the feature 
Thanks for implement it!
