### ISSUE TITLE
Live painting generate image on blank canva

### ISSUE THREAD

**Issue by quinnzoeyn** [Acly/krita-ai-diffusion#1504]
![image](https://github.com/user-attachments/assets/bd1ea180-3635-4c77-a01e-5752e160c05f)

How do i solve this?
Im using default checkpoint and pony, SD15

**Comment by Acly** [comment]
Solve what exactly? That it draws subjects (girls mostly) if there isn't anything else?

I don't think there is a 100% solution, anime checkpoints are strongly predisposed to image with subject.

Some things help: lower strength, more specific prompt ("scenery", "background", "no humans"), use a negative prompt
