### ISSUE TITLE
How do I undo the 3 character limit before auto complete pops up?

### ISSUE THREAD

**Issue by Reaper176** [Acly/krita-ai-diffusion#1514]
I have several sets of autocomplete csv's that I would like to start showing suggestions on the first letter. This was not a problem until recently. Anyone know what I would need to change for this to go back to the way it was. Please and thank you.

I tried:
    Changing:
```
if not name.startswith("<") and len(name.rstrip()) > 2:
```
back to
```
if not name.startswith("<") and len(name) > 2:
```

This did not look to have any effect.

**Comment by Acly** [comment]
It was always 3 characters. The only thing that changed was whether space is included when counting characters or not.

If you want to change it to 2 characters change the `> 2` to a `> 1`

It introduces a noticeable delay for bigger tag collections because too many things are matched.

**Comment by Reaper176** [comment]
ah, I had received someone else's config at some point and only noticed the one change in the diff.
it had been set to 
```
if not name.startswith("<") and len(name) > 1:
```
This allowed the one letter and the single space after it to start the auto completion.

Thank you for your response, and your hard work on this project. Me and my family love it. <3
