### ISSUE TITLE
[Bug]1.8 will clear the comfyui folder

### ISSUE THREAD

**Issue by bingling00** [Acly/krita-ai-diffusion#152]
![image](https://github.com/Acly/krita-ai-diffusion/assets/61322616/1f22fbc2-4a67-41e2-ad38-439c852e9a4a)
If you choose the already installed comfyui folder, the comfyui folder will be deleted!!

**Comment by Acly** [comment]
It doesn't just delete the folder. If you do "Upgrade" it will replace Comfy install with the plugins version, is that what happened? If the upgrade failed the folder should still be around, only moved to a temporary folder next to it.

I will change it next version to refuse any folder that has not been originally created by the plugin. It's not intended to fix/manage custom installs.

**Comment by Kaharos94** [comment]
Yeah. that should probably have been the way it should work from the beginning, as this shitstain of a plugin just deleted AND corrupted my entire output folder. really , great idea. Especially the part where it doesn't safe copy by first copying and then deleting. Sorry if this sounds a little aggressive, but one shouldn't expect that it touches anything else but the files it actually needs.

**Comment by Acly** [comment]
To upgrade Comfy itself it has to reinstall it. But you're right this was a fuck up, I am sorry about your lost data.
The backup/safeguard mechanisms exist, but they assumed the initial folder move would succeed, which wasn't safe outside the folder structure the plugin installer creates.

I released an updated version 1.8.2 which only installs into empty folders, or upgrades installs previously made by the plugin.
