### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by 1dadou1** [Acly/krita-ai-diffusion#154]
This error occurred when I created a new .json in Style Presets
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13499919/server.log)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13499920/client.log)
![Snipaste_2023-11-29_18-41-14](https://github.com/Acly/krita-ai-diffusion/assets/26129828/19ec5b5f-3cae-4a43-ad5e-b125f85dc98b)

**Comment by Acly** [comment]
I haven't had any luck trying to reproduce this. Was there anything else particular about the situation it produced this error? Does it happen everytime? Is there an active connection when you create the style, and what style/SD checkpoint is selected at the time?

**Comment by 1dadou1** [comment]
Thank you for your response. I have resolved the issue; it was due to a missing zoom functionality in the comfyUI.
