### ISSUE TITLE
[Discussion] SDXL Turbo mode

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#155]
I played with the new SDXL Turbo checkpoint this morning, and here are a few notes relevant to krita-ai-diffusion.

#### StableDiffusion SDXL Turbo
The base model from Stable Diffusion (available [here](https://huggingface.co/stabilityai/sdxl-turbo)) works blazingly fast at 1 to 4 steps, and 1.0 CFG. **But** it is limited to SD 1.5-like resolutions, ie. around 512x512. Many samplers don't agree too well with it, and the negative prompts are completely disabled.

On the positive side ControlNet is working, but can be difficult to fine-tune because of the few steps involved. With a hires step, its quality is better than LCM mode in my humble opinion. Still, it would be quite a pain to handle in the krita plugin, because of the resolution limitation and the subsequent upsampling needed.

#### Custom-made models

That being said, a better solution seems readily available. Many SDXL models merged with Turbo are popping everywhere. I tested [TurboVisionXL](https://civitai.com/models/215418?modelVersionId=242733) (since this is based on DynaVision which is quite good). 

The major problem above is solved : the base resolution is from SDXL (around 1024x1024), and you just have to set it to something like 6 steps and cfg 1.0 with LCM sampler to get it working right now. It works best with DPM++ SDE (Karras or normal), which is not available directly in the plugin. I tried it with a minor code modification, and the results are really good for this speed.

There is still the problem of the low steps number limiting the range of denoise values used, but still.

#### Implementation in krita-ai-diffusion

Just adding the DPM++ SDE sampler seems to be the quickest way to use the Turbo models. (Note: when the advanced samplers are added, there may be a need to set the min steps in the style definition).

The live mode could eventually be updated to have an option to use the base Turbo model at 512x512 and 1 step, it is ridiculously fast.

On a future note, I'm not sure if the Turbo mode can be converted to a LoRA as was the case with LCM. If that's the case, a simple LoRA injection would be enough to activate a turbo mode. Otherwise a full model download may be needed.

**Comment by Danamir** [comment]
Well, look what just appeared : [SDXL Turbo-LoRA](https://civitai.com/models/215485/sdxl-turbo-lora-stable-diffusion-xl-faster-than-light?modelVersionId=243508) 😅

**Comment by Acly** [comment]
The LoRA doesn't work at 1 step, but results at 3/4 seem good.

I'm wondering what effect SDTurboScheduler actually has, it doesn't seem to do much?

**Comment by Danamir** [comment]
I'm quite disappointed with the LoRA, I can't get results approaching TuboVisionXL. I'll let a few days to the LoRA makers to see if a better version emerges.

I tried SDTurboScheduler and the SamplerCustom, versus a normal step and KSamplerAdvanced. The results were a little bit different, but not really better or worse. The ControlNet effects seemed to be stronger with the SamplerCustom tho.

**Comment by Danamir** [comment]
Okay I found settings that works for me with Turbo LoRA. DPM++ SDE (Karras or not) sampler, LoRA at 40%, 6 steps, 2.5 CFG scale. 

It's working with the previous LoRA, but even better with this one [PAseer-SDXL-LCM and Turbo](https://civitai.com/models/216590/paseer-sdxl-lcm-and-turbo-accelerator?modelVersionId=244085) that mixes LCM **and** Turbo. LoRA at 50%, 6 steps, 3.0 CFG.

The quality is pretty equivalent, but the latter has better prompt coherency at SDXL resolution, and thus suffers less from the "long limbs syndrome" in portrait mode, and from the "duplicate syndrome" in landscape mode.

Strangely enough, the Turbo LoRA seems to strengthen any style applied, where the LCM+Turbo one seems to lessen it.

I'm also seeing a dip in performance when generating with a Turbo model or a normal model + Turbo LoRA. I'm down to 1.20 it/s from 2.3 it/s . Almost twice as slow ! But since I use 3x less steps, there is still an improvement. Do you have the same results speed wise ? It may be on my system only.

Some tests, left : normal, middle : LCM+Turbo, right : Turbo

![forge](https://github.com/Acly/krita-ai-diffusion/assets/15424198/fec891cb-5561-4f3f-8be4-ff436651b135)

![forge_2](https://github.com/Acly/krita-ai-diffusion/assets/15424198/5f9a1d7f-b71b-4ded-b8bb-26b35836fe3c)

**Comment by Danamir** [comment]
FYI, the same prompts with turbovisionXL . The quality is very good, the speed the same as with the LoRAs, and it also suffers from the long limbs syndrome :  
![forge_3](https://github.com/Acly/krita-ai-diffusion/assets/15424198/7c758f3b-3018-4734-b3b4-c3143b9f5089)
![forge_4](https://github.com/Acly/krita-ai-diffusion/assets/15424198/d0c940aa-7e67-42f4-a469-11a9e447b145)

**Comment by Acly** [comment]
> I'm also seeing a dip in performance when generating with a Turbo model or a normal model + Turbo LoRA. I'm down to 1.20 it/s from 2.3 it/s . Almost twice as slow !

I see no speed difference regarding model/lora. Are you comparing DPM++(SDE) to DPM++2M(SDE)? The former evaluate the model twice at each step, so it's always twice as slow. But typically need only half the steps.

Your parameters work for me too, but it's interesting how quickly quality deteriorates if you go outside the "good" range.
* SDE/Ancestral samplers seem to work a lot better (all the converging samplers give poor result in comparison for me)
* The "slow" 2-evaluation samplers seem to work better (when comparing them using half the steps)

Eg. DPM++2s ancestral is also quite nice. 
It also works to increase Lora weight, and decrease CFG+steps proportionally (gets continually faster at cost of quality & control). But at no point the Lora becomes as good as the Turbo model for 1-step generation.

**Comment by Danamir** [comment]
> Are you comparing DPM++(SDE) to DPM++2M(SDE)

Nop, that was DPM++ SDE everywhere, it may have something to do with my ComfyUI install.

> It also works to increase Lora weight, and decrease CFG+steps proportionally

Yeah that was my approach. I started at 100% lora, and very low CFG + steps, then I increased / decreased the values accordingly.

**Comment by Danamir** [comment]
After some more testing, I'm not sure I like the LCM + Turbo lora anymore. It's more stable at SDXL resolution, but you loose much creativity. All the results seems to be variations of the same pose, and the styles are much less prevalent.

A good solution seems to be the first Turbo LoRA at 50%, DPM++ SDE sampler, 6 steps, 1.5 CFG (with this lora, it seems the low cfg does not impact the contast as much as with the other one, and it reduces the long limbs appearing), and most importantly : 768px base instead of 1024px (just set the SDXL resolution * 0.75). 

I makes kinda sense since this is a 512 lora mixed with a 1024 model. 😅

**Comment by Danamir** [comment]
Rahh, I don't kwow anymore. 😬 The best option may be to give the user the choice of turbo method.

Last round of samples, for the road. The LCM+Turbo feels slightly closer to the original picture.

SDE, 18 steps, 7.0 cfg : 
![grid-normal](https://github.com/Acly/krita-ai-diffusion/assets/15424198/f10ed313-4ae0-4f41-88ea-42f95f018255)

SDE, 50% LCM+Turbo, 2.5 cfg :  
![grid-lcm-turbo-2 5cfg](https://github.com/Acly/krita-ai-diffusion/assets/15424198/d95b4eda-f163-41d9-a021-8ea405447147)

SDE 50% Turbo, 1.5 cfg :  
![grid-turbo-1 5cfg](https://github.com/Acly/krita-ai-diffusion/assets/15424198/f6e32297-7560-42c3-b9a7-5b84c0095673)

**Comment by Acly** [comment]
Closing:
* Turbo models can be used efficiently now 
* Require manual resolution configuration, but I don't know how it could be detected
* LCM is a better fit for Live (due to better img2img at low samples)
