### ISSUE TITLE
ImportError: Cannot import name 'util' from partially initialized module (circular import?)

### ISSUE THREAD

**Issue by Anonymole** [Acly/krita-ai-diffusion#156]
On Windows 10
After unzipping, placing, opening Krita and hitting Settings and Py Plugins, this is the message that shows on hover over ai diffusion selection (which is grayed out):

~~~
TrackBack (most recent last call)
Module not loaded
C:\Users\[USER]\AppData\Roaming\krita\pykrita\ai_diffusion\__init__.py
line 15, in
from . import util
ImportError: Cannot import name 'util' from partially initialized module 'ai_diffusion' (most likely due to a circular import)
Could not import ai_diffusion
~~~
Version: krita_ai_diffusion-1.8.1.zip
Krita Version: 5.2.1

**Comment by Acly** [comment]
Strange. Can't spot any obvious problems with your setup, and it just fails at the very first import.
Can you open the file (`ai_diffusion\__init__.py`) and just remove the line line 15, `from . import util`? Curious if it will fail the next or if it's a problem with the particular module.

**Comment by Anonymole** [comment]
Well, that's curious, as that file was not in the zip I pulled down.

I'll pull it down again and take a look inside.

**Comment by Anonymole** [comment]
Pulled down 1.8.2 and it's vastly different than 1.8.1.
That version worked.
