### ISSUE TITLE
Generation Error in Krita but OK in webUI

### ISSUE THREAD

**Issue by HackingU0** [Acly/krita-ai-diffusion#157]
My device: macbook Pro M1 Max
<img width="456" alt="截屏2023-11-29 下午6 48 31" src="https://github.com/Acly/krita-ai-diffusion/assets/101508770/bdaf520f-7321-4c6d-9623-5f87af5a9d28">

**Comment by Acly** [comment]
This is with or without selection?
It sounds like something isn't supported on M1/MPS, which should be reproducible in web ui - but you'd also have to use similar workflow.

**Comment by Acly** [comment]
I saw some Mac/MPS related commits in [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) repo. Maybe it fixes the issue?
