### ISSUE TITLE
Unable to install server on a fresh krita and plugin install, getting Error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by LinkTree3** [Acly/krita-ai-diffusion#160]
As the title says I'm unable to install the server on a fresh, Python, Krita and plugin install, getting Error: invalid command 'bdist_wheel'

I tried updating pip, I tried installing the wheel package but nothing seems to help

Any suggestions?

Traceback (most recent call last):
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 264, in install
    await self._install(cb)
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 161, in _install
    await install_if_missing(dir, self._install_custom_node, pkg, network, cb)
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 555, in install_if_missing
    await try_install(path, installer, *args)
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 550, in try_install
    raise e
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 545, in try_install
    await installer(*args)
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 238, in _install_custom_node
    await _execute_process(pkg.name, self._pip_install("-r", requirements_txt), folder, cb)
  File "C:\Users\\{user}\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 539, in _execute_process
    raise Exception(f"Error during installation: {errlog}")
Exception: Error during installation:   error: subprocess-exited-with-error

  

  Preparing metadata (pyproject.toml) did not run successfully.

  exit code: 1

  

  [12 lines of output]

  running dist_info

  creating C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info

  writing C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\PKG-INFO

  writing dependency_links to C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\dependency_links.txt

  writing requirements to C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\requires.txt

  writing top-level names to C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\top_level.txt

  writing manifest file 'C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\SOURCES.txt'

  reading manifest file 'C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\SOURCES.txt'

  adding license file 'LICENSE'

  writing manifest file 'C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath.egg-info\SOURCES.txt'

  creating 'C:\Users\\{user}\AppData\Local\Temp\pip-modern-metadata-ed11ndkx\iopath-0.1.10.dist-info'

  error: invalid command 'bdist_wheel'

  [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.

hint: See above for details.

2023-11-30 16:14:46,846 ERROR Installation failed

**Comment by Acly** [comment]
Which command is failing here (what is it trying to install)?
The installer uses its own stand-alone version of python, so when you try to install a package like `wheel` manually, you need to make sure to use that python's pip. Eg.
```
your-server-install-path\python\python.exe -m pip install wheel
```
It shouldn't be needed, but I don't have a better idea why this command would fail either

**Comment by LinkTree3** [comment]
Yea I assumed the same thing but wasn't entirely sure.

The thing is that when that installation fails, Krita will recognize that
this directory already exists and is in use and then it doesn't allow to do
a fix/reinstall to it unless I delete the whole directory and restart
Krita..
