### ISSUE TITLE
(Question) Can you extend an existing image?

### ISSUE THREAD

**Issue by Bmarquez1997** [Acly/krita-ai-diffusion#161]
I'm currently working with this plugin, and something that I've been having trouble with is extending an existing image.  For example, here's my most recent attempt to add legs to one of my friend's characters:

I start with the initial image, adding space to the canvas for the legs to be added
![image](https://github.com/Acly/krita-ai-diffusion/assets/17242591/1a0d50a4-5586-4fb9-8f67-e282d79004d7)

Next, I enter the prompt, select the style, and hit generate.  Once it's done generating, I tend to either get a whole new character placed inside my selection box
![image](https://github.com/Acly/krita-ai-diffusion/assets/17242591/32caba42-d231-4a1d-a3dc-39a0ebcf1272)

or something close to what I'm looking for (in this example I get an image from the waist down) but not connecting/extending the original image
![image](https://github.com/Acly/krita-ai-diffusion/assets/17242591/2fdd6867-94a2-4bce-bcf7-8c6235d24b4e)

I've tried messing with the control layers and strengths, but it doesn't seem to be adjusting the output much.

On a partially related note, are there any plans in the future to build out any documentation/wiki around the different settings/features and how to use them?  Especially now that the plugin is growing and has many different settings to configure, I think even some basic documentation to provide a bit more clarity than the tooltips provide would be extremely beneficial (and would probably help solve issues like mine)

**Comment by Bmarquez1997** [comment]
I'll give that a try, thanks for the advice! Do I select the full image
before generating, or do I just select the new bottom area (with or without
a little bit of overlap)?

And as for documentation, I completely understand.  I've run into the same
issue with multiple other projects, which resulted in a large task to
update old documents which isn't fun.  I'm by no means a stable diffusion
expert (as you can probably tell by my question), but if you think it would
be useful I'd be happy to try and put together some objective documentation
around the plugin as I learn more about it, like a settings overview page
and brief explanations on how to do each of the features you have listed in
the readme.  Nothing crazy, but things like "here's how you would set up
the plugin to do sketch to image" or "this is how you set up a new style
with a new checkpoint/model", just kind of a beginner's overview to
navigating and using the plugin.

I agree, especially with something like this best practices can be really
hard to nail down because it's so subjective on what is "good" and "bad".
I feel like having some kind of blog/forum for users to share results and
their configuration used to get them would be better for that, because then
other users could find something they like and can use it for reference.

**Comment by Acly** [comment]
Just select the bottom area, bit of overlap is added automatically by default.

I'm happy to accept documentation, have to start somewhere. Worst case we both learn something.

**Comment by Bmarquez1997** [comment]
Using your advice it seems to be working more consistently!  Still the occasional full body/not lined up image, but I'm getting more correct ones now so that's not a big deal.  Thanks again for the help!

And sounds good, I'll see what I can throw together.  Would I make a branch and submit a pull request once I'm done with that, or would you prefer me to send it a different way?

**Comment by Danamir** [comment]
Do you use a SDXL or SD 1.5 model ? The SDXL does not have inpainting ControlNet, and relies only on IPAdapter. It works, but it's less versatile than SD 1.5 inpainting.

**Comment by Bmarquez1997** [comment]
Ah, that makes sense.  I'm pretty new to SD so I'm still learning all the terms and how they relate to each other

**Comment by Danamir** [comment]
> It works, but it's less versatile than SD 1.5 inpainting.

That being said, there is an alpha model for SDXL inpainting that can do a respectable job when coupled with IPAdapter and a refine pass with another model. We're not there yet in the krita plugin, but eventually this kind of results could be attained. Here are 6 outputs, no cherry picking, just found a good set of prompt + parameters :  

![grid](https://github.com/Acly/krita-ai-diffusion/assets/15424198/9da15a3b-c281-48ad-b025-f11ef73d4ca7)
