### ISSUE TITLE
Domain not mentioned on repository description.

### ISSUE THREAD

**Issue by acalanato** [Acly/krita-ai-diffusion#162]
README doesn't mention the usage of "https://civitai.com" on the code. Why is that?
Do they keep the data sent?

**Comment by acalanato** [comment]
Sorry for the late reply.
I'm talking about the lines 234~237 of the file network.py:

```
HOSTMAP_LOCAL = {  # for testing
    "https://huggingface.co": "http://localhost:51222",
    "https://civitai.com": "http://localhost:51222",
}

```
Which appear to be mapping the hugginface to local host but overwriting again with another link, the comment says "testing" but what it is really testing?
I wonder because download seems to be done using direct links defined in  "resources.py"

**Comment by Acly** [comment]
This is for running unit tests during development. When the `HOSTMAP` environment variable is set all huggingface and civitai URLs are redirected to localhost where developers can run a local file server.
