### ISSUE TITLE
Plugin will wipe out any directory you give it to install ComfyUI, before actually installing it

### ISSUE THREAD

**Issue by Cloudwalk9** [Acly/krita-ai-diffusion#164]
I fed it my ComfyUI directory, at first not noticing that it can listen on an existing instance, but it did not check if files existed in the given directory and wiped it out.

**Comment by Danamir** [comment]
This was the point of the 1.8.2 release. Cf. the notes of https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.8.2 .

Which version did you install ?

**Comment by Acly** [comment]
Sorry you got hit by this, I should've been more careful.

**Comment by Cloudwalk9** [comment]
@Acly No worries. I make regular backups and [you're not the first](https://github.com/valvesoftware/steam-for-linux/issues/3671)
