### ISSUE TITLE
Plugin is enabled but no docker showing

### ISSUE THREAD

**Issue by giacquar** [Acly/krita-ai-diffusion#166]
I've enabled the pugin in the setting window, and it'white but when I open the dockers menu the entry for this plugin is missing.

**Comment by Danamir** [comment]
Did you install with the release download + unzip ? Or trying a git clone ?

Check the `ai_diffusion/.logs/client.log` file, it may contain more information on the problem.

**Comment by giacquar** [comment]
The release version, there's no log folder in the ai_diffusion folder

**Comment by Duemellon** [comment]
i tried an older 1.8.2 version & it won't work. either. It was working before. Maybe it's a ComfyUI update that's interfering?

**Comment by Acly** [comment]
I doubt it, the connection to ComfyUI comes later. Did you try a "clean" install (remove most of the files in ai_diffusion folder, keep: styles, settings.json, .server)?

**Comment by yandongjun** [comment]
> 我有同样的问题。有趣的是，在启用插件并重新启动 Krita 后，它在插件设置菜单中变成了灰色。我查了一下这意味着什么，它表明错误。将鼠标悬停在它上面时，我可以看到它们。 ![图像](https://private-user-images.githubusercontent.com/56469863/287373770-66e680bf-113b-42e0-a03b-dbf203b0bf8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTIxODEsIm5iZiI6MTcxMjkxMTg4MSwicGF0aCI6Ii81NjQ2OTg2My8yODczNzM3NzAtNjZlNjgwYmYtMTEzYi00MmUwLWEwM2ItZGJmMjAzYjBiZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA4NTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMmU3NmNjNGIwYTQwMjM2ZTJmOTk1YzBlNzE1MzNkMjdhNzc1NzhiYTQ1ODk1OGUyZjZiYzc2ZjczYzJmZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nBvVDiLhqmjQBL4zq75-bHK7TqWejdtVeSePyPjjKVo)我使用的是 Windows 10。

I am also experiencing this issue. Please go to the URL: https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.1 to download the file. Do not just download the source code; the new download should be usable after this.
