### ISSUE TITLE
Krita AI Diffusion 1.2.0 - Installation Error - Xformers

### ISSUE THREAD

**Issue by hansnolte** [Acly/krita-ai-diffusion#17]
Hi Acly,

Krita from today - x64-5.2.0-rc1-ba9a84ac9d - No additional plugins installed - Default Settings
krita_ai_diffusion-1.2.0

![error-installation](https://github.com/Acly/krita-ai-diffusion/assets/7922627/ea831d4d-7bcc-416d-9bf1-d9b66242b205)

**Comment by Acly** [comment]
No idea to be honest. Someone else also reported this, but it installs fine on all systems I tested.
I guess I will remove it for now (it's an optional package for slightly improved performance).

**Comment by Acly** [comment]
Okay I have an idea, please try [release 1.2.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.2.1)

**Comment by meetdilip** [comment]
1.2.1 works :)

**Comment by hansnolte** [comment]
Great work Acly.

And so far, all images are rendered at full GPU speed. Wonderful!

Bye
Hans
