### ISSUE TITLE
Inpainting broken by recent update to IPAdapter

### ISSUE THREAD

**Issue by Hsad** [Acly/krita-ai-diffusion#172]
Commit 77554c of IPAdaptor added an unfold batch option, which krita-ai-diffusion now feeds the wrong input for the node when there is an area selected in Krita. https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/77554c835d2b937fb465e6b8d016e6dba0bb9772

My error within the comfy server output was this:
```
ERROR:root:Failed to validate prompt for output 22:
ERROR:root:* IPAdapterApply 12:
ERROR:root:  - Required input is missing: unfold_batch
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

A temporary solution is to go into ComfyUI/custom_nodes/ComfyUI_IPAdaptor_plus and git checkout 6bb44b which is the commit before the addition of the batch option.

**Comment by Acly** [comment]
[1.9.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.9.0) is now compatible with latest IPAdapter
