### ISSUE TITLE
When I try to generate with Krita AI, I encounter an error related to the IP-Adapter. (Macbook Pro M1 MAX)

### ISSUE THREAD

**Issue by yamkz** [Acly/krita-ai-diffusion#174]
Error: {"type": "prompt_outputs_failed_validation", "message": "Prompt outputs failed validation.", "details": {}, "extra_info": {}} (Error transferring http://127.0.0.1:8190/prompt - server replied: Bad Request) [url=http://127.0.0.1:8190/prompt, code=302] is displayed on the screen,

The following error is displayed in the terminal:
...
got prompt
ERROR:root:Failed to validate prompt for output 17:
ERROR:root:* IPAdapterApply 13:
ERROR:root: - Required input is missing: start_at
ERROR:root: - Required input is missing: end_at
ERROR:root: - Required input is missing: unfold_batch
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

How can I resolve this issue??

The environment is deployed on a Mac and connected via a URL to Comfy. All necessary models and nodes have been installed.

![image](https://github.com/Acly/krita-ai-diffusion/assets/57112629/69a911af-27c2-4e97-a0db-462f42bb223c)

![image](https://github.com/Acly/krita-ai-diffusion/assets/57112629/61aab364-cf5c-475f-825d-0dc3fcfc87a5)

**Comment by Acly** [comment]
It's related to new version of ComfyUI_IPAdapter_plus. Latest release [1.9.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.9.0) should now be compatible.
