### ISSUE TITLE
Inpaint with LaMa

### ISSUE THREAD

**Issue by Acly** [Acly/krita-ai-diffusion#175]
Investigate and implement inpaint pipeline with LaMa as pre-processor as an alternative to IP-Adapter.

IP-Adapter is used to add context in inpaint/outpaint scenarios. It works well in many situations, but has some drawbacks:
1. Not great for removing things since the original image is part of the input 
   #35
1. It's quite heavy-weight, eg. doesn't work with 6 GB VRAM 
   #28
1. Sometimes it doesn't work :)

LaMa is an inpainting GAN which can run as a pre-process to fill inpaint and outpaint areas with some initial content that fits the image. This hopefully makes the diffusion more robust. Probably it will also make it less creative, so it should be an option. Because it's a pre-process it doesn't increase VRAM load at sampling time. It's also generally quite fast and small, but very low resolution makes follow-up diffusion desirable.

Official LaMa repo: https://github.com/advimman/lama
ComfyUI node: https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/

I tried implementing it before, but the ComfyUI node was very "beta" and I only got brown mush in most cases. There is also still a "only CUDA supported" caveat which might be an issue.

**Comment by teadrinker** [comment]
I did some experiments 5 month ago, if it might be of interest. I'm not a ML researcher, but I've done a lot of manual inpainting/outpainting.

 
![outpaint issues](https://github.com/Acly/krita-ai-diffusion/assets/678065/da62b994-0017-40ac-af84-2ceb92ab1306)

**Comment by Acly** [comment]
LaMa is now used for object removal and can be a custom pre-process. Actually the default is MAT instead of LaMa, but very similar.

**Comment by chayleaf** [comment]
I'm getting much better results using IOPaint compared to anything I tried using krita-ai-diffusion. My goal is simply object removal, but when I use krita-ai-diffusion the model's style affects the output very strongly, the result doesn't blend well with the rest of the image at all. Is there a way to use plain LaMa with krita-ai-diffusion, without inpainting?
