### ISSUE TITLE
QUESTION: Do embeddings work? What language do we use? 

### ISSUE THREAD

**Issue by Duemellon** [Acly/krita-ai-diffusion#176]
I have been using the (embeddings:Filename.pt:0.#) format but they seem to have no effect. Is that just me because I'm doing something wrong or what should be used? (this was a 1.8x version experience, FYI)

**Comment by SD-NinoPriore** [comment]
Many checkpoint models and loras come with instructions and specific descriptions and recommendations on how to use them. But there is no way to save that information along with these models when using them with this plugin, which means we have to go to civitai to look up the model or lora each time we want to use it. In the style presets window, it would be helpful if there was a text box or pulldown where we could paste those instructions and they would be saved and available to view whenever the specific model is selected (the instructions would have to be associated independently with the model or lora).
