### ISSUE TITLE
Is there a feature to automatically save images generated in live mode?

### ISSUE THREAD

**Issue by Ingyeorism** [Acly/krita-ai-diffusion#177]
Specifically, I enjoy using my desktop at home as a server to draw pictures outside. 
Is there a way to save every  generated images on my desktop at home?

If there are any related articles on this, please leave a link. 
Thank you so much for creating this great program.

**Comment by Acly** [comment]
No there is no such feature. I'm also a bit sceptical how useful this would be: in just a 30 minute session you might write about 1~2 GB, 99% of which is probably just intermediate output (so basically garbage you have to clean up).

**Comment by papersplease** [comment]
It could be useful for timelapses, but Krita already has the built-in timelapse recording feature:

https://docs.krita.org/en/reference_manual/dockers/recorder_docker.html

(it snaps the canvas obviously, not backend generations with all metadata and stuff as it has no idea about those)
