### ISSUE TITLE
Server Path error - wont connect

### ISSUE THREAD

**Issue by MellyBeany** [Acly/krita-ai-diffusion#18]
Hiya!
So i've done everythin that was put on the step by step installation; but i now get the error during server startup
I am unfamiliar with all this so im not really sure what to do
![691e0f0e1306e05b2733c7a7fdda3640](https://github.com/Acly/krita-ai-diffusion/assets/146889729/dea2253a-6aff-42b4-a419-a8b7f6a4ca9c)

**Comment by Acly** [comment]
Hi,
the error souds like the server was installed without CUDA support, but you're trying to launch it with CUDA. Was CUDA selected before you started installation?
Also it looks like the path you're installing into is the same path where Krita is installed, is that correct? I haven't really considered this, it might interfere with your Krita installation. The server path can be anywhere, but shouldn't point at an existing install.
Finally if you click "View log files" and attach the client.log that would give me some more information to go on.

**Comment by MellyBeany** [comment]
I am not completely sure; I honestly have no idea what CUDA is :^) 
Im not a programmer or a coder so that might be a problem; It is installed in the path of Krita

I'm thinking of verifying the installation files and see what it does next; but im not sure

**Comment by MellyBeany** [comment]
> Hi, the error sounds like the server was installed without CUDA support, but you're trying to launch it with CUDA. Was CUDA selected before you started installation? Also it looks like the path you're installing into is the same path where Krita is installed, is that correct? I haven't really considered this, it might interfere with your Krita installation. The server path can be anywhere, but shouldn't point at an existing install. Finally if you click "View log files" and attach the client.log that would give me some more information to go on.


So coming back to the logfile; here is the client log
[client.log](https://github.com/Acly/krita-ai-diffusion/files/12805869/client.log)

**Comment by MellyBeany** [comment]
> Hi, the error sounds like the server was installed without CUDA support, but you're trying to launch it with CUDA. Was CUDA selected before you started installation? Also it looks like the path you're installing into is the same path where Krita is installed, is that correct? I haven't really considered this, it might interfere with your Krita installation. The server path can be anywhere, but shouldn't point at an existing install. Finally if you click "View log files" and attach the client.log that would give me some more information to go on.

[client.log](https://github.com/Acly/krita-ai-diffusion/files/12805966/client.log)


Hereby the client log :^)

**Comment by MellyBeany** [comment]
PFFF LISTENNN

I changed it to CPU and it work; im dumb, im so sorry ;-;

**Comment by Acly** [comment]
No worries, this stuff isn't obvious at all if you haven't been following it for a while.

CUDA you can use if you have a graphics card from NVIDIA (preferrably one of the pricier ones that isn't too old). If you don't, CPU works, but takes a long time. Because everything runs on your PC it needs to be fairly powerful to be practical.
