### ISSUE TITLE
option for autosave

### ISSUE THREAD

**Issue by Claudecindy** [Acly/krita-ai-diffusion#181]
Dear, Wish you can add an autosave option!  I want to save all the gerneation with meta automaticly in a tempory folder, because sometime i got very good images, but unexpected closed the window and lost the prompts

**Comment by Acly** [comment]
Technically it's possible to save all direct generated outputs. But it's not actually that simple to do (especially including metadata too). And in lot of contexts such as inpaint, refinement, you'd get only the masked portion of an image, which is not very useful without knowing where exactly to insert and combine it with the canvas.

Something you can do:
If you generated something you might want to keep, apply it. It will create a layer, you can make it invisible, or put it at the bottom, but it is now part of your document. The prompt is stored too as layer name. Documents already have autosave feature.

> What could be useful though is a prompt history

Clicking the prompt header in the thumbnail viewer copies the prompt to clipboard. Not obvious and can be extended to be sure.
