### ISSUE TITLE
lora key not loaded and ERROR diffusion_model

### ISSUE THREAD

**Issue by FugueSegue** [Acly/krita-ai-diffusion#184]
I run SD on a separate rig that I access via LAN. I'm somewhat experienced with ComfyUI. I'm new to Krita and this plugin. I've spent the last day trying to set it all up. I had no problems following all the instructions and installing all of the required ControlNets, I even consulted the client.log and discovered a bunch of required ControlNets that were not documented. I thought I got everything working. SDXL seems to function with this plugin. But whenever I try to use SD15, I get a massive wall of errors that I've tried to copy below. I've searched for solutions and found that people have discussed this problem in the ComfyUI repo. The only thing that was suggested was that ComfyUI was attempting to use an SD15 LoRA with an SDXL checkpoint or vice versa. I'm completely baffled because I have no idea how this plugin interacts with ComfyUI. I don't understand what's going on. I'd appreciate suggestions.

Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_k.alpha
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_k.lora_down.weight
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_k.lora_up.weight
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_out_0.alpha
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_out_0.lora_down.weight
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_out_0.lora_up.weight
lora key not loaded lora_unet_down_blocks_1_attentions_0_transformer_blocks_1_attn1_to_q.alpha

(THERE ARE SEVERAL HUNDRED LINES OF MESSAGES STARTING WITH "lora key not loaded". I could not copy all of it into this post.)

lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_1_ff_net_0_proj.lora_up.weight
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_1_ff_net_2.alpha
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_1_ff_net_2.lora_down.weight
lora key not loaded lora_unet_up_blocks_1_attentions_2_transformer_blocks_1_ff_net_2.lora_up.weight
Requested to load SD1ClipModel
Loading 1 new model
[] []
Requested to load BaseModel
Requested to load ControlNet
Loading 2 new models
ERROR diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight shape '[640, 768]' is invalid for input of size 1310720
ERROR diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight shape '[640, 768]' is invalid for input of size 1310720
ERROR diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight shape '[640, 768]' is invalid for input of size 1310720
ERROR diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight shape '[640, 768]' is invalid for input of size 1310720
ERROR diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight shape '[1280, 768]' is invalid for input of size 2621440
ERROR diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight shape '[1280, 768]' is invalid for input of size 2621440
ERROR diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight shape '[1280, 768]' is invalid for input of size 2621440
ERROR diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight shape '[1280, 768]' is invalid for input of size 2621440
ERROR diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k.weight shape '[1280, 768]' is invalid for input of size 2621440
ERROR diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v.weight shape '[1280, 768]' is invalid for input of size 2621440
ERROR diffusion_model.output_blocks.2.0.in_layers.2.weight shape '[1280, 2560, 3, 3]' is invalid for input of size 22118400
ERROR diffusion_model.output_blocks.2.0.skip_connection.weight shape '[1280, 2560, 1, 1]' is invalid for input of size 2457600
ERROR diffusion_model.output_blocks.3.0.in_layers.2.weight shape '[1280, 2560, 3, 3]' is invalid for input of size 11059200
ERROR diffusion_model.output_blocks.3.0.emb_layers.1.weight shape '[1280, 1280]' is invalid for input of size 819200
ERROR diffusion_model.output_blocks.3.0.out_layers.3.weight shape '[1280, 1280, 3, 3]' is invalid for input of size 3686400
ERROR diffusion_model.output_blocks.3.0.skip_connection.weight shape '[1280, 2560, 1, 1]' is invalid for input of size 1228800
ERROR diffusion_model.output_blocks.3.1.proj_in.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.proj_out.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k.weight shape '[1280, 768]' is invalid for input of size 1310720
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.weight shape '[1280, 5120]' is invalid for input of size 1638400
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v.weight shape '[1280, 768]' is invalid for input of size 1310720
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.weight shape '[10240, 1280]' is invalid for input of size 3276800
ERROR diffusion_model.output_blocks.4.0.in_layers.2.weight shape '[1280, 2560, 3, 3]' is invalid for input of size 7372800
ERROR diffusion_model.output_blocks.4.0.emb_layers.1.weight shape '[1280, 1280]' is invalid for input of size 819200
ERROR diffusion_model.output_blocks.4.0.out_layers.3.weight shape '[1280, 1280, 3, 3]' is invalid for input of size 3686400
ERROR diffusion_model.output_blocks.4.0.skip_connection.weight shape '[1280, 2560, 1, 1]' is invalid for input of size 819200
ERROR diffusion_model.output_blocks.4.1.proj_in.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.proj_out.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k.weight shape '[1280, 768]' is invalid for input of size 1310720
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.weight shape '[1280, 5120]' is invalid for input of size 1638400
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v.weight shape '[1280, 768]' is invalid for input of size 1310720
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight shape '[10240, 1280]' is invalid for input of size 3276800
ERROR diffusion_model.output_blocks.5.0.in_layers.2.weight shape '[1280, 1920, 3, 3]' is invalid for input of size 5529600
ERROR diffusion_model.output_blocks.5.0.emb_layers.1.weight shape '[1280, 1280]' is invalid for input of size 819200
ERROR diffusion_model.output_blocks.5.0.out_layers.3.weight shape '[1280, 1280, 3, 3]' is invalid for input of size 3686400
ERROR diffusion_model.output_blocks.5.0.skip_connection.weight shape '[1280, 1920, 1, 1]' is invalid for input of size 614400
ERROR diffusion_model.output_blocks.5.1.proj_in.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.proj_out.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k.weight shape '[1280, 768]' is invalid for input of size 1310720
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.weight shape '[1280, 5120]' is invalid for input of size 1638400
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v.weight shape '[1280, 768]' is invalid for input of size 1310720
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q.weight shape '[1280, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight shape '[10240, 1280]' is invalid for input of size 3276800
ERROR diffusion_model.output_blocks.5.2.conv.weight shape '[1280, 1280, 3, 3]' is invalid for input of size 3686400
ERROR diffusion_model.output_blocks.6.0.in_layers.2.weight shape '[640, 1920, 3, 3]' is invalid for input of size 2764800
ERROR diffusion_model.output_blocks.6.0.emb_layers.1.weight shape '[640, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.6.0.out_layers.3.weight shape '[640, 640, 3, 3]' is invalid for input of size 921600
ERROR diffusion_model.output_blocks.6.0.skip_connection.weight shape '[640, 1920, 1, 1]' is invalid for input of size 307200
ERROR diffusion_model.output_blocks.7.0.in_layers.2.weight shape '[640, 1280, 3, 3]' is invalid for input of size 1843200
ERROR diffusion_model.output_blocks.7.0.emb_layers.1.weight shape '[640, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.7.0.out_layers.3.weight shape '[640, 640, 3, 3]' is invalid for input of size 921600
ERROR diffusion_model.output_blocks.7.0.skip_connection.weight shape '[640, 1280, 1, 1]' is invalid for input of size 204800
ERROR diffusion_model.output_blocks.8.0.in_layers.2.weight shape '[640, 960, 3, 3]' is invalid for input of size 1843200
ERROR diffusion_model.output_blocks.8.0.emb_layers.1.weight shape '[640, 1280]' is invalid for input of size 409600
ERROR diffusion_model.output_blocks.8.0.out_layers.3.weight shape '[640, 640, 3, 3]' is invalid for input of size 921600
ERROR diffusion_model.output_blocks.8.0.skip_connection.weight shape '[640, 960, 1, 1]' is invalid for input of size 204800

**Comment by FugueSegue** [comment]
I figured out what I did wrong. Simple mistake. I incorrectly named the LCM SDXL LoRA as an LCM SD15 LoRA. The errors are gone.

I downloaded the checkpoints, LoRAs, and ControlNets as specified here:
https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md

When I downloaded the LCM LoRAs for SD15 and SDXL, those files have the exact same name. I didn't notice the mix-up. I had two copies of the same LCM SDXL LoRA. I renamed one of them properly and I mistakenly renamed the other one incorrectly.

**Comment by HonZhe** [comment]
I'm also experiencing this problem, what did you do in detail to fix it?

**Comment by aphexetwine** [comment]
> I'm also experiencing this problem, what did you do in detail to fix it?

If you're using LCM, you need to use the correct Lora for SD1.5 models. You can download it from here:
https://civitai.com/models/195519?modelVersionId=424706

**Comment by erperejildo** [comment]
> I figured out what I did wrong. Simple mistake. I incorrectly named the LCM SDXL LoRA as an LCM SD15 LoRA. The errors are gone.
> 
> I downloaded the checkpoints, LoRAs, and ControlNets as specified here: https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md
> 
> When I downloaded the LCM LoRAs for SD15 and SDXL, those files have the exact same name. I didn't notice the mix-up. I had two copies of the same LCM SDXL LoRA. I renamed one of them properly and I mistakenly renamed the other one incorrectly.

not found

**Comment by aphexetwine** [comment]
> not found

Use this link
https://civitai.com/models/195519?modelVersionId=424706
![Screenshot 2024-04-09 at 21 43 05](https://github.com/Acly/krita-ai-diffusion/assets/58233846/c853dcb1-6438-4000-92bf-098b0f41afe7)
