### ISSUE TITLE
install error 1.9.0

### ISSUE THREAD

**Issue by Drakosha405** [Acly/krita-ai-diffusion#186]
Cant install plugin. or now we need full install comfyUI not portable?
Invalid location error when I select comfyUI folder.
![error](https://github.com/Acly/krita-ai-diffusion/assets/146111805/6183130d-095e-4a18-8154-21df11a39d13)

**Comment by AxelFar94** [comment]
To use a already installed ComfyUI, first launch ComfyUI, than connect to it's IP in the second option "Connect to external Server (local or remote)".

**Comment by Drakosha405** [comment]
> To use a already installed ComfyUI, first launch ComfyUI, than connect to it's IP in the second option "Connect to external Server (local or remote)".
I dont remember when I start test this plugin but I could choose 1 option and install missing elements to already installed comfyui.
today I try do same steps and its not work.

**Comment by AxelFar94** [comment]
> > To use a already installed ComfyUI, first launch ComfyUI, than connect to it's IP in the second option "Connect to external Server (local or remote)".
> 
> I dont remember when I start test this plugin but I could choose 1 option and install missing elements to already installed comfyui. today I try do same steps and its not work.

Try chosing the ComfyUI folder inside the "ComfyUI_windows_portable" folder instead

**Comment by Acly** [comment]
> I dont remember when I start test this plugin but I could choose 1 option and install missing elements to already installed comfyui. today I try do same steps and its not work.

I disabled it. It was never intended to work on installs not done by the plugin. And it could do rather drastic things to your comfy install. There is no way to ensure/test it works properly with million different comfy installs out there.

**Comment by Drakosha405** [comment]
> Try chosing the ComfyUI folder inside the "ComfyUI_windows_portable" folder instead

dont work too. only empty folder need

**Comment by Drakosha405** [comment]
> I disabled it. It was never intended to work on installs not done by the plugin. And it could do rather drastic things to your comfy install. There is no way to ensure/test it works properly with million different comfy installs out there.

ok, all what i need now its just manual download all nodes and models and chose 2 type of connection.

But we need update in "Requirements for ComfyUI" for controlnet models  to find needed names and download in https://huggingface.co/lllyasviel/sd_control_collection/tree/main
https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main

**Comment by Acly** [comment]
Well, the idea is that people using existing comfy option have most of these already :)

But I also added a simple [script which downloads models](https://github.com/Acly/krita-ai-diffusion/blob/main/scripts/download_models.py), including optional stuff like control net. Just added today though, not part of a release package yet.

**Comment by Acly** [comment]
Script is now part of the package in [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0) and can be used to list & download all the resources that the internal installer would supports.
