### ISSUE TITLE
Installation error: error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by TimmyKlamvik** [Acly/krita-ai-diffusion#187]
I get this error when following the installation instructions:

See pastebin for full logs: https://pastebin.com/CFevMwX8

# Last outputs before error:

  adding license file 'LICENSE'
 
  writing manifest file 'C:\Users\User\AppData\Local\Temp\pip-modern-metadata-4ec4voxm\iopath.egg-info\SOURCES.txt'
 
  creating 'C:\Users\User\AppData\Local\Temp\pip-modern-metadata-4ec4voxm\iopath-0.1.10.dist-info'
 
  error: invalid command 'bdist_wheel'
 
  [end of output]
 
 
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
 
error: metadata-generation-failed
 
Encountered error while generating package metadata.
 
See above for output.

**Comment by Acly** [comment]
Same as #160 

I can't reproduce this myself, but internet suggest trying the following
```
python\python.exe -m pip install --upgrade wheel setuptools
python\python.exe -m pip uninstall -r ComfyUI\custom_nodes\comfyui_controlnet_aux\requirements.txt
python\python.exe -m pip install -r ComfyUI\custom_nodes\comfyui_controlnet_aux\requirements.txt
```
in a command line inside your server install folder (...\pykrita\ai_diffusion\.server)
