### ISSUE TITLE
Error code 401

### ISSUE THREAD

**Issue by SeeYouPotato** [Acly/krita-ai-diffusion#189]
Hi ,
When i try to generate control layer from current image following error appears. I tried to look for ‘DWPreprocessor’ but I couldn't find it.
![20231205111350](https://github.com/Acly/krita-ai-diffusion/assets/152943069/e6100185-4ffe-4054-8b3d-7805f98a8b1b)
![20231205111417](https://github.com/Acly/krita-ai-diffusion/assets/152943069/a99f49d4-b7ce-4e79-9737-fcb50572f532)

**Comment by e813519** [comment]
This is a problem that I also encountered. In the comfyui_controlnet_aux folder, run install.bat, and the patch related model, and it doesn't report the error.

**Comment by SeeYouPotato** [comment]
> This is a problem that I also encountered. In the comfyui_controlnet_aux folder, run install.bat, and the patch related model, and it doesn't report the error.

Thanks for your solution, the error reporting disappeared!

**Comment by mkyung** [comment]
I had the same problem and confirmed @e813519 solution solved my problem
