### ISSUE TITLE
[feature request] ComfyUI-CoreMLSuite support

### ISSUE THREAD

**Issue by y-ich** [Acly/krita-ai-diffusion#190]
Hi.

Thank you for developing this amazing extension!
This extension let me know Krita.

Since I am a Mac user, it would be nice if the extension supports [ComfyUI-CoreMLSuite](https://github.com/aszc-dev/ComfyUI-CoreMLSuite).
Utilizing Apple Neural Engine via Core ML may perform twice or more faster than Metal depending on processors.

I just started to read codes though I am new about the extension, ComfyUI, and ComfyUI-CoreMLSuite.
I will make a pull request if possilble.

Thank you for your development!

**Comment by Acly** [comment]
Hi

I took a look at ComfyUI-CoreMLSuite, and I think this will be challenging. The nodes are somewhat invasive and restrictive, so I suspect some features of the plugin will not work with this (like IP-adapter). But the majority should work, and you are certainly welcome to try it out!
