### ISSUE TITLE
[discussion] Lora application

### ISSUE THREAD

**Issue by Miraihi** [Acly/krita-ai-diffusion#192]
It's nothing more but a little question that has been bugging me the whole time I've been using this plugin. Is it possible to apply loras just in-prompt, outside of settings/style window? I rarely want to change the basic style, but often need additional loras case by case. What I imagine is `<lora:lora_name:1>`, auto-sd style syntax, but it doesn't appear to work.

**Comment by papersplease** [comment]
It won't work because you're supposed to insert separate LoRA nodes in ComfyUI, rather than using them in the prompt.

Yes, on-the-fly LoRA switching would be nice to have.

**Comment by Danamir** [comment]
I added a quick prompt LoRA support in #198 . This could work with auto-completion at a later stage.

**Comment by Acly** [comment]
Part of [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0)
