### ISSUE TITLE
Update with overwrite option deletes everything

### ISSUE THREAD

**Issue by hwamil** [Acly/krita-ai-diffusion#193]
When I updated to 1.9.0 I figured when it said overwrite, it would be more of a merge operation, leaving the other checkpoints and loras that did not come with Krita AI undisturbed.

Learning the hard way that it simply deletes the old directory and downloads everything from scratch.

All that would be fine if things I'm downloading are small, but files for SD are in the GB territory and it's not fun.

Would it be possible to modify the way the plugin updates? I guess I could host the server myself but it's such a bother in terms of initializing. I like how I can just run Krita and then the plugin in takes care of everything.

Any way, I'll know for next time to move things out of the way before updating lol.

**Comment by Acly** [comment]
Usually the update just takes a few seconds and does not redownload models. Can you share your client.log to see what happened?
