### ISSUE TITLE
[target area] use selection to target area painting doesn't work 

### ISSUE THREAD

**Issue by hyh813** [Acly/krita-ai-diffusion#197]
![下载](https://github.com/Acly/krita-ai-diffusion/assets/88869535/ff4701cd-4f51-487c-94fb-bc198f95760f)
Why did I use a selection and box select it, but I didn't see the effect that only the rest of the selection was hidden and turned black, as you showed?

**Comment by hyh813** [comment]
I use krita5.2.1 + krita-ai-diffusion1.9.0 + windows10 + comfyUI on my 3090

**Comment by Acly** [comment]
The selection won't be effective immediately, but when the next image is generated. Should be pretty fast on a 3090 though.

I don't have an idea why it's not working for you. I tried a few things but can't reproduce it...
