### ISSUE TITLE
(Question) - how to pass --listen command to the server?

### ISSUE THREAD

**Issue by DFarley100** [Acly/krita-ai-diffusion#199]
Is there a way to pass the --listen command to the Krita ComfyUI server? Is seems to involve editing a batch file called nvidia_gpu.bat but I can't find it. I know the server question was answered elsewhere but that seems to be for people who want to set something up they can safely access from anywhere. I realize Krita would have to be running with the plugin activated on the host machine. I just want it on the local network like I've set up for Automatic1111. Thanks.

**Comment by Acly** [comment]
You can start the server on its own. Open a command prompt (or create a .bat file) in the folder where you installed the server:
```
python/python.exe ComfyUI/main.py --listen
```
You can also make Krita start the server like that: add `--listen` to the `server_arguments` in `ai_diffusion/settings.json`.

**Comment by DFarley100** [comment]
This is great - thanks! David

**Comment by DFarley100** [comment]
I tried editing the json file and it worked, although there was a permissions dialog for Python that didn't pop up until I restarted Krita.

**Comment by Acly** [comment]
If you mean the Windows firewall popup, that's expected once you add --listen (informing you that external machines can access the process - home network only unless you also forward the ports to the internet)
