### ISSUE TITLE
Error: Python not found. Please install Python via your package manager and restart despite it already being installed

### ISSUE THREAD

**Issue by roland3564** [Acly/krita-ai-diffusion#2]
Installed version: 3.11
Linux distro: Debian 12.1
Krita version: 5.2

![IMG_6174](https://github.com/Acly/krita-ai-diffusion/assets/32875049/256726bd-e1f4-476c-846b-f7bc2288fcf9)

![IMG_6174](https://github.com/Acly/krita-ai-diffusion/assets/32875049/02169b95-c20a-4826-902e-3941feaa7001)

**Comment by Acly** [comment]
Do you have pip installed also? 
```
sudo apt install python3-pip
```
I think I may have those two lumped together, which admittedly makes the error message confusing in this case.

To find python it tries `which python` and `which python3`
For pip it tries `which pip` and `which pip3`
If those work it should be found...

**Comment by roland3564** [comment]
now it gives me this error https://gist.github.com/roland3564/225dffbce1e796862f9a9ede7e81e46a

**Comment by Acly** [comment]
Hm that seems to be a Debian thing. Some workarounds are described here: https://stackoverflow.com/a/75722775

The best solution would be to use a `venv`.
```
python3 -m venv .venv
source .venv/bin/activate
./Krita-x86_64.AppImage
```
Krita must be started from the bash where you activated the venv. This works on my Ubuntu at least, it now installs all the packages into the venv.

I will test later if I can have the plugin create/activate the venv, so Krita can be started normally.

**Comment by roland3564** [comment]
I managed to solve this part, not the plugin gives me this error:

![IMG_6177](https://github.com/Acly/krita-ai-diffusion/assets/32875049/c615ce1f-914c-4b8f-a2f3-96805e1ddf0c)

**Comment by Acly** [comment]
`CUDA unknown error` doesn't give us much information unfortunately, but this might just be the GPU not being supported, or an issue with the driver.

Does the server start in CPU mode (untick the "Use CUDA" option)?

**Comment by roland3564** [comment]
It does, but I have a nvidia card (MX 130), how can I make the program use it? Or if it won’t can you make it supported?

**Comment by roland3564** [comment]
Maybe it’s because I don’t have cuda installed?

**Comment by Acly** [comment]
I don't think you need install cuda, the libraries come with the python packages and the driver.

I suspect that the GPU will struggle anyway if it isn't simply too old, but it's difficult finding conclusive information about what's supported. I'll try my laptop which has a GPU of the same generation.

**Comment by roland3564** [comment]
Thank you that you’ll try, I’ll await the results

**Comment by Acly** [comment]
Okay so I spent like 3 hours reinstalling NVIDIA drivers, then the boot loader, the kernel, etc. until I got basic CUDA working. Why does this break after every update? My Fedora install is barely 5 months old...

But anyway, it did work in the end! (100s for one image, but hey)

Regarding your problem, I can only say make sure that NVIDIA driver and CUDA are installed and working. I said earlier you don't need to install CUDA, but I was thinking of the CUDA toolkit. I didn't know there was a separate CUDA driver package on linux (`xorg-x11-drv-nvidia-cuda` for me, but might be different on Debian). Check `nvidia-smi` command. Once that worked, the server started for me.

One more issue I encountered: after starting correctly, there was "CUDA error: operation not supported" after triggering image generation. I could fix this by starting the server manually with
```
./venv/bin/python .server/ComfyUI/main.py --disable-cuda-malloc
```
This was required for my GTX 960M - I'm not sure it applies to your GPU too. The server actually has a blacklist which should detect this automatically, but I discovered it's only implemented for Windows. I cannot immediately fix this (it's not my code), but will try to report it.

**Comment by roland3564** [comment]
My Hero, thank you! You’ve put so much effort on it, I’ll see if I can find a way to install cuda on debian :)

**Comment by dCo3lh0** [comment]
i am having a similar issue regarding python, i have 3 python versions installed here on my debian 11, by default /usr/bin/python refers to python 2.7, /usr/bin/python3 refers to python 3.7, while /usr/bin/python3.9 refers to python 3.9, since ComfyUI uses version 3.9 or superior i've installed using this version, but when i try connect krita plugin to ComfyUI, it doesn't recognize any python version at all, here is the log, you can see, it always tries using /usr/bin/python which is the python 2.7 version, i cant change this version at all in your plugin.

[client.log](https://github.com/Acly/krita-ai-diffusion/files/13404867/client.log)

**Comment by Acly** [comment]
I might be able to fix that by changing the search order (look for python3 first, then try python).

Other solutions:
* `apt install python-is-python3`
* use `update-alternatives` to make your latest python the default `python3`

I don't know if you have a reason to stick to old python version (especially python 2 is EOL for years now and should not be used)?

**Comment by dCo3lh0** [comment]
i  think python2 is still used for some system processes in debian 11, so they by default installed python2 and python3, i know python2.7 is old as hell, on the next version debian 12 i think they already removed it.

**Comment by Acly** [comment]
In that case it should be no problem to use `python-is-python3` since it's a package Debian provides. [I also swapped the priority in the code](https://github.com/Acly/krita-ai-diffusion/commit/7a84bcdde277a75576c3b31ee780e2470678767c) for next release.

You will still have to make python 3.9 the default python3, I don't want to hardcode that. I think the system/user should have control which python is used.
