### ISSUE TITLE
dont work 

### ISSUE THREAD

**Issue by HernanFoster** [Acly/krita-ai-diffusion#20]
![hjjjj](https://github.com/Acly/krita-ai-diffusion/assets/100248554/2aed99a3-311c-4033-aa34-ce45e722de82)

test in krita 5.2 and 5.1.2

**Comment by Acly** [comment]
Please install the plugin in your user folder (C:\Users\...), _not_ in C:\Program Files\...
To find the user folder in Krita go: Settings ‣ Manage Resources ‣ Open Resource Folder
https://docs.krita.org/en/user_manual/python_scripting/install_custom_python_plugin.html#manually

**Comment by HernanFoster** [comment]
fix, run as administrator 👍

**Comment by Acly** [comment]
Yes that also works, but it's not ideal :)
