### ISSUE TITLE
Bring back pose creation tool

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#200]
Can't see in 1.9.0 version pose creation button anymore. It was there (and I was using it often) in previous versions :(

**Comment by Danamir** [comment]
It's still there, but sometimes the "add pose" button only appears after deleting and adding back the control layer.

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/bdc6cc53-3416-4c5a-84de-5528ab0c06e3)

**Comment by Acly** [comment]
Hm, in particular it's not visible right after generating a layer...
And anyway the button ought to be disabled when the selected layer is not a vector layer (with a tooltip explaining), not invisible.

**Comment by Acly** [comment]
Fixed in [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0)
