### ISSUE TITLE
[BUG] Generating during the selection of the region will break the selection process

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#201]
The title.

If I use lasso tool and hit generate few times, I can forget about the selecting new regions. As the image is generated, current selection breaks and ends, making sometimes ugly shapes

**Comment by Acly** [comment]
I think this is unavoidable when there is no preview yet and a new layer is inserted, Krita aborts all tool actions when the document is changed. We could add an option to disable automatic preview.

But there is no good reason it should happen for every generation when the preview layer already exists and nothing in the document changes. Which I guess is the main issue.

**Comment by Acly** [comment]
Changed/fixed behavior in [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0)
