### ISSUE TITLE
Live Painting on Selections is not working

### ISSUE THREAD

**Issue by longkinght** [Acly/krita-ai-diffusion#206]
Live Painting on Selections is not working for me. After enabling real-time painting and using the selection tool to choose any location on the canvas, there are no changes in the real-time painting window. Could you please provide me with the detailed steps to properly enable this feature?

**Comment by longkinght** [comment]
![Uploading 微信图片_20231209224922.png…]()

**Comment by Acly** [comment]
Duplicate of #197

**Comment by Acly** [comment]
Nothing special needed to enable it. I do the following:
1. open image
2. select "Live" workspace
3. press Play button to start
4. create a selection using eg. Lasso tool

**Comment by kevinwbryant** [comment]
same problem，live-----selection tool，not working，

**Comment by Acly** [comment]
Still can't reproduce this. Need more info.

https://github.com/Acly/krita-ai-diffusion/assets/6485914/a02570f0-4232-433a-a024-a50fb095e3a6

**Comment by longkinght** [comment]
The issue has been identified. It's because the plugin didn't update successfully. Once it's done, the corresponding version number will be displayed below.
