### ISSUE TITLE
It's awesome that my 4090 actually has 50S 

### ISSUE THREAD

**Issue by q88622406** [Acly/krita-ai-diffusion#207]
Load this BaseModel, super invincible and slow!
![微信截图_20231210024833](https://github.com/Acly/krita-ai-diffusion/assets/54790868/cd73ee9c-1793-4576-8f90-a8d7fe26065a)
![微信截图_20231210024843](https://github.com/Acly/krita-ai-diffusion/assets/54790868/7bb1a396-20b2-4baf-94da-1d8d4a2a289b)
![微信图片编辑_20231210024815](https://github.com/Acly/krita-ai-diffusion/assets/54790868/f92eab15-528a-42a3-a72f-b611f5f17045)

**Comment by Acly** [comment]
Awesome. Now try a smaller resolution.
