### ISSUE TITLE
How do I use XL Controlnet?

### ISSUE THREAD

**Issue by IamTirion** [Acly/krita-ai-diffusion#212]
I thought the dropdown in the control layer would automatically switch to XL Controlnets when I'm using a XL checkpoint, but that's not the case. It doesn't work for me. It seems the Controlnet models in the dropdown are all for SD1.5. How do I use the XL ones? I'm aware that there are only 4 XL Controlnet models available.

Edit: I also have another question. 

https://youtu.be/AF2VyqSApjA?t=61

Is it possible to influence the generated image by colors like in the video without using live painting? I don't see a control layer in the video, yet the generated image followed the painted colours. Am I missing something here? I can't get this working.

**Comment by Acly** [comment]
Regarding controlnet: what do you mean with "it doesn't work"? If you use an SDXL checkpoint, it will automatically use SDXL controlnet. Otherwise you'd simply get an error, they're not compatible at all.

> Is it possible to influence the generated image by colors like in the video without using live painting?

Yes that's what the strength slider does. The lower the strength, the more your existing image influences the outcome.

**Comment by IamTirion** [comment]
> Regarding controlnet: what do you mean with "it doesn't work"? If you use an SDXL checkpoint, it will automatically use SDXL controlnet. Otherwise you'd simply get an error, they're not compatible at all.

![image](https://github.com/Acly/krita-ai-diffusion/assets/50409752/f0eda748-7fcd-409d-9149-62b93df38697)

This is what I mean. I definitely have the Lineart Controlnet downloaded so it's not a missing Controlnet model problem.




> Yes that's what the strength slider does. The lower the strength, the more your existing image influences the outcome.

No, sorry, I didn't explain my problem clearly. I want to paint colours and make them affect the generated image like you did in the video. But instead of doing it in the live painting tab, because my computer isn't good enough for that, I wish to do the same thing in the Generate tab. However, if I paint anything on a layer, then type in some prompts and hit generate, the generated image will have 0 influence from what I painted.

**Comment by IamTirion** [comment]
https://github.com/lllyasviel/ControlNet-v1-1-nightly#model-specification

Well, according to the lineart section here, it says it can receive manually drawn linearts. Anyway, if the lineart control layer is a generated image, it works.

**Comment by Acly** [comment]
The link you posted is for SD1.5, which generally works better with ControlNet. The SDXL line-art model actually has a note somewhere that it primarily works on the generated images (I forgot where I read that). But it does work for hand-drawn stuff too, just maybe lower the strength to 50~60%.
