### ISSUE TITLE
Krita having an issue recognizing existing comfyui install

### ISSUE THREAD

**Issue by Lernwhet** [Acly/krita-ai-diffusion#213]
Hi there.  First, let me thank you for creating this plugin for Krita, it looks great and I can see the great possibilities.  I'm having a little problem, since I already have comfy ui installed.  I'm using Krita with the external server.  I installed the all the custom nodes that Krita was asking for.  However, Krita doesn't see the custom node below, even though it's installed.  Anything that I have to tweak in ComfyUI for Krita to finally see this?  Thanks in advance for your help.

Error: The following ComfyUI custom nodes are missing:
IP-Adapter https://github.com/cubiq/ComfyUI_IPAdapter_plus
Please install them, restart the server and try again

**Comment by Acly** [comment]
The Krita plugin queries ComfyUI for the nodes. If you get this error message it means they're not reported.
Please check in ComfyUI if ipadapter nodes are present - if not there is some issue with the custom node installation.

**Comment by Lernwhet** [comment]
Thanks Acly, I'll look into that.

**Comment by Lernwhet** [comment]
Hi Acly, I fixed the IPAdapter issue with comfy ui.  Plugin works great.  Great images with very little effort.  Thanks again for making this.

**Comment by orbenda83** [comment]
I have the same issue. on mac.
I confirm the IPAdapter plus is installed but krita does not recognize it

**Comment by Acly** [comment]
Note that if you installed/updated IPAdapter yesterday it will no longer be compatible.
https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#warning-ipadapter-v2-complete-code-rewrite-warning

**Comment by AhmedAburady** [comment]
> Note that if you installed/updated IPAdapter yesterday it will no longer be compatible. https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#warning-ipadapter-v2-complete-code-rewrite-warning

That's Exactly what happened so we will wait for an update to the plugin hopefully soon?

**Comment by AhmedAburady** [comment]
IPAdapter v2 works in the new version of the plugin

**Comment by Pauweltje** [comment]
I got it all sorted out........up and running! Booooooooooom!
