### ISSUE TITLE
Feature request: Randomize or increase/decrease seed after copying current result to canvas in Live mode

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#214]
Currently in Live mode after sending a result to the canvas, the same seed used for that result is reused for the next live result. This happens even when setting the seed to 0. Reusing a seed tends to over sharpen an image and slowly introduces more and more artifacts, especially in the background. 

Same seed (911907476):
![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/2e6cfb6d-3701-4e9c-b79f-140895022f5a)

Just one seed higher (911907477):
![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/04f9540d-ed02-4091-9a84-177e7adfc39b)

This isn't an issue with the plugin but rather with Stable Diffusion itself, as it also happens in A1111 in img2img when keeping the same seed for a result. Randomizing the seed or simply increasing or decreasing it by 1 helps fix this issue.

If possible, an option to randomize the seed after pressing the "Copy the current result to the image as a new layer" button or to add or subtract by 1 would perfectly resolve this.

**Comment by Acly** [comment]
I know what you mean, but I'm not sure automatically adjusting the seed is always the right choice. Keeping a stable seed is pretty important for Live mode. If you're adopting a result entirely you probabl want it changed as you say. But I often only adopt a part, a selection, or erase / paint over the copied image. In that case I don't want the rest of the image to change.

If in doubt I think it's better to keep it explicit.

The downside is that people may not realize this kind of burn in effect comes from using the same seed. Adding a checkbox feels like overkill though, adjusting the seed is easy after all.

**Comment by freecoderwaifu** [comment]
Yeah it's mostly just saving that one extra click from the randomize seed button or the up and down button. Though I still think randomizing seed right after sending to canvas with just one button would make the drawing with AI process more natural and seamless, since it prevents overbaking right away, especially starting from simple sketching. 

Some possible ways to do this:
1)An additional button next to the current send to canvas button that can be configured in the settings to either randomize seed or increase/decrease seed by a set number after sending to canvas 
2)Just one extra randomize seed after sending to canvas button 
3) Both a randomize after send to canvas and increase seed after send to canvas button, so 3 buttons but that would honestly be too much

I understand not wanting the UI to be too cluttered though. In that case maybe a keybind to randomize seed and increase/decrease might be better and would also be ok.

**Comment by Pirog17000** [comment]
I'd go with a checkbox/lock button near seed, which will by-default be enabled for this case, like 'seed is locked' and unticking it will make seed random every next iteration

**Comment by Acly** [comment]
I added an option to the settings dialog for now. I tried the lock idea as well but wasn't super happy with it... then I started on persisting some of the UI state in .kra files, and felt it wasn't a choice you did per document, but more of a user preference.

Available in [1.11.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.11.0)

**Comment by freecoderwaifu** [comment]
Thank you, works great👍.
