### ISSUE TITLE
Server execution error: PytorchStreamReader failed reading ZIP archive: not a ZIP archive

### ISSUE THREAD

**Issue by omioki23** [Acly/krita-ai-diffusion#215]
I've updated to a v1.10.0 and now when I try to generate in a selected area I get this error Server execution error: 
![error](https://github.com/Acly/krita-ai-diffusion/assets/149877098/54ead3b6-34f7-4b2f-bf77-d209847bdacd)
What could be the problem?

**Comment by Acly** [comment]
Please share your server.log file (or check for a more detailed error message there), it's hard to say where this is coming from exactly

**Comment by omioki23** [comment]
The issue has been solved by reinstalling the server from scratch. I guess something didn't install properly the first time.
