### ISSUE TITLE
Why is SSD-1B no longer supported?

### ISSUE THREAD

**Issue by motolo** [Acly/krita-ai-diffusion#216]
Until the previous version you could use SSD-1B, why can't you do it anymore?  what led to the non-compatibility with this model?

 Thank you

**Comment by NoMansPC** [comment]
No idea why it says that. I just updated the plugin and SSD is definitely still working.

**Comment by motolo** [comment]
Perchè dall'elenco dei checkpoint non è più possibile sceglierli, almeno nel mio caso non li vedo più presenti.

**Comment by Acly** [comment]
Depends on what do you mean with "working"? I guess basic image generation does work, but it's not detected as a separate base model and doesn't have any ControlNet support.
The means selections don't work (no inpaint, no outpaint), none of the control layers work. I think it also uses the wrong resolution. 

I filtered it out to avoid people running into all those issues.
