### ISSUE TITLE
Connecting on a NGROK application from a server.

### ISSUE THREAD

**Issue by VincentNeemie** [Acly/krita-ai-diffusion#22]
When you try to connect on a NGROK application you get an error on the krita connect server: 
"Error: Error: a bytes-like object is required, not 'str'."

Usually one would get around this using a header request, but after trying to do some alterations in some of the functions of  the file connect.py , I did not achieve success trying these: 

```
async def _post(self, op: str, data: dict):
    headers = {
        "ngrok-skip-browser-warning": "69420",
        "Content-Type": "application/json",
        # Add more headers as needed
    }
    encoded_data = json.dumps(data).encode('utf-8')  # Encode the data as bytes
    return await self._requests.post(f"{self.url}/{op}", encoded_data, headers=headers)
```
And...
```
async def connect(url=default_url):
    # Parse url
    url = url.strip("/")
    if url.startswith("http"):
        protocol, hostname = url.split("://", 1)
    else:
        protocol = "http"
        hostname = url
        url = f"{protocol}://{hostname}"
    client = Client(url)
    try:
        ws_protocol = "wss" if protocol == "https" else "ws"
        headers = {
            "ngrok-skip-browser-warning": "69420",
            # Add more headers as needed
        }
        client._websocket = await websockets.connect(
            f"{ws_protocol}://{hostname}/ws?clientId={client._id}",
            max_size=2**30,
            read_limit=2**30,
            extra_headers=headers,
        )
    except OSError as e:
        raise NetworkError(
            e.errno, f"Could not connect to websocket server at {url}: {str(e)}", url
        )
    return client

```

**Comment by Acly** [comment]
Just 1 line
```
request.setRawHeader(b"ngrok-skip-browser-warning", b"69420")
```
was enough to make it work for me. See commit above. Can you check?

**Comment by VincentNeemie** [comment]
> Just 1 line
> 
> ```
> request.setRawHeader(b"ngrok-skip-browser-warning", b"69420")
> ```
> 
> was enough to make it work for me. See commit above. Can you check?

Yes, it works. Funny thing I tried changing it on server.py and client.py and didn't check on network! thank you for the swift response and efficiency!

**Comment by kishudoshi01** [comment]
Hello a noob question probably but where you able to connect kritaai with ngroc to use it on some another browsers, foresay an ipad? Please help i am not expert in this
