### ISSUE TITLE
Add custom models to Cloud GPU (runpod)

### ISSUE THREAD

**Issue by daniel-richter** [Acly/krita-ai-diffusion#228]
E.g., with runpod, it is possible to "Customize Deployment" where you can extend the `aclysia/sd-comfyui-krita:v1.7.0` base image with your own docker commands. Until now, I couldn't find any detailed information about this base image. Is it possible to add custom models to a cloud GPU image?

**Comment by Acly** [comment]
There is no built-in mechanism which let's you specify models in "Customize Deployment". The Dockerfile is part of this repository, but you don't need to change it to download models. After deployment you can open a terminal (use ssh or Runpod's web terminal) and
```
cd /models/checkpoints
wget https://link-to-your-model-file.safetensors
```
to download custom models. They will be usable in the plugin.

The image also has [croc](https://github.com/schollz/croc) and [runpodctl](https://github.com/runpod/runpodctl) installed for options to eg. send a custom script that downloads your favourite models, so you don't have to do it manually.

Side note: I'm uploading v1.10.0 version of the image at the moment, should be available soon.
