### ISSUE TITLE
[bug] Mystery of Scribble ControlNet for SDXL

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#230]
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/2e4521f1-b186-4f59-8d3c-0e3a5307135c)
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/d1531fa1-100b-4768-b7d0-ea5bf965951d)

Scribble somehow works with SDXL, at the same time the installation menu shows it's uninstalled. 
I mean, it works! And it works very well. I have no idea what magic it is, but will be great to have it detected or marked as supported with SDXL.

**Comment by Acly** [comment]
Maybe this is more of a miscommunication: all ControlNet options which don't have (SDXL) are for SD1.5.

SDXL doesn't have a CN trained on scribbles, but the one for Line Art works okay also for most scribble content (if it's not too rough), so it's used for both.

**Comment by Pirog17000** [comment]
for LineArt yes, works pretty well.

but I'm able to use Scribble option, while using SDXL checkpoint. and it works! However, it shows that the scribble controlnet, which I'm already using, is not installed.
super-confusing

**Comment by Acly** [comment]
Nooo it shows that scribble controlnet for SD1.5 is not installed, which it isn't. And it shows lineart for SDXL is installed, and it just eats your scribbles too. Only _slightly_ confusing.

**Comment by Pirog17000** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/0a362cbf-e49e-44fe-8999-b382b8bb6a5e)

_Aren't line-art and Scribble different controlnets? why it is under different categories then?_

**Comment by Danamir** [comment]
Since there is no dedicated lineart or scribble ControlNet for SDXL, we use the "sketch" CN but with different preprocessors for a pseudo-lineart and pseudo-scribble .

Cf. `resources.py` : 

```
    ControlMode.scribble: {
        SDVersion.sd15: ["control_v11p_sd15_scribble", "control_lora_rank128_v11p_sd15_scribble"],
        SDVersion.sdxl: ["control-lora-sketch-rank", "sai_xl_sketch_"],
    },
    ControlMode.line_art: {
        SDVersion.sd15: ["control_v11p_sd15_lineart", "control_lora_rank128_v11p_sd15_lineart"],
        SDVersion.sdxl: ["control-lora-sketch-rank", "sai_xl_sketch_"],
    },
```

**Comment by Pirog17000** [comment]
Thanks for explanation @Danamir
