### ISSUE TITLE
reactor-node

### ISSUE THREAD

**Issue by ricewind100** [Acly/krita-ai-diffusion#231]
First, thank you all very much for this great work
Would it be possible to implement this?
https://github.com/Gourieff/comfyui-reactor-node

**Comment by Corruptinator** [comment]
I do imagine there would be a lot of work required to implement ReActor into the Krita Ai Diffusion.

**Comment by Acly** [comment]
IP-Adapter FaceID is on its way, I think it's more flexible than reactor.

**Comment by Acly** [comment]
[v1.13.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0) has support for face references now.

It works really well in some cases, but you have to be a bit lucky. Sometimes I have to retry or play with weights a lot.

But the models are very new and there is a lot of development and discussion still going on (eg. [here](https://www.github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195)).  Probably needs some follow up tweaks.
