### ISSUE TITLE
CUDA error... on ancient HW

### ISSUE THREAD

**Issue by megvadulthangya** [Acly/krita-ai-diffusion#236]
Hi! Is it possibru to run Diffusion AI on GTX 750 Ti 4GB ?
I get this error on a freshly installed w11 Latest nv driver...

To me, looks like not possibru... :(

![CUDA error](https://github.com/Acly/krita-ai-diffusion/assets/67601373/df448536-78f7-4943-b773-52f39636e414)

**Comment by gustrd** [comment]
I believe it's not related to hardware, because I can run it at a MX150.

**Comment by megvadulthangya** [comment]
> I believe it's not related to hardware, because I can run it at a MX150 (2GB VRAM).

Yours has CUDA 6.0... mine has 5.0...

**Another question, for the devs, what minimum CUDA version need to run this thing?**

**Comment by Acly** [comment]
Honestly don't know, it depends on pytorch and they don't really document it.

It's possible that pure image generation (without selection) works okay, but it struggles when there is a selection - it's a more complex pipeline and requires significantly more VRAM at the moment.

**Comment by megvadulthangya** [comment]
Thank you! Yeah i see it after that i played a little with settings and see gpuz gpu memory usage went 4050mb ish when freezed and before show that thing...
