### ISSUE TITLE
MacOS Krita 5.2.2, this plugin and RunPod.io ComfyUI Krita template do not work

### ISSUE THREAD

**Issue by thekotfather** [Acly/krita-ai-diffusion#237]
Plugin version 1.10.0
in RunPod Log no errors, this happens when i hit generate button:
<img width="776" alt="Снимок экрана 2023-12-16 в 00 06 42" src="https://github.com/Acly/krita-ai-diffusion/assets/148998686/7a905d08-6f97-4280-8c74-7a0a96a08fab">

But in Krita I don't see generated art, no previews, no LIVE mode, nothing.. 

This is my client.log
client.log
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13689706/client.log)

And this is when i hit the button "apply" in the bottom of AI Generation plugin:
<img width="820" alt="Снимок экрана 2023-12-15 в 23 55 06" src="https://github.com/Acly/krita-ai-diffusion/assets/148998686/6eb06bef-b4e4-4142-a1c5-ae84f1f844e3">

The window opens with this text. Help me please to solve it

[Assertion Error(Error loading Script).txt](https://github.com/Acly/krita-ai-diffusion/files/13689848/Assertion.Error.Error.loading.Script.txt)

**Comment by Acly** [comment]
Likely this issue: https://github.com/Acly/krita-ai-diffusion/issues/74#issuecomment-1819993842

**Comment by thekotfather** [comment]
Thanks, I could't find it yesterday.
It works perfectly now!
Thanks for your plugin!!
