### ISSUE TITLE
Duplicating contents of symlinks when upgrading.

### ISSUE THREAD

**Issue by ManOrMonster** [Acly/krita-ai-diffusion#238]
I copied over the latest version and overwrote the files. Then it wants me to do this:

<img width="200" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/3925151/d7dd2697-6784-4daf-80c6-3fe88a1715ac">

I use symlinks to point to my model folders elsewhere on the drive. I start the upgrade and notice it's taking forever. I check the new "upgrade-1.10.0" folder and it's hundreds of gigs, because for some reason it's copying all my models from that folder to itself.

How can I upgrade the built-in server without this happening?

**Comment by Acly** [comment]
Options:
1. Remove the symlinks, upgrade, restore the symlinks
2. Use the ComfyUI/extra_models_paths.yml file to point to your additional folders instead of symlinks

Please keep in mind the installer expects you to not mess with the installation, it's just not possible to maintain otherwise. Doesn't mean you can't try, just a warning to be cautious.

**Comment by ManOrMonster** [comment]
Thanks. I did try the first option, but it started getting weird. It kept telling me:

`Exception: Error during Ultimate SD Upscale installation: target folder C:\stable-diffusion\ComfyUI-Krita\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale already exists`

This is not a symlink. I deleted the ComfyUI_UltimateSDUpscale folder, same error. I deleted custom_nodes, same error. Finally deleted the whole ComfyUI folder and got that error again. I guess my next move is a total reinstall from scratch. Bizarre.

**Comment by Acly** [comment]
The process is not very complicated: it moves ComfyUI folder to a back-up location, installs the new version from scratch, and then copies models from the old to the new install. So it's not really very different from a reinstall.

If it was interrupted at some point, it's unclear what state it is in, probably something would have to be cleaned up to proceed. But reinstall may just be the quickest solution.
