### ISSUE TITLE
[bug] Negative values for lora doesn't apply

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#241]
To reproduce:

fixed seed, same prompt
1) no lora
2) lora written in prompt field in format as `<lora:name_of_lora>`  - works well
3) lora written in negative prompt field, same format   - works well
4) lora is written in Style preset: no effect both on positive and negative, those fields read only embeddings
5) lora is added in LoRA menu with 'Add' button: works well with positive values, negative values ignored

side note: would be great to have dedicated button for the embeddings as well, same as for LoRA

**Comment by Acly** [comment]
I can't reproduce this: LoRA added via menu in style properties with -100% gives exactly the same results as `<lora:name_of_lora:-1>`
