### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by smallma** [Acly/krita-ai-diffusion#243]
After I installed AI image Generation from Krita, I clicked on configuration to install the required packages for the latest version, but the following error occurred, please help solve it, thank you.

Error Message:
Can't not find the version satisfies the requirement torch, ERROR no matching distribution found for torch

Mac M2, macOS 12.4

Log
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13698435/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13698436/server.log)

<img width="888" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/429250/5b7500b8-97c3-4488-98c1-6057c1a3b845">

**Comment by izcohatl** [comment]
me too, same error,
mac m2, macOS 12.7, selected Use MPS (Metal Performance Shader) 
 ERROR Error during installation: ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

**Comment by jotablindfold** [comment]
anybody?

**Comment by Acly** [comment]
It's likely python version is too old. You can find which one is found in the logs.

Also possible you need macOS 14 (I don't have a mac to test this)

**Comment by hemant571990** [comment]
Extract the latest plugin zip file, go to ai_diffusion/server.py. and edit these lines(Showing for my version of plugin):

torch_args = ["torch~=2.6.0", "torchvision~=0.21.0", "torchaudio~=2.6.0"]
        if self.backend is ServerBackend.cpu:
            torch_args += ["--index-url", "https://download.pytorch.org/whl/cpu"]
        elif self.backend is ServerBackend.cuda:
            torch_args += ["--index-url", "https://download.pytorch.org/whl/cu124"]
        elif self.backend is ServerBackend.directml:
            torch_args = ["numpy<2", "torch-directml"]
        await _execute_process("PyTorch", self._pip_install(*torch_args), self.path, cb)


to:

torch_args = ["torch", "torchvision", "torchaudio"]
        if self.backend is ServerBackend.cpu:
            torch_args += ["--index-url", "https://download.pytorch.org/whl/nightly/cpu"]
        elif self.backend is ServerBackend.cuda:
            torch_args += ["--index-url", "https://download.pytorch.org/whl/nightly/cu124"]
        elif self.backend is ServerBackend.directml:
            torch_args = ["numpy<2", "torch-directml"]
        await _execute_process("PyTorch", self._pip_install(*torch_args), self.path, cb)

Now install as normal way and it would work.

**Comment by hemant571990** [comment]
Sometimes, you need to go to location and update the pip in the environment (activate env).
