### ISSUE TITLE
Unable to launch ai_diffusion plugin in Krita

### ISSUE THREAD

**Issue by yitaogo** [Acly/krita-ai-diffusion#245]
Description:

I am trying to launch the ai_diffusion plugin in Krita, but I am unable to do so. I have installed the plugin correctly and my Python version is 3.10.6. I have tried the following steps to resolve the issue, but none of them have worked:

I have checked the plugin location and made sure that it is in the correct directory.
I have disabled all other plugins except for the ai_diffusion plugin.
I have cleared the Krita cache.
I have temporarily disabled my firewall and antivirus software.
I have checked the plugin logs and error messages.
I am not sure what else to try. Can anyone help me?

Additional information:

I am using the latest version of Krita (5.2.2).
My system meets all minimum requirements.
I have tried using different Python interpreters.
![Screenshot 2023-12-18 131142](https://github.com/Acly/krita-ai-diffusion/assets/59963385/e1f10247-fa5d-467c-8daa-983e64479846)

**Comment by joshua76y** [comment]
same problem，the AI image Diffusion turns grey and can not show in the docker menu

**Comment by Acly** [comment]
Please [check here](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/common-issues.md#plugin-is-grayed-out-in-python-plugins-manager) and let me know what the error message is if you can't resolve it.

**Comment by yitaogo** [comment]
> 请[检查此处](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/common-issues.md#plugin-is-grayed-out-in-python-plugins-manager)，如果无法解决，请告诉我错误消息是什么。

![Screenshot 2023-12-18 122047](https://github.com/Acly/krita-ai-diffusion/assets/59963385/15829d73-eba6-4b46-95f8-4ed2119f4a70)
![Screenshot 2023-12-20 103713](https://github.com/Acly/krita-ai-diffusion/assets/59963385/526c37d1-39ee-41b6-b488-60b982b3aa3b)

This is the error message I received when I opened the Krita configuration window. I also tried downloading the Releases, but the problem still exists. I don't know where the problem is.

**Comment by yitaogo** [comment]
> Please [check here](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/common-issues.md#plugin-is-grayed-out-in-python-plugins-manager) and let me know what the error message is if you can't resolve it.

I have already tried to install the websockets module, but the problem still exists.

**Comment by murphyyyyyyyyyy** [comment]
同样的问题

**Comment by Acly** [comment]
The websockets module is a folder in the plugin location `...\ai_diffusion\websockets`
The folder must exist and not be empty, otherwise you get this error message.
It is contained in the ZIP archive you can download from the release page. If everything is extracted into python plugin location it should work.
Usually looks like this:
```
C:\Users\****\AppData\Roaming\krita\pykrita\ai_diffusion
C:\Users\****\AppData\Roaming\krita\pykrita\ai_diffusion.desktop
C:\Users\****\AppData\Roaming\krita\pykrita\ai_diffusion\websockets
C:\Users\****\AppData\Roaming\krita\pykrita\ai_diffusion\websockets\src
...
```
Configutaion can be different on some systems, but I notice in  your screenshot there is no `pykrita` subfolder, this looks strange.

**Comment by yitaogo** [comment]
I opened the directory under the corresponding path, and obviously there are all the files. But it still doesn't work properly.
![Screenshot 2023-12-23 134515](https://github.com/Acly/krita-ai-diffusion/assets/59963385/43d438e3-b99a-424a-84da-eeaf04a11e12)
![Screenshot 2023-12-23 134545](https://github.com/Acly/krita-ai-diffusion/assets/59963385/b93498bf-6b43-496e-9e05-f8efc409fd56)
![Screenshot 2023-12-23 134608](https://github.com/Acly/krita-ai-diffusion/assets/59963385/eb6cd2f1-e3ea-41cc-8fda-a11928335381)
![Screenshot 2023-12-23 134632](https://github.com/Acly/krita-ai-diffusion/assets/59963385/e0312dd1-1893-445d-88ad-7c9969ae34c2)

**Comment by Acly** [comment]
Yes it looks fine. 

Can you try to open `ai_diffusion\__init__.py` in your install and remove [lines 7-13](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/__init__.py#L7-L13)?
This might reveal a different error that was hidden before.

**Comment by yitaogo** [comment]
Very strange, I deleted lines 7-13, this is my error message.
![Screenshot 2023-12-23 175226](https://github.com/Acly/krita-ai-diffusion/assets/59963385/5b74aeec-5d74-4024-922a-430c3d99d345)
![1703325303_EJauzsyg](https://github.com/Acly/krita-ai-diffusion/assets/59963385/750567ed-353d-497a-9ffd-ef8d789a7772)

**Comment by Acly** [comment]
Indeed, if you delete the lines this should definitely not appear as error anymore.
Make sure you saved the file, and check you don't have two copies of the plugin somehow? I don't see how this is possible otherwise...

**Comment by yitaogo** [comment]
> Indeed, if you delete the lines this should definitely not appear as error anymore. Make sure you saved the file, and check you don't have two copies of the plugin somehow? I don't see how this is possible otherwise...

![Screenshot 2023-12-23 211115](https://github.com/Acly/krita-ai-diffusion/assets/59963385/54bbccbe-c13b-41fe-b54d-b49e734a4f0c)
I deleted lines 7-13, saved and restarted the computer, but the error is still the same.

**Comment by murphyyyyyyyyyy** [comment]
try this  【重磅更新！AI实时实时绘画插件  Krita+ComfyUI+LCM！ 完全开源免费本地部署！ 小白也能轻松使用，krea平替】https://www.bilibili.com/video/BV1G94y1J7ux?vd_source=f99bd62fc6eb8317c8d0f2fed71ca045

**Comment by yitaogo** [comment]
> try this 【重磅更新！AI实时实时绘画插件 Krita+ComfyUI+LCM！ 完全开源免费本地部署！ 小白也能轻松使用，krea平替】https://www.bilibili.com/video/BV1G94y1J7ux?vd_source=f99bd62fc6eb8317c8d0f2fed71ca045

区别在哪？

**Comment by murphyyyyyyyyyy** [comment]
> > try this 【重磅更新！AI实时实时绘画插件 Krita+ComfyUI+LCM！ 完全开源免费本地部署！ 小白也能轻松使用，krea平替】https://www.bilibili.com/video/BV1G94y1J7ux?vd_source=f99bd62fc6eb8317c8d0f2fed71ca045
> 
> 区别在哪？

傻瓜式操作，别人整合好了相关的资源

**Comment by yitaogo** [comment]
> > > try this 【重磅更新！AI实时实时绘画插件 Krita+ComfyUI+LCM！ 完全开源免费本地部署！ 小白也能轻松使用，krea平替】https://www.bilibili.com/video/BV1G94y1J7ux?vd_source=f99bd62fc6eb8317c8d0f2fed71ca045
> > 
> > 
> > 区别在哪？
> 
> 傻瓜式操作，别人整合好了相关的资源

我下的就是整个包，但是插件出问题了

**Comment by murphyyyyyyyyyy** [comment]
> > > > try this 【重磅更新！AI实时实时绘画插件 Krita+ComfyUI+LCM！ 完全开源免费本地部署！ 小白也能轻松使用，krea平替】https://www.bilibili.com/video/BV1G94y1J7ux?vd_source=f99bd62fc6eb8317c8d0f2fed71ca045
> > > 
> > > 
> > > 区别在哪？
> > 
> > 
> > 傻瓜式操作，别人整合好了相关的资源
> 
> 我下的就是整个包，但是插件出问题了

好吧，我跟着他来的，没什么问题

**Comment by molspace** [comment]
I encountered the same error and investigated into the websockets directory, which I found to be empty.
I solved the problem by copying the contents from a module zip file:[https://github.com/Acly/krita-ai-diffusion/releases/download/v1.17.2/krita_ai_diffusion-1.17.2.zip]( https://github.com/Acly/krita-ai-diffusion/releases/download/v1.17.2/krita_ai_diffusion-1.17.2.zip ) and replacing the files and folders in krita/pykrita directory. websockets directory is not empty in the given zip archive.
