### ISSUE TITLE
changing path of installation to drive e:

### ISSUE THREAD

**Issue by souvee** [Acly/krita-ai-diffusion#249]
as my c: drive has not enough capacity i installed all to e: drive
where i can adjust the correct path to e: and not to c: ?

I have this message
AssertionError
Python 3.10.7: D:\Program Files\Krita (x64)\bin\krita.exe
Tue Dec 19 15:12:35 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Admin\AppData\Roaming\krita\pykrita\ai_diffusion\ui\generation.py in apply_selected_result(self=<ai_diffusion.ui.generation.GenerationWidget object>)
  276 
  277     def apply_selected_result(self):
  278         self.model.apply_result()
  279 
  280     def apply_result(self, item: QListWidgetItem):
self = <ai_diffusion.ui.generation.GenerationWidget object>
self.model = <ai_diffusion.model.Model object>
self.model.apply_result = <bound method Model.apply_result of <ai_diffusion.model.Model object>>

 C:\Users\Admin\AppData\Roaming\krita\pykrita\ai_diffusion\model.py in apply_result(self=<ai_diffusion.model.Model object>)
  300 
  301     def apply_result(self):
  302         assert self._layer and self.can_apply_result
  303         self._layer.setLocked(False)
  304         self._layer.setName(self._layer.name().replace("[Preview]", "[Generated]"))
self = <ai_diffusion.model.Model object>
self._layer = None
self.can_apply_result = False
AssertionError: 
    __cause__ = None
    __class__ = <class 'AssertionError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AssertionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AssertionError object>
    __doc__ = 'Assertion failed.'
    __eq__ = <method-wrapper '__eq__' of AssertionError object>
    __format__ = <built-in method __format__ of AssertionError object>
    __ge__ = <method-wrapper '__ge__' of AssertionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AssertionError object>
    __gt__ = <method-wrapper '__gt__' of AssertionError object>
    __hash__ = <method-wrapper '__hash__' of AssertionError object>
    __init__ = <method-wrapper '__init__' of AssertionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AssertionError object>
    __lt__ = <method-wrapper '__lt__' of AssertionError object>
    __ne__ = <method-wrapper '__ne__' of AssertionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AssertionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AssertionError object>
    __repr__ = <method-wrapper '__repr__' of AssertionError object>
    __setattr__ = <method-wrapper '__setattr__' of AssertionError object>
    __setstate__ = <built-in method __setstate__ of AssertionError object>
    __sizeof__ = <built-in method __sizeof__ of AssertionError object>
    __str__ = <method-wrapper '__str__' of AssertionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ()
    with_traceback = <built-in method with_traceback of AssertionError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\krita\pykrita\ai_diffusion\ui\generation.py", line 278, in apply_selected_result
    self.model.apply_result()
  File "C:\Users\Admin\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 302, in apply_result
    assert self._layer and self.can_apply_result
AssertionError

**Comment by Acly** [comment]
> as my c: drive has not enough capacity i installed all to e: drive

By all, you mean the server? The plugin itself seems to be on C: (but it's very small anyway). There is no problem with the server being on E:

The error doesn't look related. I can't say directly what caused it. What did you do exactly before getting this error?
