### ISSUE TITLE
LORA PATH ISSUE

### ISSUE THREAD

**Issue by daizhuo** [Acly/krita-ai-diffusion#252]
ERror: LCM LoRA model not found for SD 1.5

I use mklink to share model betwen comfyui and webui.
But it keep showing this error.
Could you fix this minor bug for our convenience? 
Thank you so much for this great tool!

mklink /D D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\models D:\AI\stable-diffusion-webui-1.1.0\models

**Comment by Acly** [comment]
Linking the entire model folder won't work. [See here](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#how-do-i-share-models-between-another-ui-and-comfyui) on how to share model files in ComfyUI.
