### ISSUE TITLE
How to Add SDXL in Cloud GPU

### ISSUE THREAD

**Issue by raniaamina** [Acly/krita-ai-diffusion#254]
Hi, thanks for providing this plugin.

I've test it both locally and with cloud GPU, it seem the image in for cloud GPU (i use Runpod instance) doesn't include SDXL, am i missing something? Or is there any way to add it, i'll love to try.

Thanks!

**Comment by Acly** [comment]
Hi, SDXL is part of the base image, so you should be able to use it directly.
Which version of the image did you use? The latest is aclysia/sd-comfyui-krita:v1.10.0
If it doesn't work with that take a look at client.log file after connecting, it should list why SDXL isn't supported. Let me know what it says.

**Comment by raniaamina** [comment]
Ah, my mistake, sorry I wasn't careful before. You're right, it seems like everything I'm confused about is just the text editing.

Btw, I tried to fully install all the elements locally and it required around 25GB of space, it looks like the minimum storage information also needs to be updated.

Thanks!

**Comment by Acly** [comment]
Minimum storage refers to installing only the required parts for SD1.5, without ticking all the (optional) extra checkboxes.
