### ISSUE TITLE
Darkening effect at lower guidance levels (underexposed result)

### ISSUE THREAD

**Issue by althor8** [Acly/krita-ai-diffusion#255]
Hi, first of all, great work, amazing plugin, love it!!

Experiencing however a minor issue on my setup, the live diffusion result coming out darker then what is drawn on the canvas.
Tried different VAE in control panel (Configure Image Diffusion Krita/Style Presets) but problem persist.  

It mostly becomes apparent with lower guidance levels, like something of 35% (a guidance level sweet spot for me). When pushing the slider gradually more towards 100% the darkening problem goo's away but then diffusion result does not follow what I’m painting at all, (basically getting some random image).

Any solutions to stop the darkening effect at lower guidance levels?

**Comment by Acly** [comment]
How much darkening are we talking about here? Just to get an impression.

Generally diffusion is allowed to change the brightness of the image, and in most cases it's something you want it capable of doing. Unfortunately most models are biased towards images of "average" brightness (across all pixels). So in particular if your image is very bright (lots of white maybe) it can lead to darkening, the reverse would also be true.

**Comment by ThomazAbramo** [comment]
I have the same issue and found a solution, which is to create or paint a background layer with 50% gray (or adjust the brightness until achieving the desired effect). I'm not exactly sure why this resolves it, but it works.

**Comment by althor8** [comment]
Turns out it has something to do with the default color profile (icc) set in Krita. 
In menu image/convert image color space (in Krita) there’s an option to set a profile that matches your monitor. 

My monitor has its own icc and after selecting it the darkening effect was gone.

The effect is probably more pronounced on my setup because it involves a wide gamut monitor and it appears to use different gamma curve compensating for larger brightness levels. The default icc from Krita appears to use a linear gamma curve that made mid-range brightness levels appear to dark on my monitor.

For people using regular monitor the sRGB IEC61966-2.1.icc will probably give best result.
