### ISSUE TITLE
Action Button

### ISSUE THREAD

**Issue by Dervlex** [Acly/krita-ai-diffusion#257]
Sorry for writing an issue. 
I dont really know how to contact you on a different way :D 

But would it be possible to create an "auto" apply check button ?

**Comment by Acly** [comment]
You can double-click thumbnails to apply immediately instead of preview. Or do you have something different in mind?

**Comment by Dervlex** [comment]
Thx for answering so fast! I mean an option, where i dont have to press anything anymore.
As example, in the moment i queue two images, which both overlap one part of the img, the second render doesnt rerender the already rendered part of the first one, because it wasnt applied.

If there would be an option, i could queue multiply at ones and would get an already upscaled img automatically.

**Comment by Acly** [comment]
You want to chain individual generations so to speak?
I admit I usually don't have such blind trust in the generated results, so I can't quite see yet where this would be useful.
It's also not that easy to implement, currently things are queued the moment you click generate. Chaining would require a separate queue that works differently.
