### ISSUE TITLE
[Feature Request] Implement StreamDiffusion for better real-time generation.

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#258]
[StreamDiffusion](https://github.com/cumulo-autumn/StreamDiffusion)

**Comment by Acly** [comment]
It looks impressive, but it's essentially a completely different backend with limited feature support that only works for small subset of users who have the recent NVIDIA GPUs on Linux only. It's possible to hack it in as limited replacement specifically for live mode, but maintaining it including automatic deployment would be a huge effort.

It would make more sense as a cloud solution perhaps.
