### ISSUE TITLE
Save last used prompt to .kra file

### ISSUE THREAD

**Issue by JukePlz** [Acly/krita-ai-diffusion#262]
I find myself having to dump prompts into text files along with my work files, I think it would be a good idea to have a (optional) setting that saves and restores the last used prompt from an image directly into the .kra file.

This would make it much easier to go back to older work, and prevent mistake where the prompt wasn't saved before exiting the program.

**Comment by Acly** [comment]
I've been working on that, but it still has some bugs, so didn't make it into release today.

There is already #232, #110 with similar requests, so I'm closing this to not have too many open issues.
