### ISSUE TITLE
How to use embeddings

### ISSUE THREAD

**Issue by Dartterious** [Acly/krita-ai-diffusion#263]
It's not clear how to get embeddings to work, have I missed something or is there a special command or setting I need to use to get them to work correctly?

Sorry this is less an issue and more a dumb query but there doesn't appear to be a discussion forum here. 

Thanks!

**Comment by Acly** [comment]
yea it's not exactly obvious. No problem to open issues for questions, though this was asked before in #176, so search shouldve found it. I think the GitHub search bar looks only in "open" issues by default though which is not ideal...
