### ISSUE TITLE
suggestion about 1.11

### ISSUE THREAD

**Issue by spirobel** [Acly/krita-ai-diffusion#265]
Hi @Acly 

I just read the latest release note and I saw this:
>it's really easy to forget it's only a preview and still has to be applied! 

Something I recognized myself doing is: apply, save and export as jpg, then undo and apply a different result and repeat the same.

It would be nice if there was an apply and export as jpg button that turned this into one step.

Either way! Thank you for your great work! This plugin is so amazing and I still can not believe how much it improves the workflow compared to all the other stable diffusion tools out there. ( put differently: it really unlocks the potential of comfyUI)

**Comment by Acly** [comment]
Added option to save image to preview thumbnail context menu in [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0)
