### ISSUE TITLE
Missing SD 1.5 workflow even with all the models installed. 

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#267]
![Capture](https://github.com/Acly/krita-ai-diffusion/assets/63921540/dac422d9-2fc6-40ef-b3a4-5aa0584f8411)
It's been like this since I updated ComfyUI nightly along with its prerequisites and custom nodes to their latest version.

Only SDXL workflows work, SD 1.5 is missing "Stable Diffusion Checkpoint" even though I've got the same sd 1.5 based checkpoints in the same directory as usual.

**Comment by Acly** [comment]
I thought maybe ComfyUI update broke the checkpoint base model detection somehow, but at least for me it's still working with latest version.
Can you check the output of http://127.0.0.1:8188/etn/model_info 
Are your checkpoints listed? And is the base model detected correctly ("sd15" if it's SD1.5 checkpoint)?

**Comment by vidiotgameboss** [comment]
> I thought maybe ComfyUI update broke the checkpoint base model detection somehow, but at least for me it's still working with latest version. Can you check the output of http://127.0.0.1:8188/etn/model_info Are your checkpoints listed? And is the base model detected correctly ("sd15" if it's SD1.5 checkpoint)?

yes every model is listed there in etn/model_info but as base_model: "stab"

**Comment by Acly** [comment]
Okay, but the issue is that SD1.5 checkpoints are detected as "stab" for some reason.
You said you updated ComfyUI and custom nodes, but what are the exact versions of ComfyUI and [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes) you are using? 
I have both on latest (Comfy: a252963f956a7d76344e3f0ce24b1047480a25af, comfyui-tooling-nodes: b2496a3f132f8c3f7d452a0960c422f55c33d128) and can't reproduce this...

**Comment by vidiotgameboss** [comment]
> Okay, but the issue is that SD1.5 checkpoints are detected as "stab" for some reason. You said you updated ComfyUI and custom nodes, but what are the exact versions of ComfyUI and [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes) you are using? I have both on latest (Comfy: a252963f956a7d76344e3f0ce24b1047480a25af, comfyui-tooling-nodes: b2496a3f132f8c3f7d452a0960c422f55c33d128) and can't reproduce this...

ive pulled everything to the latest commit again just now, i tend to do this every couple of days/a week, its still detecting sd 1.5 as "stab", could it be a python dependency issue?

**Comment by Acly** [comment]
No, my guess is still that comfyui-tooling-nodes is outdated (for some reason).

Reason: previous versions just used the first 4 letters lower case of comfy's name for a base model. Recently comfy added support for `Stable_Zero123` base model, and your SD1.5 checkpoints are probably being misdetected as that.

But I just don't see how the current code would ever return "stab", even if the detection didn't work. It no longer does the first-4-letters thing...

**Comment by vidiotgameboss** [comment]
> No, my guess is still that comfyui-tooling-nodes is outdated (for some reason dispite your pull).
> 
> Reason: previous versions just used the first 4 letters lower case of comfy's name for a base model. Recently comfy added support for `Stable_Zero123` base model, and your SD1.5 checkpoints are probably being misdetected as that.
> 
> But I just don't see how the current code would ever return "stab", even if the detection didn't work. It no longer does the first-4-letters thing...

ive deleted comfyui-tooling-nodes and manually downloaded instead of pulling or cloning it, now it works, bases_model detects as sd15

thanks
