### ISSUE TITLE
the checkpoints can't refresh

### ISSUE THREAD

**Issue by mianayo** [Acly/krita-ai-diffusion#268]
Hey everyone, quick question: why aren't my checkpoints refreshing? Got a bunch in my comfyui folder, they work fine in comfyui, but no luck in the plugin. Refresh button's a no-go. Loras loads just fine. Main thing is, they all loaded fine when I first set up the plugin. What gives?

**Comment by Acly** [comment]
Sounds similar to #267 - is this a custom comfy install?
Also same question, can you check http://127.0.0.1:8188/etn/model_info
Are missing checkpoints listed there? Does base model look correct?

**Comment by mianayo** [comment]
Wow,fixed it! thanks you!
