### ISSUE TITLE
External server won't connect

### ISSUE THREAD

**Issue by wender1** [Acly/krita-ai-diffusion#269]
After installing the Krita AI Diffusion 1.11 the external server, even being active won't connect. Changing the plugin back to the previous version it connects perfectly.

**Comment by attyru** [comment]
fix line 150 in the client.py file in any text editor as shown in the picture. It worked for me.
<img width="650" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/76990611/06e7bae5-ad4f-48e1-937e-70fcc213d007">

**Comment by Acly** [comment]
I patched the release so v1.11.1 doesn't have that issue anymore

**Comment by wender1** [comment]
Now it works perfectly!!! Thank you very much Acly and attyru. You are awesome!!!
