### ISSUE TITLE
ControlNet folder

### ISSUE THREAD

**Issue by Drakosha405** [Acly/krita-ai-diffusion#27]
Hi, tnx you for this amazing addon

Is it possible to add a more ordered structure of the layout of models for controlnet like "models\controlnet\krita_ai" or something similar.

most of the models have almost identical names(if used sd15\sdxl). and it is not very convenient to look at each character (when deleting or transferring from folder to folder or when selecting)

best may is like this I think
model/controlnet/sd15
model/controlnet/sdxl
model/controlnet/krita_ai

What do you think about this?

PS yes duplicates of models are possible, but it will be much easier to navigate when working with them

**Comment by Acly** [comment]
The naming isn't great, but I'd rather keep the filenames as they were initially named by their author or can be commonly found on the internet. This is by far the most likely to work for everyone out of the box. Creating another naming scheme that nobody uses won't help I think.

It would be possible to have an additional search path that uses some prefix, and this might work for your suggestion. Just to be clear, your use case is running one Comfy server and using it via WebUI and Plugin at the same time, and you find it hard to pick control net in the WebUI with the original filenames?

**Comment by Drakosha405** [comment]
yes, you're right, I often run one server for krita and webui. and quite a few models for controlnet(sd15 and sdxl). it's much easier when the models for each version are in their own folders and there is no need to look for the cherished sd15 or xl in the middle of the names. Adding the search for the necessary files in subfolders to the addon will make it possible to preserve the intuitive structure of the file location

**Comment by Acly** [comment]
Latest release (1.4.0) should search for filenames now and ignore folders in the path!
