### ISSUE TITLE
Using a  URL, Krita AI is unable to update and display generated images.

### ISSUE THREAD

**Issue by mianayo** [Acly/krita-ai-diffusion#270]
Hey, I want to use it in the office. I tried using --listen with ComfyUI, then generated a URL using ngrok. I tested it and found that Krita AI can connect successfully, and I can see the progress bar. However, the generated images cannot be displayed in Krita. Can you please help me solve this issue?

**Comment by Acly** [comment]
Result images are transferred via websocket connection, maybe something is blocking it? It's a common issue on mac due to certificate issues (https://github.com/Acly/krita-ai-diffusion/issues/74#issuecomment-1819993842) for example. It was a while ago, but setup similar to yours used to work: #22

**Comment by mianayo** [comment]
> 结果图像是通过 websocket 连接传输的，也许有什么东西阻止了它？例如，由于证书问题（[#74（评论）），这是 Mac 上的一个常见问题。这](https://github.com/Acly/krita-ai-diffusion/issues/74#issuecomment-1819993842)是不久前的事情了，但与你类似的设置曾经有效：#22

Oh my, thank you so much, thank you for solving two of my problems consecutively - quick and effective. Thanks again! By the way, where are the images generated by Krita saved by default? I can't find them in my comfyui folder.

**Comment by Acly** [comment]
> where are the images generated by Krita saved by default?

They are not saved. See #181, #177 for reasoning. Upcoming version will persist them in your document to some extent (#232).
