### ISSUE TITLE
Colors not updated after theme change

### ISSUE THREAD

**Issue by vtvrv** [Acly/krita-ai-diffusion#273]
History widget's custom css is not updated after a theme change
https://github.com/Acly/krita-ai-diffusion/blob/3c3bd77089b83b9a2c2515a1e23e642f65fc4388/ai_diffusion/ui/generation.py#L45C1-L55C8

Also with the TextPromptWidget's _base_color 
https://github.com/Acly/krita-ai-diffusion/blob/3c3bd77089b83b9a2c2515a1e23e642f65fc4388/ai_diffusion/ui/widget.py#L487

![themeerror](https://github.com/Acly/krita-ai-diffusion/assets/98350357/958bed21-50b2-40bc-bfd0-a26fbf5c8122)

removing the custom theming fixed the issue.

**Comment by Acly** [comment]
There are a lot of other dark/light differences though, and all the icons have separate versions too. I don't plan to fix this, quite a lot of work for very little gain. A restart after theme change is not ideal but acceptable imo.
