### ISSUE TITLE
Version 1.10+ no longer finds checkpoints in custom install folder.

### ISSUE THREAD

**Issue by brainhaver** [Acly/krita-ai-diffusion#276]
Error: _The checkpoint used by this style is not installed_.

My ComfyUI install is a Windows portable version with custom .yaml paths. It had been working flawlessly with the plugin until 1.10/11.
Updating caused missing Python errors likely caused by ComfyUI's portable version Python folder being called _python embeded_, while the Krita plugin searches for _python_ instead. Although this had been working and is unrelated.

Now it can only detect SDXL models and no 1.5 models. If I remove the custom checkpoint path from the .yaml file it no longer detects any checkpoints at all. Every other folder path in the .yaml (LoRAs, etc.) is detected except for checkpoints. ComfyUI itself can read the checkpoint folder.

**Comment by Acly** [comment]
> Updating caused missing Python errors

That was intentional, the comfy-managed-by-plugin option isn't meant to manage a custom install (bad things can happen, use at your own risk)

> Error: The checkpoint used by this style is not installed.

Maybe the same as #267, make sure you have the latest version of [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes)

**Comment by brainhaver** [comment]
Just as you responded I saw that someone had brought this issue up before, oops!
The files in the link you posted fixed the problem.
