### ISSUE TITLE
A way to use External Drives for Checkponts etc...

### ISSUE THREAD

**Issue by macsen0** [Acly/krita-ai-diffusion#277]
Since the models tend to be huge, I download everything to an external SDD, and I've been using “Draw Things” this way.
This plugin lets me do even bigger images and I like it, but I cannot, in any way, move the checkpoints I've downloaded to my main SDD.

Any way to make the plugin look also in a new folder, or change the whole thing to that new folder in the SDD? I think this would be useful for many people.

I'm using a Mac.

**Comment by Acly** [comment]
[How do I relocate my server installation?](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/common-issues.md#how-to-share-models-from-another-folder-with-krita-ai-diffusion-plugin)
[How to share models from another folder with Krita AI Diffusion plugin?](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/common-issues.md#how-to-share-models-from-another-folder-with-krita-ai-diffusion-plugin)
