### ISSUE TITLE
[ improvement ] Apply button to be not overlayed

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#278]
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/873d7889-da9c-4df7-abeb-66edaed1bcdf)

So, every time it generates a wide and short fragments, 'Apply' button completely overlays on top of the generated option, making it hard to even click on the option without hitting the button. Would be nice to have the button stick under the generated option (or to have it separated, as was in 1.10 )

**Comment by Acly** [comment]
Thumbnail is not supposed to be this tiny, looks like it isn't scaled with display scale...

**Comment by Acly** [comment]
Should no longer happen in [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0)

**Comment by Acly** [comment]
I didn't remove the overlay in general, rather:
1. fixed the thumbnails not taking windows display scale into account
2. added extra room for the button **if** there is not enough, like in your initial screenshot (very wide image)

In your new screenshot there is space to click thumbnail anyway, BUT, it still looks too small. The thumbnail should be bigger (and then the text would fit too and the button would use up way less space).

Not sure why the screen DPI fix isn't working. Assuming it is windows (I think I asked before somewhere). Something to do with Windows version or how your display scaling is setup?

**Comment by Pirog17000** [comment]
yes, it is windows,

In Windows itself the scaling is set to 100%
In Krita:

![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/02422bca-ac3b-4db0-9ca0-35e8f3ae9c72)
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/2eb85b18-58f0-40df-9e94-f7af6024d09a)

**Comment by Acly** [comment]
Oh I see, the custom font size is what makes the thumbnail appear small in comparison to the font. But I guess that's intended then.

I can maybe take it into account, but no promises.
