### ISSUE TITLE
chkpt and lora instructions

### ISSUE THREAD

**Issue by SD-NinoPriore** [Acly/krita-ai-diffusion#280]
Many checkpoint models and loras come with instructions and specific descriptions and recommendations on how to use them. But there is no way to save that information along with these models when using them with this plugin, which means we have to go to civitai to look up the model or lora each time we want to use it. In the style presets window, it would be helpful if there was a text box or pulldown where we could paste those instructions and they would be saved and available to view whenever the specific model is selected (the instructions would have to be associated independently with the model or lora).

**Comment by Acly** [comment]
The idea is that in a style you can store all this information ready to be used, rather than as separate text.

For mixing large number of Lora it could make sense.

**Comment by Acly** [comment]
Lora-specific triggers and strength are in [v1.23.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.23.0)
