### ISSUE TITLE
.ckpt model unrecognizable.

### ISSUE THREAD

**Issue by xinyimin** [Acly/krita-ai-diffusion#284]
I want to add a.ckpt model, but I can't find it in the style presets surface version model checkpoint
![屏幕截图 2023-12-28 114738](https://github.com/Acly/krita-ai-diffusion/assets/33536064/028aad65-15fc-497c-b2e3-865d0dd46688)
![屏幕截图 2023-12-28 114707](https://github.com/Acly/krita-ai-diffusion/assets/33536064/359b0f8b-7a66-4a6e-b2a9-1f70f1f7be5c)

**Comment by Acly** [comment]
Yes, it must be .safetensors format to be recognized. The .ckpt format is old, unsafe, and harder to detect model type.

**Comment by yasavvym8** [comment]
Would you happen to be aware of a way to allowe ckpt files in my own installation? Most of my checkpoints are ckpt unfortunately, and I’m not sure how to convert them to safetensors.

**Comment by yasavvym8** [comment]
ahh okay thank you for the response! that that's it. converting them was very convenient! thank you again for your help And I very much appreciate all of the work that goes into maintaining this repository. it is very appreciated!

**Comment by nesmonmehdydeal** [comment]
Thanks
