### ISSUE TITLE
17 minutes to do a generative fill or use the ai generative

### ISSUE THREAD

**Issue by Navidos1** [Acly/krita-ai-diffusion#286]
I hope i am on the right forum. Because reddit krita suspended my thread about this issue. Seems like people hate this ai plugin.

I have installed the krita ai 1.11.0 on  my computer and installed correctly. My computer is  a 
Ryzen 7 2700x with 
Sapphire Radeon RX 570 Pulse - 8GB GDDR5 RAM . 
Corsair Vengeance LPX DDR4-3200 C16 BK DC - 16GB
MSI B450 GAMING PRO CARBON AC 

All bought in 2019.

Everything is green highligted in my installation. Meaning that i have installed everything. And the server connects fine. 

However..for every time i want to use it it uses enormous with time. For example if i want to expand the right side of a picture then it takes aroundt 17 minutes. It doesnt matter if i try gpu or cpu or whatever settings. 

I have tried different resolutions..from 8000px and downsized the image to 1024 to see if it goes faster. It doesnt matter. 

From the dropdown list on the front end i use "1.5 digital artwork". I only have "Cinematic photo" and Cinematic photo xl" and Digital artwork xl" from the dropdown list. I dont know if i am supposed to use something else?

If start Krita and go to the settings for the Krita and choose "Use directML(gpu)" then it gives me this error:
https://ibb.co/QNy38bk

The server only starts on  "Run CPU".

Going for the live option doesnt work. When ever i try it it stops at 12 % and after a while it gives this error:
https://ibb.co/ThMhpBB

The performance setttings are like these:
https://ibb.co/wBqB1CM

Okey..i know it requires a strong hardware to do Krita.but come on..is my system really that weak? Is it my  graphic card? it has 8gb even though the minimum is 6gb on the requirements. have also the same problems on my

I really hope to get some help here..love this plugin but it just really doesnt work.

**Comment by Acly** [comment]
Start with a 1.5 style (doesn't matter which) and plain 100% strength generation without selection at 512x512, you can go more complex from there.

That being said, CPU is very slow whatever you do, so try to use the GPU via DirectML. Regarding the error you get, it sounds like you didn't have DirectML option selected when you installed?

If that's the issue, you can either delete and reinstall the server (easy but takes long).
Or try to only install the DirectML package: open a command prompt and run
```
SERVERPATH\python\python -m pip install torch-directml
```
(replace SERVERPATH with the server path from the installer)

**Comment by Navidos1** [comment]
> Start with a 1.5 style (doesn't matter which) and plain 100% strength generation without selection at 512x512, you can go more complex from there.
> 
> That being said, CPU is very slow whatever you do, so try to use the GPU via DirectML. Regarding the error you get, it sounds like you didn't have DirectML option selected when you installed?
> 
> If that's the issue, you can either delete and reinstall the server (easy but takes long). Or try to only install the DirectML package: open a command prompt and run
> 
> ```
> SERVERPATH\python\python -m pip install torch-directml
> ```
> 
> (replace SERVERPATH with the server path from the installer)

Thanks a lot for your response. I use windows 11
You mean just go to "Run", type cmd and then:
C:\Users\myUsername\AppData\Roaming\krita\pykrita\ai_diffusion\python\python -m pip install torch-directml

If i rather try to install the ai plugin again. Do i just need to delete everything in the:
C:\Users\myUsername\AppData\Roaming\krita\pykrita\ai_diffusion\.server

And then just install again?

**Comment by Acly** [comment]
> You mean just go to "Run", type cmd and then:

Yep.

> Do i just need to delete everything in the:

Yep. You can back up the ComfyUI/models folder if you want, it has all the large files. No need to tick all the boxes when you reinstall, just copy the old folder in afterwards.
