### ISSUE TITLE
Select one area then generate will leads to error

### ISSUE THREAD

**Issue by gabrie** [Acly/krita-ai-diffusion#287]
size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 768]).

Always, I'm on mac

**Comment by Acly** [comment]
Is it a custom comfy install? Full error from server log? Might be the wrong clip vision model

**Comment by gabrie** [comment]
It's a custom comfy install. 

Log below


got prompt
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load CLIPVisionModelProjection
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/gabrie/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/gabrie/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/gabrie/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/gabrie/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 539, in apply_ipadapter
    self.ipadapter = IPAdapter(
  File "/Users/gabrie/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 213, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "/Users/gabrie/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
	size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 768]).

It seems like you mentioned clip vision model issue. I have 2 installed, which one else is needed?
![Snipaste_2023-12-31_20-17-59](https://github.com/Acly/krita-ai-diffusion/assets/539991/f6aa1490-3bae-4752-b08a-157cebc9f8a5)

**Comment by Acly** [comment]
I think the bottom one "SD1.5 ClipVision model (IP-Adapter)" should work. And it's expected in folder "models/clip_vision/SD1.5", last I checked that's also where ComfyUI manager places it.

**Comment by gabrie** [comment]
> I think the bottom one "SD1.5 ClipVision model (IP-Adapter)" should work. And it's expected in folder "models/clip_vision/SD1.5", last I checked that's also where ComfyUI manager places it.

Thanks, and I installed all 4 then, but still same issue.

**Comment by Acly** [comment]
Well, the issue is probably that the wrong one was selected, installing more is not going to solve it. It's easy to get them mixed up because they all have the same filename.
You could try to remove (or backup) the existing files in models/clip_vision and follow the [instructions here](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md#required-models).
