### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by jucyla** [Acly/krita-ai-diffusion#288]
Hi,

i've an issue when i launch the server : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/37240648/17704daa-8be8-43d8-a6ea-5640a26162f3)

i join logs  files 

[client.log](https://github.com/Acly/krita-ai-diffusion/files/13797207/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13797208/server.log)

thanks for your help :)

**Comment by Acly** [comment]
The last part of the error message is the important one: "Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver"
