### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by stefaniadiez** [Acly/krita-ai-diffusion#29]
![Screenshot_14](https://github.com/Acly/krita-ai-diffusion/assets/148573215/0c1a64d4-8349-419e-a18c-58434941359a)

**Comment by Acly** [comment]
Hm, this might indicate that something took very long rather than straight up failure, but I haven't run into it yet.

Please share the client.log contents (you can find the file via "View log files") to get a clearer picture.

**Comment by Drakosha405** [comment]
Hi.
1. Why u try install comfyui in krita folder in app data?
2.  why in path .server?

**Comment by Acly** [comment]
Those are the defaults. I mainly chose them so it's easy to relocate and remove the plugin (including comfy, python, etc). You're free to install to a different location of course, but it shouldn't matter (assuming you have enough disk space).
