### ISSUE TITLE
[Feature Request] Display the strength % used to generate the previews in the preview area

### ISSUE THREAD

**Issue by pdelongchamp** [Acly/krita-ai-diffusion#290]
When I'm generating previews to replace a selection, I'll often queue multiple generations at different Strength percentages until i find a good %, then I keep queuing generations at the good %. For example, I'll queue 3 generations where I increase the strength by 5% for each queued generation. 

Currently, when I see previews with a good %, there's no way for me to tell which percentage I used. e.g. Was it 20% or 25%? Currently, I try to only queue 3 generations so that I can better keep track. 

I would like to see the % so that I can reuse the good % and keep queueing generations. 

Possible implementations:
- Group previews not only by prompt changes but also by strength % changes.
- Select a preview and click something to "reuse" it's generation parameters
- In the Preview tooltip, display the Strength % along with the prompt.

**Comment by Acly** [comment]
Done in [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0)
