### ISSUE TITLE
[Feature Request] Preview generations without the animated selection border

### ISSUE THREAD

**Issue by pdelongchamp** [Acly/krita-ai-diffusion#291]
When I'm previewing multiple generations to replace an area of the images, it can be challenging to get a proper sense of what the image will look like when it's applied due to the animated "marching ants" selection border in the image. I'll sometimes select "Deselect" in Krita so that I can properly preview the generations then reply the selection using "Undo" to continue generating more previews.

There might already be a better method of doing this that I'm not aware of.

**Comment by Acly** [comment]
Here is how I do it:
First, enable global selection mask in Krita menu bar: Select ‣ Show Global Selection Mask
Now Krita will auto-insert a layer when you select something and remove that layer when you deselect.
Use the ◌ button on the layer to toggle the selection with a single click. Very useful to keep multiple selections at hand too.
