### ISSUE TITLE
Meta data Incomplete Buffer

### ISSUE THREAD

**Issue by DuVogel87** [Acly/krita-ai-diffusion#292]
Hello.

When I select the SDXL-Turbo 1.0 fp16 model checkpoint in the style presets i get the error:

server execution error: error while deserializing header: metadataincompletebuffer (screenshot attached)

how can i fix this?

greetings

![krita error](https://github.com/Acly/krita-ai-diffusion/assets/123517103/9a11a9ab-304c-4e9b-b3ee-4163deeb66d8)

**Comment by Acly** [comment]
The server.log should have a more detailed error message, but it sounds like the file is corrupt. Try re-downloading.

Note: currently SDXL Turbo is usable but will generate at the wrong internal resolution. Next release will include an option to set that manually. See also https://github.com/Acly/krita-ai-diffusion/issues/155#issuecomment-1836835263
