### ISSUE TITLE
IDEA: EbSynth for Krita

### ISSUE THREAD

**Issue by b4zz4** [Acly/krita-ai-diffusion#296]
Taking a layer or frame by reference, can create another using ebsynth

https://github.com/jamriska/ebsynth

**Comment by Acly** [comment]
Sounds like it could be useful, but I don't see much overlap with this plugin? Probably easier to create a separate plugin and be free of a lot of dependencies (and the "stain of gen AI").

**Comment by b4zz4** [comment]
Yeah, separate would be better. Although they could work together to create similar cartoon sequence for example for animation

**Comment by b4zz4** [comment]
My idea is similar https://ebsynth.com/app
