### ISSUE TITLE
amazing progressive blend rather than the traditional Gaussian blend.

### ISSUE THREAD

**Issue by onefish51** [Acly/krita-ai-diffusion#298]
Your work is truly remarkable! It's fantastic! 

I've noticed that when blending the generated result with the original image, you've used a progressive alpha that increases from 0 to 255, rather than the traditional Gaussian blend. 
![mask2](https://github.com/Acly/krita-ai-diffusion/assets/21029719/8428ad5b-b257-47ef-b2b4-6a6baac79c2c)

This is a wonderful idea, and the results are impressive and highly effective! I believe this method is versatile and can be applied to many image blending scenarios.

 I've noticed that your code relies heavily on Qt dependencies, and I'd like to replicate this using cv2 or Pillow. Could you provide some guidance? Thank you!

**Comment by Acly** [comment]
Although I'd like to claim such ingenuity, there is nothing magic going on here. Images are blended using regular alpha blending according to user selections. Selection masks may be blurred at the borders. Or do you mean something else?

**Comment by onefish51** [comment]
I have conducted some tests to compare several commonly used image fusion methods: 
fg
![d9f](https://github.com/Acly/krita-ai-diffusion/assets/21029719/2dddbe0b-5634-4f4d-a514-abe218405ff4)

 bg
![blue_img2](https://github.com/Acly/krita-ai-diffusion/assets/21029719/34e054d3-edc2-4d3b-9cce-83f8bb6767ce)

 alpha
![blue_mask2](https://github.com/Acly/krita-ai-diffusion/assets/21029719/bd1f1434-47a5-4efb-b34a-cd51f9db40c3)

Group 1: Direct blending（Directly blend the images using the formula` fg * alpha + bg * (1-alpha)`. ）
output:
![comp](https://github.com/Acly/krita-ai-diffusion/assets/21029719/37fbd3f9-7b65-49f2-8b3f-62475001090d)

Group 2: Gaussian fusion
output:
![comp2](https://github.com/Acly/krita-ai-diffusion/assets/21029719/d2f88539-2ab3-4bf9-a617-de446b89d469)

Group 3: Poisson fusion
output:
![comp3](https://github.com/Acly/krita-ai-diffusion/assets/21029719/f439813f-97b5-4741-a587-273ee07bbdc4)


Group 4: Your progressive fusion method.

I used the method you provided to generate the progressive alpha , and then blended the foreground (fg) and background (bg) using the following formula:  ` fg * progressive_alpha + bg*(1-progressive_alpha)`

result = fg * progressive_alpha + bg * (1 - progressive_alpha)
progressive_alpha:
![blue_img2_mask](https://github.com/Acly/krita-ai-diffusion/assets/21029719/e9a06108-a36d-4d8d-8dda-bc87b0577292)
output:
![comp4](https://github.com/Acly/krita-ai-diffusion/assets/21029719/30b52fb6-ed74-4fbe-834b-f3cd8f5acf6a)

As you can see, the fusion method utilizing your technique to process the original alpha and generate progressive alpha (progressive_alpha) yields excellent results !!!

**Comment by Acly** [comment]
> I used the method you provided to generate the progressive alpha

Okay still not sure which method exactly, but for selections there is a "grow" and "feather" which is applied by default. You can reproduce this with Grow/Feather operations in Krita (from Selection menu). As to what it does, grow expands/dilates the mask, and feather applies a blur (I suspect gaussian blur). Size of both grow/feather is 7% of mask bounding box by default.

I can't tell exactl details either, you'd have to dig it up in Krita's source. But don't think you have to go that far to replicate this, those operations should be common enough.

**Comment by onefish51** [comment]
The key to my progressive fusion method is to expand the original alpha into non-alpha regions, generating a new progressive alpha with progressively decreasing pixel values by 1.
original alpha for outpainting：
![alpha_inv](https://github.com/Acly/krita-ai-diffusion/assets/21029719/26327234-7a76-4e1e-b686-602289ff3a4b)
progressive alpha :
![blue_img2_mask](https://github.com/Acly/krita-ai-diffusion/assets/21029719/ff64dd2f-8da9-455a-a381-c9b9d7b324d7)
pixel values decreasing in progressive alpha :
![image](https://github.com/Acly/krita-ai-diffusion/assets/21029719/673c1eec-8c41-4728-b851-42a85a7928ca)

**Comment by onefish51** [comment]
I can reproduce the method by iteratively traversing non-255 pixels, but I find it less elegant and less efficient. Additionally, the handling of overlapping boundaries is not as good as yours. Therefore, I would like to seek your advice on how to achieve this using simple `numpy` operations.

**Comment by Acly** [comment]
Yea use a gaussian filter instead. Can probably do it with `np.convolve` and the appropriate kernel, but I'm sure this is also implemented as convenience function somewhere already.

**Comment by onefish51** [comment]
I tried applying a large Gaussian kernel to blur the original alpha, but the results were not satisfactory. There are two main reasons for this. 
Firstly, the blurred alpha generated is still relatively discrete between pixels, for example, 20, 17, 13... 
Secondly, the blurred alpha alters the alpha values corresponding to the foreground image, causing them to decrease from 255.
original alpha：
![alpha_inv](https://github.com/Acly/krita-ai-diffusion/assets/21029719/2085394d-628f-4d9d-adbd-a023e8368f4c)

 the blurred alpha `alpha = cv2.GaussianBlur(alpha, (255, 255), 0)`：
![alpha_inv2](https://github.com/Acly/krita-ai-diffusion/assets/21029719/adde2e42-ffde-429a-8ae7-069fee7c18e4)
output：
![comp4](https://github.com/Acly/krita-ai-diffusion/assets/21029719/aacc29e9-12d0-4928-b57e-5a61fe33aeee)

**Comment by onefish51** [comment]
I forget `np.convolve`, I test 
```python

import cv2
import numpy as np

fg_dir = 'fg.png'
bg_dir = 'bg2.png'
mask_dir = 'mask2.png'
save_dir = 'comp4.png'
save_dir2 = 'alpha_inv2.png'

fg = cv2.imread(fg_dir, 1)
bg = cv2.imread(bg_dir, 1)
alpha = cv2.imread(mask_dir, 1)

mask_img = alpha.astype(np.float32) / 255.0
mask_img = 1 - mask_img

kernel_size = (0, 0)  
sigma = 10  

blurred_mask = cv2.GaussianBlur(mask_img, kernel_size, sigma)

decreasing_values = np.convolve(
    blurred_mask.flatten(), np.arange(256), mode='valid')

decreasing_values = ((decreasing_values - decreasing_values.min()) /
                     (decreasing_values.max() - decreasing_values.min()))

alpha = np.resize(decreasing_values, mask_img.shape)
alpha = np.clip(alpha, 0, 1)

comp = fg * alpha + bg*(1-alpha)

cv2.imwrite(save_dir, comp)
cv2.imwrite(save_dir2, alpha*255)

```
blurred alpha:
![alpha_inv2](https://github.com/Acly/krita-ai-diffusion/assets/21029719/65f7332a-bc39-47d8-8207-b8acb49502dd)
output：
![comp4](https://github.com/Acly/krita-ai-diffusion/assets/21029719/c89f046a-0907-4214-9fc8-9e60662cf1f2)

**Comment by Acly** [comment]
> Secondly, the blurred alpha alters the alpha values corresponding to the foreground image, causing them to decrease from 255.

That's why you dilate first (there is `cv2.dilate` I think).

> Firstly, the blurred alpha generated is still relatively discrete between pixels, for example, 20, 17, 13...

Try different blur filter. It looks like what Krita does is not Gaussian after all, but a simple kernel (circle shape maybe).

Both dilation and kernel size should be 70~80px for your image.

**Comment by Acly** [comment]
Actually in your case the mask already has the shape of the image you want to blend, so you don't need dilation. But alpha values not being 255 at the borders of the image you want to blend cannot be avoided with this method. You are going to loose substantial parts of the foreground image to achieve a nice transition.

**Comment by 99991** [comment]
Here is an example for erosion and Gaussian blur:

```python
import cv2
import numpy as np

# Assuming fg.png is the house, bg.png is the snowy landscape and mask.png is the white rectangle
fg = cv2.imread("fg.png", cv2.IMREAD_COLOR)
bg = cv2.imread("bg.png", cv2.IMREAD_COLOR)
mask = cv2.imread("mask.png", cv2.IMREAD_GRAYSCALE)

# Adjust radius and kernel_size until it looks good
radius = 300
kernel_size = 501

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (radius, radius))
mask = cv2.erode(mask, kernel)
alpha = cv2.GaussianBlur(mask, (kernel_size, kernel_size), 0) / 255.0

alpha = alpha[:, :, np.newaxis]

image = alpha * fg + (1 - alpha) * bg

cv2.imwrite("output_alpha.png", alpha * 255)
cv2.imwrite("output_image.png", image)
```

**Comment by onefish51** [comment]
> Here is an example for erosion and Gaussian blur:
> 
> ```python
> import cv2
> import numpy as np
> 
> # Assuming fg.png is the house, bg.png is the snowy landscape and mask.png is the white rectangle
> fg = cv2.imread("fg.png", cv2.IMREAD_COLOR)
> bg = cv2.imread("bg.png", cv2.IMREAD_COLOR)
> mask = cv2.imread("mask.png", cv2.IMREAD_GRAYSCALE)
> 
> # Adjust radius and kernel_size until it looks good
> radius = 300
> kernel_size = 501
> 
> kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (radius, radius))
> mask = cv2.erode(mask, kernel)
> alpha = cv2.GaussianBlur(mask, (kernel_size, kernel_size), 0) / 255.0
> 
> alpha = alpha[:, :, np.newaxis]
> 
> image = alpha * fg + (1 - alpha) * bg
> 
> cv2.imwrite("output_alpha.png", alpha * 255)
> cv2.imwrite("output_image.png", image)
> ```

I have tested it, and there is a small issue. I replaced `cv2.erode` with `cv2.dilate` to fix it. The specific modification is as follows: 
```python
import cv2
import numpy as np

# Assuming fg.png is the house, bg.png is the snowy landscape and mask.png is the white rectangle
fg = cv2.imread("fg.png", cv2.IMREAD_COLOR)
bg = cv2.imread("bg.png", cv2.IMREAD_COLOR)
mask = cv2.imread("mask.png", cv2.IMREAD_GRAYSCALE)

# Adjust radius and kernel_size until it looks good
radius = 300
kernel_size = 501

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (radius, radius))
mask = cv2.dilate(mask, kernel)
alpha = cv2.GaussianBlur(mask, (kernel_size, kernel_size), 0) / 255.0

alpha = alpha[:, :, np.newaxis]

image = alpha * fg + (1 - alpha) * bg

cv2.imwrite("output_alpha.png", alpha * 255)
cv2.imwrite("output_image.png", image)
```
original alpha：
![alpha_inv](https://github.com/Acly/krita-ai-diffusion/assets/21029719/e8337a76-a03a-4edb-8a69-4107aa80513a)
blurred alpha:
![alpha_inv3](https://github.com/Acly/krita-ai-diffusion/assets/21029719/e60c062d-941c-4fb2-88ba-dd1c09c6e9e9)
progressive alpha:
![blue_img2_mask](https://github.com/Acly/krita-ai-diffusion/assets/21029719/aa9289ed-1aee-4f8a-8a6e-6486dff3824f)

blurred output:
![comp4](https://github.com/Acly/krita-ai-diffusion/assets/21029719/76458aec-26bd-4695-af90-d3d788d27c65)
progressive output:
![comp5](https://github.com/Acly/krita-ai-diffusion/assets/21029719/6d5f0936-185a-45b3-8fbd-209f56116308)

Overall, the results are very close to the performance of the progressive alpha. However, there are still two flaws. Firstly, the cv2.dilate operation takes too long. dilate ops cost: 8.630361080169678 s, while GaussianBlur ops cost: 0.201869134902954 s(input image size is 1920 × 1200). Secondly, there is still a slight abnormality in the transition of the critical region when compared to the results of the progressive alpha fusion method.
![image](https://github.com/Acly/krita-ai-diffusion/assets/21029719/0f900e55-f897-414f-86ab-7a17ef15bb48)

**Comment by 99991** [comment]
> I have tested it, and there is a small issue. I replaced cv2.erode with cv2.dilate to fix it.

Perhaps you switched foreground and background or used an incorrect mask. Usually, one assumes that the white part is the foreground (the house) and the black part is the background (sky).

> there is still a slight abnormality in the transition of the critical region when compared to the results of the progressive alpha fusion method.

Did you adjust `radius` and `kernel_size` until it looks good? See the comment in line 9 here: https://github.com/Acly/krita-ai-diffusion/issues/298#issuecomment-1879385144

If that does not work, but if you know the coordinates of the corner of the rectangle you want to cut out, you could compute the distance to the rectangle and use that as the alpha value.

```python
import numpy as np
from PIL import Image

fg = np.array(Image.open("fg.png").convert("RGB"))
bg = np.array(Image.open("bg.png").convert("RGB"))

# Coordinates of the inner rectangle
x0 = 455
y0 = 586
x1 = x0 + 538
y1 = y0 + 311

# Distance from the inner to the outer rectangle
radius = 260

# Enable smoothing for smoother transition (optional)
do_smoothing = False

w = 1920
h = 1200

# Compute pixel coordinates
x = np.arange(w)
y = np.arange(h)
x, y = np.meshgrid(x, y)

# Find closest point from each pixel to inner rectangle
px = np.clip(x, x0, x1)
py = np.clip(y, y0, y1)

# Distance for each pixel to the inner rectangle
distance = np.hypot(x - px, y - py)

# Compute alpha from distance
alpha = np.clip(distance / radius, 0.0, 1.0)

alpha = 1.0 - alpha[:, :, np.newaxis]

def smooth(t):
    # https://en.wikipedia.org/wiki/Smoothstep
    return t * t * (3.0 - 2.0 * t)

if do_smoothing:
    alpha = smooth(alpha)

# Blend foreground and background using alpha
image = alpha * fg + (1 - alpha) * bg

# Convert images to unsigned byte data type for PIL
image = np.clip(image, 0, 255).astype(np.uint8)
alpha = np.clip(alpha[:, :, 0] * 255, 0, 255).astype(np.uint8)

# Save images
Image.fromarray(image).save("output_image.png")
Image.fromarray(alpha).save("output_alpha.png")
```
