### ISSUE TITLE
contolnet xl

### ISSUE THREAD

**Issue by lymanzhao** [Acly/krita-ai-diffusion#30]
I can use the xl version of checkpoint and lora, but contolnet xl doesn't seem to support it.

**Comment by Acly** [comment]
ControlNet for XL is supported, but it requires different models. The SD1.5 ControlNet models cannot be used with XL.

They're not listed in the UI yet, but you can download ControlNet XL models from [here](https://huggingface.co/lllyasviel/sd_control_collection/tree/main). The following files should work:
* sai_xl_sketch
* sai_xl_canny
* sai_xl_depth
* thibaud_xl_openpose

For some modes there are no XL models yet.
