### ISSUE TITLE
Fails on Install

### ISSUE THREAD

**Issue by EddieSoloProjects** [Acly/krita-ai-diffusion#301]
I have tried installing this 4 times and can't figure out why it fails mid install. This has a Nvidia card and is already running Fooocus.
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13834589/client.log)

**Comment by Acly** [comment]
It has issues downloading a python package (2.4GB). What kind of network are you on? Looks like the connection is frequently interrupted

**Comment by EddieSoloProjects** [comment]
It's my roomate and he is using our Wifi connection. Is there an offline install I can download for him?

**Comment by Acly** [comment]
Technically you can [download the file](https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl) and install it manually, but it requires some tinkering knowledge of Python & pip

You can also do the full install on a different system and just copy the folder, it's relocatable (assuming both are Windows).

**Comment by EddieSoloProjects** [comment]
I just moved his computer to the router :) Thanks for letting me know what the issue was. Great work on this plugin ! We are really enjoying it.
