### ISSUE TITLE
openpose error handling server message: list indices must be integers or slices, not str.

### ISSUE THREAD

**Issue by d23lygjdpzok** [Acly/krita-ai-diffusion#302]
![1](https://github.com/Acly/krita-ai-diffusion/assets/67247523/819a2bdf-aa85-471b-b731-164194fa113b)

"When I click the 'openpose explosion' button, an error occurs with the message: 'error handling server message: list indices must be integers or slices, not str.'"

**Comment by d23lygjdpzok** [comment]
But my other controlnet can be used

**Comment by Acly** [comment]
Which version of the plugin do you use?

**Comment by d23lygjdpzok** [comment]
I have resolved the issue. The reason why it cannot be used is because the controllnet model requires the official specified version, which is not mentioned in the official documentation. If not, please add an explanation. Thank you.

**Comment by Acly** [comment]
You don't need a very specific version - the latest version of the nodes will usually work with the latest version of the plugin. But if one of them is too old it can break.

**Comment by d23lygjdpzok** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/67247523/4d4897c0-5c60-4c9d-a8f8-19d600f1c228)
I understand, I need to install these models before I can use them, although I don't understand why. With Lora_ What is the difference between rank128, fp16 and regular ones? If you know, please explain. Thank you.

**Comment by d23lygjdpzok** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/67247523/edb5d9d9-3892-42fb-9eb5-321c259a8bde)
I understand that installing these models will enable normal usage, but I don't understand why. What do lora_rank128, fp16, and 256lora represent? If you know, please tell me. Thank you."

**Comment by Acly** [comment]
lora_rank128, 256lora - these are smaller more leightweight version of ControlNet. Often they are good enough. But you can also use the full version and it will work.

fp16 - it uses 16bit weights instead of 32bit, this is very common and makes models smaller
