### ISSUE TITLE
Save option gray out

### ISSUE THREAD

**Issue by raniaamina** [Acly/krita-ai-diffusion#305]
Recently update to 1.12.0 and just found that save button gray out so can't be clicked

![gambar](https://github.com/Acly/krita-ai-diffusion/assets/22146607/1a62fb47-dd93-4a70-9922-52914c383ba8)

**Comment by Acly** [comment]
If you created a new document, it needs to be saved once to select the location. Is it grayed out after that?

**Comment by raniaamina** [comment]
Ah yeps, correct. It need document to be saved first.
Thanks!
