### ISSUE TITLE
Generation error after upscaling

### ISSUE THREAD

**Issue by Melo2323** [Acly/krita-ai-diffusion#306]
Generation error after upscaling,no generated picture can be selected, showing assertion error. 
Everything seems to work under 512 x 512 to 1024x1024,but not if using a custom resolution, For example 512 x 814 and after 2x upscale, error popped up after normal generation.

Using the latest version: 1.12.0
no issue prior to this versior,connected to external server.

**Comment by Acly** [comment]
For workaround: this happens only when the width is a multiple of 8, but the height is not.

**Comment by Melo2323** [comment]
Thank you so much, your work is really amazing.

**Comment by Acly** [comment]
Fixed in [v1.13.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0)
