### ISSUE TITLE
Lora Path Error with Local Windows Machine/Linux Remote

### ISSUE THREAD

**Issue by Grant-CP** [Acly/krita-ai-diffusion#307]
I am running into an error where I can select a LORA that is in a folder, but the extension is mangling the path before it gets passed to the linux backend.
Here's is my Krita model config screen:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/a1f194f8-f654-4e0c-aecb-a9127f8d8ae4)
Here is my error log:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/9961070f-b6b6-477a-92fc-503e4f63f788)
Note that other Loras that do not live within a subdirectory work fine. These include Loras from my A1111 install also.
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/c2919a2b-e430-4aaf-8999-9196878fcddc)

I'm not sure what the easiest fix would be. I'm happy to test any solutions. The issue is presumably the the picker menu in Krita inserts the wrong path dividing character, and then that path is used verbatim in the workflow API call.

It is worth mentioning that this path issue does not exist for the model checkpoints tab:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/d0deaae4-fb96-4a69-9f8f-41a0b79adaa9)
Observe the SDXL turbo path, which as the correct "/" path separator. Perhaps the code for the model checkpoints menu can be ported to the Lora menu?

An easy workaround for now is to not use any enclosing folders for Loras in my remote.

Extra info:
Extension was last update Dec 04. 
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/cb58f5d4-d742-46b2-84d0-dab80a37dcef)

**Comment by Grant-CP** [comment]
Wanted to add some extra info from the comfyui.log file. It might be that part of my issue is related to a custom extension. Note even if this is a custom node issue, there is still the Krita plugin issue of inconsistent path separator behavior between the Lora and Checkpoint selector bars.

I'm dumping the error logs on my remote machine here:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/c723b133-3a7b-4c5b-b9ed-42a3ba9e0284)

We can see in these logs that the comfyui process appears to see the paths correctly in the remote machine even if Krita is possibly passing them to the API incorrectly.

Not that this is your issue, but here's the full error message on the comfyui side, which is not too helpful I don't think. I'll look into what a fix might be on the pysssss node side tomorrow
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/968eafe4-cc52-497f-a484-a1c9cbd95f54)

**Comment by Acly** [comment]
That makes some sense: to get the menu structure the UI splits the full path into a tree and reassembles it when a menu item is selected. This happens with `os.path.join` which will use the client's OS-native path separator.

Posssible fixes: detect and use the server path separator, or keep the original full path for each item around. Second option is probably more robust.

**Comment by Grant-CP** [comment]
Let me know if you have anything that you want tested on cross-platform server/client issues. Really appreciate the work you are doing here.

**Comment by Acly** [comment]
Should be fixed in [v1.14.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.0), let me know if there are still problems.

The other way round is probably still an issue, Comfy on Windows transmitting backslash to a Linux client, it will choke. But that's harder to fix and much less likely scenario.
