### ISSUE TITLE
Error: Could not installed model.safetensors for SD1.5

### ISSUE THREAD

**Issue by aaaiyo** [Acly/krita-ai-diffusion#308]
![1](https://github.com/Acly/krita-ai-diffusion/assets/134725788/7d137891-a5f0-47ca-a599-004382cb7366)
![image](https://github.com/Acly/krita-ai-diffusion/assets/134725788/cde7d60f-bd5d-4d6a-8733-738273c5dc85)
![2](https://github.com/Acly/krita-ai-diffusion/assets/134725788/dfa1c7cd-72fd-4ec7-bdd8-1a77735eda83)
![image](https://github.com/Acly/krita-ai-diffusion/assets/134725788/75fe4dd9-15f6-415a-b09f-486b13d6be75)
controlnet model is also cant installed
![image](https://github.com/Acly/krita-ai-diffusion/assets/134725788/16804056-9cb9-4892-9267-2351d893335c)

**Comment by Acly** [comment]
Please read and follow the requirements, and check/post client.log for missing models
https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md

**Comment by aaaiyo** [comment]
您的邮件已收到，我将尽快回复您。

**Comment by Fox1985CLB** [comment]
I am also in the same situation. After version 1.9, Checkpoint cannot display the sd1.5 model. Could you please help me check where the problem lies.
![微信截图_20240115112011](https://github.com/Acly/krita-ai-diffusion/assets/156494515/140f1826-9f17-49e0-81fb-35f6fe7d98b3)

**Comment by Acly** [comment]
If you are missing only SD1.5 checkpoints, try to update or reinstall `comfyui-tooling-nodes`. See #267 for things to check.

**Comment by Fox1985CLB** [comment]
The problem has been resolved. Thank you for your help :)
