### ISSUE TITLE
When will it be possible to embed PS

### ISSUE THREAD

**Issue by guyuehu2304** [Acly/krita-ai-diffusion#309]
If this program can be transferred to PS, it will be the biggest surprise in the design industry, and hopefully it will happen soon

**Comment by Acly** [comment]
Why would anyone do that though? It's a ton of work, all profits will go to Adobe, and they eventually replace it with their own more deeply integrated tools.

**Comment by nakanakapoi** [comment]
> Why would anyone do that though? It's a ton of work, all profits will go to Adobe, and they eventually replace it with their own more deeply integrated tools.

Totally agreed. Please gatekeep this amazing plugin to Krita only. Besides, there are already exist other SD plugins for PS. Adobe is desperate to implement AI because open-source is catching up to them. This plugin totally closes the gap.

**Comment by guyuehu2304** [comment]
As a designer, it would be very sad news if you couldn't embed PS, because Krita was too limited to take advantage of the power of this SD plugin.

**Comment by nakanakapoi** [comment]
> As a designer, it would be very sad news if you couldn't embed PS, because Krita was too limited to take advantage of the power of this SD plugin.

Is Adobe generative AI not good? If I already paid them, I would definitely use it instead to get worth my money. I would overuse their server till I get banned if possible.
