### ISSUE TITLE
Other Models error with ControlNet not installed (when adding an image control layer)

### ISSUE THREAD

**Issue by MasterJames** [Acly/krita-ai-diffusion#31]
I tried to use a different Model like this one from civitai
https://civitai.com/models/122822?modelVersionId=133832
but when I click to ad the Image as a Background to weight the text over it says...
ControlNet not installed"
but it works for the two provided models.
I am not knowledgeable about the cause of this.
Is it not possible? the LoRA work fine, but the models lose access to control layers.
Is there a place where there are models with ControlNet setup to work with this Addon in Krita?
If someone could please explain or provide a link to understand this.
I saw maybe there was a way to convert them here? https://stackoverflow.com/questions/76450546/how-to-use-civitai-checkpoint-with-controlnet

**Comment by Acly** [comment]
The model you linked to is a SDXL model (on civitai you can see Base Model | SDXL 1.0). Other models you download generally work fine with all ControlNet modes. But the ControlNet models you can download via UI are for SD 1.5, not XL. Those are not compatible (you also cannot mix 1.5 and XL lora).

If you want to use control layers with XL you can: They're not listed in the UI yet, but you can download from [here](https://huggingface.co/lllyasviel/sd_control_collection/tree/main). The following files should work:
* sai_xl_sketch
* sai_xl_canny
* sai_xl_depth
* thibaud_xl_openpose

Put them in `ComfyUI/models/controlnet`. For some modes there are no XL models (nobody has trained any so far).

**Comment by MasterJames** [comment]
I see thank you for the explanations.
