### ISSUE TITLE
Issue : I cannot choose an SD1.5 checkpoint for my preset

### ISSUE THREAD

**Issue by Trobinou** [Acly/krita-ai-diffusion#313]
Hello,

When I installed version 1.12, I noticed that I could no longer choose an SD1.5 checkpoint for my presets, only an SDXL checkpoint.

My CHECKPOINTS directory \ComfyUI\models\checkpoints is made up of 2 sub-folders: SD1.5 & SDXL which contain the checkpoints corresponding to these 2 versions:

![folder](https://github.com/Acly/krita-ai-diffusion/assets/132901709/a8bee2e4-ebda-40f6-907f-5b59d2242f35)

In the control panel, on the STYLES tab, I only have access to SDXL checkpoints:

![XL only](https://github.com/Acly/krita-ai-diffusion/assets/132901709/35bef505-376e-4a53-b0a5-fdf2418c28c3)

Thank you in advance.

**Comment by Acly** [comment]
Which version were you upgrading from? Maybe same issue as #267

**Comment by Trobinou** [comment]
from 1.11.1

**Comment by Trobinou** [comment]
I looked at #267 and it seems to be the same problem: my checkpoints are detected as "stab"

So I deleted the 'comfyui-tooling-nodes' directory and downloaded the pack again (as user vidiotgameboss mentions) and now my SD1.5 checkpoints are well recognised 👌

**Comment by gxground** [comment]
> I looked at #267 and it seems to be the same problem: my checkpoints are detected as "stab"
> 
> So I deleted the 'comfyui-tooling-nodes' directory and downloaded the pack again (as user vidiotgameboss mentions) and now my SD1.5 checkpoints are well recognised 👌

SOLOVE MY PROBLEM ,THANKS A LOT
