### ISSUE TITLE
Google Coral?

### ISSUE THREAD

**Issue by Kogije** [Acly/krita-ai-diffusion#314]
Not as much of an Issue as a Question -- With torchml already supported for Radeon Cards, are there any plans to add support for Google Coral?

**Comment by Acly** [comment]
This is more a question for the backend (ComfyUI), but I don't know of any development in that regard. While it's technically possible to run stable diffusion on TPUs (and has been done), supporting that kind of highly flexible and extensible ecosystem is a lot of work I think, and probably unrealistic for now...
