### ISSUE TITLE
How to add new ControlNet models via resources.py?

### ISSUE THREAD

**Issue by AlekFy** [Acly/krita-ai-diffusion#316]
There are many new models for the sketch/scribble XL controlnet, and I'd love to add them to the Krita SD plugin. Can you please help me understand where should I edit the file to add more options for the dropdown menu?

**Comment by Pirog17000** [comment]
Would be great to see custom added options in the settings menu for control nets.
Like, per every newly added controlnet, the more options appear in the main interface menu for controlnet selection.

**Comment by guzuligo** [comment]
Thanks for the idea. 

I added inpaint as an option. It helps me control when I want the generator to deviate from my drawing.

I wish adding controlNets was something in a json config file instead of it being hardcoded.

**Comment by Acly** [comment]
Coding it in has advantages, there is a bit more to it than selecting a model file. While I'm not generally opposed to extensibility, consider that it's a niche use case for some users who know about models, comfy, json files, etc.

Integrating a new CN or replacing existing models along with evaluation and testing is more work yes, but it can be discovered by and will benefit all users.

**Comment by guzuligo** [comment]
I see what you mean. Accessibiliy is more importart, especially for artists.

Probably then you could just add an optional JSON file or a simple text file for anyone who wants the extra controlnets and have the tricks for the related preprocessing.
