### ISSUE TITLE
Live generation send to new layer results in blank layer

### ISSUE THREAD

**Issue by CelebBattles** [Acly/krita-ai-diffusion#317]
When I create a live generation and try to send it to new layer, it creates blank images. Video for reference.

https://github.com/Acly/krita-ai-diffusion/assets/66290957/1c610a8d-6a6c-476f-850d-8b44d19a7f59

**Comment by Acly** [comment]
I suspect this is the same issue as #306 - try with a canvas height that is a mulitple of 8 (eg. 704 instead of 700)

**Comment by Acly** [comment]
Let me know if it still happens in [v1.13.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0)
