### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by Drakosha405** [Acly/krita-ai-diffusion#32]
1.  correct me if I'm wrong, but now the one in the style settings is added to the prompt that you write?
for sdxl and not, many times u write prompt like this "anime artwork {prompt} . anime style, key visual, vibrant, studio anime, highly detailed" so I think its be great if we can replace {prompt} when write our describe.

2. negative prompt.
in order to avoid overloading the interface, a line for a negative prompt was not added. maybe then it's worth making the possibility of this in one line as "cat [dog] or cat ||dog". Where is cat a positive and dog a negative prompt?
example if you request "city street" very often there will be a street with cars and adding car and a negative prompt will give more probability of a street without cars

3.  I hope we can see ip- adapter for SDXL too.
and here we have [ip-adapter_xl.pth](https://huggingface.co/lllyasviel/sd_control_collection/blob/main/ip-adapter_xl.pth) for images.
and here clip_vision for XL [clip_vision_g.safetensors](https://huggingface.co/stabilityai/control-lora/blob/main/revision/clip_vision_g.safetensors)

4. maybe we need wiki where we can find info wants model for XL supported? I can find this only in resources.py file. (as not add this in ui yet)

**Comment by Acly** [comment]
Prompt works mostly like that, yes. There is also a case where area conditioning is used, but not for the style prompt, so in that case they are separated. Should still be possible to implement a {prompt} placeholder though. I will also think about optional UI for negative prompt.

IP-Adapter for SDXL I can add. It behaved a bit strange when I tested it, but that was a while ago. Unfortunately I could also not make it very useful for inpaint. Missing flexible inpaint support is the main reason why SDXL is a bit "hidden" at the moment. For now results with SD1.5 are much better (especially without prompt).

There is definitely the plan to revisit SDXL in near future though, and add recommended downloads in the UI.

**Comment by Drakosha405** [comment]
when I was looking about inpaint for SDSL, I found this [diffusers/stable-diffusion-xl-1.0-inpainting-0.1](https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1) I don't know if you've seen it and whether it will be useful

**Comment by Acly** [comment]
> when I was looking about inpaint for SDSL, I found this [diffusers/stable-diffusion-xl-1.0-inpainting-0.1](https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1) I don't know if you've seen it and whether it will be useful

Yes it does help a bit, but unfortunately isn't integrated well with ComfyUI. There is also the issue that it's another full 5GB+ model and not compatible with custom checkpoints (you'd have to do a merge for each, which is quite slow and resource heavy...)

**Comment by Acly** [comment]
1. {prompt} is now supported
2. negative prompt can be added to the UI in Interface options
3. IP-adapter for SDXL works, note that you need [ip-adapter_sdxl_vit-h.bin](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.bin) in `ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models`. The `clip_vision_g.safetensors` is _not_ needed (the clip vision from SD1.5 will be used, apparently that works, results are good, and it uses less VRAM)
