### ISSUE TITLE
[Bug] Fails with Clone Layers

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#320]
I use clone layers in order to prepare the image to controlNet. I draw on the main layer and the clone layer automatically updates with the effect (Similar to pre-processor).

Unfortunately, it seems I have to disable the layers and re-enable them in order for the plug-in to pick them up. This is specifically difficult with Live Mode.

I've attached a krita file including clone layers and group layers so you could experiment with it. Combining clone layers with mask filters as a preprocessor is very convenient in Live Mode.

[Clone Layer Bug Report.zip](https://github.com/Acly/krita-ai-diffusion/files/13898693/Clone.Layer.Bug.Report.zip)

**Comment by Acly** [comment]
I think I know what you mean. Krita doesn't update group/clone layers if they're not visible - probably a performance optimization.

**Comment by Acly** [comment]
I tried some more and as long as the input for control layers are visible, I don't have any issues.

Clone and group layers update reliably, the problem I found are *filter masks* which are *invisible* or in a group that is invisible. Krita does not run filters if they are not set to visible.

I don't think I can fix this, I tried to force a refresh when generating, but it noticeably impacts performance, annoying especially in live mode. Krita does it efficiently in the background, but there is no way to enforce that.

Everything seems fine as long as the group/filter is set to visible, but could still be hidden beneath a fully opaque layer. You'll pay for exclusion from img2img (#331) but only once and much cheaper.

**Comment by guzuligo** [comment]
"Krita does not run filters if they are not set to visible."
IMHO, that's actually a good thing that you shouldn't fix! Sometimes, I put several filter masks to test which mask is doing the best job, or sometimes I want to disable a mask just to render different looking outputs.

"You'll pay for exclusion from img2img"
I really wish there was a checkbox to disable that exclusion altogether 😅

**Comment by Acly** [comment]
Yes it makes sense that filters which aren't visible don't apply. That's not the problem.

I expected to get a layers content if I specifically request it via API, like it works when no filters are involved. In this case even if the filter is visible/enabled and only the group it's in is not, it causes the group image to be outdated. I don't think that behvaior makes sense, just unlikely anybody cared.

> I really wish there was a checkbox to disable that exclusion altogether

Because of performance issues?

**Comment by guzuligo** [comment]
>Because of performance issues?
And convenience issues as well.

For example, I make two layers, one for outlines, and another in multiply mode for colors.
Then, I use the outline layer in lineart controlnet, and color layer in blur controlnet. Then, denoise is set to 0.5 to get both the lineart and color.

With  exclusion enabled, both layers disappear and denoise gets no image to work with. This forces me to make duplicate layers just to make the exclusion is happy.

**Comment by Acly** [comment]
Fair enough. I'd still like to get away without a checkbox if possible though!

I think it's safe to say that for most control inputs, it doesn't make sense for them to participate in img2img. They are used purely as hints.

Also for generating over preview... there is the Apply button for this. Sometimes I too forget to press it, but I tried the reverse (included by default) for a while and it felt worse.

Blur control net: I've never seen anyone use Blur like that (and I think it's not really trained for that), but if it works why not. Also it's actually a case where using the same input for control net and img2img is a good default. That's essentially what the upscaler does too. So I would just change it to never be auto-excluded, checkbox not strictly needed.

Line art is the most interesting. It makes sense for lines to be included in the final image. But also I sometimes draw lines on top of my image to make corrections, but don't use a style with visible lines. Maybe a toggle is needed here, at least to make both cases convenient to use...

**Comment by Acly** [comment]
Hm I just notice "Blur" was already exempt from auto-exclusion, so I must've thought of this before. Maybe I will just add lines.

**Comment by guzuligo** [comment]
>Blur control net: I've never seen anyone use Blur like that

Even better, when I added the Inpaint to the list, I managed to make the colors auto fit inside the drawing. I just need to splash them on the drawing.
![image](https://github.com/Acly/krita-ai-diffusion/assets/4189008/a9151dcd-0123-465f-95c7-88910afdd79f)

Unfortunately, sharing the Krita file won't be helpful as it is a modification I did to the plug-in.

**Comment by Acly** [comment]
That is more of a happy coincidence though :)
Inpaint CN doesn't make much sense without a mask, and I feel it should be possible to get this result without it.

**Comment by guzuligo** [comment]
I'd like to share my idea of how to use inpaint the way I mentioned.

What I actually do is use Inpaint **without** a pre-processor. Put high weight, example 70%, and let it end on something like .5 or .6 time. Also, I use a 90% or 100% denoise. 

What this do is that the inpaint forces the sampler to almost keep my original drawing until a certain time, then it breaks loose. The result is that mistakes in my drawing gets fixed, or it could change my drawing without ending up drawing something else.

Maybe not many people know of this trick. But for me, this idea works even better than other CNs and sometimes I don't even need other CNs. But still, it could produce better results when combined.

**Comment by Acly** [comment]
> What this do is that the inpaint forces the sampler to almost keep my original drawing until a certain time, then it breaks loose.

This is essentially what using low strength/denoise does already - it skips part of the initial sampling steps until a certain time (strength * steps) and only samples the rest, using your image as input from there. It's a lot faster.

The difference probably comes from the first part where the control net is applied, it allows some changes. I wonder if there is a more straight forward way to condition diffusion to follow an input image.
