### ISSUE TITLE
Do you have any plan of integrate the ControlNet LLLite?

### ISSUE THREAD

**Issue by shalin-okada** [Acly/krita-ai-diffusion#321]
Your plugins have always helped me.
Thank you very much.

Official SD XL ControlNet doesn't include good scribble model.
But kohya's ControlNet LLLite Scribble model is seems good.
https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI

So I want to know do you have any plan.
If yes, I want to know when, or I want to try contribute.
If not, I want to know reason.

**Comment by Acly** [comment]
No concrete plans, the main reason I haven't used them over the others is that they require an extra custom node package. That's not a show-stopper though, if you can demonstrate the scribble works better than using current one  it would be worth replacing it.
I agree current solution for SDXL scribble  isn't great, but comparison of a few scenarios would still be nice. For the current one you probably want a lower strength (around 50%).

**Comment by shalin-okada** [comment]
Thank you.
I tried with lower strength but it's not good, so I'll try LLLite in ComfyUI and upload the result.

**Comment by Acly** [comment]
Somewhat similar discussion in #316, though the OP never mentioned what models they had in mind.
