### ISSUE TITLE
[BUG] Selection with feather at the edge cause error of tensor size mismatch

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#325]
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/d79903b5-ae37-4d33-b65b-2573102f928b)

To reproduce:
- rectangular selection tool with large feather
- select the edge of the image
- generate with power less than 100%

**Comment by Acly** [comment]
Can you attach a .kra file with the selection to reproduce? The image content doesn't matter (blank is fine), but the canvas size and exact size & position of the selection are relevant.

**Comment by Pirog17000** [comment]
I can't reproduce it anymore anyhow, tried to do the same thing and it doesn't give any errors :/

**Comment by guzuligo** [comment]
I faced the same error on 11% of grow and feather and being close to the edge.

**Comment by Acly** [comment]
Let me know if you run into this in [v1.13.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0)
