### ISSUE TITLE
Image Generation Stops Working After Anything is Changed (AMD DirectML)

### ISSUE THREAD

**Issue by ketpain** [Acly/krita-ai-diffusion#326]
I can get the first generation or first doodle working, but as soon as I make a selection or any type of modification the image will not generate. 

Pressing on the generate button again does nothing as the program seems to think it's still generating an image, but it is doing no work.

Canceling the active batch also seems to do nothing and the progress bar remains the same.

(I'm also on AMD XTX 7900 - 24GB VRAM)

Edit: After more playing around, I figured it out. Mostly user error, but it is easy to "break" without getting any runtime response

I've also run into memory issues where it goes out of bounds in big numbers of RAM, say 64gb or something.
<img width="530" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/42127943/0eb4b02f-3719-40b3-9b27-a261cef8528b">

**Comment by Acly** [comment]
So... what was the issue? Anything to improve?

> Canceling the active batch also seems to do nothing and the progress bar remains the same.

This generally works for me (progress is reset, queue count goes down) - depending on what it's doing at the time it may have a delay though (you can't cancel all operations, like loading a big model has to complete before the rest of the job is cancelled)

> I've also run into memory issues where it goes out of bounds in big numbers of RAM, say 64gb or something.

I think I've seen this before when trying DirectML. It's not very stable backend unfortunately.
