### ISSUE TITLE
[BUG] Upscale menu doesn't check the setting before processing

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#327]
![image](https://github.com/Acly/krita-ai-diffusion/assets/3022852/b8a57b7c-f252-4b05-8f36-c7b334ee1b9d)
Long story short, if I come to upscale menu, untick the 'Refine' checkbox and hit upscale, it still keeps processing with checkpoint.
But, if I tick, roll the settings a little and untick again - no more.

**Comment by Acly** [comment]
I tried this a bunch of times, but can't reproduce. 

Found/fixed an issue where no upscale model was set initially, but it was unrelated I think.

This happens for you everytime? Start Krita, open document, go to upscale workspace, untick and hit upscale?
