### ISSUE TITLE
[Bug] Controlnet suddenly loses effect

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#329]
I'm not sure how to reproduce this bug, but it keeps reoccurring within a short time in the Live Mode.

Add a controlnet like image or blur, then keep doing changes like:
- changing its strength and end time
- change the layer it is reading from
- change the seed and strength
- Add and remove layers
-  apply generation

After some changes, you'll suddenly see that any change to the controlNet has no effect until you remove it and add it. And sometimes even after adding it, the bug sticks.

**Comment by Acly** [comment]
I haven't encountered this so far... did you try saving the file and reloading? Is the configuration still the same and does it "fix" the issue?

**Comment by guzuligo** [comment]
I haven't encountered the issue since I removed the exclusion. I'll let you know if I encounter it again.

**Comment by guzuligo** [comment]
It seems it still happens. Specifically when I use Reference and blur CNs together and keep changing stuff. Suddenly they all lose effect and I don't notice until I try changing their strength value.
