### ISSUE TITLE
Safetensors Error

### ISSUE THREAD

**Issue by fanialivio** [Acly/krita-ai-diffusion#33]
Hi, 

I'm trying to configure the server but this error occurs.

I'm using Krita 5.2 on Linux Fedora 39 beta

![Screenshot from 2023-10-26 12-43-24](https://github.com/Acly/krita-ai-diffusion/assets/30428953/7d858bf6-dd94-4d21-8254-c6dfb6c14d91)

I noticed that python is needed in Linux, and I don't know if the error is related to python installation, but I got this error from terminal : E: Unable to locate package python3-venv

I also installed Safetensors, if I run a new install in the terminal, i have the output: 
Requirement already satisfied: safetensors in ./.local/lib/python3.12/site-packages (0.4.0)

**Comment by fanialivio** [comment]
Here you will find the log files:
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13176658/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13176659/server.log)

**Comment by Acly** [comment]
Hi,
from the log it looks like installation was aborted the first time round. Was there a crash or was Krita shut down for some reason during install? This has resulted in ComfyUI component being only half installed. I will try to make this a bit more robust...

To fix you can try either:
* manually remove `/home/liviux/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/.server/ComfyUI/main.py`, this should allow you to install the missing part via the UI (without having to redownload everything)
* or manually install the dependencies:
  ```
  /home/liviux/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/.server/venv/bin/pip3 install torch torchvision torchaudio -- index-url https://download.pytorch.org/whl/cu121
  /home/liviux/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/.server/venv/bin/pip install -r /home/liviux/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/.server/ComfyUI/requirements.txt
  ```
* or remove entire `.server` folder to do a full reinstall

**Comment by fanialivio** [comment]
Thank you very much for your reply. Actually yes, the one in the log was a Krita crash...it kept crashing again and again until I assigned 100% of resources to Krita. I was finally able to run the server, but only using CPU, since I have an issue installing Nvidia drivers on Fedora. But that's another story...

Thank you again for your work and for this wonderful plugin
