### ISSUE TITLE
Why exclude layers in get_image in Document.py?

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#331]
What is the job of this array variable in get_image function in the Document.py file?
```
excluded: list[krita.Node] = []
```
I forced it to be empty and it seems all my slowness and bad updating issues got resolved. 🫤

Edit:
For the ControlNet layers, I usually just keep them under the background layer so they are not visible. And if for some reason I want them visible, I put them above.

**Comment by guzuligo** [comment]
I attached a krita file to show how I group my controlNet layers while still avoiding the clutter.

[ControlNet Grouping.zip](https://github.com/Acly/krita-ai-diffusion/files/13928638/ControlNet.Grouping.zip)

**Comment by Acly** [comment]
As you maybe surmised, it's to exclude control layers from img2img. Of course you can hide them manually, but not everyone is aware, it's easy to forget, and actually often just plain convenient to modify eg. pose which is layered on top of your current image input.

Note: if you hide your control layers, then `excluded` will do nothing (it checks if layers are already invisible).
