### ISSUE TITLE
SDXL scribble feature is not working.

### ISSUE THREAD

**Issue by syou97** [Acly/krita-ai-diffusion#334]
Hello. Thank you for developing this nice plugin.

I tried to use "Scribble" with SDXL models, but I get an error saying there are no models.
The model is
I put "kohya_controllllite_xl_scribble_anime".

Is the Scribble function of SDXL currently not supported?
Or is there something wrong with the procedure?

**Comment by Acly** [comment]
SDXL Scribble currently uses the [sketch control-net](https://huggingface.co/stabilityai/control-lora/blob/main/control-LoRAs-rank256/control-lora-sketch-rank256.safetensors) (same as line art). It works okay at low strength but not great. ControlLLLite needs an extra extension, see #321
