### ISSUE TITLE
not enough GPU video memory available, but there is enough

### ISSUE THREAD

**Issue by ImBehinYa** [Acly/krita-ai-diffusion#335]
Hi 

i have a 6750 XT with 12 GB VRAM,
but i get the error: RuntimeError: Could not allocate tensor with 1032884736 bytes. There is not enough GPU video memory available!

Generativ adding or chaning dosnt work...

and 1032884736 bytes equal 1 GB so something is off...
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13940766/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13940767/server.log)
![image](https://github.com/Acly/krita-ai-diffusion/assets/63367722/cd6a3245-1e90-4557-9281-0e43c895f13a)

**Comment by ImBehinYa** [comment]
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13942063/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13942065/server.log)
generativ add change expand also not working

**Comment by Acly** [comment]
> and 1032884736 bytes equal 1 GB so something is off...

It means it needs an _additional_ 1 GB on top of what it's already using, if it no longer fits you get this error. Depending on resolution and model you can run out of memory at 12 GB quickly with DirectML (unfortunately it uses 2x the memory compared to CUDA).

100% strength + selection just gets stuck for me at the moment. Used to work a while ago. Not sure what I can do, probably disable IP-adapter (it will not work as good, but at least it might work at all).

Less than 100% strength should run fine.

**Comment by Acly** [comment]
Disabled IP-Adapter for AMD/DML as it is listed there as "not working due to AMD driver/implementation issues" now. This should make 100% strength inpaint work, albeit not with same quality.
