### ISSUE TITLE
Can't Paste Seed If Using Cloud GPU

### ISSUE THREAD

**Issue by raniaamina** [Acly/krita-ai-diffusion#338]
![gambar](https://github.com/Acly/krita-ai-diffusion/assets/22146607/6d4f5679-4244-4925-9ee5-557eb87d6eef)

I do not know for sure how it can happen, when I use a local server, copy paste seeds on the drop menu next to the generate button can work normally, but when using the GPU cloud my Paste function does not work as it should.

**Comment by Acly** [comment]
What do you mean exactly with "does not work as it should"? Can you modify the seed via typing? Only paste doesn't do anything?

It's probably not (directly) related to cloud GPU - the plugin/UI doesn't know or do anything different depending on where you connect to.

**Comment by raniaamina** [comment]
I mean after copy seed value, then when i ctrl v or right click then click paste, it does not paste anything. I know it bit weird condition, i'll try to record screen when it happen again.

**Comment by Acly** [comment]
The seed number would also be interesting, maybe it's an issue of the UI not accepting certain (too high) numbers.
