### ISSUE TITLE
[Suggestion/Idea] Adetailer

### ISSUE THREAD

**Issue by Dartterious** [Acly/krita-ai-diffusion#339]
Having an option for [ADetailer](https://github.com/Bing-su/adetailer) would be extremely appreciated. Being able to clean up faces quickly is so helpful it really would make this program worlds better than others out there. 

Thanks!

**Comment by tashachan28** [comment]
Seconding this, because ADetailer is fantastic.

**Comment by sonyeon-sj** [comment]
I agree.
