### ISSUE TITLE
Question: Possible to use on Paperspace?

### ISSUE THREAD

**Issue by Normiegetout** [Acly/krita-ai-diffusion#34]
Firstly, I apologize if this isn't the appropriate place to ask this, but I'm wondering if it's possible to use krita-ai-diffusion through Paperspace. Additionally, could you give an indication of how complicated this might be because the guides for runpod and vast.ai are so clear.

Please feel free to close this issue if it's pointless question.

**Comment by Acly** [comment]
If you can run ComfyUI on Paperspace, then almost certainly it should also work for this plugin. I know this used to be possible, but I have heard Paperspace banned tunneling at some point which made it difficult. Then again, there is this [recent blogpost](https://blog.paperspace.com/stable-diffusion-apps/) which indicates it should work.

If you are able to connect the plugin, it will probably miss some nodes and models that are [listed here](https://github.com/Acly/krita-ai-diffusion/tree/v1.5.0#optional-custom-comfyui-server). But they're not difficult to download and install.  I'm happy to help with that part, but we should check the connection first.
