### ISSUE TITLE
SD1.5 workflow error, XL normal, for 1.5 other models can not work, why?It was fine before, but it's been like this since the upgrade

### ISSUE THREAD

**Issue by kenic123** [Acly/krita-ai-diffusion#340]
![image](https://github.com/Acly/krita-ai-diffusion/assets/67681738/7a43814f-6ebb-47cf-9484-b5a94efd4924)

**Comment by kenic123** [comment]
找到原因了！！插件不适应最新版 comfyui，回到旧版 comfyui 问题就解决了，所以用本地自装 comfyui 的小伙伴注意了，1.5 工作流会报错！Found the reason！！ the plugin is not adapted to the latest version of comfyui, back to the old version of comfyui problem is solved, so with local self-installed comfyui partners note that the 1.5 workflow will report an error!

**Comment by kenic123** [comment]
Hopefully it will be adjusted soon. Because one computer can't open both backends.

**Comment by Acly** [comment]
I just tried latest ComfyUI and it works fine. Did you also update ComfyUI_IPAdapter_plus custom node?

**Comment by kenic123** [comment]
> I just tried latest ComfyUI and it works fine. Did you also update ComfyUI_IPAdapter_plus custom node?

Yes, ComfyUI_IPAdapter_plus Reinstalled，but still error

**Comment by Acly** [comment]
Strange. The error message looks like what you get when you use the wrong clip vision model (tensor size mismatch 1024 vs 1280). Are you sure the `models/clip_vision/SD1.5/model.safetensors` is the same in both cases?

**Comment by kenic123** [comment]
> The error message looks like what you get when you use the wrong clip vision model (tensor size mismatch 1024 vs 1280). Are you sure the `models/clip_vision/SD1.5/model.safetensors` is the same in both cases?

Thank you very much for your attention, without which I probably would have given up troubleshooting. After a day and two nights of trying, purely trying (I don't know the code), I have found the solution to the problem: the problem is with the ipadapter model storage, so far I can't troubleshoot which model is the problem, but I have found that the ipadapter model can only be stored in the ipadapter folder under the checkpoint and in the ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models folder under checkpoint, remember, this is very important, these two folders can only be used in one folder to store the models, in this case it can run normally, otherwise it will report this error. Maybe then this plugin can deliberately specify to read the models in a folder, I feel this is the best way, but I do not know how to code, bitter ah. Finally thanks to the code gods for writing such a great plugin, all respect belongs to them!

As for the point mentioned at the beginning about upgrades causing problems I'm not so sure now, maybe guys can upgrade conservatively, just a way to try to solve the problem. I don't have much time to verify it all over again.

非常感谢你的关注，没有你的关注我可能早就放弃排查了。经过了一天两夜的不断尝试，是纯粹尝试（我不懂代码），我找到了解决问题的办法：问题出在了ipadapter模型存放上面，到目前我无法排查是哪个模型出的问题，但是我发现ipadapter的模型只能存放在checkpoint下的ipadapter文件夹和ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models下的文件夹中的其中一个，记住，这很重要，这两个文件夹只能用一个文件夹来存放模型，这种情况下可以正常运行，否则就会报这个错误。或许再本插件中可以特意指定读取一个文件夹中的模型，我感觉这是最好的办法，但是我不会代码，苦啊。最后感谢代码大神撰写了这样一个伟大的插件，所有的尊敬都属于他们！

至于最开始提到的升级导致问题的观点我现在不太确定了，或许小伙伴们可以保守升级，只是一种尝试解决问题的方式。我没有太多的时间再去验证一遍。
