### ISSUE TITLE
Problem with Setting Lora models Version 1.12.0 

### ISSUE THREAD

**Issue by b4zz4** [Acly/krita-ai-diffusion#341]
This worked perfectly in the previous version

![2024-01-17_10-54_27](https://github.com/Acly/krita-ai-diffusion/assets/643833/6d1f43b6-730b-4011-a638-7444f4e9e1f2)

OS: Linux (Arch)
Krita 5.2.2

**Comment by Acly** [comment]
LCM Lora is applied automatically when LCM sampler is used (has always been that way since LCM is supported). Other Lora should appear as usual.
