### ISSUE TITLE
How can I delete the history manually?如何手动删除历史记录呢？

### ISSUE THREAD

**Issue by kenic123** [Acly/krita-ai-diffusion#342]
Now you can perform a lot of operations on the generated results, but why is there no delete option? There are times when a lot of historical images are generated and you need to selectively delete some of them, so how do you do it?

**Comment by Acly** [comment]
It's not possible at the moment.

Out of interest, why do you want to do it manually?

Deleting one by one sounds very tedious. Would you expect of multi-select?

**Comment by longkinght** [comment]
I also have this need, because there are too many images generated, sometimes there are some obviously dissatisfied want to delete, otherwise it will interfere with the selection. I also hope to add a copy of the history of the prompt word function, because after modifying the prompt word found the previous better, want to restore can only re-enter, if you can directly select the previous prompt word and automatically copy to the prompt word box would be great.

**Comment by longkinght** [comment]
<img width="644" alt="微信图片_20240127205604" src="https://github.com/Acly/krita-ai-diffusion/assets/9004313/3c7e92ad-b949-4dda-9b3c-e45005fdfd08">
1.13.1 I can't find the Delete picture button. What do I need to do?

**Comment by piotrkucharski** [comment]
@longkinght

> 1.13.1 I can't find the Delete picture button. What do I need to do?

It's not implemented - the screenshot I posted was only an idea how it could be done.

**Comment by kenic123** [comment]
> This would be useful:这将很有用：
> 
> ![delete-image](https://private-user-images.githubusercontent.com/5716174/299257256-26ee527b-0da2-4051-bfea-16b1e8999f6d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDQ5MzgsIm5iZiI6MTcwNjQ0NDYzOCwicGF0aCI6Ii81NzE2MTc0LzI5OTI1NzI1Ni0yNmVlNTI3Yi0wZGEyLTQwNTEtYmZlYS0xNmIxZTg5OTlmNmQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTIyMzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA2N2ZmNGZjYTJhMmY5N2U1M2U2MzdmOWQwYjgyZmZmNTgxYTVjODllZGY5MTA2Y2Y5ZDYxZjAxMTk0YTBlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LC_g63I2JIAm2nptrFoxN_mQF0ZC7GCr2WT6RrGCBOk)

I was pleasantly surprised for a moment and thought it was realized! Too many pictures can interfere or detract from creativity. Needed this feature so badly!

**Comment by kenic123** [comment]
> It's not possible at the moment.
> 
> Out of interest, why do you want to do it manually?
> 
> Deleting one by one sounds very tedious. Would you expect of multi-select?

When creating something, you only want to see the pictures that are relevant to the original idea, and too many pictures that are too often out of place can be very disruptive to the creation. So even if you don't add this feature, you can still keep unselected images from being hidden, which is probably what many people need.

**Comment by longkinght** [comment]
And everyone knows that AI sometimes generates NSFW pictures, and if it can't be deleted, it will always be there, which is too embarrassing at work. Therefore, there is an urgent need for a deletion function, and it is best to batch delete after multiple selections.

> > It's not possible at the moment.目前还不可能。
> > Out of interest, why do you want to do it manually?出于兴趣，为什么要手动执行？
> > Deleting one by one sounds very tedious. Would you expect of multi-select?一个接一个地删除听起来很乏味。你会期待多选吗？
> 
> When creating something, you only want to see the pictures that are relevant to the original idea, and too many pictures that are too often out of place can be very disruptive to the creation. So even if you don't add this feature, you can still keep unselected images from being hidden, which is probably what many people need.在创作时，你只想看到与原始想法相关的图片，而太多经常不合时宜的图片会对创作造成很大的破坏。因此，即使您不添加此功能，您仍然可以防止隐藏未选择的图像，这可能是许多人需要的。

And everyone knows that AI sometimes generates NSFW pictures, and if it can't be deleted, it will always be there, which is too embarrassing at work. Therefore, there is an urgent need for a deletion function, and it is best to batch delete after multiple selections.

**Comment by nickthesail0r** [comment]
First of all great work.It is possible after krita close to retrieve the prompt history or images generated?

**Comment by Acly** [comment]
@nickthesail0r Yes, open .kra file like a zip, it's in folder your-image-name/annotations/ai_diffusion

**Comment by AnalogKnight** [comment]
Sometimes AI generates horrible, distorted images, and it is usually desirable to remove these images immediately.

**Comment by Acly** [comment]
Done in  [1.15.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.15.0)
