### ISSUE TITLE
[FEATURE REQUEST] support meshgraphormer for hand refining

### ISSUE THREAD

**Issue by jjisnow** [Acly/krita-ai-diffusion#343]
https://github.com/Fannovel16/comfyui_controlnet_aux has just started supporting meshgraphormer hand refiner nodes which fix malformed hands well - can this workflow be supported in ai diffusion as I feel like hands seem to feature as a frequent problem.

**Comment by Acly** [comment]
You saw [latest release](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0)? You mean something beyond?

**Comment by jjisnow** [comment]
No, that's the one!
