### ISSUE TITLE
[Feature Request] Style sub-folders

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#346]
As I am experimenting with different checkpoints and Loras, my list of styles keeps growing.

I organized them under folders. But unfortunately, only the top folder is visible under the drop down.

Would it be possible if the style could scan for sub-folders in the style folder?

If not, would it be possible to provide a config where I could specify where I want the style to be searched?

**Comment by Acly** [comment]
Scanning subfolders is no problem, but it wouldn't automatically reflect in the UI, since that just lists styles by name.

Could list them in menu fashion similar to Lora, but it has some issues, I generally prefer the regular combo box...

**Comment by guzuligo** [comment]
I think there are few simple approaches this could be done.
1- A text box to provide the folder to read from and hit refresh (Empty for default folder)
2- A combo box to choose the sub-folder
3- On the same combobox of choosing the style, the top option is to change the folder and just choose the subfolder to switch to.
4- Treat it like github. i.e. if the name of the style contains slash, it will indicate sub-folder. example [  cats/furrballs.json  ]

**Comment by Acly** [comment]
In [1.15.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.15.0) styles can now be placed outside the plugin install folder, and it will read subfolders. In the UI the filepath displays the sub-folder, but it's still a single combo.
