### ISSUE TITLE
change background photo

### ISSUE THREAD

**Issue by redclif43** [Acly/krita-ai-diffusion#347]
Is it possible to replace the background photo with generate like photoshop generative fill?

**Comment by Acly** [comment]
It's possible, essentially select the background, type a simple prompt and hit Generate.

The defaults for mask expansion are not very good for this scenario though, try to disable "Selection Grow" and "Selection Feather" in Settings (Diffusion tab).

Don't know how quality of results compares to photoshop nowadays, it works pretty well for simple scenarios where there is not much interaction of foreground & background, more complex cases require some luck.

"beach bar" - mostly good results
![easy](https://github.com/Acly/krita-ai-diffusion/assets/6485914/50a6e27d-354c-4814-a7ce-ec3fd4f483c2)

"hawaii" - maybe 1 out of 10
![tricky](https://github.com/Acly/krita-ai-diffusion/assets/6485914/ec021942-726b-47b0-af4a-5fefb00efbb4)

**Comment by redclif43** [comment]
How did you select the background?

**Comment by Acly** [comment]
I used box segmentation tool from here: https://github.com/Acly/krita-ai-tools
to select the foreground. Then inverted the selection.

**Comment by Acly** [comment]
Release [v1.14.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.0) has an explicit option for this now, which chooses a smarter grow/feather, automatically inverts the selection, and chooses an appropriate fill. Results are still mixed, but I think best that can be done without having a specialized model.

**Comment by redclif43** [comment]
> Release [v1.14.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.0) has an explicit option for this now, which chooses a smarter grow/feather, automatically inverts the selection, and chooses an appropriate fill. Results are still mixed, but I think best that can be done without having a specialized model.

wow , thank you for the update
