### ISSUE TITLE
[Feature Request] T2I adapter support

### ISSUE THREAD

**Issue by ryukra** [Acly/krita-ai-diffusion#348]
T2I adapter have better performance and reduced requirements and comfyui natively supports them.

**Comment by ryukra** [comment]
Meanwhile you can just rename the t2i to "sai_xl_sketch_256lora". :)

**Comment by Acly** [comment]
Similar to #321 and #316: I believe there is value in a curated list, but I'm sure it can be improved. Better performance is good, but some T2I I tried were lacking strength, making them less flexible. Maybe this is not the case for SDXL sketch though?
