### ISSUE TITLE
Removing an object using generative AI isn't working.

### ISSUE THREAD

**Issue by shorerez** [Acly/krita-ai-diffusion#35]
I am trying to remove an object (e.g a person) from an image using the AI Image generation plugin but i am getting some strange result as it is filling up the selected area with differing stuff that has nothing to do with the image.
Any idea why is that and how to resolve it?
Thanks,
Erez.

**Comment by Acly** [comment]
It's hard to say. If you could share an image (and maybe the mask area) I can give a more specific answer, and maybe try to improve something.

Some general tips for removing objects:
* If the object is not very prominent and the area relatively small, just 100% strength without text prompt often works.
* If the object is prominent, it probably generates similar objects instead of outright removing. Use a text prompt and describe the background. Try adding unwanted objects as a negative prompt (activate it in Settings > Interface).
* If the background you'd like to see is relatively uniform in color, it can also help to fill/paint the masked area in that color. In that case slightly lower strength (70-80%) can also work well.

I haven't seen wildly different stuff appear, that's somewhat unexpected and so the above tips may not help. Large resolution photos with high complexity (many different things) can be very challenging.

**Comment by shorerez** [comment]
Here is a simple example if i make the selection in the imaged 1.jpg and run the generate without any input (like i do in photoshop) i get output like what you can see in image 2.jpg and not an image without people like i get in photoshop.

![1](https://github.com/Acly/krita-ai-diffusion/assets/21199802/25ecc8eb-a753-41f4-afcf-02d33cbeeb93)
![2](https://github.com/Acly/krita-ai-diffusion/assets/21199802/b5ae66b4-5922-4e46-9c9d-9cfaf8e3269c)

I made some tests with saying what i want to include/avoid in the generated outcome but this didn't solve the problem.
any suggestions?

**Comment by Acly** [comment]
I see, this is not entirely unexpected. The feature fills the selected area with content similar to the existing image to make it blend in. In this case the image is identified as something like "a photo of two people walking in nature" and the AI will work towards keeping it that way. This is problematic if you want to remove objects that are central to the image.

You might expect that masked content will not be part of generation input, but currently it still has an influence. You can avoid this by manually "blotting it out". I ctrl+click the grass to pick a suitable color, create a layer and use fill tool:

![Screenshot 2023-11-06 154201](https://github.com/Acly/krita-ai-diffusion/assets/6485914/a354b923-e0fe-4c5b-8028-c25b728769ca)

Results look (mostly) resonable with a simple prompt, no negative:

![Screenshot 2023-11-06 154701](https://github.com/Acly/krita-ai-diffusion/assets/6485914/2d63aba4-219f-49e6-9761-ba11ce0a9962)

I've been looking into doing that step automatically with a smart solution that works also for images where you can't use a simple plain color. But the module/extension I intend to use is quite new and had some bugs, so I postponed it. I do plan to revisit, as I think it will help for this kind of scenario in particular.

**Comment by bsl3** [comment]
> I see, this is not entirely unexpected. The feature fills the selected area with content similar to the existing image to make it blend in. In this case the image is identified as something like "a photo of two people walking in nature" and the AI will work towards keeping it that way. This is problematic if you want to remove objects that are central to the image.
> 
> You might expect that masked content will not be part of generation input, but currently it still has an influence. You can avoid this by manually "blotting it out". I ctrl+click the grass to pick a suitable color, create a layer and use fill tool:
> 
> ![Screenshot 2023-11-06 154201](https://github.com/Acly/krita-ai-diffusion/assets/6485914/a354b923-e0fe-4c5b-8028-c25b728769ca)
> 
> Results look (mostly) resonable with a simple prompt, no negative:
> 
> ![Screenshot 2023-11-06 154701](https://github.com/Acly/krita-ai-diffusion/assets/6485914/2d63aba4-219f-49e6-9761-ba11ce0a9962)
> 
> I've been looking into doing that step automatically with a smart solution that works also for images where you can't use a simple plain color. But the module/extension I intend to use is quite new and had some bugs, so I postponed it. I do plan to revisit, as I think it will help for this kind of scenario in particular.

I try to do this, but it still wants to replace it with something new, if I justs do it by chunks for example, when I replace a characters head, it creates some new ai head instead, Im using remove content, I just want to get rid of it, even If I color it in
