### ISSUE TITLE
What is ControlNet Stencil?

### ISSUE THREAD

**Issue by NoMansPC** [Acly/krita-ai-diffusion#350]
I'm using my own ComfyUI installation. While going through the missing models, I came across 'Stencil' in Krita. What is it? I looked it up on Hugging Face and couldn't find this specific control net model.

**Comment by Acly** [comment]
aka QR-code-monster
[list of packages](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py#L391-L400)

**Comment by NoMansPC** [comment]
Thanks!
