### ISSUE TITLE
How Start Comfyui local server with --dont-upcast-attention --force-fp16 ?

### ISSUE THREAD

**Issue by motolo** [Acly/krita-ai-diffusion#351]
I wanted to ask how I can start the Comfyui local server with the following parameters 
 --dont-upcast-attention --force-fp16
 They are necessary to correct problems with ipadapter sdxl which otherwise does not work.
 Where can I add such parameters?

**Comment by Acly** [comment]
The plugin folder contains a file `settings.json` which you can open and add those parameters to `server_arguments` entry, eg.
```
{
  ...
  "server_arguments": "--dont-upcast-attention --force-fp16"
  ...
}
```

**Comment by motolo** [comment]
thanks, text immediately

**Comment by motolo** [comment]
I have this error message: empty separator

**Comment by motolo** [comment]
Now it works...I don't know how but it works :) Thanks :) and if anyone encounters problems with ipadapter sdxl this is a solution.
