### ISSUE TITLE
fail install comfyUI ，how to install it manually？

### ISSUE THREAD

**Issue by MinzChan** [Acly/krita-ai-diffusion#354]
ai_diffusion.network.NetworkError: Failed to download https://github.com/comfyanonymous/ComfyUI/archive/d76a04b6ea61306349861a7c4657567507385947.zip: Connection timed out
2024-01-23 14:32:34,252 ERROR Installation failed

**Comment by MinzChan** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/38336434/fab77448-8671-4b77-91fb-eeb90c03ecf4)

Why do I have to close the program after an installation error, and when I re-enter it, I will detect that the directory is not empty again. I create a new directory, and all the files need to be reinstalled, resulting in a dead end loop

**Comment by querecuto** [comment]
same problem here 🤔
