### ISSUE TITLE
Improve SDXL inpaint model support

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#355]
Hello,

Good SDXL inpaint models are starting to become available, like [Inpaint Unstable Diffusers](https://civitai.com/models/272675/yamerinpaint), or [JuggerXL Inpaint](https://civitai.com/models/245423) . Having tested those two, they work like a charm, but the current workflow of krita-ai-diffusion's inpainting is not ideal :  

 - When outpainting, the selection dimension can often be greater than then model dimensions settings, provoking a hires pass, and thus provoking a bug with inpaint models
   - Fixed by temporarily setting a manual dimension to something larger, like 2048
 - The default SDXL inpaint behavior in the plugin is to add a IPAdapter control, which is not really useful, and even detrimental for true inpaint models
   - Fixed by adding a Reference control layer to 0% strength, blocking the auto-IPAdapter to be added
 - I'm not sure how to handle the minimum resolution of the model depending on the selection size, will the context be used to the correct size... to be tested further.

I would recommend to disable the HR pass, the auto IPAdapter layer, and maybe the dimension computation, on any inpaint done with a SDXL _true_ inpaint model. It could either be detected by name `/.*inpaint.*/` or manually set by adding a checkbox in the style definition.

Cheers,

NB : Full ComfyUI traceback for the HR pass bug : 
<details>
  <summary>Click me</summary>

```python
got prompt
Requested to load CLIPVisionModelProjection
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.60it/s]
Requested to load AutoencoderKL
Loading 1 new model
Requested to load SDXL
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\nodes.py", line 1389, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "F:\ComfyUI\nodes.py", line 1325, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 218, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "F:\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\ComfyUI\comfy\samplers.py", line 606, in sample
    positive = encode_model_conds(model.extra_conds, positive, noise, device, "positive", latent_image=latent_image, denoise_mask=denoise_mask, seed=seed)
  File "F:\ComfyUI\comfy\samplers.py", line 502, in encode_model_conds
    out = model_function(**params)
  File "F:\ComfyUI\comfy\model_base.py", line 118, in extra_conds
    denoise_mask = denoise_mask[:,:1]
AttributeError: 'NoneType' object has no attribute 'shape'

Prompt executed in 13.41 seconds
```
</details>

**Comment by Acly** [comment]
These are just merges with diffusers/stable-diffusion-xl-1.0-inpainting-0.1 right?
It would be great to merge them on the fly. The problem with that is it requires the full base & inpaint model in addition to the model you actually want to use, and deploying & loading total 20 GB of models is not fun.
I think Fooocus has a smart way of extracing the diff and merging with that directly, but nobody has backported it to Comfy yet. The code is confusing patchwork so I was hoping someone else would do it ;/

Regarding the issues:
* HR pass: maybe requires InpaintModelConditioning node? Or otherwise disable noise mask? Or is it a problem with area conditioning? In any case I hope it can be resolved and work.
* We can disable IP-Adapter
* Currently minimum size is handled by upscaling prior to diffusion if the expanded context is still too small, which should work. Expanding the context further if possible might be better, but can be evaluated separately.

Detection of SDXL inpaint models: maybe it can be done more robustly similar to [how SD1.5 inpaint models are detected](https://github.com/Acly/comfyui-tooling-nodes/blob/main/api.py#L76)

Generally inpaint models could be supported by giving each style the option to specify an additional model used for inpainting. But to me that's a worst-case last-resort kind of solution, it would be much better if any main checkpoint could simply be used for inpainting too, without the duplication and potential mismatch.

**Comment by Danamir** [comment]
> These are just merges with diffusers/stable-diffusion-xl-1.0-inpainting-0.1 right?

I did try to add the difference of yamer's Unstable Diffusion and Unstable Inpaint to another model, but could not transform it into an inpainting model. It seems that some more work is involved, otherwise inpaint models would be popping everywhere. 😅

> It would be great to merge them on the fly. The problem with that is it requires the full base & inpaint model in addition to the > model you actually want to use, and deploying & loading total 20 GB of models is not fun.

Yeah I'm not expecting the default installation of the plugin to rely on those models, considering the size. It was more of a useful thing for users who download their own models. 

> Currently minimum size is handled by upscaling prior to diffusion if the expanded context is still too small, which should work. Expanding the context further if possible might be better, but can be evaluated separately.

I did some more tests on my ComfyUI inpainting workflows, as the results I got there were much much better. And I see that in fact I do a render pass on the whole image at once, giving the source image and mask as input. So the resolution of the selection becomes irrelevant, and all the base image is used as context. This allow even multiple zones to be inpainted at once. 

It is quite a stretch from the current usage of the plugin. So I don't know how to include this style of full image pass inpainting.

I thinks it should still be possible to do only the rendering on a smaller region than the full picture, but I'm not sure how much context should be padded from outside of the selection.

**Comment by Danamir** [comment]
> Generally inpaint models could be supported by giving each style the option to specify an additional model used for inpainting. But to me that's a worst-case last-resort kind of solution, it would be much better if any main checkpoint could simply be used for inpainting too, without the duplication and potential mismatch.

I'm not suggesting (as long as there is no simple way to transform a model into an inpainting one) to have the inpaint model affecting all the styles. My process was more in the vein of : "if the current inpainting method is not good enough for a particular case, I can switch to my dedicated inpaint style to do a more robust inpainting, then switch back to the original style to refine the render".

Of course the ideal workflow would be to have a custom inpaint model always at the ready as in SD 1.5, but we're not there yet.

**Comment by Acly** [comment]
> I did try to add the difference of yamer's Unstable Diffusion and Unstable Inpaint to another model, but could not transform it into an inpainting model as it did in SD 1.5.

It works fine, same way as creating inpaint models for SD 1.5. They seem to be popping up now, but I don't think much has changed:
* The diffusers inpaint model works but it's not great
* Having a "duplicate" inpaint file for every model you have was a stretch for SD1.5 - for SDXL it's worse because they are much bigger

This can also be done in ComfyUI on the fly already, but it requires 20GB of models which take 1min+ to load.

![mmerge](https://github.com/Acly/krita-ai-diffusion/assets/6485914/c0676038-6ac1-4016-b039-3d60844cbec2)

> but we're not there yet

I think Fooocus solution is pretty good, but needs to be ported.

**Comment by Danamir** [comment]
Nice ! I'll try a comparison with the custom inpaint models, to see if there's something else going on. I was using UnstableInpaint because beeing based on UnstableDiffusers it is capable of imitating a good range of styles. I sure don't want to store one inpaint model per standard model !

**Comment by Danamir** [comment]
I missed the discussion in https://github.com/Acly/krita-ai-diffusion/issues/38#issuecomment-1837556097 , it is exactly what I was looking for when inpainting. I would enjoy an option to simply select if the current selection is to be used in a full inpaint vs. a region, instead of having to manipulate the selection mask to do the growh/feather etc. But its is a good start.

This method of inpainting do a lot of work at once with a complex selection. This was not cherry picker, literally the first inpaint I tried : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/7262d038-dacc-409e-91a8-518b2865c54b)
![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/3d283a9d-8367-4d0e-96ff-5e04d9b56b9c)
![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/028315fd-8d96-4b40-9a59-34825d558f76)

There is still a small bug when applying the mask to the returned image I think, I had to trim a little of the generated layer to get rid of this black fringe : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/51940109-5a35-4658-bda4-095a8ad24f50)

**Comment by Acly** [comment]
Yes the context control is still somewhat unfinished. With a mask like in your example you're always going to get the full image anyway though.

Black fringe like that can also be in the generated image, I have seen that few times. Or it could be a blending bug. You didn't happen to save the workflow?

**Comment by Danamir** [comment]
> Black fringe like that can also be in the generated image, I have seen that few times. Or it could be a blending bug. You didn't happen to save the workflow?

No but I can reproduce the bug every time. It is always present as long as I'm in inpainting mode (ie. 100% strength) I have this fringe. Even when not using the selection mask method. It's visible here, outside the auto padding range :  

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/234d8710-3aa7-49aa-89d6-10bce515d66c)

As soon as I lower the strength to 99% and leave the inpaint method I don't have this issue.

**Comment by Acly** [comment]
Does setting grow_mask_by parameter  of the Encode VAE for Inpaint node to something like 8 help?
You can activate comfy prompt dump now in Interface settings btw., then drag it into ComfyUI for easier experimenting.

**Comment by Danamir** [comment]
> You can activate comfy prompt dump now in Interface settings btw., then drag it into ComfyUI for easier experimenting.

Nice, this is such a good feature !

Yeah the rendered image has a black fringe, and a strange cutoff of the rendering on the feathered region :  

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/569149f1-9f91-40a5-bb09-01dd53c397f9)

With VAE Encore (for Inpainting) growth set to 8, the problems are less prevalent, but still a little present with the weird cut on left and right : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/bedae6dd-4edf-4f46-85a7-55a75f539752)

Here is the [workflow.zip](https://github.com/Acly/krita-ai-diffusion/files/14038003/workflow.zip)

**Comment by Acly** [comment]
I think the fringe comes from fact that inpaint masks are binary (not smooth) in latent. The growth pushes it further out, but of course makes inpaint area bigger, probably have to find a good trade off. Often small values already work well.

< 100% strength doesn't have this problem because it uses smooth noise mask, not inpaint mask, but that  also means it doesn't work with inpaint models

**Comment by Acly** [comment]
It's a bit ugly, but I have something that works now with the Fooocus inpaint model. Just 1.3 GB to patch any SDXL checkpoint with inpaint capabilities. Haven't really experimented much yet, but would appreciate if you could try it too :)

https://github.com/Acly/comfyui-inpaint-nodes

**Comment by Acly** [comment]
Looking good so far.

> You just have to make sure to apply any LoRAs to the model before applying the Fooocus patch, otherwise you got a whole lot of errors and a wrong output :

Yes... anything that modifies the model after the node will break that way. I can fix it by making the lora weight patch global, which is even more invasive. But I guess if it breaks it will break either way, so might as well. Don't see a way of doing it properly without supporting this new Lora type in ComfyUI directly.

I'm also having trouble to get it to work with denoisings < 100% and InpaintModelConditioning node. This works great with the inpaint merges, but not the fooocus patch (there is barely any change).

**Comment by Acly** [comment]
It works if you use the "VAE Encode (for inpaint)" latent to patch the model, and the "InpaintModelConditioning" latent as input for the sampler. Doesn't work when using only the latter.

That means the input image is VAE-encoded twice... which is some overhead.

Is that what you did too?

**Comment by Danamir** [comment]
It may be what I did. I'm not sure, the workflow is on another computer. 😅 I'll try to reproduce it.

**Comment by Danamir** [comment]
You're right, I used the `VAE Encode (for inpaint)` as the patcher input. It's an overhead for sure, but pretty acceptable if we can't find an alternative. It will only be used with lower denoising, and the result will be cached by ComfyUI in many cases (if we don't touch the mask or the source pixels).

I would argue that the inpainting mode should be an option when using the plugin, with associated costs and gains : ie. slower, less style variety and maybe final render quality ; but a much greater coherency overall.

I for one would accept such a small loss of performance, as long as it's not always activated.

**Comment by Acly** [comment]
The overhead can be avoided, but basically requires copying the `InpaintModelConditioning` node and making it return both latents (both with same image latent, only the mask is different). Maybe I will do it later.

I think inpaint model should be default for 100%, for lower denoise it's debatable. It would be nice if the influence of the inpaint patch could be toned down, but modifying the Lora strength does not work (only 1.0 makes sense and I will remove the parameter). Another option would be doing initial sampling with the inpaint model, then switching to the non-patched version.

Btw I updated the repo, other Lora should work now (I hope).

**Comment by Danamir** [comment]
>I think inpaint model should be default for 100%,

Yes in this case of course, I can't see a case where the normal model would perform better at 100% denoising.

> Btw I updated the repo, other Lora should work now (I hope).

Tested ok on my side !

**Comment by Acly** [comment]
I added a bunch of pre-processing options to play around with. Now how to integrate them... I'd like to have some options for basic use cases, like "Add new content", "Expand canvas", "Remove objects", "Change background". But not too many :)

**Comment by Acly** [comment]
Merged now, this was a more work than expected... not everything is perfect but I'm quite happy with the results.
Inpaint model/CN is used for strength > 0.5
IP-adapter only if there is no prompt, and only for "fill" and "expand" modes
And there is a "custom" mode which lets you choose inpaint yes/no, masked conditioning, fill and context size

**Comment by Danamir** [comment]
I played with the new version for a while and inspected the generated workflows. Congratulations, this is some really good stuff !

The "focus" option with conditioning set mask, the quick inpaint with the Places model, the option to apply the foocus inpaint or not, the context choice... everything works perfectly.

Thanks a lot !

**Comment by Acly** [comment]
Thanks for testing!
