### ISSUE TITLE
Allow use of full image for inpainting

### ISSUE THREAD

**Issue by jacobEAdamson** [Acly/krita-ai-diffusion#356]
Right now, inpainting works similar to how automatic's inpaint masked only functionality works. This is great a lot of the time, but sometimes it's tricky to get the inpainted area to match the rest of the picture. Can there be an option to select more of the picture to use during the inpainting process?

This, alongside using controlnet for inpainting, allows the user to inpaint at higher levels of strength, but still have it be consistent with the overall image.

**Comment by ryukra** [comment]
second this, but as an option to specify padding around the selection, higher values will automatically use the whole image

**Comment by Acly** [comment]
This is possible, but rather hidden at the moment: https://github.com/Acly/krita-ai-diffusion/issues/38#issuecomment-1837556097
