### ISSUE TITLE
[Feature Request] Automatically save files

### ISSUE THREAD

**Issue by MDReptile** [Acly/krita-ai-diffusion#357]
I think it would be very time saving to be able to save all the resulting images from batches. Maybe there could be a checkbox alongside the batch options (right side of the generate button) where you could select to save each generated image as a separate file automatically after each batch is generated.

This would be useful and save a lot of time when a good prompt is selected, and large batches are created when compared to saving each single one by clicking the 3 dots and hitting save image.

**Comment by Acly** [comment]
Images are already saved as part of the document, there is no need to save all again into extra files.
