### ISSUE TITLE
[Error] error during server startup

### ISSUE THREAD

**Issue by ceruleandm** [Acly/krita-ai-diffusion#359]
I changed the location of server path before installing
I tried to install this nice plugin but after installed, it showed error during server startup [line 76]

![image](https://github.com/Acly/krita-ai-diffusion/assets/157724179/81e69548-762b-4c06-aa78-918cda2fcc49)

thank you very much

[server.log](https://github.com/Acly/krita-ai-diffusion/files/14054165/server.log)

[client.log](https://github.com/Acly/krita-ai-diffusion/files/14054163/client.log)

**Comment by Acly** [comment]
If you're confused by the long error message, the last part is the important one:
"Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

If you installed with CUDA selected you need a NVIDIA GPU. Or you can switch to CPU (but it's very slow).

**Comment by VkArms** [comment]
I got this problem... what to do?
![image](https://github.com/Acly/krita-ai-diffusion/assets/36528815/80da5346-82ca-451f-80b7-3f08abc5ad41)

**Comment by ceruleandm** [comment]
> If you're confused by the long error message, the last part is the important one: "Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"
> 
> If you installed with CUDA selected you need a NVIDIA GPU. Or you can switch to CPU (but it's very slow).

thanks for replying. I founded that I'm confused and also I found that my laptop use intel iRIS xe Grpahic which is NOT NVIDIA or DirectML. I tried to run on CPU but this one appeared. How can I solved this?

![image](https://github.com/Acly/krita-ai-diffusion/assets/157724179/4a9fe2c8-d7cf-42da-b6c8-76f1e72336d0)

**Comment by Acly** [comment]
See #358 
In short: delete the files in .server/ComfyUI/models/checkpoints and retry with the latest version (1.13.1)

**Comment by KateWhite8** [comment]
![photo_2024-01-29_02-11-28](https://github.com/Acly/krita-ai-diffusion/assets/157999531/5ffb6040-86a2-4a1b-b00e-51afae94e7cd)
У меня такую ошибку выдал. Что это может значить?

**Comment by KateWhite8** [comment]
![photo_2024-01-29_02-11-28](https://github.com/Acly/krita-ai-diffusion/assets/157999531/cf3d12e6-4375-41f7-ba4e-4c3a19c75c09)
I have this problem... What is that means?

**Comment by ceruleandm** [comment]
> See #358 In short: delete the files in .server/ComfyUI/models/checkpoints and retry with the latest version (1.13.1)

It is working well. Thank you very much
