### ISSUE TITLE
[Error] error during server startup

### ISSUE THREAD

**Issue by VkArms** [Acly/krita-ai-diffusion#360]
I tried to install this plugin but after installed, it showed error during server startup
![image](https://github.com/Acly/krita-ai-diffusion/assets/36528815/9519b172-ae4e-468e-bdb8-6a4781ef0ed1)

[client.log](https://github.com/Acly/krita-ai-diffusion/files/14058643/client.log)

**Comment by Acly** [comment]
This indicates that the server is already running, maybe previously started by the plugin and wasn't shut down for some reason. See #196 

You can look for a Python process in task manager and end it manually. Or log off (or reboot) also works.

**Comment by VkArms** [comment]
I got this...
![image](https://github.com/Acly/krita-ai-diffusion/assets/36528815/ca08529b-773a-470d-836c-c39600da94c4)

**Comment by Acly** [comment]
Probably #358
I made a release [v1.13.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.1) which fixes the links, unless you were already using that?

No need to redo the entire install, you can delete the files in `...\.server\ComfyUI\models\checkpoints` and retry

**Comment by VkArms** [comment]
Now what happened?

![image](https://github.com/Acly/krita-ai-diffusion/assets/36528815/411de837-5cee-4566-8433-16060e224073)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14063513/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14063514/server.log)

**Comment by Acly** [comment]
Not sure yet, server.log should contain the full error message but it doesn't. Did you upload the latest version of it?

**Comment by VkArms** [comment]
Yes... The previous error was gone... Thank you...but now this is what I am facing

**Comment by Acly** [comment]
Right, my question was to double-check if the server.log you provided is up to date - I couldn't find the error message there.

**Comment by VkArms** [comment]
Hey... I don't know what just happened but when I came home and opened krita... It worked... I am too happy to have it now... It's amazing and has great potential... Mind blowing 🎉🥳🥳🥳🎉🎊🎊
