### ISSUE TITLE
Unable to freshly install 1.13.1 / 1.13.0

### ISSUE THREAD

**Issue by DrFisura** [Acly/krita-ai-diffusion#361]
A fresh installation of 1.13.1 (or 1.13.0 as I checked) produces this error

![image](https://github.com/Acly/krita-ai-diffusion/assets/113776225/a315e5b1-1eb7-4ce3-ae9a-44311efbdaba)

Therefore the installation halts and the plugin doesn't run

(You see the checkpoints unmarked there because I prefer the solution of symlinking to an external folder where I keep all my checkpoints)

1.10.0 was working just fine for me

**Comment by Acly** [comment]
Which Python/Linux version is this?

**Comment by DrFisura** [comment]
> Which Python/Linux version is this?

The Python version must have been handled by the installer upon installing the dedicated ComfyUI server. I assume there is no interference between the local environment and whatever version I have in the parent. So, I'd say whatever version 1.13.1 chooses upon installing the server? But not sure.

I'm running Zorin OS 16.3 if that's relevant.

**Comment by Acly** [comment]
No external Python is installed by the plugin on Linux, the server will use `python3` installed on the system. It does create a private virtual env to isolate the environment and avoid package conflicts.

The error message essentially states that it could not install [embreex](https://pypi.org/project/embreex/#files) package because it didn't find a version that matched your OS + Python. There are pre-built distributions available for Linux / Python3.6-12 and I haven't had any trouble on Ubuntu, not sure exactly what is causing the mismatch.

**Comment by DrFisura** [comment]
Okay then, my system has Python 3.11.5

**Comment by Acly** [comment]
I ran the UI installer for python3.11 on Ubuntu as a test and it works ok:
```
2024-01-27 22:37:54,821 INFO Collecting embreex
2024-01-27 22:37:54,861 INFO Downloading embreex-2.17.7.post4-cp311-cp311-manylinux_2_28_x86_64.whl (17.0 MB)
```
How are you running Krita? package manager, appimage, flatpack?

Things you can try:
* Does it install manually: `python3 -m pip install embreex`
* Or directly into the venv: `ai_diffusion/.server/venv/bin/python3 -m pip install embreex`
* Or [download the .whl directly](https://pypi.org/project/embreex/#files) and install it:
  `ai_diffusion/.server/venv/bin/python3 -m pip install embreex-2.17.7.post4-cp311-cp311-manylinux_2_28_x86_64.whl`

This should either get it running or clarify why it's somehow incompatible with your system.

**Comment by DrFisura** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/113776225/4ad67f8f-3e33-457b-8165-351a48832bc7)

This is what a fresh plugin installation looks like with the krita 5.2.2 appimage.

Mind me, is there a reason it isn't possible/practical to simply have the plugin go with its own installation of python and every other package? I really don't want to downgrade my system to python 3.8 to run this (and it will probably error out again for some other reason if I try). Is it just because it would be too heavy?

**Comment by Acly** [comment]
This complains that 3.8 is too old. You don't need to downgrade, Python 3.11 is perfectly fine. The reason why the package can't be found is more likely related to how your distribution has set up Python, and bringing a stand-alone Python (if such a thing existed) would run into the same issue.

> Mind me, is there a reason it isn't possible/practical to simply have the plugin go with its own installation of python and every other package?

Stand-alone Python is just not a thing on Linux/Mac. There is a lengthy mailing list where Python devs argue why not, but the gist is:
* no security fixes
* bloat
* (not the linux way)

Unlike Windows, the Linux ecosystem is diverse, and a pre-compiled packaged version may not run on all Linux flavors if distributed like that.  The alternatives are sandbox like AppImage, Flatpak - but it's not really feasible for a plugin. Also distributing a package for CUDA won't work for those without NVIDIA GPU, so many packages required for different OS, GPU, each several GB.

There is one option, if you just want to download the entire server with everything pre-installed for NVIDIA, [docker images are here](https://hub.docker.com/repository/docker/aclysia/sd-comfyui-krita/general). Run with
```
docker run --gpus all -p 3001:3000 -p 8888:8888 aclysia/sd-comfyui-krita:v1.13.0
```
then connect to 127.0.0.1:3000 in Krita.
