### ISSUE TITLE
Errors with server configuration (first time install)

### ISSUE THREAD

**Issue by KateWhite8** [Acly/krita-ai-diffusion#364]
I have this problem - 2 different errors. I tried couple of times to finish this... What is that means?  This is the first time I am trying to use AI Krita. (i even didnt have the Krita before)
![photo_2024-01-29_02-11-28](https://github.com/Acly/krita-ai-diffusion/assets/157999531/f5e5eae9-f5d7-457d-8f50-181d5e983036)
![photo_2024-01-29_15-36-10](https://github.com/Acly/krita-ai-diffusion/assets/157999531/a566f483-6d8d-4daf-be99-e1e7a4c6f09b)

at the moment  i have again the 1st error.

**Comment by Acly** [comment]
1st error: the installation folder must be empty. Probably previous install failed and there are some files left over. Just delete the .server folder to try again.

2nd error: this has something to do with language/character encoding (cyrillic in this case?). Please post client.log file (use View log files), maybe it will give a hint.

**Comment by KateWhite8** [comment]
> 1-я ошибка: папка установки должна быть пустой. Вероятно, предыдущая установка не удалась и остались какие-то файлы. Просто удалите папку .server и повторите попытку.
> 
> 2-я ошибка: это как-то связано с кодировкой языка/символов (в данном случае кириллицей?). Пожалуйста, опубликуйте файл client.log (используйте Просмотр файлов журнала), возможно, это даст подсказку.

thank you, i fixed everything, now have another error, it doesnt change anything or showing this 
![photo_2024-01-29_20-21-11](https://github.com/Acly/krita-ai-diffusion/assets/157999531/ed795990-c946-4e00-a77b-dab5e120781c)

**Comment by Acly** [comment]
Hm that one might be tough. 
Which GPU do you have? 
If you provide server.log, it might give a hint where it's coming from.
This happens for every generation? Also for simple 512x512 canvas, 100% strength?

**Comment by onsoid** [comment]
> > 1-я ошибка: папка установки должна быть пустой. Вероятно, предыдущая установка не удалась и остались какие-то файлы. Просто удалите папку .server и повторите попытку.
> > 2-я ошибка: это как-то связано с кодировкой языка/символов (в данном случае кириллицей?). Пожалуйста, опубликуйте файл client.log (используйте Просмотр файлов журнала), возможно, это даст подсказку.
> 
> thank you, i fixed everything, now have another error, using generate doesnt change anything. Or showing this error ![photo_2024-01-29_20-21-11](https://private-user-images.githubusercontent.com/157999531/300559367-ed795990-c946-4e00-a77b-dab5e120781c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzYyMTAsIm5iZiI6MTcwNjczNTkxMCwicGF0aCI6Ii8xNTc5OTk1MzEvMzAwNTU5MzY3LWVkNzk1OTkwLWM5NDYtNGUwMC1hNzdiLWRhYjVlMTIwNzgxYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQyMTE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGZmZjQzN2ZmNTIxMTg0ZTRlNmVlNWJkOTU1YjUyMjg0YTM5YWQ2NjQ3YTA1YmMyYjNmMDJlNWVlZjRhMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JwNsBaVAG9bNDki1usVrLRXtD5YalOAO2v6bMu9RdJQ)

I have the same problem
![image](https://github.com/Acly/krita-ai-diffusion/assets/41272452/04bb5e05-9368-43b3-9754-e62842148483)
