### ISSUE TITLE
 No module named 'insightface'

### ISSUE THREAD

**Issue by kungful** [Acly/krita-ai-diffusion#365]
return self.fget.__get__(instance, owner)()
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 535, in load_insight_face
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 537, in load_insight_face
    raise Exception(e)
Exception: No module named 'insightface'
![Screenshot 2024-01-29 23-13-01](https://github.com/Acly/krita-ai-diffusion/assets/84950880/2ef7f211-d42e-4a36-8034-7bc582352b87)

**Comment by Acly** [comment]
Are you sure the python you installed insightface for is the python that runs your ComfyUI? If it runs with its own embedded python you need to install it there.

**Comment by MoeWa77n** [comment]
Hello, I struggle with a similar problem since version 1.13. 
I get the following message: 
"Server execution error: "Insight Face must be provided for FaceID Models."

![Screenshot 2024-01-30 214145](https://github.com/Acly/krita-ai-diffusion/assets/129115971/c8beea44-4fcf-4351-8aa1-449c394d9f6f)

Any idea how to solve this? I'm a beginner and would appreciate some advice, thx in advance.
Cheers Moe

**Comment by qlewer** [comment]
So what need to install? Same case and can't understand problem..
