### ISSUE TITLE
Krita freezes when external server stops

### ISSUE THREAD

**Issue by TobiasPharos** [Acly/krita-ai-diffusion#366]
Krita freezes when I close the external ComfyUI server. Even when nothing is generating at this moment.

**Comment by Acly** [comment]
Which OS? Any other information that might be relevant?

I'm closing/restarting external ComfyUI server during development all the time, haven't encountered a freeze yet.

**Comment by TobiasPharos** [comment]
I'm on Windows 10.
The plugin is located on a network drive with a symlink to the user krita directory.
I start a fresh Krita and Comfy in parallel, open an image, connect the plugin with the server and when I close the Comfy command line (even if I did not touch anything else) and Krita freezes.
I use git pull to update the plugin. Do I need to re-download the build for every update?

**Comment by Acly** [comment]
> I use git pull to update the plugin. Do I need to re-download the build for every update?

No you can use git.
You used git submodule to get the websocket repository? The websocket connection is the only thing I can think of that might cause a freeze.
If I close the server, I get `WARNING Websocket connection closed: no close frame received or sent` in client.log. That's expected, do you get the warning or does it freeze before?
If you're inclined to debug a little, try adding more printing/logging to the `listen` function in `client.py`, line 225+

**Comment by TobiasPharos** [comment]
@Acly Thank you for the hint! I forgot to run `git pull --recurse-submodules` with the latest update. Now Krita stays alive after closing the server.
