### ISSUE TITLE
Question: ComfyUI  configuration

### ISSUE THREAD

**Issue by b4zz4** [Acly/krita-ai-diffusion#368]
I'm putting together a configuration that I'd like to reuse with several files (more of 100)

Is there a way to get the project that Krita create in ComfyUI on the server  Or export "workflow.json" from Krita ?

**Comment by TobiasPharos** [comment]
@b4zz4
You may want to follow the discussion here:
#153

**Comment by Acly** [comment]
In the settings there is Interface > Dump Workflow
You will find workflow.json for your last request in the logs folder.

**Comment by sunlin-xiaonai** [comment]
> In the settings there is Interface > Dump Workflow You will find workflow.json for your last request in the logs folder.

hi, acly , i cannot find dump workflow  in krita verserion 5.2.2, can you help me , thx

**Comment by sunlin-xiaonai** [comment]
<img width="623" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/129371884/f6ac7a7c-3575-4754-98db-2b5676e29f9c">
this is my settings
