### ISSUE TITLE
Error with Safetensors

### ISSUE THREAD

**Issue by Jeffsims25** [Acly/krita-ai-diffusion#37]
Nice Plugin.
I sent you a message on your YouTube channel about this error.
My Krita send me this error:

Error during server startup : Traceback (most Recent call last) "C:\...\.server\ComfyUI\main.py", line 69, in import comfy.utils
File "C:\...\.server\ComfyUI\utils.py", line 5, in import safetensors.torch ModuleNotFoundError: No module named 'safetensors' [1]
![SafetensorsErrorIMG](https://github.com/Acly/krita-ai-diffusion/assets/16766028/f38a2630-2b53-4a2d-a41e-f688214893f1)

Could you please help me with this error?

[client.log](https://github.com/Acly/krita-ai-diffusion/files/13274732/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13274735/server.log)

Thank you

**Comment by Acly** [comment]
Thanks for providing the log. I can see that the relevant command was executed, but somehow it didn't do anything (but didn't report an error either). Can you try executing it manually? Open a command prompt and run this line:
```
C:\Users\jeff_\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\Scripts\pip.exe install -r C:\Users\jeff_\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\requirements.txt
```
Maybe it will give a hint. If it just runs normally this should fix the error at least.

**Comment by Jeffsims25** [comment]
I tried twice but nothing happened.
![Github](https://github.com/Acly/krita-ai-diffusion/assets/16766028/7eaa3894-60d2-4163-b6dc-6b2fb1868f1a)
Or was that supposed to happen?

**Comment by Acly** [comment]
No, it's supposed to install stuff, or at least give an error. This explains why automatic install didn't work, but apart from that it's quite confusing. Especially since pip worked fine for the other packages.

Can you try:
```
C:\Users\jeff_\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe -v -m pip install -r C:\Users\jeff_\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\requirements.txt
```

**Comment by Jeffsims25** [comment]
Uhhhuuu!!!
Thank you my friend! Now this worked.
I hope this helps you fix future bugs on other people's machines!

**Comment by alea123** [comment]
i have the same issue... i installed all of the stuff but the launch fails because of safetensors

![grafik](https://github.com/Acly/krita-ai-diffusion/assets/11518254/6b3290d0-e356-4ec2-9acd-8a77647d5eb6)

**Comment by Acly** [comment]
Please share your client.log file (find it by clicking View log files). It helps to check what happened with the step that was supposed to install safetensors.

**Comment by alea123** [comment]
Hi and sorry I missed the logs :/

[client.log1.txt](https://github.com/Acly/krita-ai-diffusion/files/13422688/client.log1.txt)
[server.log1.txt](https://github.com/Acly/krita-ai-diffusion/files/13422689/server.log1.txt)

**Comment by Acly** [comment]
Thanks. It looks like you
* started installation in the default path first, and safetensors was installed there successfully
* moved to a different location (to fix issue with windows too long path? I still need to look into that...)
* continue installation in the new path

Technically I would expect that to work, I have moved the folder before, but maybe it caused the issue.
You can try to open a Command Prompt and run
```
"D:\Programme\Installiert\Krita (x64)\ComfyUI\python\python.exe" -m pip install -r "D:\Programme\Installiert\Krita (x64)\ComfyUI\ComfyUI\requirements.txt"
```
to install safetensors (and other requirements) specifically. Let me know the output if it doesn't work.

Otherwise can also try reinstalling on an empty folder - you will have to download a lot of stuff again, but apart from the folder switch everything seems to work fine.

**Comment by Acly** [comment]
It really does look like Python can't find the modules that were installed prior to the folder move.

The command for torch with CUDA is:
```
"D:\Programme\Installiert\Krita (x64)\ComfyUI\python\python.exe" -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
```
In case you're wondering, how many more after that... I do think that should be all :)

**Comment by alea123** [comment]
Thank you! That worked!

After prompting the command above the first start did not work so I restarted krita and tried again, which was successful!

Thank you @Acly and have a nice day!

**Comment by Herealert** [comment]
Hi! : ) Same problem, only more errors show up : /
<img width="614" alt="Captura de pantalla 2024-02-29 131611" src="https://github.com/Acly/krita-ai-diffusion/assets/161719004/7ea77011-1b99-4c1a-bc26-05cb944d8b90">

**Comment by Herealert** [comment]
here the log files:
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14447771/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14447772/server.log)
