### ISSUE TITLE
I installed the plugin, but I can't generate or use live

### ISSUE THREAD

**Issue by onsoid** [Acly/krita-ai-diffusion#371]
![image](https://github.com/Acly/krita-ai-diffusion/assets/41272452/9e4d9cea-972d-4f7e-90b5-821f40ed9e9f)

this is my graphics card
![image](https://github.com/Acly/krita-ai-diffusion/assets/41272452/9a3ddee6-a74a-4122-a12d-66d05e70c2eb)
I updated the PyTorch version

**Comment by Acly** [comment]
I suspect it will not work with a MX110
