### ISSUE TITLE
Dear friends, I want an image2image LCM workflow

### ISSUE THREAD

**Issue by yuegu2401** [Acly/krita-ai-diffusion#373]
Dear friends, I want an image2image LCM workflow that you have built-in, because I want to use it alone on comfyUI! Hope for your help, thanks

**Comment by Danamir** [comment]
Since the last version, you have an option to export the workflow used by the last action of the plugin in the log directory. This will provide you a basic workflow to use in ComfyUI.

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/727e61bf-e41c-4d9c-a0c6-38082c3ddd7d)

**Comment by yuegu2401** [comment]
krita AI's json file is saved, but why can't it be opened?
&nbsp;


番茄鸡蛋汤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月7日(星期三) 晚上7:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Acly/krita-ai-diffusion] Dear friends, I want an image2image LCM workflow (Issue #373)





 
Closed #373 as completed.
