### ISSUE TITLE
model gets reloaded after upscaling

### ISSUE THREAD

**Issue by ryukra** [Acly/krita-ai-diffusion#377]
After upscaling it seems the model will be loaded again? Even if its the same model for upscaling.

**Comment by Acly** [comment]
Uhm, possibly? Upscaling [loads the image first](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/workflow.py#L938-L939) while other workflows load the model first, flipping it might avoid the reload.

**Comment by ryukra** [comment]
that worked
