### ISSUE TITLE
Server execution error: Padding size should be less than the corresponding input dimension (during upscaling)

### ISSUE THREAD

**Issue by yhslai** [Acly/krita-ai-diffusion#378]
I keep getting this error during upscaling images.

![image](https://github.com/Acly/krita-ai-diffusion/assets/538696/03012b1a-aa51-49cd-95a3-ebe5d3025655)

I have no idea what it means. Neither `HAT_SRx4_imagenet_pretrain` nor `Real_HAT_Gen_resharper` works.

**Comment by Acly** [comment]
It's related to the resolution.
Workaround: increase canvas size to eg. 600x908, or use a different upscaler (not HAT)

It's an issue with how ComfyUI divides the image into tiles, probably needs to be fixed there.

**Comment by yhslai** [comment]
What's special about 600x908?

**Comment by Acly** [comment]
Only that 908-4*(256-32) is 12 which is fine and using 900 you get 4 which is not :)

But this was fixed in ComfyUI just now, so if you're running the server yourself you can update and it should work.
