### ISSUE TITLE
Feature: Other types of upscaling diffusion

### ISSUE THREAD

**Issue by ryukra** [Acly/krita-ai-diffusion#382]
There are more nodes like UltimateSDUpscale that work quite well:
https://github.com/shiimizu/ComfyUI-TiledDiffusion
and
https://github.com/BlenderNeko/ComfyUI_TiledKSampler

**Comment by Acly** [comment]
I'm also not a fan of UltimateSDUpscale.

Do you have comparisons? Same images upscaled with different methods, also how much time does it take.

**Comment by ryukra** [comment]
tiledK sampler is like ultimateSDupscale but better, while uSDupscale goes tile after tile, tiledk sampler switches between tiles each step so the tiles know more from the other tiles eliminating seams

tileddiffusion splits the image and vae in tiles and diffuses the image as a whole

**Comment by Kaharos94** [comment]
@Danamir You have to use the tiled Vae that comes shipped with it.

https://ibb.co/JHnVjMr  https://ibb.co/gSmNRZN these is done with the Tiled sampling - Github won't let me upload more than 10MB. Workflow is pretty much inital gen -> 2x OmniSR , Tiled sample -> 2XomniSR -> Tiled Sample. Could be done in one step, though quality is a little higher with two.  Not a direct comparison, but it does help a little to see what it can do. 

This workflow takes around 500 sec on a 3060 - seems long, but for that res it's somewhat expected. For 3072 x 1728 it's taking around 5sec / it , though that can be probably finetuned by changing the settings of tiled diffusion ; my current ones are pretty default at : 
method : mixture of Diffusers
tile_width:1024
tile_height:1024
tile_overlap:32
Tile_batch_size:8

**Comment by Danamir** [comment]
> @Danamir You have to use the tiled Vae that comes shipped with it.

Ok that makes sense. 

That's much better, I can do a 4806x3584 picture in just under 2 minutes with a 3070Ti. I adjusted the Tiled VAE Decode tile size to 1536 for a good speed boost, and without the fast mode otherwise there are some artefacts. It depends of your available VRAM of course.

**Comment by Acly** [comment]
Closing because UltimateSDUpscale is no longer used. The current solution creates individual prompt (CN, IPA) setups for each tile, which integrated solutions don't support.
