### ISSUE TITLE
Double preview on first render

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#389]
When doing the very first render on a new image, or after opening one, the render results in two preview layers thus preventing the display/hide by clicking the render thumbnail (prompt : "a bird") : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/59445977-d8d3-4194-9558-5d64c6c68b9c)

The next renders are alright (prompt "a cat") : 

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/57441219-179b-4a38-9241-79659c7ef26e)

But of course to get the normal behavior back you have to delete the redundant preview layer.

**Comment by Danamir** [comment]
Forgot to mention, this is on the [latest commit](https://github.com/Acly/krita-ai-diffusion/commit/6ef0d7e7ba79f5a7b6238a2d88a95bd7357947c4) from today, not the latest release.

**Comment by Acly** [comment]
Ah indeed I didn't notice that, looks like two selection events are emitted...
