### ISSUE TITLE
outpainting error

### ISSUE THREAD

**Issue by jlitz** [Acly/krita-ai-diffusion#39]
when I select an area to outpaint

Error; {'type': 'prompt_outputs_failed_validation',
•message': 'Prompt outputs failed validation',
'details': 'extra _ info': O} (Error transferring http://
127.0.O.1:8188/prompt server replied: Bad Request)
[url=http://127.O.O.1:8188/prompt, code=302]

generation works

**Comment by Acly** [comment]
Can you share your server.log? Find it in Settings > Connection > View log files. That would give me some more information on what failed.

How are you outpainting? Currently you have to extend the canvas explicitly before selecting new regions and generating. I usually do that with the crop tool (press C and click somewhere inside the image to adjust).

**Comment by jlitz** [comment]
There is no Connection>View Log files under Settings but  found the logs in
C:\Users\jlitw\AppData\Roaming\krita\pykrita\ai_diffusion\.logs and attached the logs
.
I used the select tool.  I do not know what extend canvas explicitly  means. image >resize canvas?

[client.log](https://github.com/Acly/krita-ai-diffusion/files/13295325/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13295326/server.log)

**Comment by Acly** [comment]
> image >resize canvas?

That will work. Or use the crop tool to do the same thing (it allows you to drag the canvas border and make it bigger, not just smaller).

Using only a selection outside of the canvas doesn't work at the moment. But I'll think about making it work, it sounds convenient, the only problem is that it's also common to inpaint a region at the border and draw the selection a bit outside the canvas - in that case you don't want the canvas to be extended.

The error you got is unrelated though: an extension was updated yesterday and is no longer compatible. I will have it fixed later today.

**Comment by jlitz** [comment]
Ok  Does the plug in auto update or reinstall required?

**Comment by Acly** [comment]
You update the plugin the same way you installed: download the zip and extract. You can overwrite existing files. The server doesn't have to be reinstalled.

You can try the latest development version which includes the fix: https://github.com/Acly/krita-ai-diffusion/archive/refs/heads/main.zip

I will make a new release in the next few days after wrapping up feature work and some more testing.

**Comment by jlitz** [comment]
Ok good  work  Great addition to Krita.   Krita has some  install scripts under tools I noticed , install from file works ok,  although the install from web site  i got an error message

**Comment by Acly** [comment]
The install from website might work with link to release zips, but not with just github link I think. But I don't find them super useful since you have to restart Krita anyway.
