### ISSUE TITLE
slow down when previewing and applying generations at high resolution

### ISSUE THREAD

**Issue by chrymium** [Acly/krita-ai-diffusion#391]
i experience substantial slowdowns when previewing and applying generated images at medium to high resolutions (2k - 4k+). Krita hangs for a bit when i click on a preview in the plugin docker and it takes about 10+ seconds to display on the canvas. is there a way to mitigate this? this does not happen at lower resolutions (800x1200 is my default for starting to generate images).  Generation itself does not take as much time if the generated area is not too large, but slowdowns happen when previewing and applying the image. 

Krita 5.2.2, plugin version 1.13.1, local install of ComfyUI running on Windows 10

**Comment by Acly** [comment]
10+ seconds is very unusual, I have to go to 8k+ to get any kind of noticeable hang.
Is it possible you are running out of RAM (not on GPU, just system memory)? If the OS has to start swapping it might explain the huge delay...

**Comment by chrymium** [comment]
i have 64GB of system RAM and krita is set to using half of that. i also am running comfyUI on a 3080 10GB, if it matters. I don't run  up on my limits when generating images, even with projects containing hundreds of layers at 4k (i end up using about 5GB according to Krita). merging the layers down so i have a smaller RAM usage doesn't seem to help.

**Comment by Acly** [comment]
64GB should be plenty. Having a ton of layers (possibly with some effects/transformations) might be something that affects it, but if you tried with flattened I guess it can be excluded as source for the problem too. Though just to be sure I'd test it with a blank document if you haven't already.

If you know a bit of python you can try to log/experiment with [set_layer_content](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/document.py#L260-L269), I assume the `self._doc.refreshProjection()` is what's causing the delay, but I can only guess blindly

**Comment by chrymium** [comment]
i tested on a flattened version of the image, and previewing and applying is much faster now, as fast as on a blank new canvas. i guess it was all the layers and adjustments i had before. this does mean that going forward i'll have to periodically flatten images along with incremental saving, but honestly i don't mind too much

**Comment by chrymium** [comment]
okay, i think I've pinpointed the problem: layer filter masks and/or filter layers. even one on a layer causes a noticeable slowdown.

**Comment by Acly** [comment]
Okay those can be quite slow depending on what you do (like large radius filter). Technically it shouldn't be needed to recompute them if something is added on top. So it's probably caused by the plugin refreshing everything. If I don't do that the image doesn't update at all though. I will try another way that looks a bit hacky, but promising

**Comment by Acly** [comment]
Should work a lot better in [1.14.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.1) now
