### ISSUE TITLE
More lines for prompt

### ISSUE THREAD

**Issue by KalleLeskinen** [Acly/krita-ai-diffusion#393]
Currently you can get up to 2 lines for positive prompt, It'd be great to select more and ability to enlarge the negative prompt also similarly. 

currently there is so much dead space

![1707397684](https://github.com/Acly/krita-ai-diffusion/assets/15031148/eaf0efe9-1ae6-490a-b943-e2e4d5665e99)

**Comment by KlenM** [comment]
I'm pretty sure there is an option in the settings to set the number of lines for a positive prompt.

**Comment by Rogal80** [comment]
Hi , but not in Live mode :(

**Comment by KalleLeskinen** [comment]
> I'm pretty sure there is an option in the settings to set the number of lines for the positive prompt.

https://github.com/Acly/krita-ai-diffusion/assets/15031148/9aad98e2-374f-4c77-b71b-1298b4d369f0

 the button doesn't work but if you type it it works. got more lines now thanks
