### ISSUE TITLE
Custom styles lost when upgrading the plugin

### ISSUE THREAD

**Issue by SteffenDuenner** [Acly/krita-ai-diffusion#394]
I usually update this amazing plugin by using Tools > Scripts > Install Python Plugin from File...
And in my state of euphoria for new features I always forget to backup my custom styles. They get deleted / overwritten by the default ones.
Is it just me (I have to backup them before upgrading and not be so stupid) or is there a workflow that keeps them?

**Comment by Acly** [comment]
The recommended way is to unzip into the plugin folder and overwrite existing files. You usually don't need a "clean" reinstall that deletes everything first. But I also didn't know that the "Install Python Plugin from File..." does that.

I kind of regret putting the styles/settings/server in the same folder, good if you want to uninstall, but not so great for updating...

**Comment by Acly** [comment]
Changed in  [1.15.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.15.0) so pre-installed styles are in `.../krita/pykrita/ai_diffusion/styles` and user styles are created in `.../krita/ai_diffusion` (outside of plugin install). You'll still have to migrate the styles manually one last time though :)

**Comment by SteffenDuenner** [comment]
This is awesome. Thanks a lot!
