### ISSUE TITLE
My Krita send me this error:

### ISSUE THREAD

**Issue by GiovanePSimoes** [Acly/krita-ai-diffusion#399]
![Captura de tela 2024-02-09 220442](https://github.com/Acly/krita-ai-diffusion/assets/13972799/943c0e3f-282b-443a-b2c1-11b4df85a8f7)

[client.log](https://github.com/Acly/krita-ai-diffusion/files/14227339/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14227340/server.log)

**Comment by Acly** [comment]
Last part of the error message: "Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

Since it is set to "Use CUDA (NVIDIA GPU)" you will need one with recent drivers installed.

**Comment by GiovanePSimoes** [comment]
My video card is AMD and not NVIDIA, Radeon RX 570. I can't install these drivers

**Comment by Acly** [comment]
You'll have to change to DirectML (instead of CUDA) and reinstall
