### ISSUE TITLE
Remote server https and wss not supported

### ISSUE THREAD

**Issue by gergelyszaz** [Acly/krita-ai-diffusion#4]
I am running comfy ui on a cloud server and it exposes only https and wss.

This can be easily resolved by editing client.py and network.py. A checkbox or dropdown list to choose between secure connection would be the simplest.

https://github.com/Acly/krita-ai-diffusion/blob/8e14748df6d2c0ee0255882b715f3dfa2e0ad7be/ai_diffusion/client.py#L110
https://github.com/Acly/krita-ai-diffusion/blob/8e14748df6d2c0ee0255882b715f3dfa2e0ad7be/ai_diffusion/network.py#L65

**Comment by Acly** [comment]
Did you try this and it worked by just changing protocols to https/wss? That would be nice.

I'd also be interested what kind of cloud service you used or was it self-hosted?

**Comment by gergelyszaz** [comment]
Yes, no problem afterwards (only my idiocy by copying the clientid from the browser and wondering why it breaks).

I'll try to send a pr later today to check https first and fallback to http if not available.

I used runpod.io by the way.
