### ISSUE TITLE
Feature Request  setting to point to installed  models

### ISSUE THREAD

**Issue by jlitz** [Acly/krita-ai-diffusion#40]
not sure  where models are  stored, but like automatic  1111, it  may be a good idea  to have a setting to point  to where models are already downloaded..     This guy did a video on adding styles fwiw   https://www.youtube.com/watch?v=_1pCKODmF70

**Comment by Acly** [comment]
There are two ways to manage the ComfyUI server used by the plugin.

1. You let the plugin install & handle the server. In that case you can find and open locations for models using the buttons in the UI.
![folder-store](https://github.com/Acly/krita-ai-diffusion/assets/6485914/d8be3f07-6994-4b5d-bcd3-fd2a26d0a0d5)

2. You manage it yourself and only enter the URL to connect. This gives you freedom to change paths and share them with other tools like auto1111. You do this by [renaming & editing extra_model_paths.yaml](https://github.com/comfyanonymous/ComfyUI#how-do-i-share-models-between-another-ui-and-comfyui).

You could also use a symbolic link to point to a central location where models are stored.

I'm not planning to add more path configurability for the plugin-managed server option - it's already very time consuming to maintain and test.

**Comment by jlitz** [comment]
OK  tnx the extra.model.path option works

**Comment by Acly** [comment]
The folder icons don't show in case you use a URL to connect, since the path is unknown and the server might be on a different machine / in the cloud.
