### ISSUE TITLE
Feature Request: Saving prompt presets

### ISSUE THREAD

**Issue by AnalogKnight** [Acly/krita-ai-diffusion#402]
Scenario Example:
If I have two characters in my screen, I now want to have the AI improve each of those characters.
Suppose character 1 is a woman, wearing a dress, and character 2 is a man, wearing a suit. Then I may need to enter the following prompts for each:
1. female, dress
2. male, suit
If I improve character 1 first and then character 2, and if I realize later that character 1 is not perfect, then I need to clear the prompts and re-enter them.

If I could save prompt presets (following the .kra file) this would be a lot easier, especially since precise descriptions of content usually require dozens of prompts. While I could keep track of prompts with the help of an external notepad, it would be difficult to manage them as the work grows.

**Comment by daniel-richter** [comment]
You can [recall the prompt](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0) for each generated image - why doesn't that solve your problem?

**Comment by AnalogKnight** [comment]
> You can [recall the prompt](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0) for each generated image - why doesn't that solve your problem?

Thank you for your reply. If I'm debugging the right prompt, the generated images might be in the dozens. Finding and applying the prompts I want in such a long list could go wrong, maybe will accidentally select the wrong image.

**Comment by daniel-richter** [comment]
Additionally, the layer name of the applied generation consists of the used prompt.

**Comment by Acly** [comment]
Regions (v1.18.0) can now be used to switch between multiple prompts in the same image.
