### ISSUE TITLE
Inpainting probably does not respect clip skip override (version 1.14.0)

### ISSUE THREAD

**Issue by Molch5k** [Acly/krita-ai-diffusion#406]
I noticed this issue while using the model [Pony Diffusion XL V6 (V6 Turbo DPO merge)](https://civitai.com/models/257749?modelVersionId=298112). It is an SDXL Turbo based model that requires clip skip 2 and only produces noisy blurs when set to clip skip 1.
It works fine when generating or refining an entire picture, with no selection.

Example of a picture generated without selection and with clip skip 2. It's not a good picture, but everything works.
![working](https://github.com/Acly/krita-ai-diffusion/assets/159817572/418e2b65-5523-4c7a-98e8-f3d4659257c4)

Same picture, except now with a selection to change that ugly head. The inpainting result is a blurry mess.
![inpaint](https://github.com/Acly/krita-ai-diffusion/assets/159817572/3ab1cc55-8982-4444-9d13-ff15f6a42fdf)

For comparison, this is the expected kind of blurry mess the model always generates with clip skip set to the default 1.
![clip skip 1 for reference](https://github.com/Acly/krita-ai-diffusion/assets/159817572/f9a8e5ef-e9f6-40cb-bd8b-0c4bbbb24af8)

Inpainting works fine with regular SDXL Turbo, so I assume that the issue here is the clip skip setting using the default value of 1 for inpainting. It's probably barely noticeable with models that don't absolutely require clip skip 2.

**Comment by Danamir** [comment]
Sadly, any Pony 6 based model is incompatible with the current inpainting merge methods ; either manually or with Fooocus method. I could not achieve a correct inpainting with any clip skip, or sampler choice on a custom ComfyUI workflow. The patching seems to mess the CLIP used by Pony Diffusion.

**Comment by Molch5k** [comment]
I see. Thanks for the workaround. I'll close this then, since the issue is model-specific and not with the clip skip.
