### ISSUE TITLE
Can't use Refenece Images on an AMD RX 6750 XT

### ISSUE THREAD

**Issue by Tofi-Dev** [Acly/krita-ai-diffusion#413]
OS: Windows 11 Pro
CPU: AMD Ryzen 5 5600
RAM: 32GB
GPU: AMD RX 6750 XT

Issue:
You can't use refenece images using an AMD GPU.

![image](https://github.com/Acly/krita-ai-diffusion/assets/52051567/eb6e5d6e-b151-47a3-855d-187528620588)

**Comment by Acly** [comment]
Yes that's why it says not supported... see comment about AMD GPU [here](https://www.github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108)

**Comment by Tofi-Dev** [comment]
Oh :(
