### ISSUE TITLE
ControlNet causes infinite server update loop in Live Mode

### ISSUE THREAD

**Issue by fiveSevenFive** [Acly/krita-ai-diffusion#414]
When using Live mode with ControlNet on certain types, (Scribble is one of them), Krita starts stuttering heavily.

In the task manager, Krita stays at high CPU usage during this, and the server log shows that it is constantly receiving new requests, and is stuck in an endless loop. See the attached files to reproduce the issue.

Thanks in advance for taking a look at this! This plugin is fantastic!

[server.log](https://github.com/Acly/krita-ai-diffusion/files/14317505/server.log)
[Test.zip](https://github.com/Acly/krita-ai-diffusion/files/14317507/Test.zip)

**Comment by Acly** [comment]
The looping is normal, there is no good way to check if the image has changed so it is updated constantly. On top of that both the scribble layer and what's underneath are required as inputs for generation, which requires recomputation of the canvas. The pattern FX maybe adds to the load too.

I plan to detect if there are no changes a bit earlier so it doesn't have to be sent to the server. And probably the polling rate should be restricted a bit more. But it will still be necessary to get the input image without the scribble on top to check it for changes, and I'm not sure how to improve that.

**Comment by fabiotgolo** [comment]
Just pause the Live after use it.

**Comment by fiveSevenFive** [comment]
Aha, that makes sense. A great feature for live mode would be to have an option to refresh only on a hotkey press, for those of us out there who use heavy clone layers and layer styles for our ControlNet setup. I prefer the workflow of live mode over generate for my purposes, but the constant updating on heavier layer setups is an issue for me.

Just something to consider. I might try adding this feature locally if you point me to the right place. Thanks for the quick response!

**Comment by Acly** [comment]
You can set hotkey for triggering generation in Krita's hotkey settings.

That being said... I checked and it doesn't work for live. [Modified actions.py to fix](https://github.com/Acly/krita-ai-diffusion/commit/32dd5b37b06b5d46c320172ba6fd04286f413f01#diff-4b5b7c0e682bea251554229f25ca40199f726a1ca3ea1d52078be4fb02236233)

**Comment by Acly** [comment]
In [version 1.16.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.0) the request are now no longer automatically sent to the server, it only checks for changes. I'm not sure if this fixes your issues. It's possible the local check was a problem, but for me it only needs very tiny % of CPU.

The polling rate is set to 100ms at the moment (easy to change in code, but no UI unless it's required).
