### ISSUE TITLE
How to use sdxl's checkpoint in version 1.14.0

### ISSUE THREAD

**Issue by Fox1985CLB** [Acly/krita-ai-diffusion#417]
Dear Author, 

I have tried to install the latest plug-in version, and the current 1.5 model is fine, but the sdxl model shows that the workload has not been installed. Can you also tell me how to solve it~

Thanks a lot.
![20240219162635](https://github.com/Acly/krita-ai-diffusion/assets/156494515/00f9ecdf-585f-426f-ad9f-54352c6b895e)

**Comment by Acly** [comment]
If you used the installer, it should work by checking and installing the SDXL workload package. 1.14.0 introduce additional files so it might be need even if you already installed it.

**Comment by Fox1985CLB** [comment]
Please let me know how I can install the additional workload. Thank you very much :)

**Comment by Acly** [comment]
I mean select it here and install
![Screenshot 2024-02-19 115412](https://github.com/Acly/krita-ai-diffusion/assets/6485914/5553ebd9-e234-455c-9b47-b0516745e2d5)

**Comment by Fox1985CLB** [comment]
The problem has been solved. Thanks for your help

**Comment by yxf551** [comment]
If you have exhausted all of the above and still have not solved the problem, copy the ip-adapter_sdxl_vit-h.safetensors file to \ComfyUI\models\ipadapter

**Comment by Shock-stcak** [comment]
> 我的意思是在这里选择它并安装 ![截图 2024-02-19 115412](https://private-user-images.githubusercontent.com/6485914/305924407-5553ebd9-e234-455c-9b47-b0516745e2d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDI5OTgsIm5iZiI6MTcxMzU0MjY5OCwicGF0aCI6Ii82NDg1OTE0LzMwNTkyNDQwNy01NTUzZWJkOS1lMjM0LTQ1NWMtOWI0Ny1iMDUxNjc0NWUyZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTYwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZiMTcxZjQ0NmEzMDkyZjkxNWY2ODA1ZTlmNjFhNmJhMGVkOGY4MjI1M2JjZjkzMTEzMDYwYjgxMjg0ZWQ0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.piY5cTHShzLtr1PfyM7x3U3NJQ2kbyONIrbmDt3d1rI)

This is to install the tarnished package or the lor file
