### ISSUE TITLE
[Feature Request] please add recolor。

### ISSUE THREAD

**Issue by gmf1982** [Acly/krita-ai-diffusion#418]
Hello, can you please add a recolor function? I think this function is very useful for black and white photos. I achieved it by modifying resources.py, but it is very troublesome to modify it every time I update it. It would be great if this function can be added to the next version! 
Thank you so much！ 
![Snipaste_2024-02-19_18-21-07](https://github.com/Acly/krita-ai-diffusion/assets/130820234/9504d8a3-d61b-4a6f-9ed0-38f60bdcbdf8)
![Snipaste_2024-02-19_18-20-52](https://github.com/Acly/krita-ai-diffusion/assets/130820234/046b0ab4-b1b0-4078-b733-cd7af3fe6cc0)

**Comment by Acly** [comment]
Moved to watchlist #779
