### ISSUE TITLE
Wrong checkpoint version

### ISSUE THREAD

**Issue by jccluaviz** [Acly/krita-ai-diffusion#421]
Having some troubles with checkpoints like OpenDalle 1.1 or Proteus V.03.

Those checkpoints are SDXL but are identified like 1.5. This way, when i try to use some controlnet, gives me an error.

OpenDalle was working right till now.

Any clue ? A problem with Comfyui ?

Thanks you.

**Comment by Acly** [comment]
Using a custom comfy install? Was it an update that broke it?

Basemodel version is identified via http://127.0.0.1:8188/etn/model_info - you can try while ComfyUI is running and check the output.

**Comment by jccluaviz** [comment]
Thank you very much for your response.

Yes, using a custom portable version of ComfyUI installed with Stability Matrix.

Really don't know if was an update. Maybe.

I got this error when i use link you gave me :

{

  *     "error": "detect_unet_config() takes 2 positional arguments but 3 were given"

}

I tried while ComfyUI was working.

Tried the OpenDalle checkpoint, but also with SDXL 1.0.

Many thanks for your response.

________________________________
De: Acly ***@***.***>
Enviado: martes, 20 de febrero de 2024 9:54
Para: Acly/krita-ai-diffusion ***@***.***>
Cc: jccluaviz ***@***.***>; Author ***@***.***>
Asunto: Re: [Acly/krita-ai-diffusion] Wrong checkpoint version (Issue #421)


Using a custom comfy install? Was it an update that broke it?

Basemodel version is identified via http://127.0.0.1:8188/etn/model_info - you can try while ComfyUI is running and check the output.

**Comment by Acly** [comment]
I see, it no longer works with latest ComfyUI.

I just added support to [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes), please update the custom node and try again!

**Comment by jccluaviz** [comment]
Ohhhh. Worked like a charm !!!

Many thanks its all ok again.

Thought my Comfyui was up to date.

You are awesome man.

Many, many thanks.

**Comment by Acly** [comment]
It was _too_ up to date, that was the problem :)
