### ISSUE TITLE
Allow system-wide installation

### ISSUE THREAD

**Issue by berolinux** [Acly/krita-ai-diffusion#422]
Currently, installing the ai_diffusion module into the system wide plugin directory (e.g. `/usr/share/krita/pykrita`) doesn't work, because the plugin insists on creating .logs and settings.json inside its own installation directory.
It would be nice (avoiding duplication on systems with multiple users as well as allowing distros to preinstall the plugin) if the plugin detected this and created logs and settings.json in a per-user directory even if the plugin is installed globally.

**Comment by Acly** [comment]
Should work now with [1.15.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.15.0)
