### ISSUE TITLE
Krita can't read the 1.5 model.

### ISSUE THREAD

**Issue by Jay3Design** [Acly/krita-ai-diffusion#427]
![微信截图_20240224160554](https://github.com/Acly/krita-ai-diffusion/assets/135821002/f25b085c-20f2-4757-905e-e9fef05fcef9)
![微信截图_20240224160528](https://github.com/Acly/krita-ai-diffusion/assets/135821002/a1505aec-ea58-462a-9084-efccd1b5006e)
After upgrading to version 1.14, krita can't recognize the 1.5 model, but can only use the XL model. Other functions can be used normally. What's wrong with it?

**Comment by Acly** [comment]
Custom ComfyUI? Probably [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes) is too old. See https://github.com/Acly/krita-ai-diffusion/issues/267

**Comment by Jay3Design** [comment]
Thanks for the answer! I neglected to update the plugin myself, and it's working fine now!!!! Thanks again!!!
