### ISSUE TITLE
[Feature Request] Stable Cascade

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#429]
[Specifically this sort of hybrid](https://www.reddit.com/r/StableDiffusion/comments/1ay1x2q/comment/krvwk4a/?utm_source=share&utm_medium=web2x&context=3) or better yet an option to just use the current workflow loaded in comfyui

**Comment by Acly** [comment]
It's looks quite resource heavy & convoluted? Anyway there is already #411 for cascade, #385 for custom workflow
