### ISSUE TITLE
Error: No checkpoints found!

### ISSUE THREAD

**Issue by nakanakapoi** [Acly/krita-ai-diffusion#43]
I got the following error when running Version 1.6.0, on krita 5.2.1, when connecting to external server.

Error: No checkpoints found! Checkpoints must be placed into ComfyUI/model/checkpoints.

All my checkpoints are in different folder via extra_model_paths.yaml. I tried putting a checkpoint in the location mention in the error message, but the error remains. The issue is resolved when I revert back to v1.5.0.

**Comment by nakanakapoi** [comment]
Curiously, this only happen to one particular server. I connect to another server, and it work fine. There is no significant different in comfy set-up between them other than that the problematic server has comfy in another drive other than C.

**Comment by Acly** [comment]
Can you check the output of `http://localhost:8188/etn/model_info` via browser? Replace localhost with your server URL. List of checkpoints is generated by the server, so extra_model_paths.yml should work, and drive doesn't matter.

If this reports something unexpected (eg empty list), output of `http://localhost:8188/object_info` would be interesting to compare.

Difference between v1.5 and v1.6 is that the latter checks for SD1.5 and SDXL separately: if you have all the prerequisites for 1.5 it will look for at least one 1.5 checkpoint, or if you have the prereqs for XL then at least one XL checkpoint. Previously it just looked for any file.

**Comment by nakanakapoi** [comment]
The output does list my checkpoints. After you mention about 1.5 checkpoint I realize this server does not have 1.5 checkpoint in it only SDXL. So, I put one inside. It now detect all the checkpoint but give different error:

`Could not find ControlNet model ControlNet tile. Make sure to download the model and place it in the ComfyUI/models/controlnet folder.`

I'm not sure what this model is. So I just copied all the content of controlnet folder from another server that work, but the error still persist.

**Comment by Acly** [comment]
All required models are listed here: https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md

If you have all prerequisites for SD XL it should work - you don't need the SD1.5 stuff (including control net tile or any 1.5 checkpoint). But if something like the IP-adapter model is missing for all versions the error will report the first missing item, and it doesn't really know what SD version you're going for.

**Comment by nakanakapoi** [comment]
I downloaded the control net tile model, thus got connected to the server successfully. Thanks for all the help. Still early and a bit buggy but I have high hope for this project.
