### ISSUE TITLE
The server is missing the IP-Adapter Face model

### ISSUE THREAD

**Issue by linxl19** [Acly/krita-ai-diffusion#435]
Sir, I encountered a problem while using the AI Image Generation plugin in Krita software. 

When I use the face mode in Generate, no matter whether I switch to the 1.5 or XL model, the interface will display: The server is missing the IP-Adapter Face model. 

However, I checked the local model files, I have already downloaded _**ip-adapter-faceid-plusv2_sdxl.bin**_ and **_ip-adapter-faceid-plusv2_sd15.bin_**, and the lora folder also contains _**ip-adapter-faceid-plusv2_sd15_lora.safetensors**_ and **_ip-adapter-faceid-plusv2_sdxl_lora.safetensors_**. 

May I ask how to solve this problem, thank you.
<img width="311" alt="PixPin_2024-02-27_11-40-25" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/57e4f284-ac29-4851-8e91-5e84ec87ee8c">

**Comment by howcaniforgetu** [comment]
how did you solve it? @linxl19

**Comment by linxl19** [comment]
> how did you solve it? @linxl19

<img width="276" alt="PixPin_2024-02-29_22-39-40" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/381b643f-654f-40cc-8c07-0b29ad249a8e">
download these files.

**Comment by afecelis** [comment]
The Windows version downloads them without problem. I grabbed a copy of them and placed them back in my Linux installation into the folder shown above.
If any of you requires them I placed a zipped copy in the following link:
https://www.dropbox.com/scl/fi/bkw6ew5xg3pwtiplh7u5f/ipadapter.zip?rlkey=3i76skuom5780wh3iiqx4nqm4&dl=0

**Comment by AzimovIz** [comment]
![изображение](https://github.com/Acly/krita-ai-diffusion/assets/66750886/45b9a633-52cf-4f8c-b1b6-00969e685c36)

I get this error when I try to use face, I downloaded lora and put it in loras folder but it didn't help.
What do I need to do?

**Comment by AzimovIz** [comment]
I was able to solve this problem. It was necessary to put the lora files in the "sd1.5" folder

![изображение](https://github.com/Acly/krita-ai-diffusion/assets/66750886/d9f616d4-0205-494b-ac29-0fc2772f8e7c)
![изображение](https://github.com/Acly/krita-ai-diffusion/assets/66750886/2164c157-6259-46b4-b3e4-58aceca47c3f)
