### ISSUE TITLE
This is SDXL checkpoint, but the SD XL workload has not been installed 

### ISSUE THREAD

**Issue by henadzi-customgamesstudio** [Acly/krita-ai-diffusion#436]
I run ComfyUI on PC in local lan. When I started Krita with plugin everything is working fine. I am using connect to external server anp put address 127.0.0.1:8188. In this case everything works well, but when I am trying to connect to this PC via lan and using adress 192.168.100.20:8188 I the sd1.5 models works well, but XL models doesn't work  and I see a message that xl workload has not been installed 
<img width="892" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/89122257/c4afc747-6bda-4033-959e-725a29ed94de">

Could u please assist me with trouble shooting this issue? I am using krita_ai_diffusion-1.14.1. The remote machine wher it doesn't work is Mac.

**Comment by Acly** [comment]
Yes it's likely missing model, you can check client.log if you want to know which one.

See #417 if you're using the plugin's installer, or [here](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#this-is-a-sd-15xl-checkpoint-but-the-sd-15xl-workload-has-not-been-installed) for custom install.

**Comment by henadzi-customgamesstudio** [comment]
I downloaded latest  1.15.0, plugin and install from scratch. And now is working fine. BTW, I had a symlinks in prev installation and symlink was inside symlinks. and now I just have symlincs for checkpoints and everything works well

**Comment by henadzi-customgamesstudio** [comment]
Fixed when updated plugin to version 1.15.0 and remove symlinks

**Comment by SalmonRK** [comment]
i'm solved these issue.  it ipadaper file name issue
Check ipadapter model MUST correct with naming below

ip-adapter_sdxl_vit-h.safetensors
ip-adapter-faceid-plusv2_sdxl.bin

![image](https://github.com/Acly/krita-ai-diffusion/assets/130884337/45a0497c-4d36-4104-a8c9-b22d3033d7dc)

**Comment by gitgitgta** [comment]
I'm solved this issue,This is a naming problem under the Lora folder. You must create two new folders under the Lora folder because the two files have duplicate names. Follow the picture prompts so that you can use the SDXL model.
This is the address for model download： https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup
![Snipaste_2024-04-09_16-34-19](https://github.com/Acly/krita-ai-diffusion/assets/166409100/8b3405ee-a3d8-4839-b76a-f5c0ea668f0d)
![Snipaste_2024-04-09_16-32-47](https://github.com/Acly/krita-ai-diffusion/assets/166409100/c8af686e-8fdc-49e9-b8a6-c108240941e2)
![Snipaste_2024-04-09_16-35-14](https://github.com/Acly/krita-ai-diffusion/assets/166409100/95f927bf-37ca-4c6b-9fd1-af1f212cd29a)

**Comment by MorrisLu-Taipei** [comment]
> i'm solved these issue. it ipadaper file name issue Check ipadapter model MUST correct with naming below
> 
> ip-adapter_sdxl_vit-h.safetensors ip-adapter-faceid-plusv2_sdxl.bin
> 
> ![image](https://private-user-images.githubusercontent.com/130884337/314385985-45a0497c-4d36-4104-a8c9-b22d3033d7dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzQ0ODksIm5iZiI6MTcxNzQzNDE4OSwicGF0aCI6Ii8xMzA4ODQzMzcvMzE0Mzg1OTg1LTQ1YTA0OTdjLTRkMzYtNDEwNC1hOGM5LWIyMmQzMDMzZDdkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNzAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTc3NTQwMzJmNGE0YzgyMDI3NDNkNzQ0ODhjZWI3YWFkN2ZkMGQ5OTRmNjVlMzVkNzAyYTVhZTgxMDJkYzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Al1uV_q87UzZJCJI04Uj2LM6IJkoCnBBP0c9WXpVsFs)

this not works for me

**Comment by MorrisLu-Taipei** [comment]
> I'm solved this issue,This is a naming problem under the Lora folder. You must create two new folders under the Lora folder because the two files have duplicate names. Follow the picture prompts so that you can use the SDXL model. This is the address for model download： https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup ![Snipaste_2024-04-09_16-34-19](https://private-user-images.githubusercontent.com/166409100/320779467-8b3405ee-a3d8-4839-b76a-f5c0ea668f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzQ0ODksIm5iZiI6MTcxNzQzNDE4OSwicGF0aCI6Ii8xNjY0MDkxMDAvMzIwNzc5NDY3LThiMzQwNWVlLWEzZDgtNDgzOS1iNzZhLWY1YzBlYTY2OGYwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNzAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDBjYWMzOWYxMGNkODM2NjZjMGU1Zjg0NjlhNzMxOWEzNzFmMzc1ZjkzNTgyY2RiMjIzZDBkZGEyYzk4OGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZG85440K_ZQ-8xf0AGwthk8gD21h3c7oChAD3plmDJY) ![Snipaste_2024-04-09_16-32-47](https://private-user-images.githubusercontent.com/166409100/320779494-c8af686e-8fdc-49e9-b8a6-c108240941e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzQ0ODksIm5iZiI6MTcxNzQzNDE4OSwicGF0aCI6Ii8xNjY0MDkxMDAvMzIwNzc5NDk0LWM4YWY2ODZlLThmZGMtNDllOS1iOGE2LWMxMDgyNDA5NDFlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNzAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjFmMmNmMzMzYjY5MmIxMmRkZjI0N2NiMDhkZjM0OGE2YzIzZGFiMTVlZTk0YzRlM2I0NTkzOGQ0Y2MwYjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SrB9-Mqk_xOaq-Ddrd4fdMu6pNwOU5eWJSAgdsMJ3zk) ![Snipaste_2024-04-09_16-35-14](https://private-user-images.githubusercontent.com/166409100/320779517-95f927bf-37ca-4c6b-9fd1-af1f212cd29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzQ0ODksIm5iZiI6MTcxNzQzNDE4OSwicGF0aCI6Ii8xNjY0MDkxMDAvMzIwNzc5NTE3LTk1ZjkyN2JmLTM3Y2EtNGM2Yi05ZmQxLWFmMWYyMTJjZDI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNzAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODE0YTk3Yzc1NTNhZTEyMjRlMTA5YzI3MDkyMzBmNzU2YWE0NjM0MzczYzliN2Y2OWVmMzQ0NDY5MGFiYjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pIp9kTy0WEFQclAsU6eWgZTvjlpjuNxX1HXT_JyHtGY)

this works to me

**Comment by krones9000** [comment]
Just to add to this if anyone comes back to the thread and can't get a working solution:

I cleaned up my LoRAs folder and didn't recognize "[Hyper-SD-LoRA (SDXL)](https://huggingface.co/ByteDance/Hyper-SD/resolve/main/Hyper-SDXL-8steps-CFG-lora.safetensors)" so I deleted it. 

It's in the [requirements list](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup) for setting up the Krita addon. If you find yourself with this issue, double check you've still got everything needed. Putting this LoRA back fixed this for me but most of the results I found for this issue in Google talk about the IP Adapter instead so hopefully this helps someone if they encounter this in future.

**Comment by deadman3000** [comment]
This is an absolute joke. I deleted some models from my checkpoint folder. Now I get this workload message and cannot use any SDXL models in Krita. I tried python download_models.py and get error ModuleNotFound ai_diffusion or something like that. If I choose the folder location it shows models missing but it WILL NOT LET ME install them unless I create a new ComfyUI folder from scratch and download an entirely new ComfyUI install! Why won't it allow me to use the existing folder location where it says most files are installed (just not the models I must have deleted)? Why can't I install the missing models from Krita? Why does this thing BREAK so easily? Why does it say I must download Python from MS Store when I have a perfectly working Python folder already in the ComfyUI folder?

It's so damned annoying. I don't want to run a seperate ComfyUI folder JUST for Krita. I run as local server but everytime I do something like delete some checkpoint to free up space I get this issue crop up.

**Comment by bbecausereasonss** [comment]
Just installed Krita and having this issue with 1.5 and SDXL... Confused... My checkpoints are in their respective folders like /SDXL /1.5 does it matter?

**Comment by NoMansPC** [comment]
Unfortunately, also getting the same error again.

**Comment by tolozine** [comment]
模型装再其他位置，用extra_model_paths.yaml加载，路径有什么要求吗？仅xl无法加载

**Comment by Fkiki18** [comment]
Version 1.28
Using Local Managed Server works without a problem, but using "custom server " was giving error.
What worked for me is to literally copy all missing files from the installed local server (new one) to my original server location. Not all models work, but many of them now work without a problem. 
it might very well be a naming problem. 
Or you need to check your Embeddings and clip vision files. 
EasyNegative.safetensors
clip-vision_vit-h.safetensors

I will check how to get my remaining files to work.
