### ISSUE TITLE
Preview not working since update from 1.12 to 1.15

### ISSUE THREAD

**Issue by Duemellon** [Acly/krita-ai-diffusion#441]
Maybe I missed some item install with such a large jump.

1 I downloaded & placed the files in the right spot but Krita didn't run AI, instead the docket didn't come up even though it was selected.

2 Then I uninstalled Krita & reinstalled & it was found but the generated image doesn't show.

3 I told it to "reset all settings" from SETTINGS but the problem persists.

You can see the periodic update "pings" from the server screen aren't happening, it is as if it fires once & stops, not "live" but still no pic either in Live or Generate, or any mode.

What to try here?

Krita 5.2.2
![image](https://github.com/Acly/krita-ai-diffusion/assets/113479041/e2fa5c00-5024-4584-9193-302aa486057f)

**Comment by Acly** [comment]
So none of the modes are working? It generates but doesn't show image?
It sounds like an issue with websockets, but not sure exactly.
1. Check client.log for errors
2. Did you remove previous version of the plugin or overwrite?

**Comment by Duemellon** [comment]
Is it possible to download the previous version 1.12 & see if that still works?

**Comment by Acly** [comment]
Yes you can try previous [releases](https://github.com/Acly/krita-ai-diffusion/releases). I don't have a better idea at the moment either.

**Comment by Duemellon** [comment]
This time:
Didn't reinstall Krita
Didn't do a settings > reset all of Krita

Del'd 1.15 files from /pykrita
Copied & pasted 1.12 in that same area

AI Dock was disabled in Krita, reenabled
restarted Krita
Works with 1.12, no problem.

I'm going to babystep up the versions now.

**Comment by Duemellon** [comment]
OK, walked through each variation from 1.12 to 1.15 & it failed only at 1.15

I kept ComfyUI running
I closed Krita
Del'd the previous version
Copy-pasted the next step up
Relaunched Krita
The only thing it asked me was to reconfig the server (my port is 8000)
And I would manually pick the model before generating (I don't have Juggernaught, etc. so I have to pick from my yaml file directory change)
And every version, up to & including 1.14.1 worked fine

An interesting thing was:
When I was putting all those other versions in only the default Style (from dropdown) was available. No problem. I simply changed the model for the one I would test & moved on.

But when 1.15 came around it "remembered" the custom Style I made up initially when I first installed it, as if there are some lingering files outside of PyKrita folder. 

Are there? how do I completely nuke the 1.15 files to see if that's the problem?

**Comment by Acly** [comment]
> But when 1.15 came around it "remembered" the custom Style I made up initially when I first installed it, as if there are some lingering files outside of PyKrita folder.

Yes this is explained in 1.15.0 release changes: https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.15.0
It makes it easier to delete/update without losing your settings and styles. But you can remove that folder too.

I took a close look at changes in 1.15 since you narrowed it down, but didn't find anything suspicious yet. There were practically no changes to live mode.

**Comment by Duemellon** [comment]
Well, this isn't just about live mode, it's about all modes won't show a preview.

**Comment by Duemellon** [comment]
So I del'd that new folder, reinstalled 1.15 & it works fine now.

**Comment by Acly** [comment]
So it was some specific setting that broke it maybe? Since the main thing deleting the folder does is reset them. Still a mystery to me, but at least it generally works.
