### ISSUE TITLE
Not connecting to the server

### ISSUE THREAD

**Issue by Herealert** [Acly/krita-ai-diffusion#444]
Hi! There is a long error I can't solve when trying to connect to the server. Thanks!

<img width="614" alt="Captura de pantalla 2024-02-29 131611" src="https://github.com/Acly/krita-ai-diffusion/assets/161719004/a6c5a9e0-978b-418a-9612-e9c4dbf8e261">
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14447822/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14447823/server.log)

**Comment by Herealert** [comment]
Here the logs:

[client.log](https://github.com/Acly/krita-ai-diffusion/files/14447833/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14447834/server.log)

**Comment by Acly** [comment]
The first error asks you to install a newer NVIDIA graphics driver. Did you do that?

The lag contains some errors related to strange server path. Make sure Server Path is set to the folder where you installed (it looks fine in the screenshot).
