### ISSUE TITLE
[Feature Request] Improved ToMe (ToDo)

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#446]
https://github.com/ethansmith2000/ImprovedTokenMerge
https://github.com/ethansmith2000/comfy-todo

Would be really useful to apply this and have sliders for it within the settings.

EDIT: Also requesting more optimizations such as
kohya's DeepShrink/High Res Fix
HyperTile

**Comment by Acly** [comment]
Moved to watchlist #779
