### ISSUE TITLE
Bug regarding new styles location?

### ISSUE THREAD

**Issue by MoreColors123** [Acly/krita-ai-diffusion#447]
Hi, first i want to say thanks and how much i love your plugin. It was the reason for me to install and work with krita while being a professional photoshop user for 20 years. But anyway, here's the thing: I have a bug with the new organisation of user styles.

Its been a very good idea to put the styles to another location, but now i experienced the following problem:

i saved my styles here, as supposed to, right?
![grafik](https://github.com/Acly/krita-ai-diffusion/assets/131474336/09203091-3f3e-43e2-abc2-0a4363b6968f)

and i do see them here:
![grafik](https://github.com/Acly/krita-ai-diffusion/assets/131474336/10b1b9f7-e128-4029-b78b-0eede727e1b0)

but this is all i see here:
![grafik](https://github.com/Acly/krita-ai-diffusion/assets/131474336/2a37ba66-06fe-4865-b2ce-68a54271ed67)

so something is wrong here, because there are some missing. oh and i deleted all the default configs in the plugins styles folder too.

By the way, the new option to delete a generation from the preview is very good. but could you please also implement:
a) a button to delete ALL current generation preview or
b) make it to keep the scroll bar down at the last generation

i find myself scrolling down to the newest generation (i.e. when inpainting a lot) all the time after generating.

Thanks!

**Comment by Acly** [comment]
The style settings list all style files. The generation UI filters that list and hides styles which use a checkpoint that can't be found or a SD version that doesn't have all requirements installed. Are there any such issues for the missing items? It should show a warning in the settings too.

This is not really new though. Not sure how the folder change might be related.

> make it to keep the scroll bar down at the last generation

This should already be the case: *if* you are currently scrolled to the bottom, new generations that are added will keep it scrolled down. If you're browsing somewhere in the middle it doesn't do that, it would be quite annoying I think.

**Comment by MoreColors123** [comment]
Oh, missing checkpoints will be the culprit, I'm sure. Thank you for the explanation. 

And regarding the other issue: I thought I tested it with the new version, but i will test again. It was definitely an annoying problem in the last version, because i remember i was scrolling down every time. But nonetheless, thank you for your work!

**Comment by Acly** [comment]
The scrolling hasn't changed, if you're scrolled all the way down and generate images that get appended below it should scroll down so they're visible. Otherwise it stays at its position. Always been that way, still works for me at least. You see something different?

**Comment by MoreColors123** [comment]
OK, I'm sure I did lot of scrolling and I don't know why i can't reproduce it now, anyway I tested again and it does work now.
