### ISSUE TITLE
hi - error when i try to sdxl inpaint - RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x2048 and 768x320)

### ISSUE THREAD

**Issue by nikolaiusa** [Acly/krita-ai-diffusion#450]
i downloaded this: 
SD XL
[IP-Adapter (SDXL)](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors) to custom_nodes/ComfyUI_IPAdapter_plus/models
[LCM-LoRA (SDXL)](https://huggingface.co/latent-consistency/lcm-lora-sdxl/resolve/main/pytorch_lora_weights.safetensors?download=true) to models/loras/lcm-lora-sdxl.safetensors rename!
[Fooocus Inpaint (Head)](https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/fooocus_inpaint_head.pth) to models/inpaint
[Fooocus Inpaint (Patch)](https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/inpaint_v26.fooocus.patch) to models/inpaint

**Comment by nikolaiusa** [comment]
what else should I do?

**Comment by nikolaiusa** [comment]
https://github.com/Acly/comfyui-inpaint-nodes - all these inpaint workflows work in comfyui
regular sdxl generations I work in krita

**Comment by nikolaiusa** [comment]
The solution was that if there is no "XL" in the model name, then Krita defines it as 1.5 model and cannot perform inpaint and controlnet

**Comment by Acly** [comment]
The detection via name is a fallback, usually it inspects the model which is more robust.

If that doesn't work try updating [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes) custom node. You can verify by going to http://127.0.0.1:8188/etn/model_info

**Comment by TsengSR** [comment]
Man, the detection of model really blows. It doesn't detect a single model correctly, I get this message on every single model and I refuse to rename 8000+files just for this thing to recognize it.

@Acly 
Isn't there  a better way to set the model or give it better hints than renaming?

The Style setting sadly only offers me "Automatic" or "SD 1.5" which sucks really hard, so I can't set it that way. And the models are already organized in folders for their respective models (SD1.5, SDXL, Pony, Illustrious, Noob, Flux etc).

Can't the other types (SDXL, Pony, Illustrios, Flux, etc.)  just be added to the drop down as a work around so we can set it as an hard option until the automatic detection gets usable?

**Comment by Acly** [comment]
This is a very old issue, name-based detection isn't used anymore at all. I haven't seen any issues with detection in a while, but it's possible it just takes too long for 8000 files (these are all checkpoints?).

You might be able to override the architecture in the style .json file.

**Comment by TsengSR** [comment]
Well 2500 checkpoints (~15 TB), but each of them comes with a json and a preview image and thumbnail of the same name as the checkpoint (other issue being is that there is no way to search/filter in the drop downs and this number or fheckpoints makes it hard to pick one thats not at the beginning). 

In ComfyUI itself I dont have any issues using any type of checkpoint.

The naming thing seems to be still in there. I tested it with one checkpoint before and that did fix it,. renaming it from daisybreed_v20.safetensors to daisybreedXL_v20.safetensor. ComfyUI and tooling nodes are on the latest versions.
