### ISSUE TITLE
Is there an option like Only masked in automaic111

### ISSUE THREAD

**Issue by nikolaiusa** [Acly/krita-ai-diffusion#452]
or  like scale before processing in invokeai...

or should I just increase the resolution before creating the mask?

(Sorry for the stupid questions, I'm trying to figure out the interface)

**Comment by Acly** [comment]
only masked is the default

for other options see https://github.com/Acly/krita-ai-diffusion/wiki/Inpainting#context-area

**Comment by nikolaiusa** [comment]
I mean, if I select an area of 100-100 pixels in size, can I specify the resolution with which XL model should perform the generation. For example, I will select 100 by 100 pixels and want the neural network to generate this square with a resolution of 1000-1000 and then reduce it and insert it into a 100 by 100 square.

**Comment by Acly** [comment]
Yea something like that will happen by default. Native checkpoint resolution can be changed in Style settings. Only if you exceed it and want more resolution you need to increase canvas resolution.
