### ISSUE TITLE
Invalid IPAdapter when using Face reference

### ISSUE THREAD

**Issue by ChrisTello** [Acly/krita-ai-diffusion#456]
Suddenly started having this error. Everything was working fine and havent changed the install location of any models but i got this error saying the models are not valid. I am using comfyui via a plugin from A1111 that lets me use comfy with a1111.
![Screenshot 2024-03-02 005447](https://github.com/Acly/krita-ai-diffusion/assets/40412807/9822a726-4f97-43c5-8ad1-3bb1cb8bf201)

**Comment by Acly** [comment]
That file is a lora, so it should be in `models/loras`, not in `models/ipadapter`

**Comment by ChrisTello** [comment]
> That file is a lora, so it should be in `models/loras`, not in `models/ipadapter`

i have the file there as well but if i only have it in the lora folder then it fails to detect the file. All of my loras are detected correctly when applying them to workflows tough so i know its looking at the right folders.

**Comment by ChrisTello** [comment]
i moved the ipadapter folder away then placed it back in and now it appears to work fine.

**Comment by Acly** [comment]
probably just luck though, when it's searching for the ipadapter (not the lora) it potentially finds the lora first because they both match the search path. Then it will fail. The lora is really not supposed to be in the ipadapter folder.

You can check the client.log file to see where it's searching and which files it uses.

**Comment by ChrisTello** [comment]
> probably just luck though, when it's searching for the ipadapter (not the lora) it potentially finds the lora first because they both match the search path. Then it will fail. The lora is really not supposed to be in the ipadapter folder.
> 
> You can check the client.log file to see where it's searching and which files it uses.

i checked and thats why i placed them in the ipadapter folder since it was looking in that folder
