### ISSUE TITLE
Incorrect Device selected

### ISSUE THREAD

**Issue by iMixJ** [Acly/krita-ai-diffusion#458]
Hi, Im pretty new with this AI things and probably it's a very easy fix but I can't found it for myself, when I try to use the plugin it gives me a error like this: "There is not enough GPU video memory availible!" And when I go to configure the plugin in the Performance tab it says that the device is: "[PRIVATEUSEONTE] privateuseone (1 GB)", but my GPU it's a AMD Rx 6650 XT, 8GB of Vram, so it never uses the GPU when I try to use the plugin

![image](https://github.com/Acly/krita-ai-diffusion/assets/161962311/b2d3937c-671e-485c-8c5e-a1353703ae3b)
![image](https://github.com/Acly/krita-ai-diffusion/assets/161962311/8fb8ed22-6d96-4f0e-9dcb-0d115abe7576)

My full specs are: RX 6650 XT 8gb Vram Stock., 16 Gb ram 3000 mhz Stock, Ryzen 5 5600x Stock. and the program is installed in a hardrive of 2tb.

**Comment by Acly** [comment]
It always says "[PRIVATEUSEONTE] privateuseone (1 GB)" ragardless when using DirectML, for some reason it doesn't support query for actual VRAM. Unless you have another GPU in your system (doesn't look like it) it is using your RX.

As to why it runs out of VRAM, does it happen every time or only for certain mode / at higher resolutions? DirectML is not very efficient, unfortunately there isn't really alternative for AMD on windows...
