### ISSUE TITLE
Feature request: face restoration

### ISSUE THREAD

**Issue by nakanakapoi** [Acly/krita-ai-diffusion#46]
First of all, I'm really really happy with your work. Similar project like this either stalled or not good enough.

One features I miss though is face restoration via gfpgan or codeformer. I'm aware that inpainting the face will give better result but sometimes I just want a really quick fix.

This is just my own selfish suggestion for you to take note. You already go beyond by implementing control net, etc. I hope this project will not stall because generative AI is fast paced nowadays. Just recently LCM is introduced I hope this plugin will support it later.

**Comment by Acly** [comment]
Face restoration I'm not sold on it being a good fit. To me it makes sense when you run highly automated initial generation in batch. But I think that is better done by other tools who can devote more UI space to setting that up (face restoration alone has many possibilities and everyone has their favourite).
You can convince me though with compelling/fitting use case :)

LCM is fun! [See here](https://github.com/Acly/krita-ai-diffusion/issues/47#issuecomment-1807104970) if you want to try. It'll take a bit of experimenting to see how it fits in.

**Comment by nakanakapoi** [comment]
Yeah, I agree that face restore is not high up on priority list. One use case is when I have a few background characters that need some fixing but not important enough to require inpainting for each face. I do face restore then slightly blur them afterward. But having to pull up the comfy tab make me wish that this feature is available.

**Comment by hansnolte** [comment]
> You can convince me though with compelling/fitting use case :)

Maybe not for generating images but definitely for scaling images (faces) Codeformer would be the ideal addition.
