### ISSUE TITLE
[Suggestion] LCM and lightning selection consistency; selecting paths and schedulers; clearing prompt history

### ISSUE THREAD

**Issue by Gwynennen** [Acly/krita-ai-diffusion#465]
Hello I have few suggestions:
1. Both LCM and lightning LoRAs have their corresponding sampler+scheduler in drop down menu but contrary to LCM (which is a required model inside resources.py), lightning must be added as a LoRA. I would personally make it so that both of these have to be added as a LoRA (also if you have folder with only LCM LoRAs it won't be visible in drop down menu because of that);
2. Creating a menu for picking schedulers separately to samplers;
3. Adding "advanced options" to set paths for resources from inside krita plugin settings instead of manually editing resources.py;
4. While v1.15 added ability to delete generated images inside the dock I didn't manage to delete prompts history, option for this would be nice: 
![image](https://github.com/Acly/krita-ai-diffusion/assets/96996569/81169430-cc16-43e0-965c-9a5d0217b343)
5. Add option to reverse sort order of created generations -> change oldest first to newest first;

**Comment by Acly** [comment]
Generally I'd like to keep an option to switch between  Regular, LCM, Lightning etc. with 1 option and avoid all the potential for misconfiguration. Lightning Lora should be made consistent, I'm just nore sure about it yet. More in #497

Paths for resources: maybe a config file for additional search paths? If somebody wants to implement it. The defaults should work unless you deliberately rename everything?

4.: Yea I didn't have time to fix it (it's unreasonably tricky to do for something minor). If it bothers you switch to a different canvas and back :)

5.: Not sure about an option, but I like the idea of just switching the order to newest on top.

**Comment by Acly** [comment]
Hm I briefly tried reverse order, but it's actually very annoying in practise. Because it's common that new images finish in the background, with newest first the position of existing items constantly changes, as they are pushed further down while you're trying to work...

**Comment by Acly** [comment]
[v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0) supports custom presets for samplers, schedulers and auto-lora
