### ISSUE TITLE
Ive tried to connect to the server but when i try to use the local server it states: error during installation : xcode-select: note: no developer tools were found, requesting install

### ISSUE THREAD

**Issue by eugehdz** [Acly/krita-ai-diffusion#466]
krita wont let me use the plug in tool for it to work and it just says " error during installation : xcode-select: note: no developer tools were found, requesting install. if developer tools are located at a non-default location on disk, use 'sude xcode-select--switch path/to/xcode.app' to specify the x code that you wish to use for command line developer tools, and cancel the installation dialog. see 'man xcode-select" for more details. " when i try to connect to the server.

i think the first time i tried it a pop up came up for some stuff to be installed but i accidentally clicked decline :/

Please help me, i am not a coder, im just a medical student who used to "code" for tumblr in 2012 hahahahha 

thank you very much!!!

**Comment by eugehdz** [comment]
i uninstalled it and now it says this "invalid location: directory is not empty but no previous installation was found"

**Comment by Acly** [comment]
> i uninstalled it and now it says this "invalid location: directory is not empty but no previous installation was found"

To uninstall the server, delete the folder indicated in "Server path". Then you can try again. (The error says that it's still there)

> error during installation : xcode-select: note: no developer tools were found, requesting install.

I don't know much about mac, but I'm sure you can google this and figure out what to install (maybe just install Xcode through app store?)
