### ISSUE TITLE
Increase maximum sampler steps to 150 or more

### ISSUE THREAD

**Issue by mysticfall** [Acly/krita-ai-diffusion#468]
The current maximum sampler steps (which is 100) can be insufficient for some samplers like DPM++ 2M SDE Kerras to generate a clear, detailed image.

As such, it'd be desirable to increase the maximum to at least 150 or even apply a different optimal value for each sampler.

**Comment by Acly** [comment]
Around 20~40 is normal range for most samplers, 150 sounds way too much. I think there are better ways if you want sharper or more detailed images.

**Comment by mysticfall** [comment]
I don't know if I'm doing something wrong. But in my case, the SDE 2M sampler sometimes produces a noisy result with less than 100 sampling steps. I haven't had a similar issue with other samplers.

But I agree that it might be more of a corner case, so I wouldn't mind too much if you think it's unnecessary.
