### ISSUE TITLE
Enable the plugin in Krita

### ISSUE THREAD

**Issue by krrleva** [Acly/krita-ai-diffusion#469]
to fix "not connected to server" I tried to install the missing one, but I actually couldn't - invalid location: director is empty, but no previous installation was found

what should I do to finally run my AI plugin?
pin the photo of the problem below

**Comment by krrleva** [comment]
<img width="876" alt="Снимок экрана 2024-03-07 в 16 08 01" src="https://github.com/Acly/krita-ai-diffusion/assets/162589226/1f019aad-ced9-4a67-b8b9-24aa66d6b9cf">

**Comment by Acly** [comment]
> invalid location: director is empty, but no previous installation was found

It should say "directory is **_not_** empty, ..." - it tells you that there are already files where you want to install, and you need to check and delete them first. This is to avoid overwriting something important to you.

If the plugin is greyed out like in the screenshot, try hovering over it to see the error.
https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#plugin-is-grayed-out-in-python-plugins-manager

**Comment by krrleva** [comment]
Thank for yours reply
I accidentally put the wrong screenshot of a problem i wrote
<img width="888" alt="Снимок экрана 2024-03-07 в 16 25 25" src="https://github.com/Acly/krita-ai-diffusion/assets/162589226/35051279-c71b-452c-81c8-010a68930b88">
This is what im talking about

**Comment by krrleva** [comment]
Thank for your reply!

**Comment by RikkB** [comment]
I've installed the Win portable version of Krita v5.2.2(x64).  Downloaded & installed the [krita-ai-diffusion] plugin, but when I start Krita, it doesn't list the AI Image Diffusion plugin, not even greyed out.  I'm a bit lost as to where to look; haven't found where Krita logs are yet, but am not seeing any error popups that would indicate an error condition occurred.
![Screenshot 2024-03-12 112025](https://github.com/Acly/krita-ai-diffusion/assets/154370212/2481a951-f77e-4eb7-8ee2-b7a6901f4647)
![Screenshot 2024-03-12 111936](https://github.com/Acly/krita-ai-diffusion/assets/154370212/c320951a-fe33-4a94-b449-a4a789af9c13)
