### ISSUE TITLE
LCM Lora support???

### ISSUE THREAD

**Issue by Drakosha405** [Acly/krita-ai-diffusion#47]
Hi.
Did you see [LCM Lora](https://github.com/huggingface/blog/blob/main/lcm_lora.md)? [comfy ui issue with answer](https://github.com/comfyanonymous/ComfyUI/issues/1934)
it works wonders.
I tried LCM Lora with SDXL and the time of generation is 3-4 times less.  and its on 1060 6gb while my video card is being repaired

if you add this in "experimental" mode its save tons of time!! of course if it's functional
P.S. for inpaint I use simple encode with mask and base settings.
8 steps:
![Test](https://github.com/Acly/krita-ai-diffusion/assets/146111805/f3e20c9b-1a75-432e-9677-c6a9d179561d)

inpaint(lips) 8 steps:
![Test_inpaint](https://github.com/Acly/krita-ai-diffusion/assets/146111805/603f6d6c-b8bd-4b98-a70a-fdda3a222bcd)

**Comment by Acly** [comment]
Yep. Experimental implementation [on a branch](https://github.com/Acly/krita-ai-diffusion/tree/lcm)
If you want to try it:
* Install  branch version of the plugin
* Make sure Comfy is latest version
* Put [LCM models](https://huggingface.co/latent-consistency/lcm-lora-sdv1-5) into models/loras, name them `lcm-lora-sdv1-5.safetensors` (for XL:  `lcm-lora-sdxl.safetensors`)
* Select "LCM" as sampler in style settings
* Remember to put samples to 4-8 and CFG to 1-2 (no floats yet)
* *Don't* add the LoRA manually

![lcm-experimental](https://github.com/Acly/krita-ai-diffusion/assets/6485914/af75c6c3-a970-48b2-b69b-67de2d32f49d)

Actually seems to work with inpainting workflows etc.

**Comment by motolo** [comment]
how to install?

**Comment by Acly** [comment]
Implemented in [latest release](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.7.0) - after installing the new plugin version it will do a server upgrade which comes with LCM loras.

Also implemented interactive "live" mode. Bit of a hype right now and probably I will regret, but... it is really fun.
