### ISSUE TITLE
 It is strongly recommended to add this sdxl tile to it. I can ask the author to authorize it to you.

### ISSUE THREAD

**Issue by kevinwbryant** [Acly/krita-ai-diffusion#473]
https://civitai.com/models/330313/ttplanetsdxlcontrolnettilerealisticv1，This tile for sdxl is the best I have ever used, and the process is quite ok. I highly recommend it.

**Comment by kevinwbryant** [comment]
![Uploading 微信图片_20240306143930.png…]()

**Comment by kevinwbryant** [comment]
![Uploading 微信图片_20240306143930.png…]()

**Comment by Acly** [comment]
This can be used in  [version 1.16.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.0) now. You will have to install it manually (download and put in `models/controlnet`), it should be picked up when it's available.

Search paths: `ttplanetsdxlcontrolnet`, `ttplanet_sdxl_controlnet_tile_realistic`

It will also be used in tiled upscale.

Personally I was not entirely convinced by the quality, in my test SD1.5 models (+tile controlnet) gave better results.

**Comment by redclif43** [comment]
> Search paths: `ttplanetsdxlcontrolnet`, `ttplanet_sdxl_controlnet_tile_realistic`

where i put this ?

**Comment by Acly** [comment]
Download https://civitai.com/models/330313/ttplanetsdxlcontrolnettilerealisticv1 and put it into `ComfyUI/models/controlnet`

**Comment by redclif43** [comment]
> Download https://civitai.com/models/330313/ttplanetsdxlcontrolnettilerealisticv1 and put it into `ComfyUI/models/controlnet`

and how to use it?

**Comment by Acly** [comment]
Use "Blur" control layer. Also used automatically during upscale.

**Comment by Sil3ntKn1ght** [comment]
I tried the model, the layer blur works very well especially in photo Restoration. BUT there is no way to disable it in upscale, so all up-scales basically break in up-scaling, Ai art ie bad faces remain the same bad. 
and removing the control net to go back to how it was results in errors as its missing.

I'm currently reinstalling to fix it. 
id love just the layer blur but should be called DeBlur and be able to be turned off in Upscale
