### ISSUE TITLE
server url - connection refused

### ISSUE THREAD

**Issue by krrleva** [Acly/krita-ai-diffusion#474]
<img width="1309" alt="Снимок экрана 2024-03-08 в 11 54 15" src="https://github.com/Acly/krita-ai-diffusion/assets/162589226/66403390-9015-479a-978c-8ece12cfa63a">
Can't connect to the server when I tried to generate image
pls tell me what should I do
*local server also didn't worked out even thou I had enough space for that
im using MacBook 2022 M2

**Comment by Acly** [comment]
For this option you need to install/run the server separately, did you do that and make sure it's working in your browser?

**Comment by krrleva** [comment]
No, could you tell me where can I read about how to do it?

**Comment by Acly** [comment]
1) You need to install [ComfyUI](https://github.com/comfyanonymous/ComfyUI) - there are lots of tutorials/videos on this...
2) Install the extensions and models listed here: https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup

"Local server" option basically does this for you. If you do it yourself, be prepared to invest some time. I would only recommend it if you want to customize it and use it outside of the Krita plugin.

**Comment by krrleva** [comment]
Thanks a lot for your reply 
I actually want to connect local server but I can't because of the error
<img width="336" alt="Снимок экрана 2024-03-09 в 10 05 17" src="https://github.com/Acly/krita-ai-diffusion/assets/162589226/1f64a3eb-a8df-4a69-b53d-dd6c3243da00">

**Comment by Acly** [comment]
Ah, this is same as #219
Not really clear to me what the correct solution is, I don't have mac silicon to try this.

But you can do the following:
1. go to folder where you installed the plugin (.../pykrita/ai_diffusion)
2. open the server.py file in a text editor
3. delete [these 2 lines (375 & 376)](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/server.py#L375-L376)
```
            elif self.backend is ServerBackend.mps:
                args.append("--force-fp16")
```
just delete them and try again

**Comment by krrleva** [comment]
It helped! Thank you!
