### ISSUE TITLE
Cloud GPU, unable to return the generated image.

### ISSUE THREAD

**Issue by huameiwei-vc** [Acly/krita-ai-diffusion#475]
I use Kaggle to run comfyui, successfully connect with Krita, and generate images in the background, but the image is not returned in Krita.

**Comment by Acly** [comment]
Probably some issue with the websocket connection. It might be blocked (by Kaggle, your PC, or whatever is in between).
In case you are on macOS: https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#macos-no-images-received-from-remote-comfyui-server

**Comment by huameiwei-vc** [comment]
Yes, I am using macOS. I used the following code to run it, but still cannot return the image. Could it be a problem with Kaggle?

```
CERT_PATH=$(python3 -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
cd /Applications/krita.app/Contents/MacOS/
./krita
```

**Comment by huameiwei-vc** [comment]
> Probably some issue with the websocket connection. It might be blocked (by Kaggle, your PC, or whatever is in between).可能是 websocket 连接存在一些问题。它可能被阻止（被 Kaggle、您的 PC 或介于两者之间的任何内容）。 In case you are on macOS: 如果您使用的是 macOS：[https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#macos-no-images-received-from-remote-comfyui-serverhttps://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#macos-no-images-received-from-remote-comfyui-server](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#macos-no-images-received-from-remote-comfyui-server)
> 
> 可能是 websocket 连接存在一些问题。它可能被阻止（被 Kaggle、您的 PC 或介于两者之间的任何内容）。 如果您使用的是 macOS：https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#macos-no-images-received-from-remote-comfyui-server

Yes, I am using macOS. I used the following code to run it, but still cannot return the image. Could it be a problem with Kaggle?

```
CERT_PATH=$(python3 -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
cd /Applications/krita.app/Contents/MacOS/
./krita
```

**Comment by Acly** [comment]
It could be, but if the Comfy web UI is working I would assume that websocket is getting through (the web UI also relies on it).

**Comment by huameiwei-vc** [comment]
I don't quite understand why, but I have also tried it on a Windows computer and indeed cannot send back the image. It should be a problem with Kaggle. Very annoying.

**Comment by huameiwei-vc** [comment]
> It could be, but if the Comfy web UI is working I would assume that websocket is getting through (the web UI also relies on it).可能是，但如果 Comfy Web UI 正在工作，我会假设 websocket 正在通过（Web UI 也依赖于它）。
> 
> 可能是，但如果 Comfy Web UI 正在工作，我会假设 websocket 正在通过（Web UI 也依赖于它）。

Hi, I don't know how it's working again, but there is another problem that when generating, the default number is 1, but it generates 5 images.
