### ISSUE TITLE
Download models with download_models.py to runpod

### ISSUE THREAD

**Issue by Chepko932** [Acly/krita-ai-diffusion#476]
Its not possible to run the download_models.py on runpod since the other files are missing etc and only ComfyUI is installed, is there a workaround?

**Comment by Acly** [comment]
Either use [this template](https://runpod.io/gsc?template=8myumeqonw&ref=of4awcqw) which has everything pre-installed, or if you want to use your own image just download the entire repo (it's not big) and then run download_models.py.

**Comment by PrimeTimeTran** [comment]
@Acly could you please advise where I can find download_models.py to install on my local? I searched the 1.17, 1.16, and 1.14.1 and none of those had it so don't know where to find it to run, Thanks in advance~!

**Comment by Acly** [comment]
Ah, the reasons it says ai_diffusion is that this is where it's located in the release package (which doesn't the rest of the git repo like scripts). I added a direct link in the Wiki to make it easier to find int he repository.
