### ISSUE TITLE
FEATURE REQUEST: Enable/disable specific layers but keep visible

### ISSUE THREAD

**Issue by Duemellon** [Acly/krita-ai-diffusion#478]
Is it possible to add a mode where it sends the info from layers X & Y, but not Z, even if it's visible?

scenario A:
Layer 1: Where I do my colors
Layer 2: Where I have the depthmap image
Layer 3: The background I want

I don't paint on Layer 2 (depth map) but I actively paint on Layer 1 but the AI uses only Layers 1 & 3 (color & background) for the latent. This way I can get more precise with my coloration of the depth map.

scenario B:
Layer 1: Outline, quick sketch, or reference image (opacity 15% or something)
Layer 2: The active layer I'm painting

I'd want Layer 1 not to calculate in the latent being sent. 

Yah? nah? maybe?

**Comment by Duemellon** [comment]
I don't have an idea of how this would work but since layers can be put in a group/folder maybe that has some attributes that could be set or flagged?

**Comment by Duemellon** [comment]
I must be behind in versions because that's how it works now so nevermind

**Comment by Acly** [comment]
Yes control layers and previews are generally excluded.

But there are some exceptions: reference, blur, line art
Line art is often wanted in the final image. Reference & Blur can make sense to use with the same input. If you don't want those included you'll have to hide them.

**Comment by Duemellon** [comment]
Is there a way to enable this manually? I'm thinking more along the blend & opacity impacts.

So I can do an outline on top layer
Display top layer in workspace as multiply or lower opacity...
But pass it to the Generator as a different opacity or blend?
