### ISSUE TITLE
Disabling Fooocus inpaint patch for inpainting.

### ISSUE THREAD

**Issue by kudou-reira** [Acly/krita-ai-diffusion#481]
In version [Version 1.14.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.0), the Fooocus inpaint model was added to the plugin. It seems that it's always used for default inpainting. In some cases, it does not produce favorable results, so I'd like to revert to the non-inpaint model functionality. I've looked in the documentation [here](https://github.com/Acly/krita-ai-diffusion/wiki/Inpainting), but it doesn't seem like there is a way to toggle the Fooocus inpaint model off.

Is that functionality built in?

**Comment by Acly** [comment]
Yes, in Custom mode disable "Seamless" option

**Comment by kudou-reira** [comment]
> Yes, in Custom mode disable "Seamless" option

Thanks, working.

![image](https://github.com/Acly/krita-ai-diffusion/assets/26351130/542d51ea-b882-44bf-9e59-8a2d3bf48cfd)
