### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by neal2000uk** [Acly/krita-ai-diffusion#487]
Hi, I'm hoping you can help with my issue as it seems simular to issues you;ve managed to help solve on here before. 

I'm getting the following error when I select my GPU but the server will connect if I select it to run on the CPU (works but it's sloooow). I am not the most technical, but I have a AMD Radeon RX 6600 graphic card. Could this be the reason why I'm getting the error?

![image](https://github.com/Acly/krita-ai-diffusion/assets/34658174/ee447cca-d416-4b9c-8b03-707b56f4e545)

[client.log](https://github.com/Acly/krita-ai-diffusion/files/14560777/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14560778/server.log)

**Comment by Acly** [comment]
Hi, did you install with DirectML selected? If not you may have to reinstall the server.
