### ISSUE TITLE
AI Image Generation not visible in Dockers

### ISSUE THREAD

**Issue by ncskkm2** [Acly/krita-ai-diffusion#491]
Have followed the install instructions and the plug in is installed, enabled in python config page but "AI Image Generation" not visible in Settings ‣ Dockers 

Thank you in Advance

**Comment by Acly** [comment]
Which OS and Krita version?

**Comment by ncskkm2** [comment]
> Which OS and Krita version?

OS Win 10
Krita 5.2.2

**Comment by ncskkm2** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/115663014/7dd40c54-c7d9-4eb2-a1ab-511ddc1b6e13)
![image](https://github.com/Acly/krita-ai-diffusion/assets/115663014/7b2cbfad-5ffa-4298-9f02-52f55b528a92)

Attaching the screenshots of the issue

**Comment by Acly** [comment]
Try including the `" "`

**Comment by ncskkm2** [comment]
> * "C:\Program Files\Krita (x64)\bin\krita.com"

thanks

![image](https://github.com/Acly/krita-ai-diffusion/assets/115663014/1495d0c4-30d5-437b-9be5-1de3e4630e9a)

**Comment by AlecMcCutcheon** [comment]
same issue 

."C:\Program Files\Krita (x64)\bin\krita.com"
Detected Intel driver build number as 1012111
Detected Intel driver, making ANGLE the preferred renderer
No "macintosh" available.
No "breeze" available.
Set style "fusion"

C:\Users\<username>\AppData\Roaming\krita\ai_diffusion\logs have log files but they are blank

**Comment by AlecMcCutcheon** [comment]
NVM I fixed it by updating Krita

**Comment by lalitgangwar0812** [comment]
![Screenshot (1)](https://github.com/user-attachments/assets/a2835c50-b28d-4b4f-afbd-ff590b820f03)
![image](https://github.com/user-attachments/assets/b2373ed0-da0c-4dc3-bcbe-5289179f5f89)
Facing the same issue: AI Image Generation is not available

**Comment by Acly** [comment]
@lalitgangwar0812 https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#plugin-is-grayed-out-in-python-plugins-manager
