### ISSUE TITLE
SD/SDXL requirements

### ISSUE THREAD

**Issue by RikkB** [Acly/krita-ai-diffusion#492]
Is there a JSON or config file we can modify to match our installation directories rather than having to duplicate large files into multiple directories?

**Comment by Acly** [comment]
If you mean sharing folders, see https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-to-share-models-from-another-folder-with-krita-ai-diffusion-plugin

If it's about file names... you either rename them, or duplicate, or modify resources.py (see search paths at the bottom).
Reading additional search paths from JSON could make sense, there was some discussion about it, but nobody has implemented it yet.

**Comment by Sil3ntKn1ght** [comment]
Do you mean have his Krita AI diffusion read models from say the A1111 directory or easy diffusion directory?

if so yes I work that out and did this video for that.

https://youtu.be/dkYUi5gZdA0?si=FAhWjf8XIXrvShsc

**Comment by RikkB** [comment]
I meant there should be a mechanism to allow Krita to read other paths for a given file - found a solution for that.

Also meant there needs to be a way to read filenames (model names) that aren't model.safetensors.....  I might want to name that my-extra-special-zippity-do-dah.safetensors just so I know it's not the same as the other 19 model.safetensors I have

**Comment by Acly** [comment]
I think it was only clip vision with the generic "model.safetensors" name.
I added the following search paths: `clip-vision_vit-h.safetensors`, `clip-vit-h-14-laion2b-s32b-b79k.*` (case insensitive) - this also allows them to be auto-detected by the new IP-adapter nodes.
