### ISSUE TITLE
Is there any update ?

### ISSUE THREAD

**Issue by ronaldomirandah** [Acly/krita-ai-diffusion#494]
I cant find if it has been updated or not.

Or Just the initial release?

**Comment by SteffenDuenner** [comment]
Here are all releases that are available:

https://github.com/Acly/krita-ai-diffusion/releases

**Comment by ronaldomirandah** [comment]
> Here are all releases that are available:
> 
> https://github.com/Acly/krita-ai-diffusion/releases

Didnt notice that! Damn! I am using one of the first releases if not the first! Updating right now! >D
