### ISSUE TITLE
Double Saved Styles 

### ISSUE THREAD

**Issue by rbfbatx** [Acly/krita-ai-diffusion#496]
Ever since the last update I have doubles of all of my styles. I have tried removing them one by one but that deletes both of them. I tried backing up the folder and then deleting the whole thing and adding back but the problem persists. The issue also occurs when adding a new style; a double is created.

**Comment by Acly** [comment]
Curious. One idea on why this might happen is that usually there are 2 style folders:
* "Built-in styles" in the install dir: `.../krita/pykrita/ai_diffusion/styles`
* "User styles" in the user dir; `.../krita/ai_diffusion/styles`

If for some reason both path are the same for you, it would explain why everything appears duplicated. I'm not sure why that would happen though. Easy way to check where your user dir points to is to use the "View log files" link in the Connection settings.

**Comment by rbfbatx** [comment]
There were two copies of ai diffusion in in my krita folder. I deleted them both and reinstalled and it fixed it. Thank you for your help.
