### ISSUE TITLE
[Feature request] Style transfer (finally!)

### ISSUE THREAD

**Issue by olegsatov** [Acly/krita-ai-diffusion#498]
Hi, Acly,

Hope you will not miss this: https://github.com/naver-ai/Visual-Style-Prompting

Looks like style transfer problem is solved now. Would be fantastic to have it!

**Comment by Danamir** [comment]
Seems great, but we will have to wait for a ComfyUI node to be able integrate it.

**Comment by Drakosha405** [comment]
https://github.com/ExponentialML/ComfyUI_VisualStylePrompting

**Comment by ryukra** [comment]
well not exactly, it copies over more that the style, also it takes twice as long for 1 image, its a bit better than ip adapter but not by much, at least the comfyui implementation

**Comment by ryukra** [comment]
its more like an ip adapter, takes the composition + style, but you can't really bend it, plus it takes twice as long to generate.. maybe with more features it could be very nice!

**Comment by Drakosha405** [comment]
https://huggingface.co/ostris/ip-composition-adapter

**Comment by Acly** [comment]
Also need to try https://b-lora.github.io/B-LoRA/ (but it's SDXL only)

**Comment by danielcederberg** [comment]
Can´t wait for these to be implemented!

**Comment by Serasul1984** [comment]
finally we get even color control, we can use the same color palette of an reference image for every generated image after it.
This would shortens the workflow of many "projects"

**Comment by Acly** [comment]
I made the composition and style weight modes of IP-Adapter available in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
It works pretty well and doesn't require additional models. The downside is that it's mostly restricted to SDXL. You can use it for SD1.5 too at the moment, but the weight distribution thing doesn't seem to work nearly as well for that architecture.
