### ISSUE TITLE
Error: No checkpoints found! Checkpoints must be placed into ComfyUI/models/checkpoints.

### ISSUE THREAD

**Issue by anagilabs** [Acly/krita-ai-diffusion#499]
Got the error:
Error: No checkpoints found! Checkpoints must be placed into ComfyUI/models/checkpoints.
Using Krita 5.2.2, checked yaml file, all paths pointing to right folders, checked http:localhost:8188/etn/model_info, shows all installed checkpoints, comfyui works in browser mode and gives results, but error shows up when connecting through krita. Tried latest plugin version 1.15. Tried putting atleast one checkpoint based on sd1.5 in ComfyUI/models/checkpoints/ folder, still doesn't work. Only using sd1.5, no sdxl. Has any one encountered this issue, if so please let me know of any solution, or if I am missing something with the latest version of plugin. Thanks.

**Comment by Sil3ntKn1ght** [comment]
i removed the check points re launched ticked and re download when i got that error. worked for me.

**Comment by Acly** [comment]
Please check client.log, is it only the checkpoints that aren't found?

Technically the list is queried via etn/model_info, if there is at least 1 checkpoint it shouldn't complain. Make sure it's detected as "sd15", for example:
```
"dreamshaper_8.safetensors": {"base_model": "sd15", "is_inpaint": false, "is_refiner": false}
```

**Comment by anagilabs** [comment]
@Sil3ntKn1ght, thanks for the reply, sorry but i didn't quite get what you meant by '.. relaunched ticked and re download', however, I was able to solve it following @Acly's comment in the following way.. 
@Acly, thanks for your reply, following your comment i did realize that checkpoint was being detected as "base_model": "stab" !. Then followed your reply to #267 and updated comfyui-tooling-nodes. Now everything works fine. Thanks again.
