### ISSUE TITLE
Error: WARNING Failed to launch/connect server at startup

### ISSUE THREAD

**Issue by mp3pintyo** [Acly/krita-ai-diffusion#5]
Krita 5.2
Windows 11

Error:
Not connected to local server.
client.log:
WARNING Failed to launch/connect server at startup: 'utf-8' codec can't decode byte 0xf6 in position 1047: invalid start byte

**Comment by Acly** [comment]
Does this happen every time on launch?

This might be related to the language of your Windows installation. Do you have the server (or plugin) installed in a path that contains non-ascii characters? Since the default location contains your user name, if it contains non-latin characters this might be a hint.

**Comment by mp3pintyo** [comment]
My user name is "user" :)
I could use it for hours after installation.
The next day I opened Krita, and then it wouldn't start.

**Comment by Acly** [comment]
Interesting. I don't really have an idea why this would suddenly pop up when it worked before.

I did check how it behaves if I use non-ascii on purpose, and encountered similar issues. I'm going to fix those. Maybe it will also help in your case.

You could try running the server manually, maybe the output gives a clue. To do so, go to the folder where the server is installed (by default ending in ..\pykrita\ai_diffusion\.server). Open a command line and run:
```
python\python.exe ComfyUI\main.py
```
Would be interesting what it prints. If it starts up ok you should also be able to connect the plugin with the "Connect to external server" option.

**Comment by Acly** [comment]
Should be more robust in latest release.
