### ISSUE TITLE
WORKLOAD SDXL

### ISSUE THREAD

**Issue by motolo** [Acly/krita-ai-diffusion#50]
Where are these workloads?  the styles with sdxl no longer appear in the latest version even if you download the sxl and sd 1.5 workload model.
 Help

**Comment by Acly** [comment]
Workload just refers models (like ControlNet or IP-adapter) that are used by the plugin in certain situations.

Did you install the server via the plugin? In that case you can find them in the Connection settings.

If you are using your own ComfyUI install: please refer to https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md#sd-xl
To use XL you currently need the XL IP-adapter model in the right place. Then styles should show up.

**Comment by motolo** [comment]
I installed through the plugin, but even though I added both, it doesn't work and continues to give me errors in all sxdl profiles:(

**Comment by Acly** [comment]
Hm, I'm trying to guess what might be wrong:
1. When you view XL styles in style settings, it says "The checkpoint is not installed" or "... the SD XL workload has not been installed"?
1. In your server installation folder, do you have the file `ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models\ip-adapter_sdxl_vit-h.safetensors`?
1. Were you using the plugin before the last version?
1. Did SD XL already work for you before last version?
1. Do you have a SD XL checkpoint which has "XL" in its name?

I'm also adding some more diagnostic for next version. If you feel like editing code you can [add these 4 lines in client.py](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/client.py#L384-L387), run and check your client.log for issues.

**Comment by motolo** [comment]
Thanks a lot:) now woks!

**Comment by Acly** [comment]
That's great! did you figure out what was wrong? Maybe there is something I can improve.

**Comment by GitSteeK** [comment]
@motolo i have the same issue.
@Acly i have installed the ip-adapters via comfyui ... but i do not have the ".safetensors" version. It's ip-adapter-plus_sdxl_vit-h.bin

**Comment by Acly** [comment]
Please download the exact models linked [here](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md). The .bin and .safetensors will both work, but the "plus" variant does not.

**Comment by GitSteeK** [comment]
@Acly it was my mistake, I actually overlooked the fact that there was a plus there, thx

**Comment by Happenedtostumblein** [comment]
@Acly No, there does seem to be a problem with the _find_ip_adapter function. Can get it to run by returning a static value, I think it’s because the ipadapter models are stored within the custom_node folder vs the other models that are in models…

**Comment by Acly** [comment]
The list of models are retrieved from the server (via http request), so the find methods do not know about folders at all (server takes care of that). If you are having issues please check the client.log file, since 1.7.1 it should tell exactly what is available and what it searched for.

**Comment by Happenedtostumblein** [comment]
Where is that file stored?

The thing is that the module is definitely installed, this repo is up to date and the models are all in the folder.

Can you shoot a link to the ipadapter repo you’re talking about? The repo itself has “plus” in it, but not the models…right?

**Comment by Acly** [comment]
There is a  .logs folder where you installed the plugin (.../pykrita/ai_diffusion/.logs)
Yes, custom node repo has "plus" in it's name (models do not): https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by Happenedtostumblein** [comment]
Ok. Just reinstalled the latest release.

The exact error is “Could not find IPAdapter model ip-adapter-sd15, ip-adapter_sdxl_vit-safetensors. Make sure to download the model and place it in ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/models.”

Note the comma…is it concatenating the file names somewhere instead of iterating through list?

**Comment by Acly** [comment]
Closing since this is quite old. The latest version [1.10.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.10.0) also adds a script which can download models and put them in the right folder with the expected name.

**Comment by camarcuson** [comment]
> Workload just refers to models (like ControlNet or IP-adapter) that are used by the plugin in certain situations.
> 
> Did you install the server via the plugin? In that case you can find them in the Connection settings.
> 
> If you are using your own ComfyUI install: please refer to https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md#sd-xl To use XL you currently need the XL IP-adapter model in the right place. Then styles should show up.

Above link; Page not found.

**Comment by Acly** [comment]
Moved to Wiki: https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#sd-xl

**Comment by iiidsoul** [comment]
Hi,
I am using my own ComfyUI install and just need to install the "SDXL workload" so that I can get rid of the error that says: "This is a SD XL checkpoint, but the SD XL workload has not been installed."I am not sure if using the download_models.py [script](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#-download-script) can fix this issue but I couldn't use that (I am not a programmer actually). Could you please help me with this?
