### ISSUE TITLE
BUG in 1.15 related to GTX systems probably others

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#500]
[https://youtu.be/5-nmaiq11Mg?si=uuQ9bbDLa3Ay9eqe](https://www.youtube.com/watch?v=5-nmaiq11Mg)

there are two bugs on older hardware in the 1.15 version, I mention them in the video, I hope it's something that can be addressed. both show this error
2024-03-17 08:20:54,027 INFO out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
2024-03-17 08:20:54,027 INFO RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: struct c10::Half key.dtype: float and value.dtype: float instead.

the fix on a1111 was webui-user.bat at the set COMMANDLINE_ARGS= add

--xformers --medvram-sdxl --medvram --no-half

I don't know if this is something that can be done as a option for the comfyai back end in the config of krita AI Diffusion, or even if this relates, just mentioning it just in case it is something related similar. Appreciate everything you're doing

figure easier showing especially since my dyslexic writing would probably not help.

**Comment by Acly** [comment]
You can pass start up arguments to ComfyUI by editing settings.json: https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui

I'm not sure which ones are needed exactly, but try
```
--force-fp32
```
it should be roughly equivalent to `--no-half` in a1111

**Comment by Sil3ntKn1ght** [comment]
Where do I put the line. In a1111 it's a bat but the krita doesn't have a bat to mod so unsureAppreciate the helpOn 16 Mar. 2024 7:00 pm, Acly ***@***.***> wrote:
You can pass start up arguments to ComfyUI by editing settings.json: https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui
I'm not sure which ones are needed exactly, but try
--force-fp32

it should be roughly equivalent to --no-half in a1111

**Comment by Sil3ntKn1ght** [comment]
> You can pass start up arguments to ComfyUI by editing settings.json: https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui
> 
> I'm not sure which ones are needed exactly, but try
> 
> ```
> --force-fp32
> ```
> 
> it should be roughly equivalent to `--no-half` in a1111

NO luck.
still getting the error 
2024-03-17 08:20:54,027 INFO out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
2024-03-17 08:20:54,027 INFO RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: struct c10::Half key.dtype: float and value.dtype: float instead.

i tried the line in AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\.ci\windows_base_files run_nvidia_gpu.bat
no luck.
The issue is only on GTX cards the RTXs seem fine.

**Comment by Sil3ntKn1ght** [comment]
> You can pass start up arguments to ComfyUI by editing settings.json: https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui
> 
> I'm not sure which ones are needed exactly, but try
> 
> ```
> --force-fp32
> ```
> 
> it should be roughly equivalent to `--no-half` in a1111

ill get the error 
2024-03-17 08:20:54,027 INFO out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
2024-03-17 08:20:54,027 INFO RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: struct c10::Half key.dtype: float and value.dtype: float instead.



note: there was no jasson only py looks like this, added and tried a few things with no luck.
    server_arguments: str
    _server_arguments = Setting(
        "Server Arguments", "--force-fp32 --xformers --medvram-sdxl --medvram --no-half", "Additional command line arguments passed to the server"

**Comment by Sil3ntKn1ght** [comment]
Lenged .. I got there forgot the new Ai diffusion file was implemented.

C:\Users\ME\AppData\Roaming\krita\ai_diffusion 
settings.json

would it be possible to add the option to say
performance preset
GPU Low (Up to 6Gig) 
where there is another GPU Low (Up to 6Gig) (fp32) 
for those less PC user people.

--
 "server_mode": "managed",
    "server_path": "C:/Users/ME/AppData/Roaming/krita/pykrita/ai_diffusion/.server",
    "server_url": "127.0.0.1:8188",
    "server_backend": "cuda",
    "server_arguments": "--force-fp32",
    "selection_grow": 5,
    "selection_feather": 5,
    "selection_padding": 7,
    "new_seed_after_apply": false,
    "prompt_line_count": 2,
    "show_negative_prompt": true,
    "auto_preview": true,
    "show_control_end": false,
    "history_size": 1000,
    "history_storage": 20,
    "performance_preset": "low",
    "batch_size": 2,
    "resolution_multiplier": 1.0,
    "max_pixel_count": 2,
    "debug_dump_workflow": false
--

Ill do a video to let people know this and give another shout out
MASSIVE thank you

**Comment by Sil3ntKn1ght** [comment]
Thank you for the help and all you are doing. <3

**Comment by Sil3ntKn1ght** [comment]
is much much slower with this argument even the pf16 i tried slows down everything.
it be nice if there was a way for it to only apply on expand and face where the issue is present. 
expand putting a . in the prompt work without the need for fp32 arguments with fp32 arguments no . is needed.
