### ISSUE TITLE
Controlnet from https://openposeai.com/

### ISSUE THREAD

**Issue by nickthesail0r** [Acly/krita-ai-diffusion#508]
how to import poses from https://openposeai.com/ i have try but not 100% accurate. i can generate from Krita and tweeak the pose to much but i wonder if it can take as it is the photo 
![pose_2024_03_18_12_53_50](https://github.com/Acly/krita-ai-diffusion/assets/16080163/00296b8e-ec42-42ad-9258-4c80412f03a6)

**Comment by Acly** [comment]
Yes you can take images like that and use them as control layer directly. How accurate they are depends on pose complexity and capabilities of the model, it's usually not 100%.
