### ISSUE TITLE
1.7 does not take effect

### ISSUE THREAD

**Issue by planb788** [Acly/krita-ai-diffusion#51]
I have covered the old version, comfyui has been upgraded to the latest, and the required models have been downloaded. But the interface hasn't changed.
In Comfyui, I can use lcm-lora normally.

**Comment by Acly** [comment]
Note that this doesn't replace the previous UI (which I think is still overall more useful), it's an alternative. You switch with the button in the top left.
![release-1 7 0-live-tab](https://github.com/Acly/krita-ai-diffusion/assets/6485914/f1003c3b-3070-482a-8ba2-e7a2aa5869f3)

Are you saying "Live" mode is not available there? 
You can also check in style settings, "LCM" should be available as sampler option.

**Comment by planb788** [comment]
> Note that this doesn't replace the previous UI (which I think is still overall more useful), it's an alternative. You switch with the button in the top left. ![release-1 7 0-live-tab](https://user-images.githubusercontent.com/6485914/283717306-f1003c3b-3070-482a-8ba2-e7a2aa5869f3.png)
> 
> Are you saying "Live" mode is not available there? You can also check in style settings, "LCM" should be available as sampler option.

In fact, I initially downloaded the zip file and then installed it through krita's own plug-in import method (another option is to install through a network link), but this installation method is not clean, even if the source file is overwritten, it will cause The interface is left over from the old version. By finding the corresponding folder in the C drive, deleting it, and reinstalling it, I successfully got the latest version of the interface.
