### ISSUE TITLE
Server Not Starting Stuck on Server Starting

### ISSUE THREAD

**Issue by EzMac2099** [Acly/krita-ai-diffusion#511]
Server is stuck on "Starting server..." after hitting launch.

I just did a brand new install of Krita and Krita AI diffusion following this youtube video:
https://www.youtube.com/watch?v=_1pCKODmF70&ab_channel=DataExtendDigital
After it was done installing it got stuck on the "Starting server..." after 10 mins I restarted Krita. I went back to configure the AI and the launch button was un-clickable so I had to redo the path to a false folder, relaunched krita, so that I could hit launch. Whenever I hit launch I get stuck on "Starting server..." (it's been about 30 mins now). I've restarted my computer multiple times and tried launching but same issues. The log files of both the client and server don't seem to indicate anything much and I'm not finding any similar issues. Computer specs and logs (shown below)

Krita Version: 5.2.2
AI: krita_ai_diffusion-1.3.0.zip
GPU: Nvidia GeForce RTX 2060
OS: Windows 10 Home 64-bit (Build 19045)
Processor: AMD FX(tm)-8350 (8CPUs) 4GHz
Ram: 32 GB
DirectX Version: DirectX 12

![Krita Ai Server Stuck](https://github.com/Acly/krita-ai-diffusion/assets/163085830/03496a05-9dd4-4de6-8d57-a82647c48e89)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14642997/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14642998/server.log)

Additional info: Not sure if this is related at all but I can go to "Connect to external server" and connect to 127.0.0.1:8188 and it does say connected, however when I try to generate an image the progress bar loads to full but does nothing.

**Comment by Acly** [comment]
> krita_ai_diffusion-1.3.0.zip

Please try the latest version (1.15): https://github.com/Acly/krita-ai-diffusion/releases

**Comment by EzMac2099** [comment]
> > krita_ai_diffusion-1.3.0.zip
> 
> Please try the latest version (1.15): https://github.com/Acly/krita-ai-diffusion/releases

Thank you! this worked, apologies, I confused 1.3.0 with the latest version.
