### ISSUE TITLE
a suggestion about live mode when multiple clients running on a server

### ISSUE THREAD

**Issue by BuzhidaoChiang** [Acly/krita-ai-diffusion#512]
i think it is problem for multiple users on one server, this is what i found:

when I use one krita to do the live painting with the cloud gpu, my computer keeps sending request  to the server, the server gets all the requests , but only generates the ones which I really made changes (prompts or paining), I think the server identifies that if the current request is as the same as last one, it will not doing generation again.

then, when i have **two computers** running the krita live painting with the **same server**, the situation is getting different.  when im not doing any changes, just turn on the live-mode, then **computer A** keeps sending the **request A** to the server, and **computer B** keeps sending the **request B** as well, request A and B reach to the sever **alternately**, then the server is crazy working, because each time it get new request, is different from last one, that means a new job it needs to be finished. it is a **big load** for the server, and **delayed** our real requests in the queue a lot.

in the original comfyui, there is function option under the queue button, **"auto queue"**--**"change"**, the function is when change really happened, then queue the request to the server. I think this is a good method to solve this problem.

is there anyway to change some settings or codes in this plugin to make that "queue on real request" happen?

thanks a lot :)

**Comment by Acly** [comment]
Should work now in [version 1.16.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.0)
