### ISSUE TITLE
i have problem in backet pain in krita 5.2.2 

### ISSUE THREAD

**Issue by serdevai** [Acly/krita-ai-diffusion#513]
the problem is the colors krita 5.2.2 have probleme in backet 

https://github.com/Acly/krita-ai-diffusion/assets/156949818/37f0a46e-d101-41e1-99f8-23400ac491d2

**Comment by Acly** [comment]
I think this is normal, you can change the threshold in Tool Options. Anyway, this is not the right place for general Krita questions.
