### ISSUE TITLE
[Request:] Change Generation/Live Strength slider to exact Step Count slider.

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#518]
Depending on your set sampler steps (especially so at low step counts using LCM/Lightning) the strength slider becomes useless for a majority of its range.

It is a lot more intuitive to move the sampler steps out of sampler settings and replace the generation/live strength slider with it. That way the user knows exactly what they are doing without having to look at the terminal to see how many steps they are doing.

**Comment by Acly** [comment]
> It is a lot more intuitive to move the sampler steps out of sampler settings and replace the generation/live strength slider with it.

You still need both: the total number of steps (100%) and the fraction you want to actually sample (strength).
* Current: sample 50% of 8 steps
* Alternative: sample 4 of 8 steps

Strength% percent is an intuitive interpretation which relates to how much the image changes.
Steps is a much more technical parameter which requires to know about sampling and total steps to interpret it (and do the math in your head).

The downside (and I guess what bothers you) is that there is rounding involved, and changes to strength can have no effect if it doesn't cross the threshold. But that could be changed while keeping the strength% semantics (just make the slider increments discrete).
