### ISSUE TITLE
the checkpoint used by this style in not installed     how to fix  

### ISSUE THREAD

**Issue by fxgame0003** [Acly/krita-ai-diffusion#520]
![屏幕截图 2024-03-22 103929](https://github.com/Acly/krita-ai-diffusion/assets/164362233/d5c09153-35a0-4c94-bec4-b61b9325304e)
![屏幕截图 2024-03-22 103915](https://github.com/Acly/krita-ai-diffusion/assets/164362233/d8dfe316-19f5-409e-837a-2d981dd8d2c8)

**Comment by Acly** [comment]
You have to download the checkpoint (dreamshaper_8.safetensors in this case). Or just select a different one, or create your own style with the checkpoints you have.

**Comment by fxgame0003** [comment]
> You have to download the checkpoint (dreamshaper_8.safetensors in this case). Or just select a different one, or create your own style with the checkpoints you have.

Thank you very much for your response; I have fixed the issue according to your instructions
