### ISSUE TITLE
Inference speed unusually slow

### ISSUE THREAD

**Issue by BuzhidaoChiang** [Acly/krita-ai-diffusion#521]
The inference speed is unusually slow. With the same parameters, the server processes inference requests sent by Krita plugin significantly slower than it processes those sent by ComfyUI. Has anyone else encountered this issue?
![607d0ca74dfb0312e76f243c4292763](https://github.com/Acly/krita-ai-diffusion/assets/132060927/0ffff9bc-9dde-4cc0-8516-e0ae3d419286)

**Comment by Acly** [comment]
> With the same parameters

How did you ensure this? Did you export the ComfyUI workflow from the plugin?

**Comment by BuzhidaoChiang** [comment]
not yet. I just generated the same size pictures from krita and comfyui, and then found this big difference. for the same size pictures generation, i think the speed should be close, even the workflows had some difference (are they very different?). I used the cloud GPU server by the way, and I am trying to test on local later. I'll let you know the result, thanks for replying :) PS: did you check out my last issue posted couple of days ago, about the multiple-clients making server crazy problem? is there any easy way to fix that?

**Comment by Acly** [comment]
There's no difference between using Comfy backend from its web UI or Krita plugin. Performance is identical.

If you see a different speeds, it must be due to different workflow (resolution, batch size, are the obvious ones, but could be something more subtle)

**Comment by BuzhidaoChiang** [comment]
Hi Acly,
I found out the reason. yes you are right, it is because of the different workflows. I exported the workflow from krita, and found out that it's different what I built in comfyui. I use live generate mode in krita a lot, so the canvas i set like 512*768 usually. for this canvas size, SD1.5 model will generate pictures directly, but XL model, it uses a bigger resolution to generate picture first, and then resize the picture to the canvas size. that why I found so different speeds between krita plugin and comfyui. 

the workflow is designed like that can maximize the model's performance, but it lower the speed under the live generate mode. I think the live generate mode should have a better balance between picture quality and generating speed. and i made some tests and found out that 768 resolution under xl model is good for quality and speed, it has better quality than 512, faster speed than 1024. 

And I solved the keep-sending-requests- to-server problem I think, but still need more tests.

thanks for replying :)

**Comment by Acly** [comment]
That makes sense. Using a resolution too far out of a models "comfort zone" can give quite bad results (both composition wise where it crops/cuts off things, as well as fidelity). Some XL checkpoints are more flexible than others though, and there are some Turbo merges that end up working best in the 768 range.

You can configure the "native checkpoint resolution" in style settings, under advanced checkpoint. So if you set it to 768, it should no longer do 2-pass generation. Although I think for live 512x768, SD1.5 is a good fit for quality/speed.

Another solution might be to use https://github.com/bytedance/res-adapter
But I haven't had time to investigate yet.

> And I solved the keep-sending-requests- to-server problem I think, but still need more tests.

I did a lot of changes to streamline cloud, so this should no longer be an issue on latest version of the code now. (But no released yet)

**Comment by BuzhidaoChiang** [comment]
> Another solution might be to use https://github.com/bytedance/res-adapter

Looked, and tried demo, feel like not that stable on quality, maybe more test needed when it's released.

> I did a lot of changes to streamline cloud, so this should no longer be an issue on latest version of the code now. (But no released yet

That's great!!! expecting the new released version :)

**Comment by Acly** [comment]
It's out: [version 1.16.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.0)
