### ISSUE TITLE
ip adapter plus node error

### ISSUE THREAD

**Issue by kubilaykilinc** [Acly/krita-ai-diffusion#524]
I updated the ComfyUI custom node - cubic ip adapter plus. And loaded.
However, when I try to connect Krita to COmfyUI, I get this error. It says this node is not installed.
![cubiq-error](https://github.com/Acly/krita-ai-diffusion/assets/18080130/cb779d65-5ba5-4c6a-8f79-d60d834d9073)

What is problem?

**Comment by Acly** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#warning-ipadapter-v2-complete-code-rewrite-warning

**Comment by kubilaykilinc** [comment]
I did a fresh install. but this problem continues. Does Krita Diffusion need an update? Should I wait for it?

**Comment by Acly** [comment]
Yes it's no longer compatible, so you either need to revert IP-adapter to an earlier version, or wait for the next release.

I did the required changes to make it compatible again earlier today, but need some more testing before next release.

**Comment by hinablue** [comment]
@kubilaykilinc 

https://github.com/Acly/krita-ai-diffusion/blob/c51b05bb3b7b744660ed11d22b3657ee4eef67e4/ai_diffusion/resources.py#L36

`IPAdapterApply` no longer exists in the `ComfyUI_IPAdapter_plus`. You can remove is for workaround now.

**Comment by MoreColors123** [comment]
> @kubilaykilinc
> 
> https://github.com/Acly/krita-ai-diffusion/blob/c51b05bb3b7b744660ed11d22b3657ee4eef67e4/ai_diffusion/resources.py#L36
> 
> `IPAdapterApply` no longer exists in the `ComfyUI_IPAdapter_plus`. You can remove is for workaround now.

What exactly did you do?

**Comment by freecoderwaifu** [comment]
> > @kubilaykilinc
> > https://github.com/Acly/krita-ai-diffusion/blob/c51b05bb3b7b744660ed11d22b3657ee4eef67e4/ai_diffusion/resources.py#L36
> > 
> > `IPAdapterApply` no longer exists in the `ComfyUI_IPAdapter_plus`. You can remove is for workaround now.
> 
> What exactly did you do?

Open `AppData\Roaming\krita\pykrita\ai_diffusion\resources.py` in a text editor that shows lines like Notepad++ and go to line 36
Or just use the search function in regular Notepad and search for ` ["IPAdapterModelLoader",`
Change` ["IPAdapterModelLoader", "IPAdapterapply"],` to `["IPAdapterModelLoader", "IPAdapter"], ` (just remove `apply` from `IPAdapterapply`)
Save the file

That's it.

**Comment by Acly** [comment]
This will let you connect, but IP-adapter (reference/face) won't work since the nodes or organized a bit different now

**Comment by baptiste-rios** [comment]
Do "git checkout 90d3451cd970d5aa9cac55224e24a7c7fd98d253" in your custom_nodes/ComfyUI_IPAdapter_plus folder.
It will get the latest working nodes.

**Comment by Acly** [comment]
Now using the new nodes in [version 1.16.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.0)

**Comment by gilberthello** [comment]
> Do "git checkout 90d3451cd970d5aa9cac55224e24a7c7fd98d253" in your custom_nodes/ComfyUI_IPAdapter_plus folder. It will get the latest working nodes.
> 
> https://github.com/cubiq/ComfyUI_IPAdapter_plus/commits/main/README.md (Feb 2, 24)

thx a lot ,this aproadch worked

**Comment by JeffreyBull76** [comment]
Just found out the issue here. For some reason Krita does not update the script correctly unless you first disable the current version. 

So you need to launch Krita, go to plugin manager > disable current AI diffusion script > then I restarted just to make sure though not sure if this step is required > install new updated version of AI-diffusion, say yes when it asks if you want to re-enable the plugin > restart > enjoy !!
