### ISSUE TITLE
Plugin not recognizing ComfyUI directory

### ISSUE THREAD

**Issue by LgnGithub** [Acly/krita-ai-diffusion#525]
![Screenshot 2024-03-25 at 12 46 45](https://github.com/Acly/krita-ai-diffusion/assets/61321468/e725e8f6-ebf3-420b-a291-539bdd816486)

Check screenshot.

It says that "installation directory is empty, but no previous installation has been found". This is **WRONG**. ComfyUI is installed in the directory indicated, but the plugin is not recognizing it. MacOS paltform

**Comment by Acly** [comment]
Actually it says "directory is _**not**_ empty". You can only install into empty/new directories, it is not possible to modify custom installs. Use the "Connect to external server" option if you want to run your own.
