### ISSUE TITLE
IPAdapter got a big update - Krita plugin need update to

### ISSUE THREAD

**Issue by FoxyFlame** [Acly/krita-ai-diffusion#529]
Like in title IPAdapter got huge update to v2
https://github.com/cubiq/ComfyUI_IPAdapter_plus

Now i Krita is an error :
Error: The following ComfyUI custom nodes are missing:
IP-Adapter https://github.com/cubiq/ComfyUI_IPAdapter_plus
Please install them, restart the server and try again.

**Comment by Acly** [comment]
See #524
