### ISSUE TITLE
[Question] Is there a way to use another computer's video card to split the work? (same home network)

### ISSUE THREAD

**Issue by iaznaB** [Acly/krita-ai-diffusion#53]
I have another computer with a similar card and it usually is not being used, but a hassle to take out and put back in. Any way i could use it to split the work between my video card and the one in the other computer?

**Comment by Acly** [comment]
Using another computer on the network is possible, but splitting the work between multiple servers (one local, one network) isn't supported.

I think it doesn't make sense to implement that in the plugin directly, but rather have a small server in the middle, which brokers between the plugin and splits work between the two (or more) servers. I don't know that something like that exists yet though.
