### ISSUE TITLE
Krita can't recognize IPAdapter 

### ISSUE THREAD

**Issue by AhmedAburady** [Acly/krita-ai-diffusion#531]
The plugin can't connect after IPAdapter V2 code re-write with the latest update

**Comment by kubilaykilinc** [comment]
https://github.com/Acly/krita-ai-diffusion/issues/524

**Comment by Acly** [comment]
Now using the V2 nodes in [version 1.16.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.0)
