### ISSUE TITLE
[1.6] Replace background inverts next selections

### ISSUE THREAD

**Issue by wormpattern** [Acly/krita-ai-diffusion#535]
When using replace background it works fine, but all other selections for Refine are inverted. Meaning it looks like replace background mask logic stays for all other operations. After saving and reloading picture, it's still inverted.

**Comment by Acly** [comment]
I see. It goes back to normal when you set 100% strength and switch to Fill (or something else)?

**Comment by wormpattern** [comment]
It got somehow fixed after a while, not sure what I have done, I will try replicate soon.

**Comment by Acly** [comment]
Fixed in [v1.16.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.1)
