### ISSUE TITLE
Error: Could not find Upscaler model Upscale model 'fast_4x' for All.

### ISSUE THREAD

**Issue by DiegoRRR** [Acly/krita-ai-diffusion#537]
I just installed it and the necessary custom nodes, and I am trying to connect it to my already existing ComfyUI, but it can't connect because : 
`Error: Could not find Upscaler model Upscale model 'fast_4x' for All. Make sure to download the model and place it in the ComfyUI/models/upscale_models folder.`

I feel stupid but I can't find any info anywhere about what this 'fast_4x' upscale model file is...

Help please.

**Comment by Acly** [comment]
It refers to [OmniSR_X4_DIV2K](https://huggingface.co/Acly/Omni-SR/resolve/main/OmniSR_X4_DIV2K.safetensors), see the list [here](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#shared)

It would be more useful if it printed the actual filename, I'll look into that...

**Comment by DiegoRRR** [comment]
Thanks :)
