### ISSUE TITLE
Safetensors version of SD 1.5 clip_vision model is available on HG

### ISSUE THREAD

**Issue by dimtoneff** [Acly/krita-ai-diffusion#54]
Just asking if we can use the .safetensors version of the SD 1.5 clip_vision here:
https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder

model.safetensor vs pytorch_model.bin

Please, close if there was a reason to pick the .bin version. Tnx!

**Comment by Acly** [comment]
Currently it only accepts pytorch_model.bin, but the only reason is that the safetensors version wasn't available at the time.

safetensors format is preferrable though, so I will add it. Only wish they would choose a more unique name...
