### ISSUE TITLE
Error: IP-Adapter is missing

### ISSUE THREAD

**Issue by SeraphYDQ** [Acly/krita-ai-diffusion#542]
here is my error:
I've installed the ip-adapter by comfyUI manager (node name: ComfyUI_IPAdapter_plus) and put the IPAdapter models in  "models/ipadapter".
However, when I tried to connect it still showed the following picture:
![error](https://github.com/Acly/krita-ai-diffusion/assets/165343945/cc77a8b0-a4d9-48ce-aa72-6cb875d7622e)
I've checked the server URL and the client.log, but there was no error can be found.
I am confusing. Any thoughts ???

**Comment by xcfxr** [comment]
the version of ip-adapter is not matched

**Comment by SeraphYDQ** [comment]
> the version of ip-adapter is not matched

Where can I check the version?

**Comment by SeraphYDQ** [comment]
> the version of ip-adapter is not matched

Where can I check the version?

**Comment by Acly** [comment]
The latest version of the plugin (1.16.0) and latest version of IP-Adapter should work.

**Comment by d23lygjdpzok** [comment]
The old version of IP-Adapter works fine, but after updating to the new version of IP-Adapter and using the latest 1.16.0 plugin, I encountered the same error message as displayed

**Comment by Acly** [comment]
Which version exactly are you using?
The latest ComfyUI_IPAdapter_plus is `e736a64212ad15c7b09b17b58e19b03561f29f03` (from `Sat Mar 30 09:34:13 2024 +0100`), I tested that and it works with v1.16.0 (and also v1.16.1 now) of the plugin. 

Please also check Comfy web UI displays all the IP-adapter nodes.

**Comment by xuhuaye** [comment]
,I encountered the same error message as displayed，
I'm sure I've installed the ip-adapter by comfyUI manager (node name: ComfyUI_IPAdapter_plus) and put the IPAdapter models in "models/ipadapter".
![微信图片_20240331212400](https://github.com/Acly/krita-ai-diffusion/assets/75203681/c035f3e0-f859-4d3e-a155-8026b58cacb7)

**Comment by xuhuaye** [comment]
and I can load ipadpaterapply 
![微信图片_20240331212608](https://github.com/Acly/krita-ai-diffusion/assets/75203681/e4d5dcc5-18fe-4692-87f3-c62f8f27d8e2)

**Comment by Acly** [comment]
That's a node from some other extension.

It should look like this:
![image](https://github.com/Acly/krita-ai-diffusion/assets/6485914/7d24ba66-0a84-4d01-a18d-27cbfcd749c4)

**Comment by xuhuaye** [comment]
Thank u for your answer，Take a look at this picture.
![微信图片7](https://github.com/Acly/krita-ai-diffusion/assets/75203681/539ee223-4cee-4ebe-a4bb-7a77316f5ff4)

**Comment by Acly** [comment]
Looks good. If you are using version 1.16.x of the plugin it should work. It just checks if the following nodes exist: `IPAdapterModelLoader`, `IPAdapter`
They should be listed in http://127.0.0.1:8188/object_info

**Comment by xuhuaye** [comment]
Thank u,This could be the problem，http://127.0.0.1:8188/object_info I can't find ipadpter,How do I fix it？

**Comment by d23lygjdpzok** [comment]
Hello, Acly, please uninstall the ipadapter_plus plugin and install the latest version. This error should occur after that, and I don't know how to fix it.

**Comment by nothingness6** [comment]
I also faced the same issue. IPAdapter Plus is installed properly, but Krita AI Diffusion keeps showing me the error. I uninstalled IPAdapter and re-installed it, but nothing happened. 
Using the latest version for all. 
![ipadapter](https://github.com/Acly/krita-ai-diffusion/assets/105210258/f413f7b3-6093-4ae9-9d3c-2787eb563654)
![Krita AI-02](https://github.com/Acly/krita-ai-diffusion/assets/105210258/7dd86e63-e3ae-4608-95b0-c97936070a86)
![Krita AI-01](https://github.com/Acly/krita-ai-diffusion/assets/105210258/3305f827-a459-40a7-ae73-b55f6982dab0)

**Comment by d23lygjdpzok** [comment]
I think after the update of ipadapter, the plugin node or the model directory has changed, causing Krita to not recognize the plugin.

**Comment by nothingness6** [comment]
> I think after the update of ipadapter, the plugin node or the model directory has changed, causing Krita to not recognize the plugin.

Then, should we wait the next update?

**Comment by d23lygjdpzok** [comment]
i don`t know,Need to ask the Acly

**Comment by qingzhenbiaojie** [comment]
@nothingness6 我看你的截图不太像1.16.1的版本？确认一下脚本是否覆盖了旧版本的脚本，有时出现无法覆盖，需手动删除，再重新导入新的脚本进行安装

**Comment by Acly** [comment]
It doesn't look like you're using latest version of the plugin. Maybe there was an issue when upgrading?

![image](https://github.com/Acly/krita-ai-diffusion/assets/6485914/ac97ff80-04e8-4189-8143-274fa8d8c73e)

**Comment by nothingness6** [comment]
> It doesn't look like you're using latest version of the plugin. Maybe there was an issue when upgrading?
> 
> ![image](https://private-user-images.githubusercontent.com/6485914/318740045-ac97ff80-04e8-4189-8143-274fa8d8c73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTkwMTksIm5iZiI6MTcxMjA1ODcxOSwicGF0aCI6Ii82NDg1OTE0LzMxODc0MDA0NS1hYzk3ZmY4MC0wNGU4LTQxODktODE0My0yNzRmYThkOGM3M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMTE1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTlkMDk1NmQwMTQ1NTdlN2Y1ZTQyYjY4MjdlOTRmNGQ2OWVjYTVmZWFkNTk1Y2FkM2IwNTBlZWIwODkyZDg3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v4isrdiYbrn7HWW5ncq9tMeJxIxhR7aAlRYyLN_2ROE)

Hi, Acly.
Oh, you are right! I updated in a wrong way!
Btw, I found out it's pain in the ass because, AI Diffusion requires the specific model names and most of the models I own have different names. I downloaded all models through Stability Matrix. Thus, I just roll it back. 
Thanks for your help anyways! ;)

**Comment by d23lygjdpzok** [comment]
Hi, nothingness6, how did you solve it?

**Comment by d23lygjdpzok** [comment]
Hi, Acly, I finally solved the issue with the ipadapter error. After downloading the 1.16.1 plugin, I had to manually install the plugin to C:\Users\admin\AppData\Roaming\krita\pykrita. After restarting Krita again, error messages started appearing, such as missing certain models. Eventually, I managed to resolve all the issues. Thanks for your response.

**Comment by Acly** [comment]
You mean updating via "Import Python Plugin" from Krita didn't work?
It seems to sometimes not replace existing install for some people :\

**Comment by SeraphYDQ** [comment]
Hi Acly
I solved the issue by downloading the latest Krita plugin and updating my ComfyUI and all of the related custom nodes.
I still had to download a lot of missing models after that, but finally I enjoyed the plugin~
Thank you for your advice. 
It's a long way to Tipperary :)

**Comment by JeffreyBull76** [comment]
Just found out the issue here. For some reason Krita does not update the script correctly unless you first disable the current version. 

So you need to launch Krita, go to plugin manager > disable current AI diffusion script > then I restarted just to make sure though not sure if this step is required > install new updated version of AI-diffusion, say yes when it asks if you want to re-enable the plugin > restart > enjoy !!

**Comment by hu147369** [comment]
有没有大神帮忙解释下，明明confyui里有模型，kirta一直报错说没有，Is there a great god to help explain.,Obviously there is a model in confyui.,Kirta keeps reporting an error saying no.
![微信图片_20240906002443](https://github.com/user-attachments/assets/5d8827a3-6f16-42f0-9297-a2667652d0b3)
![微信图片_20240906002604](https://github.com/user-attachments/assets/c0c6bce9-4714-4bbb-98a0-3b423bbed307)
