### ISSUE TITLE
Greyed out

### ISSUE THREAD

**Issue by davcmitch2** [Acly/krita-ai-diffusion#546]
![image](https://github.com/Acly/krita-ai-diffusion/assets/165380573/d8dfa665-c6a8-46b8-af6e-34329041592d)
I downloaded krita 5.2. I used the new release, tried redownloading several times . Could not find my exact issue in the other threads so I made this one, Thanks,

**Comment by davcmitch2** [comment]
Hey I figured it out and no longer need help. Thanks

**Comment by alanjsebas** [comment]
How did you resolve it?
