### ISSUE TITLE
Error: Error: coroutine raised StopIteration

### ISSUE THREAD

**Issue by 1jackyleung** [Acly/krita-ai-diffusion#550]
Traceback (most recent call last):
  File "C:\Users\J\AppData\Roaming\krita\pykrita\ai_diffusion\connection.py", line 85, in _connect
    self._client = await ComfyClient.connect(url)
RuntimeError: coroutine raised StopIteration

Can someone tell me what this error is? I'm trying to connect Krita to my ComfyUI installation. I've installed all the required models. When I try to connect I get: Error: Error: coroutine raised StopIteration

**Comment by elopezga** [comment]
Install one of the recommended checkpoints.

**Comment by st-julian** [comment]
Error: coroutine raised StopIteration
this is my problem with this is alfter i put in everything 
i dont know what to do
