### ISSUE TITLE
IP-Adapter is not supported by this GPU

### ISSUE THREAD

**Issue by attyru** [Acly/krita-ai-diffusion#552]
Hello. Plugin version 1.16.0. I see this message when I select the "Reference" or "Face" tool. The thing is that on my video card (5700xt) IP-Adapter Plus works fine in Comfyui, I checked it in different workflows. Is it possible to make these tools work also in krita-ai-diffusion?
And thank you very much for your work - the plugin is great. I use different AI tools, but your plugin and krita are the best tools for spot editing!

**Comment by Acly** [comment]
It does look like the issues it had got resolved at some point, I'll remove the filter

**Comment by attyru** [comment]
Thank you, now all works)
