### ISSUE TITLE
RuntimeError: coroutine raised StopIteration

### ISSUE THREAD

**Issue by gregorio500** [Acly/krita-ai-diffusion#553]
While downloading the models for Krita-AI-Diffusion, I encountered this error: "RuntimeError: coroutine raised StopIteration." After reinstalling Krita, the issue with the server connection arose again.
Operating system: windows 11
Attached log files:
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14808694/server.log)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14808695/client.log)

**Comment by Acly** [comment]
You need to download/install at least one checkpoint. There are a few recommended ones you can select from the installer.

I'm fixing the error message to be more useful.
