### ISSUE TITLE
TTPLanet_SDXL_Controlnet_Tile_Realistic_V1 - Blur / upscale 

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#554]
I tried the model, TTPLanet_SDXL_Controlnet_Tile_Realistic_V1
The the layer blur works very very well, especially in photo Restoration, unbelievable. 
BUT!!! there is no way to disable it in upscale, 

So all up-scales basically break as in up-scaling, 
IE: Ai art with bad faces remain the same bad, prior upscale would change image depending on how much weight and fix images, unfortunately with TTPLanet_SDXL_Controlnet_Tile_Realistic_V1 it breaks upscale and the image stays the same when you don't want that.

Removing the control net to go back to how it was resulted in errors as its missing on upscale for me.
I'm currently reinstalling to fix it.

id love TTPLanet_SDXL_Controlnet_Tile_Realistic_V1 But just as a layer blur, but should be called (DeBlur) since that's what it does (blur sounds like a background bluring tool) 
Please can you make it able to be turned off in Upscale, I only want it as a layer option.

**Comment by Acly** [comment]
I'd argue that the idea of "upscaling" is usually that you _do_ want things to stay the same. I wouldn't expect it to fix faces or do other creative modifications by default when I just want a higher resolution.

But some more options like this for tiled diffusion probably makes sense. Not sure when I will get around to it though.

**Comment by Sil3ntKn1ght** [comment]
> I'd argue that the idea of "upscaling" is usually that you _do_ want things to stay the same. I wouldn't expect it to fix faces or do other creative modifications by default when I just want a higher resolution.
> 
> But some more options like this for tiled diffusion probably makes sense. Not sure when I will get around to it though.

On lower spec systems like my gtx1070 because lower canvas size when doing Ai bad faces hands etc are common plus low bad background details, upscale strength of 30 up fixes keeping original style look but rebuilding image, this is very handy.
I have do videos on this, ( streamtabulous ) "my prompt tips some trick and my methods" video, there is a lot low end systems so smaller canvas till you get what you want as faster renders then upscale to enhance finish and fix is fantastic. that what it does without TTPLanet_SDXL_Controlnet_Tile_Realistic_V1 - Blur / upscale #554 
But with  TTPLanet_SDXL_Controlnet_Tile_Realistic_V1 - Blur / upscale #554 nothing changes its just more pixels and sharper, its hand with photo resolution or perfect image only.
hence why needs a option to tick this on or off. 
I'm finding so so many that can't afford high end gpu's so the upscale with changes is important to anyone with RTX3060s i have a rtx3060 also and have found the same, or lower GPU Systems, At same time i teach photo Restorations and how to use your tool to better the process and  TTPLanet_SDXL_Controlnet_Tile_Realistic_V1 - Blur / upscale #554  blur layer is the best I have come across ever. 
Hence to wish for the option to have as layer use and untick so off in upscale for AI art use where those want the changes.

**Comment by Acly** [comment]
In v1.18.0 tile/unblur can now be disabled or set to lower strength.
