### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy.options'

### ISSUE THREAD

**Issue by marekbujko** [Acly/krita-ai-diffusion#56]
Hi,
in Server manager I'm getting these errors after auto install Local server:

2023-11-18 01:49:04,220 ERROR Traceback (most recent call last):

File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\ .server\ComfyUI\main.py", line 1, in <module>
import comfy.options

ModuleNotFoundError: No module named 'comfy'

2023-11-18 01:50:24,904 ERROR Traceback (most recent call last):

File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\ .server\ComfyUI\main.py", line 1, in <module>
import comfy.options

ModuleNotFoundError: No module named 'comfy.options'

**Comment by Acly** [comment]
Hi,
this sounds like the installation is broken somehow.
Your server path looks strange: `...\pykrita\ai_diffusion.server\ComfyUI`  - there is a `\` missing between `ai_diffusion` and `.server`. Unless that was on purpose? Or maybe accidentaly hit delete?

If you actually installed in that path that should be okay, but check if it contains both `ComfyUI\main.py` file and also `ComfyUI\comfy` folder. If one is missing, try deleting `ComfyUI\main.py`. This should allow you to click "Install" again and only replace the missing parts.

**Comment by marekbujko** [comment]
Path is correct, Github short path in message:
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\ .server\ComfyUI\main.py", line 1, in <module>
(I add gap now in EDIT first message)

**Comment by Acly** [comment]
Sounds like the path wasn't an issue, server or .server should both work, and what I saw was just a GitHub formatting issue.

I don't have a good explanation why the installation was broken first time round, but the error message indicated that some parts were really missing. Anyway, sometimes retrying is the easiest solution, glad it's running now.
