### ISSUE TITLE
AI LCM Live drawing is not working

### ISSUE THREAD

**Issue by stanleyshek** [Acly/krita-ai-diffusion#561]
I've installed Krita 5.2.2 and krita_ai_diffusion-1.16.1.  The server is running but as a draw, AI generated image just gave me what I drawn, not creating any image.  

![Screenshot 2024-04-01 012121](https://github.com/Acly/krita-ai-diffusion/assets/4930397/4716489e-108d-4896-a77c-023457a0e36c)
![Screenshot 2024-04-01 012059](https://github.com/Acly/krita-ai-diffusion/assets/4930397/afec36f4-1d80-455f-89ad-a50a2eb7cba7)

**Comment by BuzhidaoChiang** [comment]
if you use XL model, the strength need be set more 60%. 30% strength makes no changes.

**Comment by stanleyshek** [comment]
> if you use XL model, the strength need be set more 60%. 30% strength makes no changes.

Thanks, it seems start drawing after strength over 80%.

**Comment by Acly** [comment]
It should also work for 30% (it changes less of course, but it should be visible). What checkpoint are you using?

**Comment by stanleyshek** [comment]
> It should also work for 30% (it changes less of course, but it should be visible). What checkpoint are you using?

I use the cinematic photo XL, 30% really did nothing.  60% only smooth the shape.  Over 80% it start drawing but is cartoon style, not realistic even I put "realistic" in the prompt.[
![Screenshot 2024-04-02 203325](https://github.com/Acly/krita-ai-diffusion/assets/4930397/ffda9235-044e-40da-af6f-3ccb3535efca)
![Screenshot 2024-04-02 203144](https://github.com/Acly/krita-ai-diffusion/assets/4930397/6b499f98-69e6-4b50-911e-be36aabab9e0)
](url)

**Comment by stanleyshek** [comment]
lower one is 61% strength, upper is 88%.
