### ISSUE TITLE
ComfyUI-Setup page shows incorrect directory for IP-Adapter files

### ISSUE THREAD

**Issue by UrzasLegacy** [Acly/krita-ai-diffusion#562]
https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup

Required Models section show the IP-Adapter files should be in directory "custom_nodes/ComfyUI_IPAdapter_plus/models" when they should actually be in "models/ipadapter"

**Comment by PresTrembleyIIIEsq** [comment]
Is this why I'm seeing the following error, even after reinstalling both ComfyUI and the new updated version of `ComfyUI_IPAdapter_plus`, and confirming it works correctly in ComfyUI?

![Screenshot_20240331_162506](https://github.com/Acly/krita-ai-diffusion/assets/140981996/1c6a4ebb-7dcc-439f-818a-65569a65198b)

**Comment by d23lygjdpzok** [comment]
Hello, Acly, please uninstall the ipadapter_plus plugin and install the latest version. This error should occur after that, and I don't know how to fix it.

**Comment by Acly** [comment]
>Required Models section show the IP-Adapter files should be in directory "custom_nodes/ComfyUI_IPAdapter_plus/models" when they should actually be in "models/ipadapter"

Oh. Thought I'd changed that ages ago. Fixed now...
