### ISSUE TITLE
Live mode, no matter how many steps are set, only 4 steps are executed

### ISSUE THREAD

**Issue by huameiwei-vc** [Acly/krita-ai-diffusion#565]
<img width="879" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/125441847/e3b837b1-8e0b-4121-8a3f-ef6c2c783248">
<img width="758" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/125441847/0b7ed0db-4987-496b-9584-6d6e6ee2eebb">

**Comment by wenTongYU** [comment]
In this mode, the step relates to the strength directly, if you set 100% you will get full sampler steps in this setting. The minimal step is 4 by default.
![image](https://github.com/Acly/krita-ai-diffusion/assets/55220201/eec0f9b1-8e9b-4ddc-9a4a-5a0dc626697f)

**Comment by huameiwei-vc** [comment]
> In this mode, the step relates to the strength directly, if you set 100% you will get full sampler steps in this setting. The minimal step is 4 by default.在此模式下，该步骤与强度直接相关，如果设置为 100%，则在此设置下将获得完整的采样器步骤。默认情况下，最小步骤为 4。 ![image](https://private-user-images.githubusercontent.com/55220201/318647822-eec0f9b1-8e9b-4ddc-9a4a-5a0dc626697f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzY1NzMsIm5iZiI6MTcxMjAzNjI3MywicGF0aCI6Ii81NTIyMDIwMS8zMTg2NDc4MjItZWVjMGY5YjEtOGU5Yi00ZGRjLTlhNGEtNWEwZGM2MjY2OTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA1Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExOGMzN2Y3NjliNmVkZTcxZjk5ZjhiYmJiZDk0Mzc0NDRmNWVhNTg0MTZkOGJjNGIyMThhZWUyNGRlNTBlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BI89yUqN5u7FI9UNh6aqTLZ2QMkvkR73tscPp36NDLY)
> 
> 在此模式下，该步骤与强度直接相关，如果设置为 100%，则在此设置下将获得完整的采样器步骤。默认情况下，最小步骤为 4。

I tested it and indeed it is like this, thank you very much. How do you usually set it up for better results?

**Comment by wenTongYU** [comment]
Hard to say, it depends on your needs. In my experience, the 6 step is enough in live mode as same as other sample method. You can try set CFG to different values, it will give you better result with same steps that do not loss performance. BTW the different sample method need setting different CFG to get suitable results. But usually higher CFG results to more changes compare to your input image. I did some testing for that. 
![image](https://github.com/Acly/krita-ai-diffusion/assets/55220201/83f9b608-0e9e-4294-ab4c-3f6f88af97cf)

**Comment by huameiwei-vc** [comment]
> Hard to say, it depends on your needs. In my experience, the 6 step is enough in live mode as same as other sample method. You can try set CFG to different values, it will give you better result with same steps that do not loss performance. BTW the different sample method need setting different CFG to get suitable results. But usually higher CFG results to more changes compare to your input image. I did some testing for that.很难说，这取决于您的需求。根据我的经验，与其他示例方法一样，在实时模式下，6 步就足够了。您可以尝试将 CFG 设置为不同的值，它会以相同的步骤为您提供更好的结果，而不会损失性能。顺便说一句，不同的采样方法需要设置不同的 CFG 才能获得合适的结果。但与输入图像相比，通常更高的 CFG 结果会带来更多的变化。我为此做了一些测试。 ![image](https://private-user-images.githubusercontent.com/55220201/318718668-83f9b608-0e9e-4294-ab4c-3f6f88af97cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTAzMjksIm5iZiI6MTcxMjA1MDAyOSwicGF0aCI6Ii81NTIyMDIwMS8zMTg3MTg2NjgtODNmOWI2MDgtMGU5ZS00Mjk0LWFiNGMtM2Y2Zjg4YWY5N2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA5MjcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYjdkNzVjZjM1ZGExYzdhN2NmMGVkMDE4MmQwMDFkMzA4ZmY1ZDY2Nzc3Y2E2MDFkZTFmODc3YTZkOTZkOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8bu2DRnKOJ5V3NOSjdfnLS1qvywICGbT74PVT_KAos8)
> 
> 很难说，这取决于您的需求。根据我的经验，与其他示例方法一样，在实时模式下，6 步就足够了。您可以尝试将 CFG 设置为不同的值，它会以相同的步骤为您提供更好的结果，而不会损失性能。顺便说一句，不同的采样方法需要设置不同的 CFG 才能获得合适的结果。但与输入图像相比，通常更高的 CFG 结果会带来更多的变化。我为此做了一些测试。

Thanks, I tested it and at 30%, it's basically 4 steps, so I feel like it shouldn't have much of an impact.
