### ISSUE TITLE
[Feature Request] More Upscalers - SUPIR and APISR

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#566]
APISR: https://github.com/Kiteretsu77/APISR
SUPIR: https://github.com/Fanghua-Yu/SUPIR

**Comment by olegsatov** [comment]
Vote!

**Comment by SyamsQ** [comment]
How to instal it on Krita?

**Comment by Acly** [comment]
Moved to watchlist #779
