### ISSUE TITLE
Can’t find ControlNet model

### ISSUE THREAD

**Issue by dashiwawa** [Acly/krita-ai-diffusion#569]
Does anyone know how to fix this problem?
![IMG_8480](https://github.com/Acly/krita-ai-diffusion/assets/131458110/7e378aff-3d92-4177-ba46-de2dfe67c399)

I can use scribble in my ComfyUI but in krita it’s not working.

**Comment by qingzhenbiaojie** [comment]
检查一下comfy根目录-modle-controlnet里面是否装了scribble模型，或comfy 的custom note中的controlnet-modle

**Comment by dashiwawa** [comment]
> r
解決問題了，沒有模型在資料夾裡，重新下載後可以使用了，謝謝
