### ISSUE TITLE
Error: LCM LoRA model not found for SD 1.5

### ISSUE THREAD

**Issue by dmarx** [Acly/krita-ai-diffusion#57]
not only do i have the lora, i even have it loaded through the style option! i believe i installed this lora through comfy manager, so it should be in the expected location with the expected name. 

as a work around, maybe this could be a configurable option for when it can't be autodetected? there will probably be lots of different LCM loras soon (heck, there're already at least three), so all the more reason not to rely on autodetection probably.

**Comment by dmarx** [comment]
Ah, just found this: https://github.com/Acly/krita-ai-diffusion/blob/355793e81876dc27b635a8fb5e38acda42444f9c/doc/comfy-requirements.md?plain=1#L25

guess for now the lora file needs to be renamed, and the installation docs could be clarified a bit.

**Comment by dmarx** [comment]
after renaming the lora, i'm not getting the "lora not found" error anymore, but the live preview isn't doing anything either. the image remains unchanged on the canvas, and the preview in the docker is just black

**Comment by Acly** [comment]
As much as possible I go with the original names the model authors choose, but if it's something like "model" or "weights" like in this case it becomes an issue. There are currently 22 different models being detected and the list is growing, manual configuration sounds tedious. I can add whatever convention ComfyUI Manager uses to the recognized list though, as it is a popular option.

> the image remains unchanged on the canvas

I don't quite understand this remark, the idea is that you change the canvas, and the preview in the docker updates to reflect the changes. By black you mean it produces a black image (as opposed to it doesn't produce an image at all and you just see widget background)?

**Comment by raphatbho** [comment]
I can confirm the same issue. Even after renaming to lcm-lora-sdv1-5.safetensors or by using lcm installed using ComfyUI model installer (which creates a separate folder \lcm\SD1.5\pytorch_lora_weights.safetensors), still the error persists.

**Comment by Acly** [comment]
To be precise, v1.7.0 looks for a file which has "lcm-lora" or "lcm_lora" as well as "sd15" or "sdv1-5" in it's name.
Latest version from GIT now also allows combinations of "lcm", "SD1.5" and "pytorch_lora_weights".

If you're still getting "LCM LoRA model not found for SD 1.5" please double-check it's listed with the correct filename in ComfyUI's "Load LoRA" node.

**Comment by dmarx** [comment]
> I don't quite understand this remark, the idea is that you change the canvas, and the preview in the docker updates to reflect the changes. By black you mean it produces a black image (as opposed to it doesn't produce an image at all and you just see widget background)?
I mean the preview in the docker panel doesn't update and just shows a black image. the actual canvas remains unchanged from whatever it was before i turned live on. i'll send you a screenshot in a bit. 

also, for clarity: this is on ubuntu. if the live update assumes i'm running on windows, that would explain it.

**Comment by Acly** [comment]
No, there is nothing windows-specific about it. I just tested ubuntu and it works for me.

**Comment by raphatbho** [comment]
> To be precise, v1.7.0 looks for a file which has "lcm-lora" or "lcm_lora" as well as "sd15" or "sdv1-5" in it's name. Latest version from GIT now also allows combinations of "lcm", "SD1.5" and "pytorch_lora_weights".
> 
> If you're still getting "LCM LoRA model not found for SD 1.5" please double-check it's listed with the correct filename in ComfyUI's "Load LoRA" node.

It's working correctly on Comfy, both differently named options.

**Comment by Acly** [comment]
Good to hear. [Version 1.7.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.7.1) now also supports the Comfy Manager path, but I made filename requirements more strict to avoid confusing it with other potential LCM Lora.
I also added some more logging so the plugin reports what it's searching for, what it found, and whether it was a match. Should make diagnosing this stuff easier in the future I hope.

**Comment by dmarx** [comment]
so it seems to be recognizing that I'm making changes, but isn't showing them. here's what it looks like when krita emits a prompt to the server. concretely, i'm trying to duplicate your example from the video, where you manipulate an openpose skeleton. if i move a control point on the skeleton, i get at least one 6 step inference. so that much checks out. but i don't see anything update in previews or on the canvas

```
Prompt executed in 0.00 seconds
got prompt
Prompt executed in 0.00 seconds
got prompt
Requested to load ControlNet
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.19it/s]
Prompt executed in 1.67 seconds
got prompt
Requested to load ControlNet
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.21it/s]
Prompt executed in 1.68 seconds
got prompt
Prompt executed in 0.00 seconds
got prompt
```

**Comment by dmarx** [comment]
i just realized i'm running krita 5.0.2 and current version is 5.2.1. I'm going to try updating krita and see if that changes anything.

**Comment by husw725** [comment]
我就是一直报 not found,我最后是通过修改workflow.py的第299行 加载lora的那行代码实现的，写死成下载的模型

**Comment by d23lygjdpzok** [comment]
Dear friend, lcm lora 1.5 \ sdxl must be renamed and placed in the ComfyUI \ models \ loras \ directory, otherwise krita will not be able to find the path and recognize it.
For example:
E: \ ComfyUI \ models \ loras \ lcm lora sdv1-5. safetensors
E: \ ComfyUI \ models \ loras \ lcm lora sdv1-5. safetensors lcm lora sdxl. safetensors

**Comment by dqzxlbc** [comment]
lcm-lora-sdv1-5;lcm-lora-sdxl;lcm-lora-ssd-1b

**Comment by ZhianLin** [comment]
检查是不是lora文件名有大写字母 。我的lora在服务器上是大写，但是ai-diffusion1.9获取到的文件名是小写，导致client.py指定文件名还是提示 not found。
Check if the lora file name has uppercase letters.File name of my Lora is in uppercase on the server, but the file name obtained by ai-diffusion1.9 is in lowercase, causing client.py to still prompt 'not found' when specifying the file name.

![image](https://github.com/Acly/krita-ai-diffusion/assets/25313785/0bdc899e-d8bc-4577-a5cf-7264cdd4d32c)

**Comment by Maple-yoo** [comment]
you can download the base lora models,and rename it.
![git1](https://github.com/Acly/krita-ai-diffusion/assets/173487396/f2ee0820-0262-4def-a5e6-3b18e703b1d9)
![git2](https://github.com/Acly/krita-ai-diffusion/assets/173487396/1f8034c5-5cff-4d13-996e-7820707d889c)
