### ISSUE TITLE
Key Error 'Prompt_id' on Remote Server Connection

### ISSUE THREAD

**Issue by ckmwai** [Acly/krita-ai-diffusion#570]
Hi,

when i am connected to a custom server remote I get an Error: 'Prompt_Id' when I want to generate a picture. Live or just by Generating, doesn't matter.

Here from the Log:

`ERROR Error: 'prompt_id'
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 836, in _report_errors
    return await coro
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 176, in enqueue_jobs
    await self._enqueue_job(job, input)
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 182, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 151, in enqueue
    job_id = result["prompt_id"]
KeyError: 'prompt_id'`

I am connected to an Pod on runpod.io. I used the Docker Template that exists already there for deployment.
I am not sure if this maybe due to the ComfyUI installation on runpod, because this ComfyUI Installation seems a little bit outdated.
I already updated the ComfyUI Installation manually with git pull on the pod.

With my local installed server in krita it works fine. 
Use the Version 1.16.1 of the Plug in

Thanks for help!
Mic

**Comment by Acly** [comment]
Yes the docker image is outdated, I've been having trouble generating a new one (some connection issues).

Did you check the runpod log to see if ComfyUI printed an error?

**Comment by ckmwai** [comment]
Hi, 
sorry for the late response. I was able to test again two days ago. Now it works everything fine. 
I guess you updated it, right?

Thank you very much!
