### ISSUE TITLE
Initial loading very slow

### ISSUE THREAD

**Issue by visaeon** [Acly/krita-ai-diffusion#571]
As opposed to older versions in the newer versions of the plugin im finding the initial loading of models to be excruciatingly slow.
were talking a 5 to ten minute loading time for each model.
Once its loaded its fine but the wait times for model loading are crazy long.

**Comment by Reaper176** [comment]
Dont know if this ever got fixed for you over the passage of time but if not take a look at this. https://github.com/brendanhoar/comfyui-faster-loading
