### ISSUE TITLE
Regarding the masking tool used in real-time preview, an error was reported and stopped working!

### ISSUE THREAD

**Issue by qingzhenbiaojie** [Acly/krita-ai-diffusion#572]
After upgrading to version 1.16.1, ai starts normally, but as long as the mask tool is used, a red error message appears and the real-time function is suspended. I have checked that the url link is normal. What is the problem?
![微信截图_20240402171507](https://github.com/Acly/krita-ai-diffusion/assets/156321695/73c12d13-75e5-4da1-b7c4-8c828bff7bc3)

comfy console real-time log
![微信截图_20240402172609](https://github.com/Acly/krita-ai-diffusion/assets/156321695/34fa6561-1043-42dc-a9d5-ddf1932893fd)

**Comment by Acly** [comment]
Please update [comfyui-inpaint-nodes](https://github.com/Acly/comfyui-inpaint-nodes)

**Comment by qingzhenbiaojie** [comment]
@Acly thanks，it's OK now
