### ISSUE TITLE
Server execution error: 'ModuleList' object has no attribute '4'

### ISSUE THREAD

**Issue by planb788** [Acly/krita-ai-diffusion#58]
When I used openpose to recognize a pose, I adjusted a bone at will, and tried to create an image from the adjusted skeleton, I got an error message.
I am using the first way to connect to comfyui and have downloaded all the models through the program.

**Comment by planb788** [comment]
I am using the SSD1B model. When I changed it to the XL model, there was no error.

**Comment by Acly** [comment]
SSD1B is a changed base architecture compared to XL. It does not support ControlNet. As far as I know there are none available at this point. So short answer: the plugin doesn't support SSD1B.

It would be nice to have a better error message, I will have a look. Unfortunately it's not that easy to identify model architectures and what you got is just what comfyui spits out, which is not very helpful...

**Comment by planb788** [comment]
thanks!
