### ISSUE TITLE
ComfyUI_IPAdapter_plus got updated

### ISSUE THREAD

**Issue by AyKayORG** [Acly/krita-ai-diffusion#581]
ComfyUI_IPAdapter_plus got updated and the Apply IPAdapter node is gone. Now you have to use the "IP Adapter Advanced" Node insted. (Same Inputs and outputs, works the same)

Therefore I get an Error about a custom node missing on the server (self managed comfyUI install)
The Install link in the Error message leads me to the github repo I already have installed... but the newest versionof it... and downgrading would inhibit some of my other comfy workflows I am using.

Could you please look into this and update the Plugin accordingly?
Thank you for your amazing work!

**Comment by d23lygjdpzok** [comment]
I finally solved the issue with the ipadapter error. After downloading the 1.16.1 plugin, I had to manually install the plugin to C:\Users\admin\AppData\Roaming\krita\pykrita. After restarting Krita again, error messages started appearing, such as missing certain models. Eventually, I managed to resolve all the issues. 

This is my solution, and it worked. You can give it a try.

**Comment by AyKayORG** [comment]
Oh wow I kinda feel stupid now. Didn't really come to mind to try to update to the latest Plugin (checked the changenotes and didn't find something about that). Yeah installing the latest plugin and following the links to missing stuf solved the issue for me too...

Sorry Acly für this thread and thank you, again, for your outstanding work!!!
