### ISSUE TITLE
Failed to write Image to buffer

### ISSUE THREAD

**Issue by alkaris2** [Acly/krita-ai-diffusion#582]
Fresh installed the plugin, and then tried to generate something, and then it throws this Script Error about;

```
Exception: Failed to write Image to buffer [1280x720 format=4 -> webp@80
```

I hadn't changed any of the settings, everything is all on defaults, as I only just typed random text into the prompt section and clicked Generate, and the following contents was presented;

```python3
Exception
Python 3.11.8: /usr/bin/python3
Wed Apr  3 23:46:17 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/alkaris/.local/share/krita/pykrita/ai_diffusion/persistence.py in _save_results(self=<ai_diffusion.persistence.ModelSync object>, job=<ai_diffusion.jobs.Job object>)
  114             slot = self._slot_index
  115             self._slot_index += 1
  116             image_data, image_offsets = job.results.to_bytes()
  117             self._model.document.annotate(f"result{slot}.webp", image_data)
  118             self._history.append(_HistoryResult(job.id or "", slot, image_offsets, job.params))
image_data undefined
image_offsets undefined
job = <ai_diffusion.jobs.Job object>
job.results = <ai_diffusion.image.ImageCollection object>
job.results.to_bytes = <bound method ImageCollection.to_bytes of <ai_diffusion.image.ImageCollection object>>

 /home/alkaris/.local/share/krita/pykrita/ai_diffusion/image.py in to_bytes(self=<ai_diffusion.image.ImageCollection object>, format=<ImageFileFormat.webp: ('webp', 80)>)
  448         for img in self:
  449             offsets.append(result.pos())
  450             img.write(result, format)
  451         result.close()
  452         return data, offsets
img = <ai_diffusion.image.Image object>
img.write = <bound method Image.write of <ai_diffusion.image.Image object>>
result = <PyQt5.QtCore.QBuffer object>
format = <ImageFileFormat.webp: ('webp', 80)>

 /home/alkaris/.local/share/krita/pykrita/ai_diffusion/image.py in write(self=<ai_diffusion.image.Image object>, buffer=<PyQt5.QtCore.QBuffer object>, format=<ImageFileFormat.webp: ('webp', 80)>)
  339         result = writer.write(self._qimage)
  340         if not result:
  341             raise Exception(
  342                 f"Failed to write image to buffer [{self.width}x{self.height} format={self._qimage.format()}] -> {format_str}@{quality}"
  343             )
builtinException = <class 'Exception'>
Exception: Failed to write image to buffer [1280x720 format=4] -> webp@80
    __cause__ = None
    __class__ = <class 'Exception'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of Exception object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of Exception object>
    __doc__ = 'Common base class for all non-exit exceptions.'
    __eq__ = <method-wrapper '__eq__' of Exception object>
    __format__ = <built-in method __format__ of Exception object>
    __ge__ = <method-wrapper '__ge__' of Exception object>
    __getattribute__ = <method-wrapper '__getattribute__' of Exception object>
    __getstate__ = <built-in method __getstate__ of Exception object>
    __gt__ = <method-wrapper '__gt__' of Exception object>
    __hash__ = <method-wrapper '__hash__' of Exception object>
    __init__ = <method-wrapper '__init__' of Exception object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of Exception object>
    __lt__ = <method-wrapper '__lt__' of Exception object>
    __ne__ = <method-wrapper '__ne__' of Exception object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of Exception object>
    __reduce_ex__ = <built-in method __reduce_ex__ of Exception object>
    __repr__ = <method-wrapper '__repr__' of Exception object>
    __setattr__ = <method-wrapper '__setattr__' of Exception object>
    __setstate__ = <built-in method __setstate__ of Exception object>
    __sizeof__ = <built-in method __sizeof__ of Exception object>
    __str__ = <method-wrapper '__str__' of Exception object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    add_note = <built-in method add_note of Exception object>
    args = ('Failed to write image to buffer [1280x720 format=4] -> webp@80',)
    with_traceback = <built-in method with_traceback of Exception object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/alkaris/.local/share/krita/pykrita/ai_diffusion/persistence.py", line 116, in _save_results
    image_data, image_offsets = job.results.to_bytes()
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alkaris/.local/share/krita/pykrita/ai_diffusion/image.py", line 450, in to_bytes
    img.write(result, format)
  File "/home/alkaris/.local/share/krita/pykrita/ai_diffusion/image.py", line 341, in write
    raise Exception(
Exception: Failed to write image to buffer [1280x720 format=4] -> webp@80
```

What's weirder is the fact that it still manages to generate (an) image, but only does 1 image from what it's worked out from the prompt.

**Local installed** server on **Manjaro Linux** with **Krita 5.2.2**.

If I go to the WebUI and generate prompts from there I get no errors like shows in Krita, it passes without issue.

**Comment by DrewAlderfer** [comment]
Same problem here, although I updated by pulling the repo.

my steps:

1. Open new image 1024 x 1024 @ 72 dpi
2. Scribble on canvas.
Using default style 'Cinematic Photo':
3. Add scribble layer to controlnet layers
4. Click Generate 
5. Error (same as above)

When I exit out of the error popup an image does appear in the generator feed.

I'm using the plugin managed server on Arch, and installed the krita plugin with the git clone method described in the contributor instructions.

**Comment by Acly** [comment]
How did you install Krita? AppImage, Flatpak, Package manager?

It looks like on your system (Py)Qt5 can't write .webp images. It might be some extra component/package that's not installed. In this case it's used to persist the history in the .kra files, so while ignoring the error may seem to work, likely storing the history does not. It's also used in some other cases when transferring images.

> I can't make much out from the error message, and I'm not sure how to log from a krita plugin (print(result) didn't print to the console I started krita from).

Hm, `print` usually works for me. You could also try to put more info into the exception message. QImageWriter has a `errorString()` method which would be interesting. I should've probably added that :)
```
raise Exception(
    f"Failed to write image to buffer {writer.errorString()} ...
```

**Comment by DrewAlderfer** [comment]
The errorString:
 "Unsupported image format"

I've been using the plugin and it seems to behave mostly normally, but I noticed that I cannot right click 'save image' on generated results. And in some circumstances the live image generation will stop updating.

I will look into what might be missing for .webp on my system.

I installed the plugin by cloning the repo and symlinking it to the pykrita folder.

I suspect this is unrelated but I am getting errors in the terminal when starting Krita:

```
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_generate"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_cancel"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_cancel_queued"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_cancel_all"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_toggle_preview"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_apply"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_switch_workspace_generation"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_switch_workspace_upscaling"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_switch_workspace_live"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_toggle_workspace"
NOT COOL: Duplicated action name from xml data:  "ai_diffusion_settings"
```

**Comment by freeo** [comment]
Confirming installing `qt5-imageformats` fixes this error for arch.

**Comment by Acly** [comment]
Thanks for trying it out, I extended the error message to include advice about the package for now.

Maybe will have to consider automatic fallback to jpg/png, but jpg quality is... bad :\

**Comment by lboklin** [comment]
Would it be possible for you to keep this issue open until a fallback has been implemented? I'm using Krita from nixpkgs, which apparently doesn't have this dependency (and as evidenced by this issue it may not be present on all systems; adding the dep for the nix package wouldn't help those others that are affected on other distros).

**Comment by martinsmid** [comment]
On ubuntu, the package name that fixed it was `qt5-image-formats-plugins`. Thank you

**Comment by moonwhaler** [comment]
Just reporting in to inform that I had the same issue with my Arch Linux install. The hint to install "qt5-imageformats" (via pacman) fixed the issue. Thank you.

**Comment by nerochiaro** [comment]
> On ubuntu, the package name that fixed it was `qt5-image-formats-plugins`. Thank you

This suggestion fixed it for me as well on Ubuntu 24.04.01

**Comment by mailee01** [comment]
> Confirming installing `qt5-imageformats` fixes this error for arch.

can you tell me how to download and install qt5-imageformats to fix that issue. I have the same issue, "server execution error fail to load image 0 from buffer". I use Window

**Comment by mmxgn** [comment]
@lboklin and others using Nix:

This fixed it for me:

```nix
nix-shell -p 'with import <nixpkgs> {}; krita.overrideAttrs (oldAttrs: { buildInputs = oldAttrs.buildInputs ++ [ libsForQt5.qt5.qtimageformats ]; })'
```

Alternatively, replace `krita` on your `home-manager` or `systemPackages` with:

```nix
      (krita.overrideAttrs (oldAttrs: {
        buildInputs = oldAttrs.buildInputs ++ [  libsForQt5.qt5.qtimageformats ];
      }))
```
