### ISSUE TITLE
Feature request: Ip Adapter presets

### ISSUE THREAD

**Issue by ryukra** [Acly/krita-ai-diffusion#584]
It would be nice if there was a seperate settings page where you could create IP adapter presets like how foooocus allows 4 images. 
IP adapter inputs are mostly square so handling them as a layer seems a hassle and sometimes you want multiple images.
You could use clothes + face ip adapter in one preset for a specific character.

**Comment by Acly** [comment]
Although they don't necessarily match the image dimensions, using layers as inputs has some advantages:
* Can easily cut/crop the image to be square and show relevant content
* Can easily use the actual image as input, this is quite useful for expand/outpaint, or just at low strength to be more style preserving

I don't think it's that much hassle to add an external image? I usually copy the image, press Ctrl+V in Krita (which inserts it as layer and makes it active), then click the add-control-layer button (which automatically uses the active layer). Not sure how to do it any faster tbh.

Regarding presets: I think this might fit into the general request to have inputs (prompts/control/etc) somehow attached to image areas or layers. Unfortunately diffusion isn't layer aware (and layer diffusion is like 50% there but missing img2img). Doing it manually via presets is also an option but more tedious than I'd like.

**Comment by Acly** [comment]
In v1.18.0 you can now setup IP-Adapter individually for different areas in the image.
