### ISSUE TITLE
prompt add lora not saved or coüpied

### ISSUE THREAD

**Issue by Codeschreibaer** [Acly/krita-ai-diffusion#586]
I’ve noticed that when integrating LoRA models into the prompt in the Krita plugin, the added LoRA model does not persist when copying the prompt or reopening the project. It would be beneficial if the LoRA model integration remained intact even after these actions. This feature would enhance the user experience by allowing consistent and convenient use of LoRA models across different prompts and sessions. (or is it a bug?)

Thank you for considering this enhancement!

**Comment by Codeschreibaer** [comment]
Correction; it does save of lora addings in prompts.
But it still doesnt copy them  by clicking copy prompt  in the context menu.
(It just didnt **save** in my example because it was lost before while copying prompt.)

**Comment by Acly** [comment]
Fixed in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
