### ISSUE TITLE
更新到1.16.1时出现了让我安装[ComfyUI_IPAdapter_plus]但我已安装

### ISSUE THREAD

**Issue by zty18cm** [Acly/krita-ai-diffusion#589]
我已经安装了[ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus)插件，但在更新到1.16.1时出现了让我安装[ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus)的错误，在此之前的版本是可以正常使用的
<img width="330" alt="{044AD945-D60E-4a52-A6B5-9164A176CAF8}" src="https://github.com/Acly/krita-ai-diffusion/assets/155368219/61fa402d-7828-4d25-8bcf-5dabde6d536f">

**Comment by zty18cm** [comment]
我找到了问题所在，要将C:\Users\11821\AppData\Roaming\krita\pykrita中的插件文件完全删除，并安装全新的1.16.1的插件文件

**Comment by Blacksage81** [comment]
This issue should Pinned and closed, I translated the OP's reply and it reads, "I found the problem. I need to completely delete the plug-in files in C:\Users\11821\AppData\Roaming\krita\pykrita and install a new 1.16.1 plug-in file."
