### ISSUE TITLE
Prompts/Text disappear during LIVE

### ISSUE THREAD

**Issue by edmondyang81** [Acly/krita-ai-diffusion#59]
![image](https://github.com/Acly/krita-ai-diffusion/assets/119105240/fd4201a3-3c30-4afa-9806-51736ebd8591)

Anybody got the same issue?

**Comment by Acly** [comment]
After experimenting a bit I think I know what you mean. It seems to scroll to a second line of text, can happen when selecting text and moving mouse down. I can bring the text back by selecting in upwards direction (or keyboard up).

Anyway it's annoying it happens even if there isn't a second line of text, I think I will switch to a strict one-line widget to fix it.

**Comment by edmondyang81** [comment]
Also a user based error, I used to press enter after modifying a prompt, that’s why it’s disappeared 😂 but it would’ve helped with two lines 🙏🏼
