### ISSUE TITLE
Stuck on "Starting server..."

### ISSUE THREAD

**Issue by ronnie-code** [Acly/krita-ai-diffusion#591]
After clicking launch, stuck on "Starting server..."
![Issue](https://github.com/Acly/krita-ai-diffusion/assets/69150781/7e568dda-9ac8-40a3-8b36-ddfec54b3296)

**Comment by Acly** [comment]
* First, update to latest version
* Please post server.log if it still happens

**Comment by ronnie-code** [comment]
I've already installed the latest version but issue is the same. Is it because on my 1050ti 4 GB VRAM? It not then please suggest further.

**Comment by Acly** [comment]
Screenshot looked old, that's why I asked. Anyway, click View log files, post server.log contents for more info.
