### ISSUE TITLE
Generated characters didn't follow the original pose

### ISSUE THREAD

**Issue by davide445** [Acly/krita-ai-diffusion#592]
Starting from the hilighted images and pose, I tried to generate different versions of the character, with the idea of them following the original pose

![image](https://github.com/Acly/krita-ai-diffusion/assets/33984290/5627d9d4-8c5a-4f39-9c14-8bcb99e4b4cf)

They have all different pose from the original one.

**Comment by rbfbatx** [comment]
Open pose hasn't worked for me since I started using SDXL Turbo and Lightning checkpoints. It works for in painting but is ignored for generating at 100%. I generally use depth now.
