### ISSUE TITLE
Better LoRA lookup / navigation

### ISSUE THREAD

**Issue by local306** [Acly/krita-ai-diffusion#595]
I am a new user (and maybe I'm missing something) and I find navigating the dropdown menu for adding in LoRAs incredibly difficult when you have a large library of items. I'm coming from A1111 + ComfyUI where I already have quite a few LoRAs in my directory.

For whatever reason my list is partially sorted alphabetically. It somehow sorts them A-Z for a group, and then starts over a-z again. 

Additionally, when I go to type the first letter to jump to a point in the list it will select the first LoRA it comes across with that letter. The dropdown menu always seems to want to start from the beginning regardless of current selection. Scrolling through from the beginning every time is tedious. 

If the dropdown menu behaved more like the model dropdown where typing a letter jumps to that spot rather than selecting a LoRA would help. Or if there was an option to manually type in the LoRA instead would also be very helpful.

**Comment by Acly** [comment]
I also think maybe a combo box with search/filter functionality would be better. But it would loose the hierarchical discovery part of the current menu solution (which people also want). Combining both is probably quite a bit of work due to custom UI.

**Comment by local306** [comment]
Would it be easy to add in a similar search functionality as the model lookup where you can type a key to jump to that point in the list? Also, can the list sort not be case sensitive? Seems weird navigating it from #, A-Z, and then a-z.

**Comment by Acly** [comment]
Improved search/filter/sorting in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
