### ISSUE TITLE
Preset Always Duplicated for Unknown Reason

### ISSUE THREAD

**Issue by raniaamina** [Acly/krita-ai-diffusion#596]
Hi, this recently happen in latest version

![gambar](https://github.com/Acly/krita-ai-diffusion/assets/22146607/d3c962ed-e41f-46ce-a8be-df987dd07fda)

I Tried to clean up the preset style directory, then add a file there, but in Krita it show as two list. Sometimes, when i try to update one of them it will revert back to last condition before update when i close the plugin setting dialog.

**Comment by Acly** [comment]
It's likely a folder mix-up.
Plugin installation and pre-installed styles should be in `.../krita/pykrita/ai_diffusion`
User settings and custom styles should be in `.../krita/ai_diffusion`

If somehow both folders are the same you get this doubling behavior.

**Comment by raniaamina** [comment]
Ah, i recheck the folder structur and it causing problem.
So, i got problem when save plugin and style in `krita/ai_diffusion` directly, after move it into `krita/pykrita/ai_diffusion` and separate style file to  `krita/ai_diffusion` the problem solved.
