### ISSUE TITLE
Super simple to fix feature request - increase the number of digits in the seed nr

### ISSUE THREAD

**Issue by Drexel78** [Acly/krita-ai-diffusion#597]
Currently only 9 digits are allowed in the seed nr when generating AI images, which is not enough to reproduce most images on Civitai and other homepages with all parameters used. Please change the property of this box from 9 to at least 14 :)

Keep up the good work!

**Comment by Acly** [comment]
Qt (GUI library) number box allows values up to 2^31, so it's actually not simple to fix!

Even if it was possible to use the seed value I doubt you will reproduce images exactly though, too many things that have an influence and change things quite radically...

**Comment by Drexel78** [comment]
Maybe a separate item, but on the topic of things that can result in discrepancies - is it possible to change the seed calc from gpu to cpu? Apparently using the GPU for seed generation is problematic since it is not the same between computers. I guess the seed on CivitAi is cpu based, otherwise its meaningless.

**Comment by Acly** [comment]
The seed you see is always computed on CPU.

There may be an additional seed for randomness introduced by SDE samplers, which is computed on GPU.
