### ISSUE TITLE
Error: server is missing one or more custom nodes

### ISSUE THREAD

**Issue by djdance** [Acly/krita-ai-diffusion#60]
I've installed it by "one click"
It has downloaded 12Gb to ComfyUI, but can not properly start the server.
What should I do with it? Thanks

Win11

![image](https://github.com/Acly/krita-ai-diffusion/assets/2269720/d1bfb2f6-22f1-4290-bfb2-e259e9eb3882)

**Comment by djdance** [comment]
Ah, resolved.
Need to run ComfyUI one time, stop it, and then launch from the plugin again.

**Comment by Acly** [comment]
Hm, something seems to have fixed the issue, I'm curious what it was but it's probably hard to figure out now. Typically the server should start up without errors automatically right after installation. I just tried a fresh install with same package selection but didn't encounter the error.
