### ISSUE TITLE
Can't use the Ai

### ISSUE THREAD

**Issue by Cozy888** [Acly/krita-ai-diffusion#600]
Every time i tried the function expand or fill i got these error - "Server execution error: Expected query, key and value to have the same dtype".

**Comment by Acly** [comment]
Which GPU? Which OS?

**Comment by Cozy888** [comment]
Sorry for being so vague.
nvidia geforce gtx 1050 ti
Windows 10
Krita version - 5.2.2

**Comment by Acly** [comment]
Did this happen with empty prompt? Does adding a text prompt avoid it?

See #500

**Comment by Cozy888** [comment]
Yes with empty prompt and yes adding a text prompt avoids it.
Tried to add  on settings.json the "--force-fp32" or "--force-fp16" but it still gives me the error with the empty prompt.
