### ISSUE TITLE
DPM++ 3M sampler

### ISSUE THREAD

**Issue by qlewer** [Acly/krita-ai-diffusion#602]
Hi, nice work, thanks for plugin!
I have a question. Firstly I try 'local' mode, it works fine, but I no find 3M sampler in options. Then.. I install separately ComfyUI, where 3M is ready (and I install all depends for plugin), run Comfy server, Krita connect succesfully, all working fine, go to plugin options, but... 3M sampler is no there =) What need to do for use him?

**Comment by Acly** [comment]
3M samplers are not exposed (I think they're a bit useless tbh). See #497 for potential plans/ways to add them.

**Comment by qlewer** [comment]
OK, thx for answer!
