### ISSUE TITLE
Cinematic Photo and realisticvisionv51_51vae.safetensors 

### ISSUE THREAD

**Issue by mocat15** [Acly/krita-ai-diffusion#603]
When I ran the AI Image Generation plug-in in Krita 5.2.2, I received the following error:

_the checkpoint 'realisticvisionv51_51vae.safetensors' used by style 'cinematic photo' is not available on the server_

To give more context, I'm running my main ComfyUI instance in the background and connecting through the Custom Server option.  I went through the whole list of models, nodes, and checkpoints that I needed to install.

As I dug through the settings, I noticed that the VAE is set to Checkpoint Default.

I downloaded realisticvisionv51_51vae.safetensors from HuggingFace and saved it to the models/VAE folder.  This fixed the error.

This likely happened because I used my existing ComfyUI instance and did not install a fresh new instance via Krita.  The plug-in is working great - it made a better background replacement than any free web-based tool so far!

I wanted to post this just in case some other person had this problem with the missing VAE.  Take care, and keep creating!

**Comment by Acly** [comment]
Cinematic Photo is one of the default styles, and it is set to use realisticvisionv51_51vae checkpoint. If you try to use it without that checkpoint, you get the error. But you can choose a different checkpoint in style settings, or create your own style - then it should work.

You don't _have_ to download this checkpoint, and it's not required or used for the VAE if you use a different one.

> This likely happened because I used my existing ComfyUI instance and did not install a fresh new instance via Krita

That's also okay, you can switch back and forth anytime.
