### ISSUE TITLE
[Feature Request]  IP Adapter Plus - Style Transfer And Composition

### ISSUE THREAD

**Issue by kubilaykilinc** [Acly/krita-ai-diffusion#604]
Recently, there have been very important improvements in IP Adapter Plus, which is a Comfyui custom node. It would be great to be able to optionally use all the features of Ipadapter Plus and Style transfer and Compositon transfer features in Krita Diffusion.

**Comment by Ahcool123** [comment]
Thanks a lot for adding this feature, but today April 11th after I installed the latest version, when linked, it always appears：Error: The following ComfyUI custom nodes are missing:
IP-Adapter https://github.com/cubiq/ComfyUI_IPAdapter_plus
Please install them, restart the server and try again.

I already have the latest IPAdapter_plus installed.

**Comment by Acly** [comment]
Added in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
