### ISSUE TITLE
Assertion error after "remove object"

### ISSUE THREAD

**Issue by Melo2323** [Acly/krita-ai-diffusion#605]
Facing issue of Assertion error after using "remove object", did a fresh install of local server, the issue still persist
After error popped up, its the end for that krita file, any further generation will pop up error...

**Comment by Acly** [comment]
Please post assertion error message and the [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files)

**Comment by Melo2323** [comment]
> Please post assertion error message and the [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files)

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\sdd\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py in update_content(self=<ai_diffusion.ui.diffusion.ImageDiffusionWidget object>)
  126             self._frame.setCurrentWidget(self._welcome)
  127         elif model.workspace is Workspace.generation:
  128             self._generation.model = model
  129             self._frame.setCurrentWidget(self._generation)
  130         elif model.workspace is Workspace.upscaling:
self = <ai_diffusion.ui.diffusion.ImageDiffusionWidget object>
self._generation = <ai_diffusion.ui.generation.GenerationWidget object>
self._generation.model = <ai_diffusion.model.Model object>
model = <ai_diffusion.model.Model object>

 C:\Users\sdd\AppData\Roaming\krita\pykrita\ai_diffusion\ui\generation.py in model(self=<ai_diffusion.ui.generation.GenerationWidget object>, model=<ai_diffusion.model.Model object>)
  591             self.custom_inpaint.model = model
  592             self.queue_button.model = model
  593             self.history.model_ = model
  594             self.update_generate_button()
  595 
self = <ai_diffusion.ui.generation.GenerationWidget object>
self.history = <ai_diffusion.ui.generation.HistoryWidget object>
self.history.model_ = <ai_diffusion.model.Model object>
model = <ai_diffusion.model.Model object>

**Comment by Acly** [comment]
This error you got right when you loaded a .kra file which previously showed the error, yes?

I'm not sure it has something to do with remove object, but it might be that this is triggered if the generated image is exactly the size of the thumbnail (I think 192x192 at the moment)

Removing the assertion shouldn't do any harm. If you want to give it a try:
* Open `C:\Users\sdd\AppData\Roaming\krita\pykrita\ai_diffusion\image.py` file with a text editor
* Go to line 269 which says `assert img.extent != target`
* Delete that line

The file should load after that.

**Comment by Acly** [comment]
Also if you could share the .kra file, that would be helpful.

**Comment by Melo2323** [comment]
> This error you got right when you loaded a .kra file which previously showed the error, yes?
> 
> I'm not sure it has something to do with remove object, but it might be that this is triggered if the generated image is exactly the size of the thumbnail (I think 192x192 at the moment)
> 
> Removing the assertion shouldn't do any harm. If you want to give it a try:
> 
> * Open `C:\Users\sdd\AppData\Roaming\krita\pykrita\ai_diffusion\image.py` file with a text editor
> * Go to line 269 which says `assert img.extent != target`
> * Delete that line
> 
> The file should load after that.

Yes,trying to generate a 192 x 192 and then the error pop up.
After deleting the line as you said, it solved the problem. Thanks!

**Comment by Melo2323** [comment]
> Also if you could share the .kra file, that would be helpful.

Normally the resolution would be 1216 x 832, I encountered the error mostly when using remove content to remove small artifacts,probarly hitting the 192x192 zone

**Comment by Acly** [comment]
Fixed in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
