### ISSUE TITLE
Can you help me see how I can solve this problem?

### ISSUE THREAD

**Issue by Ahcool123** [Acly/krita-ai-diffusion#606]
Thanks a lot for adding this feature, but today April 11th after I installed the latest version, when linked, it always appears：Error: The following ComfyUI custom nodes are missing:
IP-Adapter https://github.com/cubiq/ComfyUI_IPAdapter_plus
Please install them, restart the server and try again.

I already have the latest IPAdapter_plus installed.

**Comment by Acly** [comment]
The latest plugin version (1.16.1) works with latest IP-adapter nodes. Usually this error boils down to either one being too old, or not having updated properly. The plugin version should show in the log files and at the bottom of the settings. See #542 for things to check.
