### ISSUE TITLE
Error: Error transferring http//127.0.0.1:8188/prompt - samer replied: Internal sarver Error lurl=http://127.0.0.1:8188/prompt, code=401]

### ISSUE THREAD

**Issue by carmo2011** [Acly/krita-ai-diffusion#612]
when i select the region, and use fill function, the error happened.
even the live mode, if i select one region, the error also happened.
![image](https://github.com/Acly/krita-ai-diffusion/assets/87646057/455be6f0-2d71-4de8-a035-7cf87efb4fdc)

ERROR Error: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error
Traceback (most recent call last):
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 836, in _report_errors
    return await coro
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 601, in _continue_generating
    new_input = await self._model._generate_live(self._last_input)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 254, in _generate_live
    await self.enqueue_jobs(input, JobKind.live_preview, JobParams(bounds))
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 176, in enqueue_jobs
    await self._enqueue_job(job, input)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 182, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 150, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 143, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error

**Comment by Acly** [comment]
Please check/post the server.log (or ComfyUI output if you're running yourself)

**Comment by jovly** [comment]
> 当我选择区域并使用填充功能时，发生了错误。即使是实时模式，如果我选择一个区域，错误也会发生。 ![image](https://private-user-images.githubusercontent.com/87646057/321927163-455be6f0-2d71-4de8-a035-7cf87efb4fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzM1OTEsIm5iZiI6MTcxMjkzMzI5MSwicGF0aCI6Ii84NzY0NjA1Ny8zMjE5MjcxNjMtNDU1YmU2ZjAtMmQ3MS00ZGU4LWEwMzUtN2NmODdlZmI0ZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE0NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MjczOGQ2ZjRkODY1MDU2MDM3ZTdhZDVkODQ0MDNjZWVkMjdjZDZlY2QwNjJiZWE5MGM5YmFkZjRkZmZjNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B10h8fefgPb8xRRKArFTATj41DmyYHimEj5zYUEgi00)
> 
> 错误错误：传输 http://127.0.0.1:8188/prompt 时出错 - 服务器回复：内部服务器错误回溯（上次调用）：文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py”，第 836 行，在 _report_errors 返回 await coro 文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py”，第 601 行，在 _continue_generating new_input = await self._model._generate_live（self._last_输入） 文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py”，第 254 行，在 _generate_live 等待 self.enqueue_jobs（输入、JobKind.live_preview、JobParams（bounds）） 文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py”，第 176 行，在 enqueue_jobs 等待 self._enqueue_job（job， input） 文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py”， 第 182 行，在 _enqueue_job 中 job.id = await client.enqueue（input， self.queue_front） 文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py”，第 150 行，在队列中 result = await self._post（“prompt”， data） 文件“C：\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py”，第 143 行，_post返回 await self._requests.post（f“{self.url}/{op}”， data） ai_diffusion.network.NetworkError：传输 http://127.0.0.1:8188/prompt 时出错 - 服务器回复：内部服务器错误

Less models in comfyui.

**Comment by carmo2011** [comment]
thanks for the solution, comfyui inpaint node need update,thanks.
