### ISSUE TITLE
[Feature Request] Make the '[Live]' in the name of the output layer optional

### ISSUE THREAD

**Issue by DrFisura** [Acly/krita-ai-diffusion#613]
Pretty much what says in the title. This would be a feature request.

I often find myself pressing F2 on the name of a layer to quickly copy and paste its name to reuse the prompt, but I have to delete that '[Live]' part first every time. Having an option to tell the program not to write it in the first place would help, I just want the prompt.

I'm not sure if this would be hard to implement code-wise.

A possible addition, too, would be to add the seed instead at the start of the name, because I often use the layer name to store it, along with the prompt. You could implement these via adding a check box.

Help me evaluate whether this is a viable option to implement.

**Comment by Acly** [comment]
You can modify it here: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/model.py#L615
Changing to something like `f"{self._model.prompt} {self._model.seed}"` should work.
Note that's the current seed, not neccesarily the one used in last generated result, but in live mode it's usually the same.

I don't really like creating options and checkboxes for this sort of thing unless there's a compelling reason. We can just change it and unless somebody cries out they really want that [Live] prefix back, it's probably fine...

**Comment by DrFisura** [comment]
Your solution, of course, works. And your perspective is clearly superior. Had I known this myself, I probably wouldn't have bothered to ask for a checkbox. This just works!

And if you don't want to add too many checkboxes to avoid cluttering that's probably for the best. You can just change it then and it'll probably be fine. Up to you, my liege. Again, thank you.
