### ISSUE TITLE
[Suggestion and Feature Reguest for Inference] To Add e.l.l.a+sd cascade and wurstchen

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#615]
is it possible to integrade and Merge inference UI with Stable Cascade+Wurstchen and E.L.L.A since its already available in Comfy UI https://ella-diffusion.github.io/ https://github.com/TencentQQGYLab/ELLA and Eventually SD 3

**Comment by Acly** [comment]
I think Pixart Sigma is also very promising. But it all depends on if it is adopted, the plugin really needs the ecosystem, control net, inpaint, ip adapter, everything working together. I'm also inclined to wait how good prompt understanding is on Pixart/Sigma + SD3 before going for something like ELLA (another heavy model just for text, which is not so much a focus here).
