### ISSUE TITLE
where to find the control layer models,such as face, hand

### ISSUE THREAD

**Issue by carmo2011** [Acly/krita-ai-diffusion#617]
![image](https://github.com/Acly/krita-ai-diffusion/assets/87646057/fac13a8a-ad39-4f0b-99c6-5833826d3a40)
Are there any instruction documents for these features usage?
I know how to use some of them, such as canny, depth.
but i don't know how to use and where to find models for face, hand layer functions.
any one know that? pls help, thanks a lot.

**Comment by rbfbatx** [comment]
There are several controlnet guides out there and tons of videos on YouTube. Search "control net hands" or control net depth. "

**Comment by Acly** [comment]
There's no dedicated documentation yet. [Release notes](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0) have some info and model downloads.
