### ISSUE TITLE
Function added

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#618]
Hello! Hope the following features can be added, thank you very much!
1. Prompt word inference, you can add a local picture, if you don’t add a local picture, it will be inferred from the selection, if there is no selection, it will be inferred from the canvas.
2. LayerDiffuse
3. Facial protection and face changing function
4. Remove the background, cover it with a mask in the layer, and you can call masking to generate the image

**Comment by Acly** [comment]
1. See #372 - not planned for now, without using a large text model the results are very poor and not useful
2. See #453
3. FaceID is already supported (Face control layer) - you mean something else?
4. Check https://github.com/Acly/krita-ai-diffusion/wiki/Inpainting#replace-background - if you need segmentation tool, there is https://github.com/Acly/krita-ai-tools
