### ISSUE TITLE
Not enough gpu memory on 8GB vram GPU

### ISSUE THREAD

**Issue by marekkloc1** [Acly/krita-ai-diffusion#619]
Hello I need help with this problem, I know that such a discussion has already been created but I have not found any other, the thing is that I have in my computer wi 8GB vram graphics card AMD Radeon 6600 RX, only that the graphics requirement is 6GB so krita does not generate me any image because of this error. Could someone please kindly advise me how to solve this? Thank you.

My CPU : AMD Ryzen 7 3700X
Ram in total: 32GB
GPU: AMD Radeon 6600 RX

Error code > failed: Could not allocate tensor with 1026555904 bytes. There is not enough GPU video memory available!

![Screenshot_7](https://github.com/Acly/krita-ai-diffusion/assets/107433668/adabd51d-72a3-41fa-a915-4d4a23f1e924)

**Comment by Acly** [comment]
6GB is a ballpark minimum to use most functionality on NVIDIA, but the actual VRAM required depends on a lot of things like SD1.5 vs SDXL (XL uses much more), image resolution, number of control layers...
Also AMD typically uses 2x the memory compared to NVIDIA on Windows, the support is not very good unfortunately.

Did you try a low resolution, like 512x512?

**Comment by klaun000** [comment]
Hello Admin! I have the same problem with my gpu :( Can you fix it? or give me hint how to repair it?
GPU:  Radeon RX 7800 XT
CPU: AMD Ryzen 9 5900x
RAM: Corsair 16GB KIT DDR4 3600MHz CL18, x2 = 32GB memory
![Bez názvu](https://github.com/Acly/krita-ai-diffusion/assets/167319372/04c33d10-d600-4071-b5a7-ac656adef4f0)

**Comment by Acly** [comment]
Supposedly it's possible to get decent performance with AMD on Linux, or maybe with ZLUDA on Windows. But it requires manual setup and is not straight forward.

I don't think I can do anything here until AMD support for ComfyUI on Windows improves and becomes more stable.

**Comment by stoolzo** [comment]
any update for this I have exactly the same card and still have these problems in 2025, are there no tweets at all we can do in kria itself to lower the amount of RAM that it uses Even if it means lowering the quality of the AI generation, is better than not being able to do anything at all
