### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by RonGeorge** [Acly/krita-ai-diffusion#62]
A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Program Files\Krita (x64)\share\krita\pykrita\ai_diffusion\ui\widget.py in apply_result(self=<ai_diffusion.ui.widget.GenerationWidget object>, item=<PyQt5.QtWidgets.QListWidgetItem object>)
  753     def apply_result(self, item: QListWidgetItem):
  754         self.show_preview(item)
  755         self.apply_selected_result()
  756 
  757 
self = <ai_diffusion.ui.widget.GenerationWidget object>
self.apply_selected_result = <bound method GenerationWidget.apply_selected_re...<ai_diffusion.ui.widget.GenerationWidget object>>

 C:\Program Files\Krita (x64)\share\krita\pykrita\ai_diffusion\ui\widget.py in apply_selected_result(self=<ai_diffusion.ui.widget.GenerationWidget object>)
  749 
  750     def apply_selected_result(self):
  751         self.model.apply_current_result()
  752 
  753     def apply_result(self, item: QListWidgetItem):
self = <ai_diffusion.ui.widget.GenerationWidget object>
self.model = <ai_diffusion.ui.model.Model object>
self.model.apply_current_result = <bound method Model.apply_current_result of <ai_diffusion.ui.model.Model object>>

 C:\Program Files\Krita (x64)\share\krita\pykrita\ai_diffusion\ui\model.py in apply_current_result(self=<ai_diffusion.ui.model.Model object>)
  415     def apply_current_result(self):
  416         """Promote the preview layer to a user layer."""
  417         assert self._layer and self.can_apply_result
  418         self._layer.setLocked(False)
  419         self._layer.setName(self._layer.name().replace("[Preview]", "[Generated]"))
self = <ai_diffusion.ui.model.Model object>
self._layer = <PyKrita.krita.Node object>
self.can_apply_result = False
AssertionError: 
    __cause__ = None
    __class__ = <class 'AssertionError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AssertionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AssertionError object>
    __doc__ = 'Assertion failed.'
    __eq__ = <method-wrapper '__eq__' of AssertionError object>
    __format__ = <built-in method __format__ of AssertionError object>
    __ge__ = <method-wrapper '__ge__' of AssertionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AssertionError object>
    __gt__ = <method-wrapper '__gt__' of AssertionError object>
    __hash__ = <method-wrapper '__hash__' of AssertionError object>
    __init__ = <method-wrapper '__init__' of AssertionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AssertionError object>
    __lt__ = <method-wrapper '__lt__' of AssertionError object>
    __ne__ = <method-wrapper '__ne__' of AssertionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AssertionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AssertionError object>
    __repr__ = <method-wrapper '__repr__' of AssertionError object>
    __setattr__ = <method-wrapper '__setattr__' of AssertionError object>
    __setstate__ = <built-in method __setstate__ of AssertionError object>
    __sizeof__ = <built-in method __sizeof__ of AssertionError object>
    __str__ = <method-wrapper '__str__' of AssertionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ()
    with_traceback = <built-in method with_traceback of AssertionError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Program Files\Krita (x64)\share\krita\pykrita\ai_diffusion\ui\widget.py", line 755, in apply_result
    self.apply_selected_result()
  File "C:\Program Files\Krita (x64)\share\krita\pykrita\ai_diffusion\ui\widget.py", line 751, in apply_selected_result
    self.model.apply_current_result()
  File "C:\Program Files\Krita (x64)\share\krita\pykrita\ai_diffusion\ui\model.py", line 417, in apply_current_result
    assert self._layer and self.can_apply_result
AssertionError

Trying to follow along with your video, but when there's some goofiness of the image automatically jumping into the main canvas or it just creating thumbnails on the right. When I double click a thumbnail on the right, I get this error.

**Comment by Miraihi** [comment]
Exactly my problem #52

**Comment by Acly** [comment]
Indeed, and should be fixed now in [version 1.7.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.7.1)!
