### ISSUE TITLE
The ControlNet model is not installed

### ISSUE THREAD

**Issue by Shock-stcak** [Acly/krita-ai-diffusion#621]
The ControlNet model is not installed，Prompted for this problem, was fine using it a few days ago. Using real-time painting with ComfyUI, I've looked up everything on the web and can't fix it, nor can I change the version.

**Comment by Acly** [comment]
client.log lists all control net models, if they are found or not, which paths it looks for, etc.
Please check.

**Comment by blackBB1** [comment]
control net XL models Where is it?

**Comment by blackBB1** [comment]
control net XL models Where is the placement location?

**Comment by Shock-stcak** [comment]
放这里。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月25日(星期四) 晚上8:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Acly/krita-ai-diffusion] The ControlNet model is not installed (Issue #621)














 
控制网 XL 型号 放置位置在哪里？
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;
