### ISSUE TITLE
Error during installation: Process exited with code 1

### ISSUE THREAD

**Issue by Majistor** [Acly/krita-ai-diffusion#623]
![Screenshot from 2024-04-17 04-35-27](https://github.com/Acly/krita-ai-diffusion/assets/153444913/47f2111b-093a-4101-abb3-de89c370c57d)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/15003624/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/15003626/server.log)

**Comment by TomasZmek** [comment]
I have the same problem with Ubuntu 23.10 and Krita 5.2.2

**Comment by Acly** [comment]
From client.log:

> The virtual environment was not created successfully because ensurepip is not
> available.  On Debian/Ubuntu systems, you need to install the python3-venv
> package using the following command.
> 
> apt install python3.11-venv
> 
> You may need to use sudo with that command.  After installing the python3-venv
> package, recreate your virtual environment.

**Comment by TomasZmek** [comment]
This worked for me. After installing the package, the local server installation works

**Comment by Majistor** [comment]
> From client.log:
> 
> > The virtual environment was not created successfully because ensurepip is not
> > available.  On Debian/Ubuntu systems, you need to install the python3-venv
> > package using the following command.
> > apt install python3.11-venv
> > You may need to use sudo with that command.  After installing the python3-venv
> > package, recreate your virtual environment.

it worked ,thanks.

**Comment by cristianmoreno14** [comment]
> apt install python3.11-venv

this worked for me as well 
using linux mint 21.3
cheers
