### ISSUE TITLE
error during installation : error : subprocess-exited-with-error x

### ISSUE THREAD

**Issue by Majistor** [Acly/krita-ai-diffusion#625]
[server.log](https://github.com/Acly/krita-ai-diffusion/files/15009314/server.log)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/15009316/client.log)

**Comment by Acly** [comment]
This is related to installing dependencies specific for "IP-Adapter Face" feature. You can proceed without it.

If you want to install it, it requires Python headers, which are usually part of package `python3.11-dev` (maybe `python3.11-devel` for some distros)

**Comment by Majistor** [comment]
> This is related to installing dependencies specific for "IP-Adapter Face" feature. You can proceed without it.
> 
> If you want to install it, it requires Python headers, which are usually part of package `python3.11-dev` (maybe `python3.11-devel` for some distros)

thanks  , it worked
