### ISSUE TITLE
Feature suggestion: save all selected images (or all images from an entire entry in the history)

### ISSUE THREAD

**Issue by interstellarjam** [Acly/krita-ai-diffusion#626]
When multiple images are selected and I right click and choose save from the context, I'd expect that all the selected images are iterated through and saved individually. Currently seems only one image is saved when doing this.

Additionally I think it would be great if we could perhaps click/rightclick the headings in the history to choose to select all images within them (or present the same context menu allowing us to mass save or discard).

Had a brief look and I suppose that passing all selected images to the save function (or calling it for each of them) might suffice as a basic implementation?

**Comment by Acly** [comment]
Yes saving all selected images certainly makes sense.

**Comment by Acly** [comment]
Fixed in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
