### ISSUE TITLE
Feature suggestion: image save quality/format preferences

### ISSUE THREAD

**Issue by interstellarjam** [Acly/krita-ai-diffusion#627]
Currently choosing 'save' from the context menu produces what seems like a very lossy .webp output image that's not useful for other projects - I would prefer if we could save out as png or other formats.

I made this trivial change myself (simply changing the webp to png in _save_job_result in model.py), but think it would be great if there was an entry in the preferences somewhere to specify the format and/or quality - sometimes for sure just dumping webps or jpgs out would be good for reference when quality didn't matter. Maybe there's a more natural place to make this choice on a per-session basis?

**Comment by Acly** [comment]
> sometimes for sure just dumping webps or jpgs out would be good for reference when quality didn't matter.

would it? I'm not exactly sure what the purpose of save image is in the first place, so don't necessarily want more options for it. All images are already persisted in the .kra file (compressed but with high quality), so dumping them on top serves little purpose. I mostly got the impression people wanted it for peace of mind or they were used to it from Auto1111 et al.

Writing losless (webp or png) maybe makes a bit more sense, although I'm still curious why you'd use it that way?

**Comment by interstellarjam** [comment]
Well for me it's the two different use cases: if working on something within Krita, and primarily keeping the high quality generated images in the file it's still useful to save off at least some of them so they can be viewed and referenced externally. This serves as a memorandum, can be built into project notes, makes searching for projects visually easier later etc. If I have a file that contains dozens or hundreds of image scraps but I can't search them up externally then I often run into the case later where I cannot for the life of me remember which project file contains the image I'm thinking of! So I often externalise most of the important image components in subfolders.

Then the other case where creating images to use in other apps, eg modelling/texturing in Blender, naturally I want to quickly save off nice quality images, and individually applying the images as a layer and saving them all off with proper names would be too time consuming! (although I guess it can be scripted)

Anyway it's not a big deal, as I said I changed it to png output which serves me fine, but thought that maybe there's others who would benefit from a setting to control the output format.

**Comment by Acly** [comment]
I will change it to png - without a setting for now, until someone makes a case for a lossy format :)

It's maybe not a big deal, but still really helps to know the use cases to make these kinds of decisions.
