### ISSUE TITLE
server execution error

### ISSUE THREAD

**Issue by Majistor** [Acly/krita-ai-diffusion#629]
![Screenshot from 2024-04-18 23-09-57](https://github.com/Acly/krita-ai-diffusion/assets/153444913/b47c3991-f9b9-4840-b845-878beca7968d)

I used this plugin one time after the installation but now it is giving error and also in "XL" mode the image generation is not starting only bur everything worked perfectly last time
[server.log](https://github.com/Acly/krita-ai-diffusion/files/15028532/server.log)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/15028538/client.log)

**Comment by Acly** [comment]
Can't really tell you more than the error message, it runs out of VRAM. 4 GB is cutting it very close, and the image resolution as well as other things (program open in the background) all have some influence on whether it's enough or not. I think 1920x1080 is going to be super slow if it works at all.

**Comment by Rishto07** [comment]
Server execution error: Insufficient funds - generation would cost 9 tokens. Remaining tokene: 2 . I am getting this error. What should I do ?
