### ISSUE TITLE
1.17.0 - "Edit Custom Presets" does nothing when Clicked in the Styles Configuration

### ISSUE THREAD

**Issue by Jim5865** [Acly/krita-ai-diffusion#634]
The words in the Dialog box that say "**Edit custom presets**" appears to be clickable, the same as "**Open Settings folder**" further down the dialog box, however nothing happens when I click it. I assume it has something to do with opening the folder with samplers.json? 

Anyway, a minor issue. Thanks for all your hard work!

**Comment by Codeschreibaer** [comment]
opens visual studio 2022 with me

**Comment by Acly** [comment]
Right, it creates the samplers.json file with an example preset, then opens it. But if you don't have a program set to open .json files, the 2nd part probably does nothing.

Since that's not uncommon it's maybe better to just open the folder instead, or it could run notepad or something...

**Comment by Jim5865** [comment]
Thanks for the feedback - I've associated .json files with an editor and all is well. I was a "drag and drop" guy with .json files - all sorted out now. Again, thanks for the wonderful work!
