### ISSUE TITLE
krita中不显示此插件

### ISSUE THREAD

**Issue by chanry520** [Acly/krita-ai-diffusion#64]
将下载的文件解压后，放入pykrita文件夹，但是在设置-配置krita-python插件管理中没有找到krita-ai-扩散

**Comment by Acly** [comment]
Make sure pykrita folder contains both:
* ai_diffusion (folder)
* ai_diffusion.desktop (file)

There is a longer explanation here: https://docs.krita.org/zh_CN/user_manual/python_scripting/install_custom_python_plugin.html
