### ISSUE TITLE
Model usage issues

### ISSUE THREAD

**Issue by Shock-stcak** [Acly/krita-ai-diffusion#641]
Serer execution error, Error while deserializing
HeaderTooLarge Iheader。
It's okay to use the Ginnillat mode, the Lief mode is incorrectly displayed: Salee Exek Tionero, Eero Wilder Serya Lihid Turachi Ihd. This is an error problem that is prompted using the Kerr model.

**Comment by Sil3ntKn1ght** [comment]
> Serer execution error, Error while deserializing HeaderTooLarge Iheader。 It's okay to use the Ginnillat mode, the Lief mode is incorrectly displayed: Salee Exek Tionero, Eero Wilder Serya Lihid Turachi Ihd. This is an error problem that is prompted using the Kerr model.

under configuration connections where stop is there is view logs files, click to open.
the client.log open with note pad, scroll to bottom
copy the last paragraphs just before and with error.
its very important to help know what what's happened
