### ISSUE TITLE
Invalid location: directory is not empty, but no previous installation was found

### ISSUE THREAD

**Issue by N3onD4wn** [Acly/krita-ai-diffusion#642]
[client.log](https://github.com/Acly/krita-ai-diffusion/files/15052267/client.log)
![Screenshot 2024-04-21 162657](https://github.com/Acly/krita-ai-diffusion/assets/167693857/f7b220a4-438f-42bd-aa7b-8dd9b9f9aa78)

**Comment by Acly** [comment]
Not sure about the package installation error. You can try to install it from Command Prompt instead:
```
C:\Users\Admin\AppData\Roaming\krita\ai_diffusion\server\python\python.exe -m pip install svglib antlr4-python3-runtime
```
Maybe this will shed some light on the cause.

To retry install you have to delete the server folder, there are probably some files leftover there.

**Comment by N3onD4wn** [comment]
Hi, I wasn't sure where to paste the code since I'm very noob to this, but deleting the server folder and reinstalling it from krita solved my problem. Thank you for the help.
