### ISSUE TITLE
Custom node 'ComfyUI_IPAdapter_plus' is outdated, please update.

### ISSUE THREAD

**Issue by mcgor** [Acly/krita-ai-diffusion#643]
<img width="662" alt="Snipaste_2024-04-21_22-28-51" src="https://github.com/Acly/krita-ai-diffusion/assets/38026612/470a6089-34bb-40f0-8704-6d9549b79514">

**Comment by kiradzS** [comment]
我也是，这个插件已经更新到最新版了

**Comment by jeremytao0** [comment]
i just solved by 'Update All' in manager

**Comment by Pedro12f** [comment]
i didn't get it, how do you solve it out? can you explain please?

**Comment by Pedro12f** [comment]
> i just solved by 'Update All' in manager

i didn't get it, how do you solve it out? can you explain please?

**Comment by jeremytao0** [comment]
> > i just solved by 'Update All' in manager
> 
> i didn't get it, how do you solve it out? can you explain please?

I updated all in ComfyUI Manager

**Comment by WilliamTianYe** [comment]
Have you resolved this problem?
