### ISSUE TITLE
Style, composition, reference modes cannot be used

### ISSUE THREAD

**Issue by lcwewei** [Acly/krita-ai-diffusion#645]
krita_ai_diffusion-1.17.0, using style, composition, reference mode, Server execution error: 'ModelPatcher' object has no attibute 'get_model_object'
Prompt executed in 0.95 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing !!!
Traceback (most recent call last)
  File DProgram FilesComfyUI-aki-v1.2execution.py, line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File DProgram FilesComfyUI-aki-v1.2execution.py, line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File DProgram FilesComfyUI-aki-v1.2execution.py, line 74, in map_node_over_list
    results.append(getattr(obj, func)(slice_dict(input_data_all, i)))
  File DProgram FilesComfyUI-aki-v1.2custom_nodesComfyUI_IPAdapter_plusIPAdapterPlus.py, line 996, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, ipa_args), )
  File DProgram FilesComfyUI-aki-v1.2custom_nodesComfyUI_IPAdapter_plusIPAdapterPlus.py, line 359, in ipadapter_execute
    sigma_start = model.get_model_object(model_sampling).percent_to_sigma(start_at)
AttributeError 'ModelPatcher' object has no attribute 'get_model_object'

**Comment by Acly** [comment]
Likely need to update ComfyUI
