### ISSUE TITLE
sdxl workload has not been installed

### ISSUE THREAD

**Issue by lcwewei** [Acly/krita-ai-diffusion#646]
krita_ai_diffusion_1.17.0,
![image](https://github.com/Acly/krita-ai-diffusion/assets/16218099/385b7eb9-bd40-4ce8-afb1-2b8a1a98eef7)

**Comment by Sil3ntKn1ght** [comment]
go to connections look at the ticked options, its happened to me where there a update and the SDXL was not ticked as not by default, so what your getting happens, simply tick to update will re appear install and fixed.

**Comment by lcwewei** [comment]
I'm using the second mode: custom server (local or remote)

**Comment by Acly** [comment]
https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#this-is-a-sd-15xl-checkpoint-but-the-sd-15xl-workload-has-not-been-installed
