### ISSUE TITLE
Addon wants me to constantly Update to the newest version

### ISSUE THREAD

**Issue by Muskelmagier** [Acly/krita-ai-diffusion#65]
Like it says in the Title I wanted to use the Krita plugin

So i freshly installed Krita and I downloaded the newest version of Krita-Ai-diffusion and used the installer per instruction inside the docker option and now the problem began 

Every time I wanted to use the Addonwhem I started Krita it didn't initialize because it wanted to update to the newest version or even downgrade. 
it asked me to "update" to version 1.7.0 from 1.7.1 but this doesn't work. 

Afterward, I got an error about model migration.

The best way to prevent this from happening again in the future in my opinion decouple starting the server from updating it.

**Comment by Acly** [comment]
Yea okay that was just a silly mistake on my part. :\

To fix manually: open the `.version` file in the server installation folder in a text editor, and change it to 1.7.0

**Comment by Muskelmagier** [comment]
OK what you said fixed it Thx
