### ISSUE TITLE
CHECKPOINTS!!!!

### ISSUE THREAD

**Issue by Tasvthe** [Acly/krita-ai-diffusion#650]
After KRITA AI DIFFUISON is updated, most checkpoint files in the path cannot be traversed, and only three SDXL files can be identified
![{3C8AEDD2-5D98-41ca-ACF4-4C42552E7E6A}](https://github.com/Acly/krita-ai-diffusion/assets/156665109/25bb4fb1-dd7d-44a3-8e74-ae435ca0cdd5)

**Comment by Tasvthe** [comment]
I want to know which file I need to go to to change the identification path

**Comment by Sil3ntKn1ght** [comment]
> I want to know which file I need to go to to change the identification path

do you mean to point to another hard drive and have checkpoints there?
C:\Users\pc\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI extra_model_paths.yaml

i have a video on it if so, i ramble though so fast-forward where needed.

https://www.youtube.com/watch?v=dkYUi5gZdA0&t=306s

**Comment by Acly** [comment]
Also make sure ComfyUI & custom nodes (especially [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes)) are updated. See #267

**Comment by Tasvthe** [comment]
> Also make sure ComfyUI & custom nodes (especially [comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes)) are updated. See #267

Recovered, Oyeah
