### ISSUE TITLE
Feature Requests (Differential Diffusion, layerdiffuse)

### ISSUE THREAD

**Issue by ricperry** [Acly/krita-ai-diffusion#652]
I noticed recently that the Fooocus inpaint method is being used. It would be great however to be able to optionally select the differential diffusion method in the configuration dialog. Additionally, it would also be great to be able to use layer diffuse when adding objects (again, optional in either the UI at generate, or in the configuration settings).

I think differential diffusion is built in now, but layerdiffusion is here: https://github.com/huchenlei/ComfyUI-layerdiffuse

Love your work, Acly! Keep it up!

**Comment by Acly** [comment]
Differential diffusion is built in, for layer diffusion track #453 (it's still unclear)
