### ISSUE TITLE
server execution error : could not allocate tensor with 52428800 bytes . There is not enough GPU video memory avaialble . 

Graphic Card - Asus rx6600 8gb vram , why is this happening? Any solution?

### ISSUE THREAD

**Issue by ishanjaiswal2610** [Acly/krita-ai-diffusion#655]
![Screenshot 2024-04-24 180717](https://github.com/Acly/krita-ai-diffusion/assets/138959240/1b80a54b-16df-4014-bec4-68798348dbfb)

**Comment by Acly** [comment]
When I switch to DirectML a 640x512 image uses almost 12GB VRAM with latest version. I also think this was better at some point and fit into 8GB... 

I'm not sure what I can do about it though, it doesn't look like anybody cares enough about AMD on Windows to improve the situation in ComfyUI :\

**Comment by ishanjaiswal2610** [comment]
> When I switch to DirectML a 640x512 image uses almost 12GB VRAM with latest version. I also think this was better at some point and fit into 8GB... 
> 
> I'm not sure what I can do about it though, it doesn't look like anybody cares enough about AMD on Windows to improve the situation in ComfyUI :\

Can i use my friend's gpu to use krta he has rtx 3060 , but he is not living with me can i use his gpu ? If yes plss help me how can i use his gpu for my work  @Acly

**Comment by Acly** [comment]
> add too "server_arguments": "--force-fp16" or "--force-fp32"

I don't think those do anything with DirectML. It always uses FP32 and doesn't support anything else.

**Comment by Acly** [comment]
> Can i use my friend's gpu to use krta he has rtx 3060 , but he is not living with me can i use his gpu ?

Yes you can, but a bit of networking knowledge is required, I can't give you a complete walkthrough here. Maybe you can find guides on the internet.

Steps are roughly:
1. Setup the server on your friends PC. Either install Krita+Plugin there and go through the installer, or copy the server folder from your PC might work. Or install ComfyUI+dependencies manually.
2. Run the server from command line with the `--listen` argument
3. If you want to connect to your friend's PC over the internet, you either need to do port forwarding (security risk, _not_ recommended), or use a reverse proxy like [nginx](https://www.nginx.com/), or a VPN.

**Comment by Sil3ntKn1ght** [comment]
> > Can i use my friend's gpu to use krta he has rtx 3060 , but he is not living with me can i use his gpu ?
> 
> Yes you can, but a bit of networking knowledge is required, I can't give you a complete walkthrough here. Maybe you can find guides on the internet.
> 
> Steps are roughly:
> 
>     1. Setup the server on your friends PC. Either install Krita+Plugin there and go through the installer, or copy the server folder from your PC might work. Or install ComfyUI+dependencies manually.
> 
>     2. Run the server from command line with the `--listen` argument
> 
>     3. If you want to connect to your friend's PC over the internet, you either need to do port forwarding (security risk, _not_ recommended), or use a reverse proxy like [nginx](https://www.nginx.com/), or a VPN.

omg i need a video or guide so i can use this on my local network and use my lounge pc from my desk pc.

**Comment by Acly** [comment]
It might also be possible to use AMD on Windows with ZLUDA. It should be much better performance and memory efficiency. There is a [ComfyUI fork](https://github.com/patientx/ComfyUI-Zluda). But you will have to set it all up yourself and I can't say if everything is supported. It's not possible to test it without actually having AMD hardware.
