### ISSUE TITLE
Krita -AI plugin local server error launch

### ISSUE THREAD

**Issue by opako666** [Acly/krita-ai-diffusion#659]
Hi

I have problem with launch local  managed server on AI plugin. 

INFO OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\opako\AppData\Roaming\krita\pykrita\ComfyUI\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
2024-04-25 13:22:57,200 ERROR 

Is there any solution?

Thanx
![Configure Krita](https://github.com/Acly/krita-ai-diffusion/assets/168090820/26a74cff-a531-4340-9f80-25fdc0118933)

_Originally posted by @opako666 in https://github.com/Acly/krita-ai-diffusion/issues/503#issuecomment-2076989725_

**Comment by Acly** [comment]
Was this a fresh install or upgrade from previous version?

I encountered similar problem when upgrading torch, it's some kind of dependency issue (some DLL is missing, not in the right place or not the right version). I'm not sure I can help much though, I ended up reinstalling.

If you haven't done already I would try installing with minimal packages into a seprate folder to see if that works. You can copy the models afterwards if it does to avoid most downloads.

**Comment by opako666** [comment]
It is new install. I try install all again with minimal packages.  Same problem.

**Comment by opako666** [comment]
this file "fbgemm.dll" exist in that lib folder.

**Comment by opako666** [comment]
Hardware is Surface pro 8 with Windiws 11.

**Comment by Acly** [comment]
> this file "fbgemm.dll" exist in that lib folder.

Yea usually it's that the dll requires some other dlls, which also require other dlls... and so on.
And at some point one of them is missing. Windows doesn't like to tell you which though.

[Dependencies](https://github.com/lucasg/Dependencies) tool can help, you drag the DLL in and ideally it tells you which one is missing.

I thought this might be related to recent pytorch update (which the DLL belongs to). But I just tried a fresh install on Windows 11 and it's working ok.

**Comment by opako666** [comment]
I don´t know how to fix it.
Thanks for help.
![dependencies](https://github.com/Acly/krita-ai-diffusion/assets/168090820/4f7c63be-7a9e-4a14-aed9-d9492d9edeac)

**Comment by opako666** [comment]
I fix it....I installed Visual C++ Redistributable.

Acly thanks so much for your help.

**Comment by opako666** [comment]
it is terribly slow on the CPU to the point of being unusable.

**Comment by Acly** [comment]
I'm afraid so :(
