### ISSUE TITLE
runpod cloud error

### ISSUE THREAD

**Issue by zxcvqwerasdf** [Acly/krita-ai-diffusion#66]
I found only this template 
![image](https://github.com/Acly/krita-ai-diffusion/assets/67195196/82db4960-68ee-43a6-a84d-f4004b0ce7e5)
Copied url and got this:
![image](https://github.com/Acly/krita-ai-diffusion/assets/67195196/370f0310-8ba8-49ef-9143-0fc447267806)

**Comment by Acly** [comment]
That template is just has a base installation of ComfyUI, so you'd have to install custom nodes and models manually.

I made a template with everything pre-installed. Direct link: https://runpod.io/gsc?template=8myumeqonw&ref=of4awcqw

I thought it would be public on runpod and others can find it, but I'm not sure how it works on runpod works exactly.
