### ISSUE TITLE
I'm missing some options like open Models folder.

### ISSUE THREAD

**Issue by RealAzmodeo** [Acly/krita-ai-diffusion#663]
![image](https://github.com/Acly/krita-ai-diffusion/assets/14279740/22803059-e9eb-4a09-9e40-5d4e86de65d5)

I've been following tutorials and everyone has a folder button next to refresh. On top of that I have no idea where are the models located, and I want to add a couple.

Thanks!

**Comment by FHeifer** [comment]
C:\Users\YourUserName\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\models\checkpoints   .   This is the path to models as it´s  installed in my computer.

**Comment by Acly** [comment]
The folder button should be there if you installed through the plugin ("Local Managed Server" connection option).

Other options don't display it (the plugin doesn't know or have access to the folder in that case)
