### ISSUE TITLE
Issue with pose (from image) no skeleton made blank. On some images only

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#664]
https://www.mediafire.com/file/qnzaou1k86uw6v8/Mannequins.zip/file

this is odd, 1.17.1
some images work others do not. 3 days ago I started getting people telling me pose does not work on all images, so i started testing more.
prior to in 1.15 all the images in the zip you could drop the image insert as new layer, select pose as add control layer, and then the 3 stars from image and it make the vector skeleton

but now and i have no idea why, some work some don't.
I tried converting the images so from webp to png etc but no luck tied PSP re-save also to png as thought krita might just be changing the extension and not the encoding. 
as i thought it might be a compression issue.
most work but few don't, before all work and the webp worked. but in prior versions I found size did cause a off set skeleton that was not over the image, I wonder if the skeleton is off the screen when made for some?

so this one works, in the zip 
![Uploading 000 (1).png…]()

this one does not
![000 (1 1)](https://github.com/Acly/krita-ai-diffusion/assets/81461290/0a51c61f-b56a-47be-92c6-81782e17c355)

this does not
![000 (79)](https://github.com/Acly/krita-ai-diffusion/assets/81461290/6539178a-4681-4b6e-a282-031b7a2a8469)

any insights into if its something I'm doing

PS 1.17.1 is good so far and the sampler renames are great thank you.

**Comment by Codeschreibaer** [comment]
Try: Create a new paint layer, entire black, pose it under your vector layer. Effect?

**Comment by Sil3ntKn1ght** [comment]
> Try: Create a new paint layer, entire black, pose it under your vector layer. Effect?
tried making image white areas back same issue.
not a vector layer issue, can add skeleton no problem.

its creation of skeleton from certain images that not working where prior it did work.

**Comment by Codeschreibaer** [comment]
my fault sry.  I meant: lay a black image under your pose image (not under vector layer). I had the same with white white.

**Comment by Acly** [comment]
In 1.16.0 the model for detection was changed.
In 1.17.1 it was changed back because new model didn't work on some installs

So it makes sense that behavior changed but it should be back to same models as 1.15.0 now. There were some other updates that influence it, so maybe not 100%.

As for the mannequins, most seem to work but some don't. Keep in mind the pose detection model was trained on *real-life photos of actual people*. It kinda works in some other situations too, but isn't really made for detecting pose mannequins...

**Comment by Sil3ntKn1ght** [comment]
> In 1.16.0 the model for detection was changed. In 1.17.1 it was changed back because new model didn't work on some installs
> 
> So it makes sense that behavior changed but it should be back to same models as 1.15.0 now. There were some other updates that influence it, so maybe not 100%.
> 
> As for the mannequins, most seem to work but some don't. Keep in mind the pose detection model was trained on _real-life photos of actual people_. It kinda works in some other situations too, but isn't really made for detecting pose mannequins...


got it working seem to get confused on the joins, made sense after you said made on people.
I use mannequins as there are so many poses easy to get photos of those poses is harder to find, Plus i want to buy one as from my art days i use to had a wood one I used as reference, till the disability stopped me being able to draw. 
Mannequin is great as can pose to what you want take photo and put in to control Ai art more. 
Cleaning the joins is easy.
I think it was originally very light and i thought making it darker would be easier for the AI.

Still makes off set skeleton on some images, that's not you that would be the open pose maker.


![Screenshot 2024-04-29 074914](https://github.com/Acly/krita-ai-diffusion/assets/81461290/e03fc176-230a-4633-b116-582c1111b78d)


![000 (1)-test](https://github.com/Acly/krita-ai-diffusion/assets/81461290/e1575a6e-2ee6-4020-a056-bf572c586e1e)

**Comment by Sil3ntKn1ght** [comment]
and the gtx1070 no issues doing the skeleton with those images wtf  lol
that does have --force-fp16 --normalvram  but surely that would not affect it.
in not fussed it works well enough just ood.
i imagine its something to do with the pose control certainty not you AI diffusion.

**Comment by Codeschreibaer** [comment]
there is a free alternative for manikins: www.posemy.art
btw i said i had issues myself, which i solved (mainly) with a black background
