### ISSUE TITLE
Doubles the image generation

### ISSUE THREAD

**Issue by A-Byte-Sized** [Acly/krita-ai-diffusion#666]
Everything is generating double of the requested items. For example, if I hit _Generate_ once I'll get two different images out. If I batch three, I'll get six out. 

Happens with every model/preset. I've tried removing krita + the plugin and reinstalling. Logs seem normal. 

Is there some setting/feature I'm not aware of?

![image](https://github.com/Acly/krita-ai-diffusion/assets/17830331/9288304e-3384-4d03-80f9-1350ee566873)

```
2024-04-28 19:24:09,599 INFO got prompt
2024-04-28 19:24:23,319 INFO 0%|          | 0/20 [00:00<?, ?it/s]
  5%|▌         | 1/20 [00:00<00:09,  2.09it/s]
 10%|█         | 2/20 [00:01<00:14,  1.25it/s]
 15%|█▌        | 3/20 [00:02<00:12,  1.31it/s]
 20%|██        | 4/20 [00:02<00:11,  1.34it/s]
 25%|██▌       | 5/20 [00:03<00:11,  1.36it/s]
 30%|███       | 6/20 [00:04<00:10,  1.37it/s]
 35%|███▌      | 7/20 [00:05<00:09,  1.37it/s]
 40%|████      | 8/20 [00:05<00:08,  1.38it/s]
 45%|████▌     | 9/20 [00:06<00:07,  1.39it/s]
 50%|█████     | 10/20 [00:07<00:07,  1.39it/s]
 55%|█████▌    | 11/20 [00:07<00:06,  1.40it/s]
 60%|██████    | 12/20 [00:08<00:05,  1.40it/s]
 65%|██████▌   | 13/20 [00:09<00:05,  1.40it/s]
 70%|███████   | 14/20 [00:10<00:04,  1.40it/s]
 75%|███████▌  | 15/20 [00:10<00:03,  1.55it/s]
 80%|████████  | 16/20 [00:11<00:02,  1.63it/s]
 85%|████████▌ | 17/20 [00:11<00:01,  1.71it/s]
 90%|█████████ | 18/20 [00:12<00:01,  1.78it/s]
 95%|█████████▌| 19/20 [00:12<00:00,  1.81it/s]
100%|██████████| 20/20 [00:13<00:00,  1.86it/s]
100%|██████████| 20/20 [00:13<00:00,  1.52it/s]
2024-04-28 19:24:23,840 INFO Prompt executed in 14.16 seconds
```

GPU is a 3090 (24 vram)

Thank you for your time!

**Comment by Acly** [comment]
You're looking for the "Maximum Batch Size" setting in the Performance section.
* Batch Size: multiple images are generated in parallel
* Batches (batch count): the same as clicking generate multiple times, just puts things into a queue

Increasing batch size is usually pretty efficient, you get two images, but it's not actually twice as slow.
