### ISSUE TITLE
Add multi-language switching function

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#668]
Hello, the attachment is the translated simplified Chinese version. I hope that language switching can be integrated into the plug-in settings. Thank you!
[krita_ai_diffusion-1.17.1.zip](https://github.com/Acly/krita-ai-diffusion/files/15167466/krita_ai_diffusion-1.17.1.zip)

**Comment by syl1130** [comment]
Hello, the attachment is the new translated simplified Chinese version. I hope that language switching can be integrated into the plug-in settings. I have also added support for translating Deep Chinese prompt words, which requires the installation of the ComfyUI_Custom_Nodes_AlekPet translation node. Thank you! 
[krita_ai_diffusion_ZH-CN-1.20.0.zip](https://github.com/user-attachments/files/16172247/krita_ai_diffusion_ZH-CN-1.20.0.zip)

**Comment by Acly** [comment]
Language switching is now implemented in [v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0)

I'm afraid you (or someone) will have to redo translation. But it will then work for all future versions, and only new features have to be added.

https://github.com/Acly/krita-ai-diffusion/blob/main/CONTRIBUTING.md#translations-localization

Translation template: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/language/new_language.json.template

**Comment by syl1130** [comment]
okay, thanks
&nbsp;

Best Regards,&nbsp;


Alxen






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月25日(星期四) 晚上10:00
收件人: ***@***.***&gt;; 
抄送: "Alxen ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Acly/krita-ai-diffusion] Add multi-language switching function (Issue #668)





 
Language switching is now implemented in v1.21.0
 
I'm afraid you (or someone) will have to redo translation. But it will then work for all future versions, and only new features have to be added.
 
https://github.com/Acly/krita-ai-diffusion/blob/main/CONTRIBUTING.md#translations-localization
 
Translation template: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/language/new_language.json.template
 
&mdash;

**Comment by syl1130** [comment]
Hello Acly,


I have translation the&nbsp;language to zh-cn.json.&nbsp;I will send you the translated file as an attachment. Add translations to the updated sections in the future. Thank you for your work.


and the translation of 'off', 'Batches'&nbsp;and 'on' is not displayed. please check this.&nbsp;









Alxen&nbsp;Shen
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Acly/krita-ai-diffusion"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Jul 25, 2024 10:00 PM
***@***.***&gt;;
Cc:&nbsp;"Alxen ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Acly/krita-ai-diffusion] Add multi-language switching function (Issue #668)





 
Language switching is now implemented in v1.21.0
 
I'm afraid you (or someone) will have to redo translation. But it will then work for all future versions, and only new features have to be added.
 
https://github.com/Acly/krita-ai-diffusion/blob/main/CONTRIBUTING.md#translations-localization
 
Translation template: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/language/new_language.json.template
