### ISSUE TITLE
Mask as context window is broken

### ISSUE THREAD

**Issue by RadioVs** [Acly/krita-ai-diffusion#669]
When you select a mask as a context window, it expands to cover the entire image and beyond its borders

![image](https://github.com/Acly/krita-ai-diffusion/assets/62827539/0c0e10f3-f73c-4810-843b-9184807b27de)
![image](https://github.com/Acly/krita-ai-diffusion/assets/62827539/ca914ddd-7cd2-4bcc-b7df-4abccf629909)

**Comment by Acly** [comment]
Fixed in [1.17.2](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.2)
