### ISSUE TITLE
(Suggestion) Inpaint with regular ksamplers

### ISSUE THREAD

**Issue by RadioVs** [Acly/krita-ai-diffusion#670]
Lightning models are fixed at 4-8 steps of the loras baked into them, and in advanced ksamplers the denoise is regulated by the start_at_steps, so with low denoise the quality drops noticeably. It would be better to use a regular ksampler with a constant number of steps. Even for other models.

**Comment by Acly** [comment]
There's some discussion about this in #483 

I don't know a good solution to make img2img work well with Lightning models. What you're suggesting is not different from increasing total steps. For example running 8-step lightning model at 50% denoise with 16 total steps -> results in 8 actual steps. Doesn't actually look good though in my experience, the noise schedule is too diferent from what Lightning was trained on.

It helps a bit to not use a uniform scheduler (not Karras).

**Comment by rbfbatx** [comment]
I use the lightening models at 45 and they look pretty good especially after a couple of passes but literally go back to that noisy hazy quality at 40 or 50 or any other level.
