### ISSUE TITLE
Buying Tokens for Krita AI

### ISSUE THREAD

**Issue by SarvikuonoD** [Acly/krita-ai-diffusion#677]
Hi

As non technical person Id like to buy tokens to use Kritas AI addition. I got tokens, but they gave me three generative fills to use.

Interstice says that there is no way to buy them at the moment. 

Any plan, time or date, when it would be possible?

yrs
Nikolai

**Comment by Acly** [comment]
Hi! and thanks for testing.

There is still some work to do regarding better balancing and transparency, but mostly it's waiting for some bureuacratic processes. Things are in motion but it might take 4-6 weeks.

I hope to update #532 with some news soon.

**Comment by Eggrollah** [comment]
How do I get more tokens for ai diffusion? I get an error that says I don’t have enough tokens for generative fill.
