### ISSUE TITLE
extra_model_paths.yaml not working

### ISSUE THREAD

**Issue by Wonderer11** [Acly/krita-ai-diffusion#680]
I have installed a local managed server (Krita AI) of the Krita plugin and a local comfyui in the same drive, with different models stored in the 2 servers.
![Screenshot 2024-05-02 211355](https://github.com/Acly/krita-ai-diffusion/assets/79945225/8ad4123a-ec46-4937-87e0-69599a33628c)

I tried to share models using `extra_model_paths.yaml` but I can only share models from the plugin to the local comfyui and not all models (sd-turbo missing) to the plugin.

Can the plugin detect files shared using `extra_model_paths.yaml`? Do I need to change the code to enable sharing?

Would also like to know if the plugin considers using fast model generation such as sd-turbo (https://huggingface.co/stabilityai/sd-turbo) or sd-lighting (https://huggingface.co/ByteDance/SDXL-Lightning) which also support live painting (https://github.com/hashmil/comfyUI-workflows/blob/main/SDXL-turbo-livepainting_workflow.png) and seem to be faster than using lcm. Just asking because it seems that I cannot change the default workflow to speedup the generation using scheduler node. Should I use turbo/lighting merge for live performance?

**Comment by Acly** [comment]
The installer only detects and downloads models in the default `ComfyUI/models` location. Small set of required models is required to be there to launch. But you can use `extra_model_paths.yaml`  for any optional models (checkpoint, lora, control...) with the plugin. Sharing works same as for any ComfyUI install.

You can use turbo & lightning models, make sure to select the appropriate sampler: [Docs](https://github.com/Acly/krita-ai-diffusion/wiki/Samplers)

I still prefer LCM for Live paint.

**Comment by Wonderer11** [comment]
Thank you! It solve most of my question.
