### ISSUE TITLE
Failed during install: failed to download http://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors: Socket operation timed out

### ISSUE THREAD

**Issue by luliart** [Acly/krita-ai-diffusion#681]
Macbook pro, 32GB memory
Failed during install: failed to download http://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors: Socket operation timed out
<img width="1032" alt="Screenshot 2024-05-03 at 12 13 32" src="https://github.com/Acly/krita-ai-diffusion/assets/138900276/18394ba6-b846-43f1-a119-db97eabe2619">
<img width="1032" alt="Screenshot 2024-05-03 at 12 13 32" src="https://github.com/Acly/krita-ai-diffusion/assets/138900276/c818dedb-b988-45aa-a408-4d6d09fca826">

**Comment by Acly** [comment]
Sounds like a connection issue, maybe the server was having problems (try again later), or internet connection or some firewall.
Does the download link work for you from the browser?

**Comment by czpwpq** [comment]
it's the same problem, i use browser download it, but i dont know where i need to put in

**Comment by czpwpq** [comment]
the same problem
http://huggingface.co 
Almost nothing on this website can be downloaded automatically. I have tried many methods but nothing works. I can only download them one by one through the browser and manually put them into the corresponding folder.

But if it is not written in the website description, I don’t know where to put it, which makes it impossible to continue.
<img width="1051" alt="屏幕截图 2024-05-26 125848" src="https://github.com/Acly/krita-ai-diffusion/assets/24430845/266c8113-87d5-410b-8fd0-4a45f8e6cf73">

**Comment by thejennnn** [comment]
@Acly Hello greetings! My friend and I had the same problem today, I tried reinstalling many times but it still didn't work. I also checked my internet connection and there are no issues. Please give me some advice, thank you.

Mac pro 2018, sonama 14.4.1

<img width="727" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/170909473/21392a03-c770-44ab-9f8a-d009483ba3da">

**Comment by ice-ko** [comment]
> Sounds like a connection issue, maybe the server was having problems (try again later), or internet connection or some firewall. Does the download link work for you from the browser?

I also encountered this error, and I can download it normally using the browser

**Comment by Acly** [comment]
@ice-ko Are you using Mac also? Maybe it's related.

**Comment by ice-ko** [comment]
@Acly I use Windows 11. I can download it by copying the link to the browser. However, the download timeout occurs when I use Configure Image Diffusion.

**Comment by SergeyManAi** [comment]
> same here , but i download the file from browser and copy the files to the specified folder based on the log
on this link it downloads only one file, where to put it? any instruction. After I put the file in the server folder, Krita still doesnt recognise the file and keep redoanloading the file and fails. what to do?
