### ISSUE TITLE
Face repaint issue

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#686]
In the following illustration, I want to keep the character's face unchanged and redraw it elsewhere, or I need to replace the character's face, but the generated result is very different from the original image. What should I do? please help me!

![image](https://github.com/Acly/krita-ai-diffusion/assets/25132014/18f4c265-6e17-45be-ac37-2a6904eb7674)

**Comment by ricewind100** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/24190944/4bdc580b-6813-4c4d-95ce-543c6084cb9e)
