### ISSUE TITLE
ComfyUI Unable to start

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#688]
Hello! In order to save disk, the ComfyUI I installed in StabilityMatrix https://github.com/LykosAI/StabilityMatrix currently cannot be started in Local Managed Server. It can be connected in Custom Server (local or remote), but some ControINet cannot be used. Can the author fix it? Thank you so much!

![image](https://github.com/Acly/krita-ai-diffusion/assets/25132014/6d278d50-2f30-4fd9-be5a-cf21efe197bd)

**Comment by ricperry** [comment]
I have found that the most likely cause for me was that the installer assumes you're using an nvidia GPU. If you're using AMD or Intel, you'll need to go into the server folder, activate the venv, uninstall torch and torchvision, then install the correct versions. Once you do that, you should be good to go. 

You can get the install line from the PyTorch page here: https://pytorch.org/get-started/locally/

Just select the appropriate options in the chart then it will give you the pip install command you need to use.

**Comment by Acly** [comment]
Using the installer on or launching a external ComfyUI (eg. from StabilityMatrix) is not supported. Use at your own risk.

There is no way to implement that safely, it's impossible to test all kinds of custom/external ComfyUI installs out there.

If you want to use / install via StabilityMatrix, you also need to use it to launch.
