### ISSUE TITLE
duplicated preset styles in the interface

### ISSUE THREAD

**Issue by lyonnel4** [Acly/krita-ai-diffusion#689]
Hi.
Since a recent version (I guess it was 1.16), all the styles (default ones and those I created) are duplicated in my listboxes (in the panel and in the config window). the plugin in works fine but it's still a little irritating.

![screenshot2](https://github.com/Acly/krita-ai-diffusion/assets/48279234/0ae87a72-2b5a-4f60-9e0e-a4ae860bae44)
![screenshot1](https://github.com/Acly/krita-ai-diffusion/assets/48279234/97c2a25f-131f-4b09-84b8-48a9acad9106)

I did some tests : when I create a new style, it's not duplicated immediately. it's not duplicated even after stopping then starting the server.
It is duplicated only after quitting then launching Krita.
same occurs when deleting a style (the first time it occurred, I deleted one of each duplicated styles...and it was a bad idea because all the other were deleted afterwards when I launched Krita again.)

The styles json files are not duplicated, that's only a bug in the display.

I already reinstalled everything from scratch (except krita itself.) : I deleted the ai diffusion folder (and the .desktop file)  and installed again the last version, I completely deleted the folder where ComfyUI was installed and let ai diffusion install everything again) but the styles are still displayed in double.

Any idea how I could fix that ?
Maybe I did something wrong with the styles because when I uncheck the "show pre-installed styles", I got nothing.

As I said the plugin works really fine and that only a cosmetic issue

**Comment by Acly** [comment]
Probably same as #496 

How did you install the plugin, and which folder is it in? I'm still a bit confused why it would even work if it's outside the "pykrita" folder. But if that's the issue you can fix it by moving the folders around (no need to reinstall everything).

**Comment by lyonnel4** [comment]
my bad, I didn't see the #496. I'm Sorry.
I effectively didn't install the last version in the correct folder.
I have put the files in the ai_diffusion folder that is in the krita folder, not the one in krita/pykrita
the two folders named ai_diffusion confused me. 

I guess it worked because there was a correctly installed version (from march I guess) in the pykrita folder.


No more duplicates, thank you.
