### ISSUE TITLE
Start and End of Influence (Controlnet)

### ISSUE THREAD

**Issue by Luzido** [Acly/krita-ai-diffusion#69]
First of all: Great Plugin!! awesome.

I think a limiting factor right now is that we cannot adjust the start and end of the controlnet influence. I had really awesome results setting lineart cnet to end at 0.3 or something.
I wish that would be possible!

**Comment by Acly** [comment]
I've looked into it a bit, but I'm not convinced it can fit in directly. There is a lot of overlap with ControlNet strength, and I don't want to clutter the UI with 3 configurable values. 

Not saying a case can't be made for it, but it should be motivated by
* use cases where you need start/end and one strength value isn't enough
* an intuition about those values: start/end is very technical and you need to know about sampling process, but it could be presented as "how much it affects composition" and "how much it affects details"
* some examples on what you can achieve with it (advantages compared to plain CN with strength tweaking)

It would also be interesting if quality can be improved by adjusting all of start/end/strength under the hood of one user-exposed value.

**Comment by Acly** [comment]
ControlNet end parameter is now supported in 1.8.0
