### ISSUE TITLE
Server execution error: CUDA error: operation not supported

### ISSUE THREAD

**Issue by Arescjw** [Acly/krita-ai-diffusion#695]
hi guys~ im complete newbie here, just follow the instruction to install krita with comfyui but error happens while generating AI images. The attachment shows all the message of the error, can somebody guide or advice me please, thanks!!!
![krita error](https://github.com/Acly/krita-ai-diffusion/assets/169321891/39fa7c64-abd5-4b2a-a64a-420139c962fb)

**Comment by Acly** [comment]
This _usually_ means the GPU is too old / not supported, [server.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) might give some more clarity.

**Comment by Arescjw** [comment]
I see, here is my server.log, please have a look
[server.log](https://github.com/Acly/krita-ai-diffusion/files/15275727/server.log)

but i think my GPU quite old already, it is nvidia geforce gtx 950m, 
Is it unable to support? :/

**Comment by Acly** [comment]
I think you need at least a gtx 10xx card, sorry

**Comment by gandolfi974** [comment]
same problem with P40 Tesla but it's possible to use A1111 and comfyui without krita
