### ISSUE TITLE
Error: Error transferring http://127.0.0.1:8188/prompt - server replied:Internal Server Error[url=http://127.0.0.1:8188/prompt,code=401]

### ISSUE THREAD

**Issue by linxl19** [Acly/krita-ai-diffusion#696]
<img width="331" alt="PixPin_2024-05-09_12-46-17" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/df0f9f5f-d6cb-4b40-9d52-f2b81206e6a4">
<img width="253" alt="PixPin_2024-05-09_12-46-55" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/cacc71ee-3c27-4438-8eab-18d5bfb83165">
<img width="1068" alt="PixPin_2024-05-09_12-45-00" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/b96d248c-9372-4154-9855-2aff635c4d01">

Sir,
This error alert occurs when I use the Depth mode of the XL model. 
I have updated ComfyUI to the latest version, 
comfyui-inpaint-nodes also updated to the latest version, 
how should I solve this problem？

**Comment by linxl19** [comment]
![Uploading PixPin_2024-05-09_12-46-55.png…]()

**Comment by linxl19** [comment]
<img width="720" alt="PixPin_2024-05-09_12-46-55" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/2bbefa8a-b230-49fb-b99a-225d49bc611b">

**Comment by Acly** [comment]
This node is part of `comfyui_controlnet_aux` custom nodes, please try to update it.
