### ISSUE TITLE
Missing IP-Adapter model: IP-Adapter model 'reference' for SD 1.5

### ISSUE THREAD

**Issue by mkyung** [Acly/krita-ai-diffusion#699]
Hello, I have a recent new installation, plugin version `1.17.1`, but it is not working, with errors being:

<img width="554" alt="Screenshot 2024-05-10 at 8 56 05 AM" src="https://github.com/Acly/krita-ai-diffusion/assets/2427239/b04e4311-4a16-43cc-aa2f-824629a47347">

On my ComfyUI Server, I installed the models by using `download_models.py`
Inside `ComfyUI\models\ipadapter` I have:

<img width="616" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/2427239/bd1f9a9f-b609-4460-8e3d-673953f61e97">

Client logs:
`2024-05-09 23:50:50,460 WARNING Missing IP-Adapter model reference for SD 1.5`
`2024-05-09 23:50:50,460 INFO -> No model matches search paths: ip-adapter_sd15`
`2024-05-09 23:50:50,460 INFO -> Available models: `
`2024-05-09 23:50:50,460 WARNING Missing IP-Adapter model reference for SD XL`
`2024-05-09 23:50:50,460 INFO -> No model matches search paths: ip-adapter_sdxl_vit-h`
`2024-05-09 23:50:50,460 INFO -> Available models: `
`2024-05-09 23:50:50,460 INFO Optional IP-Adapter model face for SD 1.5 not found (search path: ip-adapter-faceid-plusv2_sd15, ip-adapter-faceid-plus_sd15)`
`2024-05-09 23:50:50,460 INFO Optional IP-Adapter model face for SD XL not found (search path: ip-adapter-faceid-plusv2_sdxl, ip-adapter-faceid_sdxl)`

Not sure what went wrong :(

**Comment by mkyung** [comment]
OK I first tried checking the models within the IPAdapter by `Add Node` -> `IPAdapter` -> `loaders` -> `IPAdapter Model Loader` and found that the list was undefined.
Then I googled and found that it was the problem of using Stability Matrix. I switched to the ComfyUI portable version and problem is fixed

**Comment by zdaar** [comment]
If someone has the same issue using StabilityMatrix, you can copy the 4 ipadapter model files in StabilityMatrix\Data\Models\IpAdapter and it will work

**Comment by Sdreamtale** [comment]
I also encountered the same issue, but I didn't understand how to fix it. Could you explain it in detail?

**Comment by Sorry-Im-Stupid** [comment]
I agree with Sdreamtale, I don't know what you mean by 'stabilitymatrix' here. 
As far as I can tell I have the files where they should be, but it's giving me the same error message, and comfy is also not seeing them.
