### ISSUE TITLE
custom yaml files

### ISSUE THREAD

**Issue by Muskelmagier** [Acly/krita-ai-diffusion#70]
Hi a short Question is it somehow possible to Use custom yaml files for specific models somehow?

**Comment by Acly** [comment]
yaml files are used in various places, what kind are you referring to specifically?

**Comment by Muskelmagier** [comment]
One of the models i have often was a terminal-snr-v-prediction model that normally needs a configuration yaml file placed alongside the model file for configuration otherwise the model only spews out rough noise.

**Comment by Acly** [comment]
I think I have seen those before, but never used. I'm not sure if ComfyUI loads a config yaml automatically if it has a certain name. If it does not, you'd have to explicitly provide it to the checkpoint loader node. The plugin doesn't support that.
