### ISSUE TITLE
(BUG) lora Auto-Completion work only in 1st line.

### ISSUE THREAD

**Issue by Drakosha405** [Acly/krita-ai-diffusion#700]
lora Auto-Completion work only in 1st line.
and maybe  we can start the search immediately after "<" and no need write lora?
![Lora bug](https://github.com/Acly/krita-ai-diffusion/assets/146111805/a885f64f-d946-495b-8954-2ec70b5dba0d)

**Comment by Acly** [comment]
If it's specifically the start of a new line, I think I fixed it in [this commit](https://github.com/Acly/krita-ai-diffusion/commit/63c56c32dbbf2e64488cecfafb9d98de2b1d112a) (not released yet)

**Comment by Acly** [comment]
Fixed in [1.17.2](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.2)
