### ISSUE TITLE
Server execution error: Failed to load image 0 from buffer

### ISSUE THREAD

**Issue by cherrynoize** [Acly/krita-ai-diffusion#702]
I keep getting the above error when trying to upscale an image. I am on an active layer, with the whole thing selected.

**Comment by Acly** [comment]
Please post contents of [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files), your OS, and how you connect

**Comment by cherrynoize** [comment]
After a full system update I got a different error, and it was solved by [this issue](https://github.com/Acly/krita-ai-diffusion/issues/582). Seems to be working now.

**Comment by cherrynoize** [comment]
Will reopen this if I find the error again.

**Comment by Acly** [comment]
So you installed `qt5-imageformats` to resolve? That would make sense, there is still a case where the PNG fallback doesn't work in the current release.

**Comment by cherrynoize** [comment]
Yes. But when I did I was seeing a different error (the one mentioned in that issue). My error seemed to solve spontaneously. I don't know what happened exactly but I had just installed the plugin, so maybe a restart helped.

**Comment by mailee01** [comment]
> Yes. But when I did I was seeing a different error (the one mentioned in that issue). My error seemed to solve spontaneously. I don't know what happened exactly but I had just installed the plugin, so maybe a restart helped.

can you tell me how to download and install qt5-imageformats to fix that issue. I have the same issue, "server execution error fail to load image 0 from buffer". I use Window
