### ISSUE TITLE
More backends?

### ISSUE THREAD

**Issue by DeXtmL** [Acly/krita-ai-diffusion#703]
This is _not_ a feature request.
Just wondering if you have any plans to support more backends, like **InvokeAI** ?

I need the super slick linear UI InvokeAI provides to create art directly from my iPad (remotely).
However, this plugin only supports the ComfyUI.
Keeping **two** AI generation backends simultaneously is bad for my VRAM

**Comment by Acly** [comment]
It's unlikely, this project is pretty much married to Comfy (for better or worse ^^).
Also I think Invoke backend is very specific to its own UI and not meant for reuse (admittedly I haven't looked at it in detail)
