### ISSUE TITLE
troubleshooting at installing server

### ISSUE THREAD

**Issue by Beppemassari65** [Acly/krita-ai-diffusion#706]
[client.log](https://github.com/Acly/krita-ai-diffusion/files/15287140/client.log)

I can't install the AI server on krita. I can't even tell if anybody has already opened a similar issue because I can't understand what's happening, sorry. I linked the server  log so you can verify it.

**Comment by Acly** [comment]
Looks like a network connection issue

**Comment by Beppemassari65** [comment]
Thank you so much, in fact I was connected by wi-fi and the connection was possibly too weak... in connected the LAN cable and almost all went well... in fact I had another little issue, my GPU drive was not updated enough... I did that, and now it's all working.
Thank you again.
