### ISSUE TITLE
Cuda unknown error

### ISSUE THREAD

**Issue by joerack81** [Acly/krita-ai-diffusion#707]
Error during server startup: RuntimeError: CUDA unknown error- this may be due to an incorrectly set up environment, eg. changing any env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero [1]
 
 plugin version 1.17.1 Linux mint GPU GTX 3060 12gb

deleted folder reinstalled everything, get same error

**Comment by Acly** [comment]
The error message from CUDA is not very helpful, but since it happens right at the start first thing, I'm guessing it's an issue with GPU driver

**Comment by joerack81** [comment]
Yes, sry, was on me.

**Comment by joerack81** [comment]
yes, sorry was my fault

**Comment by TransRapid** [comment]
What is the resolution?
