### ISSUE TITLE
KeyError: 'ImageScale'

### ISSUE THREAD

**Issue by Wladislav** [Acly/krita-ai-diffusion#709]
Hello, I did everything as described here https://www.interstice.cloud/plugin. But I get an error: KeyError: 'ImageScale' when I try to generate an image and KeyError: 'DifferentialDiffusion' when I do an Infill on an image. Can you help with something please?

![150307](https://github.com/Acly/krita-ai-diffusion/assets/2454823/071c0b43-63f9-4bff-b65a-7326e4e053ce)
![150459](https://github.com/Acly/krita-ai-diffusion/assets/2454823/2ed2b405-070f-4f78-ba1f-99d8147820aa)

KeyError: 'ImageScale'
got prompt
Error handling request
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ImageScale'

**Comment by Acly** [comment]
It means it can't find some nodes in your ComfyUI install. It's probably just too old and needs an update.

**Comment by Wladislav** [comment]
> It means it can't find some nodes in your ComfyUI install. It's probably just too old and needs an update.

I get CompyUI from https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z
Is this an old version?

![153750](https://github.com/Acly/krita-ai-diffusion/assets/2454823/9dc63db2-4f49-401e-8630-b2349ac8abb8)

Where is there a newer version of ComfyUI?

**Comment by Acly** [comment]
No the version is fine. Can you find the node in the UI?
![image](https://github.com/Acly/krita-ai-diffusion/assets/6485914/107cc704-c43e-4c81-ba67-6b5d9becbc4e)

**Comment by Wladislav** [comment]
> No the version is fine. Can you find the node in the UI? 
![000936](https://github.com/Acly/krita-ai-diffusion/assets/2454823/01f9901e-dd80-4fa9-804d-754d7f7e1318)
that's all there is. Do you need to add anything?

**Comment by Acly** [comment]
Both `ImageScale` and `DifferentialDiffusion` are part of base ComfyUI. You have a bunch of nodes I don't know, presumably from some other extensions. Maybe there is a conflict?

**Comment by Wladislav** [comment]
> Both `ImageScale` and `DifferentialDiffusion` are part of base ComfyUI. You have a bunch of nodes I don't know, presumably from some other extensions. Maybe there is a conflict?

Thank you very much! Works!
