### ISSUE TITLE
Can't Inpaint with Live (LCM Lora), Can't use SD1.5

### ISSUE THREAD

**Issue by iterhating** [Acly/krita-ai-diffusion#71]
(This should probably be in a Discussion than an Issue as it might be my own ignorance on controlling the setup)

Whenever I use the Live option, generation works but the result is always a new image spanning the canvas. I can't select some portion and get it to inpaint that. Is that the expected behavior? I can inpaint a section as in the example with Generate.

Separately, I can't use any SD1.5 models. Whenever I select a 1.5 model it states:

_This is a SD 1.5 checkpoint, but the SD 1.5 workload has not been installed._

Did I miss a step? I don't see how to install any 1.5 workloads. 

I'm running a remote server, all the required nodes are installed, and as I said it is generating.
Anyway, thanks for the plug in! I'm somewhat enjoying it now and hopeful it'll be greatly useful in the future.

**Comment by Acly** [comment]
Inpaint in live mode is not implemented so far. I'm not quite sure how it should work yet, the selection method from generation mode doesn't feel right. Need to experiment with it a bit more.

Regarding workloads: that's a term I use for "every model the plugin uses under the hood". If you're using the plugin-managed install you can just select and install it. If you manage your own, please refer to [ComfyUI requirements page](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md). The SD1.5 workload would be all the models listed under SD1.5. At the bottom there are also useful tips on how to check what you might be missing.

**Comment by iterhating** [comment]
I don't see why selecting a region and inpainting that should be any different for live mode, just speaking from the perspective of one user's expectation.

What does live/generate draw from? It it the total image on the canvas? A certain number layers numbered from some base layer? A certain name of a layer? I haven't figured it out yet for live at least, it seemed to ignore info in my 4-5th layer, though it worked as expected (taking in as input the total image shown on the canvas) for the first few layers.

**Comment by Acly** [comment]
What you see in the canvas is also what is sent as input for generation. It's the combination of all (visible) layers.

Only exception is that it excludes control layers that have been selected as input for control net (like pose or sketch).

**Comment by ShadoWxShinigamI** [comment]
Masked live generation with the selection tools would make this tool extremely amazing. Please do add that support.
