### ISSUE TITLE
Ip adapter face SD & XL will not install

### ISSUE THREAD

**Issue by joerack81** [Acly/krita-ai-diffusion#710]
![image](https://github.com/Acly/krita-ai-diffusion/assets/64382714/3018c8b2-ef19-4673-b802-564e2b51ff14)

Unable to install IP-adapter face (SD 1.5 and XL)

Solved copying manually the required files in /ipdapter, but need to start server unchecking the boxes

**Comment by Acly** [comment]
Does it actually work though? Installing IP-adapter face is a 2-step process: first it installs insightface, then downloads models.

Looks like first step failed, but hard to tell from screenshot. Please check client.log for the full error.
Installing insightface on linux can be a bit tricky, it doesn't work from sandbox environment (like flatpak), and requires compiler toolchain installed (gcc).
