### ISSUE TITLE
Function addition requirements

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#712]
Please add the following connection functions integrated into the plugin, thank you very much!

https://github.com/TheMistoAI/MistoLine
https://github.com/lllyasviel/IC-Light
https://github.com/ToTheBeginning/PuLID
https://github.com/huchenlei/ComfyUI-layerdiffuse
https://hyper-sd.github.io/

**Comment by Acly** [comment]
Moved to watchlist #779
