### ISSUE TITLE
Feature request: move the options in the diffusion tab into the styles

### ISSUE THREAD

**Issue by mx** [Acly/krita-ai-diffusion#714]
The diffusion settings (selection grow, selection feather, selection padding) I'll often need to make minor changes to. It would be helpful if these could be done as part of the styles so we can have them quickly swappable, rather than global.

**Comment by Acly** [comment]
That also means you now _have_ to set it up for every style, which might be a big hassle. I don't really see how they're related.

Keep in mind that minor changes can also be done after you apply a result as new layer, just by using a soft brush to erase parts you don't like. The grow/feather doesn't have to be precise, if it's slightly too large that's an easy fix. For padding there are various context options when using "Custom" fill mode which ignore the padding and let you be more specific if needed.
