### ISSUE TITLE
Inpainting with any realistic SDXL model loses detail

### ISSUE THREAD

**Issue by NoMansPC** [Acly/krita-ai-diffusion#718]
Has this happened with anybody else here? Inpainting with 1.5 models is fine and it actually adds more details, but with any SDXL, it airbrushes everything. I don't know if this behavior is the same with other UIs.

**Comment by agoulddesign** [comment]
Yes, definitely notice this behavior. Especially pronounced when using anything other than 100% strength.

**Comment by NoMansPC** [comment]
> Yes, definitely notice this behavior. Especially pronounced when using anything other than 100% strength.

Acly should probably let us choose between Foocus' inpainting model and any other. That's probably the root of the problem.

**Comment by Acly** [comment]
You can disable it (Seamless checkbox in [Generate/Refine Custom](https://github.com/Acly/krita-ai-diffusion/wiki/Inpainting#custom-generation))

Which checkpoint are you using?

**Comment by Acly** [comment]
The Lightning & Turbo merges don't work well with the inpaint model. They also have issues with less than 100% strength (but more subtle). There is no solution for either of those issues as far as I'm aware, so recommend using standard checkpoints (no Turbo/Lightning) for those use cases.
