### ISSUE TITLE
Error failed to download https://bootstrap.pypa.io/get-pip.py: Host bootstrap.pypa.io not found

### ISSUE THREAD

**Issue by nickshotxd** [Acly/krita-ai-diffusion#719]
![Capturedafadf](https://github.com/Acly/krita-ai-diffusion/assets/67675424/f8cd2ebc-91b2-4d5b-b8f0-e9be1c673902)
While i am trying to download the Generative AI server locally on my computer it says error  Error failed to download https://bootstrap.pypa.io/get-pip.py: Host bootstrap.pypa.io not found

**Comment by Acly** [comment]
Maybe connection issue, firewall or something? Did you try the link via browser? Maybe it was a temporary issue, it does seem to work at the moment.
