### ISSUE TITLE
Feature request:  IC-Light support

### ISSUE THREAD

**Issue by davletsh1n** [Acly/krita-ai-diffusion#720]
https://huggingface.co/spaces/lllyasviel/IC-Light/tree/main

its now available for comfyui, very powerful instrument to match lighting between images
![image](https://github.com/Acly/krita-ai-diffusion/assets/62463493/b191c265-9972-4b4c-a006-6e3235b57c4b)

**Comment by LeF0URBE** [comment]
i agree !

**Comment by syl1130** [comment]
Agree, too

**Comment by Acly** [comment]
Tracked via watchlist #779
