### ISSUE TITLE
Question (inpaint support) & request function

### ISSUE THREAD

**Issue by TRGLN** [Acly/krita-ai-diffusion#722]
Can you tell me please how the plugin implements support for inpaint models? 
Can I use my own inpaint model?
I have tested all possible generation methods and it seems only the add content mode works correctly (as an inpaint model)
When connecting any other model that differs from the preset ones, in the add content mode, generation takes a very long time and as a result, a blurred image is obtained.
The plugin itself is great, but it really lacks a more classic mode in which you can select any model \ lora \sampler \ resolution \ and other values. The plugin decides a lot for me, unfortunately it does not always work as a plus.

**Comment by Acly** [comment]
> Can you tell me please how the plugin implements support for inpaint models?

SD1.5: inpaint controlnet
SDXL: fooocus inpaint patch
In settings "Interface" tab there is an option to dump workflows, you can inspect what it does.

> Can I use my own inpaint model?

No.

> When connecting any other model that differs from the preset ones, in the add content mode, generation takes a very long time and as a result, a blurred image is obtained.

It should work for any SD1.5/SDXL checkpoint, there is nothing special about the preset ones. No idea why it would be slower, it might be a different issue. Need more info on what exactly isn't working.

> I have tested all possible generation methods and it seems only the add content mode works correctly (as an inpaint model)

They're meant to be correct for their respective use case... there is also Custom mode where you can set it up manually. The "Seamless" option directly toggles inpaint model on/off.
