### ISSUE TITLE
[Feature Request] Add seed to layer name of generated images

### ISSUE THREAD

**Issue by bjoern-tantau** [Acly/krita-ai-diffusion#727]
When i add a layer from live mode the seed is appended to the layer name. But unfortunately the same doesn't happen for images created under "Generate". This leads to many layers with the same name (which makes Krita's layer export overwrite images while exporting.

**Comment by Corruptinator** [comment]
I'm thinking maybe the "Seed" should be placed before the "Prompt" in the layer name, something like this:

_(Seed), [Generated], (Prompt)_

**Comment by Acly** [comment]
Done in [v1.18.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.0)
