### ISSUE TITLE
Websocket Files Missing Error

### ISSUE THREAD

**Issue by viasky657** [Acly/krita-ai-diffusion#730]
I downloaded the Krita-ai-diffusion plugin as a zip folder, but it was missing the python WebSocket files. (I repeated the download two times to see if it was an internet error but it still occured.) The plugin failed to launch in Krita due to a missing Websocket error. However, I found a method to fix the error by manually downloading the zip files from this repository here: https://github.com/python-websockets/websockets/tree/bf858ac9a6e047c50614d6990a12345e1f38802c. I extracted the zip contents of the Krita-ai-diffusion plugin then I put the folder files into the empty websocket folder. Lastly, I compressed the folder into a zip folder and I went into the tool settings of Krita to add it as a plugin and it worked as intended. I checked to see if this issue was addressed and I did not find a replicate issue, so please let me know if this issue has already been addressed and I will promptly remove this issue.  

My Computer Specs for Replicating the Error:
Operating System: Windows 10
GPU: NVIDIA (Cuda)
Krita Version: 5.2.2

![WebsocketEmptyFolderLocation](https://github.com/Acly/krita-ai-diffusion/assets/89562411/20061aaa-ed47-408f-b510-14a9534828b4)

![WebsocketFilesAdded](https://github.com/Acly/krita-ai-diffusion/assets/89562411/d6297670-7938-4c21-9c5a-8ed6b7e1826d)

![Fixed Websocket](https://github.com/Acly/krita-ai-diffusion/assets/89562411/4667fb62-5d5b-4433-839f-5eb139a6f534)

**Comment by Acly** [comment]
It's a submodule, so it's not part of the source download. The install instructions should link to the releases though, which include websockets.

https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#plugin-is-grayed-out-in-python-plugins-manager
