### ISSUE TITLE
IPAdapter-plus not installed

### ISSUE THREAD

**Issue by kakachiex2** [Acly/krita-ai-diffusion#732]
I get this error when trying to connect but I have IP Adapter already installed in comfyui custom node
![Screenshot 2024-05-23 174459](https://github.com/Acly/krita-ai-diffusion/assets/1762112/5f345c89-747a-40f9-9612-664e780e88f5)

**Comment by Acly** [comment]
Please check that ComfyUI startup console output lists them as loaded, and does not report errors. Also make sure the nodes can be created in Comfy's web UI

**Comment by coolzilj** [comment]
same issue, i'm sure  ipadapter plugin is installed and can be created in web UI

**Comment by snoche** [comment]
same issue here, any solution?

**Comment by yuyukongkong** [comment]
same issue

**Comment by Acly** [comment]
Please mention your plugin version & ip-adapter version, most likely cause is one of them is too old.

If you run ComfyUI local, the plugin queries http://127.0.0.1:8188/object_info
It will return a long list of all nodes. `"IPAdapter":` and `"IPAdapterModelLoader":` need to be in there. Use search to find them or post the output.

**Comment by kakachiex2** [comment]
Any solution for this I have IPA-adapter and all my workflow made use of it but the plugin don't recognize it.
This is an IP-Adapter workflow and work correctly.
![workflow](https://github.com/Acly/krita-ai-diffusion/assets/1762112/c0ccba3b-9417-4765-8634-0227fe75a121)

**Comment by Acly** [comment]
You need https://github.com/cubiq/ComfyUI_IPAdapter_plus
Looks like what you're using is a different custom node pack

**Comment by Ulf3000** [comment]
Having the same issue 

`"IPAdapter":` and `"IPAdapterModelLoader":`

are there and ip adapter works in comfy, all the latest version including the plugin update from yesterday

**Comment by wangwenqiao666** [comment]
![image](https://github.com/user-attachments/assets/2b07d888-2a60-48ab-a55a-7cf098e4530d)
I have the same problem，do you solved it?
