### ISSUE TITLE
[Feature Request] Add proxy support. 

### ISSUE THREAD

**Issue by Leroy-X** [Acly/krita-ai-diffusion#735]
In my country, internet access is heavily restricted, making it difficult to connect to many foreign websites. I have enabled a system proxy using proxy software, but it doesn't seem to work for Krita AI. I hope to see network proxy settings added in the future. 

Thanks

**Comment by Acly** [comment]
You can try modifying [network.py](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/network.py#L72)
In line 72 (below `self._net = QNetworkAccessManager()`) add
```
        from PyQt5.QtNetwork import QNetworkProxy
        self._net.setProxy(QNetworkProxy(QNetworkProxy.ProxyType.HttpProxy, "my.proxy.com", 1234, "user", "password"))
```
Adapt host/port/user/password as needed.
I don't have  time to test it properly or add UI myself at the moment.

Also maybe it makes more sense to add a mirror for the files that isn't GitHub/HuggingFace and much more likely to be accessible. Judging from other issue reports many users who have issues with this will struggle to setup/configure proxy.

**Comment by Acly** [comment]
Ah my bad, there are two more places where `QNetworkAccessManager` is constructed for downloading in [server.py](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/server.py#L278) (lines 119 and 278)

Adding the same code there should make it work for huggingface downloads.
