### ISSUE TITLE
Floating Point Exception in SDClipModel.forward

### ISSUE THREAD

**Issue by adamulp** [Acly/krita-ai-diffusion#737]
I'm trying to get this to work with cpu mode, but it keeps crashing silently when I press the generate button from Krita. I tried running main from the terminal and added some print statements to see where this is happening.

The issue happens in SDClipModel.forward when storing outputs with self.transformer. I don't really understand the syntax for self.transformer, but it looks  like some kind of a constructor/alternative constructor for working with torch.

outputs = self.transformer(
                tokens,
                attention_mask,
                intermediate_output=self.layer_idx,
                final_layer_norm_intermediate=self.layer_norm_hidden_state,
            )

`python main.py --cpu --cpu-vae --verbose --use-split-cross-attention --disable-cuda-malloc --disable-smart-memory`

![image](https://github.com/Acly/krita-ai-diffusion/assets/163217780/d67fbbf3-f72e-4d3f-a43e-75698f02574b)

I should also mention that I had to hack the resources.py file from the plugin zip file because UltimateSDUpscale wouldn't download:
https://github.com/Acly/krita-ai-diffusion/issues/484

**Comment by Acly** [comment]
This is basic generation (100% strength, just text)?
It works for me (just using `--cpu` on the command line). Not sure if those other arguments influence the behavior.
What's your CPU? It might be a bug in PyTorch related to your CPU.

**Comment by adamulp** [comment]
Yeah, just text. I tried with just the --cpu flag first but it wasn't very clear to me where the args array came in for the different functions and class methods, so I just added more for testing the control flow between modules. There are some methods that have "gpu" in the name, but are more universal than that for example.

It's an AMD cpu, same for the GPU, but the GPU isn't officially supported by rocm. I can test a few things again in a couple weeks, including the unofficial rocm with an external ComfyUI. I saw some issues with different versions of ComfyUI and AMD CPUs, but I think those were EPYC chips.

Anyway, it does sound a bit more like a pytorch issue, especially if this kind of thing is still cropping up with different x86 CPUs from AMD. Freebie credits on different sites will probably do the trick for the brainstorming tools I was looking for over the weekend. My python is getting a little rusty, so I'll do some more testing in a couple weeks.

**Comment by Acly** [comment]
The CPU model might make a difference, if it's a relatively new/high-end one it supports more instruction sets (like AVX2, AVX512) which tend to not be tested as much.

Something that worked in another issue for example is to restrict it via environment variable:
```
ONEDNN_MAX_CPU_ISA=AVX2
```
