### ISSUE TITLE
Inpaint Nodes are missing?

### ISSUE THREAD

**Issue by linxl19** [Acly/krita-ai-diffusion#738]
Sir, I have downloaded Inpaint Nodes, but why is it still reminded that I lost the nodes?
How am I supposed to fix this?

<img width="763" alt="PixPin_2024-05-09_12-46-17" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/32e9edb0-9ce1-467f-a6a4-76a350ee3201">
<img width="1070" alt="PixPin_2024-05-09_12-45-00" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/a2a417c1-dcd4-4c62-924c-456833e97be0">

**Comment by linxl19** [comment]
![Uploading PixPin_2024-05-09_12-45-00.png…]()

**Comment by linxl19** [comment]
<img width="336" alt="PixPin_2024-05-09_12-45-00" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/8d9932c7-5b26-4cb0-a307-a3bee32ca073">

**Comment by Acly** [comment]
Check ComfyUI output, did the nodes load correctly?

If you installed very recent version of ComfyUI please update the comfyui_inpaint_nodes and try again. See https://github.com/Acly/comfyui-inpaint-nodes/issues/47
