### ISSUE TITLE
Error during server startup KRITO

### ISSUE THREAD

**Issue by dyno1301** [Acly/krita-ai-diffusion#742]
getting this error. Help me
(my nvidia drivers are uptodate)

![ss krito prob](https://github.com/Acly/krita-ai-diffusion/assets/171027092/e0a91eea-6b74-4cbc-8e40-f10f3a29e7e4)

**Comment by Acly** [comment]
https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#error-during-server-startup-could-not-bind-on-address-only-one-usage-of-each-socket-address-is-normally-permitted

**Comment by dyno1301** [comment]
> https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#error-during-server-startup-could-not-bind-on-address-only-one-usage-of-each-socket-address-is-normally-permitted



> https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#error-during-server-startup-could-not-bind-on-address-only-one-usage-of-each-socket-address-is-normally-permitted

did all the steps checked the ports adn everything but still not solved

**Comment by Acly** [comment]
Linking #774 

But answer is same, if Windows says it can't bind to the port something is preventing it, I don't see what I can do.
