### ISSUE TITLE
Animation on generation button 1.17.2 not working.

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#746]
tinny issue animation is not working, its nice to see that it responds to the click, unfortunately with update its no longer animated

**Comment by FurkanGozukara** [comment]
@Sil3ntKn1ght since on OneTrainer forum people don't want me to reply, you are doing wrong

I did 100+ training research so follow this tutorial and i tell you it will work : https://youtu.be/0t5l6CP9eBg

**Comment by Acly** [comment]
Fixed in [1.20.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.0)
