### ISSUE TITLE
Cloud (runpod) slow, possibly using cpu only?

### ISSUE THREAD

**Issue by mikedinicolatt** [Acly/krita-ai-diffusion#748]
I've deployed RTX 4090 but a single batch image takes about a minute, I assume this is not normal?

**Comment by mikedinicolatt** [comment]
Using the default 512x512, is that considered high res? I did also reduce max pixel count to 2MP. Let me know what else I can try and/or what other debugging I can do, thanks!

**Comment by Acly** [comment]
Anything in 512~1536 range should take around 5-10 seconds per batch. You'll have to check the runpod logs, it should show how long 1 iteration and 1 image takes and similar stats. Maybe there was really slow internet connection between you and the pod.

**Comment by mikedinicolatt** [comment]
Must have been a fluke, all good now thank you!
