### ISSUE TITLE
[Feature request] Please add Anyline and Mistoline control net support

### ISSUE THREAD

**Issue by syl1130** [Acly/krita-ai-diffusion#749]
To add Anyline and Mistoline ControlNet support to Krita AI, ComfyUI Control Net's Anyline offers seamless integration, high accuracy, and user-friendly design, enhancing control and efficiency in applications.

**Comment by pendave** [comment]
Yes I think it's possible, I create anyline image from ComfyUI and drop the image to Krita, it works.

**Comment by Acly** [comment]
Done in [v1.19.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.19.0)
Anyline is replacing previous "Soft Edge" preprocessor.
MistoLine can be used for Scribble, Line Art, Soft Edge (and also Canny but others are better)
