### ISSUE TITLE
Add a Clip Skip option please.

### ISSUE THREAD

**Issue by LuluViBritannia** [Acly/krita-ai-diffusion#75]
Hello!
First of all, amazing plugin!
Sadly, I noticed the workflow you implemented doesn't have a Clip Set Last Layer node (also called "Clip Skip" in Auto1111). A lot of models and LoRAs _require_ a Clip Skip of 2 (-2 in ComfyUI), otherwise the result quality is mediocre.

The proof is in the noodles: make the most basic ComfyUI workflow (Checkpoint Loader + prompts + Ksampler + output), make sure all parameters are the exact same as in Krita, even the prompt (obviously), and generate an image in both Comfy and Krita. You get the same result (with slight variation due to the plugin autmatically upscaling). On the contrary, adding a Clip Skip of 2 in Comfy gives a different result... and a much better one, usually.

I'm sure it depends on the model, but a lot of models and LoRAs I downloaded online require a Clip Skip of 2 to work properly. Please add the option to change the Clip Skip.

**Comment by Acly** [comment]
Yea there is no clip skip at the moment. I always disliked that it was required to be set manually, but unfortunately many checkpoints use 2 (and also many don't). I'm okay with adding it to the style settings, only not sure I will have time for it in the next days. If someone else wants to have a go, it should be straight forward.

**Comment by LuluViBritannia** [comment]
Yeah, I don't like having to set it either xD! Sadly, it's mandatory for 1.5 models to work properly.
I'd love to add it myself, but I checked the plugin's codes and couldn't find out how to add it T_T. I'll let you add it once you have time. Thanks for your hard work!

**Comment by KillyTheNetTerminal** [comment]
Hi! I got a question, how can I modify the workflow under the hood working on the plugin? is curious to me

**Comment by Acly** [comment]
You mean in code? It uses `ComfyWorkflow`, a builder to create ComfyUI prompt JSON. It's a simple wrapper, each function corrsponds to a comfy node, you call the function, supply the inputs, it adds the node, and returns the output.
Eg. to be on topic, [this line](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/workflow.py#L180) creates the Checkpoint Loader node. You'd want to add `clip = w.clip_set_last_layer(clip)` afterwards.

**Comment by LuluViBritannia** [comment]
I think it's a little more complicated than that ^^'. We need to write the function that creates the node in comfyworkflow.py, then call that function in workflow.py, right?

I tried a bunch of times, but I don't know enough about Python, sadly.

**Comment by Fezinaru** [comment]
I just added a pull request for clip skip: https://github.com/Acly/krita-ai-diffusion/pull/136

**Comment by LuluViBritannia** [comment]
Thank you! I confirm it works! I still don't get exactly the same quality as in ComfyUI directly, but it's much closer!

**Comment by Fezinaru** [comment]
Your welcome. I needed clip skip myself and know python so I figured I'd spend my Sunday afternoon tackling it.  I went with a positive number scale since Auto1111 does that and CivitAI uses positive numbers for their clip skip tags as well.
