### ISSUE TITLE
Issue with the selection of the 'selected area' not working when using the AI drawing feature in Krita plugin version 1.7.1 (Krita 5.2.2)

### ISSUE THREAD

**Issue by dada5872** [Acly/krita-ai-diffusion#752]
Hello, my ComfyUI + Krita setup is functional for drawing. However, when I attempt to use a selection before initiating an AI draw, the selection seems to have no effect. I am using version 1.7.1 of the Krita plugin and Krita version 5.2.2. Below is part of the installation process for the plugin:

Above content translated into English for convenience to post a question on GitHub to the developer. This issue is related to AI painting functionality.
![image](https://github.com/Acly/krita-ai-diffusion/assets/69775612/9a4a815e-b9e5-458e-af4b-5b6538885ceb)

Real-time painting is not supported.
![image](https://github.com/Acly/krita-ai-diffusion/assets/69775612/53f6395a-4b00-4e9a-856e-4a31dfdee7d0)

Generated painting is possible.
![image](https://github.com/Acly/krita-ai-diffusion/assets/69775612/abc08d23-4649-4d0f-b2ed-b9cc74ba8ae7)

**Comment by Acly** [comment]
>  I am using version 1.7.1

That is from half a year ago :) See https://github.com/Acly/krita-ai-diffusion/releases for recent versions

**Comment by dada5872** [comment]
I've also tried version 1.7.2, and I'm encountering the same issue.



---Original---
From: ***@***.***&gt;
Date: Fri, May 31, 2024 23:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Acly/krita-ai-diffusion] Issue with the selection of the'selected area' not working when using the AI drawing feature in Krita pluginversion 1.7.1 (Krita 5.2.2) (Issue #752)




  
I am using version 1.7.1
  
That is from half a year ago :) See https://github.com/Acly/krita-ai-diffusion/releases for recent versions

**Comment by Acly** [comment]
It was not even implemented in 1.7.x, current is 1.**17**.2
Please check settings are showing the version at the bottom

**Comment by dada5872** [comment]
It seems there was a mistake in my version notation; the two versions I am referring to are .1.17.1 and 1.17.2.

Currently, after updating to version 1.17.2, I encounter an error:
The message reads: 
`comfyui has already been updated to the latest version.`

However, the issue persists with the following error:
`Error: Error: The custom node 'ComfyUI_IPAdapter_plus' is outdated, please update.`

I confirm that my ComfyUI_IPAdapter_plus is indeed on the latest version.

Could you please help translate the above content into English for me? This would facilitate posing my question directly to the author on GitHub.

![image](https://github.com/Acly/krita-ai-diffusion/assets/69775612/22916a3b-9cfe-49db-82b1-2d42806abc93)
![image](https://github.com/Acly/krita-ai-diffusion/assets/69775612/9ab6c7b0-655c-44ef-9cd8-b30db4b42794)
![image](https://github.com/Acly/krita-ai-diffusion/assets/69775612/baf67376-35e3-4349-9c02-33402575b34f)

**Comment by dada5872** [comment]
Problem Resolved

The issue has been resolved.
