### ISSUE TITLE
[Feature Request] Add support for AlignYourSteps / AYS scheduler.

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#755]
Already supported in ComfyUI but the implementation for krita-ai-diffusion isn't as simple as switching to it in samplers.json

Separate feature request which goes along with AYS scheduler: [PCM](https://github.com/G-U-N/Phased-Consistency-Model/) with its [fp16 models here](https://huggingface.co/Kijai/converted_pcm_loras_fp16/tree/main)

**Comment by Acly** [comment]
Moved to watchlist #779
