### ISSUE TITLE
[Feature Request] Prompt Translation

### ISSUE THREAD

**Issue by Drakosha405** [Acly/krita-ai-diffusion#756]
1. add a translator from a custom language to English. for example I use [DeepTranslatorCLIPTextEncodeNode](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet) and edit 233 line  in comfy_workflow.py
add the translation option to the interface settings and manually specify which language to translate from for greater accuracy (when combining different languages, English + user did not always translate when I use DeepTranslatorCLIPTextEncodeNode 

writing prompts in your native language will significantly simplify the workflow and become accessible to even more people. And understanding SDXL or SD3 a simple prompt makes this option even more valuable.

2. custom workflow in workspaces? Is there any news about this?
I saw a plugin for photoshop and it just implements the ability to edit the workflow, I don't know how it is from a technical point of view, but it looks just like I dream of for krita. where I can edit any process by simply adding any nodes. 
https://youtu.be/JwLbnO4px-E?si=ggNNPmVZGVUpnsTx
https://github.com/NimaNzrii/comfyui-photoshop

adding this will eliminate most of the new integration requests for any new features. and even my point No. 1 could easily be crossed out with user workflows.

3. clearing the history of empty queries (where deleted all the images)
at the moment, empty logs can occupy the entire window during long-term operation, the solution at the moment is simply to create a new file, but at the same time the history is lost, which is not very pleasant

4. bug when copying prompt from image, the negative field is filled with text from the style, which leads to duplicate text when sending if you do not manually clear the field

5. adding lora to prompt is even more convenient. something like adding a translucent + button at the end of the input line, when clicked, a list of Loras will drop down and then when pressed, it will be added to prompt
this point also echoes the first one, where people, if they have a translator, will not have to switch between languages to add lora

**Comment by Acly** [comment]
1. I think plugin translation has a bit higher priority. Prompt translation sounds interesting too, though not sure how much I like depending on eg connection to google for that.
2. No news. #385
3. The empty logs are just a visual glitch, they disappear on restart or switch document tab. But for some reason clear button is often requested and probably easy to have, so might as well...
4. Should be fixed (1.18.0)
5. Yes maybe, but there are already enough ways to add Lora, it will probably not be important enough

**Comment by AlexYez** [comment]
> 1. I think plugin translation has a bit higher priority. Prompt translation sounds interesting too, though not sure how much I like depending on eg connection to google for that.
There is a great plugin with translation via offline model, it would be great to intern it into the workflow: https://github.com/kingzcheung/ComfyUI_kkTranslator_nodes

**Comment by Acly** [comment]
I'm making this about prompt translation to track that.

Clear history is implemented in [1.20.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.0)

**Comment by Acly** [comment]
Prompt translation implemented in [v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0)
