### ISSUE TITLE
[Feature] Bad quality when refining small selection

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#757]
On SDXL models, say you have 1024x1024 image, and you selected a 512x512 part of it. If you refine, you get distorted results.
Though, it seems some models aren't as bad as others.

As a suggested solution:
Include an option in custom refine to re-scale before refining the selection. i.e. If I write 1024 in the re-scale, the 512x512 should be viewed to the model as 1024x1024.

This would also work well for SD15 models when working on details as some models work with 512 and others with 7xx.

What I currently do to overcome this is to resize the whole canvas to a random bigger number. I end up with more than 1024x1024 size, and the processing of the image starts taking longer.

**Comment by Acly** [comment]
It's already implemented like that. Could there be another cause for the distortions?

**Comment by guzuligo** [comment]
I did some experimenting. I think I was wrong.

It seems the issue is with the ControlNet's not compatible with some of the newer XL models.
