### ISSUE TITLE
Allow configuration of models

### ISSUE THREAD

**Issue by Banbury** [Acly/krita-ai-diffusion#758]
There are several new ControlNet models for SDXL out (https://huggingface.co/xinsir), which I would like to try. But the models are hard-coded.
It would be nice, if all models were configurable. A simple JSON file would be enough, instead of `search_paths` in `resources.py`.

**Comment by Danamir** [comment]
Having tested those models, I can confirm that they are noticeably better than the older ones for SDXL models ; and waaaaay better for PDXL derivative models (where the older one where not even usable). 

But they also are bigger(2.3GB each), need more ram, and can be 1.5 slower depending on your specs.

**Comment by mechamuffin2000** [comment]
I was wondering about this myself, I've been trying to use xinsir's ControlNet models through Krita on the local managed server but it doesn't seem like the plugin recognizes them as canny/scribble models.

**Comment by LeF0URBE** [comment]
i backup this, should be a choice in the setup.
is there a doc to target what controlnet is prioritized in the extension ?

i enjoy this krita ai extension greatly btw :)

**Comment by Banbury** [comment]
The names of all controlnet models are fix and cannot be changed easily. So there is no prioritization happening.

**Comment by Danamir** [comment]
That being said, if you want to alter the code on your installation to do a quick test, the file to look into is `/ai_diffusion/resources.py`. Comment the original `ControlMode.scribble`, `ControlMode.canny_edge`, and `SDVersion.sdxl, ControlMode.pose` lines for SDXL and replace the model detection by the xinsir models, for example (adapt to your models names) : 

```Python
    # resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.scribble): ["control-lora-sketch-rank", "sai_xl_sketch_"],
    resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.scribble): ["controlnetxlCNXL_xinsirScribble",],

    # resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.canny_edge): ["control-lora-canny-rank", "sai_xl_canny_"],
    resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.canny_edge): ["controlnetxlCNXL_xinsirCannyv2"],

    # resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.pose): ["control-lora-openposexl2-rank", "thibaud_xl_openpose"],
    resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.pose): ["controlnetxlCNXL_xinsirOpenposeTwins"],
```

Be sure to revert to the old code once finished testing to avoid unexpected results.

**Comment by Acly** [comment]
resource.py search paths are a priority list. Prepend the name of a file you want to use and it should work. It's not really harder than editing a JSON?

If someone wants to add support for additional paths from JSON go ahead. I usually prefer to try/compare/experiment with new models in ComfyUI directly, it's great for that.

On the modes: has anybody compared Xinsir Scribble with Mistoline?

**Comment by Banbury** [comment]
For end-users finding and editing a Python source file is harder than editing a config file.
Also all changes I make to resource.py would be overwritten with the next update.

**Comment by LeF0URBE** [comment]
> resource.py search paths are a priority list. Prepend the name of a file you want to use and it should work. It's not really harder than editing a JSON?
> 
> If someone wants to add support for additional paths from JSON go ahead. I usually prefer to try/compare/experiment with new models in ComfyUI directly, it's great for that.
> 
> On the modes: has anybody compared Xinsir Scribble with Mistoline?

thanks you so much for your reply ! i've done what you suggested and i'm REALLY happy with the result
by checking the log workflow i can see the Xinsir Openpose model loaded

![workflow Krita ai Xinsir controlnet](https://github.com/Acly/krita-ai-diffusion/assets/130357976/bf282338-ca32-4b7e-a017-10c3aeb617da)

**Comment by Serasul1984** [comment]
> resource.py search paths are a priority list. Prepend the name of a file you want to use and it should work. It's not really harder than editing a JSON?
> 
> If someone wants to add support for additional paths from JSON go ahead. I usually prefer to try/compare/experiment with new models in ComfyUI directly, it's great for that.
> 
> On the modes: has anybody compared Xinsir Scribble with Mistoline?

![new-sdxl-controlnets-canny-scribble-openpose-v0-ninvi9ye973d1](https://github.com/Acly/krita-ai-diffusion/assets/106548837/892f03ee-4e65-4a38-aea2-cfcfae1a82bf)
![icymi-new-sdxl-controlnet-models-were-released-this-week-v0-p3nronupu04d1](https://github.com/Acly/krita-ai-diffusion/assets/106548837/4f48127f-830f-44e4-a088-936a4f8c77e8)

**Comment by LeF0URBE** [comment]
what i find hard is that for editing the ressource.py i had to locate it by myself not knowing where. (my Krita is on D drive)
it is there :
C:\Users\name\AppData\Roaming\krita\pykrita\ai_diffusion
just leaving that here for when i forgot. I would have to search for ressource.py or external controlnet or something to see where it is located.

**Comment by krigeta** [comment]
> That being said, if you want to alter the code on your installation to do a quick test, the file to look into is `/ai_diffusion/resources.py`. Comment the original `ControlMode.scribble`, `ControlMode.canny_edge`, and `SDVersion.sdxl, ControlMode.pose` lines for SDXL and replace the model detection by the xinsir models, for example (adapt to your models names) :
> 
> ```python
>     # resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.scribble): ["control-lora-sketch-rank", "sai_xl_sketch_"],
>     resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.scribble): ["controlnetxlCNXL_xinsirScribble",],
> 
>     # resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.canny_edge): ["control-lora-canny-rank", "sai_xl_canny_"],
>     resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.canny_edge): ["controlnetxlCNXL_xinsirCannyv2"],
> 
>     # resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.pose): ["control-lora-openposexl2-rank", "thibaud_xl_openpose"],
>     resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.pose): ["controlnetxlCNXL_xinsirOpenposeTwins"],
> ```
> 
> Be sure to revert to the old code once finished testing to avoid unexpected results.

So I did the following and now it is saying "The controlNet model is not installed"
```
optional_models = [
ModelResource(
        "ControlNet Canny Edge (XL)",
        ResourceId(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.canny_edge),
        {
            Path(
                "models/controlnet/controlnet-canny-sdxl_1_0.safetensors"
            ): "https://huggingface.co/xinsir/controlnet-canny-sdxl-1.0/resolve/main/diffusion_pytorch_model_V2.safetensors",
        },
    ),
]

# fmt: off
search_paths: dict[str, list[str]] = {
resource_id(ResourceKind.controlnet, SDVersion.sdxl, ControlMode.canny_edge): ["controlnet-canny-sdxl"],
}
```

May you guide me what is happening?

**Comment by Acly** [comment]
Search path needs to match the filename.

Xinsir, MistLine and some others are added in [v1.19.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.19.0)
I'm closing this, but if someone still wants to implement external JSON of some sort feel free to re-open.
