### ISSUE TITLE
got an unexpected keyword argument 'cache_dir'

### ISSUE THREAD

**Issue by linxl19** [Acly/krita-ai-diffusion#760]
Sir,
When I use Line Art or Scribble, the following error message appears.
**_Server execution error: LineartDetector.from_pretrained() got anunexpected keyword argument 'cache_dir'_**
 I have updated comfyUI to the latest version and Krita ai diffusion to the latest. 
How can I solve this problem?
THX.
<img width="330" alt="PixPin_2024-06-02_19-53-33" src="https://github.com/Acly/krita-ai-diffusion/assets/44080439/d82daebb-39db-4068-9ab8-64f326ff8a2a">

**Comment by linxl19** [comment]
Still can't fix it.

**Comment by Acly** [comment]
Probably an issue with comfyui_controlnet_aux custom node, try to update it?
