### ISSUE TITLE
I cant use my AMD graphics card

### ISSUE THREAD

**Issue by rodyupi** [Acly/krita-ai-diffusion#764]
![11](https://github.com/Acly/krita-ai-diffusion/assets/171649138/105bc333-911b-4d15-be24-346c9e0f1e23)
![radeon](https://github.com/Acly/krita-ai-diffusion/assets/171649138/d97a7ae2-34af-4fd2-90c6-6e70edf215d6)

**Comment by Acly** [comment]
Did you initially install with DirectML selected?

**Comment by martinobal1** [comment]
I got same problem :(((

**Comment by sincess1** [comment]
I have the same problem. Has anyone found a solution?
