### ISSUE TITLE
[Feature request] Independent Lora page

### ISSUE THREAD

**Issue by mvstrawn** [Acly/krita-ai-diffusion#767]
First of all thank you for this project, it's incredible.

It would be great if we could have a page for configuring Loras and possibly saving groups of Loras to apply to generations. As it is now, if I want to quickly gen e.g. a set of 10 images with a Lightning model just to test, and then gen more with the non-Lightning version of a model, I have to coordinate Loras between both models.

It would be much more convenient to have a detached Lora page that allows us to plug in a set of Loras independent of the model/style preset being used. It would also allow for the usage of different Lora configs with the same style preset, which I personally frequently wish to do.

**Comment by Muskelmagier** [comment]
I would second this, 

especially if I have Lora's with several subjects and trigger words. that would be much easier to manage loras similar to how part of the CivitAI addon works for A1111.

**Comment by Serasul1984** [comment]
i want this too i have over 36 loras and made for every single one of them a .txt with their trigger words in it.......

**Comment by Acly** [comment]
Linking this to #337 and #280 which are very similar.
