### ISSUE TITLE
Error:  "reference; style; composition; face" never work even once.

### ISSUE THREAD

**Issue by py613** [Acly/krita-ai-diffusion#768]
all  control layers working properly except "reference; style; composition; face"

they all  got the same error message like this:
![error1](https://github.com/Acly/krita-ai-diffusion/assets/156308766/79256a2a-3430-4ae9-9b7b-8ff0b3cb5d08)

and the error message in terminal of ComfyUI  is like this:
![error2](https://github.com/Acly/krita-ai-diffusion/assets/156308766/47d84c76-2fcd-4e90-b51e-1eecd61b5168)

anyone could help me out? a lot of thanks.

**Comment by Acly** [comment]
Looks like a corrupt file, try re-downloading the Clip Vision model. It's located in `.../ComfyUI/models/clip_vision`

**Comment by py613** [comment]
> Looks like a corrupt file, try re-downloading the Clip Vision model. It's located in `.../ComfyUI/models/clip_vision`

Great !! everything works now ! thanks a lot. loving you
