### ISSUE TITLE
Can't get regions to work

### ISSUE THREAD

**Issue by AvidSpline** [Acly/krita-ai-diffusion#769]
First: great work on this feature. It's really exciting! I'm jumping in early with some bugs I encountered trying to use it this morning. (49cfcefde11ce2768f1f782b34b5a5ae6f6f9fd6, 'Shortcut to create a region').

I had pulled the pr where this was being worked on last week and it mostly worked, with blending and ui issues. I'm now trying this on Main and I can't get it to work at all, basically. It doesn't seem any different than just selecting a region and generating for that region, at best, and at worst it ignores the region prompt entirely (most of the time this is what happens).

I have tried in both live and generate mode. Maybe I'm missing something simple that I need to do outside of the ui to enable this workflow ?

Normal mode, basic sd 1.5 model, no loras, dpm++ 2m, 20 steps, 7 cfg

1. I created a new document
2. I type in what I want, in this case a forest scene, and generate, select my scene, so far so good
3. I click 'new region'. I would expect this to create a new layer, but instead it adds a region to my selected layer. A little odd feeling, but probably so I can add layers to regions that don't have them... So I move my forest description there.
4. I click new region again, which adds a layer like I expected. 
5. I select a foreground area. A selection mask layer is created at the top of my layers list. 
6. I type 'a white cat' and tap fill. I get no pictures of cats, even if I weight this term all the way to 2. I've tried selecting other regions, the paint layer, the mask, nothing generates the cat.

<img width="581" alt="Screenshot 2024-06-08 093051" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/a00ff7a6-1b65-497c-8904-f55569ce34eb">
<img width="607" alt="Screenshot 2024-06-08 093139" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/2021bd9d-d70a-42c5-abb0-95f902f00e76">

7. I switched to live mode to try there with the same layer and region setup:

<img width="877" alt="Screenshot 2024-06-08 093605" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/2e1c8a44-098b-45fe-a4f3-fbbdcc8c067c">

Still no cat even with multiple regens. Mostly it puts the road there, but it did pop a dress in there once. I tried editing the region prompt, no luck.

8. I create a new region with the same selection. I type a white cat. It doesn't automatically regen, even though it probably should in live mode. Editing the region prompt is not triggering regens at all.

This doesn't work in live mode either and has the additional complication of not showing any of the layers that aren't selected, so i have to switch back to general to see the layers. 

9. Minor tweak: In live mode the text "Describe the content you want to see or leave empty"... it's no longer clear what this text refers to. I sit the background ? It the whole thing ? Is it added to every layer ? How does this relate to the selection ?

<img width="826" alt="Screenshot 2024-06-08 094021" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/8222f235-0c20-46ac-81eb-8ed0d38ec523">

Even if this did work I'd want to see my layer context here, the same as in generate mode. I'd also expect that when I click a layer with the region it switches to that region (this works) AND remembers what the selection was but lets me redefine it.

10. I created a new region. I added 'a dog'. I selected a new area. I hit generate. No dog.
11. I created a new layer with the plus button. It showed the link a layer controls. I linked it to an existing layer (a white cat) that was already linked to another layer, just to see what would happen. I linked it to 'white cat', but it still shows the text for 'a dog'

<img width="582" alt="Screenshot 2024-06-08 094848" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/9170cb4e-ed07-48be-a1f3-a41a5716e830">

<img width="129" alt="Screenshot 2024-06-08 094900" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/24a64f0d-2a56-479c-99f4-990b258ac1a8">

<img width="285" alt="Screenshot 2024-06-08 094909" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/ebf9c235-da4b-4f3a-ad47-047d0a3d05aa">

13. I started a new document in live mode and tried adding forest scene, switched to juggernaut reborn because base sd was giving me cartoons. Generating worked as normal. Then make a selection, hit new region button, typed 'a cat'. It did regenerate as I typed this time, unlike earlier when I switched to live with existing regions. But no cat appeared.

FYI: I experimented a bit and if I create a new layer, then hit the new region button next to 'Active layer not linked to a region', then typing in that field does not live generate, so that's a small bug that might be easy to reproduce. I think live generation is broken when you aren't just creating a region with the the icon button. e.g. selecting a layer, linking a layer to a region, all seem to break it.
 
I tried changing the text for the "describe the content" field to "a photo of a bright forest scene, highly realistic, with a cat and dog in the foreground". Still no cat.

The only way I can seem to generate a cat is to create a new layer, select an area, do not link or create a region, and change this basic "describe the content" text, which is probably just doing what it was doing before regions.

Oh, I found another way that works in live mode. If I unselect everything, create a new region, then type 'a cat' and then draw the selection, it generates the cat (although I'm not sure this is actually using regions, it is somewhat blended but not more than I would have expected pre-regions). Looks terrible:

<img width="514" alt="Screenshot 2024-06-08 101031" src="https://github.com/Acly/krita-ai-diffusion/assets/152655489/d97c0f11-8018-4f17-8290-3c888a776943">

If I do the selection FIRST, then create a new region, this does not work. Seems like maybe the selection is associated with the region ?Maybe it should deselect when you create a region to prevent this if the selection is somehow associated with a previously selected region ? Then when you select a previous region it reselects what was selected for that region, if anything ? 

However, if I unselect everything, then create a new region again, type 'a dog' and then make a selection: no dog. So it only works once ?  Very confused here!

**Comment by Acly** [comment]
You're probably right about this feature requiring at least a short tutorial to get started with the basic idea.

I think you _mostly_ got it, and we agree on the things that should work (and mostly are implemented like that). There is one big misconception, which is that it has anything to do with selections.

Selections are used for inpainting as before, and they're a completely orthogonal feature. They're not required for, but can work together with regions. In order to define a region, the (alpha) mask of the linked layer or group is used. So you have to "paint" your region bounds, or you could use a selection fill. An empty layer covers zero area, it will have no effect.

Another thing: the bottom prompt ("common" or root prompt) is not attached to any region or area. It allows you describe the overall setup of the scene, and will be appended to all region prompts. It seems quite important to roughly mention what is going in the entire image. It can and will also be used as background region if one isn't specified, but often it makes sense to have a separate prompt for that.

![Screenshot 2024-06-08 203920](https://github.com/Acly/krita-ai-diffusion/assets/6485914/3762d640-7332-471b-a29c-b07764a9d371)

![Screenshot 2024-06-08 203719](https://github.com/Acly/krita-ai-diffusion/assets/6485914/51f2e9b9-b94b-4848-916e-dc175f12a587)

**Comment by Acly** [comment]
The idea for Live mode is that you
* create a new region
* enter the text for what you're about to draw
* start painting

The prompt you entered will now affect only the new things you paint. Repeat the process when you move to the next subject. Go back to a previous subject by selecting its layer.

**Comment by Acly** [comment]
meinamix (realistic models suck at interactions...), some manual corrections and removing of 5th legs, and a bit of inpainting using "Refine Region"

![Screenshot 2024-06-08 211202](https://github.com/Acly/krita-ai-diffusion/assets/6485914/770125cb-c66c-48bd-a784-26cf9fa191f2)

**Comment by AvidSpline** [comment]
Ahh, that makes a LOT more sense.  I can also see why this is a better way to handle things. Thanks for the thorough explanation; I’ll give it a try later today/ early tomorrow when I’m back at my machine.

**Comment by AvidSpline** [comment]
Oh, one other thing I noted: when I “approve” a layer change even without regions in live mode it used to put a new layer with the name from the prompt in the later menu and it no longer seems to. Is that an intended change? It happens even if I don’t use regions. I tend to use that to go up and down branches of gens, since these are more of trees to me than a flat list.

**Comment by AvidSpline** [comment]
Ok, tried all this and other than the no regions live mode not adding new layers bug(?) it works great. So much better than managing selections. Awesome work.

**Comment by Acly** [comment]
Not adding a layer was intended, mainly because with N regions you get N new layers each time you apply. It clutters the stack to the point where you have to manage it, which I found to be rather distracting in Live mode.

Could keep the new layer for when no regions are used though.

Also if you create a group it will add layers instead of replacing content (same as in generate workspace).
