### ISSUE TITLE
[Feature Request] Controlnet Scribble sdxl intergration

### ISSUE THREAD

**Issue by kexul** [Acly/krita-ai-diffusion#771]
Hi, this seems to be better than the current scribble control net, would you mind to intergrate it?

https://huggingface.co/xinsir/controlnet-scribble-sdxl-1.0

![图片](https://github.com/Acly/krita-ai-diffusion/assets/5920217/3b391dcd-2c0a-4368-8e3d-6805ad6417bc)

**Comment by Acly** [comment]
Moved to watchlist #779
