### ISSUE TITLE
IPAdapter composition

### ISSUE THREAD

**Issue by jccluaviz** [Acly/krita-ai-diffusion#773]
Hi, guys.

Seems I'm having some troubles trying to IPAdapter composition transfer work.

I've been testing the workflow you are using with **IPAdapter Loader + IPAdapter Encoder + IPAdapter Embeds** nodes. When i use this aproach, the result is not what i expect of the composition transfer. Most of times the adherence to the composition is wrong.

Changing this nodes in the workflow with **IPAdapter Unified Loader + IPAdapter Advanced** seems to work like a charm in my case.

 Maybe i'm doing something wrong ?

Thank you, very much

**Comment by Acly** [comment]
I'm pretty sure those are just two methods to do the same thing. Using Encoder + Embeds allows to aggregate and weight multiple images, that's all.

Do you have a workflow that compares the two? I checked them side-by-side at the time and they gave identical results, but can't find the workflow anymore right now.

**Comment by jccluaviz** [comment]
Sure, i send you this workflow. 

A use a red car as image for the IPAdapter and a prompt turn the car to black.  IPAdapter Unified Loader + IPAdapter Advanced seems to be more consistent with the composition. Half of times, embeds, turns the car to face in the other direction.

[Test (1).json](https://github.com/user-attachments/files/15788813/Test.1.json)

Thank you.

**Comment by Acly** [comment]
2 differences in your workflows:
* The embeds workflow has `end_at=0.8`, the unified workflow has `end_at=1.0`
* The embeds workflow loads the STANDARD IPA model `ip-adapter_sdxl_vit-h`, the unified workflow loads the PLUS model

If you align both, they produce exact same results.

**Comment by jccluaviz** [comment]
Ohhh, yeaaaa. 

Can i chose anyway the model that is loaded by the embeds ?

Hehe. Well who cares there is a new UPDATE to play with region control. 

Woooohoooo !!!

Thank you, thank you, thank yo.

**Comment by Acly** [comment]
I think if you don't have the standard model available, it will use the plus one. But there is no UI to select at the moment. You'll have to edit resources.py to load a specific model.
