### ISSUE TITLE
Tooncrafter support

### ISSUE THREAD

**Issue by extra-large-onions** [Acly/krita-ai-diffusion#778]
Is there any plan to support [toon crafter](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/) for animation?
I can't thank you enough for this plugin.

**Comment by Acly** [comment]
I'd like to work on animation more at some point, but it's a big project. Only few Krita animation features are exposed to plugins, so still unclear how well it can work.

I'm move this to the (new) watchlist for now: #779
