### ISSUE TITLE
Can't you make the inpainting model recognizable?

### ISSUE THREAD

**Issue by dydtjrwls1** [Acly/krita-ai-diffusion#78]
I tryed to generate image with inpainting model but it was not recognizable.
Please add this feature.

**Comment by Acly** [comment]
It's disabled on purpose. Inpainting automatically uses inpaint ControlNet, which provides a similar effect, but doesn't require a separate inpaint checkpoint for every checkpoint you want to use.

Another reason to disable them is that they did not work correctly with ComfyUI's inpaint masks ([discussion here](https://github.com/Acly/krita-ai-diffusion/issues/26#issuecomment-1763367439)). Results were bad/confusing.
