### ISSUE TITLE
[Version 1.18.0] Krita crashes after manual update because backup folder is to big?! ...........

### ISSUE THREAD

**Issue by Serasul1984** [Acly/krita-ai-diffusion#781]
download zip of new version
open it
installed it in the right folder
in krita configuration
in server configuration it will update the plugin
click update
krita crashes

my pluginfolder is 72GB big (many checkpoints and loras)
when i cut out my models and loras, update only takes secounds and krita has no problems

seems like a folder that is to big will crash krita when the plugin makes an backup folder in the process.

**Comment by Acly** [comment]
Hmm I tried it with 110GB folder and it worked fine. The upgrade moves the folders to backup and back, usually that's a very quick and painless operation (nothing is copied). But it depends a lot on OS, file system, storage device, and things like symlink, network drives, and probably more stuff I haven't thought about, can have an influence.

If it remains an issue, you can use ComfyUI/extra_model_paths.yaml and just store your models somewhere else. That way the plugin installer never has to touch them.
