### ISSUE TITLE
Where is BATCH SIZE & SAVE LIVE?

### ISSUE THREAD

**Issue by Duemellon** [Acly/krita-ai-diffusion#782]
I haven't used this for a few months & a lot has changed.

How do I apply batch sizes?
How do I send a Live generated image to canvas?

**Comment by Duemellon** [comment]
found the "apply live", it's a checkmark next to the play button

**Comment by Acly** [comment]
Batch size is in performance settings.
Batch count is in the drop down next to Generate button.
