### ISSUE TITLE
Regional Prompting Busted by Missing Nodes

### ISSUE THREAD

**Issue by SytanSD** [Acly/krita-ai-diffusion#786]
Error:
```invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node ETN_BackgroundRegion does not exist.', 'details': "Node ID '#3'", 'extra_info': {}}
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node ETN_BackgroundRegion does not exist.', 'details': "Node ID '#3'", 'extra_info': {}}
```
I have run multiple custom node updates and updated my whole comfy install, yet this is still throwing this error and I can't find any info on what note this pack is from. Help would be greatly appreciated <3

**Comment by SytanSD** [comment]
My ComfyUI Manager was bugged, so I had 37 updates that were behind 😅

**Comment by 1036065542** [comment]
update comfyui-tooling-nodes
