### ISSUE TITLE
Saved .kra with [Version 1.18.0] does not has Control Layers.

### ISSUE THREAD

**Issue by pendave** [Acly/krita-ai-diffusion#788]
I have added complex Control layers but when I saved the .kra with [**Version 1.18.0**] those structures are not there anymore as before in [**Version 1.17.2**] . Also the struture in old .kra saved with [**Version 1.17.2**] are not there anymore when it opened with [**Version 1.18.0**].

![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/a1777758-fad4-473d-b388-f08ee3e68bd7)

Could you please let the function back to new version?

![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/f7538b2e-c210-47c7-970a-e68cc7332460)

If I wanna get back the info such as the control layer strength saved in old .kra file, how could I do?

**Comment by pendave** [comment]
BTW, in Live mode, sometimes when I click the button to add Control Layer, it does not appear or have no effect. I have to swtich to Generate mode to add.

![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/ef073c10-b9a7-4fdf-9f5e-18e696b65476)

And when an image layer has filter layer and it's selected, when I run the Live button it report error in Red. Could you please fix this let it go when filter layer is selected? :)

**Comment by Acly** [comment]
Fixed the issues with control layers. Loading old .kra files should work (as long as you didn't save/overwrite them with the new version I hope!).

> And when an image layer has filter layer and it's selected, when I run the Live button it report error in Red. Could you please fix this let it go when filter layer is selected? :)

Just to clarify, there is "Filter Layer" and "Filter Mask". You mean the "Filter Mask"?

**Comment by pendave** [comment]
> Fixing the issues with control layers. Loading old .kra files should work again (as long as you didn't save/overwrite them with the new version I hope!).
> 
> > And when an image layer has filter layer and it's selected, when I run the Live button it report error in Red. Could you please fix this let it go when filter layer is selected? :)
> 
> Just to clarify, there is "Filter Layer" and "Filter Mask". You mean the "Filter Mask"?

Yes, all kinds of Mask Layers.

**Comment by Acly** [comment]
Fixed in [1.18.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.1)
