### ISSUE TITLE
Error when generating with AMD GPU

### ISSUE THREAD

**Issue by AuDaCZ** [Acly/krita-ai-diffusion#792]
Hello, please can someone help me? 
I installed Krita + The AI Image Generation plugin and when i generate something i always got error:

"Server execution error: Could not allocate tensor with (random number) bytes. There is not enough GPU video memory available.

This error i always get when i generate, i have AMD GPU RX 6700 XT 12GB and i tried so many settings and everything, even reinstall GPU drivers and i don't know how to fix it. Please help!

![Error in Krita AI](https://github.com/Acly/krita-ai-diffusion/assets/86071556/65dfdec6-a76d-4ba9-9eb6-85bbcf08f3d6)

**Comment by Acly** [comment]
You can try in Performance settings to lower batch size (choose preset CPU for lowest setting), and a low canvas resolution like 512x512. AMD support is unfortunately not great and uses much more memory than it should.

**Comment by Zenesy** [comment]
Is that it? 

Changing to CPU (or any settings change in Performance) does not make any difference.

Why claim any sort of AMD support when even 12 GB VRAM, and reportedly 24 GB VRAM will not be able to run it? That is not minimal support, that is non-existent support whatsoever.

**Comment by Acly** [comment]
I didn't claim support initially, but enough users asked/complained why it doesn't support AMD when ComfyUI (the backend) does, and that it works for them if they set it up. 12 GB should work for basic stuff, it seems people get some use out of it dispite the poor performance and prefer it over no support at all.
