### ISSUE TITLE
LoRA filter not working on Mac (empty dropdown)

### ISSUE THREAD

**Issue by olegsatov** [Acly/krita-ai-diffusion#793]
Here is how LoRA filter dropdown menu looks on Windows machine:

<img width="326" alt="Снимок экрана 2024-06-12 в 14 59 10" src="https://github.com/Acly/krita-ai-diffusion/assets/147343262/cf9588f7-01d9-4f5b-9148-5b4c85faa8a1">

And here is what I get on Mac (empty dropdown):

<img width="461" alt="Снимок экрана 2024-06-12 в 14 58 26" src="https://github.com/Acly/krita-ai-diffusion/assets/147343262/798d22e4-9cdf-48e4-bb25-493809f5bd91">

___

Both machines connected to the same backend.

**Comment by Acly** [comment]
Fixed in [1.18.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.1) (probably)
