### ISSUE TITLE
ImportError: Could not find websockets module

### ISSUE THREAD

**Issue by Amsmolfish** [Acly/krita-ai-diffusion#794]
Manual update from 1.17 to 1.18. 
Unable to import/activate the plugin. 
Importing the .zip through kritas import plugin from file tool produces this error:

Failed to fetch display info: "current platform doesn't support fetching display information"
krita.scripting: "Traceback (most recent call last):"
krita.scripting: "  File \"/home/amsmol/.var/app/org.kde.krita/data/krita/pykrita/ai_diffusion/__init__.py\", line 8, in <module>"
krita.scripting: "    raise ImportError("
krita.scripting: "ImportError: Could not find websockets module. This indicates that it was not installed with the plugin. Please make sure to download a plugin release package (NOT just the source!). You can find the latest release package here: https://github.com/Acly/krita-ai-diffusion/releases"
krita.scripting: "Could not import ai_diffusion"
krita.scripting: Error loading plugin "ai_diffusion"

**Comment by Acly** [comment]
1. Make sure you use a release package! https://github.com/Acly/krita-ai-diffusion/releases
2. Try to delete the plugin folder and re-install (see [location](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#where-are-plugin-and-user-files-located))

**Comment by Amsmolfish** [comment]
Complete reinstall did fix.

**Comment by FeepingCreature** [comment]
Future reminder: if you are getting this error as you are trying to set up Krita AI Diffusion from source, make sure to `git submodule update --init` in the AI Diffusion repo.

**Comment by greggh** [comment]
I have this same error, a reinstall did not help. I am using the latest release zip file on a Mac.
