### ISSUE TITLE
Stable Diffusion 3

### ISSUE THREAD

**Issue by CannibalKush** [Acly/krita-ai-diffusion#795]
Is it possible to use the recently released SD3 models with this Krita plugin?

**Comment by olegsatov** [comment]
Not yet, but we hope it will soon)

**Comment by Acly** [comment]
![Screenshot 2024-06-12 174154](https://github.com/Acly/krita-ai-diffusion/assets/6485914/4dd8a771-3848-42fb-bcc7-2e0db81c3d29)

Very much WORK IN PROGRESS, gotta leave now :)
https://github.com/Acly/krita-ai-diffusion/commits/sd3/

**Comment by Serasul1984** [comment]
> ![Screenshot 2024-06-12 174154](https://private-user-images.githubusercontent.com/6485914/339039894-4dd8a771-3848-42fb-bcc7-2e0db81c3d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTA2NDcsIm5iZiI6MTcxODIxMDM0NywicGF0aCI6Ii82NDg1OTE0LzMzOTAzOTg5NC00ZGQ4YTc3MS0zODQ4LTQyZmItYmNjNy0yZTBkYjgxYzNkMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTYzOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVmNGUzYjU4ZmQxMzhlZjBjOWM1YmZiYjYwNzY3OWViMjU4MGI3MDE1ZTBlZDAzYTBhZWY2MzgxMDg5Y2UxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nvQvCv32gVICbueRdguZwi9UUqk40pPJMr-m-9IuyTk)
> 
> Very much WORK IN PROGRESS, but I gotta leave now :) https://github.com/Acly/krita-ai-diffusion/commits/sd3/

i think you dont need to stress out, some people in the stable diffusion discord channel for SD3 pointed out that the model is worse than SD 2.1 they testet out all steps,schedulers and so on, seems like the sd3 models are heavy distilled and censored and even a heavy fine-tuning cant bring it over sdxl quality.  you dont need to believe me but you dont need to make the tool compatible as fast as you can because i trust my source.
most of the trainers looking at https://github.com/PixArt-alpha/PixArt-sigma

**Comment by agoulddesign** [comment]
> i think you dont need to stress out, some people in the stable diffusion discord channel for SD3 pointed out that the model is
> worse than SD 2.1 they testet out all steps,schedulers and so on...

Tips, per Emad:

Sampler: dpmpp_2m (not kararas etc.)
Steps: 32
CFG:  4-6

I think that's what he was addressing anyway.

**Comment by Acly** [comment]
It's actually not that much effort to get the basics working, and that's all SD3 is for now. It will take time to see where the ecosystem settles, took many months for SDXL to get good fine tunes, inpainting, control-net, and all the other stuff the plugin very much depends on.

PixArt Sigma is very interesting too, but I don't think anyone seriously invested yet, because they were holding their breath for SD3. Now we can compare :)

**Comment by moonwhaler** [comment]
The prompt adherence is really good in my experience (using StableSwarmUI/ComfyUI backend). So SD3 does bring something to the table, yet, it's not ready for serious work - as far as my current tests go. So I agree with the current consensus.

**Comment by Sil3ntKn1ght** [comment]
> ![Screenshot 2024-06-12 174154](https://private-user-images.githubusercontent.com/6485914/339039894-4dd8a771-3848-42fb-bcc7-2e0db81c3d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzc0NTAsIm5iZiI6MTcxODIzNzE1MCwicGF0aCI6Ii82NDg1OTE0LzMzOTAzOTg5NC00ZGQ4YTc3MS0zODQ4LTQyZmItYmNjNy0yZTBkYjgxYzNkMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDAwNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhiYzAyYTI1NzQyNjZhYmM1NDMwZDBhOTE2YmQ1ZTFiYjNjMGUxZmZjODFlODI0ODdlZGNmNWQyNWUzYmQ1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AgQtYQ56e_FIJn_T38bpTcW1Ak5DnJKnG8XW7SljaXk)
> 
> Very much WORK IN PROGRESS, but I gotta leave now :) https://github.com/Acly/krita-ai-diffusion/commits/sd3/

Tease lol 
very exciting, you are a legend <3

**Comment by Sil3ntKn1ght** [comment]
> > ![Screenshot 2024-06-12 174154](https://private-user-images.githubusercontent.com/6485914/339039894-4dd8a771-3848-42fb-bcc7-2e0db81c3d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTA2NDcsIm5iZiI6MTcxODIxMDM0NywicGF0aCI6Ii82NDg1OTE0LzMzOTAzOTg5NC00ZGQ4YTc3MS0zODQ4LTQyZmItYmNjNy0yZTBkYjgxYzNkMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTYzOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVmNGUzYjU4ZmQxMzhlZjBjOWM1YmZiYjYwNzY3OWViMjU4MGI3MDE1ZTBlZDAzYTBhZWY2MzgxMDg5Y2UxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nvQvCv32gVICbueRdguZwi9UUqk40pPJMr-m-9IuyTk)
> > Very much WORK IN PROGRESS, but I gotta leave now :) https://github.com/Acly/krita-ai-diffusion/commits/sd3/
> 
> i think you dont need to stress out, some people in the stable diffusion discord channel for SD3 pointed out that the model is worse than SD 2.1 they testet out all steps,schedulers and so on, seems like the sd3 models are heavy distilled and censored and even a heavy fine-tuning cant bring it over sdxl quality. you dont need to believe me but you dont need to make the tool compatible as fast as you can because i trust my source. most of the trainers looking at https://github.com/PixArt-alpha/PixArt-sigma

yer, text is good apparently and its prompt translation, might be finally able to do to character in one prompt, but wont hold my breath. but it has more limb issues. 
but to be fair so did sdxl 1 2 but less than sd1.5, but it was the community that trained and got us where we are, and if the Prompt adherence understanding is there then ill be looking forward to those trainer models that will improve on it, but it may be like sd2 where everyone used sd1.5
bit sdxl3 is important as it will surly have changes and a birth of a new fixed version from feedback in time, so more people using and giving feed back is important.
from a side not in krita I can see a use case of using sdxl and then say inpaint with sdxl 3 for a sign text things like that where it might have strengths

**Comment by gibru** [comment]
> text is good apparently and its prompt translation

I've been running some tests with text examples. While not perfect, for my work it is good enough already. For instance, neon signs and graffiti work well. Occasionally there's one or two letters too many, but within Krita this can easily be fixed. So in a way it already shows some usefulness as another tool in the toolbox. That being said, initial testing feels more like SD2.5 than SD3. Then again, your mileage may vary.

**Comment by Drakosha405** [comment]
of course, it's good to have SD3 support, but unfortunately at the moment SD3 is losing very much. The anatomy was killed, a cropped model was opened and you just don't see the quality that was presented before. it is unknown what training remains to wait and see when everything is needed (controlnet, hyper and the rest).

There are a lot of negative posts on reddit about SD3, in my opinion, there weren't many of them after XL. yes, there were that XL is heavy, but not about the quality in such quantity as with SD3

**Comment by Drakosha405** [comment]
in my opinion, the biggest problem with SD3 is their policy, which is well described in this video. this can have a very strong impact on development
https://youtu.be/r8oA42saTNI?si=tw09zO7XTmv_t1IE

**Comment by Serasul1984** [comment]
> It's actually not that much effort to get the basics working, and that's all SD3 is for now. It will take time to see where the ecosystem settles, took many months for SDXL to get good fine tunes, inpainting, control-net, and all the other stuff the plugin very much depends on.
> 
> PixArt Sigma is very interesting too, but I don't think anyone seriously invested yet, because they were holding their breath for SD3. Now we can compare :)

seems like sd3 diffusers has many bugs https://github.com/huggingface/diffusers/pulls

**Comment by Acly** [comment]
SD3 is now low-key supported in [v1.19.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.19.0), see release notes on which models you need to put where.

It can be quite good in certain situations. Only the basic features work for now, and it'll stay that way until it becomes clear if the model has a future. There are certainly issues like botched training and unclear license which would need to be sorted out.

The official recommendation was to use tiled upscaling for any resolution > 1024. That could be done automatically, but isn't implemented yet. Mostly because it actually seems to be surprisingly flexible with resolution? In some cases high resolutions do produce some grain/blocky artifacts.
