### ISSUE TITLE
[Bug?] Strange zig-zags in 2d generation

### ISSUE THREAD

**Issue by gergelyszaz** [Acly/krita-ai-diffusion#8]
My 2d images turn out strange using AnimeLineart_v10 and flat2DAnimerge checkpoints. There are duplicated lines, sharp turns and speckles all over the place, basically ruining the output.

I suspect the vae or something else in the workflow.

**Comment by Acly** [comment]
I generated a few images with flat2DAnimerge, and they turned out rather pretty. What are you doing exactly?

VAE override was added in style options, but for me both the default and vae-ft-mse-840000-ema-pruned work fine with this checkpoint.

**Comment by gergelyszaz** [comment]
I'll test it sometime later, must have been my setup then.
- generated a 1024x1024 image
- happened for any input positive and negative prompt
- no lora, controlnet or anything else

**Comment by gergelyszaz** [comment]
It might be what starting image is used at 100% strength

99% is what I would expect, 100% is full of lines (or lines that became something else). It's like an image of a net was the starting point.

### 100% (don't remember which, maybe flat2danimerge) `simple background, one apple`
Another one was just the apple logo, but corrupted.
![one apple](https://github.com/Acly/krita-ai-diffusion/assets/22294122/72cde3a9-dfc6-4a87-b5ba-58995c25e8fd)

### 100% sd1.5 `simple background, one apple`
This is interesting, because the image is not ruined, but got more... woodgrain? Also 2 apples.
![one apple sd15](https://github.com/Acly/krita-ai-diffusion/assets/22294122/e3db4b26-ef05-4b0e-8460-9eb9e727b36f)

### 99% flat2danimerge `simple background, one apple`
How to draw an apple: Step 1: draw a detailed anime girl face with one teeny-tiny apple. Step 2: remove the face
![one apple anime](https://github.com/Acly/krita-ai-diffusion/assets/22294122/3ac89180-48f6-47e4-9569-deab9d427e17)

**Comment by Acly** [comment]
Do you have an active selection? Starting image should have no impact at all if you generate at 100% for the whole canvas. Unless you were to select the whole canvas, in which case it would use the inpaint workflow and probably weird things happen.

In any case I should probably detect select-all and not use a mask...

**Comment by gergelyszaz** [comment]
No selection used previously. The image was a plain white background.
After further experimentation I also noticed that it <100% it still does some thing. Squiggly lines and spots instead of lines.

Like this thing at 70% (this one had an active selection)
![one apple anime selection](https://github.com/Acly/krita-ai-diffusion/assets/22294122/edc9f913-6031-4af8-903f-0986d30ddd51)

It's mostly bad if it's the whole image. Selecting a smaller area makes it a lot better.

(After removing the prompts from the style, no more random anime girl in my juicy apple pictures.)

**Comment by Acly** [comment]
Can you try generating at 768x768? I think it might be related to latent upscale, which doesn't work great for clean lines. I get something similar when I try to reproduce, although nowhere near as bad for some reason.

1024x1024
![apple_1024](https://github.com/Acly/krita-ai-diffusion/assets/6485914/5a16b128-09ae-4600-ba12-8b19fb4a8fd5)

768x768
![apple_768](https://github.com/Acly/krita-ai-diffusion/assets/6485914/6b01ea1f-7fe2-4801-bccf-33cdd332a311)
