### ISSUE TITLE
The issue with using Remove Content is that the modified areas don't match the edges of the original image, despite the feathering being normal.

### ISSUE THREAD

**Issue by kevinwbryant** [Acly/krita-ai-diffusion#802]
![issue](https://github.com/Acly/krita-ai-diffusion/assets/135085430/59e8992b-568d-4e02-8e69-951d34de1f4d)
Every time I use this feature, I encounter this problem. Is there something missing in ComfyUI? I haven't changed anything, and both the software and the version are up to date. This issue suddenly appeared without any warning.
![QQ截图20240613173731](https://github.com/Acly/krita-ai-diffusion/assets/135085430/8739de7a-7b95-45e1-82ae-8688785b7a8d)

**Comment by kevinwbryant** [comment]
![QQ截图20240613174008](https://github.com/Acly/krita-ai-diffusion/assets/135085430/90be44cc-641b-43a4-9f4c-66cbb4d42df1)
This is a screenshot of ComfyUI startup.

**Comment by kevinwbryant** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/135085430/8c8aa250-a396-49c2-8a55-3090d238c7b0)
"How can these two problems be solved? Thank you."

**Comment by Acly** [comment]
Those are not issues, just info. It's working as it should.

Regarding slight color/brightness differences in your image, this can happen, especially in very uniform content like sky. Similar discussion here: https://github.com/Acly/krita-ai-diffusion/issues/662#issuecomment-2092485463
