### ISSUE TITLE
Images are burned

### ISSUE THREAD

**Issue by txirrindulari** [Acly/krita-ai-diffusion#803]
I am using 1.18 over Krita 5.2.2 on Linux and my custom comfyui server.
Every image I can generate inside Krita are burned. I tried different settings and models, but all look similar burned effect. Comfyui is working fine.
Any idea of what could happen?
![Screenshot from 2024-06-13 11-53-56](https://github.com/Acly/krita-ai-diffusion/assets/2056993/e5b59301-ba7b-4a32-a753-0e2764abcfe8)
![Screenshot from 2024-06-13 11-53-01](https://github.com/Acly/krita-ai-diffusion/assets/2056993/315fffe7-a254-430e-ba7a-e24e10107dce)

**Comment by txirrindulari** [comment]
I I don't have a clear conclusion about the error, but it is related to the pixel/inch resolution.
I can generate very large images of 3500x3000 correctly with 72 pixel/inch. Also 1024x1024 100pixel/inch. But sometimes trying a higher/lower range of pixels/inch produces a python error or the image appears burned.
If the ratio of W/H of the canvas to pixel/inch is too large, the image is burned.

Either way, this project is wonderful. Great job, congratulations!! Thank you all

**Comment by Acly** [comment]
I don't have an idea directly. But the pixels/inch doesn't have any impact on generation at all. Only the absolute pixel values matter.

Maybe you can try to [export the workflow](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#comfyui-workflow-export) of an affected image and compare it in ComfyUI directly. It might give a hint?

**Comment by freecoderwaifu** [comment]
The thumbnails look ok, might be an issue with the document's color profile, try setting it to the default or try a different one.

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/d6f07555-9363-4649-b10d-bf8d2ac86eae)
![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/8a8bd8a9-bc86-4d9c-ba91-16f31f3f06b2)
![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/0c1f23c8-f2d4-444c-802f-e2ddf1ed2034)

Could also be the mode the layer is set to, if it's somehow not defaulting to Normal mode. Maybe also check soft proofing isn't on either.

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/ef1e7a23-74ce-4113-93ec-9ffb0fb899c5)

Looks more like a Krita side thing.
