### ISSUE TITLE
Saving file that contains a generated layer with a long name corrupts the file

### ISSUE THREAD

**Issue by billyboy1122** [Acly/krita-ai-diffusion#804]
I've discovered an issue where if you generate a layer that has a long name (i.e the result of using Deep Danbooru to generate a prompt) and then save the image, this corrupts it and is then unable to be opened by Krita or Photoshop. It's definitely caused by the length of the layer name, if you rename the layer to something short before saving, this prevents the image from being corrupted.

**Comment by Acly** [comment]
I can't reproduce this (tried very looong layer names). But putting a cap on how much of the prompt is written to layer names seems like a good idea to me anyway, the full text can still be retrieved from the history.
