### ISSUE TITLE
An error occurred while creating a new document

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#805]
After upgrading to version 1.18, an error occurred when creating a new document, and Krita stuck and closed when adding a region.

![屏幕截图 2024-06-13 184436](https://github.com/Acly/krita-ai-diffusion/assets/25132014/dd252a64-e660-474c-b3cc-109794ba068c)

AttributeError
Python 3.10.7: C:\软件\图形图像\krita 5.3\bin\krita.exe
Thu Jun 13 18:45:19 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py in canvasChanged(self=<ai_diffusion.ui.diffusion.ImageDiffusionWidget object>, canvas=<PyKrita.krita.Canvas object>)
  114     def canvasChanged(self, canvas: krita.Canvas):
  115         if canvas is not None and canvas.view() is not None:
  116             self.update_content()
  117 
  118     def register_model(self, model: Model):
self = <ai_diffusion.ui.diffusion.ImageDiffusionWidget object>
self.update_content = <bound method ImageDiffusionWidget.update_conten...fusion.ui.diffusion.ImageDiffusionWidget object>>

 C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py in update_content(self=<ai_diffusion.ui.diffusion.ImageDiffusionWidget object>)
  121 
  122     def update_content(self):
  123         model = root.model_for_active_document()
  124         connection = root.connection
  125         if model is None or connection.state is not ConnectionState.connected:
model undefined
global root = <ai_diffusion.root.Root object>
root.model_for_active_document = <bound method Root.model_for_active_document of <ai_diffusion.root.Root object>>

 C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\root.py in model_for_active_document(self=<ai_diffusion.root.Root object>)
   49 
   50     def model_for_active_document(self) -> Model | None:
   51         doc = KritaDocument.active()
   52         if doc is None or not doc.is_valid:
   53             return None
doc undefined
global KritaDocument = <class 'ai_diffusion.document.KritaDocument'>
KritaDocument.active = <bound method KritaDocument.active of <class 'ai_diffusion.document.KritaDocument'>>

 C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\document.py in active(cls=<class 'ai_diffusion.document.KritaDocument'>)
  130                 return None
  131             id = doc.rootNode().uniqueId().toString()
  132             return cls._instances.get(id) or KritaDocument(doc)
  133         return None
  134 
cls = <class 'ai_diffusion.document.KritaDocument'>
cls._instances = <WeakValueDictionary>
cls._instances.get = <bound method WeakValueDictionary.get of <WeakValueDictionary>>
id = '{408cc5e1-4296-4bb6-8ce5-83ed70ca9482}'
global KritaDocument = <class 'ai_diffusion.document.KritaDocument'>
doc = <PyKrita.krita.Document object>

 C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\document.py in __init__(self=<ai_diffusion.document.KritaDocument object>, krita_document=<PyKrita.krita.Document object>)
  122         self._poller.start()
  123         self._instances[self._id.toString()] = self
  124         self._layers = LayerManager(krita_document)
  125 
  126     @classmethod
self = <ai_diffusion.document.KritaDocument object>
self._layers = <ai_diffusion.layer.LayerManager object>
global LayerManager = <class 'ai_diffusion.layer.LayerManager'>
krita_document = <PyKrita.krita.Document object>

 C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\layer.py in __init__(self=<ai_diffusion.layer.LayerManager object>, doc=<PyKrita.krita.Document object>)
  319             self._root = Layer(self, root)
  320             self._layers = {self._root.id: self._root}
  321             self._active_id = doc.activeNode().uniqueId()
  322             self.update()
  323             self._timer = QTimer()
self = <ai_diffusion.layer.LayerManager object>
self._active_id undefined
doc = <PyKrita.krita.Document object>
doc.activeNode = <built-in method activeNode of Document object>
).uniqueId undefined
AttributeError: 'NoneType' object has no attribute 'uniqueId'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'uniqueId'",)
    name = 'uniqueId'
    obj = None
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py", line 116, in canvasChanged
    self.update_content()
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py", line 123, in update_content
    model = root.model_for_active_document()
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\root.py", line 51, in model_for_active_document
    doc = KritaDocument.active()
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\document.py", line 132, in active
    return cls._instances.get(id) or KritaDocument(doc)
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\document.py", line 124, in __init__
    self._layers = LayerManager(krita_document)
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\layer.py", line 321, in __init__
    self._active_id = doc.activeNode().uniqueId()
AttributeError: 'NoneType' object has no attribute 'uniqueId'

**Comment by Acly** [comment]
I try to avoid getting into this situation in [1.18.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.1)
But I'm not sure what caused it. This never happened for me so far.
