### ISSUE TITLE
Missing PTH file (Possible Bug) for the hands controlnet using the "Generate control layer from current layer" button.

### ISSUE THREAD

**Issue by Corruptinator** [Acly/krita-ai-diffusion#809]
Just an important FYI, the server was installed on an external hard drive to save space on my PC. Not sure if it's related or not but figure I explain what _could be a bug_:

I experienced an error that occurred while I tried to make a control layer for hands using the generate control layer button, but it resulted in an error message saying a file is missing:

![image](https://github.com/Acly/krita-ai-diffusion/assets/5027750/6f7edc31-97ae-4eff-a3c4-f525ac7c6c05)

`Server execution error: [Errno 2] No such file or directory: 'G:\\KritaAI\\ai_diffusionNEW\\server\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\hr16\\ControNet-HandRefiner-pruned\\.huggingface\\download\\hrnetv2_w64_imagenet_pretrained.pth.41ed675bcd1f4f4b62a49bad64901f08f8b67ed744b715da87738f926dae685c.incomplete`

I did check the folder if the file was there and somehow it isn't

![image](https://github.com/Acly/krita-ai-diffusion/assets/5027750/c749020e-c70c-4ff8-8a01-2aa710cbec0a)

So I searched and downloaded the missing file from the huggingface location:
(https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/blob/main/hrnetv2_w64_imagenet_pretrained.pth)

![image](https://github.com/Acly/krita-ai-diffusion/assets/5027750/7bfaf7cc-9ffe-4e76-b468-f51f5c86b5c0)

Unfortunately, after downloading the missing file and rebooting Krita and the AI plugin, the error message was still there, saying it's still missing. Same example shown in image above.

Could it be that the plugin was looking for an alternate name besides the original filename? Cause there is a syntax limitation of how many characters can fit within, and the missing filename is way too long to rename the file into.

**Comment by Acly** [comment]
These files are automatically downloaded by an extension, the plugin doesn't try to use/find them directly. It looks like something with the download went wrong.

Try putting the file directly in the `hr16/ControlNet-HandRefiner-pruned` folder - not in `.huggingface/download`. The download folder is probably just temporary and can be deleted.

**Comment by Corruptinator** [comment]
I'll definitely test and check to make sure that works!

**Comment by Corruptinator** [comment]
Yup! You were right, it was supposed to be placed in the `hr16/ControlNet-HandRefiner-pruned` folder directly.

No missing file errors occurred and was able to generate the depthmap:

![image](https://github.com/Acly/krita-ai-diffusion/assets/5027750/88da01e0-f6b9-44a8-948f-008d2cc5ea50)

I was thinking maybe the plugin could utilize a _hidden function where it double checks the necessary installed files_ are in place.

Regardless of the slight issue/hinderance, it works!  :)
