### ISSUE TITLE
√ button in [Version 1.18.0] 

### ISSUE THREAD

**Issue by pendave** [Acly/krita-ai-diffusion#810]
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/f9704474-4f78-46b1-b3a7-7d738f0b35ec)
In **[Version 1.18.0]** Live mode when I feel good for the current render result, now I have to add a blank new layer, then to click the √ button to add/copy it to the new layer. 

What is the logic for doing this? I like the way in **[Version 1.17.2]** that no need to manually add a blank new layer.

**Comment by rayn69420** [comment]
yeah it's pretty annoying, cannot even undo that. a switch for this feature would be much appreciated

**Comment by 775229** [comment]
yeah it's pretty annoying, cannot even undo that. a switch for this feature would be much appreciated

**Comment by 775229** [comment]
The good news is that it will be fixed in the next release

**Comment by Acly** [comment]
There's two buttons now in [1.18.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.1)

Replacing content is useful, for small changes, but especially when you have many regions. It would add 1 layer per region every apply making it hard to navigate.
