### ISSUE TITLE
comfy ui installation problems osx

### ISSUE THREAD

**Issue by itchymitchy** [Acly/krita-ai-diffusion#811]
Getting this error when trying to set up local ai server on Sonoma

Failed to download https://github.com/comfyanonymous/ComfyUI/archive/56333d48508f95bdef23870cad3239ba0ebdb8a9.zip: Socket operation timed out

Can anyone advise?

**Comment by Acly** [comment]
Probably same: #681
I have no idea though, something on mac prevents downloads?

**Comment by itchymitchy** [comment]
Solved it - it was Little Snitch blocking a connection.

**Comment by johnnyimm** [comment]
> Solved it - it was Little Snitch blocking a connection.

Hi, how to unblock it? thx!
