### ISSUE TITLE
Queue counter does not reset to zero.

### ISSUE THREAD

**Issue by nakanakapoi** [Acly/krita-ai-diffusion#814]
I'm using a remote server. If I run the generation queue while I'm having a connection problem, the queue will go up but never reset again.  For example, If the current 8 batch is not successful, the next queue will always start from 8 instead of zero. After a while these number accumulates.

Of course, I should fix my unstable connection in the first place, but it would be nice if the counter always reset after each successful connection. The only fix that I know is to restart Krita.

**Comment by rbfbatx** [comment]
I have been experiencing the same issue for quite some time now. It definitely started several releases back. Additionally, I've noticed a new issue where, if I take attention/focus away from the Krita window, it will stop generating.

**Comment by Acly** [comment]
Fixed in [v1.20.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.1)
