### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by 3H4D0W** [Acly/krita-ai-diffusion#816]
I get this error when installing Krita on my computer. What is the problem and how can I solve it? Please help

![Screenshot 2024-06-15 222254](https://github.com/Acly/krita-ai-diffusion/assets/172931995/0bb0170d-3729-41bf-b77a-819915af010c)

**Comment by Acly** [comment]
"No space left on device" - ie. you ran out of disk space on C: or where you want to install

**Comment by 3H4D0W** [comment]
Thank you, I installed it on C disk and the problem was solved.
