### ISSUE TITLE
Issues with Krita Generating Stopping When Switching Windows

### ISSUE THREAD

**Issue by rbfbatx** [Acly/krita-ai-diffusion#817]
I've noticed a new issue where, if I take focus away from the Krita window by clicking or scrolling outside of Krita, it will stop generating. This has never been an issue before the latest release and is particularly annoying because I often work in multiple windows simultaneously. When generating in multiple instances or windows in Krita, if I switch to another instance to prepare a checkpoint or perform another task, the generation process stops. This significantly disrupts my workflow.I did install the pre-released changes for SD3 before installing the current release. Additionally, I created a new Comfy install because my previous setup had gotten quite messy. I'm not sure if this is something I did or if it’s an actual bug.Thank you for looking into this issue.

**Comment by Acly** [comment]
Can't reproduce this. I also often context switch or even minimize, it still continues generation.

Also no idea how a new Comfy install (or anything) would cause this... I mean it would be pretty difficult to pause generation even if I wanted to. Maybe Windows deprioritize the process and some other process is hogging all resources?

**Comment by rbfbatx** [comment]
> Can't reproduce this. I also often context switch or even minimize, it still continues generation.
> 
> Also no idea how a new Comfy install (or anything) would cause this... I mean it would be pretty difficult to pause generation even if I wanted to. Maybe Windows deprioritize the process and some other process is hogging all resources?

I don't think it is that but I haven't been able to play with it anymore. I won't be able to look into it again for a few days. I can try and screen record it then.
