### ISSUE TITLE
Failling to create a local server

### ISSUE THREAD

**Issue by M4l4k4s** [Acly/krita-ai-diffusion#819]
I get stuck at this point:

'ERROR Error during installation: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.

    torch from https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-win_amd64.whl#sha256=bf1438aeb124fc36ae2d6b4b5c76d751d47a9fc3d7b15291b41f0caa8d5bf27b:

        Expected sha256 bf1438aeb124fc36ae2d6b4b5c76d751d47a9fc3d7b15291b41f0caa8d5bf27b

             Got        f35f2b5c671e43a50857b0d854126ce239e78409eb7002d1392005e412110ed4'

**Comment by Acly** [comment]
That shouldn't happen, could be that the file wasn't downloaded properly.

Do you run into the same error when you retry installation?
If it's cached you might have to purge it manually:
```
cd %APPDATA%\krita\ai_diffusion\server\python
python-m pip cache purge
```

**Comment by M4l4k4s** [comment]
I have tried multiple times by reinstalling and completely wiping all related files but no luck. 

The %APPDATA%\krita\ai_diffusion\**server** folder does not exist on my drive since it hasn't been able to complete the installation probably.

Is there anything else I could try?

**Comment by Acly** [comment]
I just put the default server install path, if you chose a different one you need to use that. I think there should be something there if you got to the point where it was downloading python packages, but not 100% sure.

As for the potentially corrupted file causing the problem, it probably lives in pip cache. Hence the idea of purging the cache. But deleting it manually should also work. On my system it's located in `C:\Users\<username>\AppData\Local\pip\cache`

**Comment by M4l4k4s** [comment]
The folder you mentioned in your last reply, worked. It is running fine now.

Thank you very much!
