### ISSUE TITLE
IDEA: Image to Text (Auto prompt)

### ISSUE THREAD

**Issue by b4zz4** [Acly/krita-ai-diffusion#829]
Prompt autogenerator and not prompt.
This is very useful to know that you see clip in the image and be able to modify it.

**Comment by Acly** [comment]
> This is very useful to know that you see clip in the image and be able to modify it.

That's not really how it works.

But there is #372 which is same request I think. The solutions at the time were quite bad. Now you can use Florence-2 maybe, but I haven't tried yet.

**Comment by b4zz4** [comment]
I don't know if it's the same, I think it could generate a text description of the picture given as input.
This is good to understand that it interprets the AI of the image.

Similar: https://huggingface.co/spaces/pharmapsychotic/CLIP-Interrogator

**Comment by b4zz4** [comment]
Similar IDEA for comfyui:

https://github.com/Nuked88/ComfyUI-N-Nodes
