### ISSUE TITLE
Missing Inpaint model: Inpaint model 'default' for All

### ISSUE THREAD

**Issue by oneto8** [Acly/krita-ai-diffusion#831]
![Screenshot 2024-06-18 003345](https://github.com/Acly/krita-ai-diffusion/assets/37242602/f7d4990d-1e4d-4211-9017-ca632e45e7fe)

Downloaded all required models. Couldn't find what default model is asked

**Comment by Acly** [comment]
[MAT_Places512_G_fp16](https://huggingface.co/Acly/MAT/resolve/main/MAT_Places512_G_fp16.safetensors), it's in the [list](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#shared) and the error message...

**Comment by raniaamina** [comment]
hi, it's happen to me, the model MAT_Places512_G_fp16 already exist in the directory but the error still happen

**Comment by Saktawdi** [comment]
I reviewed the project source code and found that this model needs to be placed in the following directory: models/inpaint/. If it doesn't exist, create one.

**Comment by DCinAC** [comment]
placed the model MAT_Places512_G_fp16 in the `models/inpaint/` directory and the error message still persists.

**Comment by DCinAC** [comment]
added `inpaint: models/inpaint` into "extra_model_paths.yaml" in comfyui and all good
