### ISSUE TITLE
Live Drawing Issues Help

### ISSUE THREAD

**Issue by DDZ0920** [Acly/krita-ai-diffusion#833]
Hey everyone,
This plugin is absolutely amazing and super useful! Huge thanks to the developer!
However, I've run into a few issues:

1️⃣Using the 1.5 model + LoRA on a 512x512 canvas works smoothly. However, when I switch to 1024, it needs to "load 1 new model" with every stroke. This significantly slows down the sync rate, making the generation time longer and preventing real-time display.

2️⃣When using the XL model, whether on 512 or 1024, it always shows "loading 1 new model." This really ruins the real-time experience.

Does anyone know why this is happening? Any solutions? Thanks a lot!
<img width="462" alt="企业微信截图_457b4491-ffc2-48f7-974c-e60d8d0646b4" src="https://github.com/Acly/krita-ai-diffusion/assets/131282694/04487624-fd87-4bf5-ac1c-7f158de15821">
<img width="489" alt="企业微信截图_f5525a11-1c25-489e-8ec6-eb281ca3e912" src="https://github.com/Acly/krita-ai-diffusion/assets/131282694/ea049c85-da35-48cc-9ec1-0ae2fb6aa9c8">

**Comment by DDZ0920** [comment]
What I mean is, with every stroke, it needs to load this "model" again, which is a huge waste of time. What exactly is it, and is there any solution?
<img width="443" alt="企业微信截图_a700a95e-b7a4-48d8-a91d-46b1180c42bb" src="https://github.com/Acly/krita-ai-diffusion/assets/131282694/1180d803-20ea-4078-84f4-0a5d3faf31e0">

**Comment by Acly** [comment]
This usually means you don't have enough VRAM to keep everything on the GPU, so it has to load/unload for different parts of the process. And yes that ruins performance.

You can try to override ComfyUI's detected settings by passing `--highvram` for example. But if you don't actually have enough VRAM, it will just crash.
