### ISSUE TITLE
How do I MPS High Watermark Ratio=0.0 WHERE IS THE FILE AND WHICH LINE?

### ISSUE THREAD

**Issue by jinreiyu** [Acly/krita-ai-diffusion#835]
Hello devs,

I get an error when trying to use generative fill and I understand that my M1 8gb doesnt have enough ram but I would still like to try to PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 but I dont know where the file I need to modify is and what line in this mystery file to change. Thank you for your help

Here's the error that I get when I run the generative fill:
![tempImageDsXWIi](https://github.com/Acly/krita-ai-diffusion/assets/36853262/4c15aea2-4aec-42d4-bff5-10724f5be3d8)

Server execution error: MPS backend out of memory (MPS allocated: 6.63 GB, other allocations: 18.84 MB, max allowed: 9.07 CB). Tried to allocate
2.77 GB en private pool. Use
PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for

**Comment by victoraavila** [comment]
Hey! Just went through this issue on vanilla PyTorch.

Run the following in your terminal:
```bash
export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
```

Or just delete it with:
```bash
unset PYTORCH_MPS_HIGH_WATERMARK_RATIO
```
