### ISSUE TITLE
getting error message when trying to apply a generated image to a new layer

### ISSUE THREAD

**Issue by roVer-11** [Acly/krita-ai-diffusion#836]
![Screenshot 2024-06-18 190356](https://github.com/Acly/krita-ai-diffusion/assets/168192280/2d1ca6d6-9456-49a1-be59-c9830377e762)
![Screenshot 2024-06-18 190410](https://github.com/Acly/krita-ai-diffusion/assets/168192280/d5c19b6e-3e12-488f-a538-564db3025499)
![Screenshot 2024-06-18 190420](https://github.com/Acly/krita-ai-diffusion/assets/168192280/cb61a5de-e793-4573-a536-b119716e481e)

after clicking the generated image, this box appears and doesnt let click any generated images to add into layer

**Comment by roVer-11** [comment]
@Acly thanks for the reply, yes it did solve the error box to not appear but still the generated image is not clickable on the 2nd generation i.e. only the first generation automatically gets applied as a new layer, and when i click a few times , the krita application freezes and crashes completely.

**Comment by Acly** [comment]
Is there anything special about your setup, or what you are doing? Does this happen for just a blank file and hitting Generate?

I thought it might just be a timing issue, but sounds like something else is broken. But I don't really have any clues, I wasn't able to reproduce the initial error box either.

**Comment by roVer-11** [comment]
when i generate an image with a prompt, the first image is applied in a layer
when the second image is generated, i cant click the image and it doesnt apply to a new layer
instead it crashes krita a bit later

**Comment by roVer-11** [comment]
v 1.17.2 works perfectly fine in my system, can i use v1.17.2's layer.py in v1.18.1 ?

**Comment by Acly** [comment]
I wasn't able to reproduce the crash. There are a few changes to layer.py in [1.20.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.0) though maybe it helps.

**Comment by roVer-11** [comment]
still on v 1.20.0 its happening
it happens only when i do a 2nd image generation, the krita becomes unresponsive and crashes to desktop
https://github.com/Acly/krita-ai-diffusion/assets/168192280/f8fcd6f0-04f4-436b-b603-9865e290d479

im currently on rtx 2070 super, running on cuda

**Comment by Acly** [comment]
Thanks for the video, it was related to the Flatten Image. Fixed in [v1.20.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.1)
