### ISSUE TITLE
[bug] Control Layers disappear in other condition

### ISSUE THREAD

**Issue by pendave** [Acly/krita-ai-diffusion#839]
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/45833e5a-f06f-4b14-9522-3c2f94ef738f)
I just multiple selected then removed some image layers as the Live Mode on progressing, could it trigger this?
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/50751a57-4eea-470d-8603-febb8428a6a9)

**Comment by Acly** [comment]
I think this is the same as #823, let me know if it still happens in [v1.19.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.19.0)
