### ISSUE TITLE
Cannot recognize IP-Adapter

### ISSUE THREAD

**Issue by Heliddy** [Acly/krita-ai-diffusion#84]
![image](https://github.com/Acly/krita-ai-diffusion/assets/36270952/bb00974f-0fb3-496a-9eee-301c67d656dc)
![image](https://github.com/Acly/krita-ai-diffusion/assets/36270952/526d42a7-3cf6-4d6a-b8a9-e52944ba44ec)

But I clearly have installed IP-Adapter
![image](https://github.com/Acly/krita-ai-diffusion/assets/36270952/3e03edf0-f068-428a-bb11-55e3099b0a05)
![image](https://github.com/Acly/krita-ai-diffusion/assets/36270952/32d4d0b7-e558-490a-9c37-d1e5296416fe)
![image](https://github.com/Acly/krita-ai-diffusion/assets/36270952/653d7d07-89cf-4221-b74c-ca99065ee78c)

**Comment by Happenedtostumblein** [comment]
This will need to be addressed by maintainer(s) but here’s a quick fix if you just want to try it:

Open client.py, search for _find_ip_adapter and replace the return function with a static string. I’m not sure if it’s totally correct, but used the file name and it does work.

**Comment by Acly** [comment]
These are two issues, right? The first one where it doesn't detect the node in your custom installation. It could be too old or failed to load. The plugin specifically queries Comfy for available nodes and checks if "IPAdapterModelLoader" and "IPAdapterApply" are available. If they're present in Comfy Web UI it should work for the plugin too.

**Comment by Happenedtostumblein** [comment]
Oh yeah, two issues, sorry. But maybe related somehow since OP says they definitely have the module installed…and I definitely have the MODELS in the right place.

**Comment by Heliddy** [comment]
Sorry, it turns out that my comfyui version is too old, which caused the nodes "IPAdapterModelLoader" and "IPAdapterApply" in the ip-adapter to be unusable. After updating comfyui, the problem was solved.
