### ISSUE TITLE
Server connection error

### ISSUE THREAD

**Issue by l84928** [Acly/krita-ai-diffusion#848]
When I try to open krita, I get the following error, please help me!
The strange thing is that I don't have any problems using the same URL on other computers.
![photo_2024-06-20_20-52-30](https://github.com/Acly/krita-ai-diffusion/assets/39004400/bd737be4-2f3b-49b2-9f96-1f4fc8310c6c)

**Comment by Sil3ntKn1ght** [comment]
there seems to be a install conflict its only wanting to run from itself and from only 
C:\Users\   \AppData\Roaming\krita\ai_diffusion\server

as my installs all started playing up, i noticed it was seeing the perset dir as a installation

**Comment by Acly** [comment]
It looks like some routing/connectivity issue, I don't think it's related to the plugin.
