### ISSUE TITLE
Somebody made a SDXL Segmentation control net!

### ISSUE THREAD

**Issue by FeepingCreature** [Acly/krita-ai-diffusion#849]
https://huggingface.co/abovzv/sdxl_segmentation_controlnet_ade20k/tree/main

Found it in the comments for https://www.reddit.com/r/StableDiffusion/comments/16nqzzh/is_there_a_segmentation_model_for_sdxl_controlnet/

Do we need anything else to enable support for segmentation layer for SDXL networks?

**Comment by Acly** [comment]
I added it to the search path, it actually works pretty well. 5 GB though... (might be fp32)

**Comment by Acly** [comment]
[v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0) has support for xinsir union CN, which also happens to work pretty well for segmentation. So separate CN is no longer strictly needed (but it still works).
