### ISSUE TITLE
Krita Ai Plugin Error: Connection refused prompt.code=1

### ISSUE THREAD

**Issue by Gemglitch888** [Acly/krita-ai-diffusion#852]
I tried to use the Krita AI plugin on a painting layer, and I got this error. I installed the plugin using a tutorial video. I’m not sure how to code. How can I fix this issue?
![Untitled78_20240620181935](https://github.com/Acly/krita-ai-diffusion/assets/123265696/ab6ba259-dacd-43d0-984c-b59115456834)

**Comment by Gemglitch888** [comment]
I have Krita installed on SSD could this be whats causing the issue?

**Comment by Acly** [comment]
Please check server.log (see [log files](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files)), it looks like it stopped for some reason.

> I have Krita installed on SSD could this be whats causing the issue?

No, it would be strange if you didn't have it installed on a SSD, that's where you normally install things :)

**Comment by Gemglitch888** [comment]
Okay thank you for your help

**Comment by Acly** [comment]
External or not makes no difference, assuming it remains connected and mapped to the same drive. Can't really say more without looking at logs.
