### ISSUE TITLE
Negative prompt disappears

### ISSUE THREAD

**Issue by piotrkucharski** [Acly/krita-ai-diffusion#857]
Krtia-ai-diffusion: 1.18.1
Krita: 5.2.2

Negative prompt box disappears when prompt line count is changed:

![image](https://github.com/Acly/krita-ai-diffusion/assets/5716174/1f1b4f9a-62b3-4b35-83de-3070c38c055a)
![image](https://github.com/Acly/krita-ai-diffusion/assets/5716174/f5b4bd04-c566-41d3-a47f-09bbe3c70a90)

**Comment by Serasul1984** [comment]
negative promt should also have the same line options that positive promt has

**Comment by Acly** [comment]
Fixed in [v1.19.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.19.0)

> negative promt should also have the same line options that positive promt has

Pff you're lucky to have that single line! :P
