### ISSUE TITLE
Not sure how to describe it other than self conflict and wont run suddenly 

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#859]
ok its been running ell for a lomg time in the Pykrita dir
C:\Users\    \AppData\Roaming\krita\pykrita\ai_diffusion\.server
but suddenly not installed and will only allow install into
C:\Users\    \AppData\Roaming\krita\ai_diffusion\server 

I can't even point it to another drive where i have a back up copy of prior versions, and it wont install to a different dir, only allowing 
C:\Users\    \AppData\Roaming\krita\pykrita\ai_diffusion\.server

very odd behaviour

currently reinstalling to the only directory its letting me C:\Users\    \AppData\Roaming\krita\pykrita\ai_diffusion\.server
to see if it will work

![Screenshot 2024-06-22 175915](https://github.com/Acly/krita-ai-diffusion/assets/81461290/f548acff-5baf-4419-95e4-a142102dbd4b)
![Screenshot 2024-06-22 181942](https://github.com/Acly/krita-ai-diffusion/assets/81461290/8325079d-90d3-418d-bb74-01a061f9a2d0)
![Screenshot 2024-06-22 182013](https://github.com/Acly/krita-ai-diffusion/assets/81461290/5c11b95c-b9a1-46cf-8e5f-8a8ed7c43a9d)

**Comment by Sil3ntKn1ght** [comment]
NOTE seems the ai_diffusion folder that was made for our presets is seen as a installation causing this conflict to randomly happen

**Comment by Sil3ntKn1ght** [comment]
![Screenshot 2024-06-22 192618](https://github.com/Acly/krita-ai-diffusion/assets/81461290/907371fb-b998-4f7e-8fef-b5cf4a438d60)

100% conflict

**Comment by Sil3ntKn1ght** [comment]
does it in just .server dir and often auto adds \Comfyui

**Comment by Acly** [comment]
1. Please don't install the server into the plugin folder ( `.../pykrita/ai_diffusion`)
2. Remove the added `\ComfyUI` and it will pick up existing installations (fixed next update)
3. Select an empty folder for new installation works fine for me
