### ISSUE TITLE
[VAE MEMORY ERROR]

### ISSUE THREAD

**Issue by Happenedtostumblein** [Acly/krita-ai-diffusion#86]
Getting this error when running any prompt:

Warning: Ran out of memory when regular decoding, retrying with tiled VAE decoding.

Prompt generates, but seems a little slow.

**Comment by Happenedtostumblein** [comment]
@Acly

**Comment by Acly** [comment]
Comfy has a tiled VAE implementation which it falls back to if the GPU runs out of memory while using the regular VAE. It may be possible and faster to make it use tiled VAE from the start using a command line argument like --lowvram, not sure about this.

**Comment by Happenedtostumblein** [comment]
The issue may have been that setting in Performance tab has to be on Automatic if you’re connecting to an external server, for anyone else who *stumbles* across this thread.

**Comment by kexul** [comment]
I got the same error, any help? I'm connecting to external server and setting the performance to automatic.
