### ISSUE TITLE
Some refinenemts suggestions

### ISSUE THREAD

**Issue by 3blackbar** [Acly/krita-ai-diffusion#860]
When you generate new image - display it, now i have to click on generated image after inpainting, it should be done automatically so newly generated image is shown, this is just adding one more click and it stacks up very quickly and its not intuitive at all, why would i need to see old image after i generated new one ?
Display new images at the top not at the bottom.
Any support for transparency ?

Also please dont ask me to APPLY... whats the point of this? apply all of them automatically! theres not point of this, we can still go to other ones even if we dont apply them.
You are wasting clicks my man.

Were is resolution choice for inpaint? I dont want whatevers default, sometimes i want 1024 and sometimes 640, i want a manual choice.
"**Resolutions**: Work efficiently at any resolution. The plugin will automatically use resolutions appropriate for the AI model, and scale them to fit your image region."

Yyyah... lets... not do this please ? Let us select resolution manually, its not a lot of space , jus 2 boxes.
Either this or auto.
Are You aware of the fact that if you choose by selected region and inpaint - the face that is small will always be shitty and small res ? This is not the way it should work at all. This is because you locked us out of resolution choices, if a head is small that it takes up 100 pixels , i wanna inpatint it at 640x640  (so its detailed ! )and scale down to 100 to fit the image, idefo do not want to inpaint it with 100 pixels over and over getting crap details...  this is huge for inpainting.

With inpainting we actually almost never wanna work on old generated images, we always do things forward -one way, so do autoapply and forget about past gens, they can stay buried below on other layers and thats about it.
The "apply" confirmation is really annoying.
If i dont like new generated pic - i remove layer on my own dont worry.
Actually - id swap apply with delete , so we can delete generated pic fast, but apply needs to go.
Get rid of all unecessary confirmations and clicks - GUIS were invented for a reason - to work faster, and the clicks add to annoyance, especially if they dont change much.
If i apply - ok i can use new img but if i dont then what? Im stuck with old one, and now i have to add even more clicks to remove new image? This is so wrong.

**Comment by arcusmaximus** [comment]
Clicking "Apply" adds a new layer, so it's not something I'd do automatically for every single generated image. I often generate batches of 30 candidates and would rather add one layer that I need than delete 29 layers that I don't.

Concerning resolutions: the plugin does in fact work by upscaling your selection, denoising, and downscaling again. You can see this in the Comfy workflow that it generates, and I do like that it's one less thing I don't have to worry about. That being said, the resolution calculation could maybe use some tweaking: if I inpaint a 272x168 area, it gets denoised at 1304x808, which doesn't use SDXL's preferred dimensions. Indeed, using a square selection (which makes the plugin denoise at 1024x1024) seems to give better results. Maybe the context could be automatically padded?

**Comment by Acly** [comment]
AI generates a lot of crap. I tried a "Discard" workflow (delete unwanted results), it's typicaly no less clicks than the "Apply" workflow. It's also frustrating, you preview image, decide it's no good, click generate to get some more options _-- oops_ it now generates based on the result you didn't like. Click are required to indicate preference one way or another. You get used to it.

> Display new images at the top not at the bottom.

Also tried that, sounds good in theory, really annoying in practise. History constantly rearranges itself as new images finish and require space at the top.

Resolutions: See #294 for reasons why this is a bad idea. It should work the other way round, not downscaling high-res results, but upscaling low-res ones.

**Comment by 3blackbar** [comment]
Ok but you show me examples that have errors and mistakes made by rookies, so you wanna adapt to ignorant ppl or help the ones that actually do job with inpaint ...
What i suggested works for me very well in auto11 , its just i have to go back and forth between paint soft and auto to bring over results and touch up.... then i tried this with hopes it will help me to get job done faster but no... i have to confirm every gen, and then i have to click on the gen cause its not on top at all times... so whats the point of even having any sorting ?

Some stuff does need to be generated at the same res but its not always the case, especially face, also if denoise is low enough - this is non issue, which is why i dont really care the issues rookies have, im way past beyond that.
I care about speed, yeah iud like to autoamtically add new layer with each genreated pic, at least add it as option.
Also exposed resolutions and CFG is a must  along with sampler , especially for turbo models that all work differently some turbos wok best with euler A which is crap with non turbo.
I dont really wanna shjare my workflows much and blabber but i wish we were not treated like dumb kids who can do harm if we have too much access to too many options... but its the case here, why did you hide CFG, resolution and samplers ?
Please bring them back, optionable or not i dont really care, i need the access, currently some models genereate faded results with low contrast without cfg control, this is not for me without cfg, its very basic stuff, how can this be hidden is just beyond me.
The project is handicapped a lot by rookie pandering, i do not like this.MAke some space for advanced users please .

Also i select a face with lasso - do invert , so the face is NOT SELECTED, but when i inpaint - the face is also inpainted , whole 
image is, this is not how it should be.

**Comment by freecoderwaifu** [comment]
Works on my machine.

>why did you hide CFG, resolution and samplers ?

?

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/88b4bc10-5db2-4f78-813b-d29f8fcc535c)

Arrow pointing to option that opens up Notepad

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/d462fe5c-1638-44e1-b286-30f3210086a6)

What to manually add (you like hard mode stuff right?):
https://github.com/Acly/krita-ai-diffusion/wiki/Samplers

Resolution = canvas resolution and resolution multiplier in settings. 

Batches (for inpainting) are also there.

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/9985a528-26e7-441d-b5db-5f6cdb9f25b6)

Inpainting resolution = do Entire image and it should respect the canvas' resolution

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/d06b1257-d7f0-4130-b77f-38e43d0b501f)

You can also change batches here:

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/2d198f9a-14c3-4276-8b1c-c242c539a50b)

Auto apply? Use Live Mode and the Apply button to not spawn multiple layers. Use a regular sampler for it, and it will be the same quality as doing Generate or Refine. Make a dedicated preset for it. 

![image](https://github.com/Acly/krita-ai-diffusion/assets/66507343/90ac44a0-ba9b-4471-be61-f83efc976e11)

The only fair point is an option to order new layers in Generate/Refine from ascending to descending, but even then it's no big deal.

**Comment by 3blackbar** [comment]
Nooo my man! I Want it next to prompt! That was the whole point, i know  you can set single res out there in style settings... this is not really wghat i want, i want x and y.
And i want also cfg, i want also sampler , and i want them all on top of prompt.
Just that and nothing else.
I might frankenstein something with GPT asistance but for you its a piece of cake to include spinboxes

**Comment by Acly** [comment]
Don't hold your breath - all that crap like CFG, Sampler, having to manually adjust steps, resolution, ticking and unticking a million checkboxes in the same patterns over and over. It's a distraction. All of this will go away. 

What you want isn't difficult to implement at all, there's a bunch of plugins and apps before which are basically just lazy A1111 UI copy paste. But that's where we started. There's no value in it, no future, so I'm not interested.

> But realistically, i kinda expected lot of manual controls, cause its krita you know 

Yes Krita is about painting and pixel manipulation on a canvas. Look around. Why should inpaint ultimately have more UI than a brush?

**Comment by 3blackbar** [comment]
well ok man, you do plugin for kids, i look elsewhere

**Comment by freecoderwaifu** [comment]
> Don't hold your breath - all that crap like CFG, Sampler, having to manually adjust steps, resolution, ticking and unticking a million checkboxes in the same patterns over and over. It's a distraction. All of this will go away.

This, all those settings are just due to how UIs adapted to the parameters early on, and it just carried on. Eventually all those parameters will be mostly automatic, there's already automatic CFG for example. It's like still wanting to edit autoexec.bat and IRQs in 2024.

Currently you don't even need a prompt with Live mode either, you can just draw and the AI will still autocomplete mostly coherently whatever you're drawing, depending on the checkpoint and Lora. 

Parameter fidgeting is kind of a meme, ESPECIALLY in an art program where you can just draw what the parameters aren't giving you. All you need is drawing and Refine/Live mode, and their more in depth options when applicable.
