### ISSUE TITLE
SD3 

### ISSUE THREAD

**Issue by Crazysl0th42** [Acly/krita-ai-diffusion#864]
Sd3 medium doesn't show in the list. have the correct file and clips

**Comment by Acly** [comment]
custom comfy? updated custom nodes?

**Comment by Crazysl0th42** [comment]
Sorry about that, I should have given more information I was really sleepy. I'm on a custom comfyui. I made sure to update beforehand as well. If I can provide anything else i'd be glad to help.

**Comment by Acly** [comment]
It is most likely  comfyui-tooling-nodes not latest version (or ComfyUI itself). See if you can check which version you're on (depends a bit on how you update them)

**Comment by Acly** [comment]
If you got them from a ZIP or copied them like you did now, you can't update them via git. That only works if they were installed via git in the first place. ComfyUI Manager uses git. So if you delete and let Manager install them, it should also work for updates in the future.
