### ISSUE TITLE
Existing Comfyui connection and Existing Model folder settings

### ISSUE THREAD

**Issue by cemo702** [Acly/krita-ai-diffusion#868]
Guys i couldnt find a solutuion how to show krita ai that i have a comfyui and over 1 tb models there. i dont wanna copy back and forth everytime. i just updated from 1.17 ---> 1.19 and all gone.
Can you please  explain and make that feature avaliable for newcomers how to show existing models and folders so it didnt install it again

Where to set modelfolders?

**Comment by TCFrancis** [comment]
In the root Directory (D:\ComfyUI\    for me) there is a file called: extra_model_paths.yaml, there you can set extra or external model-folders. 

See extra_model_paths.yaml.example
