### ISSUE TITLE
Krita AI plugin Error during installation: process exited with code 1

### ISSUE THREAD

**Issue by DrakKuba** [Acly/krita-ai-diffusion#870]
Hi, I have a problem with the AI ​​plugin on Krita, I can't install the server for the plugin and I don't know why. I have Krita installed on Linux Ubuntu and I installed everything according to the instructions and nothing... nothing works! Please help. 

![Error](https://github.com/jellyDean/Bowling/assets/173703798/66db0d0e-26b8-4f2f-a304-97b8c0ca5126)

**Comment by Acly** [comment]
Please check [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) file

**Comment by DrakKuba** [comment]
> Please check [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) file

In the client log, it says that I should install python using the command: apt install python3.10-venv
but the terminal tells me: The lock file could not be opened...operation refused
Unable to get dpkg frontend lock.....Are you root?

**Comment by Acly** [comment]
Yes you need root to install packages. Use `su` or install `python3.10-venv` with whatever you usually use to install software packages.

**Comment by DrakKuba** [comment]
Is this Python suitable?
python3.10-venv_3.10.12-1~22.04.3_amd64.deb

**Comment by Acly** [comment]
That should work. You can use 3.11 too if you want a newer version.

**Comment by DrakKuba** [comment]
Okay, and when I install it, it should work? That server installation?
