### ISSUE TITLE
Error when trying to generate a pose control layer:

### ISSUE THREAD

**Issue by Gavin266** [Acly/krita-ai-diffusion#871]
I get this error when trying to generate a pose control layer:
INFO cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:282: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: E:\krita\krita-ai-diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\dw-ll_ucoco_384.onnx in function 'cv::dnn::dnn4_v20240521::ONNXImporter::ONNXImporter'

I'm using a locally managed server on Windows 11 and I'm on ai diffusion 1.19.0. and krita 5.2.2

**Comment by Acly** [comment]
Sounds like there is an issue with this file: E:\krita\krita-ai-diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\dw-ll_ucoco_384.onnx

You can delete it and try again, it will be re-downloaded automatically.

**Comment by katona-zoltan-github** [comment]
I have a similar problem when generating the (control) pose. The described solution does not work. 
It's looking for a D: drive path, but it doesn't exist, it should look for the H: path instead. How can I rewrite it to find it on the right route?
I'm using a locally managed server on Windows 11 and I'm on ai diffusion 1.29.0. (latest version) and krita 5.2.2

Server execution error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:277: error: (-5:Bad argument) Can't read ONNX file: H:\KritaTárhely\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\dw-ll_ucoco_384.onnx in function 'cv::dnn::dnn4_v20240521::ONNXImporter::ONNXImporter'

**Comment by Acly** [comment]
Ignore the D:\ path, it's not relevant. The path of the file comes afterwards (starts with H:\)

**Comment by katona-zoltan-github** [comment]
Ok. But what should i do to make it work?:)

**Comment by Acly** [comment]
Delete the file that it can't read. Try again.
