### ISSUE TITLE
SDXL Workload ERROR : inpaint_v26.fooocus.patch missing, but it is in the folder....

### ISSUE THREAD

**Issue by TCFrancis** [Acly/krita-ai-diffusion#872]
Hi,

when I try to select a SDXL-Model I get the error message: "This is a SD XL checkpoint, but the SD XL workload has not been installed."

Looking into the client.log I see the following error message:

2024-06-24 17:49:16,868 WARNING Missing Inpaint model fooocus_patch for SD XL
2024-06-24 17:49:16,868 INFO -> No model matches search paths: inpaint_v26.fooocus.patch
2024-06-24 17:49:16,868 INFO -> Available models: mat_places512_g_fp16.safetensors, fooocus_inpaint_head.pth

Everything else in the client.log looks fine and good

2024-06-24 17:49:20,926 INFO SD 1.5: supported
2024-06-24 17:49:20,926 INFO SD XL: missing 1 models    <- I suppose it is the "inpaint_v26.fooocus.patch"-Error ???2024-06-24 17:49:20,926 INFO SD 3: supported

But the fun part: I have the "inpaint_v26.fooocus.patch" file in my directory (D:\ComfyUI\models\inpaint)

Running the download_models.py AIO-Model-Download the download srcipt sees the inpaint model...

   ...
   Hyper-SD LoRA (SD1.5): found - skipping
   Hyper-SD LoRA (SDXL): found - skipping
   Fooocus Inpaint: found - skipping
   Fooocus Inpaint: found - skipping
   MAT Inpaint: found - skipping
   Easy Negative: found - skipping
   ...

Edit: Deleting and Re-Downloading of inpaint_v26.fooocus.patch through the download_models.py did not help and did not fix the problem.

Am I missing something?

**Comment by Acly** [comment]
A while back somebody had the same problem, and it turned out there was another custom node which overrides the registered filte extensions. The result is that .patch files are no longer found.

I forgot which node it was and can't find the issue anymore right now, but was something Fooocus related.

**Comment by TCFrancis** [comment]
Thank you for pointing it out, there could be a problem with another conflicting custom node. :)

I just found out in the ComfyUI-Browser-Interface I also can not find the inpaint_v26.fooocus.patch in the INPAINT_LoadFocusInpaint-Node.

I guess I try a Local Server Install out of the Krita AI Plugin. And then going for a hunt to find that other conflicting custom node...

Very good solution by the way to give all the required Install options in the Plugin-UI... Helps with my slow download speed to AIO-Install over night... :)
