### ISSUE TITLE
[improvement] IPAdapter plus update "style transfer precise" and "mad scientist node"

### ISSUE THREAD

**Issue by pendave** [Acly/krita-ai-diffusion#874]
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/c962f5e4-9fee-4f67-a308-a009c38588c8)
https://x.com/cubiq/status/1804914765317214390

https://x.com/cubiq/status/1805281845841477886

I hope to use this new functions in [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) ASAP.

**Comment by Acly** [comment]
Okay it produces slightly different images, but what is the feature here?
