### ISSUE TITLE
host bootstrap.pypa.io  not found

### ISSUE THREAD

**Issue by nickshotxd** [Acly/krita-ai-diffusion#876]
![image](https://github.com/Acly/krita-ai-diffusion/assets/67675424/5fc9cb46-4fb9-4cf6-ab20-f73016f91941)

**Comment by Acly** [comment]
#719 - please don't open new issue

**Comment by nickshotxd** [comment]
> #719 - please don't open new issue

Why?

**Comment by Acly** [comment]
You can provide more information and reopen the old issue if you think there is a problem with the plugin.

But if you cannot connect to https://bootstrap.pypa.io/get-pip.py it is likely a problem with your connection, or a firewall. That's not something I can fix.
