### ISSUE TITLE
Support question; What are the defaults for the style presets?

### ISSUE THREAD

**Issue by HanHeld** [Acly/krita-ai-diffusion#878]
I'm sorry for the obvious question -I keep losing track of and trashing my defaults despite making copies and backups. 

What I'd like to know is;
1)what are the names of the default style presets? I have "cinematic photo","comic and anime" and "digital photo" -are these the defaults?
2)most importantly -what's the default checkpoint for each of the default presets?

Thanks for your help!

**Comment by Acly** [comment]
You can find them here: https://github.com/Acly/krita-ai-diffusion/tree/main/ai_diffusion/styles
Also note that they will be reset whenever you update the plugin. Or you can reset them by copying the files from the release ZIP.
Best to always create your own styles for tweaking.

In Style settings they can be recognized by the filename, eg. "Cinematic Photo (_**built-in**_/cinematic-photo.json)"
