### ISSUE TITLE
[Feature request] Read prompt info from PNG 

### ISSUE THREAD

**Issue by moonwhaler** [Acly/krita-ai-diffusion#880]
I often use A1111 or ComfyUI to generate batches of images and refine them afterwards using Krita (Diffusion). I often need to copy paste info from the initial prompting to Krita. It would be a huge help, if the plugin could somehow grab this info and place it in the (negative) prompt.

**Comment by Acly** [comment]
You mean when opening the PNG as a new document in Krita?

**Comment by Sil3ntKn1ght** [comment]
> You mean when opening the PNG as a new document in Krita?

they want the embedded meta data saved so the prompt etc are in the image, i dont want that. if you ever put it in please give the option to be switched off.

**Comment by moonwhaler** [comment]
> > You mean when opening the PNG as a new document in Krita?
> 
> they want the embedded meta data saved so the prompt etc are in the image, i dont want that. if you ever put it in please give the option to be switched off.

The assumption is correct. Having this with a switch in the settings is also fine. Not sure, if something like this is possible. It's a feature request.

**Comment by Acly** [comment]
> they want the embedded meta data saved so the prompt etc are in the image

That's _not_ what I understood from the request. I thought it was about reading info from PNG other tools wrote.

When opening a PNG as new document it might be possible via the filepath. If you copy-paste it or add as layer in existing document there is not much chance I think, since PNG info isn't available to the plugin in those cases.

**Comment by moonwhaler** [comment]
I am sorry. What you describe is true, but I think we are all on the same level here with other words. It's about PNG files from other tools that I open (as a new document) via the file menu.

**Comment by pendave** [comment]
I always drop the png file to EmEditor or Notepad++ or any text editor to check the embedding info in the image, so simple and conviniet, no need to use other tools online :)

**Comment by moonwhaler** [comment]
> I always drop the png file to EmEditor or Notepad++ or any text editor to check the embedding info in the image, so simple and conviniet, no need to use other tools online :)

There are many roads that lead to rome. :) The tool mentioned in the comment before yours is 100% locally and really convenient, yet it's still 1-2 steps on top of the workflow.

**Comment by moonwhaler** [comment]
@Acly: Thanks for the implementation! Really happy about that. I am no Python coder, but if I read the code snippet correctly, it's implemented without a switch (on/off) in the settings. (for me that's totally fine, but maybe other people might be unhappy about this). Anyways.

**Comment by Acly** [comment]
Pretty sure he was concerned about _export_ of metadata. You can always configure your A1111/Comfy to not write the prompt, then Krita can't read it.

**Comment by moonwhaler** [comment]
Maybe I misunderstood the sentiment. Thanks.

**Comment by Sil3ntKn1ght** [comment]
> Pretty sure he was concerned about _export_ of metadata. You can always configure your A1111/Comfy to not write the prompt, then Krita can't read it.

how do i do that using you install to disable meta data embedding?

**Comment by Acly** [comment]
> how do i do that using your install to disable meta data embedded on saving images from krita AI?

The Krita plugin never saves metadata to images. You only need to disable if you use ComfyUI directly.

> or is your implementation only reading importing into krita from a1111 and others with meta data in images?

Yes, it's only about reading.

**Comment by Acly** [comment]
Done in [1.20.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.0)

**Comment by KuroiMatoO** [comment]
> The Krita plugin never saves metadata to images. You only need to disable if you use ComfyUI directly.
Dumb question but is it possible to save metadata when I export image as png somehow? Right now I have to save image as png and kra to be able to get prompt and other stuff from my older images which is not very convenient.

**Comment by kalle07** [comment]
like 
https://github.com/Acly/krita-ai-diffusion/issues/1225

when I load a PNG with internal information meta-data, as it is created in a1111 or webui or fooocus...
this is immediately displayed in your prompt window ... on the other hand, this is very confusing and unfamiliar if I want to change/inpaint a small part of my image, i must delete it every time the pos and ne prrompt becasue they load automatic ...

it give an option to disable the automatic read of the meta-data ?
