### ISSUE TITLE
The debug workflows are no more parsable by ComfyUI

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#882]
Not sure if the problem is recent, as I could not find any mention to it in the ComfyUI git repository, but the debug `workflow.json` generated by the plugin are no more parsed.

It seems those are using a lightweight / older syntax. I hope it's a bug on ComfyUI side, because it's a pain to debug without this option.

Here is a sample workflow : [workflow.json](https://github.com/user-attachments/files/15995927/workflow.json)

Can anyone try to import it ? On my ComfyUI all the nodes are disconnected, and the various widget values are ignored : 

![workflow](https://github.com/Acly/krita-ai-diffusion/assets/15424198/aa730c3d-2f72-4a13-bdb4-2f87f8d313ab)

**Comment by Acly** [comment]
[I'm not seeing this issue, works as usual.](https://github.com/comfyanonymous/ComfyUI/pull/3876) ?

**Comment by Danamir** [comment]
Yep, updated just now. It's been solved. 😅
