### ISSUE TITLE
Live mode with region maxes out a CPU core even when doing nothing

### ISSUE THREAD

**Issue by arcusmaximus** [Acly/krita-ai-diffusion#883]
When Live mode is active and I have a region layer selected, Krita.exe constantly maxes out a CPU core, even when python.exe (Comfy) sits at 0% and I'm not doing anything. As a result, even moving the brush cursor around the canvas is sluggish. It stops the moment I select a non-region layer - but if I then select the region layer again, it first idles until Comfy is done generating, then goes straight back to loading the core for no discernible reason.

I let it sit for a few minutes but nothing changed, so I assume it's running some kind of endless (polling?) loop.

Using version 1.19.0.

**Comment by Acly** [comment]
Yes it's polling to check for changes, not much I can do about that. It shouldn't use full CPU core though.

Performance when using region is quite bad in current version. I'm working on it, already improved from ~150ms to 20-30ms which isn't noticeable anymore on my system.

**Comment by Acly** [comment]
Should be much better in [1.20.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.0), let me know if it still feels choppy.

**Comment by arcusmaximus** [comment]
It is much better. Thank you!
