### ISSUE TITLE
upscale error , invalid_prompt, message, cannot execute because node ETN_TileLayout does not exist, details node id # 8

### ISSUE THREAD

**Issue by jimmytfc** [Acly/krita-ai-diffusion#884]
having problem with upscale tool
![upsace error](https://github.com/Acly/krita-ai-diffusion/assets/173428229/ba417f4f-84f1-47ea-abec-b591a0abbadd)

version 1.19.0
on rundiffusion server

thanks so much .

**Comment by jimmytfc** [comment]
> bro, how did you solve it?

hey, took some time to test, i didt fix it, i just do not use the refine options under the up scale tab. you can use the generate tab(30%strength) unblur controlnet (medium strength) after you have upscaled. i hope it makes sense .

**Comment by Acly** [comment]
The error indicates `comfyui-tooling-nodes` (custom node) needs to be updated.
