### ISSUE TITLE
SDXL workload has not been installed, ONLY on 1.19.0

### ISSUE THREAD

**Issue by gabrie** [Acly/krita-ai-diffusion#885]
I was using 1.18.1, as you could see in screenshot, SDXL is working.
![Snipaste_2024-06-27_10-17-29](https://github.com/Acly/krita-ai-diffusion/assets/539991/071b1ac8-a02c-40b8-bd55-0bf035edf19c)

Then I updated to 1.19.0, Krita told me, SDXL workload has not been installed.
![Snipaste_2024-06-27_10-18-04](https://github.com/Acly/krita-ai-diffusion/assets/539991/e601785a-1b46-4ec2-ac05-fbe544cffb4b)
![Snipaste_2024-06-27_10-18-24](https://github.com/Acly/krita-ai-diffusion/assets/539991/2e727cf7-3455-47f5-8d19-0c35b61727ba)

I connected to my Comfyui, and Hyper loras are in the right place.
Maybe some things else I need to set?

**Comment by jimmytfc** [comment]
i had same issue, just make sure everything from requirement folder is in the comfy ui folder accordingly.

**Comment by gabrie** [comment]
> i had same issue, just make sure everything from requirement folder is in the comfy ui folder accordingly.

As I mentioned, everything are already in the folder, including 1.19.0 new added Hyper Lora needs. This is why 1.18.1 works totally with the same settings.

**Comment by Danamir** [comment]
Can you check the content of the `%USERPROFILE%\AppData\Roaming\krita\ai_diffusion\logs` log files to see if there are more details on the error ?

**Comment by alicat22** [comment]
I ran into this same issue. The solution came down to checking the `client.log` in the logs folder.
```
2024-06-26 17:19:57,280 INFO SD XL: missing 1 models
```
```
2024-06-26 17:44:16,830 INFO -> No model matches search paths: hyper-sd15-8steps-cfg-lora
```
Turns out, I had `hyper-sd15-8steps--lora` instead of `hyper-sd15-8steps-cfg-lora` which caused that error to appear. Another issue I ran into was symlinks. I made sure to add all paths to the `extra_model_paths.yaml`. Hopefully this helps with troubleshooting!

**Comment by gabrie** [comment]
> I ran into this same issue. The solution came down to checking the `client.log` in the logs folder.
> 
> ```
> 2024-06-26 17:19:57,280 INFO SD XL: missing 1 models
> ```
> 
> ```
> 2024-06-26 17:44:16,830 INFO -> No model matches search paths: hyper-sdxl-8steps-cfg-lora
> ```
> 
> Turns out, I had `hyper-sdxl-8steps-lora` instead of `hyper-sdxl-8steps-cfg-lora` which caused that error to appear. Another issue I ran into was symlinks. I made sure to add all paths to the `extra_model_paths.yaml`. Hopefully this helps with troubleshooting!

Thanks, me too, fixed now!
