### ISSUE TITLE
[Feature request] As the models grow larger, please add support for customizable model paths

### ISSUE THREAD

**Issue by DeXtmL** [Acly/krita-ai-diffusion#892]
(Self-explanatory)

**Comment by Drakosha405** [comment]
How do I share models between another UI and ComfyUI?
See the [Config file](https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example) to set the search paths for models. In the standalone windows build you can find this file in the ComfyUI directory. Rename this file to extra_model_paths.yaml and edit it with your favorite text editor.
