### ISSUE TITLE
error during server startup OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188)

### ISSUE THREAD

**Issue by jimmy-bullard14** [Acly/krita-ai-diffusion#895]
**Hi!

Could you please help with the error during server startup?**

  _File "C:\Users\FirePC\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 254, in <module>

    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))

  File "asyncio\base_events.py", line 649, in run_until_complete

  File "C:\Users\FirePC\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 149, in run

    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())

  File "C:\Users\FirePC\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\server.py", line 649, in start

    await site.start()

  File "C:\Users\FirePC\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\aiohttp\web_runner.py", line 119, in start

    self._server = await loop.create_server(

  File "asyncio\base_events.py", line 1519, in create_server

OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188)_

**I saw common issues section and tried to configure settings file with port changing:**

  _server_arguments: --port 25608
    _server_arguments = Setting(
        "Server Arguments", "", "Additional command line arguments passed to the server"_

**but im still getting the same error. What do i do wrong?**

**Comment by Acly** [comment]
Hm it looks like you changed the source code (.py file)? 
It should be settings.json, usually located in `C:\User\<your-name>\AppData\Roaming\krita\`

You can check the server.log file (same location in the logs folder) if the port change is working, it should be written there.

**Comment by ivans80** [comment]
Not just a port. Localhost, too...For example I had automatic1111 running on local host and different port, and I cannot run ComfyUI until close google chrome tab with automatic1111 and connection fog localhost server
