### ISSUE TITLE
after installing while following the instructions, the option for the AI feature is not shown in the dockers window

### ISSUE THREAD

**Issue by Thexgames1** [Acly/krita-ai-diffusion#896]
im REALLY new to krita and it seems i have done everything right and it still does not work

**Comment by Thexgames1** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/150345514/0ab80199-ec81-4753-af9d-624ff0d500ad)

**Comment by mscailyn2007** [comment]
I've got the same problem, how do I fix it?
