### ISSUE TITLE
UI doesn't mention that Style Prompts support "{prompt}"

### ISSUE THREAD

**Issue by arcusmaximus** [Acly/krita-ai-diffusion#901]
The Style Prompt in the settings currently only allows appending keywords to the prompt. Some models, however, give better results when the keywords are placed in the front - the most well-known example probably being PonyXL with its `score_9, score_8_up, ...` tags.

Please add support for prepended keywords. This could be done by extending the Style Prompt to accept a template such as `score_9, score_8_up, {prompt}` - this is how A1111 does it.

**Comment by Acly** [comment]
> This could be done by extending the Style Prompt to accept a template such as `score_9, score_8_up, {prompt}`

That already works. I think built in styles use it too.

**Comment by arcusmaximus** [comment]
Aha, nice. In that case, please update the UI to inform users this is possible. Right now it doesn't:

![image](https://github.com/Acly/krita-ai-diffusion/assets/133129/3575d732-9141-4902-8b28-45d4f6f79392)

**Comment by christianv78** [comment]
Does the same apply to negative prompts?  Do I use the word "{prompt}" or "{negativeprompt}" or something else...?

**Comment by Acly** [comment]
Works exactly the same, with the same placeholder.

**Comment by christianv78** [comment]
Thanks.  I think there was an example of that in the negative prompt when I first installed, but after I erased it, I could never see the example again.

**Comment by pendave** [comment]
Is {promt} still working in the template settings? I notice it could be removed from some version of [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) so I delete {promt} :(

Please guide me for this confusion. Thanks.

**Comment by Acly** [comment]
Yes it's working.
