### ISSUE TITLE
While Generating Images Error: Connection refused

### ISSUE THREAD

**Issue by 3H4D0W** [Acly/krita-ai-diffusion#908]
I occasionally get this error when creating images. I updated the krita and everything seems to be fine except for this error. How can I solve the problem?
![Screenshot 2024-07-05 153308](https://github.com/Acly/krita-ai-diffusion/assets/172931995/fa5052ac-173c-4614-a825-bb31c8956b71)

**Comment by Acly** [comment]
Not sure, it usually means the server is not running. Does this happen in the middle of work and go away by itself? Or you restart.
Checking [server.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) might help

**Comment by xiaoboelse** [comment]
The same issue, but in the connection settings, it has already been successfully connected
