### ISSUE TITLE
How use existing Comfy installation?

### ISSUE THREAD

**Issue by gerroon** [Acly/krita-ai-diffusion#91]
Hi

The doc mentions using an existing installation of Comfy. I have it  running on another PC. How do I connect it to that one? That would be so great so that I do not have to use the GPu on my main PC.

thanks

**Comment by gerroon** [comment]
@ZaneH 

I have the necessary files but it can't find the model  :( It seems to be there

![image](https://github.com/Acly/krita-ai-diffusion/assets/8519469/a467d674-7811-49f8-a162-5256f8c90b94)

**Comment by ZaneH** [comment]
> @ZaneH
> 
> I have the necessary files but it can't find the model :( It seems to be there

I looks like it might be expecting it in a folder called `SD1.5`

<img width="236" alt="image" src="https://github.com/Acly/krita-ai-diffusion/assets/8400251/8f1d729f-9fa6-4c87-a1dd-7d339c6cd159">

**Comment by gerroon** [comment]
Awesome, thaks.
