### ISSUE TITLE
[Feature Request] Implementation of Tooncrafter AI for animation frame interpolation

### ISSUE THREAD

**Issue by Corruptinator** [Acly/krita-ai-diffusion#911]
This might sound Impossible or a Tall Order to ask but I was wondering if it would be possible to implement the Tooncrafter AI:

https://github.com/ToonCrafter/ToonCrafter

As a feature for the AI Plugin or perhaps a separate plugin.

I imagine the Tooncrafter would make inbetweens for the Krita Animation timeline slightly more approachable to drawing frames. Not as in cutting corners but can output a rough outline of what the inbetween could look like and allow animators to make corrections in the generated frames afterwards.

Figure I ask. Shouldn’t hurt to be curious.

**Comment by Marksusu** [comment]
这是个好提议，并且，Krita 的动画功能太陈旧了，应该向主流视频剪辑软件的方向靠拢，有处理多个音轨的能力，并把原有的故事板、脚本和帧三者的关系理清，整合在同一个时间线面板上操作。
好吧，我也不知道怎样最好，但目前的 Krita 动画实在很落后。哈哈哈

**Comment by Acly** [comment]
It's tracked in #779. I'd like to do more with animation, but no promises. Krita plugin doesn't have good access to animation features (such as they are), I ran into a lot of problems when I tried some initial things.

Closing this until someone works on it.
