### ISSUE TITLE
black ai generative fill 

### ISSUE THREAD

**Issue by Enrico-Milazzo** [Acly/krita-ai-diffusion#913]
hew do you deal when the ai generative fill is totally black ?

**Comment by FeepingCreature** [comment]
You can dump the workflow (it's in the interface settings) and try loading it directly into Comfy. Usually this points at some configuration, code or driver issue on ComfyUI's side or the graphics card's. Any messages in the server output?

**Comment by Enrico-Milazzo** [comment]
> You can dump the workflow (it's in the interface settings) and try loading it directly into Comfy. Usually this points at some configuration, code or driver issue on ComfyUI's side or the graphics card's. Any messages in the server output?

thanks ill try with that. a more in depth look led me to conclude that the problem regard when i try the expand mode in the generative ai. on the server side, i do not have any type of messages. do you know how to solve it ?

**Comment by FeepingCreature** [comment]
No idea, sorry :( Try updating your ComfyUI and all your nodes.

**Comment by Enrico-Milazzo** [comment]
> No idea, sorry :( Try updating your ComfyUI and all your nodes.

how do you dump the workflow ? do you have a guide to update the ComfyUI and  nodes ? thank a lot

**Comment by Acly** [comment]
https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#comfyui-workflow-export

You can share the workflow.json, it might help to fix it if it's not something specfic to your system/hardware.
