### ISSUE TITLE
Plugin is crashing Krita

### ISSUE THREAD

**Issue by pshaddock** [Acly/krita-ai-diffusion#915]
After using "Remove Content" the new layer crashes when you click on it. This occured after upgrading Krita and the AI plugin. Reinstalling everything did not fix the problem. Windows 11 Intel with an rtx4090. Xencelabs medium tablet.

Also defaults to producing a batch of three instead of the default one.

**Comment by Acly** [comment]
What you describe sounds pretty basic and I haven't seen a crash so far. I think we need some more detail what exactly you're doing step by step. Or it might help to share the .kra file with everything set up to produce the crash (assuming it always happens).

> Also defaults to producing a batch of three instead of the default one.

You can change it batch size in performance settings (select custom preset) - the default for 4090 is more than 1
