### ISSUE TITLE
Problems with version 1.20.0

### ISSUE THREAD

**Issue by leodina75** [Acly/krita-ai-diffusion#920]
I already uninstalled and installed again, I ran it on krita 5.2.2 and 5.2.3, always the same thing, anyone with the same problem?

![Captura de tela 2024-07-07 203036](https://github.com/Acly/krita-ai-diffusion/assets/151082273/05a463dd-777f-49d9-a678-0218dbc0819f)

TypeError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Sun Jul  7 20:32:41 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py in update_content(self=<ai_diffusion.ui.diffusion.ImageDiffusionWidget object>)
  126             self._frame.setCurrentWidget(self._welcome)
  127         elif model.workspace is Workspace.generation:
  128             self._generation.model = model
  129             self._frame.setCurrentWidget(self._generation)
  130         elif model.workspace is Workspace.upscaling:
self = <ai_diffusion.ui.diffusion.ImageDiffusionWidget object>
self._generation = <ai_diffusion.ui.generation.GenerationWidget object>
self._generation.model = <ai_diffusion.model.Model object>
model = <ai_diffusion.model.Model object>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\generation.py in model(self=<ai_diffusion.ui.generation.GenerationWidget object>, model=<ai_diffusion.model.Model object>)
  599                 self.generate_button.clicked.connect(model.generate),
  600             ]
  601             self.region_prompt.regions = model.regions
  602             self.custom_inpaint.model = model
  603             self.generate_button.model = model
self = <ai_diffusion.ui.generation.GenerationWidget object>
self.region_prompt = <ai_diffusion.ui.region.RegionPromptWidget object>
self.region_prompt.regions = <ai_diffusion.region.RootRegion object>
model = <ai_diffusion.model.Model object>
model.regions = <ai_diffusion.region.RootRegion object>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in regions(self=<ai_diffusion.ui.region.RegionPromptWidget object>, regions=<ai_diffusion.region.RootRegion object>)
  377             return
  378         self._regions = regions
  379         self._setup_bindings()
  380 
  381     def _setup_bindings(self):
self = <ai_diffusion.ui.region.RegionPromptWidget object>
self._setup_bindings = <bound method RegionPromptWidget._setup_bindings...i_diffusion.ui.region.RegionPromptWidget object>>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in _setup_bindings(self=<ai_diffusion.ui.region.RegionPromptWidget object>)
  387             regions.removed.connect(self._show_inactive_regions),
  388         ]
  389         self._update_active()
  390 
  391     def _update_active(self):
self = <ai_diffusion.ui.region.RegionPromptWidget object>
self._update_active = <bound method RegionPromptWidget._update_active ...i_diffusion.ui.region.RegionPromptWidget object>>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in _update_active(self=<ai_diffusion.ui.region.RegionPromptWidget object>)
  390 
  391     def _update_active(self):
  392         self._setup_region_bindings(self._regions.active_or_root)
  393 
  394     def _setup_region_bindings(self, region: RootRegion | Region | None):
self = <ai_diffusion.ui.region.RegionPromptWidget object>
self._setup_region_bindings = <bound method RegionPromptWidget._setup_region_b...i_diffusion.ui.region.RegionPromptWidget object>>
self._regions = <ai_diffusion.region.RootRegion object>
self._regions.active_or_root = <ai_diffusion.region.RootRegion object>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in _setup_region_bindings(self=<ai_diffusion.ui.region.RegionPromptWidget object>, region=<ai_diffusion.region.RootRegion object>)
  394     def _setup_region_bindings(self, region: RootRegion | Region | None):
  395         region = region or self._regions
  396         self._prompt.region = region
  397         self._control.model = region.control
  398         self._show_inactive_regions()
self = <ai_diffusion.ui.region.RegionPromptWidget object>
self._prompt = <ai_diffusion.ui.region.ActiveRegionWidget object>
self._prompt.region = <ai_diffusion.region.RootRegion object>
region = <ai_diffusion.region.RootRegion object>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in region(self=<ai_diffusion.ui.region.ActiveRegionWidget object>, region=<ai_diffusion.region.RootRegion object>)
  187         if region != self._region:
  188             self._region = region
  189             self._setup_bindings(region)
  190 
  191     def _setup_bindings(self, region: RootRegion | Region | None):
self = <ai_diffusion.ui.region.ActiveRegionWidget object>
self._setup_bindings = <bound method ActiveRegionWidget._setup_bindings...i_diffusion.ui.region.ActiveRegionWidget object>>
region = <ai_diffusion.region.RootRegion object>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in _setup_bindings(self=<ai_diffusion.ui.region.ActiveRegionWidget object>, region=<ai_diffusion.region.RootRegion object>)
  195             self._root = region
  196             self._bindings = [
  197                 bind(region, "positive", self.positive, "text"),
  198                 bind(region, "negative", self.negative, "text"),
  199             ]
global bind = <function bind>
region = <ai_diffusion.region.RootRegion object>
self = <ai_diffusion.ui.region.ActiveRegionWidget object>
self.positive = <ai_diffusion.ui.widget.TextPromptWidget object>

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\properties.py in bind(model=<ai_diffusion.region.RootRegion object>, model_property='positive', widget=<ai_diffusion.ui.widget.TextPromptWidget object>, widget_property='text', mode=<Bind.two_way: 2>)
  103 
  104     # set initial value from model
  105     widget_setter(getattr(model, model_property))
  106 
  107     if mode is Bind.one_way:
widget_setter = <function _setter.<locals>.set_py>
builtingetattr = <built-in function getattr>
model = <ai_diffusion.region.RootRegion object>
model_property = 'positive'

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\properties.py in set_py(value=['31', 0])
  152 def _setter(inst, property: str):
  153     def set_py(value):
  154         setattr(inst, property, value)
  155 
  156     qt_setter_name = f"set{property.capitalize()}"
builtinsetattr = <built-in function setattr>
inst = <ai_diffusion.ui.widget.TextPromptWidget object>
property = 'text'
value = ['31', 0]

 C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\widget.py in text(self=<ai_diffusion.ui.widget.TextPromptWidget object>, value=['31', 0])
  529             return
  530         if self._line_count > 1:
  531             self._multi.setPlainText(value)
  532         else:
  533             self._single.setText(value)
self = <ai_diffusion.ui.widget.TextPromptWidget object>
self._multi = <ai_diffusion.ui.widget.MultiLineTextPromptWidget object>
self._multi.setPlainText = <built-in method setPlainText of MultiLineTextPromptWidget object>
value = ['31', 0]
TypeError: setPlainText(self, str): argument 1 has unexpected type 'list'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("setPlainText(self, str): argument 1 has unexpected type 'list'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\diffusion.py", line 128, in update_content
    self._generation.model = model
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\generation.py", line 601, in model
    self.region_prompt.regions = model.regions
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 379, in regions
    self._setup_bindings()
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 389, in _setup_bindings
    self._update_active()
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 392, in _update_active
    self._setup_region_bindings(self._regions.active_or_root)
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 396, in _setup_region_bindings
    self._prompt.region = region
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 189, in region
    self._setup_bindings(region)
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 197, in _setup_bindings
    bind(region, "positive", self.positive, "text"),
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\properties.py", line 105, in bind
    widget_setter(getattr(model, model_property))
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\properties.py", line 154, in set_py
    setattr(inst, property, value)
  File "C:\Users\55759\AppData\Roaming\krita\pykrita\ai_diffusion\ui\widget.py", line 531, in text
    self._multi.setPlainText(value)
TypeError: setPlainText(self, str): argument 1 has unexpected type 'list'

**Comment by leodina75** [comment]
"When opening images generated by Auto1111 or basic ComfyUI workflows, the prompt is now read from the image"

This is happening with images coming in PNG from comfyUI, it must be this prompt reader, my workflows have an average of 25 to 30 nodes.

**Comment by leodina75** [comment]
![ComfyUI_01983_](https://github.com/Acly/krita-ai-diffusion/assets/151082273/ec546095-7bc9-468c-a28c-a82bdcdcd66d)

**Comment by gmf1982** [comment]
Try updating comfyui-inpaint-nodes

**Comment by Acly** [comment]
> This is happening with images coming in PNG from comfyUI, it must be this prompt reader

Yes it has trouble with the prompt string being constructed from nodes. Fixed in https://github.com/Acly/krita-ai-diffusion/commit/088f0bc06ef19308e37a6a0e38ace22a88c0b3cf (it won't load the prompt, but makes the error go away)

**Comment by leodina75** [comment]
you can also add the node
"Save Image with Generation Metadata" in the ComfyUI workflow, it will generate the necessary metadata.

thanks Acly and gmf1982
