### ISSUE TITLE
Drop down to select preprocessors and controlnet?

### ISSUE THREAD

**Issue by krigeta** [Acly/krita-ai-diffusion#921]
Multiple Controlnet models and preprocessors are available, but the UI should include functionality to allow us to select the desired combination while using this excellent plugin.

**Comment by GeminiSquishGames** [comment]
That maybe what I'm experiencing, as I can't seem to get it to see that I have certain SDXL models but in different Adapter/Diffuser types... Having trouble getting any T2I Adapter plus XL models to work with "Styles" that use XL... I'll just have to use basic ones then.

**Comment by Acly** [comment]
Happy to discuss what the best pre-processors and models are, but I don't intend to just throw dozens of pre-processors & models out there with no guidance, most of which are obscure, obsolete or make no sense to combine in the first place.

**Comment by krigeta** [comment]
> Happy to discuss what the best pre-processors and models are, but I don't intend to just throw dozens of pre-processors & models out there with no guidance, most of which are obscure, obsolete or make no sense to combine in the first place.

there must be a simple and advance controlnet mode where the simple mode is as same as it is right now and in advance section we are able to do things like they are in stable diffusion webUI aka A1111, I hope it is possible.
