### ISSUE TITLE
xinsir AIO controlnet

### ISSUE THREAD

**Issue by mvstrawn** [Acly/krita-ai-diffusion#923]
Hello again! Just want to notify you that xinsir has released an all-in-one controlnet: https://huggingface.co/xinsir/controlnet-union-sdxl-1.0

Probably worth taking a look at integrating. Thanks again for your work!

**Comment by Acly** [comment]
Done, [v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0)
