### ISSUE TITLE
Trouble with Stable Matrix handeld packages/platforms. Requirements not detected by script but are showing as nodes in Comfyui

### ISSUE THREAD

**Issue by GeminiSquishGames** [Acly/krita-ai-diffusion#925]
I'm not sure what causes this but my custom comfyui seems to pick up from the Stability Matrix symlinked folder where I keep all of my models just fine but AI Diffusion doesn't seem to be detecting them. They show up in ComfyUI's... UI and work. I also can get Comfy to use XL ControlNet just fine but AI Diffusion says it's not installed for my Styles that use XL. The script picks up on 1.5 checkpoint based styles just fine. Also while trying to figure this problem out, and what models need to be in the ComfyUI's model folder* I ran into this error a few times when removing the ControlNet Layer in Krita:

```ValueError
Python 3.10.7: D:\Graphics\Krita (x64)\bin\krita.exe
Tue Jul  9 03:41:33 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\lintp\AppData\Roaming\krita\pykrita\ai_diffusion\ui\control.py in remove(self=<ai_diffusion.ui.control.ControlWidget object>)
  204 
  205     def remove(self):
  206         self._control_list.remove(self._control)
  207 
  208     def resizeEvent(self, a0: QResizeEvent | None):
self = <ai_diffusion.ui.control.ControlWidget object>
self._control_list = <ai_diffusion.control.ControlLayerList object>
self._control_list.remove = <bound method ControlLayerList.remove of <ai_diffusion.control.ControlLayerList object>>
self._control = <ai_diffusion.control.ControlLayer object>

 C:\Users\lintp\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in remove(self=<ai_diffusion.control.ControlLayerList object>, control=<ai_diffusion.control.ControlLayer object>)
  182 
  183     def remove(self, control: ControlLayer):
  184         self._layers.remove(control)
  185         self.removed.emit(control)
  186 
self = <ai_diffusion.control.ControlLayerList object>
self._layers = []
self._layers.remove = <built-in method remove of list object>
control = <ai_diffusion.control.ControlLayer object>
ValueError: list.remove(x): x not in list
    __cause__ = None
    __class__ = <class 'ValueError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ValueError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ValueError object>
    __doc__ = 'Inappropriate argument value (of correct type).'
    __eq__ = <method-wrapper '__eq__' of ValueError object>
    __format__ = <built-in method __format__ of ValueError object>
    __ge__ = <method-wrapper '__ge__' of ValueError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ValueError object>
    __gt__ = <method-wrapper '__gt__' of ValueError object>
    __hash__ = <method-wrapper '__hash__' of ValueError object>
    __init__ = <method-wrapper '__init__' of ValueError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ValueError object>
    __lt__ = <method-wrapper '__lt__' of ValueError object>
    __ne__ = <method-wrapper '__ne__' of ValueError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ValueError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ValueError object>
    __repr__ = <method-wrapper '__repr__' of ValueError object>
    __setattr__ = <method-wrapper '__setattr__' of ValueError object>
    __setstate__ = <built-in method __setstate__ of ValueError object>
    __sizeof__ = <built-in method __sizeof__ of ValueError object>
    __str__ = <method-wrapper '__str__' of ValueError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('list.remove(x): x not in list',)
    with_traceback = <built-in method with_traceback of ValueError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\lintp\AppData\Roaming\krita\pykrita\ai_diffusion\ui\control.py", line 206, in remove
    self._control_list.remove(self._control)
  File "C:\Users\lintp\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 184, in remove
    self._layers.remove(control)
ValueError: list.remove(x): x not in list
```

I'm hoping that is related and can help.

*So far the inpainting directory and models are the only ones that absolutely have to be in the ComfyUI folder. Everything else seems to pick up from the symlink folder, but it maybe what is causing the issue with the XL ControlNet models. I have to tinker with the locations to find out more.

PSEDIT: This maybe because the preprocessor and models I have aren't the general ControlNet types but different Diffuser or Adapter types, there is an issue already suggesting support of a wider array of ControlNet, but there is still something fiddly with the deletion of CN layers making that error happen, but I'm not sure what causes it yet.

**Comment by cdmusic2019** [comment]
Maybe you modified the configuration of 'extra_model_paths.yaml'.

**Comment by GeminiSquishGames** [comment]
> Maybe you modified the configuration of 'extra_model_paths.yaml'.

Haven't even touched the temp file for it. Comfy sees them and uses them internally, in it's own UI, as well as the nodes that use them, just fine. I think it's that the plugin doesn't know how to use the non-base trained ones or their nodes, base trained CN XL processors and models are working fine in the plugin, but the ones that are IPAdapter, Lora, or Diffuser, etc. trained are not detected. They tend to be big so I just deleted a lot of the base-trained ones for the other types. Not exactly a big deal to redownload them again I suppose,  but it would be nice to support all types.

**Comment by Acly** [comment]
Control models are matched via file name. You can look up (also modify) the search paths in [resources.py](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py#L786-L829).

Feel free to suggest extensions or different but common file naming conventions. There was also some discussion of allowing search path extensions via separate json, but nobody implemented it so far.

**Comment by GeminiSquishGames** [comment]
Awesome, that works. I probably need to go over all of the code when I have a chance so I don't have to keep bugging you. Then I might be able to contribute, if it's referencing a json to replace or append the values in the string arrays of the script, that should be pretty easy, one just needs the time to put into it. As far as different but common, I'm not sure I would recognize that but I think everything I've got was obtained on huggingface. I probably have far too many actually, but I was going through them and testing the differences and probably wasting time I could be doodling instead. Thank you for your help and great work.

**Comment by Acly** [comment]
Yea there's a lot of options out there, but IMO there's little value in adding them to the UI just because they exist. A lot of them are sidegrades or simply obsolete. Experimenting and figuring out which ones work the best for a given use case is more work, but it's valuable as it saves people time.

Appending some more options to the search path is fine, it essentially increases the chance existing ComfyUI users can use the models they already have. A JSON would allow those same people to customize, and is usually acceptable solution for such users.

Closing this for now, but feel free to reopen/open new one if you decide to work on something.
