### ISSUE TITLE
Apply result to active/new layer sometimes stops working in live mode in a project. See attached project file for possible reproduction.

### ISSUE THREAD

**Issue by GeminiSquishGames** [Acly/krita-ai-diffusion#928]
I don't know what causes it yet, but It's acting a bit ike it did for me before, when I flattened the whole image into a "root Merged" layer, and wouldn't apply any of the live mode results at all, no response. Generate/refine modes are still working. Seems to persist now in this file. I can port my layers to a new project but thought I should send the borked project for investigative purposes. Hopefully you have the same results and even more hopefully it helps to find the issue.

[citybort.zip](https://github.com/user-attachments/files/16146568/citybort.zip)

**Comment by Acly** [comment]
There were some issues with Fill layer and a follow up error, so the file helped! Fixed in [v1.20.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.1)
