### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Bladesh9** [Acly/krita-ai-diffusion#929]
Hello! How do tokens work here? For example, I have 300 free tokens in my account. When they run out, do the tokens reset every month, day, or week? Or maybe the 300 are the only ones you have until you buy more? And in the case of buying 5000 tokens, do they reset, or do I have to buy more when they run out? Thanks.

**Comment by GeminiSquishGames** [comment]
What are you toke'n? We don't need no stinking tokens! But seriously you are either in the wrong place or high, or both. Happens to the best of us. If you need further assistance just ring the bell.🛎

**Comment by Acly** [comment]
Tokens are useful if you don't have a 4090 :)

300 are free, but once spent they don't come back. Same goes for those you buy, they directly pay for a certain amount of compute/images.

**Comment by GeminiSquishGames** [comment]
Oh, I get it... I don't get it. I'm missing something again aren't I? Is this related to the plugin or something else? Do I get tokens for being silly? Do I lose tokens for being a dingus? I apologize for the lack of professionalism I'm contributing to your github, @Acly... 😔

**Comment by XylitolJ** [comment]
@GeminiSquishGames tokens are use in this case:

![image](https://github.com/Acly/krita-ai-diffusion/assets/16879990/1b72d51c-2bbc-4ad5-8ee6-4c7fecc765bf)

![image](https://github.com/Acly/krita-ai-diffusion/assets/16879990/15a68fa5-96d2-47d6-bd5e-33cd59cfec14)

**Comment by GeminiSquishGames** [comment]
Ah, okay! I didn't know there was an official thing. It might have clicked had I made it synonymous with credits in my noggin. I know about other paid things and free like Horde but don't use them for SD. Would be nice to have a 40xx but I only have an RTX 2060 and am very poor so I kind of just forget these things exist and live with what I've got.
