### ISSUE TITLE
Help! why do I need to update every time I open?

### ISSUE THREAD

**Issue by yuzehong1986** [Acly/krita-ai-diffusion#93]
求助！已经全部安装好了，目前用的就是v1.7.1，为什么每次打开都需要更新？
Help! All have been installed. Currently, I am using v1.7.1. Why do I need to update  every time I open ?
![image](https://github.com/Acly/krita-ai-diffusion/assets/14815703/3344703c-a817-4611-9c44-42f379e15c92)

**Comment by Acly** [comment]
This was a bug in the 1.7.1 package. I fixed it yesterday, but if you downloaded before you might see this issue.

You can download again [from here](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.7.1) and overwrite your install. It should fix it (you don't have to download the server again).

Alternatively, you can go to server install path, open `.version` file in a text editor, and change it to `1.7.0`. Restart Krita and it will no longer try to update.

**Comment by yuzehong1986** [comment]
thx~
