### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by xanderusa** [Acly/krita-ai-diffusion#930]
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1

thoughts?

**Comment by Acly** [comment]
Well it's a generic "something went wrong" error, so not  a whole lot of thoughts :)

Might be able to tell more with the [server.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files). But usually CUDA errors boil down to unsupported (too old) GPU or graphics drivers.
