### ISSUE TITLE
Updating to 1.20 - "Error: cannot unpack non-iterable Mask object"

### ISSUE THREAD

**Issue by skyv195** [Acly/krita-ai-diffusion#934]
I am trying to do a Generative Fill on an image (Cinematic Photo) but making a selection. But I get this error. I did not have it before 1.20. Where did I go wrong? Appreciate the help. Thank you.

**Comment by Acly** [comment]
Sounds like it might be a bug, but need a bit more information:
* Are you using managed server install or custom ComfyUI?
* Please provide [log files](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) (and console output if you run ComfyUI manually)
