### ISSUE TITLE
'TypeError:..' while installing plugin

### ISSUE THREAD

**Issue by anagilabs** [Acly/krita-ai-diffusion#94]
I get this error while installing: 

krita.scripting: "Traceback (most recent call last):"
krita.scripting: "  File \"C:\\Users\\user\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\__init__.py\", line 22, in <module>"
krita.scripting: "    from .extension import AIToolsExtension"
krita.scripting: "  File \"C:\\Users\\user\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\extension.py\", line 12, in <module>"
krita.scripting: "    class AIToolsExtension(Extension):"
krita.scripting: "  File \"C:\\Users\\user\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\extension.py\", line 13, in AIToolsExtension"
krita.scripting: "    _actions: dict[str, QAction] = {}"
krita.scripting: "TypeError: 'type' object is not subscriptable"
krita.scripting: "Could not import ai_diffusion"
krita.scripting: Error loading plugin "ai_diffusion"

tried, version 1.7.1 and 1.7.0.. will check for olderversion.

**Comment by anagilabs** [comment]
Apparently typeerror is related to older version of python being used in Krita prior to version 5.2.1, after installing new version of Krita 5.2.1, its installing properly..

**Comment by bingling00** [comment]
The problem I encountered seems similar. After installation, I cannot import troch.

I installed version 5.2.1, and he called version 1.9 of Python

**Comment by anagilabs** [comment]
Now, getting comfyui-controlnet-aux error while configuring. couldnot install comfui-controlnet-aux, because of this error: 

AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

any similar experiences, or suggestion on fixing it are most welcome, thanks.

**Comment by ZaneH** [comment]
Did you try this solution: https://github.com/Fannovel16/comfyui_controlnet_aux/issues/60#issuecomment-1735726142?

**Comment by anagilabs** [comment]
Yes, i tried it multiple times over to no avail. however after uninstalling 'Reactor' node, it started working. Also another interesting point is when I install 'comfyui-impact-node' both work, atleast i dont get [IMPORT-FAILED] error..dont know why!
