### ISSUE TITLE
Unable to use Pose controlnet model - setuptools AssertionError

### ISSUE THREAD

**Issue by Pugsworth** [Acly/krita-ai-diffusion#940]
The Pose ControlNet fails to generate "From Image".

Krita Version: 5.2.2
Plugin Version: 1.19.0
Using custom ComfyUI Installation on a separate machine with Nvidia GPU.
I have a bunch of custom nodes as well, but I'm not sure how to isolate only the required nodes for this plugin without losing data/nodes.

What I have attempted to fix:
- Updated ComfyUI to `#f45157e` as well as all of my custom nodes.
- Removed all models from `/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose/` as I saw from #871
- Installed libcublas12 and libcublaslt12 manually through `apt`.
- Installing different setuptools versions (65, 68, 69, 70). Currently on ==69.
- installing/removing `inference` and `inference-gpu` python packages.

This is the output from ComfyUI when I press the "From Image" button.
( unrelated paths are obfuscated with <path> and <path2> )
```
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_path is <path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose/yolox_l.onnx
model_path is <path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose/dw-ll_ucoco_384.onnx

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
2024-07-11 14:48:06.262238487 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

DWPose: Caching ONNXRuntime session dw-ll_ucoco_384.onnx...
2024-07-11 14:48:06.731873941 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

!!! Exception during processing!!! <path2>/Python310/lib/python3.10/distutils/core.py
Traceback (most recent call last):
  File "<<path>/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "<<path>/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "<<path>/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "<<path>/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "<<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 87, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
  File "<<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "<<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 83, in func
    pose_img, openpose_dict = model(image, **kwargs)
  File "<<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 262, in __call__
    poses = self.detect_poses(input_image)
  File "<<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 252, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "<<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/wholebody.py", line 80, in __call__
    import torch.utils.benchmark.utils.timer as torch_timer
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/benchmark/__init__.py", line 2, in <module>
    from torch.utils.benchmark.utils.timer import *  # noqa: F403
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 8, in <module>
    from torch.utils.benchmark.utils import common, cpp_jit
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/benchmark/utils/cpp_jit.py", line 13, in <module>
    from torch.utils import cpp_extension
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 9, in <module>
    import setuptools
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 91, in do_override
    ensure_local_distutils()
  File "<<path>/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 78, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: <path2>/Python310/lib/python3.10/distutils/core.py

Prompt executed in 1.08 seconds
```

In troubleshooting, I seemed to have solved the "libcublas*" errors at the top. This is probably one or both of the `inference` python package stuff or from manually installing the `libcublas*` packages from `apt`. Either way, the result is the same with slightly different line numbers.

```
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_path is <path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose/yolox_l.onnx
model_path is <path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose/dw-ll_ucoco_384.onnx

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
DWPose: Caching OpenCV DNN module yolox_l.onnx on cv2.DNN...
DWPose: Caching OpenCV DNN module dw-ll_ucoco_384.onnx on cv2.DNN...
!!! Exception during processing!!! <path2>/Python310/lib/python3.10/distutils/core.py
Traceback (most recent call last):
  File "<path>/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "<path>/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "<path>/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "<path>/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 87, in estimate_pose
    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
  File "<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 85, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
  File "<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 83, in func
    pose_img, openpose_dict = model(image, **kwargs)
  File "<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 262, in __call__
    poses = self.detect_poses(input_image)
  File "<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 252, in detect_poses
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "<path>/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/wholebody.py", line 80, in __call__
    import torch.utils.benchmark.utils.timer as torch_timer
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/benchmark/__init__.py", line 2, in <module>
    from torch.utils.benchmark.utils.timer import *  # noqa: F403
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 8, in <module>
    from torch.utils.benchmark.utils import common, cpp_jit
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/benchmark/utils/cpp_jit.py", line 13, in <module>
    from torch.utils import cpp_extension
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 9, in <module>
    import setuptools
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "<path>/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: <path2>/Python310/lib/python3.10/distutils/core.py

Prompt executed in 0.59 seconds
```

**Comment by Pugsworth** [comment]
I found an issue on the `Fannovel16/comfyui_controlnet_aux` repo that I think finally solved it for me temporarily!
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/299#issuecomment-2072385326
> Try downgrading to: `pip install setuptools==59.8.0`

I did just that and the Pose model works. It's such a lower version that I didn't think it would be error-free. I'll keep testing things to see if anything else broke.

**Comment by Emperor-of-Mankind** [comment]
I have the same issue. tried your solution but did not work. 
but i had it working before. 
im asssuming this is a path problem and a missing files problem, but i dont know how to fix it.

**Comment by Acly** [comment]
My guess would rather be some dependency issue between system packages (eg Debian/Ubuntu hast python3-distutils package) and same package installed via pip, or compatibility with system C/C++ compiler toolchain. This problem pops up in various places that have nothing to do with ComfyUI. I don't know any other ways to fix it either.

**Comment by Pugsworth** [comment]
If it helps, I have a venv for ComfyUI entirely.
However, he's some more information that might be useful for troubleshooting.

OS: Ubuntu 24.04 LTS
**System** python version: **3.10.14**
**venv** python version: **3.10.11**

---

Here's what pip shows for system:
> `pip list`
<details>
<summary>
Python Pip System Packages
</summary>
<pre>
Package                 Version
----------------------- --------------
attrs                   23.2.0
Babel                   2.10.3
bcc                     0.29.1
blinker                 1.7.0
Brlapi                  0.8.5
certifi                 2023.11.17
chardet                 5.2.0
click                   8.1.6
cloud-init              24.1.3
colorama                0.4.6
command-not-found       0.3
configobj               5.0.8
cryptography            41.0.7
cupshelpers             1.0
dbus-python             1.3.2
defer                   1.0.6
distro                  1.9.0
distro-info             1.7+build1
greenlet                3.0.3
gyp                     0.1
httplib2                0.20.4
idna                    3.6
Jinja2                  3.1.2
jsonpatch               1.32
jsonpointer             2.0
jsonschema              4.10.3
language-selector       0.1
launchpadlib            1.11.0
lazr.restfulclient      0.14.6
lazr.uri                1.0.6
louis                   3.29.0
markdown-it-py          3.0.0
MarkupSafe              2.1.5
mdurl                   0.1.2
msgpack                 1.0.3
netaddr                 0.8.0
netifaces               0.11.0
numpy                   1.26.4
oauthlib                3.2.2
olefile                 0.46
pexpect                 4.9.0
pillow                  10.2.0
pip                     24.0
ptyprocess              0.7.0
pycairo                 1.25.1
pycups                  2.0.1
Pygments                2.17.2
PyGObject               3.48.2
PyJWT                   2.7.0
pynvim                  0.5.0
pyparsing               3.1.1
pyrsistent              0.20.0
pyserial                3.5
python-apt              2.7.7+ubuntu1
python-dateutil         2.8.2
python-debian           0.1.49+ubuntu2
python-distutils-extra  3.0
pytz                    2024.1
pyxdg                   0.28
PyYAML                  6.0.1
requests                2.31.0
rich                    13.7.1
screen-resolution-extra 0.0.0
setuptools              68.1.2
six                     1.16.0
systemd-python          235
typing_extensions       4.10.0
ubuntu-drivers-common   0.0.0
ubuntu-pro-client       8001
ufw                     0.36.2
unattended-upgrades     0.1
urllib3                 2.0.7
wadllib                 1.3.6
wheel                   0.42.0
xdg                     5
xkit                    0.0.0
xlrd                    2.0.1
</pre>
</details>

I do notice a **setuptools** version **68**. This might have been accidentally installed globally when troubleshooting.

---

Here's what pip shows for inside the venv:
> `./venv/bin/python -m pip list`
<details>
<summary>
Python Pip venv Packages
</summary>
<pre>
Package                           Version
--------------------------------- --------------------
absl-py                           2.1.0
accelerate                        0.25.0
addict                            2.4.0
aenum                             3.1.15
aiohttp                           3.9.5
aioresponses                      0.7.6
aiosignal                         1.3.1
albumentations                    1.4.7
annotated-types                   0.6.0
antlr4-python3-runtime            4.9.3
anyio                             4.3.0
APScheduler                       3.10.1
async-timeout                     4.0.3
attrs                             23.2.0
audioread                         3.0.1
awscli                            1.33.25
backoff                           2.2.1
blendmodes                        2024.1.1
boto3                             1.34.108
botocore                          1.34.143
cachetools                        5.3.3
certifi                           2024.2.2
cffi                              1.16.0
chardet                           5.2.0
charset-normalizer                3.3.2
click                             8.1.7
clip-interrogator                 0.6.0
cmake                             3.29.2
color-matcher                     0.5.0
colorama                          0.4.4
coloredlogs                       15.0.1
colorlog                          6.8.2
colour-science                    0.4.4
contourpy                         1.2.1
cryptography                      42.0.6
cssselect2                        0.7.0
cstr                              0.1.0
cycler                            0.12.1
Cython                            3.0.0
daltonlens                        0.1.5
dataclasses-json                  0.6.5
ddt                               1.7.2
decorator                         5.1.1
deepdiff                          7.0.1
defusedxml                        0.7.1
Deprecated                        1.2.14
diffusers                         0.29.2
dill                              0.3.8
distro                            1.9.0
docker                            6.1.3
docutils                          0.16
easydict                          1.13
einops                            0.8.0
embreex                           2.17.7.post4
exceptiongroup                    1.2.1
facexlib                          0.3.0
fairscale                         0.4.13
fastapi                           0.110.3
ffmpeg-python                     0.2.0
ffmpy                             0.3.0
filelock                          3.14.0
filterpy                          1.4.5
flatbuffers                       24.3.25
fonttools                         4.51.0
frozenlist                        1.4.1
fsspec                            2024.3.1
ftfy                              6.2.0
future                            1.0.0
fvcore                            0.1.5.post20221221
gitdb                             4.0.11
GitPython                         3.1.43
glcontext                         2.5.0
glfw                              2.7.0
glitch_this                       1.0.3
google-api-core                   2.19.1
google-api-python-client          2.137.0
google-auth                       2.32.0
google-auth-httplib2              0.2.0
google-cloud-core                 2.4.1
google-cloud-storage              2.17.0
google-crc32c                     1.5.0
google-resumable-media            2.7.1
googleapis-common-protos          1.63.2
GPUtil                            1.4.0
h11                               0.14.0
httpcore                          1.0.5
httplib2                          0.22.0
httpx                             0.27.0
huggingface-hub                   0.23.4
humanfriendly                     10.0
idna                              3.7
imageio                           2.34.1
imageio-ffmpeg                    0.4.9
img2texture                       1.0.6
importlib_metadata                7.1.0
inference-cli                     0.9.13
inference-sdk                     0.9.23
iniconfig                         2.0.0
insightface                       0.7.3
iopath                            0.1.10
jax                               0.4.28
jaxlib                            0.4.28
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
jsonschema                        4.22.0
jsonschema-specifications         2023.12.1
kiwisolver                        1.4.5
kornia                            0.7.2
kornia_rs                         0.1.3
lazy_loader                       0.4
librosa                           0.10.2.post1
lightning-utilities               0.11.2
llvmlite                          0.43.0
loguru                            0.7.2
lxml                              5.2.2
mapbox-earcut                     1.0.1
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
marshmallow                       3.21.2
matplotlib                        3.8.4
matrix-client                     0.4.0
mdurl                             0.1.2
mediapipe                         0.10.14
mido                              1.3.2
ml-dtypes                         0.4.0
moderngl                          5.10.0
mpmath                            1.3.0
msgpack                           1.0.8
mss                               9.0.1
multidict                         6.0.5
mypy-extensions                   1.0.0
natsort                           8.4.0
networkx                          3.3
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.4.127
nvidia-nvtx-cu12                  12.1.105
omegaconf                         2.3.0
onediff                           1.0.0
onnx                              1.16.0
onnxruntime                       1.15.1
onnxruntime-gpu                   1.15.1
open-clip-torch                   2.24.0
openai                            1.30.1
opencv-contrib-python             4.10.0.84
opencv-python                     4.8.0.76
opencv-python-headless            4.10.0.84
opt-einsum                        3.3.0
ordered-set                       4.1.0
packaging                         23.2
pandas                            2.2.2
pendulum                          3.0.0
piexif                            1.1.3
pilgram                           1.2.1
pillow                            10.3.0
pip                               24.1.2
pixeloe                           0.0.10
platformdirs                      4.2.1
pluggy                            1.5.0
pooch                             1.8.1
portalocker                       2.8.2
prettytable                       3.10.0
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 6.0.0
proto-plus                        1.24.0
protobuf                          4.25.3
psutil                            5.9.8
PuLP                              2.8.0
py-cpuinfo                        9.0.0
pyasn1                            0.6.0
pyasn1_modules                    0.4.0
pybase64                          1.3.2
pycocoevalcap                     1.2
pycocotools                       2.0.7
pycollada                         0.8
pycparser                         2.22
pydantic                          2.7.1
pydantic_core                     2.18.2
pydot                             2.0.0
PyGithub                          2.3.0
Pygments                          2.18.0
PyJWT                             2.8.0
PyMatting                         1.1.12
PyNaCl                            1.5.0
pynvml                            11.5.0
PyOpenGL                          3.1.7
PyOpenGL-accelerate               3.1.7
pyparsing                         3.1.2
pypng                             0.20220715.0
pytest                            8.2.0
pytest-asyncio                    0.21.1
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-rtmidi                     1.5.8
pytorch-lightning                 2.2.4
pytz                              2024.1
PyWavelets                        1.6.0
PyYAML                            6.0.1
qrcode                            7.4.2
redis                             5.0.4
referencing                       0.35.1
regex                             2024.4.28
rembg                             2.0.56
reportlab                         4.2.0
requests                          2.31.0
requests-toolbelt                 1.0.0
requirements-parser               0.9.0
rf-clip                           1.0
rich                              13.5.2
rich-argparse                     1.4.0
rpds-py                           0.18.0
rsa                               4.7.2
Rtree                             1.2.0
s3transfer                        0.10.1
safetensors                       0.4.3
scikit-image                      0.23.2
scikit-learn                      1.4.2
scipy                             1.13.0
seaborn                           0.13.2
segment-anything                  1.0
Send2Trash                        1.8.3
sentencepiece                     0.2.0
setuptools                        59.8.0
shapely                           2.0.1
simpleeval                        0.9.13
six                               1.16.0
skypilot                          0.5.0
smmap                             5.0.1
sniffio                           1.3.1
sounddevice                       0.4.6
soundfile                         0.12.1
soxr                              0.3.7
spandrel                          0.3.4
starlette                         0.37.2
stereoscopy                       2.0.1
structlog                         24.2.0
supervision                       0.20.0
svg.path                          6.3
svglib                            1.5.1
sympy                             1.12
tabulate                          0.9.0
termcolor                         2.4.0
thop                              0.1.1.post2209072238
threadpoolctl                     3.5.0
tifffile                          2024.5.3
time-machine                      2.14.1
timm                              0.6.13
tinycss2                          1.3.0
tokenizers                        0.19.1
tomli                             2.0.1
torch                             2.3.0+cu121
torchmetrics                      1.4.0.post0
torchsde                          0.2.6
torchvision                       0.18.0+cu121
tqdm                              4.66.4
trampoline                        0.1.2
transformers                      4.41.0
trimesh                           4.3.2
triton                            2.3.0
typer                             0.9.0
types-setuptools                  69.5.0.20240513
typing_extensions                 4.11.0
typing-inspect                    0.9.0
tzdata                            2024.1
tzlocal                           5.2
ultralytics                       8.2.54
ultralytics-thop                  2.0.0
uritemplate                       4.1.1
urllib3                           1.26.18
vhacdx                            0.0.6
vnoise                            0.1.0
wcwidth                           0.2.13
webencodings                      0.5.1
websocket-client                  1.8.0
wheel                             0.43.0
wrapt                             1.16.0
xatlas                            0.0.9
xxhash                            3.4.1
yacs                              0.1.8
yapf                              0.40.2
yarl                              1.9.4
zipp                              3.18.1
zxing-cpp                         2.2.0
</pre>
</details>

---

And here's any python related packages installed as reported via `apt list --installed | grep python`
<details>
<summary>
Python Apt System Packages
</summary>
<pre>
libpython3-dev/noble,now 3.12.3-0ubuntu1 amd64 [installed,automatic]
libpython3-stdlib/noble,now 3.12.3-0ubuntu1 amd64 [installed,automatic]
libpython3.10-minimal/noble,now 3.10.14-1+noble2 amd64 [installed,automatic]
libpython3.10-stdlib/noble,now 3.10.14-1+noble2 amd64 [installed,automatic]
libpython3.12-dev/noble,now 3.12.3-1 amd64 [installed,automatic]
libpython3.12-minimal/noble,now 3.12.3-1 amd64 [installed,automatic]
libpython3.12-stdlib/noble,now 3.12.3-1 amd64 [installed,automatic]
libpython3.12t64/noble,now 3.12.3-1 amd64 [installed,automatic]
python-apt-common/noble,now 2.7.7ubuntu1 all [installed,automatic]
python-babel-localedata/noble,now 2.10.3-3build1 all [installed,automatic]
python3-apport/noble,now 2.28.1-0ubuntu2 all [installed,upgradable to: 2.28.1-0ubuntu3]
python3-apt/noble,now 2.7.7ubuntu1 amd64 [installed,automatic]
python3-aptdaemon.gtk3widgets/noble,now 1.1.1+bzr982-0ubuntu44 all [installed,automatic]
python3-aptdaemon/noble,now 1.1.1+bzr982-0ubuntu44 all [installed,automatic]
python3-attr/noble,now 23.2.0-2 all [installed,automatic]
python3-babel/noble,now 2.10.3-3build1 all [installed,automatic]
python3-blinker/noble,now 1.7.0-1 all [installed,automatic]
python3-bpfcc/noble,now 0.29.1+ds-1ubuntu7 all [installed,automatic]
python3-brlapi/noble,now 6.6-4ubuntu5 amd64 [installed,automatic]
python3-cairo/noble,now 1.25.1-2build2 amd64 [installed,automatic]
python3-certifi/noble,now 2023.11.17-1 all [installed,automatic]
python3-cffi-backend/noble,now 1.16.0-2build1 amd64 [installed,automatic]
python3-chardet/noble,now 5.2.0+dfsg-1 all [installed,automatic]
python3-click/noble,now 8.1.6-2 all [installed,automatic]
python3-colorama/noble,now 0.4.6-4 all [installed,automatic]
python3-commandnotfound/noble,now 23.04.0 all [installed,automatic]
python3-configobj/noble,now 5.0.8-3 all [installed,automatic]
python3-cryptography/noble-updates,noble-security,now 41.0.7-4ubuntu0.1 amd64 [installed,automatic]
python3-cups/noble,now 2.0.1-5build6 amd64 [installed,automatic]
python3-cupshelpers/noble,now 1.5.18-1ubuntu9 all [installed,automatic]
python3-dateutil/noble,now 2.8.2-3ubuntu1 all [installed,automatic]
python3-dbus/noble,now 1.3.2-5build3 amd64 [installed,automatic]
python3-debconf/noble,now 1.5.86ubuntu1 all [installed,automatic]
python3-debian/noble,now 0.1.49ubuntu2 all [installed,automatic]
python3-defer/noble,now 1.0.6-2.1ubuntu1 all [installed,automatic]
python3-dev/noble,now 3.12.3-0ubuntu1 amd64 [installed,automatic]
python3-distro-info/noble,now 1.7build1 all [installed,automatic]
python3-distro/noble,now 1.9.0-1 all [installed,automatic]
python3-distupgrade/noble,now 1:24.04.16 all [installed,upgradable to: 1:24.04.19]
python3-distutils-extra/noble,now 3.0 all [installed]
python3-gdbm/noble,now 3.12.3-0ubuntu1 amd64 [installed,automatic]
python3-gi/noble,now 3.48.2-1 amd64 [installed,automatic]
python3-greenlet/noble,now 3.0.3-0ubuntu5 amd64 [installed,automatic]
python3-httplib2/noble,now 0.20.4-3 all [installed,automatic]
python3-ibus-1.0/noble,now 1.5.29-2 all [installed,automatic]
python3-idna/noble-updates,noble-security,now 3.6-2ubuntu0.1 all [installed,automatic]
python3-jinja2/noble-updates,noble-security,now 3.1.2-1ubuntu1.1 all [installed,automatic]
python3-json-pointer/noble,now 2.0-0ubuntu1 all [installed,automatic]
python3-jsonpatch/noble,now 1.32-3 all [installed,automatic]
python3-jsonschema/noble,now 4.10.3-2ubuntu1 all [installed,automatic]
python3-jwt/noble,now 2.7.0-1 all [installed,automatic]
python3-launchpadlib/noble,now 1.11.0-6 all [installed,automatic]
python3-lazr.restfulclient/noble,now 0.14.6-1 all [installed,automatic]
python3-lazr.uri/noble,now 1.0.6-3 all [installed,automatic]
python3-louis/noble,now 3.29.0-1build1 all [installed,automatic]
python3-markdown-it/noble,now 3.0.0-2 all [installed,automatic]
python3-markupsafe/noble,now 2.1.5-1build2 amd64 [installed,automatic]
python3-mdurl/noble,now 0.1.2-1 all [installed,automatic]
python3-minimal/noble,now 3.12.3-0ubuntu1 amd64 [installed,automatic]
python3-msgpack/noble,now 1.0.3-3build2 amd64 [installed,automatic]
python3-netaddr/noble,now 0.8.0-2ubuntu1 all [installed,automatic]
python3-netifaces/noble,now 0.11.0-2build3 amd64 [installed,automatic]
python3-netplan/noble-updates,noble-security,now 1.0-2ubuntu1.2 amd64 [installed,automatic]
python3-numpy/noble,now 1:1.26.4+ds-6ubuntu1 amd64 [installed,automatic]
python3-oauthlib/noble,now 3.2.2-1 all [installed,automatic]
python3-olefile/noble,now 0.46-3 all [installed,automatic]
python3-opencv/noble,now 4.6.0+dfsg-13.1ubuntu1 amd64 [installed]
python3-pexpect/noble,now 4.9-2 all [installed,automatic]
python3-pil/noble-updates,noble-security,now 10.2.0-1ubuntu1 amd64 [installed,automatic]
python3-pip-whl/noble,now 24.0+dfsg-1ubuntu1 all [installed,automatic]
python3-pip/noble,now 24.0+dfsg-1ubuntu1 all [installed]
python3-pkg-resources/noble,now 68.1.2-2ubuntu1 all [installed,automatic]
python3-problem-report/noble,now 2.28.1-0ubuntu2 all [installed,upgradable to: 2.28.1-0ubuntu3]
python3-ptyprocess/noble,now 0.7.0-5 all [installed,automatic]
python3-pygments/noble,now 2.17.2+dfsg-1 all [installed,automatic]
python3-pynvim/noble,now 0.5.0-1 all [installed,automatic]
python3-pyparsing/noble,now 3.1.1-1 all [installed,automatic]
python3-pyrsistent/noble,now 0.20.0-1build2 amd64 [installed,automatic]
python3-requests/noble,now 2.31.0+dfsg-1ubuntu1 all [installed,automatic]
python3-rich/noble,now 13.7.1-1 all [installed,automatic]
python3-serial/noble,now 3.5-2 all [installed,automatic]
python3-setuptools-whl/noble,now 68.1.2-2ubuntu1 all [installed,automatic]
python3-setuptools/noble,now 68.1.2-2ubuntu1 all [installed,automatic]
python3-six/noble,now 1.16.0-4 all [installed,automatic]
python3-software-properties/noble,now 0.99.48 all [installed,automatic]
python3-speechd/noble,now 0.12.0~rc2-2build3 all [installed,automatic]
python3-sss/noble-updates,noble-security,now 2.9.4-1.1ubuntu6.1 amd64 [installed,automatic]
python3-systemd/noble,now 235-1build4 amd64 [installed,automatic]
python3-typing-extensions/noble,now 4.10.0-1 all [installed,automatic]
python3-tz/noble,now 2024.1-2 all [installed,automatic]
python3-update-manager/noble,now 1:24.04.6 all [installed,automatic]
python3-urllib3/noble,now 2.0.7-1 all [installed,automatic]
python3-venv/noble,now 3.12.3-0ubuntu1 amd64 [installed]
python3-wadllib/noble,now 1.3.6-5 all [installed,automatic]
python3-wheel/noble,now 0.42.0-2 all [installed,automatic]
python3-xdg/noble,now 0.28-2 all [installed,automatic]
python3-xkit/noble,now 0.5.0ubuntu6 all [installed,automatic]
python3-xlrd/noble,now 2.0.1-2 all [installed,automatic]
python3-yaml/noble,now 6.0.1-2build2 amd64 [installed,automatic]
python3.10-minimal/noble,now 3.10.14-1+noble2 amd64 [installed,automatic]
python3.10/noble,now 3.10.14-1+noble2 amd64 [installed]
python3.12-dev/noble,now 3.12.3-1 amd64 [installed,automatic]
python3.12-minimal/noble,now 3.12.3-1 amd64 [installed,automatic]
python3.12-venv/noble,now 3.12.3-1 amd64 [installed,automatic]
python3.12/noble,now 3.12.3-1 amd64 [installed,automatic]
python3/noble,now 3.12.3-0ubuntu1 amd64 [installed]
</pre>
</details>
