### ISSUE TITLE
Region Control

### ISSUE THREAD

**Issue by jccluaviz** [Acly/krita-ai-diffusion#945]
Hi, guys, a pleasure to meet you again.

I've been testing region control.

Found that in most of cases, i need to lower the strength of generation bellow 100%. Any other way, when the strength its 100%, the adherence to the regional prompts its not working like expected.

Is this how it works ? Is this the way to go ?

Many thanks

**Comment by Committing** [comment]
I think this might be that setting?

![Uploading 895d89fa4ce0bc14496ecf67f2d52e3a.png…]()

**Comment by Acly** [comment]
Strength% isn't directly related, it works with all values.

But it doesn't strongly force a certain composition, if you are using it like that on a blank image, it might not work. Depends on how well your bottom/root prompt decribes the entire image, and how likely the model is to generate the desired composition without regions.

For more tricky composition, some approximate painting and lower strength% is a way to make it work. Sketch or other control layer would also be an option and work with 100%.

**Comment by jccluaviz** [comment]
Thank you Acly.

So the bottom/root prompt has to be precise and faithfully represent the concepts and actors of the general image, right?

**Comment by Acly** [comment]
Not precise, but yes all major concepts and actors.

Essentially the root prompt is appended to all the others, and gives them context about the entire image. 

Details only go into the region prompt, to avoid SD mixing them up when they're all merged together.
