### ISSUE TITLE
Allow option to enable a save node in workflow sent to ComfyUI

### ISSUE THREAD

**Issue by sraney** [Acly/krita-ai-diffusion#946]
Would It be possible to add an option to enable mirroring results sent to the "Send Image (WebSocket)" node and pipe it to an additional "Save Image" node? 

 I hacked a forced node in the ai_diffusion/workflow.py  but, that's a mess but works.  

Example workflow generated by my hack.  ( moved the node to make it a bit more presentable.  

![Krita-ComfyUILocalSave](https://github.com/user-attachments/assets/eea5fb5f-8cd2-4fa1-90df-c84939d0d11a)

**Comment by Acly** [comment]
Yes but why? Images are already saved in the document, and doing it this way will give partial / incomplete images for selections.

**Comment by sraney** [comment]
> Yes but why? Images are already saved in the document, and doing it this way will give partial/incomplete images for selections.

Due to how ComfyUI saves the workflow and allows me to rebuild it with a drag and drop back into ComfyUI to see the workflow created.  Currently the 'save workflow' only seems to save the last workflow used.  Also, it allows me to use them outside of Kriata if I need to rebuild or import them into Clip Studio Paint or Inkscape.

**Comment by Acly** [comment]
Problem is it requires to keep all workflows ever created. Unlike most ComfyUI workflows, the plugin's workflow always contain the entire data (all input images full resolution lossless). It eats up lot of memory really fast, for something most people will never access, and even those that do only rarely.

**Comment by asn88** [comment]
I agree, this will really increase memory consumption. Thanks for taking the time to review my idea.
