### ISSUE TITLE
The control layer is not available

### ISSUE THREAD

**Issue by Shock-stcak** [Acly/krita-ai-diffusion#947]
I have downloaded all the relevant models,
![01](https://github.com/user-attachments/assets/c84320d0-d0df-4cec-a625-9893fc3ba96c)
 why is it that I can't use any of the control layers yet.
![01](https://github.com/user-attachments/assets/a3fed5bc-69fd-4ed5-9e82-265457aabee9)

**Comment by Acly** [comment]
You should be able to Generate. But if you are trying to use the preprocessor ("from current Image") those are different models. Usually they are downloaded automatically.

URL + target path for some of them: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/resources.py#L614-L664
I don't have a better list at the moment.
