### ISSUE TITLE
where should "model.safetensors" be saved?

### ISSUE THREAD

**Issue by funkysugar1983** [Acly/krita-ai-diffusion#949]
i'm in China, many sites are blocked. it can't download the model.safetensors file automatically. but i can download it manually. but i don 't know where to locate that file.
![Snipaste_2024-07-16_04-47-35](https://github.com/user-attachments/assets/fecb1242-a8c3-4b71-958d-81a440c2ddd2)

can anyone help? thx a lot.

**Comment by XylitolJ** [comment]
this is default path:
%appdata%\krita\ai_diffusion\server

model will be place in this folder:

%appdata%\krita\ai_diffusion\server\ComfyUI-some_random_characters\models

![image](https://github.com/user-attachments/assets/e3ca6c5b-8c6e-48fa-b952-b1d8bb3c9147)

**Comment by Acly** [comment]
You can follow the [Custom ComfyUI Setup](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#required-models) instructions, it lists how to rename and where files need to be placed in ComfyUI folder.

**Comment by funkysugar1983** [comment]
> this is default path: %appdata%\krita\ai_diffusion\server
> 
> model will be place in this folder:
> 
> %appdata%\krita\ai_diffusion\server\ComfyUI-some_random_characters\models
> 
> ![image](https://private-user-images.githubusercontent.com/16879990/349214696-e3ca6c5b-8c6e-48fa-b952-b1d8bb3c9147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzU2MjAsIm5iZiI6MTcyMTI3NTMyMCwicGF0aCI6Ii8xNjg3OTk5MC8zNDkyMTQ2OTYtZTNjYTZjNWItOGM2ZS00OGZhLWI5NTItYjFkOGJiM2M5MTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA0MDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMmIwMGM5N2NmMTExMzkyNWZmZmIwNDJiYTAyNTQ0ZWE3ZjFlMzNlNjNmZWVlNDE0ZmE4MWZiZGMzNjIwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SJKh8V1fQ0JVQeWxgWEaVizt8gtM5Te5vGc--DuPqTc)
thx for yr reply. but it doesn't help. there's NO "sever" folder in "C:\Users\Administrator\AppData\Roaming\krita\ai_diffusion". even i created the folder manually and placed "model.safetensors" there. it still can't work

**Comment by TiptopFunk** [comment]
please follow the [official guide](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#required-models): this is a clip vision model, you should put it into this path: models/clip_vision/SD1.5

**Comment by Acly** [comment]
Server will be at the path you entered (from your screenshot `H:\Krita (x64)\ComfyUI\ComfyUI`)

**Comment by funkysugar1983** [comment]
> Server will be at the path you entered (from your screenshot `H:\Krita (x64)\ComfyUI\ComfyUI`)

thks. i fixed it by searching the file name here.

**Comment by work9998** [comment]
Would you share the path for downloading "model,safetensors"? Thank you
