### ISSUE TITLE
Can we add a Chinese translation function?

### ISSUE THREAD

**Issue by cornum501109** [Acly/krita-ai-diffusion#952]
Can we add a Chinese translation function? It would make it easier for Chinese users to use, thank you

**Comment by Drakosha405** [comment]
https://github.com/Acly/krita-ai-diffusion/discussions/867

**Comment by cornum501109** [comment]
It worked after I tried it! Thank you so much. I wish Acly could integrate this feature into the built-in app, that would be even better.

**Comment by Acly** [comment]
[v1.21.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.21.0)
