### ISSUE TITLE
segment ,the controlnet model not installed.

### ISSUE THREAD

**Issue by jimmytfc** [Acly/krita-ai-diffusion#955]
may i ask which is the controlnet model used for segment tool? thanks
![image](https://github.com/user-attachments/assets/b91c1084-90a2-450c-a17e-6697e7c84c28)

**Comment by mvstrawn** [comment]
@jimmytfc The file /(krita installation dir)/pykrita/ai_diffusion/resources.py contains urls to download every default model.
