### ISSUE TITLE
ask for help about live paint : could not find lora 'hyper' used by sampler

### ISSUE THREAD

**Issue by hanetyb** [Acly/krita-ai-diffusion#957]
could please give some advice its failed to use live paint by SD3, it works at SD1.5. SDXL with hyper-sd
version 1.20.1. 1.20. 1.19.  , it same issue.
Krita 5.2.2 version
CF:2383, update at 19th july 2024
i already update comfyui as well
![图片](https://github.com/user-attachments/assets/2c9e83e8-1492-4cb4-a253-1054deb939b7)

hyper-sd,sdxl model is ready in fold and succesfully at boot.
![图片](https://github.com/user-attachments/assets/c9b254ba-721b-4836-9665-e31439c851ef)

**Comment by GeminiSquishGames** [comment]
AFAIK, SD3 has no LCM/Lightning/Turbo/Hyper yet. SD 1.5 and SDXL each have their own so I would think you'd need the Hyper to be trained with SD3 in mind for it to be useable, same with any lora or training, it only works for the base SD type it was trained for. Given the new licensing stuff for SD3, I don't think people will train as much as it's kind of restrictive officially, but give it time I guess.

**Comment by hanetyb** [comment]
thank you sir. it helped.
