### ISSUE TITLE
Module not loaded

### ISSUE THREAD

**Issue by lonelyman0907** [Acly/krita-ai-diffusion#96]
Hi Acly,

Here's my spec
Win10+Krita 5.2.1+ 4090
The AI Image Diffusion plugin is grey out, when I hover on it, it shows Module not loaded
![image](https://github.com/Acly/krita-ai-diffusion/assets/114672437/c19af7b9-4497-4aba-ba30-0191eda66d5c)

How can I solve it?

Thanks for your contribution!

**Comment by Acly** [comment]
Hi,
this usually happens when you download the source code from GitHub, rather than a [release](https://github.com/Acly/krita-ai-diffusion/releases).

**Comment by lonelyman0907** [comment]
It works!
Thank you for the instant reply!
