### ISSUE TITLE
not a issue but will PixArt models be supported 

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [Acly/krita-ai-diffusion#960]
not a issue but will PixArt models be supported 

im curios to try these new models out, clearly no rush especially when sdxl has come so far.
https://civitai.com/models/573014/900m-pixart-sigma

**Comment by Acly** [comment]
PixArt, AuraFlow, etc. will be supported when they get some more investment.

For now it's better to try them in ComfyUI directly (or A1111 or whatever). Until it's more clear which one will get community support.
