### ISSUE TITLE
Server Execution Error:  No module named ultralytics'

### ISSUE THREAD

**Issue by gurilagardnr** [Acly/krita-ai-diffusion#961]
Fresh Krita install.  Fresh "local server managed by Krita" install.  Selected ALL options.  

The plugin will generate full screen images, but will not do any type of regional or 'live' generation.

I'm an experienced Comfyui user.  I know how to install python packages as it relates to a "non-portable" comfy install, as I don't see a venv folder.  I do not know how to perform this activity with your custom managed server, nor am I clear as to whether I should have to or not.

**Comment by Acly** [comment]
Can you check [server.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files) for the full error? I'm not sure where ultralytics dependency is supposed to come from, it shouldn't be needed.

The managed server on Windows works similar to Comfy portable, ie. brings its own Python. So you'd have to use that python's pip to install packages. But no, you shouldn't have to do that manually.

**Comment by gurilagardnr** [comment]
I...I am very dumb.  My fault, sorry for the time waster.  I wasn't re-selecting a model between restarts.  Doh!

**Comment by Sorry-Im-Stupid** [comment]
I'm getting this now, it was working yesterday. 
I'm trying to use the same comfy install for krita and directly, because I don't have infinite drive space, but is that impossible? Are there modules that will stop it somehow?
Krita shouldn't be trying to load anything it's not using right?
