### ISSUE TITLE
cant find module

### ISSUE THREAD

**Issue by teajay9999999** [Acly/krita-ai-diffusion#966]
when i want to start the server in Krita then it says that the server is not running and i cant do shit against it 

PLS help
![fehler kritta doof](https://github.com/user-attachments/assets/93457bbc-6037-45cb-be0b-222ac6fa7578)

**Comment by Hysocs** [comment]
im having the same issue after updating to 1.20.1 after reinstalling krita

**Comment by nojonsko** [comment]
> im having the same issue after updating to 1.20.1 after reinstalling krita
> 
> the missing dll is present and even reinstalling pytorch manually didnt solve it. im thinking its a pytorch issue maybe
> 
> EDIT: i fixed it by using revo uninstaller and removing all python related and pytorch related programs & files and re-installing them

can you give a more detailed explanation? i have completely uninstalled python 3.12 with revo and reinstalled it. i'm still getting the same error

**Comment by Acly** [comment]
If missing libomp140 dll is the problem, installing tha latest VC redistributable might fix it.

Download X64 installer (from Microsoft): https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

See also https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/10

**Comment by Acly** [comment]
> i have completely uninstalled python 3.12 with revo and reinstalled it. i'm still getting the same error

Note that the plugin installs/uses its own private Python 3.10

**Comment by nojonsko** [comment]
> Note that the plugin installs/uses its own private Python 3.10

understandable, i sort of figured that considering there's quite a few other programs i use that uses it's own bundled python install, but i was grasping at straws from what little context i had from that person's fix

> If missing libomp140 dll is the problem, installing tha latest VC redistributable might fix it.
> 
> Download X64 installer (from Microsoft): https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
> 
> See also https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/10


i have just attempted this, and it hasn't fixed the issue for me. 

[this is my client.log.](https://pastebin.com/DAnwbTeT) i've trimmed it down so it only shows the logs for when i press Launch

![](https://github.com/user-attachments/assets/ffa00a22-f5cb-4274-acaa-aa8716ca269a)
^ and this is a screenshot for what redist i have installed shown through control panel

**Comment by Acly** [comment]
These problems are super annoying to track because Windows doesn't say which particular DLL is missing. You can try with [https://github.com/lucasg/Dependencies](Dependencies) - the dependency tree for fbgemm.dll is actually not that big.
It's how I fixed a similar problem, sometimes it's obvious, sometimes you get a lot of false positives.

**Comment by Hysocs** [comment]
mine broke again after krita restarted and i fixed it this time by just downloading this and placing it in my windows/system32
https://www.dllme.com/dll/files/libomp140_x86_64?sort=upload&arch=0x8664

i think something is deleting the dll, no clue what tho. it seems people are having this issue all over the place.

ive personally been using this krita plugin for months and even using pytorch on my own and have been fin, and then boom its doing this with no changes. so maybe windows is just removing it

**Comment by Acly** [comment]
Yea it's strange it's popping up for a lot of people so suddenly. `libomp140_x86_x64` should definitely be part of the VC++ Redistributable...

**Comment by Acly** [comment]
Hm actually my `fbgemm.dll` is using `VCOMP140.DLL`, not `libomp140_x86_x64.dll` (same library from a different compiler). So not sure it's part of the redistributable after all. 

Is this an issue with pytorch 2.4.0 ?

I still had 2.3.1, official pytorch.org doesn't even list 2.4.0 as stable release yet, but looks like that's what you get now via pip.

After updating to 2.4.0 my `fbgemm.dll` also needs the `libomp140_x86_x64.dll` now. I already had it so I didn't get this issue.

**Comment by meikodunois** [comment]
Same issue, and i can't fix it, i don't find a solution yet. i already installed and reinstalled MS Visual C++ and i can't download the fbgemm.dll, it seems dllme page doesn't work in my country .

**Comment by Acly** [comment]
Closing this, all the info is in #965
