### ISSUE TITLE
Error during server startup WinError 126

### ISSUE THREAD

**Issue by malinik26** [Acly/krita-ai-diffusion#968]
![obrázek_2024-07-24_204459338](https://github.com/user-attachments/assets/abb19f39-2048-4dbb-b3af-237146bf2abe)

hello i have this issue i tried a lot  of fixes but it didnt work. Can someone help mi with this ?

**Comment by The-Echii** [comment]
same....
![image](https://github.com/user-attachments/assets/31715a63-2789-4536-b291-2a900168b8b5)

**Comment by Acly** [comment]
Problem with the latest pytorch version, see #965 #966
