### ISSUE TITLE
slow function in big images

### ISSUE THREAD

**Issue by wilzamguerrero** [Acly/krita-ai-diffusion#971]
Hi, thank you for this amazing tool, i have a problem when i work in a big image for example with model 1.5 and i have for example image of 2000 px works but is slow you can put one option for put one value for example 512 for width and this work for the document in general or the selection and convert temporally for send to comfyui in this proportion, with this the resolution is less but is more fast, is possible to add this option?

**Comment by Acly** [comment]
This exists in Performance settings, it's called "Maximum Pixel Count".

Set the preset to Custom then you can set it to eg. 1 MP. That means everything with more than 1 million pixel (1000x1000) will get downscaled for diffusion. So you can use a high resolution canvas without making everything slow.

Currently 1MP is lowest setting so it doesn't go down to 512, but it should be enough? Some models can't go to lower resolution.
