### ISSUE TITLE
Context option has disappeared

### ISSUE THREAD

**Issue by physeo** [Acly/krita-ai-diffusion#975]
The drop down for selecting the image context is no longer showing. Is there a setting I inadvertently changed that would cause it to go missing? It was there when I first installed, but was gone the next day.

![image](https://github.com/user-attachments/assets/4b653126-0fe5-42a9-8c2e-84911f080449)

**Comment by FeepingCreature** [comment]
Try clicking the empty dropdown on the right? Next to "None"? Maybe it's gotten deselected somehow.

**Comment by Acly** [comment]
Yea I think the drop-down is there, but with a non-existing option pre-selected. So it looks invisible (but you can see the caret). Probably this happens since the last used option is saved now, and if it was a specific layer that doesn't exist in new document you get this issue.

**Comment by physeo** [comment]
> Yea I think the drop-down is there, but with a non-existing option pre-selected. So it looks invisible (but you can see the caret). Probably this happens since the last used option is saved now, and if it was a specific layer that doesn't exist in new document you get this issue.

Ah, I see it, the little chevron on the right. I'll try that when I'm back at my computer and report back. Thanks.

**Comment by physeo** [comment]
You guys were right, the dropdown had an empty value selected. I'll close this. Thanks for the help!

**Comment by Acly** [comment]
Let's leave it open, it's still a bug (should not be empty).
