### ISSUE TITLE
Server execution error: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by yang-77-7** [Acly/krita-ai-diffusion#978]
I have installed this model on my computer, but it cannot recognize it. Please help me！
![QQ截图20240726162258](https://github.com/user-attachments/assets/19002d99-2d63-49ff-a722-0868070898b4)

**Comment by Acly** [comment]
Generate should work, and use your model.

The preprocess (sparkle button) needs a separate model which is downloaded on demand.
https://huggingface.co/depth-anything/Depth-Anything-V2-Base/resolve/main/depth_anything_v2_vitb.pth
to folder `ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/depth-anything/Depth-Anything-V2-Base`
