### ISSUE TITLE
translation the language to zh-cn.json

### ISSUE THREAD

**Issue by syl1130** [Acly/krita-ai-diffusion#979]
Hello Acly @Acly ,

I have translation the language to zh-cn.json. I will send you the translated file as an attachment. Add translations to the updated sections in the future. Thank you for your work.

and the translation of 'off', 'Batches' and 'on' is not displayed. please check this. 

![off-on](https://github.com/user-attachments/assets/af13e34e-ee6d-463e-ba7a-e17605f01916)

![Batches](https://github.com/user-attachments/assets/3db548b4-2bfc-417c-90da-7fba7fc4fc5f)

[zh-cn.json](https://github.com/user-attachments/files/16390668/zh-cn.json)

**Comment by Acly** [comment]
Thanks! I added it to the repository

**Comment by syl1130** [comment]
@Acly  the new translation file 
[zh-cn.json](https://github.com/user-attachments/files/16394683/zh-cn.json)
