### ISSUE TITLE
[Feature request] Negative prompt in live mode

### ISSUE THREAD

**Issue by Muskelmagier** [Acly/krita-ai-diffusion#98]
Hi overall I love the Krita plugin and I now use it nearly for every pic I create.

But there is a problem. in live mode, there are just sometimes things I don't want to have in the picture or i want to specify a concept that has a broad definition and as such I want to tighten the constraints a little more. 

This is somewhat already possible because you can add a Negative prompt into the style preset directly, but in my opinion, it would be better to just do it like in the Generate tab

**Comment by Acly** [comment]
Part of version 1.8.0, uses the existing setting to show negative prompt.
