### ISSUE TITLE
Error when trying to install server

### ISSUE THREAD

**Issue by HoodBlah** [Acly/krita-ai-diffusion#981]
I keep getting this error whenever I try to install the server. It always happens around the time it tries to download pytorch.
![image](https://github.com/user-attachments/assets/f4f54098-c4d2-40e0-bf76-efe5f8ed9f21)
[client.log](https://github.com/user-attachments/files/16391683/client.log)

**Comment by Acly** [comment]
Sorry I missed this. But it looks like internet connection issue. pytorch is ~2GB, need a stable connection.
