### ISSUE TITLE
translation the language to ja.json

### ISSUE THREAD

**Issue by picolet21** [Acly/krita-ai-diffusion#985]
Hello Acly @Acly ,

I translated into ja.json.
Because of the difference in word order between Japanese and English, there are some parts that I did not dare to translate.
I will send you the translated file as an attachment.
Thank you for your work.

[ja.json](https://github.com/user-attachments/files/16392386/ja.json)

**Comment by Acly** [comment]
Thanks! I will add the translation.

> Because of the difference in word order between Japanese and English, there are some parts that I did not dare to translate.

It's a good point, I should use placeholder more instead of assuming object is at the end.

Most cases seem to be error messages which have some extra information at the end (a file, folder, URL, error code). It would probably be okay or even better to translate them without trying to integrate that into the sentence.
For example "Could not connect to websocket server at" -> "Websocketサーバーに接続できませんでした。" (ignoring the "at")

**Comment by picolet21** [comment]
Thanks Acly @Acly ,

I would appreciate it if you could use placeholders for messages that have concatenated text at the end of them.

However, for messages that are output to a log file, it is best not to target them for translation in the first place.
This is because the logs may be submitted to people using other languages.
Therefore, it is better to exclude messages for log output from the template.
Please consider this.

**Comment by Acly** [comment]
The error messages you see in the translation files are all displayed to the user in the UI.

I didn't add the things that are written to the log (although there might be some rare case where it's used for both, have to check that).

**Comment by picolet21** [comment]
> The error messages you see in the translation files are all displayed to the user in the UI.
> 
> I didn't add the things that are written to the log (although there might be some rare case where it's used for both, have to check that).

That was not my understanding and I apologize for that.
I have translated all the untranslated parts and will send you the ja.json.
Best regards.

[ja.json](https://github.com/user-attachments/files/16399065/ja.json)

**Comment by picolet21** [comment]
I have fixed the untranslated parts such as 'Batches'.
I will send you ja.json.

[ja.json](https://github.com/user-attachments/files/16413280/ja.json)

**Comment by Acly** [comment]
Updated, thank you

**Comment by picolet21** [comment]
Hi  Acly @Acly ,

I have added the text regarding tags and will send you the ja.json.
I have also added the NSFW filter options text at the end. This is not in the template, but I added it while I was at it.

[ja.json](https://github.com/user-attachments/files/16560156/ja.json)

**Comment by Acly** [comment]
That was just in time for release! I think everything was merged.
