### ISSUE TITLE
 Regarding the problem that segment cannot working，help！

### ISSUE THREAD

**Issue by kevinwbryant** [Acly/krita-ai-diffusion#987]
I'm glad that you have been updating this very cool project. I have a small problem here. After I run segment, I will be prompted with the following question. It seems that union sdxl cannot work. I also put union-sdxl into the following folder,  I don't know what is something wrong with my settings, thank you
![image](https://github.com/user-attachments/assets/d4598597-cc82-4090-bdcd-1a5da1f04811)
![image](https://github.com/user-attachments/assets/86544c2c-e5fb-45e0-a46b-2a5f3bc41ae8)

![image](https://github.com/user-attachments/assets/389253c6-5c21-4c30-a2ba-dec3e7f2bcad)

![image](https://github.com/user-attachments/assets/662f37aa-fdbb-4df5-b130-00286e118551)

**Comment by Acly** [comment]
There are 2 steps
1. (Optional) generate segment image from current image
2. Generate new image based on segment image

xinsir model is for step 2. it looks like you are asking about step 1? did you try a different image? I don't see any errors, so it's probably working, just not detecting anything to segment in your image.
